### ISSUE TITLE
It takes up to 8 seconds to save in the editor

### ISSUE THREAD

**Issue by fregante** [pixiebrix/pixiebrix-extension#1002]
I can't quite tell what's taking so long, I don't see network requests (maybe I can't find them).

https://user-images.githubusercontent.com/1402241/128514182-ebebdc12-869f-4045-866b-aa1e70d90a75.mov

**Comment by twschiller** [comment]
There's a number of network requests that need to be done in sequence: http://github.com/pixiebrix/pixiebrix-extension/blob/5a30ee652ac6c474deee2f6e5e9f5dbaf3b839d0/src/devTools/editor/hooks/useCreate.ts#L138-L138

2-3 weeks ago I had made all the requests blocking to eliminate some race conditions that were happening on slow computers/networks

There's some blockers in the ticket queue (that I don't have time right now to link to all of them)

**Comment by fregante** [comment]
Makes sense. As a possible related improvement, at least for the first save in some cases, I copy here a request from https://github.com/pixiebrix/pixiebrix-extension/issues/802#issuecomment-881581391:

> Don't make the Save button await the permissions, it should save immediately and request permissions asynchronously.


In short, we can move this out: https://github.com/pixiebrix/pixiebrix-extension/blob/5a30ee652ac6c474deee2f6e5e9f5dbaf3b839d0/src/devTools/editor/hooks/useCreate.ts#L169-L182

Or just no `await` it:

```ts
        void ensurePermissions(element, addToast).catch((error: unknown) => {
          // Continue to allow saving (because there's a workaround)
          reportError(error);
          console.error("Error checking/enabling permissions", { error });
          addToast(
            "An error occurred checking/enabling permissions. Grant permissions on the Active Bricks page",
            {
              appearance: "warning",
              autoDismiss: true,
            }
          );
        });
```

**Comment by fregante** [comment]
It appears that this piece of code was not changed in the PR you mentioned:

- https://github.com/pixiebrix/pixiebrix-extension/pull/879

https://github.com/pixiebrix/pixiebrix-extension/blob/5a30ee652ac6c474deee2f6e5e9f5dbaf3b839d0/src/devTools/editor/hooks/useCreate.ts#L204-L216

The last line is an `await` in a `for` loop. Could this perhaps be parallelized? Do you foresee issues and/or possible speed improvements?

**Comment by twschiller** [comment]
> The last line is an await in a for loop. Could this perhaps be parallelized?

That one could be parallelized. I'm doubtful that that's causing your issue though, as it's extremely rare to add multiple custom readers to the foundation via the page editor

**Comment by twschiller** [comment]
Closing because in the new page editor approach, new extensions are self-contained so we don't save the reader and extension point

@fregante will re-open if it's still a problem for you (IIRC, there might still be some checks that might be unnecessary or could be cached)

**Comment by fregante** [comment]
Yep it seems faster!


https://user-images.githubusercontent.com/1402241/135693438-d7c4b91d-9226-462d-a60f-b6b28632181f.mov
