### ISSUE TITLE
Serve source maps from server instead of bundling them

### ISSUE THREAD

**Issue by fregante** [pixiebrix/pixiebrix-extension#1007]
To make the extension bundle leaner, we could remove the source maps from it. We have a couple of options if we want to preserve source maps without including them:

- upload them to a public server: https://webpack.js.org/plugins/source-map-dev-tool-plugin/#host-source-maps-externally
- upload them just for Rollbar: https://rollbar.com/blog/upload-source-maps-to-rollbar/

I think the public server approach is interesting, we get every benefit of source maps without making the user download them. The upload would only be enabled on CI, perhaps exclusively for production/store builds.

**Comment by twschiller** [comment]
We already upload the source maps to Rollbar: http://github.com/pixiebrix/pixiebrix-extension/blob/0c6f2308ee1a68ec05fbedaaf4b4e3547129342b/webpack.config.js#L77-L77

My main concern is that excluding source maps could increase our Chrome Web Store review time. The benefit of a public server is that Chrome could find them (I'm not sure it it could load them from a remote server if they're maps for an extension?). If we just want the CWS team to find them, we could upload them as artifacts to the GitHub action build

@fregante any insights from your experience with the review process?

**Comment by fregante** [comment]
Source maps should work the same everywhere, the browser will resolve absolute URLs just as well as local paths I'd reckon. 

I don't remember sourcemaps affecting CWS, I rarely include them and they rarely complain. 

AMO does not care for maps, they want the full source and they will build it from scratch if they see "generated code." This only happens at random; It hasn't happened in months to me but at some point they flagged every release for a month last year. Submissions are accepted automatically but then they're flagged and you have 15 days to upload the source manually. There's no upload API and they don't want URLs, they want a zip file.

I see sourcemaps as useful to us for debugging, not for reviews.

**Comment by twschiller** [comment]
I'd recommend we do the following. Thoughts?

- Upload the source maps as artifacts of the build (I'll mention in the CWS notes where they're available)
- Drop them from the bundle

IIRC, the source maps don't actually work locally in the release bundle anyway as they're not in web_accessible_resources?

**Comment by fregante** [comment]
I'll have to do some tests, I think uploading them automatically to a server would work and it would be best for you since there's no manual step. There's an abundance of permanent and temporary storage options for this, we just need to pick the easiest to implement on GitHub Actions.
