### ISSUE TITLE
BusinessErrors still being report as "error" level to Rollbar

### ISSUE THREAD

**Issue by twschiller** [pixiebrix/pixiebrix-extension#1013]
**Expected Behavior**
- BusinessError (e.g., no elements found for selector) should be getting passed to Rollbar at the "debug" level

**Actual Behavior**
- Reported at error level, with "BusinessError:" prefix in the item name

**Comment by fregante** [comment]
I presume this was fixed by your changes in:

- https://github.com/pixiebrix/pixiebrix-extension/pull/2752

**Comment by fregante** [comment]
- Fixed by https://github.com/pixiebrix/pixiebrix-extension/pull/4408
