### ISSUE TITLE
RFC: Vendors bundle

### ISSUE THREAD

**Issue by fregante** [pixiebrix/pixiebrix-extension#1014]
Previously mentioned in:

- https://github.com/pixiebrix/pixiebrix-extension/issues/411

Also related to size:

- https://github.com/pixiebrix/pixiebrix-extension/issues/1007
- https://github.com/pixiebrix/pixiebrix-extension/issues/978

I found the webpack configuration that would enable us to create a vendor bundle with common dependencies like react and the web extension polyfill:

https://github.com/webpack/webpack/tree/main/examples/explicit-vendor-chunk

This would not affect:

- existing code-splitting configuration via `import()`
- usage (modules can be `import`ed as usual, this is just a configuration change)
- the app

What would need to change:

- webpack configuration
- every HTML file and the manifest would need to also reference this `vendors.js` file, examples:

```diff
+ <script src="vendors.js"></script>
  <script src="devtools.js"></script>
```

```diff
"background": {
  "scripts": [
+   "vendors.js",
    "background.js"
  ]
},
```

**Comment by twschiller** [comment]
Should be a quick PR to see what the impact will be on bundle sizes. 

My concern would be any impact on `script.js` injection into the host page as we might need to keep that self-contained. I wonder if/how the vendor bundle approach keeps the global namespace clean?

**Comment by fregante** [comment]
> how the vendor bundle avoids side-effects on window

I forgot to address this: webpack does set a global variable, but its name depends on the `package.json`, so in our case it would be `window.webpackChunkpixiebrixextension` probably
