### ISSUE TITLE
RFC: eliminate support for implicit variables usage

### ISSUE THREAD

**Issue by twschiller** [pixiebrix/pixiebrix-extension#1021]
**Context**
- The behavior of `mapArgs` is to fill in value if a name is found in the context. Otherwise, the name of the variable is passed through
- The nice thing about this is: 1) it's concise, 2) the value is passed directly, and is not subject to the limitations of template-based expressions #1020. (Although output keys use `@name` which requires quotes when used in the YAML editor 
- The terrible thing about this is the behavior is confusing for variables that are conditionally defined (e.g., output keys, reader output that might not be present)
- For compound expression, the check is based on the first name. An error is thrown if the subsequent part of the path fails (though ? is supported).

**Options/Considerations**
- Introduce GitHub action style expressions with `${{ }}`: https://docs.github.com/en/actions/reference/context-and-expression-syntax-for-github-actions.  If we introduce syntax highlighting/rich entry (TODO: write the ticket), the syntax might be hidden from non-technical users. The nice thing about `${{ }}` is that it doesn't have to be enclosed in quotes. Is the expression parser open source? It's not clear what kind of expressions we should support. We might just need a way to indicate intentional variable use

**Implementation Sketch**
- Refactor code to pass in brick configuration version to mapArgs?

**Comment by fregante** [comment]
Related:

- https://github.com/pixiebrix/pixiebrix-extension/issues/628

**Comment by fregante** [comment]
> * Introduce GitHub action style expressions with `${{ }}`:

Why not just use the regular templates we already have?

**Comment by fregante** [comment]
I think this was addressed via the input type selector
