### ISSUE TITLE
New google sheets integration configuration shows blank modal

### ISSUE THREAD

**Issue by mnholtz** [pixiebrix/pixiebrix-extension#1048]
When activating a brick in the Marketplace Activation Wizard that involves a Google Sheet integration, the modal that displays after connecting a Google account to create a new Google Sheet configuration is blank, and the only way to escape is to refresh the page.

<img width="1380" alt="Screen Shot 2021-08-10 at 3 05 09 PM" src="https://user-images.githubusercontent.com/36575242/128943574-84f4958e-43ab-4e8f-a07d-b96623cb8a27.png">

**Steps to reproduce**
1. Navigate to the Marketplace tab in the extension
2. Select a blueprint that involves Google Sheets (e.g. _Send Apartments to Google Sheets_) by clicking "Add"
3. Add a new Google Sheet configuration by either clicking the "+ Configure" button or the "+ Add new" button in the dropdown
4. Follow the steps to select a spreadsheet id by clicking the "select" button

**Comment by twschiller** [comment]
Root cause: https://github.com/fregante/webext-detect-page/issues/13
