### ISSUE TITLE
Close offcanvas sidebar on navigation

### ISSUE THREAD

**Issue by fregante** [pixiebrix/pixiebrix-extension#1075]
I feel that the sidebar should close on selection, that's how most navigation works (generally as a direct consequence of the browser navigating to a new page)

https://user-images.githubusercontent.com/1402241/129484334-f02427bb-ae92-4c73-b592-7602a982486b.mov

Related:

- #996 
- #1074

**Comment by twschiller** [comment]
Notes
- Sidebar toggler: http://github.com/pixiebrix/pixiebrix-extension/blob/f3c40eea2031fb47beb4b09083a28019f08d5071/src/layout/Navbar.tsx#L59-L59
- useLocation: https://reactrouter.com/web/api/Hooks/uselocation
