### ISSUE TITLE
Lazy load Ace editor

### ISSUE THREAD

**Issue by fregante** [pixiebrix/pixiebrix-extension#1221]
I think Ace should not be automatically included in the bundle but it should be lazy-imported via `import()`

<img width="1173" alt="before" src="https://user-images.githubusercontent.com/1402241/131411250-f6524757-e613-48c6-b713-644e5a0cc14a.png">

cc @BALEHOK

**Comment by twschiller** [comment]
@BALEHOK. We just need to put the component in BrickDetail behind a React.lazy. See here for an example:

http://github.com/pixiebrix/pixiebrix-extension/blob/6600dbb7b62b441f0f6c4165acc82d3e972ed1a8/src/options/pages/brickEditor/CodeEditor.tsx#L32-L32
