### ISSUE TITLE
RFP: rationalize application state management

### ISSUE THREAD

**Issue by twschiller** [pixiebrix/pixiebrix-extension#1224]
**Triaging**

_This ticket is important long term, but should not take precedence over page editor, form builder, expression editor, or brick runtime work. We can, however, use that work to experiment._

**Context**
* For state management, we use a mixture on Redux, Formik, useState, URL params (React Connected Router), and React contexts in various places
* We use Formik for forms because Redux is inefficient for tracking individual key presses
* We use https://github.com/rt2zz/redux-persist to store the redux state in local storage. However, in some places we read the state from local storage directly instead of using redux-persist. Redux-persist has a mechanism for handling data migrations
* Since we're using useAsyncState/useFetch for fetches, the interface has to reload during navigation even if the user was previously on the screen
* We use Redux Toolkit (RTK) for defining slices: https://redux-toolkit.js.org/introduction/getting-started
* We have custom useFetch and useAsyncHook that are used for fetching/loading async state
* Redux Toolkit has an rtk-library which can generate Redux actions from an API definition https://redux-toolkit.js.org/rtk-query/overview, which can automatically handle loading state, etc.

**Additional Considerations**
* We generate an OpenAPI schema for our API from the app project, and generate Typescript definitions from that. The app uses the TypeScript definitions for return types for API calls. We also use it in some places in the extension. We don't the definitions for the request payloads
* See the API docs here: https://app.pixiebrix.com/api/docs/
* The types might be inaccurate/missing in some places -- the OpenAPI schema has not been stress-tested. In particular, some operations are missing types (because they don't serializers) and the operation names may not make sense
* RTK has a code generator https://redux-toolkit.js.org/rtk-query/usage/code-generation that can generate RTK query style operations from OpenAPI

**Other**
* We also use [IDB](https://github.com/jakearchibald/idb) for the local brick registry and brick execution logs

**Next Steps**
- [ ] Evaluate rtk-query to see if how close it matches our application data fetching model
- [ ] Test https://redux-toolkit.js.org/rtk-query/usage/code-generation to see if it errors out / what the gaps are to producing a Redux client
- [ ] ???

**Comment by BALEHOK** [comment]
There's definitely a lot to think of and discuss.
To begin with I'd get rid of React Context in favor of Redux. These are basically 2 different frameworks that serve the same purpose - handle the global application state.

Redux Toolkit looks good. I see slices are already in use on the project. We can continue with RTK.
