### ISSUE TITLE
Show marketplace information in brick selection modal

### ISSUE THREAD

**Issue by twschiller** [pixiebrix/pixiebrix-extension#1280]
**Context**
- The brick selection modal provides a search bar to search the universe of bricks. Because of the number of bricks, you have to know what to search for
- We're updating the page editor to show better information about inputs/output once the user has added the brick

**Triaging**
- Once we launch the external marketplace, this issue is not urgent important because the user can always use the public marketplace to find the brick they need

**Out of Scope**
- Suggesting bricks based on what other bricks the user has selected

**Blockers**
- @twschiller to create wireframes

**Comment by twschiller** [comment]
Closing in favor of #1326

**Comment by mnholtz** [comment]
Closing in favor of #1326
