### ISSUE TITLE
Brick selection modal with marketplace content

### ISSUE THREAD

**Issue by twschiller** [pixiebrix/pixiebrix-extension#1326]
**Context**
- The existing [BlockModal](http://github.com/pixiebrix/pixiebrix-extension/blob/2bbbb7422107e9a806c0b6238fc5f0b6395f377d/src/components/fields/BlockModal.tsx#L164-L164) has poor discoverability. You need to have a good idea of what you're looking for to find it
- We've hard-coded in recommendations in the Page Editor based on what kind of extension you're working on: http://github.com/pixiebrix/pixiebrix-extension/blob/2bbbb7422107e9a806c0b6238fc5f0b6395f377d/src/devTools/editor/tabs/effect/QuickAdd.tsx#L43-L43. We won't be showing this in the new page editor layout
- The [BrickDetail](http://github.com/pixiebrix/pixiebrix-extension/blob/2bbbb7422107e9a806c0b6238fc5f0b6395f377d/src/options/pages/brickEditor/referenceTab/BrickDetail.tsx#L65-L65) in the Workshop shows additional detail about a brick and has overlap with what we show in the marketplace and what we'll want to show in the brick selection modal
- In the page editor, we're assuming there's more horizontal space than vertical space

**Implementation Sketch**
- [x] Create a new BlockModal component, with the additional following props. (The current one is weird in that is also render it's own button to launch the modal; you may want to have the modal part as its own separate components)
	- Recommended bricks (a list of brick ids)
- [x] On component load, fetch the marketplace listings and create a lookup by registry id. (In the future we'll want to move this to the redux state so we don't have to re-load it on each brick modal display). You can use `useFetch` for this
- [x] If there's a matching listing, use the marketplace listing to determine which icon to show (either the font-awesome icon, or an image with URL)
- [x] When no search query is selected, show the recommended bricks that were passed in
- [x] The brick detail page: same structure as the reference tab
	- Name, id, description
	- Show open in marketplace link (variant="info" if available)
	- Show input/output schema using the SchemaTree component (but no copy YAML action)
	- Do not show the YAML definition (which is currently shown in the Brick Reference)

**Considerations**
- You might be able to re-use the search components from the Brick Reference
- It might be easier to create a copy of the brick detail, rather than using props to control which sections are show
- Yes, it's inefficient fetching the whole marketplace each time the you open the brick modal. We'll have a follow up issue to store this off in redux state

**Wireframes**
- See the Brick Selector Wireframe: https://balsamiq.cloud/s7ffzg5/pu105es/r49F2

**Out of Scope**
- Incorporating tags into the 

**Related**
- #1327

**Comment by mnholtz** [comment]
> * The existing [BlockModal](https://github.com/pixiebrix/pixiebrix-extension/blob/2bbbb7422107e9a806c0b6238fc5f0b6395f377d/src/components/fields/BlockModal.tsx#L164-L164) has poor discoverability. You need to have a good idea of what you're looking for to find it

It's not clear to me from this ticket or wireframe how this increases discoverability? Clearly there is more information included via incorporating marketplace listings, however, the user still needs to start a search query in order to "browse" available bricks. Otherwise, they'd still be going to the marketplace to browse available bricks.
