### ISSUE TITLE
Add 'isRequired' functionality to FieldTemplate/ConnectedFieldTemplate

### ISSUE THREAD

**Issue by BLoe** [pixiebrix/pixiebrix-extension#1343]
Currently there isn't a way for a formik field to detect from the validation schema whether or not it's required. We should come up with a pattern to use here. There isn't currently a good feature for this in Yup or Formik. We need to decide on how much coupling with Yup we're comfortable with, and then decide on which workaround/hack we want to use to let a ConnectedFieldTemplate figure out if it's required or not. Then FieldTemplate should be extended to include a generic "required" tag/indicator in the UI.

**Comment by twschiller** [comment]
Related: https://github.com/formium/formik/issues/712
