### ISSUE TITLE
Page editor experience functionality quick hits

### ISSUE THREAD

**Issue by twschiller** [pixiebrix/pixiebrix-extension#1352]
This issue is to track quick hit functionality improvements

- [x] When a brick is added, switch over to that brick - @twschiller will do
- [x] Swap brick name and output key position - @BLoe  to do
- [x] Move delete button from node badge (but keep in badge code). #1354 
- [x] Hide non-@ object from the input context pane (i.e., force people to use the `@`-based keys unless they really know wha they're doing - @BLoe 
- [x] Change "Add Node" to "Add Brick" - @twschiller to check where this is

**Comment by BLoe** [comment]
Filter context on `@` ouputs fixed with #1360

**Comment by BLoe** [comment]
I did a ctrl+F for "Node" in the source code and didn't see any more usage, I think your change to the remove button of `Remove Node` --> `Remove Brick` seems like it was the only thing.
