### ISSUE TITLE
Improve load time of form modal

### ISSUE THREAD

**Issue by twschiller** [pixiebrix/pixiebrix-extension#1368]
**Context**
- In #1275, we isolated out custom modal to prevent interaction from the host page (e.g., hotkeys, body base font size)
- The downside is that the time to render of the form is slower. (< 1s on development, but still noticeable)

**Implementation Sketch**
- You can design forms using the form builder in the page editor
- We need to profile what's causing the form to be slow to render (communication? JS module loading in the frame?) and come up with a proposal for how to fix

**Theories**
- It's cause by injecting all of bootstrap into the shadowdom
- It's caused by browser messaging overhead
- It's caused by the z-index check
- It's caused by the JS module loading in the frame

**Comment by fregante** [comment]
Is this slowness also happening when the extension is built for production? Like for the initial report in https://github.com/pixiebrix/pixiebrix-extension/issues/430, the slow loading is just a consequence of the large development bundles, but are otherwise relatively snappy otherwise.

**Comment by twschiller** [comment]
Let's hold off for now and I'll collect some more information. I think we're in pretty good shape for developer machines, but will want to double-check during screenshare with enterprise clients that have more commodity hardware

**Comment by fregante** [comment]
Sounds good. I went ahead and dropped one of the concerns though
