### ISSUE TITLE
Form abstraction improvements

### ISSUE THREAD

**Issue by twschiller** [pixiebrix/pixiebrix-extension#1392]
This issue is for capturing potential improvements to the form abstraction

**Ideas**
- Fix warnings about controlId vs. id (does this break anything -- if it does we need to prioritize)
- Move widgets to their own folder
- Create "unconnected" widgets for use with the unconnected `FieldTemplate`: https://pixiebrix.slack.com/archives/C02DKNNB7T9/p1632139218003700?thread_ts=1632138034.001400&cid=C02DKNNB7T9
- Provide a way to pass in a status message that's not an error message (E.g., a warning message about some options not loading, etc.). The context here is for some fields we try to fetch a schema definition, but if that fails we fallback to a generic object widget
- Figure out how to type check field names?
- Is the type checking for extra props when using `as={Widget}` working?

**Related**
- https://github.com/pixiebrix/pixiebrix-extension/issues/1343

**Comment by BLoe** [comment]
* The interface for custom connected widgets is in an awkward state right now. It's not very intuitive how the `value` prop and the wiring up to formik works when trying to use a more complex connected widget.
