### ISSUE TITLE
Fix BlockModal lag

### ISSUE THREAD

**Issue by mnholtz** [pixiebrix/pixiebrix-extension#1396]
The BlockModal lags when opening and when searching, reference comment below:

> The main issue I see right now is the modal is a bit laggy - for the initial open and search. I'm not sure if I caused this (it probably is, as each brick needs to iterate through the marketplace to see if there's a listing for itself). If the cause is the block result rendering, we might need to use: https://github.com/bvaughn/react-virtualized or https://github.com/bvaughn/react-window (which should be pretty easy because the blocks have fixed heights)

https://github.com/pixiebrix/pixiebrix-extension/pull/1359#issuecomment-922546082

**Comment by twschiller** [comment]
The two options we discussed:
- Hard-code an upper threshold for number of results returns (which is what we do in the workshop Brick Reference), or
- Use one of bvaughn/react-virtualized or bvaughn/react-window
