### ISSUE TITLE
Page Editor UI Quick Hits

### ISSUE THREAD

**Issue by twschiller** [pixiebrix/pixiebrix-extension#1408]
Important:
- [x] Data Preview panel width changes based on: 1) whether any tabs are showing (i.e., no trace message is showing), or 2) the size of the content of the selected tab in the data view panel 
- [x] Label should be top-aligned with field
- [x] When copying from the "Output" data panel, also copy the the output key. (This is useful if you want to wire up the next brick without re-running thing with the new config-less brick to get its input context)

Nice to Have/Nits:
- [x] Show "Remove Brick" text if break point gives it it's own line
- [x] When brick is selected, show icon in white for more contrast

**Comment by BLoe** [comment]
>Data Preview panel width...

Fixed as part of #1406

**Comment by BLoe** [comment]
>Label ...

Fixed with #1442

**Comment by BLoe** [comment]
>Show "Remove Brick" text if break point gives it it's own line

Fixed with #1445

**Comment by BLoe** [comment]
>When copying from the "Output" data panel, also copy the the output key. 

This was fixed as part of #1360

**Comment by BLoe** [comment]
>When copying from the "Output" data panel, also copy the the output key.

Closed via #1520
