### ISSUE TITLE
Locked field signifier in Page Editor

### ISSUE THREAD

**Issue by twschiller** [pixiebrix/pixiebrix-extension#1409]
- Show a lock icon, with tooltip: "Value comes from foundation. Edit the foundation in the Workshop"
- Disable field. Hide any shortcuts (for template field and URL match pattern field)

Out of Scope:
- Indicator for foundation fields (for foundation with id+version) that you have edit access to, to inform you that saving that will change the behavior everywhere

**Comment by BLoe** [comment]
Fixed via #1422
