### ISSUE TITLE
BrickIcon is includes SVG files in multiple bundles

### ISSUE THREAD

**Issue by fregante** [pixiebrix/pixiebrix-extension#1414]
These 2 imports are not being treeshaken:

https://github.com/pixiebrix/pixiebrix-extension/blob/b3dab4aea00fe8dfa8a1821750bd162cc083f02b/src/components/BlockIcon.tsx#L23-L24

## Currently

<img width="215" alt="Screen Shot 1" src="https://user-images.githubusercontent.com/1402241/134383560-ffd0d071-67d2-4d90-b310-9311272e392d.png">

## Without those 2 lines

Consider the `Parsed size`

<img width="184" alt="Screen Shot" src="https://user-images.githubusercontent.com/1402241/134383582-cecbfebe-e587-4dad-a6d2-28b8c62182e1.png">

Related:

- https://github.com/pixiebrix/pixiebrix-extension/pull/1359

**Comment by twschiller** [comment]
@fregante The context here is that BrickIcon needs to be able to show any font-awesome icon (since they are configured in the marketplace and not known statically)

There's probably a way to something similar to how we handled the other icon libraries?

**Comment by twschiller** [comment]
I think the solution is to 1) split the load out into a separate module, 2) load the module async in the options page and the devtools pane

We might be able to do that async call in BlockIcon itself

**Comment by fregante** [comment]
I just realized that those are not 2 icons but whole libraries. Should not use the existing iconLibrary? https://github.com/pixiebrix/pixiebrix-extension/blob/28651bf02acccdec1b8bc6106d60d54f75572753/src/icons/getSvgIcon.ts#L27

**Comment by twschiller** [comment]
> Should not use the existing iconLibrary?

The iconLibrary is the bootstrap icons and simple icons libraries that we support as icons for users to use in menu items / buttons they add to pages

The BrickIcon React component is for a different use - it's for showing brick icons in the page editor and workshop reference. In retrospect, we probably should have used the bootstrap/simple icons for these as well but that ship has already sailed :|

So we'll probably want to have a separate module for these FontAwesome icons that would be async-loaded by the options page and page editor

**Comment by fregante** [comment]
> that ship has already sailed :|

Ships always return. I don't think we should have these many different icon set, even just for consistency in the UI. 😰 

> So we'll probably want to have a separate module for these FontAwesome icons that would be async-loaded by the options page and page editor

By the looks of it, the same thing as before is happening: SVG are being inlined. I think the solution is the same too:

- extract the SVGs
- maybe also use a library loader like https://github.com/pixiebrix/pixiebrix-extension/blob/main/src/icons/list.ts

I think the only difference is that the old icons were always loaded via innerHTML, while these are actual components, so a bit extra work will be needed.


---

An alternative quick fix is to make `BrickIcon` an async component and just code-split these new icons, as you suggested.
