### ISSUE TITLE
Update react-table reactTableConfig.d.ts with proper type signatures

### ISSUE THREAD

**Issue by mnholtz** [pixiebrix/pixiebrix-extension#1437]
As acknowledged in [this comment](https://stackoverflow.com/a/68766549), `@types/react-table` type signatures are not compatible with those in `react-table-config.d.ts`. Hopefully, a future version of `react-table` will resolve this issue. For now, type signatures are manually modified in `reactTableConfig.d.ts`.

We would like to use proper type signatures referenced in the [@types/react-table documentation](https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/react-table#example-type-file).

**Comment by fregante** [comment]
> For now, type signatures are manually modified in `reactTableConfig.d.ts`.
> 
> We would like to use proper type signatures referenced in the [@types/react-table documentation](https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/react-table?rgh-link-date=2021-09-23T20%3A15%3A03Z#example-type-file).

It looks to me that the types we're using follow the pattern suggested in the documentation. What is there to do here?

## Documentation
<img width="598" alt="Screen Shot 2" src="https://user-images.githubusercontent.com/1402241/152156894-05920589-1146-4dcf-a2ec-47c9d75380ad.png">



## Ours
<img width="635" alt="Screen Shot 3" src="https://user-images.githubusercontent.com/1402241/152156864-7fd09031-4182-47f7-9d13-e68384a77788.png">

**Comment by mnholtz** [comment]
> It looks to me that the types we're using follow the pattern suggested in the documentation. What is there to do here?

<img width="842" alt="Screen Shot 2022-02-02 at 9 09 54 AM" src="https://user-images.githubusercontent.com/36575242/152204689-490db0a5-2676-4468-84bb-8f44e0876c87.png">

@fregante `D extends object` is less specific than `extends Record`. I have less experience with TypeScript so I am open to closing this issue, but I opened this hoping that `react-table` would solve this in a more recent update. The interfaces they implement in their library don't match these types. 

For this issue we would then be upgrading to a newer version and replacing the modifications in this file.

**Comment by fregante** [comment]
> `D extends object` is less specific than `extends Record`

True, but it seems that there's a readme/types mismatch by the Types authors, in the same repo:

- https://github.com/DefinitelyTyped/DefinitelyTyped/blob/6c720eb3395e5130adc569ce63b1ac5dcf12422d/types/react-table/index.d.ts#L35-L45
- https://github.com/DefinitelyTyped/DefinitelyTyped/blob/6c720eb3395e5130adc569ce63b1ac5dcf12422d/types/react-table/Readme.md?plain=1#L112

I think our only choice is to wait for an update (of `react-table` or its types) and expect a broken CI; _then_ we can fix it. Our types are fine at the moment.
