### ISSUE TITLE
Data Panel for foundation

### ISSUE THREAD

**Issue by twschiller** [pixiebrix/pixiebrix-extension#1443]
Context:
- Splitting this off of the #1421 bug ticket
- Previously FoundationTrace used a hack where it read the trace from the first brick

Open questions
- Do we want to do the hack? Or should we somehow create a trace for the readers? The problem with using the first brick is that it requires you to include a brick

Implementation sketch
- Indicate which panels on not available for the foundation. (I would keep the tab, but show some explanation on the panel)

**Comment by BLoe** [comment]
Closed via #1529
