### ISSUE TITLE
Form Builder layout/UI improvements for 1.4.0

### ISSUE THREAD

**Issue by twschiller** [pixiebrix/pixiebrix-extension#1444]
Placeholder ticket for any form builder changes we want to make for 1.4.0

Improvements
- [x] Add File as a field type (`type: "string"`, `format: "data-url"`)

**Comment by BALEHOK** [comment]
Hey @twschiller
Need more details here.

**Comment by twschiller** [comment]
Sorry, was just creating a placeholder ticket for planning purposes for this week's 1.4.0 release. Just added 1 thing so far: support for file fields
