### ISSUE TITLE
One-time error when using context menu from page editor

### ISSUE THREAD

**Issue by twschiller** [pixiebrix/pixiebrix-extension#1537]
- [ ] Default context to "all" if not provided
- [ ] First time running context menu there's a message about the handler not returning in 1000 second

**Comment by fregante** [comment]
This one, right? https://github.com/pixiebrix/pixiebrix-extension/pull/1319#discussion_r708218973

**Comment by twschiller** [comment]
Thanks for the link. The handleMenuAction method is incorrect, it can't have a timeout assigned to the handler b/c some timeouts can take an arbitary amount of time (e.g., when showing a form that the user needs to enter values into)

I'll take a look at how to adjust the existing logic
