### ISSUE TITLE
Active Bricks page shows below onboarding screen if no extensions are installed

### ISSUE THREAD

**Issue by twschiller** [pixiebrix/pixiebrix-extension#1547]
See "Active Bricks" card header below the video section:

Let's add a test case for this

![image](https://user-images.githubusercontent.com/1879821/135483608-ca396423-d23e-4bd6-8290-f4361f7d79ba.png)

**Comment by BALEHOK** [comment]
@twschiller Can you explain please what was a problem with `noExtensions`?

![image](https://user-images.githubusercontent.com/3116723/135604073-ffcded68-b1bd-4464-801b-cf6cbe962669.png)
![image](https://user-images.githubusercontent.com/3116723/135604112-5842524d-ef6e-4e87-821f-322e3539a01c.png)
