### ISSUE TITLE
Intermittent build errors: Error: Cannot find module 'cssnano-preset-default'

### ISSUE THREAD

**Issue by twschiller** [pixiebrix/pixiebrix-extension#1549]
ERROR in styles.css
styles.css from Css Minimizer
Error: Cannot find module 'cssnano-preset-default'

**Comment by fregante** [comment]
What was the issue that made you use the resolution enforcer?

**Comment by fregante** [comment]
Found https://github.com/pixiebrix/pixiebrix-extension/pull/939, will attempt to drop the dependency.

**Comment by fregante** [comment]
https://github.com/jsdom/webidl-conversions/issues/38#issuecomment-917472852

> jsdom and its dependent packages (like webidl-conversions) are intended for a Node.js environment. If you want to run in browsers, those browsers must support the same features as Node.js, like SharedArrayBuffer. As such, Safari is not supported at all, and Chrome/Firefox require the cross-origin isolation headers to be set on your site.
