### ISSUE TITLE
Re-order bricks in page editor

### ISSUE THREAD

**Issue by twschiller** [pixiebrix/pixiebrix-extension#1599]
**User Story**
- As a Page Editor creator, I would like to re-order bricks in the pipeline of an extension in the page editor
- Currently you'd have to delete and re-create the node

**Considerations**
- Most nodes would probably only need to be moved 1-2 positions
- Drag & drop probably doesn't make sense given the lack of vertical space in the node area? On my screen it only shows 3 at a time

**Comment by BLoe** [comment]
Closed via #1649
