### ISSUE TITLE
IDEA COLLECTION: Page Editor UI / style improvements

### ISSUE THREAD

**Issue by twschiller** [pixiebrix/pixiebrix-extension#1635]
**This issue is a place to record stylistic inconsistencies/improvement ideas for the Page Editor. For bugs, please open a separate ticket. If there's an impact on UX/usability, please note the considerations so we can use when triaging**

- [PR 1482: use flat style for brick nodes to better match other button styles](https://github.com/pixiebrix/pixiebrix-extension/pull/1482)

**Comment by BLoe** [comment]
The tiny `plus-circle` icon buttons between each node in the editor node layout are not intuitive enough right now. It's not totally clear to users what they do, or what it means to add bricks between other bricks in the extension.

A couple initial ideas:
- We should simply change the buttons to be large with text that says "Add brick" or something
- We should make it so that, when the user hovers the cursor over the small circle buttons, they expand and become the full-size "append brick" node from the bottom of the node layout

**Comment by BLoe** [comment]
UX/discoverability of the "Remove Node" button in the editor config panel is not great.

![image](https://user-images.githubusercontent.com/2801308/137534734-7c5f5107-4ece-4790-b5ed-22a6226a05a7.png)

1. The distance (A) between the node layout and the remove button is very large, probably about 1/2 of the window width. Users are creating, selecting, and re-ordering nodes in the node layout, but they must change contexts to the opposite side of the config panel to find the remove button.
2. The remove node button ends up pretty close to the identical-looking remove extension button in the top right (B). This is confusing to have the two different buttons look so similar near each other in the UI when they do very different things.
3. The text of just "Remove" may not be totally clear what is being removed, considering the location of the button. Plus the word goes away at smaller width breakpoints.

**Comment by fregante** [comment]
### Target displayed as plain text in the page editor


Could they be placed in a box? Especially when there's just one it looks like the text doesn't belong there


<img width="711" alt="Screen Shot 9" src="https://user-images.githubusercontent.com/1402241/144716199-5882411a-e617-48e9-95f0-09f058b6f7b0.png">

_Originally posted by @fregante in https://github.com/pixiebrix/pixiebrix-extension/issues/2042#issuecomment-986050485_

**Comment by fregante** [comment]
### Search label in the data panel is _always_ broken on two lines

This screenshot was taken at 1800px wide, with the sidebar collapsed. I think we should just display the label on top. The same applies to every form that is consistently displayed at <500px of width.

<img width="361" alt="Screen Shot 2" src="https://user-images.githubusercontent.com/1402241/152648102-131321f1-379b-4ae6-99f2-1c5eff9720bc.png">
