### ISSUE TITLE
Page Editor "Save" button has no effect

### ISSUE THREAD

**Issue by twschiller** [pixiebrix/pixiebrix-extension#1653]
**Context**
- Extension version 1.4.1
- Don't have reliable steps to reproduce yet. We need to add some additional logging and error messages
- Workaround: restart the page editor (you might lose your work)

**Debugging**
- Is Formik blocking the save somehow? If the code made it to the "useCreate" handler, there should be a toast on every code path. I'm also not seeing any errors/network requests

**Related Code**
- http://github.com/pixiebrix/pixiebrix-extension/blob/8183ec57a1444cfc459129a7b7a327be158dbd01/src/devTools/editor/hooks/useCreate.ts#L118-L118

**Comment by twschiller** [comment]
@BALEHOK I'm pretty sure this issue is caused by Formik thinking the state is invalid due to an "error" in the previous run. (There will be an "Error" even if it's a Cancel error thrown by the user cancelling a modal)

**Comment by BALEHOK** [comment]
> @BALEHOK I'm pretty sure this issue is caused by Formik thinking the state is invalid due to an "error" in the previous run. (There will be an "Error" even if it's a Cancel error thrown by the user cancelling a modal)

If there's an error Formik will not trigger its submit callback, i.e. it is not possible to save an extension with an error. There seems to be no way to tell Formik to skip validation. The solution is not to use Formik's submit at all.
