### ISSUE TITLE
Visually separate Form Editor from other fields on the Edit Tab.

### ISSUE THREAD

**Issue by BALEHOK** [pixiebrix/pixiebrix-extension#1710]
When configuring a field the UI that is part of the Form Field configuration is not clearly separated from the rest of the block config. It may create a false impression that the `Cancelable` switch belongs to the `field1` on the screenshot whereas it's a setting of the Modal Form block.

<img width="1041" alt="Screen Shot 2021-10-19 at 8 46 38 PM" src="https://user-images.githubusercontent.com/3116723/138423618-7c754641-0484-453b-b099-aa727595a3c3.png">

**Comment by twschiller** [comment]
Support added in 1.8.4/5
