### ISSUE TITLE
Support setting multi-line values in textareas

### ISSUE THREAD

**Issue by twschiller** [pixiebrix/pixiebrix-extension#1714]
**Context**
- As a user, I'd like to use the `@pixiebrix/forms/set` and `@pixiebrix/form-fill` bricks to fill out forms with text areas with multiline text

**Implementation Sketch**
- Modify our [setValue method](http://github.com/pixiebrix/pixiebrix-extension/blob/84902a7c02c7193050c262133a361d7fb118c999/src/blocks/effects/forms.ts#L35-L35). Check to see if the element is a textarea. If it is, logic that supports multi line entry

**References**
- https://stackoverflow.com/questions/51799278/set-text-in-textarea-including-newlines/51799362

**Related Issue**
- https://github.com/pixiebrix/pixiebrix-extension/issues/1715

**Comment by twschiller** [comment]
Thanks for the info -- looks like we're going to have to think through how to let the user toggle to a widget that supports multi-line entry in the Page Editor. 

@BLoe is working on general field toggling #1020, but we haven't started considering that aspect of entry yet (multiline vs. single line strings)

An option, at least for this one, would be to define custom options of these bricks that are aware of what kind of element is selected by the brick. Then it could show a single-line vs. multi-line based on what kind of element is currently matched

The longer-term alternative would be to enable the user to toggle between a single line and multi-line widget, and save/store their decision with the extension.

**Comment by fregante** [comment]
In practice I think we can just *always* use textarea and be done with it. The textarea can be "one line tall" by default and expand as the user enters more text or presses enter. Example:

https://github.com/fregante/fit-textarea

Textareas also have better usability when the text no longer fits in a single-line field.

**Comment by fregante** [comment]
From a quick look at our code, it doesn't look like blocks support this. I found `uiSchema` but `Block` does not have a type for it

```js
  uiSchema = {
    value: {
      "ui:widget": "textarea",
    },
  }
```

**Comment by fregante** [comment]
The above would also be required to fix https://github.com/pixiebrix/pixiebrix-extension/issues/1822

Current UI in that case:

<img width="461" alt="Screen Shot" src="https://user-images.githubusercontent.com/1402241/140554995-a51b30f2-51a0-4173-8a0d-f903c03a40b0.png">

**Comment by BLoe** [comment]
>From a quick look at our code, it doesn't look like blocks support this. I found `uiSchema` but `Block` does not have a type for it

I think we support this with `SchemaField`, see: https://github.com/pixiebrix/pixiebrix-extension/blob/main/src/components/fields/schemaFields/widgets/TextWidget.tsx#L87

What do you mean by "Block does not have a type for it"?

**Comment by fregante** [comment]
`Effect` has a `inputSchema` field but not `uiSchema` 

https://github.com/pixiebrix/pixiebrix-extension/blob/84902a7c02c7193050c262133a361d7fb118c999/src/blocks/effects/forms.ts#L55-L78

`TextWidget` is just a component that _could_ be used by `FormFill`, but there's no (apparent) way to do so.

This issue can be considered resolved once this field is a textarea:

https://github.com/pixiebrix/pixiebrix-extension/blob/038499ca9cff1dfc8f017938fcdac850fb3abeb6/src/blocks/renderers/html.ts#L35-L38


<img width="461" alt="Screen Shot" src="https://user-images.githubusercontent.com/1402241/140554995-a51b30f2-51a0-4173-8a0d-f903c03a40b0.png">


Is that already possible?

**Comment by BLoe** [comment]
@twschiller Our `SchemaField` is already set up to take in a `uiSchema` parameter and there is some handling for things like the `textarea` widget setting in `TextWidget`. It looks like `Block` doesn't have a `uiSchema` field though, and we're never actually passing in a `uiSchema` to `genericOptionsFactory()`. Would it be feasible to add a `uiSchema` field to `Block` to allow us to set at least this specific config value (html) to use a `textarea` input?
