### ISSUE TITLE
RFC: sandbox/playground for QA/training/sales

### ISSUE THREAD

**Issue by twschiller** [pixiebrix/pixiebrix-extension#1721]
## Goals/Purpose
An environment replicating different situations that occur in websites in the wild

- Training environment: stable place for learning different skills
- Sales demo environment: mimic internal tools (e.g., CRMs, etc.)
- QA environment: replicate different conditions on web sites. For both manual QA and automated QA (e.g., with Selenium or Rainforest QA, or other tools)

## Requirements
- Backend: for Turbolinks/Turbo: https://github.com/hotwired/turbo
- Isolated front-end versions: multiple versions of React, Ember, Vue, etc. Paired with different state management libraries
- Mimic screens/interactions of common business tools
- Isolated URL roots for testing different front-end router implementations
- No restart/cold start time

## Examples of Cases to Cover
- Major frameworks: React with Redux, React with MobX, Vue, Ember
- Ruby with Turbolinks (navigation event occurs before page content changes)
- Infinite scroll
- Site with hotkeys enabled

## Business Apps to Mimic
- CRM
- Ticketing system
- BPM forms
- Project Management

## Open questions / considerations
- Is it worth having a backend? We'd need it for Turbolinks? Static admin interfaces, e.g., Django admin? We probably need affordances for multiple backends (Ruby vs. Django)
- Are JS modules at a point where we don't even need to bundle them? We could just reference the CDN directly from the page (e.g., using https://unpkg.com/)
- Repository structure: have as a separate AGPLv3 repository from the extension. Categorized by major framework, sub-organized by combination

## Prior Art
- https://replit.com/@PixieBrixTodd/ReactSandbox Our current sandbox, implemented as a Repl
- TodoMVC: https://todomvc.com/ (implementations of a simple TODO app in different frameworks)

**Comment by fregante** [comment]
Example set up here: https://github.com/pixiebrix/playground

Default page available at: https://pixiebrix.github.io/playground/example/

More subfolders can be added by anyone who wants to create custom cases for their tests.
