### ISSUE TITLE
Add test coverage reporting to PRs

### ISSUE THREAD

**Issue by twschiller** [pixiebrix/pixiebrix-extension#1727]
Considerations
- We don't want to enforce as a hard check yet, but will be a piece of information for reviewers

Questions
- Use Codacy for tracking over time?

**Comment by BALEHOK** [comment]
Personally I very much like the experience with Codecove (https://about.codecov.io/product/features/).
It does support github actions and delivers nice coverage visibility on PR level.

**Comment by twschiller** [comment]
@BALEHOK could you help set up this action? https://github.com/codecov/codecov-action
