### ISSUE TITLE
No handler for RUN_BLOCK was registered in the receiving end

### ISSUE THREAD

**Issue by twschiller** [pixiebrix/pixiebrix-extension#1798]
Bug introduced in 1.4.4? Introduced sometime between 1.4.2, 1.4.3, or 1.4.4

**Steps to reproduce:**

Use a blueprint with:
1. Use open a tab to open a new tab that contains a form
2. Submit a form on the page (using `window: target`)
3. Wait for an element on the next page (using `window: target`)

**Related**
- https://github.com/pixiebrix/pixiebrix-extension/issues/1585: we fixed the bug during 1.4.1, but it looks like it's back
- https://github.com/pixiebrix/pixiebrix-extension/issues/1724: not sure if this is related?

**Comment by fregante** [comment]
> * [executeInTarget fails early due to intermediate content script state #1585](https://github.com/pixiebrix/pixiebrix-extension/issues/1585): we fixed the bug during 1.4.1, but it looks like it's back

I changed the error message after that PR, so if it's the same exact error then we just need to update `NOT_READY_PARTIAL_MESSAGES`
