### ISSUE TITLE
Inconsistent form/extension state when editing v3 extensions

### ISSUE THREAD

**Issue by twschiller** [pixiebrix/pixiebrix-extension#1804]
Branch on branch feature/1020-input-field-type-toggles, not reproducible on main?

Steps to reproduce
1. Create new button
2. Add jQuery brick
3. Add one jQuery selector
4. Save the extension
5. --> selector disappears

TODO: confirm this isn't impacting main or the 1.4.5 release branch

**Comment by BLoe** [comment]
Just to note here, can confirm this isn't an issue for the 1.4.5 release.

**Comment by BLoe** [comment]
@twschiller Can we close this?
