### ISSUE TITLE
HTML renderer removes newlines

### ISSUE THREAD

**Issue by 4626433** [pixiebrix/pixiebrix-extension#1822]
Formatting of HTML pasted into HTML renderer bricks loses newlines making it very hard to read or work with once in the brick.

**Comment by twschiller** [comment]
Hi @4626433, could you post which id you're working with? It might be an issue with which YAML multiline mode you're using vs. the HTML brick.

See https://yaml-multiline.info/, you might need to use the `|` indicator?

**Comment by twschiller** [comment]
Closing as per: https://pixiebrix.slack.com/archives/C02CN01JXAA/p1642717227085000
