### ISSUE TITLE
Upgrade to React Router v6

### ISSUE THREAD

**Issue by twschiller** [pixiebrix/pixiebrix-extension#1851]
See:
* https://github.com/pixiebrix/pixiebrix-extension/pull/1838
* https://github.com/pixiebrix/pixiebrix-extension/pull/1835
* https://github.com/pixiebrix/pixiebrix-extension/pull/4146

**Comment by fregante** [comment]
Blocked by:

- https://github.com/supasate/connected-react-router/issues/397

The project hasn't seen updates in years
