### ISSUE TITLE
Improve error message if user has blueprint shared with them, but a component (e.g., Service) isn't shared

### ISSUE THREAD

**Issue by MMirandi** [pixiebrix/pixiebrix-extension#1857]
Can we improve the error message if a user has a blueprint shared with them, but one of the components (e.g., Service) isn't shared with them. This error message would appear when they try to install the blueprint.

**Comment by twschiller** [comment]
On the "Share Extension" option on the Active Bricks page, we actually automatically share dependencies. 

I'd imagine we'd want to do something similar when saving in the workshop. On save, popup a warning that says to the effect: "Not all dependencies are visible" and provide and option/button for the user to automatically also update the sharing options on the dependencies (if they are allowed to)

Will also be good to add on the consumer side as well
