### ISSUE TITLE
Significant lag updating trace outputs and block status indicator

### ISSUE THREAD

**Issue by twschiller** [pixiebrix/pixiebrix-extension#1868]
Release build 1.4.7-alpha.2

Steps to reproduce:
- Add a side panel brick
- Add a couple intermediary bricks, e.g., URL brick, mapping brick
- Add iframe or markdown brick with an error in it (e.g,. an unterminated template expression)
- Click "render panel" 
- Click "render panel" again

It will take 10-15+ seconds for the second run to register both in the badge and also data panel.

Also during this time you can't save because of https://github.com/pixiebrix/pixiebrix-extension/issues/1653

Update:
I think it’s a 1.4.7 issue? Not totally sure. I did a clean install of 1.4.6 from CWS and seems ok. There’s also a chance our trace records aren’t getting cleaned up so and I had accumulated a ton of irrelevant trace records?

**Comment by twschiller** [comment]
Update: I'm not seeing the issue on a clean install of 1.4.7-alpha.2. Will keep this open in the backlog and see if I start experience the problem again

**Comment by BALEHOK** [comment]
@twschiller Can we close this one?
