### ISSUE TITLE
Revive the sound effect brick

### ISSUE THREAD

**Issue by twschiller** [pixiebrix/pixiebrix-extension#1997]
**Context**
- At one point we had a play sound effect brick, but the audio sprite handling wasn't working (it was playing effects too long, wasn't starting at the right spot). Here's the PR/diff where it was remove: https://github.com/pixiebrix/pixiebrix-extension/pull/1345
- The audio sprite we had tried using is still in the repository (I'm not sure if it's cut up correctly): http://github.com/pixiebrix/pixiebrix-extension/blob/b21472a612cff45222518554a6e4b2b518eaa2b0/static/audio#L1-L1

**Implementation Sketch**
- Follow the steps to set up a local build of the extension: https://github.com/pixiebrix/pixiebrix-extension/wiki/
- Review the instructions for adding a JavaScript brick: https://www.notion.so/Adding-a-JavaScript-Brick-8676a48f3f1c44ca8339d00a4c9b88e1
- Revive the old code (re-add the howler js packages to the project), re-add the sound effect brick. (You may need update some of the locations it's imports point to?)

**Helpful Articles**
- Creating an audio sprite for howlerjs: https://medium.com/game-development-stuff/how-to-create-audiosprites-to-use-with-howler-js-beed5d006ac1

**Comment by fregante** [comment]
If instantaneous playback isn't required, we might just use `new Audio().src = 'file.mp3'` instead. 

Howler would only be useful to have complete control over the playback of the file, for example to be used in video games where the sounds needs to match the video effect and must be pre-loaded.

The regular `audio` element is fine for a local file, without a sprite, adding minimal playback delay (I'm guessing less than 300ms). I can take care of splitting that sprite up if you want to preserve those sound effects.

**Comment by twschiller** [comment]
Good idea and worth an experiment to see what the latency would be. That would also better allow for playing remote sound effects

> I can take care of splitting that sprite up if you want to preserve those sound effects

I'm not tied to these sound effects. They just happened to be what I came across in public domain when I originally tried prototyping the feature

I'll connect with @MMirandi to see what sound effects would be most useful (probably cheer, gong, etc.)
