### ISSUE TITLE
HTTP bricks fail on request to http (non-secure) urls

### ISSUE THREAD

**Issue by twschiller** [pixiebrix/pixiebrix-extension#2002]
- Have the bricks throw a validation error?
- Warn to the brick logger?
- Add support for HTTP URLs (is it a CSP/permissions thing?)

**Comment by fregante** [comment]
Is the request being made from the content script? If the request doesn't need cookies, you can just fetch it in the background page. I'm not entirely sure if extensions are allowed to bypass this restriction, they're also often restricted just like other pages. Another example is CORB: https://stackoverflow.com/q/54786635


Rules about mixed content might have gotten stricter over the years as it appears that HTTP fetches in HTTPS pages are just blocked now, maybe only resources like JS, CSS, frames and images are still allowed. 



It doesn't look like there's a way allow them, everyone [suggests](https://stackoverflow.com/q/33507566) a CSP rule that simply attempts to fetch via HTTPS anyway (this only works if the server _does_ support HTTPS after all)

**Comment by twschiller** [comment]
It's getting fetched from the background page, so the request is subject to the extensions permissions. (Our CSP has  https: in the connect-src. I _thought_ http could also work if you explicitly granted host permissions to the HTTP host)

It looks like Firefox is banning non-HTTPS traffic after Dec 1: 
> The use of encryption - standard HTTPS - is now always required when communicating with remote services.

I like the approach of trying to upgrade to HTTPS automatically. For simplicity and security, though, I'd probably lean toward just throwing an argument validation error on non-HTTPS URLs

**Comment by fregante** [comment]
> It looks like Firefox is banning non-HTTPS traffic after Dec 1:

Great news!

An alternative could be setting up a quick proxy on, say, CloudFlare Workers or Vercel. This way we can support all the URLs.

Deprecating HTTP requests would also be acceptable IMHO, but it's always possible that some enterprise "can't upgrade to HTTPS"

**Comment by twschiller** [comment]
> An alternative could be setting up a quick proxy on, say, CloudFlare Workers or Vercel

Our API has an `/api/proxy/` endpoint we can use as a fallback. It's also able to perform authentication with team credentials the user shouldn't have access to

**Comment by twschiller** [comment]
Closing because we now enforce HTTPS: http://github.com/pixiebrix/pixiebrix-extension/blob/09613df2831c95ec59e291726b63fd71781c2df6/src/services/requestErrorUtils.ts#L163-L163
