### ISSUE TITLE
Workshop: if the server has an internal server error, the save button is disabled and no error is shown

### ISSUE THREAD

**Issue by twschiller** [pixiebrix/pixiebrix-extension#2023]
- Need to show a server error on 5XX responses
- Need to re-enable the create button on 5XX responses

Related Code
- https://github.com/pixiebrix/pixiebrix-extension/blob/7452a68c7cd031420582fe8b7fd3d5bbf1fbba40/src/options/pages/brickEditor/EditPage.tsx#L110-L110

**Comment by abdullah4244** [comment]
Hi @twschiller  can you tell me how to raise exception , wanted to test out my code

**Comment by BALEHOK** [comment]
I can't reproduce the bug. @twschiller could you verify the error still exists? If so please provide more details on steps to reproduce.

Create new brick
https://user-images.githubusercontent.com/3116723/186395796-1b275720-da0b-48fa-a160-6f685e6ed879.mov

Update a brick
https://user-images.githubusercontent.com/3116723/186395865-595440e7-709b-4459-8e4c-d9742035827e.mov

**Comment by twschiller** [comment]
> I can't reproduce the bug. @twschiller could you verify the error still exists? If so please provide more details on steps to reproduce.

Thanks, I just checked and can't reproduce either when have the server return a 500. Closing the ticket
