### ISSUE TITLE
Node Config Panel has tiny horizontal scroll

### ISSUE THREAD

**Issue by BLoe** [pixiebrix/pixiebrix-extension#2030]
In `EditorNodeConfigPanel`, the top row of Step Name, Output, and Remove Node button has something wrong with the horizontal sizing causing a tiny amount of horizontal scroll in the middle panel of the page editor.

![image](https://user-images.githubusercontent.com/2801308/144098718-a09b0f08-677d-4ff8-891b-1b8fa0590fca.png)

**Comment by fregante** [comment]
Please don't just add `overflow-x-: hidden` to it 😃 

If the bar appears, sizing somewhere is incorrect
