### ISSUE TITLE
Implement developer comments that are visible/editable in both the page editor and the workshop

### ISSUE THREAD

**Issue by BLoe** [pixiebrix/pixiebrix-extension#2038]
We aren't sure if this is even feasible, Todd will investigate.

Ideally this would be a way to add comments in the YAML code that can be interpreted somehow in the page editor and displayed to the user.

**Comment by twschiller** [comment]
Closing - we are moving everything to the page editor so this isn't a requirement. Don't need to support the mixed editing scenario
