### ISSUE TITLE
Pop-out, wider text edit input for dealing with longer strings

### ISSUE THREAD

**Issue by BLoe** [pixiebrix/pixiebrix-extension#2039]
This would be useful for handling longer selector strings, and some other use-cases.

Considerations:
- We could simply use the same `textarea` approach as regular text inputs, but not sure this UX works as well for a long single string like a jquery selector
  - Does it affect the selectors if there are newlines included? Do they get stripped out at some point? If not, should we strip them out explicitly?
- If we build a "pop-out," modal, `textarea` input, it should be very simple for now, just want to be able to view more of the entire string at once

**Comment by fregante** [comment]
Line breaks don't matter in selectors, they are interpreted as regular spaces. We can still pass the full string to jQuery unchanged. 

I think that, at least for selectors, it's not worth implementing a new UI type. Wrapping selectors is fine and the current textarea solution would also show the full selector "at rest", whereas a popout would then presumably go back to a little `input`

Perhaps I'd still add a "full-screen editor mode" for fields that require a lot of content, for example an HTML template.

**Comment by BLoe** [comment]
We've now changed `TextWidget` to use `textarea` in all cases, so this ticket only applies to `SelectorSelectorWidget` at this point. The `textarea` solution only allows expanding down to multiple lines, it doesn't give any extra horizontal space. There also isn't much auto-formatting that happens right now in the `textarea` inputs, so it would still be awkward to write selectors across multiple lines. For long jQuery selectors, it's probably going to be a better UX if we can have a way to show a _wider_ text input, in order to view all (or at least more of) the selector at once, on a single line.

**Comment by BALEHOK** [comment]
I've got the following editor experience
![image](https://user-images.githubusercontent.com/3116723/146822513-ac48d6a9-e76e-4dac-b334-66eddd193f30.png)

Things get better with collapsed Sidebar (but still not ideal).
![image](https://user-images.githubusercontent.com/3116723/146822712-2ab6999d-4102-433e-806a-e0a44622d120.png)

**Comment by BLoe** [comment]
We have #1863, which includes making changes to help with that situation.

**Comment by fregante** [comment]
There's a lot of wasted space in that view on every side. Every column of empty space makes sense on its own (labels, type selectors) but they're taking 50-80% of the available horizontal space so I think that's the issue that should be solved.

![146822712-2ab6999d-4102-433e-806a-e0a44622d120](https://user-images.githubusercontent.com/1402241/146823350-fab99231-5899-4e78-8bd9-3d502253c711.png)

One solution could be to show the field label on top at least on small viewports — if not all the time.

Another possible improvement would be to allow resizing/collapsing all the sidebars, not just the extension list.

In @BALEHOK’s first screenshot, the fields take 85 pixels out of available 900pixels on screen.

**Comment by fregante** [comment]
Since this issue seems affect mostly these large tables, what do you think about breaking the whole table into a modal instead of just a single field? This would make it easy to not only edit each value, but also see an overview of the table.

For example when the table not longer fits you can show a <kbd>Edit `columns` field</kbd> that opens a modal.

## Before

<img width="965" alt="Screen Shot" src="https://user-images.githubusercontent.com/1402241/146825662-86d6394f-3739-437f-b103-c666f9abcad9.png">

## After

<img width="963" alt="Screen Shot 1" src="https://user-images.githubusercontent.com/1402241/146825670-25b4954e-cad3-43bc-a1ad-c89130c5cd94.png">

## Modal open

<img width="963" alt="Screen Shot 1 2" src="https://user-images.githubusercontent.com/1402241/146825950-4052ec8c-badd-43e4-8405-aee32bd451fd.png">

**Comment by BLoe** [comment]
I don't think we want to put things behind a modal popup where you can't see the properties until you open it up. We're going to try and address these spacing issues though, for sure.

**Comment by BALEHOK** [comment]
@BLoe @fregante 
A popup input?

![image](https://user-images.githubusercontent.com/3116723/147293799-0662d13b-3bfe-464c-8c55-849982a28d0b.png)

On click and/or long hover? Could display the label as well, think Form group.
