### ISSUE TITLE
Target displayed twice in the page editor

### ISSUE THREAD

**Issue by fregante** [pixiebrix/pixiebrix-extension#2042]
I think the label on top is a remnant of a previous implementation, before the Target field was added to the advanced options

<img width="539" alt="Screen Shot 4" src="https://user-images.githubusercontent.com/1402241/144701401-949620b5-c08c-4f5a-87a9-135b42eb2021.png">

**Comment by twschiller** [comment]
@fregante That is the expected behavior. When you override a default, the value you've set is displayed up above to so it's quick to see if any default behaviors have been overridden. For example, if you set that to "broadcast", up above the text will say "Target: broadcast"

**Comment by fregante** [comment]
I see, all the advanced options are re-displayed up there:

<img width="711" alt="Screen Shot 9" src="https://user-images.githubusercontent.com/1402241/144716199-5882411a-e617-48e9-95f0-09f058b6f7b0.png">

Could they be placed in a box? Especially when there's just one it looks like the text doesn't belong there

**Comment by fregante** [comment]
Moved to the collection
