### ISSUE TITLE
`@pixiebrix/wait/sleep` unusable via page editor (it expects an integer)

### ISSUE THREAD

**Issue by fregante** [pixiebrix/pixiebrix-extension#2045]
<img width="557" alt="Screen Shot 8" src="https://user-images.githubusercontent.com/1402241/144706406-a3c900b5-42ed-4768-a172-913259f38eed.png">

**Comment by twschiller** [comment]
@fregante Thanks for reporting. This is the motivation for @BLoe's work on field toggling which we'll be rolling out soon. If you want to use the preview version, on the foundation note you can set API version to v3 on the foundation:

![image](https://user-images.githubusercontent.com/1879821/144711722-1c32d064-4dc2-4ad6-a124-55e3e1fd30a1.png)
