### ISSUE TITLE
Page editor autocomplete for inputs - Implement the UI

### ISSUE THREAD

**Issue by BLoe** [pixiebrix/pixiebrix-extension#2072]
Considerations:
- If the extension has not run yet, indicate in the UI what is speculative versus known
- Place the suggestions list in the right place, aligned with where the typing is occurring (check that it works in the middle of a `textarea`)
- Two sections, top one is type-ahead suggestions for completing variable *names*, and the bottom section is search results for data *values* matching anywhere in the value

**Comment by twschiller** [comment]
Closing because its been implemented as the variable popover
