### ISSUE TITLE
Isolate styles for notifications on host page

### ISSUE THREAD

**Issue by twschiller** [pixiebrix/pixiebrix-extension#2096]
**Context**
- Our host page notifications are not in a shadow dom, so on some pages the font size and icon alignment is broken
- We use $.notify for rendering the notifications
- All of the notifications go through [notify.ts](http://github.com/pixiebrix/pixiebrix-extension/blob/547f0dd8936a26508fdc61f404b840b3637dfeaf/src/contentScript/notify.ts#L27-L27). I did it that way so we could swap out the implementation at some point to improve the style/behavior

**Comment by fregante** [comment]
> * on some pages the font size and icon alignment is broken

Do you know any examples off the top of your head?

**Comment by fregante** [comment]
Is this private? I don't see it in the UI:

https://github.com/pixiebrix/pixiebrix-extension/blob/1ad7151bf9cb9b26023da96a6e6a674b5ef17ddc/src/runtime/reducePipeline.ts#L367

**Comment by fregante** [comment]
https://github.com/pixiebrix/pixiebrix-extension/blob/cbd8d906edcdde1e6b9d27b79b7ae4d31a873716/src/extensionPoints/menuItemExtension.ts#L117-L119

$.notify’s options seem to be used "raw" in the extensions. Are you aware if they use anything more than `className`? Is there anything else I should map to react-hot-toasts?

Here's the full list of options available: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/b343913eba52889828771a9cb5d96d12bad946b3/types/notifyjs-browser/index.d.ts#L9-L39
