### ISSUE TITLE
Remove "scope" configuration on Page Editor first run

### ISSUE THREAD

**Issue by mnholtz** [pixiebrix/pixiebrix-extension#2151]
**Context**
When users first start using the Page Editor, they are prompted to choose a scope. However, scope is only used when sharing or saving bricks.

In order to making the onboarding journey smoother and less overwhelming, we would like to ask the user to choose a scope later in the onboarding process, i.e. when sharing or saving.

**Comment by twschiller** [comment]
Implementation Sketch:
- Remove ["Require Scope"](http://github.com/pixiebrix/pixiebrix-extension/blob/ecec1bfa553284f9ee4b877acd75541e3fca5fd2/src/devTools/Panel.tsx#L64-L64) from Page Editor Pane
- Handle if user does not have scope set in [Sidebar footer](http://github.com/pixiebrix/pixiebrix-extension/blob/ecec1bfa553284f9ee4b877acd75541e3fca5fd2/src/devTools/editor/sidebar/Footer.tsx#L24-L24)
- Update [ShareExtensionModal](http://github.com/pixiebrix/pixiebrix-extension/blob/ecec1bfa553284f9ee4b877acd75541e3fca5fd2/src/options/pages/installed/ShareExtensionModal.tsx#L111-L111) flow from the Active Bricks/Blueprints to have user configure a scope first if they have not configured one yet
- In the Save Extension Wizard, show a scope configuration form as part of the wizard if the user selects ["Save as New Blueprint"](http://github.com/pixiebrix/pixiebrix-extension/blob/ecec1bfa553284f9ee4b877acd75541e3fca5fd2/src/devTools/editor/panes/save/SaveExtensionWizard.tsx#L89-L89)

Related Issues: 
- https://github.com/pixiebrix/pixiebrix-extension/issues/2556
