### ISSUE TITLE
Add/fix onboarding views to storybook

### ISSUE THREAD

**Issue by mnholtz** [pixiebrix/pixiebrix-extension#2152]
**Context**
There are some onboarding views in storybook already (e.g. EnterpriseSuccessModal, and OnboardingPage). We need to figure out what is left to add to storybook within both the extension and the app, in order to better discuss onboarding flow.

**Comment by mnholtz** [comment]
I was verifying onboarding view in storybook today... and noticed that the `OnboardingPage` story is not appearing in storybook despite it having a story. Would someone else be able to replicate/verify this?

All I did was `npm run storybook` after a fresh pull and `npm install`, and I'm not seeing `OnboardingPage` underneath the "Onboarding" heading, nor via the search bar.

**Comment by twschiller** [comment]
@mnholtz some stories are appearing and are broken (because they need to be wrapped in a Provider). Other stories aren't showing up at all because they are broken

**Comment by mnholtz** [comment]
@twschiller I think we need to close this issue and reopen with something more specific, e.g. add a CI or PR checklist item for ensuring storybook stories still work. They keep breaking.

**Comment by twschiller** [comment]
Yes, let's add an item to the checklist. Unfortunately, I don't think we can check during CI easily because broken stories compile OK. (We'd have to use Cypress/Selenium/etc. to test our Storybook)

**Comment by mnholtz** [comment]
@twschiller which checklist are you referring to?
