### ISSUE TITLE
Slim down background bundle to speed up its reloading in MV3

### ISSUE THREAD

**Issue by fregante** [pixiebrix/pixiebrix-extension#2156]
With MV3, the background page is unloaded every 5 minutes at the latest. I think we should make sure that this bundle takes the shortest amount of possible to execute and become ready. 

Current production sizes:

- background.js: 1.1MB 

Related:

- https://github.com/pixiebrix/pixiebrix-extension/pull/2106

**Comment by fregante** [comment]
For reference, I'll post the current list of files indirectly imported by the background page

- [src/analysis/analysisSelectors.ts](https://github.com/pixiebrix/pixiebrix-extension/blob/main/src/analysis/analysisSelectors.ts)
- [src/analysis/analysisVisitors/baseAnalysisVisitors.ts](https://github.com/pixiebrix/pixiebrix-extension/blob/main/src/analysis/analysisVisitors/baseAnalysisVisitors.ts)
- [src/auth/authUtils.ts](https://github.com/pixiebrix/pixiebrix-extension/blob/main/src/auth/authUtils.ts)
- [src/auth/token.ts](https://github.com/pixiebrix/pixiebrix-extension/blob/main/src/auth/token.ts)
- [src/background/activateBrowserActionIcon.ts](https://github.com/pixiebrix/pixiebrix-extension/blob/main/src/background/activateBrowserActionIcon.ts)
- [src/background/auth/authStorage.ts](https://github.com/pixiebrix/pixiebrix-extension/blob/main/src/background/auth/authStorage.ts)
- [src/background/auth/codeGrantFlow.ts](https://github.com/pixiebrix/pixiebrix-extension/blob/main/src/background/auth/codeGrantFlow.ts)
- [src/background/auth/getToken.ts](https://github.com/pixiebrix/pixiebrix-extension/blob/main/src/background/auth/getToken.ts)
- [src/background/auth/implicitGrantFlow.ts](https://github.com/pixiebrix/pixiebrix-extension/blob/main/src/background/auth/implicitGrantFlow.ts)
- [src/background/auth/launchOAuth2Flow.ts](https://github.com/pixiebrix/pixiebrix-extension/blob/main/src/background/auth/launchOAuth2Flow.ts)
- [src/background/browserAction.ts](https://github.com/pixiebrix/pixiebrix-extension/blob/main/src/background/browserAction.ts)
- [src/background/capture.ts](https://github.com/pixiebrix/pixiebrix-extension/blob/main/src/background/capture.ts)
- [src/background/contentScript.ts](https://github.com/pixiebrix/pixiebrix-extension/blob/main/src/background/contentScript.ts)
- [src/background/contextMenus.ts](https://github.com/pixiebrix/pixiebrix-extension/blob/main/src/background/contextMenus.ts)
- [src/background/deploymentUpdater.ts](https://github.com/pixiebrix/pixiebrix-extension/blob/main/src/background/deploymentUpdater.ts)
- [src/background/eventUtils.ts](https://github.com/pixiebrix/pixiebrix-extension/blob/main/src/background/eventUtils.ts)
- [src/background/executor.ts](https://github.com/pixiebrix/pixiebrix-extension/blob/main/src/background/executor.ts)
- [src/background/externalProtocol.ts](https://github.com/pixiebrix/pixiebrix-extension/blob/main/src/background/externalProtocol.ts)
- [src/background/firefoxCompat.ts](https://github.com/pixiebrix/pixiebrix-extension/blob/main/src/background/firefoxCompat.ts)
- [src/background/initBrowserCommands.ts](https://github.com/pixiebrix/pixiebrix-extension/blob/main/src/background/initBrowserCommands.ts)
- [src/background/installer.ts](https://github.com/pixiebrix/pixiebrix-extension/blob/main/src/background/installer.ts)
- [src/background/messenger/api.ts](https://github.com/pixiebrix/pixiebrix-extension/blob/main/src/background/messenger/api.ts)
- [src/background/messenger/external/_implementation.ts](https://github.com/pixiebrix/pixiebrix-extension/blob/main/src/background/messenger/external/_implementation.ts)
- [src/background/messenger/external/api.ts](https://github.com/pixiebrix/pixiebrix-extension/blob/main/src/background/messenger/external/api.ts)
- [src/background/messenger/registration.ts](https://github.com/pixiebrix/pixiebrix-extension/blob/main/src/background/messenger/registration.ts)
- [src/background/modUpdater.ts](https://github.com/pixiebrix/pixiebrix-extension/blob/main/src/background/modUpdater.ts)
- [src/background/navigation.ts](https://github.com/pixiebrix/pixiebrix-extension/blob/main/src/background/navigation.ts)
- [src/background/partnerHandlers.ts](https://github.com/pixiebrix/pixiebrix-extension/blob/main/src/background/partnerHandlers.ts)
- [src/background/partnerIntegrations.ts](https://github.com/pixiebrix/pixiebrix-extension/blob/main/src/background/partnerIntegrations.ts)
- [src/background/permissionPrompt.ts](https://github.com/pixiebrix/pixiebrix-extension/blob/main/src/background/permissionPrompt.ts)
- [src/background/proxyUtils.ts](https://github.com/pixiebrix/pixiebrix-extension/blob/main/src/background/proxyUtils.ts)
- [src/background/refreshToken.ts](https://github.com/pixiebrix/pixiebrix-extension/blob/main/src/background/refreshToken.ts)
- [src/background/requests.ts](https://github.com/pixiebrix/pixiebrix-extension/blob/main/src/background/requests.ts)
- [src/background/starterMods.ts](https://github.com/pixiebrix/pixiebrix-extension/blob/main/src/background/starterMods.ts)
- [src/background/telemetry.ts](https://github.com/pixiebrix/pixiebrix-extension/blob/main/src/background/telemetry.ts)
- [src/background/walkthroughModalTrigger.ts](https://github.com/pixiebrix/pixiebrix-extension/blob/main/src/background/walkthroughModalTrigger.ts)
- [src/background/webextAlert.ts](https://github.com/pixiebrix/pixiebrix-extension/blob/main/src/background/webextAlert.ts)
- [src/bricks/available.ts](https://github.com/pixiebrix/pixiebrix-extension/blob/main/src/bricks/available.ts)
- [src/bricks/effects/alert.ts](https://github.com/pixiebrix/pixiebrix-extension/blob/main/src/bricks/effects/alert.ts)
- [src/bricks/effects/assignModVariable.ts](https://github.com/pixiebrix/pixiebrix-extension/blob/main/src/bricks/effects/assignModVariable.ts)
- [src/bricks/effects/attachAutocomplete.ts](https://github.com/pixiebrix/pixiebrix-extension/blob/main/src/bricks/effects/attachAutocomplete.ts)
- [src/bricks/effects/clipboard.ts](https://github.com/pixiebrix/pixiebrix-extension/blob/main/src/bricks/effects/clipboard.ts)
- [src/bricks/effects/confetti.ts](https://github.com/pixiebrix/pixiebrix-extension/blob/main/src/bricks/effects/confetti.ts)
- [src/bricks/effects/event.ts](https://github.com/pixiebrix/pixiebrix-extension/blob/main/src/bricks/effects/event.ts)
- [src/bricks/effects/getAllEffects.ts](https://github.com/pixiebrix/pixiebrix-extension/blob/main/src/bricks/effects/getAllEffects.ts)
- [src/bricks/effects/highlight.ts](https://github.com/pixiebrix/pixiebrix-extension/blob/main/src/bricks/effects/highlight.ts)
- [src/bricks/effects/highlightText.ts](https://github.com/pixiebrix/pixiebrix-extension/blob/main/src/bricks/effects/highlightText.ts)
- [src/bricks/effects/insertHtml.ts](https://github.com/pixiebrix/pixiebrix-extension/blob/main/src/bricks/effects/insertHtml.ts)
- [src/bricks/effects/pageState.ts](https://github.com/pixiebrix/pixiebrix-extension/blob/main/src/bricks/effects/pageState.ts)
- [src/bricks/effects/postMessage.ts](https://github.com/pixiebrix/pixiebrix-extension/blob/main/src/bricks/effects/postMessage.ts)
- [src/bricks/effects/replaceText.ts](https://github.com/pixiebrix/pixiebrix-extension/blob/main/src/bricks/effects/replaceText.ts)
- [src/bricks/effects/runSubTour.ts](https://github.com/pixiebrix/pixiebrix-extension/blob/main/src/bricks/effects/runSubTour.ts)
- [src/bricks/effects/scrollIntoView.ts](https://github.com/pixiebrix/pixiebrix-extension/blob/main/src/bricks/effects/scrollIntoView.ts)
- [src/bricks/effects/sidebar.ts](https://github.com/pixiebrix/pixiebrix-extension/blob/main/src/bricks/effects/sidebar.ts)
- [src/bricks/effects/sound.ts](https://github.com/pixiebrix/pixiebrix-extension/blob/main/src/bricks/effects/sound.ts)
- [src/bricks/effects/ToggleQuickbarEffect.ts](https://github.com/pixiebrix/pixiebrix-extension/blob/main/src/bricks/effects/ToggleQuickbarEffect.ts)
- [src/bricks/effects/tourEffect.ts](https://github.com/pixiebrix/pixiebrix-extension/blob/main/src/bricks/effects/tourEffect.ts)
- [src/bricks/PipelineVisitor.ts](https://github.com/pixiebrix/pixiebrix-extension/blob/main/src/bricks/PipelineVisitor.ts)
- [src/bricks/readers/factory.ts](https://github.com/pixiebrix/pixiebrix-extension/blob/main/src/bricks/readers/factory.ts)
- [src/bricks/readers/getAllReaders.ts](https://github.com/pixiebrix/pixiebrix-extension/blob/main/src/bricks/readers/getAllReaders.ts)
- [src/bricks/readers/jquery.ts](https://github.com/pixiebrix/pixiebrix-extension/blob/main/src/bricks/readers/jquery.ts)
- [src/bricks/readers/PageMetadataReader.ts](https://github.com/pixiebrix/pixiebrix-extension/blob/main/src/bricks/readers/PageMetadataReader.ts)
- [src/bricks/readers/window.ts](https://github.com/pixiebrix/pixiebrix-extension/blob/main/src/bricks/readers/window.ts)
- [src/bricks/registry.ts](https://github.com/pixiebrix/pixiebrix-extension/blob/main/src/bricks/registry.ts)
- [src/bricks/renderers/customForm.ts](https://github.com/pixiebrix/pixiebrix-extension/blob/main/src/bricks/renderers/customForm.ts)
- [src/bricks/renderers/document.ts](https://github.com/pixiebrix/pixiebrix-extension/blob/main/src/bricks/renderers/document.ts)
- [src/bricks/renderers/getAllRenderers.ts](https://github.com/pixiebrix/pixiebrix-extension/blob/main/src/bricks/renderers/getAllRenderers.ts)
- [src/bricks/renderers/iframe.ts](https://github.com/pixiebrix/pixiebrix-extension/blob/main/src/bricks/renderers/iframe.ts)
- [src/bricks/renderers/MarkdownRenderer.ts](https://github.com/pixiebrix/pixiebrix-extension/blob/main/src/bricks/renderers/MarkdownRenderer.ts)
- [src/bricks/transformers/brickFactory.ts](https://github.com/pixiebrix/pixiebrix-extension/blob/main/src/bricks/transformers/brickFactory.ts)
- [src/bricks/transformers/component/TableReader.ts](https://github.com/pixiebrix/pixiebrix-extension/blob/main/src/bricks/transformers/component/TableReader.ts)
- [src/bricks/transformers/controlFlow/ForEach.ts](https://github.com/pixiebrix/pixiebrix-extension/blob/main/src/bricks/transformers/controlFlow/ForEach.ts)
- [src/bricks/transformers/controlFlow/ForEachElement.ts](https://github.com/pixiebrix/pixiebrix-extension/blob/main/src/bricks/transformers/controlFlow/ForEachElement.ts)
- [src/bricks/transformers/controlFlow/IfElse.ts](https://github.com/pixiebrix/pixiebrix-extension/blob/main/src/bricks/transformers/controlFlow/IfElse.ts)
- [src/bricks/transformers/controlFlow/MapValues.ts](https://github.com/pixiebrix/pixiebrix-extension/blob/main/src/bricks/transformers/controlFlow/MapValues.ts)
- [src/bricks/transformers/controlFlow/Retry.ts](https://github.com/pixiebrix/pixiebrix-extension/blob/main/src/bricks/transformers/controlFlow/Retry.ts)
- [src/bricks/transformers/controlFlow/TryExcept.ts](https://github.com/pixiebrix/pixiebrix-extension/blob/main/src/bricks/transformers/controlFlow/TryExcept.ts)
- [src/bricks/transformers/controlFlow/WithAsyncModVariable.ts](https://github.com/pixiebrix/pixiebrix-extension/blob/main/src/bricks/transformers/controlFlow/WithAsyncModVariable.ts)
- [src/bricks/transformers/ephemeralForm/formTransformer.ts](https://github.com/pixiebrix/pixiebrix-extension/blob/main/src/bricks/transformers/ephemeralForm/formTransformer.ts)
- [src/bricks/transformers/jq.ts](https://github.com/pixiebrix/pixiebrix-extension/blob/main/src/bricks/transformers/jq.ts)
- [src/bricks/transformers/mapping.ts](https://github.com/pixiebrix/pixiebrix-extension/blob/main/src/bricks/transformers/mapping.ts)
- [src/bricks/transformers/parseCsv.ts](https://github.com/pixiebrix/pixiebrix-extension/blob/main/src/bricks/transformers/parseCsv.ts)
- [src/bricks/transformers/ParseJson.ts](https://github.com/pixiebrix/pixiebrix-extension/blob/main/src/bricks/transformers/ParseJson.ts)
- [src/bricks/transformers/parseUrl.ts](https://github.com/pixiebrix/pixiebrix-extension/blob/main/src/bricks/transformers/parseUrl.ts)
- [src/bricks/transformers/regex.ts](https://github.com/pixiebrix/pixiebrix-extension/blob/main/src/bricks/transformers/regex.ts)
- [src/bricks/transformers/RunMetadataTransformer.ts](https://github.com/pixiebrix/pixiebrix-extension/blob/main/src/bricks/transformers/RunMetadataTransformer.ts)
- [src/bricks/transformers/searchText.ts](https://github.com/pixiebrix/pixiebrix-extension/blob/main/src/bricks/transformers/searchText.ts)
- [src/bricks/transformers/splitText.ts](https://github.com/pixiebrix/pixiebrix-extension/blob/main/src/bricks/transformers/splitText.ts)
- [src/bricks/transformers/template.ts](https://github.com/pixiebrix/pixiebrix-extension/blob/main/src/bricks/transformers/template.ts)
- [src/bricks/transformers/temporaryInfo/DisplayTemporaryInfo.ts](https://github.com/pixiebrix/pixiebrix-extension/blob/main/src/bricks/transformers/temporaryInfo/DisplayTemporaryInfo.ts)
- [src/bricks/transformers/temporaryInfo/popoverUtils.ts](https://github.com/pixiebrix/pixiebrix-extension/blob/main/src/bricks/transformers/temporaryInfo/popoverUtils.ts)
- [src/bricks/transformers/temporaryInfo/temporaryPanelProtocol.ts](https://github.com/pixiebrix/pixiebrix-extension/blob/main/src/bricks/transformers/temporaryInfo/temporaryPanelProtocol.ts)
- [src/bricks/transformers/tourStep/tourStep.ts](https://github.com/pixiebrix/pixiebrix-extension/blob/main/src/bricks/transformers/tourStep/tourStep.ts)
- [src/bricks/types.ts](https://github.com/pixiebrix/pixiebrix-extension/blob/main/src/bricks/types.ts)
- [src/bricks/util.ts](https://github.com/pixiebrix/pixiebrix-extension/blob/main/src/bricks/util.ts)
- [src/components/fields/schemaFields/fieldInputMode.ts](https://github.com/pixiebrix/pixiebrix-extension/blob/main/src/components/fields/schemaFields/fieldInputMode.ts)
- [src/components/fields/schemaFields/fieldTypeCheckers.ts](https://github.com/pixiebrix/pixiebrix-extension/blob/main/src/components/fields/schemaFields/fieldTypeCheckers.ts)
- [src/components/fields/schemaFields/integrations/integrationDependencyFieldUtils.ts](https://github.com/pixiebrix/pixiebrix-extension/blob/main/src/components/fields/schemaFields/integrations/integrationDependencyFieldUtils.ts)
- [src/components/fields/schemaFields/propTypes.ts](https://github.com/pixiebrix/pixiebrix-extension/blob/main/src/components/fields/schemaFields/propTypes.ts)
- [src/components/fields/schemaFields/schemaFieldUtils.ts](https://github.com/pixiebrix/pixiebrix-extension/blob/main/src/components/fields/schemaFields/schemaFieldUtils.ts)
- [src/contentScript/contextMenus.ts](https://github.com/pixiebrix/pixiebrix-extension/blob/main/src/contentScript/contextMenus.ts)
- [src/contentScript/elementReference.ts](https://github.com/pixiebrix/pixiebrix-extension/blob/main/src/contentScript/elementReference.ts)
- [src/contentScript/ephemeralFormProtocol.ts](https://github.com/pixiebrix/pixiebrix-extension/blob/main/src/contentScript/ephemeralFormProtocol.ts)
- [src/contentScript/externalProtocol.ts](https://github.com/pixiebrix/pixiebrix-extension/blob/main/src/contentScript/externalProtocol.ts)
- [src/contentScript/lifecycle.ts](https://github.com/pixiebrix/pixiebrix-extension/blob/main/src/contentScript/lifecycle.ts)
- [src/contentScript/messenger/api.ts](https://github.com/pixiebrix/pixiebrix-extension/blob/main/src/contentScript/messenger/api.ts)
- [src/contentScript/pageEditor/elementPicker.ts](https://github.com/pixiebrix/pixiebrix-extension/blob/main/src/contentScript/pageEditor/elementPicker.ts)
- [src/contentScript/sidebarDomControllerLite.ts](https://github.com/pixiebrix/pixiebrix-extension/blob/main/src/contentScript/sidebarDomControllerLite.ts)
- [src/contrib/automationanywhere/aaApi.ts](https://github.com/pixiebrix/pixiebrix-extension/blob/main/src/contrib/automationanywhere/aaApi.ts)
- [src/contrib/automationanywhere/aaFrameProtocol.ts](https://github.com/pixiebrix/pixiebrix-extension/blob/main/src/contrib/automationanywhere/aaFrameProtocol.ts)
- [src/contrib/automationanywhere/RunBot.ts](https://github.com/pixiebrix/pixiebrix-extension/blob/main/src/contrib/automationanywhere/RunBot.ts)
- [src/contrib/google/sheets/bricks/append.ts](https://github.com/pixiebrix/pixiebrix-extension/blob/main/src/contrib/google/sheets/bricks/append.ts)
- [src/contrib/google/sheets/bricks/lookup.ts](https://github.com/pixiebrix/pixiebrix-extension/blob/main/src/contrib/google/sheets/bricks/lookup.ts)
- [src/contrib/google/sheets/core/handleGoogleRequestRejection.ts](https://github.com/pixiebrix/pixiebrix-extension/blob/main/src/contrib/google/sheets/core/handleGoogleRequestRejection.ts)
- [src/contrib/google/sheets/core/sheetsApi.ts](https://github.com/pixiebrix/pixiebrix-extension/blob/main/src/contrib/google/sheets/core/sheetsApi.ts)
- [src/development/autoreload.ts](https://github.com/pixiebrix/pixiebrix-extension/blob/main/src/development/autoreload.ts)
- [src/development/messengerLogging.ts](https://github.com/pixiebrix/pixiebrix-extension/blob/main/src/development/messengerLogging.ts)
- [src/errors/businessErrors.ts](https://github.com/pixiebrix/pixiebrix-extension/blob/main/src/errors/businessErrors.ts)
- [src/errors/clientRequestErrors.ts](https://github.com/pixiebrix/pixiebrix-extension/blob/main/src/errors/clientRequestErrors.ts)
- [src/errors/contextInvalidated.ts](https://github.com/pixiebrix/pixiebrix-extension/blob/main/src/errors/contextInvalidated.ts)
- [src/errors/errorHelpers.ts](https://github.com/pixiebrix/pixiebrix-extension/blob/main/src/errors/errorHelpers.ts)
- [src/errors/genericErrors.ts](https://github.com/pixiebrix/pixiebrix-extension/blob/main/src/errors/genericErrors.ts)
- [src/hooks/auth.ts](https://github.com/pixiebrix/pixiebrix-extension/blob/main/src/hooks/auth.ts)
- [src/hooks/useMergeAsyncState.ts](https://github.com/pixiebrix/pixiebrix-extension/blob/main/src/hooks/useMergeAsyncState.ts)
- [src/hooks/useRefreshRegistries.ts](https://github.com/pixiebrix/pixiebrix-extension/blob/main/src/hooks/useRefreshRegistries.ts)
- [src/hooks/useUpdatableAsyncState.ts](https://github.com/pixiebrix/pixiebrix-extension/blob/main/src/hooks/useUpdatableAsyncState.ts)
- [src/integrations/integrationTypes.ts](https://github.com/pixiebrix/pixiebrix-extension/blob/main/src/integrations/integrationTypes.ts)
- [src/integrations/locator.ts](https://github.com/pixiebrix/pixiebrix-extension/blob/main/src/integrations/locator.ts)
- [src/integrations/registry.ts](https://github.com/pixiebrix/pixiebrix-extension/blob/main/src/integrations/registry.ts)
- [src/integrations/store/integrationsMigrations.ts](https://github.com/pixiebrix/pixiebrix-extension/blob/main/src/integrations/store/integrationsMigrations.ts)
- [src/integrations/util/getModDefinitionIntegrationIds.ts](https://github.com/pixiebrix/pixiebrix-extension/blob/main/src/integrations/util/getModDefinitionIntegrationIds.ts)
- [src/integrations/util/getUnconfiguredComponentIntegrations.ts](https://github.com/pixiebrix/pixiebrix-extension/blob/main/src/integrations/util/getUnconfiguredComponentIntegrations.ts)
- [src/integrations/util/locateSanitizedIntegrationConfigWithRetry.ts](https://github.com/pixiebrix/pixiebrix-extension/blob/main/src/integrations/util/locateSanitizedIntegrationConfigWithRetry.ts)
- [src/integrations/util/makeServiceContextFromDependencies.ts](https://github.com/pixiebrix/pixiebrix-extension/blob/main/src/integrations/util/makeServiceContextFromDependencies.ts)
- [src/integrations/util/permissionsHelpers.ts](https://github.com/pixiebrix/pixiebrix-extension/blob/main/src/integrations/util/permissionsHelpers.ts)
- [src/mv3/api.ts](https://github.com/pixiebrix/pixiebrix-extension/blob/main/src/mv3/api.ts)
- [src/pageEditor/slices/editorSelectors.ts](https://github.com/pixiebrix/pixiebrix-extension/blob/main/src/pageEditor/slices/editorSelectors.ts)
- [src/pageEditor/slices/editorSlice.ts](https://github.com/pixiebrix/pixiebrix-extension/blob/main/src/pageEditor/slices/editorSlice.ts)
- [src/pageEditor/slices/editorSliceHelpers.ts](https://github.com/pixiebrix/pixiebrix-extension/blob/main/src/pageEditor/slices/editorSliceHelpers.ts)
- [src/pageEditor/starterBricks/formStateTypes.ts](https://github.com/pixiebrix/pixiebrix-extension/blob/main/src/pageEditor/starterBricks/formStateTypes.ts)
- [src/pageEditor/starterBricks/pipelineMapping.ts](https://github.com/pixiebrix/pixiebrix-extension/blob/main/src/pageEditor/starterBricks/pipelineMapping.ts)
- [src/pageEditor/tabs/editTab/editHelpers.ts](https://github.com/pixiebrix/pixiebrix-extension/blob/main/src/pageEditor/tabs/editTab/editHelpers.ts)
- [src/pageEditor/uiState/uiStateTypes.ts](https://github.com/pixiebrix/pixiebrix-extension/blob/main/src/pageEditor/uiState/uiStateTypes.ts)
- [src/pageEditor/utils.ts](https://github.com/pixiebrix/pixiebrix-extension/blob/main/src/pageEditor/utils.ts)
- [src/pageScript/messenger/sender.ts](https://github.com/pixiebrix/pixiebrix-extension/blob/main/src/pageScript/messenger/sender.ts)
- [src/permissions/permissionsUtils.ts](https://github.com/pixiebrix/pixiebrix-extension/blob/main/src/permissions/permissionsUtils.ts)
- [src/registry/internal.ts](https://github.com/pixiebrix/pixiebrix-extension/blob/main/src/registry/internal.ts)
- [src/registry/memoryRegistry.ts](https://github.com/pixiebrix/pixiebrix-extension/blob/main/src/registry/memoryRegistry.ts)
- [src/registry/packageRegistry.ts](https://github.com/pixiebrix/pixiebrix-extension/blob/main/src/registry/packageRegistry.ts)
- [src/runtime/brickYaml.ts](https://github.com/pixiebrix/pixiebrix-extension/blob/main/src/runtime/brickYaml.ts)
- [src/runtime/extendModVariableContext.ts](https://github.com/pixiebrix/pixiebrix-extension/blob/main/src/runtime/extendModVariableContext.ts)
- [src/runtime/mapArgs.ts](https://github.com/pixiebrix/pixiebrix-extension/blob/main/src/runtime/mapArgs.ts)
- [src/runtime/pathHelpers.ts](https://github.com/pixiebrix/pixiebrix-extension/blob/main/src/runtime/pathHelpers.ts)
- [src/runtime/reducePipeline.ts](https://github.com/pixiebrix/pixiebrix-extension/blob/main/src/runtime/reducePipeline.ts)
- [src/runtime/renderers.ts](https://github.com/pixiebrix/pixiebrix-extension/blob/main/src/runtime/renderers.ts)
- [src/runtime/runtimeUtils.ts](https://github.com/pixiebrix/pixiebrix-extension/blob/main/src/runtime/runtimeUtils.ts)
- [src/sandbox/messenger/api.ts](https://github.com/pixiebrix/pixiebrix-extension/blob/main/src/sandbox/messenger/api.ts)
- [src/sandbox/messenger/executor.ts](https://github.com/pixiebrix/pixiebrix-extension/blob/main/src/sandbox/messenger/executor.ts)
- [src/services/baseQuery.ts](https://github.com/pixiebrix/pixiebrix-extension/blob/main/src/services/baseQuery.ts)
- [src/services/errorService.ts](https://github.com/pixiebrix/pixiebrix-extension/blob/main/src/services/errorService.ts)
- [src/starterBricks/contextMenu.ts](https://github.com/pixiebrix/pixiebrix-extension/blob/main/src/starterBricks/contextMenu.ts)
- [src/starterBricks/contextMenuReader.ts](https://github.com/pixiebrix/pixiebrix-extension/blob/main/src/starterBricks/contextMenuReader.ts)
- [src/starterBricks/factory.ts](https://github.com/pixiebrix/pixiebrix-extension/blob/main/src/starterBricks/factory.ts)
- [src/starterBricks/helpers.ts](https://github.com/pixiebrix/pixiebrix-extension/blob/main/src/starterBricks/helpers.ts)
- [src/starterBricks/menuItemExtension.ts](https://github.com/pixiebrix/pixiebrix-extension/blob/main/src/starterBricks/menuItemExtension.ts)
- [src/starterBricks/panelExtension.ts](https://github.com/pixiebrix/pixiebrix-extension/blob/main/src/starterBricks/panelExtension.ts)
- [src/starterBricks/registry.ts](https://github.com/pixiebrix/pixiebrix-extension/blob/main/src/starterBricks/registry.ts)
- [src/starterBricks/sidebarExtension.ts](https://github.com/pixiebrix/pixiebrix-extension/blob/main/src/starterBricks/sidebarExtension.ts)
- [src/starterBricks/tourController.ts](https://github.com/pixiebrix/pixiebrix-extension/blob/main/src/starterBricks/tourController.ts)
- [src/starterBricks/tourExtension.ts](https://github.com/pixiebrix/pixiebrix-extension/blob/main/src/starterBricks/tourExtension.ts)
- [src/starterBricks/triggerExtension.ts](https://github.com/pixiebrix/pixiebrix-extension/blob/main/src/starterBricks/triggerExtension.ts)
- [src/starterBricks/types.ts](https://github.com/pixiebrix/pixiebrix-extension/blob/main/src/starterBricks/types.ts)
- [src/store/editorMigrations.ts](https://github.com/pixiebrix/pixiebrix-extension/blob/main/src/store/editorMigrations.ts)
- [src/store/editorStorage.ts](https://github.com/pixiebrix/pixiebrix-extension/blob/main/src/store/editorStorage.ts)
- [src/store/enterprise/managedStorage.ts](https://github.com/pixiebrix/pixiebrix-extension/blob/main/src/store/enterprise/managedStorage.ts)
- [src/store/enterprise/singleSignOn.ts](https://github.com/pixiebrix/pixiebrix-extension/blob/main/src/store/enterprise/singleSignOn.ts)
- [src/store/extensionsMigrations.ts](https://github.com/pixiebrix/pixiebrix-extension/blob/main/src/store/extensionsMigrations.ts)
- [src/store/extensionsSlice.ts](https://github.com/pixiebrix/pixiebrix-extension/blob/main/src/store/extensionsSlice.ts)
- [src/store/extensionsStorage.ts](https://github.com/pixiebrix/pixiebrix-extension/blob/main/src/store/extensionsStorage.ts)
- [src/store/settings/settingsMigrations.ts](https://github.com/pixiebrix/pixiebrix-extension/blob/main/src/store/settings/settingsMigrations.ts)
- [src/store/settings/settingsSlice.ts](https://github.com/pixiebrix/pixiebrix-extension/blob/main/src/store/settings/settingsSlice.ts)
- [src/telemetry/BackgroundLogger.ts](https://github.com/pixiebrix/pixiebrix-extension/blob/main/src/telemetry/BackgroundLogger.ts)
- [src/telemetry/initRollbar.ts](https://github.com/pixiebrix/pixiebrix-extension/blob/main/src/telemetry/initRollbar.ts)
- [src/telemetry/logging.ts](https://github.com/pixiebrix/pixiebrix-extension/blob/main/src/telemetry/logging.ts)
- [src/telemetry/reportError.ts](https://github.com/pixiebrix/pixiebrix-extension/blob/main/src/telemetry/reportError.ts)
- [src/telemetry/reportEvent.ts](https://github.com/pixiebrix/pixiebrix-extension/blob/main/src/telemetry/reportEvent.ts)
- [src/telemetry/trace.ts](https://github.com/pixiebrix/pixiebrix-extension/blob/main/src/telemetry/trace.ts)
- [src/themes/themeUtils.ts](https://github.com/pixiebrix/pixiebrix-extension/blob/main/src/themes/themeUtils.ts)
- [src/types/annotationTypes.ts](https://github.com/pixiebrix/pixiebrix-extension/blob/main/src/types/annotationTypes.ts)
- [src/types/schemaTypes.ts](https://github.com/pixiebrix/pixiebrix-extension/blob/main/src/types/schemaTypes.ts)
- [src/utils/clipboardUtils.ts](https://github.com/pixiebrix/pixiebrix-extension/blob/main/src/utils/clipboardUtils.ts)
- [src/utils/ConsoleLogger.ts](https://github.com/pixiebrix/pixiebrix-extension/blob/main/src/utils/ConsoleLogger.ts)
- [src/utils/deploymentUtils.ts](https://github.com/pixiebrix/pixiebrix-extension/blob/main/src/utils/deploymentUtils.ts)
- [src/utils/detectRandomString.ts](https://github.com/pixiebrix/pixiebrix-extension/blob/main/src/utils/detectRandomString.ts)
- [src/utils/enrichAxiosErrors.ts](https://github.com/pixiebrix/pixiebrix-extension/blob/main/src/utils/enrichAxiosErrors.ts)
- [src/utils/expressionUtils.ts](https://github.com/pixiebrix/pixiebrix-extension/blob/main/src/utils/expressionUtils.ts)
- [src/utils/extensionUtils.ts](https://github.com/pixiebrix/pixiebrix-extension/blob/main/src/utils/extensionUtils.ts)
- [src/utils/inference/inferSingleElementSelector.ts](https://github.com/pixiebrix/pixiebrix-extension/blob/main/src/utils/inference/inferSingleElementSelector.ts)
- [src/utils/inference/selectorInference.ts](https://github.com/pixiebrix/pixiebrix-extension/blob/main/src/utils/inference/selectorInference.ts)
- [src/utils/modUtils.ts](https://github.com/pixiebrix/pixiebrix-extension/blob/main/src/utils/modUtils.ts)
- [src/utils/objectUtils.ts](https://github.com/pixiebrix/pixiebrix-extension/blob/main/src/utils/objectUtils.ts)
- [src/utils/parseDataUrl.ts](https://github.com/pixiebrix/pixiebrix-extension/blob/main/src/utils/parseDataUrl.ts)
- [src/utils/parseDefinitionList.ts](https://github.com/pixiebrix/pixiebrix-extension/blob/main/src/utils/parseDefinitionList.ts)
- [src/utils/parseDomTable.ts](https://github.com/pixiebrix/pixiebrix-extension/blob/main/src/utils/parseDomTable.ts)
- [src/utils/promiseUtils.ts](https://github.com/pixiebrix/pixiebrix-extension/blob/main/src/utils/promiseUtils.ts)
- [src/utils/sanitize.ts](https://github.com/pixiebrix/pixiebrix-extension/blob/main/src/utils/sanitize.ts)
- [src/utils/storageUtils.ts](https://github.com/pixiebrix/pixiebrix-extension/blob/main/src/utils/storageUtils.ts)
- [src/utils/stringUtils.ts](https://github.com/pixiebrix/pixiebrix-extension/blob/main/src/utils/stringUtils.ts)
- [src/utils/urlUtils.ts](https://github.com/pixiebrix/pixiebrix-extension/blob/main/src/utils/urlUtils.ts)
- [src/validators/generic.ts](https://github.com/pixiebrix/pixiebrix-extension/blob/main/src/validators/generic.ts)
- [src/vendors/pkce.ts](https://github.com/pixiebrix/pixiebrix-extension/blob/main/src/vendors/pkce.ts)

**Comment by twschiller** [comment]
We haven't seen any problems with this during dogfooding. Closing for now and will re-open if it comes up during the beta
