### ISSUE TITLE
Replace field toggle symbols with updated SVG icons

### ISSUE THREAD

**Issue by BLoe** [pixiebrix/pixiebrix-extension#2164]
Update the field toggle options to show the SVG icons from the designer instead of text "symbols"

**Comment by twschiller** [comment]
@BLoe could you pass along the SVG icon folder?

**Comment by BALEHOK** [comment]
Update `https://github.com/pixiebrix/pixiebrix-extension/blob/16dbaf91eab6d1f121452ba955f8be1461841df7/src/components/fields/schemaFields/v3/BasicSchemaField.tsx` and `https://github.com/pixiebrix/pixiebrix-extension/blob/16dbaf91eab6d1f121452ba955f8be1461841df7/src/components/fields/schemaFields/widgets/TemplateToggleWidget.tsx`.
