### ISSUE TITLE
SVG Marketplace Icons broken in brick selection modal

### ISSUE THREAD

**Issue by twschiller** [pixiebrix/pixiebrix-extension#2165]
Release 1.4.11-beta.1. Note the last Google Search brick. The SVG is there but it's tiny

![image](https://user-images.githubusercontent.com/1879821/146432378-9bcab6b5-e63d-48f7-9e34-292473300de0.png)

**Comment by twschiller** [comment]
@fregante I assigned to you since I suspect it might have to do with some SVG work you were doing?

**Comment by twschiller** [comment]
Another example

![image](https://user-images.githubusercontent.com/1879821/146432884-9ac25df7-6882-4b0b-aaf0-bd369c692c92.png)

**Comment by fregante** [comment]
> some SVG work you were doing?

I don't remember doing any SVG work recently. If this broke just now, it's not esbuild-loader either. I don't see anything relevant in my commits in the past 3 weeks other than a generic messenger PR: https://github.com/pixiebrix/pixiebrix-extension/pull/2050

I'll take a very quick look now

**Comment by fregante** [comment]
Ah yes
