### ISSUE TITLE
Block error shown on wrong block

### ISSUE THREAD

**Issue by BALEHOK** [pixiebrix/pixiebrix-extension#2169]
Steps:
1. Get a runtime block error.
2. See the error is shown for a block.
3. Remove the block.

Expected result: The error is not visible in the editor.

Actual result: the error is bound to the next block in the pipeline.

Block with the error:
![image](https://user-images.githubusercontent.com/3116723/146534387-edb22c45-2ed3-4434-88e3-5050f0379231.png)

After the block removed:
![image](https://user-images.githubusercontent.com/3116723/146534472-10662dfa-fb70-45eb-b0a1-1d825ac2a28a.png)

**Comment by twschiller** [comment]
@BALEHOK these 3 issues I think are all duplicates?

https://github.com/pixiebrix/pixiebrix-extension/issues/2078
https://github.com/pixiebrix/pixiebrix-extension/issues/2046
https://github.com/pixiebrix/pixiebrix-extension/issues/2169
