### ISSUE TITLE
Affordance for end-user to configure the quickbar shortcut

### ISSUE THREAD

**Issue by twschiller** [pixiebrix/pixiebrix-extension#2189]
**Context**
- The quickbar is mapped to "Cmd+K" and it's Windows equivalent
- Low priority since we for our current main clients we don't think there's a shortcut conflict

**Open Questions**
- If we implement https://github.com/pixiebrix/pixiebrix-extension/issues/2188, the user can change on the Chrome Shortcuts page? 
- Is it possible to also provide a field on our options page that updates it? (E.g., because Chrome trusts the configuration action since it was user-initiated, like it does for permission requests?)

**Related**
- https://github.com/pixiebrix/pixiebrix-extension/issues/2188

**References**
- Some discussion: https://github.com/pixiebrix/pixiebrix-extension/issues/1866#issuecomment-991737907

**Comment by fregante** [comment]
> * Is it possible to also provide a field on our options page that updates it? (E.g., because Chrome trusts the configuration action since it was user-initiated, like it does for permission requests?)

No 👇 

> * `chrome.commands` does not give us any control. We can't set, check, nor link to the page to set a shortcut. We'd only be limited to instructions like _"Open the extensions page, click here, click there, etc."_ We only receive a "command" event.

**Comment by twschiller** [comment]
Closing because we now link the user to the Chrome shortcuts entry
