### ISSUE TITLE
Look into error feedback speed in Page Editor

### ISSUE THREAD

**Issue by twschiller** [pixiebrix/pixiebrix-extension#2216]
- Sometimes it can take 5-10+ seconds for trace and error information to show up

**Possible Causes**
- Trace database not being cleared out (e.g., delete old extension run on on new run)
- We're not actually using the IDB index when querying for the given runId. We need to look into how these run ids work?

**Diagnosis**
- Seems like it gets worse as there more traces - so probably related to our use of IDB

**Comment by BALEHOK** [comment]
What I've learned so far.

**Trace**
Average `getLatestRunByExtensionId` execution time (each entry shows total time from the beginning of the function):
0.928955078125 ms getDB
1.15380859375 ms transaction
113.5498046875 ms matches loop
113.77490234375 ms sorting
114.450927734375 ms total

With querying by index [see PR](https://github.com/pixiebrix/pixiebrix-extension/pull/2250/files#diff-a68351ab154fdb695bbd3fac44c714da9e61717dabd75a92c8288eecb6cfc202R208-R212):
0.759033203125 ms getDB
2.052001953125 ms transaction (transaction + matches)
2.2080078125 ms sorted
2.287841796875 ms total

**Logs**
1. `useLogEntries` is called multiple times and cause invocation of multiple refreshing (2-3 cycles running in parallel).
2. Switching between Edit and Logs tabs adds more loading cycles.
3. `getLog` takes about 300-600 ms to complete. Getting logs in component with `useLogEntries` takes 2,5-3 seconds.

Average execution time of `getLog` (each entry show total time from the beginning of the function):
14.406005859375 ms getDB
15.81396484375 ms transaction
217.89990234375 ms matches
220.87109375 total ms

**Comment by BALEHOK** [comment]
Thoughts on possible improvements:
1. Polling should never run in more than one thread. It has to be gated on the service level (`trace.ts` and `loggin.ts`). Alternatively the polling mechanism can utilize Redux and defined on the store level.
2. Fetching of logs from IDB should be refactored with IDB indexes.

**Comment by BALEHOK** [comment]
A couple of new findings:
1. Edit Page form validation
Form Validation in [`usePipelineField` hook](https://github.com/pixiebrix/pixiebrix-extension/blob/0b93f21817d5c6202f02d4e27b117dedc721af6a/src/devTools/editor/hooks/usePipelineField.ts#L73) takes ~80-100 ms. [`validatePipelineBlocks`](https://github.com/pixiebrix/pixiebrix-extension/blob/0b93f21817d5c6202f02d4e27b117dedc721af6a/src/devTools/editor/hooks/usePipelineField.ts#L48) (the part where we perform pipeline validation and apply trace errors)  takes ~0.5-1 ms, i.e. it looks like a place we should not worry about.

Perf trace:
```
usePipelineField.ts:58 validatePipelineBlocks took: 0.10000002384185791ms
usePipelineField.ts:83 entire form validation took 84.89999997615814 ms
```

2. Fetching logs
Usually we fetch logs by index (`extensionId` or `blueprintId`), [`logging.getLog`](https://github.com/pixiebrix/pixiebrix-extension/blob/5d3c0e6b8ee5641b143a267aba6489f96018c45b/src/background/logging.ts#L148). Then we filter the fetched entries by the context in JS. This matching takes relatively small amount of time.

Perf traces (having ~14k log entries in IDB) :
``` javascript
{
  entries: 3500, // number of fetched log entries (filtered by blueprintId)
  entriesTime: 424, // time of IDB request
  matchingTime: 1.600000023841858 // time to match by rest of context
  totalTime: 425.60000002384186,
},
{
  entries: 3700, // number of fetched log entries (filtered by blueprintId)
  entriesTime: 223.70000004768372, // time of IDB request
  matchingTime: 1.0999999046325684, // time to match by rest of context
  totalTime: 224.79999995231628,
}
```
