### ISSUE TITLE
`@pixiebrix/uipath/app` has large icon in editor

### ISSUE THREAD

**Issue by fregante** [pixiebrix/pixiebrix-extension#2236]
<img width="205" alt="Screen Shot 3" src="https://user-images.githubusercontent.com/1402241/147063837-a7d607fb-22de-4235-a84c-00fa4a014ce2.png">

This is because it has `2em` in its attributes, overriding the regular styles. This likely happens with other custom bricks as well.

**Comment by twschiller** [comment]
> This is because it has 2em in its attributes

You mean the SVG file itself, or somewhere else?

Or is this systematic with the icon changes you had made here?: https://github.com/pixiebrix/pixiebrix-extension/pull/2168

**Comment by fregante** [comment]
I didn't look into where they're set, but yes it's related to that change, kind of. 2em was fine before but that PR made the icons smaller. Will update. 

Also I'm seeing a possible improvement: 

- [ ] align the brick text if the variable name is missing
