### ISSUE TITLE
Enhance copy/paste brick functionality to work when copying service fields to separate extensions

### ISSUE THREAD

**Issue by BLoe** [pixiebrix/pixiebrix-extension#2240]
This follows on from #2036.

When a brick with a service selected in a service field is copied to a different extension, that extension doesn't have the same service config on the `element` in the formik state, so the variable reference from the select dropdown doesn't match up to anything, and the field appears empty (unselected). Currently, the workaround is that user can simply click the dropdown and re-select a service. We should enhance the `pasteBlock()` function to also set up the proper service config if it detects a service field in the brick being copied.

**Comment by twschiller** [comment]
We should bump the priority of this a bit. It also impacts the PixieBrix API-based extensions, where the service dropdown is hidden, so there's really hard to debug errors: https://github.com/pixiebrix/pixiebrix-extension/issues/2444

**Comment by BLoe** [comment]
@twschiller Are we okay with just clearing the selected service value when you paste a brick with a service field? Then, the default service field behavior will run as if you just added the brick in the first place. It's pretty complicated to take an output key (e.g. `uipath: "@uipath"`) and back all the way out through the select options to a service id to a service auth.

**Comment by BLoe** [comment]
_Discussed this in standup, clearing the selected service is correct here 👍_

(cc @twschiller)
