### ISSUE TITLE
`ConfirmationModal` fadeout animation missing

### ISSUE THREAD

**Issue by mnholtz** [pixiebrix/pixiebrix-extension#2246]
It looks like the fadeout animation on ConfirmationModal is missing on Cancel and Confirm actions. One place this can be observed is in the Admin Console, [on the GroupDetail page's "Delete Group" action](http://github.com/pixiebrix/pixiebrix-app/blob/0b1fbb4f9e3cbf064d5656147b061c5054c422f3/pixiebrix-app/src/pages/groups/GroupDetailPage.tsx#L45-L50).

Related:
https://github.com/pixiebrix/pixiebrix-app/pull/904#discussion_r774251375

**Comment by twschiller** [comment]
@abdullah4244 Here's the code for this one:

https://github.com/pixiebrix/pixiebrix-extension/blob/b684435eb529d731be3ae04ca38e5527c5dce9b2/src/components/ConfirmationModal.tsx#L47-L47

You might want to add an example to storybook. For examples of usage, look for modals.showConfirmation in the code

**Comment by abdullah4244** [comment]
@twschiller @mnholtz  I have fixed the issue but changes are in pixiebrix-app rather than extension so shouldn't we create issue in that repo?
here's the working demo

https://www.loom.com/share/7c2007e3bef047b19612e85407c512f7

**Comment by twschiller** [comment]
>  have fixed the issue but changes are in pixiebrix-app rather than extension so shouldn't we create issue in that repo?

@abdullah4244  to clarify my earlier comment: https://github.com/pixiebrix/pixiebrix-extension/issues/2246#issuecomment-1125566913

- @mnholtz please confirm, but I believe this bug ticket is for modals that are built using [ConfirmationModal](https://github.com/pixiebrix/pixiebrix-extension/blob/b684435eb529d731be3ae04ca38e5527c5dce9b2/src/components/ConfirmationModal.tsx#L47-L47).  @abdullah4244's loom is showing for the Create Group modal
- The Confirmation Modal and the useModals hooks are in the extension repository. So we need to be including a PR for the extension repository
- Please also add an example of showConfirmation and the modal to Storybook. To do this, you can make a story that has a button that when clicks, shows the confirmation modal

**Comment by mnholtz** [comment]
> @mnholtz please confirm, but I believe this bug ticket is for modals that are built using [ConfirmationModal](https://github.com/pixiebrix/pixiebrix-extension/blob/b684435eb529d731be3ae04ca38e5527c5dce9b2/src/components/ConfirmationModal.tsx#L47-L47).

@twschiller @abdullah4244  I don't remember what I was originally thinking when I wrote this ticket, but I'm poking around modals in the extension and the app right now and the missing animation is not exclusive to ConfirmationModal.

**Comment by abdullah4244** [comment]
> > have fixed the issue but changes are in pixiebrix-app rather than extension so shouldn't we create issue in that repo?
> 
> @abdullah4244 to clarify my earlier comment: [#2246 (comment)](https://github.com/pixiebrix/pixiebrix-extension/issues/2246#issuecomment-1125566913)
> 
> * @mnholtz please confirm, but I believe this bug ticket is for modals that are built using [ConfirmationModal](https://github.com/pixiebrix/pixiebrix-extension/blob/b684435eb529d731be3ae04ca38e5527c5dce9b2/src/components/ConfirmationModal.tsx#L47-L47).  @abdullah4244's loom is showing for the Create Group modal
> * If the bug applies to all modals, what's the fix? We may need to add adapt it to both the extension project and the app project
> * The Confirmation Modal and the useModals hooks are in the extension repository. So we need to be including a PR for the extension repository
> * Please also add an example of showConfirmation and the modal to Storybook. To do this, you can make a story that has a button that when clicks, shows the confirmation modal

@twschiller @mnholtz  basically issue is with not the modal Component itself but with the how modal is being rendered 

current logic is being applied like this 

showAdd && <ConfirmationModal/>  or showAdd && <CreateGroupModal/> 

i.e if our showAdd state is true then Modal COmponent will render rather than that 
we have to use something like 
react Bootstrap Modal component comes up with show Prop that handles Modal visibility so we will do something like this

<Modal show={showAdd} >

**Comment by twschiller** [comment]
Thanks for investigating. For now, could you just fix on ConfirmationModal? 

I will create separate tickets to refactor our other modal usage now that we know the animation issue. I don't want to prioritize it at the moment though
