### ISSUE TITLE
Quickbar font family isolation

### ISSUE THREAD

**Issue by twschiller** [pixiebrix/pixiebrix-extension#2294]
I think we need to explicitly set the font-family and some other properties in the quick bar?

On cnn.com (note icon vertical alignment issues):
![image](https://user-images.githubusercontent.com/1879821/148159588-85f4bc42-b8db-47b5-839e-9c928bae4cf0.png)

On news.ycombinator.com
![image](https://user-images.githubusercontent.com/1879821/148159639-14a78a49-5cd5-4b81-90cf-3d8688839c31.png)

On foxnews.com
![image](https://user-images.githubusercontent.com/1879821/148159668-b35ef7ef-226a-4f13-9643-897f1265a3ba.png)

On pbx-vue-element admin
![image](https://user-images.githubusercontent.com/1879821/148159702-1855d269-0f7d-4e62-a514-e7937c46c77d.png)

**Comment by fregante** [comment]
_I forgot the door open._ I'll review ReactShadowRoot’s usage

<img width="218" alt="Screen Shot 5" src="https://user-images.githubusercontent.com/1402241/148160581-79b758ca-a9f6-4ac4-a736-f87a87611438.png">
