### ISSUE TITLE
Blank advanced options card showing in v3

### ISSUE THREAD

**Issue by twschiller** [pixiebrix/pixiebrix-extension#2307]
Since we removed the `templateEngine` field in v3, there are some bricks that have a blank advanced options section (see screenshot, which is from the Document Builder):

![image](https://user-images.githubusercontent.com/1879821/148476612-5fa05657-8b45-42be-b533-302aa35b49ad.png)

We should show a `text-muted` message here that says no Advance Options available? That's probably preferable to hiding the section

**Comment by BLoe** [comment]
@twschiller I thought every brick would at least show the `if` conditional field here? The Document Builder doesn't allow conditional execution?
