### ISSUE TITLE
Add brick to read JSON object from HTML table

### ISSUE THREAD

**Issue by twschiller** [pixiebrix/pixiebrix-extension#2314]
**Input**
- Table selector

**Libraries**
- https://www.npmjs.com/package/tabletojson

**Reference**
- https://docs.pixiebrix.com/8676a48f3f1c44ca8339d00a4c9b88e1

**Potential Improvements**
- If the element itself is not a table, try to find the table that contains it. (Or the nearest descendent?)

**Comment by fregante** [comment]
Note: tabletojson imports both cheerio and got (like `request`) and thus it's not really a browser module 😰 https://bundlephobia.com/package/tabletojson

Would it be worth making an alternative for scratch? I'd be available

**Comment by twschiller** [comment]
@fregante, sounds like we'll want to make our own. Should probably split out the table parser as a separate package. 

To start, we just need handle very simple cases:
- Single header row
- A header column (property table), where each row is a `<th>Property</th><td>Value</td>`

**Comment by twschiller** [comment]
Let's just put in this repository for now. As we develop this sort of functionality that also has parts that make sense stand-alone we might consider a mono-repo like approach

The must haves right now are:
- Single header row. Should be parsed to an array of `Array<{[header]: value}>`
- A header column (property table), where each row is a `<th>Property</th><td>Value</td>`. Should be parsed to `{[property]: value}`

The brick input schema would be:
```yaml
selector:
   type: string
   format: selector
   description: The table selector
```

Nice to have:
- If the element itself is not a table, try to find the table that contains it. (Or the nearest descendent?)

**Comment by fregante** [comment]
I already started work on this, but figuring out the table’s direction is not foolproof. Example:

<table>
<tr>
	<th>
	<th>Value
<tr>
	<th>Color
	<td>Red
</table>

Should it be `[{Value: "Red"}]`?

It's a little more clear in this case:


<table>
<tr>
	<th>
	<th>Value
<tr>
	<th>Color
	<td>Red
<tr>
	<th>Size
	<td>Big
</table>

`[{Color: "Red", Size: "Big"}]`

`tabletojson` only supports tables with headers on top for example

**Comment by BLoe** [comment]
And that second case could also be `[{"": "Color", Value: "Red"}, {"": "Size", Value: "Big"}], right? Maybe the direction of the table should also be an input property in the block schema?

**Comment by fregante** [comment]
Indeed it's possible that we don't need to guess anything. When the user picks a table they can decide direction and how many rows/columns to discard for example. In my example the setting would be:

- direction: column
- 1st row: discard
- 1st column: use as headers

**Comment by BLoe** [comment]
It would be neat if there was some sort of table selector tool where they can drag a box around any part of a table on a page. But, unless there's a library that can accomplish this, definitely too large of a scope to develop ourselves I think right now.
