### ISSUE TITLE
Error when BasicSchemaField mutates `schema.additionalProperties`

### ISSUE THREAD

**Issue by twschiller** [pixiebrix/pixiebrix-extension#2345]
Encountered on the Zapier brick (while investigating): https://github.com/pixiebrix/pixiebrix-extension/issues/1938

```
TypeError: Cannot add property additionalProperties, object is not extensible
    at BasicSchemaField (devtoolsPanel.js:112804:37)
    at renderWithHooks (vendors.js:65186:18)
    at mountIndeterminateComponent (vendors.js:68012:13)
```

This line looks wrong; the widgets/fields can't mutate the schema: http://github.com/pixiebrix/pixiebrix-extension/blob/94bd11d6016bae26e73b85032be3d6f0b97e3b06/src/components/fields/schemaFields/v3/BasicSchemaField.tsx#L406-L406

**Comment by BLoe** [comment]
The point here was that a field with `type: "object"` would still show the add-properties UI even if the `additionalProperties` value wasn't defined in the field schema. I guess this never came up in our testing or usage that we've seen? Probably just need to copy/mutate the schema input param into a new reference and then define it explicitly outside the spread `...props`.
