### ISSUE TITLE
Add ability to re-configure blueprint's options from the Page Editor

### ISSUE THREAD

**Issue by twschiller** [pixiebrix/pixiebrix-extension#2390]
Context
- During blueprint activation, a user enters options. These get added to each IExtension activated from the blueprint
- We will be adding the ability to edit/modify a blueprint's options in the Page Editor. Related: https://github.com/pixiebrix/pixiebrix-extension/issues/2389
- As a blueprint developer, I want to be able to test my blueprint's extensions with a variety of options
- As a Page Editor user, I want to re-configure options from the Page Editor

Wireframes (see "Editing Extension's Options")
![image](https://user-images.githubusercontent.com/1879821/149676470-a37d4172-9e90-4de7-b943-d402b784d565.png)

**Comment by corinnemayans** [comment]
Closing this out because we're covering it in a different way via https://github.com/pixiebrix/pixiebrix-extension/issues/4780
