### ISSUE TITLE
Dev Tools / Page Editor vertical resize gets "stuck" at smaller sizes

### ISSUE THREAD

**Issue by twschiller** [pixiebrix/pixiebrix-extension#2416]
Conversation
- https://pixiebrix.slack.com/archives/C02RAMRDF0R/p1642441633001100

**Comment by fregante** [comment]
That’s part of the Chrome UI and we can’t do anything about it

**Comment by twschiller** [comment]
> That’s part of the Chrome UI and we can’t do anything about it

Will keep on eye Chrome UI feature announcements to see if there's a way to mitigate in the future
