### ISSUE TITLE
Database dropdown not loading in Page Editor

### ISSUE THREAD

**Issue by twschiller** [pixiebrix/pixiebrix-extension#2421]
It's stuck in the loading state. It has probably errored out, but isn't wired to show the error:

![image](https://user-images.githubusercontent.com/1879821/149847542-d0165458-61e2-4d44-9193-d0ce61b4ab20.png)

**Comment by twschiller** [comment]
@BALEHOK let me know if this is a likely server problem. We've been refactoring some of the backend permissions code

**Comment by BALEHOK** [comment]
@twschiller Can't reproduce, works for me on the latest `main`

![image](https://user-images.githubusercontent.com/3116723/149940828-edfd47ba-e5e0-41e9-b613-73287ffc644a.png)

**Comment by twschiller** [comment]
@BALEHOK just saw this also happen on a call with a customer. Will look into if it's a permissions issue

**Comment by twschiller** [comment]
It's 503 error - seems like the API endpoint is doing something wrong

**Comment by twschiller** [comment]
Fixed in the app
