### ISSUE TITLE
Add mailto: brick

### ISSUE THREAD

**Issue by twschiller** [pixiebrix/pixiebrix-extension#2430]
If you use the Open Tab brick with a mailto link with Chrome, it doesn't actually open in the mail program. Instead it's just a blank tab with the URL filled in

I think we might need to inject an `a` tag somewhere and simulate a click?

Example: `mailto:todd@pixiebrix.com`

Reference:
- https://www.w3docs.com/snippets/html/how-to-create-mailto-links.html

**Comment by fregante** [comment]
That sounds strange. When using the regular window.open() API it should still open the mail software (and then leave a blank page). What happens when you click on mailto links on your computer? Live [example](mailto:user@example.com)

**Comment by fregante** [comment]
It works correctly for me (I have an app that just copies the email to the clipboard)

https://user-images.githubusercontent.com/1402241/150088594-94baca4a-6b43-40c5-abbb-d9323bb94de0.mov

It still makes sense to have a "Prepare email" brick to:

- make it easier to use ("Open a tab" with "mailto" doesn't make sense to non-webdevelopers)
- allow adding a body/subject via brick.

**Comment by twschiller** [comment]
> What happens when you click on mailto links on your computer? Live example

You're correct. The mailto setup is broken on one of my browser profiles. We can implement this in a YAML brick that wraps Open Tab mailto: with the support fields

**Comment by twschiller** [comment]
Brick is in marketplace: https://www.pixiebrix.com/marketplace/079f2ce2-2d3f-4dc3-b2cc-d2b76e8f61e9/
