### ISSUE TITLE
Suggest buttons in button placement mode

### ISSUE THREAD

**Issue by twschiller** [pixiebrix/pixiebrix-extension#2436]
Context
- Button placement is tricky - you have to click the right part of the button
- Training people to give multiple examples is tricky

Implementation Sketch
- Look for button elements, and elements with role=button
- Translucent overlay those when in insertion mode
- Each generated Overlay would need to know which element it corresponds to, so when the overlay is clicked the element is passed through as the selected element

Considerations:
- User should still be able to click somewhere else
- Don't generate overlays for hidden elements
- Still would be good to support selecting multiple to provide the templating algorithm multiple examples. Overlays could also be a nice way of showing which things you've selected
- Overlay the menu instead of the buttons? Having the user click the menu is better when all buttons are homogenous. But if the buttons are different inference would break. We could let the user choose which style? (This is out of scope)

**Comment by fregante** [comment]
> * Button placement is tricky - you have to click the right part of the button

The solution outlined in https://github.com/pixiebrix/pixiebrix-extension/issues/2436 would actually be beneficial here. My first example covers this exactly.

With filters (`a, button, [role=button]`) it feels like we could even reduce the overlay to _exclusively_ those areas. The picker currently completely fails if the user clicks anywhere but those.


---

As an alternative UI for this, possibly out of scope, we could also add placeholders for the buttons so the user knows exactly where it will end up. I feel that it's counterintuitive to have to click on "Contacts" when I really want the button to appear _next to it_.

For example the menu:

```
[Home] [About us] [Contacts]
```

would be temporarily shown as 

```
[Home] 🟣 [About us] 🟣 [Contacts] 🟣
```

which is simply the result of:

1. Find applicable elements on the page (this ticket)
2. Add a 🟣 next to each one

**Comment by twschiller** [comment]
I left a comment in the other ticket (read that one first), but will comment on menu specific items here.

Some considerations:
- Our menu/button extension point currently works by taking a 1) menu container element, and 2) if you want to prepend or append the element to it
- When you're placing a button, what you're clicking is generating "examples" for our button template inference (you can shift-click to select more than one example). This allows us to infer button templates in menus with heterogenous buttons.  
- We don't currently support the ability to add menu options inline. That'd require relative positioning based on: 1) index in the menu (so we'd need to be able accurately identify menu elements, or 2) relative position based on selector 

> As an alternative UI for this, possibly out of scope, we could also add placeholders for the buttons so the user knows exactly where it will end up

I like the idea of this, but isn't possible given the above considerations. Overall we're going to have to re-think the button extension point a bit to better support: 1) locations where there are not already buttons, 2) custom button styles

**Comment by fregante** [comment]
I suppose this is done for now.
