### ISSUE TITLE
Suggest inputs and content-editables in selection mode for Set Input Value brick

### ISSUE THREAD

**Issue by twschiller** [pixiebrix/pixiebrix-extension#2437]
Context
- Some inputs and content editables are finicky to click on

Implementation Sketch
- In selection mode, find all the `:input` and content editables and show an overlay
- Still allow the user to click on a non-overlay element
- I think we'll need to pass a "mode" to the "native" code that handles the overlay. E.g., there might be a "input" mode, and a "button-placement" mode (see https://github.com/pixiebrix/pixiebrix-extension/issues/2436)

Related
- https://github.com/pixiebrix/pixiebrix-extension/issues/2436

**Comment by fregante** [comment]
> * Some inputs and content editables are finicky to click on

Is this issue specific to fields? It feels to me that the selection process could be 2 step:
1. Click on an element
2. Allow refining the selection by showing the full list of parents

For example I click in:

```
<nav><a>…</a><a><span>Conta⬇️cts</span></a></nav>
```

`span` will be selected, but before confirming the selection we can show:

1. span
2. a
3. nav
4. body
5. html

This step could be reduced or skipped in cases where we expect `a, button`.


For this issue specifically, if the picker’s filter is `input, [contenteditable]` it will automatically pick the `contenteditable` once found.

Does the current picker have this sort of filtering mechanism?

**Comment by twschiller** [comment]
> Is this issue specific to fields? It feels to me that the selection process could be 2 step:

It's not specific to fields. There will be multiple scenarios where we want to suggest what to click on. 
- Form: Form Fill brick
- Fields: Form Fill, Set Input Value, Trigger Extension Point (Blur selector)
- Menu Buttons (role="menu", etc.): Menu Item (location selector)

Here's what I had in mind. Highlight all fields with translucent overlay. The goal being to remove any guesswork for clicking on something valid

![image](https://user-images.githubusercontent.com/1879821/151080249-fe645a52-623b-46ea-9910-1d063d714055.png)

I do think your approach is very useful, and will be necessary in the future. It's more for power-users though because you need a basic understanding of DOM to use it

With this ticket, I want to see how possible it to enable non-technical users (e.g., salespersons, etc.) filling out forms

**Comment by fregante** [comment]
The code for this exists but how do we go about adding the required selector? I think these fields (and related element picker) are generated via schema. A naive selector would be `input, textarea, [contenteditable]`. Maybe it needs `input:not([type=button])` and similar, which I can look into once we know how to customize this schema-generated picker.

**Comment by fregante** [comment]
Tentatively reassigning because @BLoe implemented a similar schema change recently:

- https://github.com/pixiebrix/pixiebrix-extension/pull/2025

Needed:

- `SelectorSelectorWidget` should accept a `filter` prop so that it can be passed to `userSelectElement` like we do in `src/nativeEditor/insertButton.tsx`
- Such `filter` should probably be part of the schema so any field can specify it

More context may be found in https://github.com/pixiebrix/pixiebrix-extension/pull/2508/files
