### ISSUE TITLE
Pass selection to quickbar actions

### ISSUE THREAD

**Issue by twschiller** [pixiebrix/pixiebrix-extension#2443]
Context:
- The quickbar is a great way to trigger a lot of actions without the navigational downsides of context menus
- When you press "Cmd+K" your current selection goes away
- So currently your quickbar actions can't reference the selection

User Story:
- As a user, I would like to use the quickbar to trigger a search for my current selection

Brainstorming:
- Add a permanent context menu item that triggers the quickbar with the current selection
- If PixieBrix already has access to a page, we can track changes to the selection and pass it to the quick bar
- Does Chrome have some way other of determining the selection at the time the shortcut was run?

**Comment by fregante** [comment]
> Add a permanent context menu item that triggers the quickbar with the current selection
I thought that context menus were an exact alternative to the quick bar. If you’re in the context menu, why not just trigger the action there?

**Comment by twschiller** [comment]
> I thought that context menus were an exact alternative to the quick bar. If you’re in the context menu, why not just trigger the action there?

I agree. The thinking was - have 1 context menu, but 20+ quick bar actions. There's far fewer downsides to having a lot of quickbar actions

The problem with having a lot of context menu items is that the UX for finding the one you want is bad if there's a lot of them

**Comment by twschiller** [comment]
As per [slack convo](https://pixiebrix.slack.com/archives/D024R1S2D9N/p1642690533021200), the likely fix will be to grab the selection before the quickbar autofocuses
