### ISSUE TITLE
Handle expressions in custom block options components

### ISSUE THREAD

**Issue by BLoe** [pixiebrix/pixiebrix-extension#2459]
Considerations:
* Some fields can be converted to use `SchemaField`
* Some need to be restricted to literals, independently
  * We can show an "edit in workshop" message for the individual field
* Some fields affect the rest of the block, and if expressions are detected, we'll need to bail on the whole block options component and show a workshop message

Note: Make sure we go through every block options component registered in `editors.ts`

**Comment by twschiller** [comment]
@BLoe For after 1.5.2, we need to make sure the way we report "Use Workshop to Edit" is consistent. The tabName one in this screenshot doesn't show the field name

![image](https://user-images.githubusercontent.com/1879821/151551330-55727231-31bc-4d0a-aa6d-09cc87c066fd.png)
