### ISSUE TITLE
Partially support non-native CSS selectors  for trigger "watch" mode

### ISSUE THREAD

**Issue by twschiller** [pixiebrix/pixiebrix-extension#2471]
Context
- Our trigger extension point supports "watch" mode, which attaches the trigger to new elements matching the pattern
- However, currently it only supports native CSS selectors

```typescript
export type AttachMode =
  // Attach handlers once (for any elements available at the time of attaching handlers) (default)
  | "once"
  // Watch for new elements and attach triggers to any new elements that matches the selector. Only supports native
  // CSS selectors (because it uses MutationObserver under the hood)
  | "watch";
```

Triaging:
- I'm not sure how urgent this is. A customer was hitting problems, but I need to double-check what selectors they were trying to do. I think they were trying use the contains selector

Related:
- http://github.com/pixiebrix/pixiebrix-extension/blob/762b48b54a1b5d155d3b05db361f3175d0d72dcf/src/extensionPoints/triggerExtension.ts#L429-L429

Brainstorming:
- If there's a native parent CSS selector (e.g., for a modal), the performance penalty of checking the non-native functionality of the selector (e.g., `:contains` on the sub elements might be OK in practice)

Example, if I'm putting a blur trigger on an input, we can use native selectors up for .modal div, and then run the rest on each mutation event

```
.modal div:contains("My Input Label") + div input
```

**Comment by twschiller** [comment]
@fregante any ideas here?

**Comment by fregante** [comment]
I was under the assumption that $.initialize actually supported jQuery selectors, but apparently it just uses qSA:

https://github.com/pixiebrix/pixiebrix-extension/blob/762b48b54a1b5d155d3b05db361f3175d0d72dcf/src/vendors/initialize.js#L96-L111

As a quick fix we could probably replace those `querySelectorAll` calls with `$.find`

**Comment by fregante** [comment]
> we can use native selectors up for .modal div, and then run the rest on each mutation event

I think we'd run into a couple of problems:

- parsing CSS selectors
- assuming that everything before `:contains` is actually static, while it might not be (e.g. the modal doesn't exist when we start watching for its children)

If performance is a concern perhaps we can replace `$.initialize` with a 300ms poller (when the tab is visible)

**Comment by twschiller** [comment]
Hmm, I didn't realize initialize didn't support JQuery selectors either. Here's the open ticket about support JQuery selectors: https://github.com/pie6k/jquery.initialize/issues/29 (looks like there's infinite loop issue, and one comment mentions a potential workaround)

Long-term, for performance reasons, we'll probably need to parse the selector

For now, agree a poller is the right way to go (and you're right we should pause which the tab isn't active. Should we use the Page Visibility API https://stackoverflow.com/a/35455211/402560?)

Ideally we'd just tweak the existing `initialize` export so this is handled transparently. We just need to check if the selector is a native (see [isNativeCssSelector](http://github.com/pixiebrix/pixiebrix-extension/blob/6861d42849561b5968e97c32d626ca58fdf88d5b/src/extensionPoints/helpers.ts#L100-L100)). And, if it's not we'd poll instead of attaching the mutation observer

**Comment by fregante** [comment]
It looks like everything we discussed was already implemented in:

https://github.com/pixiebrix/pixiebrix-extension/blob/128127ba77e413554f7e83273d1ba6e8107a6950/src/extensionPoints/helpers.ts#L186-L196

Should I just replace the following with `_initialize`?

https://github.com/pixiebrix/pixiebrix-extension/blob/128127ba77e413554f7e83273d1ba6e8107a6950/src/extensionPoints/triggerExtension.ts#L429-L447
