### ISSUE TITLE
Fix confusing copy in "remove extension" dialog

### ISSUE THREAD

**Issue by twschiller** [pixiebrix/pixiebrix-extension#2491]
The current remove extension dialog is misleading

Implementation Sketch:
- Change heading to "Remove Extension"
- If it's a personal extension, say that you can re-activate it from the bricks page
- If it's an extension that's from a recipe, say you can re-activate it from the blueprints page (look for _recipe.id)
- If it's an extension that's from a recipe and there are others installed, include a note that those others will remain active (look for other installed extensions with same _recipe.id)

Current Dialog
![image](https://user-images.githubusercontent.com/1879821/150840548-ce34dd40-729f-4cf3-a43a-651be575a372.png)

Related:
- https://pixiebrix.slack.com/archives/C02RAMRDF0R/p1642920792024700

**Comment by orliesaurus** [comment]
Do you want to add small (?) icons around the UI of the page editor to provide popover help at some point?

**Comment by twschiller** [comment]
Add some generic copy improvements here: https://github.com/pixiebrix/pixiebrix-extension/pull/2513. With these I think we can deprioritize the more specific instructions
