### ISSUE TITLE
Add support for Markdown in ephemeral forms

### ISSUE THREAD

**Issue by twschiller** [pixiebrix/pixiebrix-extension#2516]
Context:
- Customer wants to link to documentation/policies in forms
- More broadly, we've had asks for bulleted lists in forms

Implementation Sketch
- Run form and field description through markdown (and sanitize) before embedding in the form

Considerations
- @BALEHOK I think this just involves creating a custom template for React JSON Schema form?

**Comment by BALEHOK** [comment]
Markdown in field description needs a little bit more research.
