### ISSUE TITLE
Blueprints screen layout information hierarchy improvement

### ISSUE THREAD

**Issue by twschiller** [pixiebrix/pixiebrix-extension#2552]
Context
- With the Page Layout and the category sidebar, the main content of the consolidate blueprints page is in the bottom right 25% of the screen
- The "empty"/non-installed page state will help explain what it's for and how to find new stuff to add
- We want the category filters to be always shown for discoverability

Ideas:
- Don't use the Page Layout component. Since this is the home screen, there's not too much value in the space explaining what it is
- Move the Category filters to the right side, and make the font smaller

Questions
- Where does the "Open Public Maketplace Button get moved to"? We could try the bottom of the Category Filter Widget?

**Comment by twschiller** [comment]
I'm also still seeing the double scroll bar on this

![image](https://user-images.githubusercontent.com/1879821/153238291-ca902997-d0e5-4f44-aeec-a4e03e064ee9.png)

**Comment by mnholtz** [comment]
Additional improvements:
- [ ] Remove/rearrange information on Blueprint cards and rows per discoverability needs derived from user stories
    - [ ] i.e. include extra information on hover and on click
