### ISSUE TITLE
Show blueprint elements in the page editor side bar and group extensions under the blueprint

### ISSUE THREAD

**Issue by BLoe** [pixiebrix/pixiebrix-extension#2557]
Implement blueprints in the side bar of the page editor.

![image](https://user-images.githubusercontent.com/2801308/152043577-520d361c-98ab-4390-8982-7040c9004bb0.png)

* Accordian-style collapse of the extensions under a blueprint
* Blueprint Options tab shown in main config panel when the blueprint is selected

Questions:
* What should we show in the main panel Edit tab when the blueprint is selected?
* How should saving/removing extensions work?
  * Do we show save/reset/delete buttons for the entire blueprint itself? Probably would function like it does currently, just discard changes and remove from the page editor (deactivate), but don't mess with the published blueprint.
  * If I delete an extension and then save the blueprint, what happens?
    * - when all extensions have been removed from the blueprint?
    * - when there are other (remaining) extensions in the blueprint?
  * Do we include an option to add a new extension to a blueprint and save it to update the blueprint?
  * Create new blueprint?

Thinking of these roughly scoped steps:
1. Display blueprints and group extensions under them in the sidebar, show blueprint options tab when selecting the blueprint
2. Implement removing/editing extensions within a blueprint and saving to update the blueprint
3. Implement adding extensions to a blueprint
4. Implement creating a new blueprint from page editor

**Comment by twschiller** [comment]
@BLoe  I've added an updated wireframe which clarifies sizing etc:

![image](https://user-images.githubusercontent.com/1879821/152055670-42328c6f-98a0-40c3-8086-e3c8c68e0258.png)

**Comment by BLoe** [comment]
Remaining work:

1. Display blueprints and group extensions under them in the sidebar, show blueprint options tab when selecting the blueprint
  ~a. Display & group in sidebar~
  b. Implement blueprint Logs tab
  c. Show blueprint options tab on recipe instead of extensions
  d. Implement edit tab for blueprints to change input values
2. Implement removing/editing extensions within a blueprint and saving to update the blueprint
  a. Implement `SaveRecipeWizard`
  b. Implement `useRecipeSaver` hook to wire up to `SaveRecipeWizard`
3. Implement adding extensions to a blueprint
  a. Add existing extension to a blueprint
  b. Create new extension within a blueprint
  c. Move an extension from one blueprint to another
4. Implement creating a new blueprint from page editor
  a. Create blueprint using one or more existing extensions
  b. Create new empty blueprint (maybe disallow save until it has at least one extension?)
