### ISSUE TITLE
Quickbar not opening on some pages

### ISSUE THREAD

**Issue by twschiller** [pixiebrix/pixiebrix-extension#2568]
Context
- We've had reports of the quickbar not opening on some pages. We don't have a reliable reproduction of this
- I'm asking in Slack for more information (e.g., what sites, etc.)

Theories
- They don't have a Chrome shortcut defined
- The don't have a Chrome shortcut defined and PixieBrix doesn't have access to the page to add its own shortcut handler?
- They are running the shortcut on a special page (extension page, etc.)

Related Issues:
- https://github.com/pixiebrix/pixiebrix-extension/issues/2569

Conversation:
- https://pixiebrix.slack.com/archives/C02CN01JXAA/p1643832770040289

Rollbar Telemetry:
- https://rollbar.com/pixiebrix/pixiebrix/items/2138/

**Comment by orliesaurus** [comment]
This just happened:
- Opened the page where I have the quickbar installed
- Quickbar didnt open
- Opened console
- Saw error
- Refreshed page
- Quickbar worked!

https://www.loom.com/share/6cbbb9a3e3294fc58dd6da946846580b

**Comment by twschiller** [comment]
@fregante looks like a bug in "save" or guessSelectedElement

- http://github.com/pixiebrix/pixiebrix-extension/blob/d8b3624c7569c0b41ed7d5d38674e7af34b1351c/src/utils/selectionController.ts#L52-L52
- http://github.com/pixiebrix/pixiebrix-extension/blob/d8b3624c7569c0b41ed7d5d38674e7af34b1351c/src/utils/selectionController.ts#L31-L31
