### ISSUE TITLE
Instruct user to define a Chrome Quickbar shortcut when activating a quickbar extension

### ISSUE THREAD

**Issue by twschiller** [pixiebrix/pixiebrix-extension#2569]
**Implementation Sketch**
- On blueprint Activation Wizard, if an extension uses the quickbar, check if the user has a quickbar shortcut defined. If not show user documentation on how to configure
- On Page Editor, when the user adds a quickbar extension, check if the user has quickbar shortcut defined. If not show the user documentation on how to configure
- Update any places where we reference Ctrl-K as a hard-coded value: https://pixiebrix.slack.com/archives/C02RAMRDF0R/p1643904620159719

Related Code
- Page Editor Panel: http://github.com/pixiebrix/pixiebrix-extension/blob/d8b3624c7569c0b41ed7d5d38674e7af34b1351c/src/devTools/Editor.tsx#L95-L95
- Defining Activation Wizard Steps: http://github.com/pixiebrix/pixiebrix-extension/blob/d8b3624c7569c0b41ed7d5d38674e7af34b1351c/src/options/pages/marketplace/useWizard.ts#L53-L53

**Reference:**
- https://developer.chrome.com/docs/extensions/reference/commands/#verify-commands-registered

**Out of Scope**
- On active bricks page (soon to be consolidated blueprints page), show a warning if the user has a quickbar extension installed, but does not have a shortcut configured for the quickbar

**Comment by fregante** [comment]
Related/duplicate issue:

- https://github.com/pixiebrix/pixiebrix-extension/issues/2189
