### ISSUE TITLE
Warn users using non-Chrome Chromium browser

### ISSUE THREAD

**Issue by twschiller** [pixiebrix/pixiebrix-extension#2571]
Context
- Edge, Brave, etc. use the Chrome Web Store
- PixieBrix will happily install, but some features will be silently broken

Implementation Sketch
- On the options page, try to detect the browser
- If not Chrome, show a warning that PixieBrix is not officially supported on their browser (Nice to have: show what browser was detected)
- Allow the user to acknowledge and continue as normal
- Track the acknowledge in the settingsSlice, so it's persisted

@fregante what do you recommend for detecting the browser?

Reference/Related
- [Code for tracking if the user has "snoozed" updates](http://github.com/pixiebrix/pixiebrix-extension/blob/c85855923de2bb0112887433380e089949af7545/src/options/pages/deployments/DeploymentModal.tsx#L86-L86).

**Comment by fregante** [comment]
> @fregante what do you recommend for detecting the browser?

I'm sure that there are plenty of ultra-specific libraries for this but they're usually unnecessarily large for the purpose. What do you think about identifying a few "major" Chromium projects and then looking for their agents? Examples:

```
# Chrome:

Mozilla/5.0 (Macintosh; Intel Mac OS X 12_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.80 Safari/537.36


# Others:

Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Brave Chrome/83.0.4103.116 Safari/537.36

Mozilla/5.0 (Macintosh; Intel Mac OS X 12_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.80 Safari/537.36 OPR/83.0.4254.16

Mozilla/5.0 (Macintosh; Intel Mac OS X 12_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.80 YaBrowser/22.1.0 Yowser/2.5 Safari/537.36

Mozilla/5.0 (Macintosh; Intel Mac OS X 12_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.80 Safari/537.36 Vivaldi/4.3

Mozilla/5.0 (Macintosh; Intel Mac OS X 12_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.80 Safari/537.36 Edg/97.0.1072.69
```

As you can see they're all easily detectable: `/\b(Brave|OPR|YaBrowser|Vivaldi|Edg)\b`/

However we might just be able to use `isFirefox() || chrome.identity` to filter them out, which from what I understand is Google Chrome-specific?

**Comment by twschiller** [comment]
> from what I understand that API is Google Chrome-specific?

I think chrome.identity will be available (because launchwebauthflow should be available across browsers). IIRC, what they got rid of was the automatic linkage to the Google account?

https://www.npmjs.com/package/detect-browser is 27kb

I think we can just look at the URL scheme and see if it's `chrome-extension://`?

**Comment by fregante** [comment]
> > from what I understand that API is Google Chrome-specific?
> 
> I think chrome.identity will be available

I must have mistaken it with `gapi`. We can use that one too. Related:

- https://github.com/pixiebrix/pixiebrix-extension/issues/1636




> [npmjs.com/package/detect-browser](https://www.npmjs.com/package/detect-browser) is 27kb

`isUnsupported = () => / (Brave|OPR|YaBrowser|Vivaldi|Edg)\//.test(navigator.userAgent)` is 80 bytes 😜 


> I think we can just look at the URL scheme and see if it's `chrome-extension://`?

No such luck:

<img width="757" alt="Screen Shot 1" src="https://user-images.githubusercontent.com/1402241/152370940-e9e9db0d-a7ff-4e38-a006-32ddcfaf3530.png">
