### ISSUE TITLE
Add a "Ask a Question" button to the Page Editor

### ISSUE THREAD

**Issue by twschiller** [pixiebrix/pixiebrix-extension#2573]
Context
- As a Page Editor author, I'd like to receive help with a brick

Links
- Community Slack Link: https://join.slack.com/t/pixiebrixworkspace/shared_invite/zt-11jzgaxqq-BkvBJyRcyPHctXs5wqCGhw
- Calendly link: https://calendly.com/pixiebrix-support/ask-a-question
- Link to community: https://community.pixiebrix.com/ (that's the Discourse logo)

Considerations:
- Highlight the community slack option since it's the preferred option
- The button should be on the left side (to the right of logs) in the toolbar
- We should find SVG versions of the logos

Ideas
- Include likely response time? E.g., for Slack, "Get a response in minutes"

Wire Frames:
- ![image](https://user-images.githubusercontent.com/1879821/152267545-a3ffe1b3-7a39-4f9c-88a2-e2ccbb84e69b.png)

**Comment by orliesaurus** [comment]
I like the idea of giving the user what they'll be getting from each channel:
i.e.
- Slack: 
    - Label: Join Slack, get answers now 
- Forum:
    -  Label: Start a new discussion thread
-  Zoom:
    -  Label: Schedule a deep dive
