### ISSUE TITLE
Custom Quick Bar item is showing up on all pages regardless of documentUrlPattern

### ISSUE THREAD

**Issue by twschiller** [pixiebrix/pixiebrix-extension#2582]
Steps to Reproduce
- Create a Quick Bar item with a document and URL patterns for a site, e.g., https://news.ycombinator.com/*
- Save
- Open another site, e.g., https://www.cnn.com/
- Press the shortcut to open the quickbar

Expected behavior
- The quick bar item is not shown because the URL doesn't match

Actual Behavior
- The quick bar item is shown and can be run

Considerations
- The quickBar registry is a [singleton per contentScript](http://github.com/pixiebrix/pixiebrix-extension/blob/aef721d44d5d333f7d86e331a18bed7d95bcb362/src/components/quickBar/quickBarRegistry.tsx#L129-L129), so it shouldn't be a cross tab issue
- I think I might have just [forgotten to implement any documentUrlPattern logic](http://github.com/pixiebrix/pixiebrix-extension/blob/aef721d44d5d333f7d86e331a18bed7d95bcb362/src/extensionPoints/quickBarExtension.tsx#L300-L300) for enforcing documentUrlPattern
- It should probably be enforced in the [registerExtension method](http://github.com/pixiebrix/pixiebrix-extension/blob/aef721d44d5d333f7d86e331a18bed7d95bcb362/src/extensionPoints/quickBarExtension.tsx#L199-L199)

**Comment by fregante** [comment]
I'm not sure of where this should be done. `isAvailable` is called and it returns `false` as expected, but then the item is still in `this.extensions`, an array of `ResolvedExtension` that does not have `isAvailable` nor `documentUrlPattern`, so I don't see a way to enforce that in `registerExtensions`
