### ISSUE TITLE
Reload page vs. reload editor buttons confusing for slow-loading pages

### ISSUE THREAD

**Issue by twschiller** [pixiebrix/pixiebrix-extension#2586]
Context
- On slow loading webpages (e.g., some enterprise SaaS), the page editor connection to the host page times out because the document_idle event takes too long
- The "Reload page" button is the more prominent button, so people click that, which just reloads the slow page and doesn't solve the situation
- The user doesn't have a mental model of when they'd need to "Reload Editor" instead of reload page

Considerations
- Do we need a "reconnect" button as the primary action that attempts to reconnect without reloading the page or page editor?

**Comment by fregante** [comment]
> * reconnect without reloading the page or page editor

If that's possible, I think it should be done automatically. 

Can we look into avoiding the timeout altogether? Perhaps showing a "Waiting for the page" banner if it never comes on, instead of throwing an error. We can make the `connect` function smarter when reporting _why_ it's not connecting.
