### ISSUE TITLE
Fix missing IntelliJ import option for the FontAwesomeIcon component

### ISSUE THREAD

**Issue by mnholtz** [pixiebrix/pixiebrix-extension#2589]
In IntelliJ, when a component is used for the first time in a file, you may `right click` -> `Show context actons` -> `add import statement`. However, this option is no longer provided for the FontAwesomeIcon component. 

**Observations**
- Font awesome icons, e.g. `faStar`, do have the option to `add import statement`. 
- The import statement for FontAwesomeIcon used to work, but was very slow.

**Comment by fregante** [comment]
It seems to work for me on WebStorm 2021.3.2, I'm not sure what we could do about it either way since it's an IDE feature:



https://user-images.githubusercontent.com/1402241/152646564-76676768-ec7a-44be-bcd3-19e1fd58a7c4.mov

**Comment by mnholtz** [comment]
> can this be closed?

Yees, thanks @fregante
