### ISSUE TITLE
Broadcast performance regression

### ISSUE THREAD

**Issue by twschiller** [pixiebrix/pixiebrix-extension#2597]
Steps to reproduce:
- Create a button
- Add a "Context Reader" brick with window/target "broadcast"
- Perform some action with the results, e.g., show window alert with with "{{ @context | length }}"

Expected behavior:
- The alert shows nearly instantaneously

Actual behavior:
- The alert takes 1 second to run for 2 tabs

Considerations:
- The current speed is "ok" but IIRC we had it nearly instantaneous at some point when we had added the pre-check
- Not sure if the messaging is what's slow, or [the precheck of which tabs to message](http://github.com/pixiebrix/pixiebrix-extension/blob/6d303d7c9f3f3d4b8da2fd13b2a51b716cb0d475/src/background/executor.ts#L81-L81) is slow
- I don't think this is a 1.5.3 regression

**Comment by fregante** [comment]
Can't reproduce:

https://user-images.githubusercontent.com/1402241/152640168-22b48f1c-45d0-42c5-99d2-8bcc565eabfd.mov

This is the full log of a trigger (with just a log brick) in the local content script, which completes in less than 200ms

<img width="600" alt="Screen Shot 11" src="https://user-images.githubusercontent.com/1402241/152640215-977065cf-77b9-42d5-b615-f4f7464ea7d8.png">

**Comment by fregante** [comment]
It's the same with any number of tabs, using context reader:



https://user-images.githubusercontent.com/1402241/152640411-d7b358b2-8533-4aba-94d5-bd689ad2e22e.mov

**Comment by twschiller** [comment]
I'll close for now and see if it comes up again during QA. I haven't heard of any users running into issues
