### ISSUE TITLE
Read all tables bricks error on Wikipedia page

### ISSUE THREAD

**Issue by twschiller** [pixiebrix/pixiebrix-extension#2598]
Steps to reproduce:

- Run the read all tables brick on: https://en.wikipedia.org/wiki/Stanley_Cup
- Fails with "Cannot read properties of undefined (reading 'value')"

I haven't looked into which table(s) are causing the error. It might not be work reading from them

If reading a table fails, it should probably just skip that table, but log a warning?

**Comment by fregante** [comment]
This is due to the lack of colspan/rowspan support. `colspan` means that a table has this form:

<table>
<tr>
	<td>0
	<td>1
	<td>2
<tr>
	<td>0
	<td>1
<tr>
	<td>0
	<td>1
	<td>2
</table>

Let's see if I can patch this up without having to implement colspan (which is more involved)
