### ISSUE TITLE
Don't log uncaught cancelled promises

### ISSUE THREAD

**Issue by twschiller** [pixiebrix/pixiebrix-extension#2622]
Was this behavior introduced in https://github.com/pixiebrix/pixiebrix-extension/pull/2608? 

From utils.ts:325 

```
Uncaught (in promise) PromiseCancelled: Promise was cancelled
    at rejectOnCancelled (chrome-extension://mpjjildhmpddojocokjkgmlkkkfjnepo/contentScript.js:60741:15)
    at async RemoteMenuItemExtensionPoint.installMenus (chrome-extension://mpjjildhmpddojocokjkgmlkkkfjnepo/contentScript.js:52349:34)
    at async RemoteMenuItemExtensionPoint.reacquire (chrome-extension://mpjjildhmpddojocokjkgmlkkkfjnepo/contentScript.js:52328:13)
```

Related Code:
- [PromisedCancelled class](http://github.com/pixiebrix/pixiebrix-extension/blob/01906a0214403c332e5f7b2172e1efc4833554ff/src/utils.ts#L323-L323)

**Comment by fregante** [comment]
`Uncaught (in promise)` is a error thrown in a promise. They used to be caught:

https://github.com/pixiebrix/pixiebrix-extension/blame/cd9e3392c97e8d12fed09f9ea7583194ba4ed92d/src/telemetry/reportUncaughtErrors.ts#L35

but then they would still be manually logged:

https://github.com/pixiebrix/pixiebrix-extension/blob/cd9e3392c97e8d12fed09f9ea7583194ba4ed92d/src/telemetry/logging.ts#L51-L55

Appearing like:


<img width="753" alt="Screen Shot 4" src="https://user-images.githubusercontent.com/1402241/152666617-f784e633-bce9-49bc-a596-7c036e1f24c7.png">

**Comment by fregante** [comment]
I can hide specific errors from the console though. If you want I can completely silence all of them:

https://github.com/pixiebrix/pixiebrix-extension/blob/2d0b165fae6ca33d1b5a2ff61a522aa233cbbcdf/src/telemetry/rollbar.ts#L58-L62

What are the steps to show this promise cancelled error? Even "cancel"ing  a modal triggered by a context menu I don't see it.
