### ISSUE TITLE
Consolidate blueprints page perfomance

### ISSUE THREAD

**Issue by twschiller** [pixiebrix/pixiebrix-extension#2679]
Context
- Page becomes unresponsive when switching between categories/grouping, etc., if you have a lot of bricks or have access to a lot of bricks

Potential Causes:
- Not caching lookups: e.g., extension type
- Entries that aren't currently visible requesting data
- A lot of requests through the messenger API

Potential Solutions:
- Make sure we're caching async state, e.g., using Redux or cached promises
- Use react-virtualized
- Make calls the have to go through background page via messenger API work in bulk. E.g., add a fetchMany to the registry
- Show a loading indicator while the values are populating. (Using setTimeout) to perform the actual computation. So the interface will be slow but not hang
- Switch some to webworker (would like to avoid)

**Comment by mnholtz** [comment]
Closing because this issue is resolved: https://github.com/pixiebrix/pixiebrix-extension/pull/2759
