### ISSUE TITLE
"Successfully linked extension to your PixieBrix account" toast message always shows on Admin Console home page

### ISSUE THREAD

**Issue by twschiller** [pixiebrix/pixiebrix-extension#2701]
"Successfully linked extension to your PixieBrix account" toast message shows every time you load the admin console

Related code:
- http://github.com/pixiebrix/pixiebrix-extension/blob/6acfbe994f06388ee61bded5d9dbca058d78965b/src/auth/token.ts#L110-L110

Triaging:
- This is also reloading the extension

**Comment by fregante** [comment]
I can't reproduce this with the `main` version and 1.5.4 store version, even if I refresh the `?install=1` page

https://user-images.githubusercontent.com/1402241/154783474-0641fbe2-3e3d-41f4-96b9-0dc010231da7.mov

**Comment by twschiller** [comment]
> I can't reproduce this with the main version and 1.5.4 store version

There's some logic here to prevent passing data the old versions don't expect there: http://github.com/pixiebrix/pixiebrix-app/blob/aa2230ba58496ffb30ce950f2cb1e87e072478b9/pixiebrix-app/src/auth/useSyncExtensionToken.ts#L28-L28

**Comment by fregante** [comment]
I was able to to sort of replicate this:

1. Open http://127.0.0.1:8000/
2. See message
3. Open http://app.pixiebrix.com
4. See message
5. GOTO 1
