### ISSUE TITLE
Error setting default value for dropdown in Form Builder field

### ISSUE THREAD

**Issue by twschiller** [pixiebrix/pixiebrix-extension#2719]
Steps to reproduce
1. Add a Dropdown field with options #webhooks, and #welcome
2. Enter #webooks as the field default 
3. Try running the form

Error setting default value for form. The modal then gets "stuck"

Implementation Sketch
- Fix the default value bug
- To prevent future getting "stuck": we should wrap the form in an ErrorBoundary and bail out of the form by throwing an error?

![image](https://user-images.githubusercontent.com/1879821/153802844-9d21f0cd-5e7c-4afd-86ad-1900e4e9d193.png)

**Comment by fregante** [comment]
> To prevent future getting "stuck": we should wrap the form in an ErrorBoundary and bail out of the form by throwing an error?

In general, we can offer a fully-functioning modal regardless of content. That means always showing a close button, "click outside to exit", esc key listener, etc (depending on which modal we're using, some of these come standard)
