### ISSUE TITLE
Create/use an SCSS variables/mixins file

### ISSUE THREAD

**Issue by twschiller** [pixiebrix/pixiebrix-extension#2749]
Implementation Sketch
- Check if the bootstrap SCSS have utilities as variables/mixins. If so can we re-use them in our modules?
- Create a  SCSS variables file if it does not already exist
- Is should include: colors, padding (which should match the utility classes)
- Add documentation on how to use (how to import, etc.)

Questions
- Can we use the existing _variables.scss file?
- We need to have a file for the options page/sidebar them, and another file for the devtools theme
- Does padding/margin belong in there? Or do those get implemented using mixins?

**Comment by mnholtz** [comment]
FYI - finished looking into this today 

It looks like with `node-sass` (which is [apparently deprecated](https://www.npmjs.com/package/sass), by the way. Perhaps we should consider moving over to [Dart Sass](https://www.npmjs.com/package/sass) as recommended in the deprecation reference) we can simply import & use mixins and variables like so:

```
// including full path because it looks like this is where our main theme variables & mixins live
@import "../../../../vendors/theme/assets/styles/_variables.scss";
@import "../../../../vendors/theme/assets/styles/mixins/_misc.scss";

.cardFooter {
  color: $sidebar-dark-menu-icon-color;
}

.sharingLabel {
  //overflow: hidden;
  //white-space: nowrap;
  //text-overflow: ellipsis;
  @include ellipsor;
}
```

Although, it looks like webpack is not happy with importing some of our existing files, like [_variables.scss](https://github.com/pixiebrix/pixiebrix-extension/blob/d6e36801d248c31f83230b351c46a1618692ba0c/src/vendors/theme/assets/styles/_variables.scss#L18-L18), in the way they are currently written. I had to comment out offending lines that were using improperly imported or non-existent variables.

Additionally, I think we should refactor files like `_variables.scss` to remove or replace unused or unhelpful variables & mixins (e.g. colors that we never want to use in the app).



_____________
Other alternatives I found in my research:
**1. using [sass-resources-loader](https://github.com/shakacode/sass-resources-loader)**
```
 // We could potentially register existing bootstrap theme files like this
            resources: [
              './path/to/vars.scss',
              './path/to/mixins.scss',
              './path/to/functions.scss'
            ]
```
or
**2. [css modules variables](https://github.com/css-modules/css-modules/blob/master/docs/values-variables.md)?**
Although this method doesn't look desirable for being able to reuse existing sass files, as well as providing a method to use mixins.

**Comment by fregante** [comment]
If we can stick to regular SCSS it would probably be easier, also because we're already using it. 


---

Re: dart-sass

We can't upgrade due to our incompatible custom theme:

- https://github.com/pixiebrix/pixiebrix-extension/issues/975

**Comment by mnholtz** [comment]
> If we can stick to regular SCSS it would probably be easier, also because we're already using it.

I agree

**Comment by fregante** [comment]
Side request:

- [ ] Move our customizations out of the `vendors` folder because it always takes a lot of guesswork to figure out what is ours and what is the default Bootstrap theme

**Comment by BLoe** [comment]
@mnholtz Is this ticket relevant any more? Was this before we created our color variables file and stuff?

**Comment by mnholtz** [comment]
@BLoe I think we can tentatively close this. We've implemented a lot of points (e.g. being able to import variables) discussed in this ticket. We probably want to address newer tickets that address css architecture instead.
