### ISSUE TITLE
Improve selector sorting in inferSelector

### ISSUE THREAD

**Issue by twschiller** [pixiebrix/pixiebrix-extension#2812]
Context
- Our [inferSelectors](http://github.com/pixiebrix/pixiebrix-extension/blob/1d3a1052dfe5deb2d2bbda036868d13d6f52b856/src/contentScript/nativeEditor/infer.ts#L532-L532) method attempts to sort selectors. Currently this is based on length
- This sorting is undesireable, e.g., it will rank id selectors below attribute selectors if the id is long

Implementation Sketch
- Define a custom sort function that sorts by selector type. Order of preference should be based on the kind of selector included:
1. id
2. id-like attributes, e.g., data-test-id, data-test, data-cy
3. tag
4. classname
5. structural selectors, e.g., nth child

- It's OK to keep using length as a tiebreak

Related
- https://github.com/pixiebrix/pixiebrix-extension/issues/2498. In the future, we might consider still generating selectors with CSS module names, but ranking them lower. Currently with css-selector-generator this might not be possible?

**Comment by fregante** [comment]
> 3. tag
> 4. classname 

Why place the tag above the classname? I'd expect selectors to be sorted by [specificity](https://specificity.keegan.st) with the id-like exceptions you mentioned.

**Comment by twschiller** [comment]
> Why place the tag above the classname?

My guess (which I'm not sure in practice) is that if the tag is actually unique then it's a pretty robust target. But generally I'd expect the tag not to be unique.

For example, we'd end up targeting h1, nav, etc., but would generally not ever target span/div because they wouldn't be unique

**Comment by twschiller** [comment]
@fregante We need to tweak this a bit to take into account mixed selectors

![image](https://user-images.githubusercontent.com/1879821/156237399-8ed8067d-2d0b-4677-b83c-14fbba0811fa.png)
