### ISSUE TITLE
Rollbar not applying sourcemaps to all files

### ISSUE THREAD

**Issue by twschiller** [pixiebrix/pixiebrix-extension#2817]
![image](https://user-images.githubusercontent.com/1879821/155183670-d56dc2c9-fd9a-4d30-be46-4012b26524d1.png)

The source map is uploaded (automatically)

![image](https://user-images.githubusercontent.com/1879821/155183729-fbb49643-aaa2-43cb-a632-98fbd461529c.png)

Also isn't working if you manually upload the source map

Possible problems:
- Multiple sourcemaps/files for the same code version? (CI is also uploading). Not a problem in practice since Rollbar won't ever see any errors from those
- Rollbar doesn't like the tool we're using for sourcemaps 
- The occurences we're looking at haven't been processed with the source map: https://docs.rollbar.com/docs/source-maps#4-verify-source-maps-work

**Comment by twschiller** [comment]
Update: it looks like it is coming through. Just not for the initial occurrences because Rollbar hasn't fetched them yet

![image](https://user-images.githubusercontent.com/1879821/155184760-dd8e4989-c22d-4fbc-87c0-7e392e50d4cd.png)

As part of Release CI, we probably want to tell Rollbar to prefetch the files

> If you're using the Automatic Download method, you can notify our API to trigger a download for each of your minified files. Doing this will reduce the number of errors that the source map isn't applied to (since we'll have a greater chance of downloading the source map before the first error after a deploy occurs).

**Comment by fregante** [comment]
> Just not for the initial occurrences because Rollbar hasn't fetched them yet

What a limitation. It almost makes me want to restore the old uploading, except that it used to occasionally fail and it's a 10MB upload spread over several files.

I think we can call the api with a simple shell loop in `scripts/rollbar-upload.sh` or with a `parallel` or `xargs` call in npm scripts.
