### ISSUE TITLE
Create a slice for auth

### ISSUE THREAD

**Issue by mnholtz** [pixiebrix/pixiebrix-extension#2821]
**Context**
RTK useGetAuthQuery hooks are slowing down component rendering for large lists of components - e.g. the new Blueprints page. For this example in particular, user `scope` and `flags` are used to calculate possible user actions.

**Implenentation sketch**
- Add a Redux `authSlice` that stores auth information like `scope`, `flags` and `organization` from `useGetAuthQuery`

**Comment by twschiller** [comment]
Closing in favor of: https://github.com/pixiebrix/pixiebrix-extension/issues/2909
