### ISSUE TITLE
Active Bricks page shows "undefined" instead of a team name

### ISSUE THREAD

**Issue by BALEHOK** [pixiebrix/pixiebrix-extension#2847]
Steps to reproduce:
1. Add a user to a team.
2. As the new team user install a team-shared blueprint.
3. As an admin of the team remove that user from the team.
4. As a removed user open the Active Bricks page.

Actual result:
`undefined` is shown instead of a team name

<img width="651" alt="Screen Shot 2022-02-28 at 10 07 49 PM" src="https://user-images.githubusercontent.com/3116723/156060182-ed491a63-f7e5-40f2-a216-4598b3567a11.png">

Expected behavior:
Display "Shared blueprint" or uninstall the blueprint if the access was revoked. @twschiller what do you think?

**Comment by twschiller** [comment]
Closing as stale
