### ISSUE TITLE
Add Parse JSON brick

### ISSUE THREAD

**Issue by BLoe** [pixiebrix/pixiebrix-extension#2863]
### Add a brick to parse raw JSON into an object variable:
<img width="930" alt="image" src="https://user-images.githubusercontent.com/2801308/156657164-a5ff3ea1-988a-4ba3-a2f9-36fc53ebedff.png">

Questions:
- Should we use a new, custom `format` with `TextWidget`? Separate custom widget?
- Do we validate the JSON values? How?
- We need to support expression tags like YAML (e.g. `{ myField: "!var @input.foo" }`)
- We need to also support text templates (e.g. `{ {{@myFieldName}}: "{{@myFieldValue}}" }`)

**Comment by fregante** [comment]
I think it could be useful to load up an editor like ACE when we display code. The issue would be that `{{{@var}}: 124}` isn't really JSON so we'd have to build a custom parser for the editor too.

**Comment by twschiller** [comment]
Let's start with something quite simple:

The input schema:

```
properties:
   json:
     type: string
     description: The JSON string to parse
```

The brick body:

```typescript
try {
   return JSON.parse(json);
} catch (error) {
   // Can use a logger call or custom error type to capture more 
   throw new BusinessError("Invalid JSON: ${getErrorMessage(error)})");
}
```

This is automatically support text templates (and also numbers, because you just wouldn't surround it in quotes, e.g.,:

```
{
   myString: "{{ @str }}",
   number: {{ @num }}
}
```
