### ISSUE TITLE
Clicking property name in data tree to expand it also copies the path

### ISSUE THREAD

**Issue by twschiller** [pixiebrix/pixiebrix-extension#2898]
Steps to reproduce
- Click on a property in the data preview panel to expand it

Actual behavior
- It expands
- It copies the path to the clipboard and shows a notification

Expected behavior
- It expands, but does not copy the path

NOTE: this also happens when collapsing the path

**Comment by twschiller** [comment]
@BALEHOK @BLoe Looking at the code, it doesn't look like a new problem?

**Comment by BLoe** [comment]
Doesn't seem like it's new, I haven't noticed it before though.
