### ISSUE TITLE
Selector field not finding unique h1 field from Quick Start

### ISSUE THREAD

**Issue by twschiller** [pixiebrix/pixiebrix-extension#2899]
Steps to reproduce
- Follow the quick start steps
- LinkedIn organization pages have a unique h1. Clicking the h1 selects a terrible selector with no other options:

![image](https://user-images.githubusercontent.com/1879821/157159148-746dd5b4-4c8f-4a9d-9513-289a820d57ea.png)

**Comment by fregante** [comment]
This line is the only new filtering line we added recently: 

https://github.com/pixiebrix/pixiebrix-extension/pull/2824/files#diff-03a0dea69f16a927833227b0b1c2932d1d6bcb9c7b1f32531035ed77b00b02ddR131

But are these IDs have fewer than 3 letters?

**Comment by twschiller** [comment]
> But do these IDs have fewer than 3 letters?

It's not an id, it's a tag. We should only be applying the 3 letter rule to class names

I think we need to NOP this change for 1.5.6 until we test more thoroughly what the impact is
