### ISSUE TITLE
Incorrect "connection lost" message for multi-page flows

### ISSUE THREAD

**Issue by twschiller** [pixiebrix/pixiebrix-extension#2902]
Steps to reproduce
- Create an extension with a 1) open tab, 2) wait (window: target)
- Run the extension and close the new target tab while it's waiting

Actual Behavior
- On the starting tab, PixieBrix will show a non-dismissable connection lost alert

Expected Behavior
- PixieBrix should show a normal action failed message for the action. (It still has a connection to the host page)

Considerations
- We should record a more informative error message in this case, such as "Target tab unexpectedly closed"
- This also affects opener target. If the opener tab is closed, it should be "Opener tab no longer exists", and/or "Opener tab unexpectedly closed

Related code: 
- The BackgroundLogger error method shows a notification. The error text must be transformed before it hits that http://github.com/pixiebrix/pixiebrix-extension/blob/F/bug/avoid-double-reporting/src/telemetry/BackgroundLogger.ts#L80-L80

**Comment by fregante** [comment]
This might be a little involved because with the Messenger we've basically gone towards: "Try messaging this target, until it exists, full stop", it doesn't differentiate between a non-existing target and a target that's loading because we tried to make it completely opaque to the caller, along with other requirements that came along, like named targets ("tabId-less targets").

I'll look into it tomorrow

**Comment by fregante** [comment]
Uh oh. It's actually a deeper problem. We can't distinguish between:

- the page unloaded before responding (tab closed or page refreshed)
- the tab never existed


Here's what happens:

1. The tab receives the message and the sender awaits a response
2. You close the tab
3. Chrome throws **"The message port closed before a response was received."**
4. `webextension-polyfill` purposefully silences this error, resolving the underlying `sendMessage` with `undefined`:
	- https://github.com/mozilla/webextension-polyfill/issues/365
5. `webext-messenger` treats `undefined` as a loading error or "the extension has not yet loaded" 🟣
	- https://github.com/pixiebrix/pixiebrix-extension/pull/1753
	- https://github.com/pixiebrix/webext-messenger/blob/192b35b10c599f38b16c22ae747bf60360d06771/source/sender.ts#L73-L76)
6. `webext-messenger` will retry
7. The tab no longer exists, so we start getting  **"Could not establish connection. Receiving end does not exist."**
8. The time runs out
9. `webext-messenger` throws this last error
10. The extension treats this error as a complete runtime failure 🟣

The steps marked with 🟣 can likely be improved with little effort. I don't expect the polyfill to fix this issue in the short term or maybe even ever.

**Comment by fregante** [comment]
I opened two issues to document this behavior:

- https://github.com/mozilla/webextension-polyfill/issues/365
- https://github.com/pixiebrix/webext-messenger/issues/66

**Comment by twschiller** [comment]
I think your analysis looks correct. I was thinking of just solving the proximate cause:

Can we just wrap the runBrick calls in a try/catch and change the error message? This should be a BusinessError, since when dealing with target/opener/etc. it's generally a misconfigured multipage extension

- [requestRunInTarget](http://github.com/pixiebrix/pixiebrix-extension/blob/b1a09f47a6617488275ee084990bea4a97a2521a/src/background/executor.ts#L104-L104)
- [requestRunInOpener](http://github.com/pixiebrix/pixiebrix-extension/blob/b1a09f47a6617488275ee084990bea4a97a2521a/src/background/executor.ts#L54-L54)
