### ISSUE TITLE
Page Editor sometimes not appearing on Chrome 99

### ISSUE THREAD

**Issue by twschiller** [pixiebrix/pixiebrix-extension#2904]
- Chrome Bug Tracker: https://bugs.chromium.org/p/chromium/issues/detail?id=1304058 
	This is impacting all Chrome Extensions, not just ours
- Team discussion: https://pixiebrix.slack.com/archives/C023KL47XV4/p1646751676312859

**Comment by fregante** [comment]
I saw the error, will report it:

<img width="892" alt="Screen Shot 1" src="https://user-images.githubusercontent.com/1402241/157713185-0767e271-a5f6-44cc-b1fc-f9bc0ea01c67.png">

Reloading this devtools will make the tab appear.

**Comment by fregante** [comment]
Closing this as I've not seen this issue in months. On the Chrome bug tracker, after many comments in March/April, they've also slowed down and they will be closing the issue soon. Either way not much we can do about it at all.

The issue can stay closed and if it happens again we can leave a comment on chromium.org
