### ISSUE TITLE
JQuery Reader brick shows incorrect preview for trigger in eventTarget root mode

### ISSUE THREAD

**Issue by twschiller** [pixiebrix/pixiebrix-extension#2906]
Steps to reproduce
- Define a click trigger on a button
- Add a JQuery reader with the default (using "inherit" for root mode)

Actual Behavior
- Preview shows results relative to the root document

Expected Behavior
- Preview should be relative to the element/target from the last run

Considerations
- If the trigger is eventTarget root mode and the JQuery brick is configured to inherit, we can just say "Preview not available" (TODO: improve this error message)

**Comment by BALEHOK** [comment]
Loom https://www.loom.com/share/64c3ac125e6640e2ac4a2a7bd445d591
