### ISSUE TITLE
Data output in Brick issue - Create New Email Message

### ISSUE THREAD

**Issue by orliesaurus** [pixiebrix/pixiebrix-extension#2922]
When using the Create New Email Message brick - the values that come out from the brick are replacing all spaces with `+` signs
When a user has a default email client set to handle the mailto links such as Microsoft Outlook, the plus signs aren't parsed out and therefore show up in the body and subject of the email (and possibly other fields)

![image](https://user-images.githubusercontent.com/4209733/157723241-1c6077d7-93d4-4140-a810-faefe21a6b31.png)

**Comment by fregante** [comment]
To the bugfixer: this URL should be built with URL and its searchParams map, we don’t have to serialize URL parameters manually.

**Comment by twschiller** [comment]
Relevant discussion: https://webmasters.stackexchange.com/questions/15920/should-plus-be-encoded-in-mailto-hyperlinks
