### ISSUE TITLE
`initLocator` being called from contentScript (and getting blocked by CSP)?

### ISSUE THREAD

**Issue by twschiller** [pixiebrix/pixiebrix-extension#2925]
ClientNetworkError: No response received. Your browser may have blocked the request. See https://docs.pixiebrix.com/network-errors for troubleshooting information

initLocator cannot be called from the contentScript because it makes a network call

```
File webpack:///./src/services/requestErrorUtils.ts line 186 col 10 in E
return new ClientNetworkError(
File webpack:///./src/hooks/fetch.ts line 81 col 5 in async f
throw await enrichRequestError(error);
File webpack:///./src/services/locator.ts line 136 col 12 in async b.refreshRemote
this.remote = await fetch<SanitizedAuth[]>(
File webpack:///./src/services/locator.ts line 165 col 28 in async b._refresh
const timestamp = Date.now();
File webpack:///./src/services/locator.ts line 159 col 57 in async b.refresh
this._refreshPromise = this._refreshPromise ?? this._refresh();
File webpack:///./src/background/locator.ts line 22 col 31 in async a
export default async function initLocator() {
```

Other information:
- pageName = contentScript in the error telemetry. (There's a chance [this reportError logic to get the pageName](http://github.com/pixiebrix/pixiebrix-extension/blob/d6e36801d248c31f83230b351c46a1618692ba0c/src/telemetry/reportError.ts#L48-L48)) might be broken?). It might actually be getting called from the background page
- We are getting the blueprintId, deploymentId, extensionId, extensionPointId for the error. So this is running in the path of an extension 
- The brick sequence is:
  -  "@pixiebrix/wait/element"
  - "@pixiebrix/state/get"
  - "@pixiebrix/cancel" (conditional)
  - "@pixiebrix/wait/element"
  - "@pixiebrix/session"
  - "@pixiebrix/document-context"
  - "@pixiebrix/jq"
  - "@pixiebrix/data/put"
  - "@pixiebrix/form-modal"
  - "@pixiebrix/state/set"
  - "@pixiebrix/data/put"
- I can't reproduce the code path locally on my machine
- What's weird is that the only call to initLocator appears to be background.ts. So I'm not sure how it'd ever be run in the context of a brick run. (And there's a call to forbidContext in LazyLocatorFactory)

Potential places:
- [makeServiceContext](http://github.com/pixiebrix/pixiebrix-extension/blob/d6e36801d248c31f83230b351c46a1618692ba0c/src/extensionPoints/triggerExtension.ts#L266-L266). makeServiceContext uses the background messenger correctly though

Telemetry:
- https://rollbar.com/pixiebrix/pixiebrix/items/2672/occurrences/216869217155/. This is from a trigger that makes a call

**Comment by fregante** [comment]
Is it `useDependency`? This file for example uses a background API (which suggests it's not being used in the background) but also uses `useDependency` directly, which calls `locator.locate()` without the messenger:

https://github.com/pixiebrix/pixiebrix-extension/blob/677d586ee31508a29877b1735ea72efd2f99b118/src/contrib/uipath/uipathHooks.ts#L19-L38

There could be more situations like this, but this is probably one.

**Comment by fregante** [comment]
The `initLocator` mention is probably on the wrong line. As you said there's no way that function is called outside the background page, but the call right above it definitely can.

**Comment by fregante** [comment]
> * There's a chance [this reportError logic to get the pageName](https://github.com/pixiebrix/pixiebrix-extension/blob/d6e36801d248c31f83230b351c46a1618692ba0c/src/telemetry/reportError.ts#L48-L48)) might be broken?

`getContextName` uses the same detections as the rest of the app. If that's broken, then a lot more things are. I tried running the raw code in the console and it appears to be detected correctly:

<img width="750" alt="Screen Shot" src="https://user-images.githubusercontent.com/1402241/158008690-e1266f2d-5479-4970-bf18-157598f7d9ec.png">




In this case `reportError` is a local-context function that adds the `contextName` before using the messenger, so this piece of code should be right.
