### ISSUE TITLE
Confetti blocked on some sites due to worker CSP

### ISSUE THREAD

**Issue by twschiller** [pixiebrix/pixiebrix-extension#2953]
Steps to reproduce
- Visit https://news.ycombinator.com/ on Chrome 99
- Add the confetti brick

Expected
- Confetti

Actual
- No confetti with CSP error in the console

Possible solutions
- Use `useWorker: false` (https://www.npmjs.com/package/canvas-confetti)
- Is there a way we can detect and then fall back to useWorker: false?
- Should we expose that as an option on the brick (so people can enable if they know it works on the site they're using)

**Comment by fregante** [comment]
Can't reproduce:

![gif](https://user-images.githubusercontent.com/1402241/158401431-201a63cf-7c77-4a10-b8bd-1a57449bbd9b.gif)

**Comment by twschiller** [comment]
Hmm, might just be on their comment page: https://news.ycombinator.com/item?id=30689043

```
Content-Security-Policy: default-src 'self'; script-src 'self' 'unsafe-inline' https://www.google.com/recaptcha/ https://www.gstatic.com/recaptcha/ https://cdnjs.cloudflare.com/; frame-src 'self' https://www.google.com/recaptcha/; style-src 'self' 'unsafe-inline'; img-src 'self' https://account.ycombinator.com
```

**Comment by fregante** [comment]
I can see the error in the console there, yes:

<img width="1094" alt="Screen Shot 7" src="https://user-images.githubusercontent.com/1402241/158558810-aa75c010-b4a9-4f97-99c1-e7bbb8c5d8ef.png">
