### ISSUE TITLE
Support text template entry for selector fields in Page Editor

### ISSUE THREAD

**Issue by twschiller** [pixiebrix/pixiebrix-extension#2958]
Context
- Not sure if this is a regression (bug) / or wasn't implemented: https://pixiebrixcommunity.slack.com/archives/C02TS1K83EX/p1647341361981219

Implementation Sketch
- The selector selector widget should support/produce literal strings
- The toggle should include a dropdown to provide a nunjucks text template

Workaround
- Use JQ to assign the selector to a variable and pass it as a variable

**Comment by orliesaurus** [comment]
Just to clarify - I feel like the "Jquery Selector" doesn't support using nunjucks variables such as {{@myVar}}

This example wouldn't work - it's an array of jquery selectors
![image](https://user-images.githubusercontent.com/4209733/158492006-e5bcaac3-2671-48f6-8b45-a397bd2e01b1.png)

**Comment by Myvar** [comment]
Love it when i get pulled into random issues lol
