### ISSUE TITLE
Iframe brick width and height can't be set

### ISSUE THREAD

**Issue by orliesaurus** [pixiebrix/pixiebrix-extension#2959]
Somewhere/something has changed with chrome it seems.

When you try to render an iframe and try to specify for example a spreadsheet as the URL of the iframe brick, setting the height/width of the iframe doesn't apply them to the iframe that is inside the iframe in the brick.

**Comment by fregante** [comment]
I saw this bug but I forgot to send a fix. I think it's not loading the CSS

**Comment by orliesaurus** [comment]
asdasd ok here it is:

![image](https://user-images.githubusercontent.com/4209733/158528090-9e0f2b98-9e6b-4b41-ac7b-baa74436e77d.png)

The width and height should be applied to the bottom iframe too in this snippet
![image](https://user-images.githubusercontent.com/4209733/158528146-194485d6-0e99-4b9c-a842-6e211beffeda.png)
