### ISSUE TITLE
Clean up front-end data model of extensions and blueprints

### ISSUE THREAD

**Issue by twschiller** [pixiebrix/pixiebrix-extension#2969]
## Context
- During activation in the activation wizard, everything gets "deconstructed" from the blueprint into individual extensions
- During this step, services/options selected during activation get pushed down into the IExtension entities that are created 
- PageEditor and Installable page is significantly more convoluted than they need to be because you have to "reconstruct" the recipes from the active IExtensions
- For the consolidated blueprints page, we had to introduce an Installable type to represent what users work with
- For RecipeDefinition and UnsavedRecipeDefinition, there's wackiness where the backend enriches the blueprint with a couple metadata fields that aren't part of the YAML. So we have to jump through hoops in the front-end to hide those/exclude those in some situations

## Other Pain Points/Bad Ergonomics
- ExtensionPointConfig type name has two different definitions/uses
- Types are all shoved into core.ts/definitions.ts files
- `CloudExtension` can't have optionsArgs on them, but currently allows them: https://github.com/pixiebrix/pixiebrix-app/pull/1379/files#r830488976

## Assumptions
- In the Activation Wizard, we had allowed people to choose which extensions to install during the install. This was because at the time we were shipping context menu blueprints with numerous context menus. We could preserve this ability, but have any unselected extensions be "paused" (similar to what we do for deployments that need a kill switch)

## Goals
- Eliminate the reconstruction step for front-end developers in the options page and page editor. It's OK (and probably preferred) for the runtime to work with individual instantiated extensions
- Use this work as an opportunity to clean up naming: 1) choose between recipe vs. blueprint, 2) make consistent with our external names

## Reference
- `IExtension`: `Config` generic is the configuration of the menu item, trigger, panel, etc.
    - Resolving axis
        - `UnresolvedExtension` → has a definitions section
        - `ResolvedExtension` → not definitions section, ids have been replaced with `@inner/<hash>` pointing to the the in-memory extension point
    - Persisted vs. unsaved angle:
        - `PersistedExtension` → is Redux extensionsSlice. (Is an Unresolved Extension)
        - `CloudExtension` → in the API contract, comes from the server
- RecipeDefinition
    - Saved vs. unsaved
        - `UnsavedRecipeDefinition` → this is what you should create/work with in the page editor
        - `RecipeDefinition` → this is what comes back from the server
- Installable → RecipeDefinition or Extension (depends on if activated or not)

## Meetings
- https://www.notion.so/pixiebrix/Type-Hierarchy-720dd39e59014456af508f17cf44ac8c

**Comment by BLoe** [comment]
@grahamlangford The core pain-point this ticket is pointing out - namely that we interact with the API in terms of "Recipes/Blueprints," while the product itself is more organized around the _extensions_ within the recipe, so there's a lot of packing/unpacking that happens in various ORM-adjacent code - is definitely still an issue. But many of the explicit examples, naming conventions, and underlying assumptions in this write-up have changed since Mar2022 and would be worth reviewing before anyone takes action on this ticket.
