### ISSUE TITLE
Include original error stack trace for Rollbar when throwing error in block pipeline

### ISSUE THREAD

**Issue by twschiller** [pixiebrix/pixiebrix-extension#2973]
Throw block errors reported to Rollbar needs to include original stack trace. Otherwise for application errors we can't pinpoint what line caused the error

![image](https://user-images.githubusercontent.com/1879821/159163772-c04ab624-5e6a-4424-a9c8-7eeac669eb2d.png)

Relevant code:
- http://github.com/pixiebrix/pixiebrix-extension/blob/4cf13fc048c6f3b5eac9248227b324b8b78c3cc3/src/runtime/reducePipeline.ts#L570-L570

Related:
- https://github.com/pixiebrix/pixiebrix-extension/issues/2966

**Comment by fregante** [comment]
Indeed, we discussed this before I think:

- https://github.com/pixiebrix/pixiebrix-extension/issues/1562#issuecomment-939049682
- https://github.com/pixiebrix/pixiebrix-extension/issues/580#issuecomment-865993072

I'll re-read your long comment in that last thread as it contains a lot information about a setup that we haven't fully achieved yet.

Related:

- Do you think I should work on this so we don't have to worry about serialized errors anymore? https://github.com/sindresorhus/serialize-error/issues/48

**Comment by fregante** [comment]
I looked into a few solutions:

- `Error#cause` is already used by `ContextError` but it doesn't appear to be followed/displayed by Rollbar
- the `make-error-cause` module seemed to fit but actually just concatenates the stacks
- `AggregateError` is a new native error group, but unfortunately the console does not show its "children errors" yet and likely neither does Rollbar
- the `aggregate-error` module seemed to offer a clean API to merge errors and their stacks, but its stack merger/cleaner isn't optimized outside Node

Here's for example what the result of `aggregate-error` looks like:

<img width="867" alt="Screen Shot 2" src="https://user-images.githubusercontent.com/1402241/159206929-1990bce2-30f5-4e0c-918c-16ae55b929c5.png">

So I can suggest just appending the stack like everyone else seems to be doing, something like:

```js
try {
	throw new Error('Original')
} catch (original) {
	const composed = new Error('New details: ' + original.message)
	composed.stack += '\n' + original.stack
	throw composed;
}
```

and it results into:

<img width="814" alt="Screen Shot 3" src="https://user-images.githubusercontent.com/1402241/159207634-17a7711c-6dfc-45ef-be25-21f92aa06816.png">


Pros:

- no lost details (including each error Type)
- the last-thrown error message contains all the information

I'll turn this pattern into a helper so we can create such wrappers easily, like:

```js
class ContextError extend WrappedError {
	constructor(message, cause, context) {
		super(message, cause); // Will automatically concatenate the message and stacks
		this.context = context;
	}
}
```

**Comment by fregante** [comment]
Additionally, for the long term, we'd want `Error#cause` support in:

- Rollbar
- `getErrorMessage` (it would take care of concatenation)

**Comment by twschiller** [comment]
> Additionally, for the long term, we'd want `Error#cause` support in:
> 
> * Rollbar (maybe you can open a ticket?)

Opened a ticket with rollbar: https://github.com/rollbar/rollbar.js/issues/1010

A workaround might be to overload the payload transform method. (Which is where we currently [re-write the host on the stack track URLS](http://github.com/pixiebrix/pixiebrix-extension/blob/02e8016d53658812b6a6a4ea5f570a4fe68516b6/src/telemetry/rollbar.ts#L96-L96)

**Comment by cyrusradfar** [comment]
@fregante @twschiller hi, I do Product at Rollbar. I've followed up on the thread in rollbar/rollbar.js

**Comment by fregante** [comment]
@twschiller great idea! Today I'll see if Rollbar supports the current concatenated stack and if it does I'll move the concatenation logic to that transform. 🎉

**Comment by fregante** [comment]
Update:

- Rollbar already had (undocumented) support for nested errors using the property `nested`: (below: `b` is the cause)
 
<img width="830" alt="Screen Shot" src="https://user-images.githubusercontent.com/1402241/162369949-222322ab-4c9c-49a0-bac2-af3baae8e08c.png">

- They just added the same support for  `cause` as well, but it hasn't been shipped yet
