### ISSUE TITLE
Run local TagUI process

### ISSUE THREAD

**Issue by marcelocecin** [pixiebrix/pixiebrix-extension#2990]
hello, I would like to suggest a brick similar to [Run local UiPath process](https://www.pixiebrix.com/marketplace/0a0d34b4-631d-442c-95e1-87bf5e6cb974/)
however using [TagUI](https://github.com/kelaberetiv/TagUI) as RPA
it would be possible ?
thank you !

**Comment by twschiller** [comment]
Hi @marcelocecin, should be possible! The local UiPath process bricks works by using their JS Robot SDK: https://docs.uipath.com/robot/docs/about-the-robot-javascript-sdk. Does TagUI have something similar?

Or, if we're not talking directly to the bot we could run via API or custom URL-scheme, etc.

**Comment by marcelocecin** [comment]
hi Todd, I will try via API, thanks

**Comment by twschiller** [comment]
> hi Todd, I will try via API, thanks

Great! I couldn't find the API docs for TagUI. If you do find the API docs or URL-scheme, let us know. Our team can help add some TagUI bricks to our marketplace

**Comment by marcelocecin** [comment]
I found it here: https://github.com/kelaberetiv/TagUI/blob/pre_v6/README.md

![image](https://user-images.githubusercontent.com/2955762/160090610-a5df075b-d924-4bc0-8a03-4dced37dc1f8.jpeg)

![image](https://user-images.githubusercontent.com/2955762/160090644-c3a916db-5f1d-491b-90b9-a9e30430c85a.jpeg)
