### ISSUE TITLE
Suggest scopes in Page Editor

### ISSUE THREAD

**Issue by twschiller** [pixiebrix/pixiebrix-extension#3029]
Context
- As a team extension creator, I want to save a blueprint as a team blueprint so 
- Currently we offer no guidance on what scopes (incl. personal) you are able to save as
- I might not know my team's scope

Implementation Sketch
- Fetch organizations/scopes that the user can write to (they need developer role or higher)
- Show in forms where the user is specifying the id for a blueprint

Considerations
- In the workshop, people can save a scopeless brick, but only if it's public. In the Page Editor we don't currently support sharing public blueprints, so don't need to handle the scopeless case

Related: 
- https://github.com/pixiebrix/pixiebrix-app/issues/880

**Comment by BLoe** [comment]
Should we change the blueprint id input, when it's not readonly, to actually be split up into a dropdown with scope options to pick from and a text input for the name?

**Comment by twschiller** [comment]
> Should we change the blueprint id input, when it's not readonly, to actually be split up into a dropdown with scope options to pick from and a text input for the name?

Yes, I think a split widget approach is a good idea

![image](https://user-images.githubusercontent.com/1879821/166475403-493bcead-f21d-449b-bf2b-3d1fb05e4363.png)

We can leave off the "Public" option for now, and revisit it when we take a look at blueprint sharing via the page editor

**Comment by twschiller** [comment]
@BLoe what's the status of this ticket? I think you mentioned there's some WIP?

**Comment by BLoe** [comment]
Yep, got this mostly working. Was curious what the best way is to load all the scopes for the current user? I can see the user scope and org scope in the Auth slice in redux, is it just those two for now or how do I load other Org scopes the user has edit access for?

**Comment by twschiller** [comment]
You can grab it off the `organizations` prop of in the auth slice: https://github.com/pixiebrix/pixiebrix-extension/blob/fbe61d434445e5afb0ccbdf0352cf21e7c651f9c/src/auth/authSlice.ts#L32-L32

It will be any organization where the role is Developer, Manager, or Admin. See enum here: https://github.com/pixiebrix/pixiebrix-extension/blob/fbe61d434445e5afb0ccbdf0352cf21e7c651f9c/src/types/contract.ts#L80-L80

That enum needs to be updated with the Manager role (5): https://github.com/pixiebrix/pixiebrix-app/blob/e524130e1e3d0b9f03f4911a45e568fe0ef236cf/api/models/teams.py#L21-L21

**Comment by BLoe** [comment]
Those objects have `id`, `name`, and `role`. Is the scope just `@<name>`? Or do I need to use the org ID and look up scopes somewhere?

**Comment by twschiller** [comment]
> Those objects have id, name, and role. Is the scope just @<name> with the name "sluggified"? Or do I need to use the org ID and look up scopes somewhere?

Apologies, we currently don't return the scope on that data. Let me check what would be involved in that on the backend and propose a sketch here

We have an `/organizations/` endpoint which returns the scope. But that endpoint has performance problems if you're an admin or manager currently. (Because it returns all the organization members too)

**Comment by BLoe** [comment]
Ah okay I was just looking at the api page and saw the `/organizations/` endpoint. We have an rtk query set up for it too, but it gets all orgs. The most specific endpoint for this use-case would be one that takes an array of org ids and returns scopes. Could also do an endpoint that returns "un-hydrated" orgs with just the name, scope, id, etc. We could use `Promise.all` on the client if we had a singular get-org-by-id endpoint as well.
