### ISSUE TITLE
Offer ability to add permission when using `@pixiebrix/get` and other bricks

### ISSUE THREAD

**Issue by fregante** [pixiebrix/pixiebrix-extension#3054]
The error surfaced by the `@pixiebrix/get` is not actionable:

<img width="1114" alt="Screen Shot 2" src="https://user-images.githubusercontent.com/1402241/160540916-a359ce1e-fc90-43ee-b447-f4f1b0031693.png">

Current fix:

1. Visit the URL (hoping you won't be redirected elsewhere)
2. Open editor
3. Click on the "Enable PB" button

Ideal fix:

- Show "Enable PB on this domain" button next to the error (or in its place). Maybe via `ErrorDisplay`?

Side quest:

- [ ] Make it work even if it redirects across domains. 😬 For example the url `https://fregante.com` redirects to `https://twitter.com`, so I think adding a permission for `fregante.com/*` is not enough or not necessary at all. I'm not sure whether this is fixable since we don't have access to the final URL that `fetch` requests.

**Comment by twschiller** [comment]
> Current fix

This fixes it for your current browser install, but does not fix it if you were to redeploy on another computer.

> Ideal fix

When that happens, we need to add the origin to the `permissions.origins` declaration on the extension: https://docs.pixiebrix.com/developer-guide/multi-page-automation#e9f10aaf9a7d4127ad0af9106b6b5297

We'll need to update the:
- [BaseExtensionState](http://github.com/pixiebrix/pixiebrix-extension/blob/608b587df058c60cccebcae261299fe204893e7a/src/pageEditor/extensionPoints/elementConfig.ts#L58-L58) form type
- [Base extension adapter code](http://github.com/pixiebrix/pixiebrix-extension/blob/608b587df058c60cccebcae261299fe204893e7a/src/pageEditor/extensionPoints/base.ts#L164-L164)

**Comment by fregante** [comment]
Very related issue:

- https://github.com/pixiebrix/pixiebrix-extension/issues/2043

**Comment by fregante** [comment]
Reopening because there's still no way to add a permission. It's clear (even to me) how to add a permission. Can we add this button when the error is detected?


<img width="413" alt="Screen Shot" src="https://user-images.githubusercontent.com/1402241/182340427-45678717-81a8-4dc5-8d21-1174157e32da.png">
