### ISSUE TITLE
Support RJSF Schema validation in strict CSP

### ISSUE THREAD

**Issue by twschiller** [pixiebrix/pixiebrix-extension#3059]
Context:
- See discussion: https://github.com/pixiebrix/pixiebrix-extension/pull/3019#issuecomment-1083072232

**Comment by fregante** [comment]
What do you intend to do here? Should be just move RJSF to the sandbox or do you want to propose changes upstream?

I'm asking because some code may not currently allow asynchronous function calls and may need refactoring.

Related:

- https://github.com/pixiebrix/pixiebrix-extension/issues/4730

**Comment by twschiller** [comment]
Looks like the RJSF team has a v5 in beta that modularized the validation code.

In v4 what we have to deal with is:
- validateFormData is synchronous: https://github.com/rjsf-team/react-jsonschema-form/blob/35663cf43dd1351a9f0d8e7d238e7dca22b4d378/packages/core/src/validate.js#L168
- Which is called here which is also synchronous: https://github.com/rjsf-team/react-jsonschema-form/blob/35663cf43dd1351a9f0d8e7d238e7dca22b4d378/packages/core/src/components/Form.js#L145
- We might be able to use the extraErrors prop: https://github.com/rjsf-team/react-jsonschema-form/pull/1444

In v5, it looks like validation is also not async: https://github.com/rjsf-team/react-jsonschema-form/blob/main/packages/validator-ajv6/src/validator.ts#L256

So I think our current bet is to look into using extraErrors. For v4 we also may need to use webpack so swap out some internal implementations

**Comment by fregante** [comment]
Do you have something in mind with regards to async code? What I'm asking is about `eval`

**Comment by twschiller** [comment]
I see us as having two options:

- Swap out for @cfworker/json-schema which is synchronous. So we'd just need to use Webpack to swap out the Ajv validator function
- Move Ajv to the Sandbox, which would make form validation asynchronous (because of the async sandbox call)

I have no clue what the functional difference between what @cfworker/json-schema can validate vs. Ajv. I suspect that @cfworker/json-schema is sufficient for our field types in the Form Builder. The only gotcha would be if we need to translate the validation exceptions from @cfworker/json-schema to the format RJSF expects from Ajv

**Comment by fregante** [comment]
I haven’t looked into either dependency yet, but I think that making changes to our own engine is quicker than dealing with upstream PRs and error translation issues that might prop up over time.  

- Is async validation possible/ideal within PB? 
- Do you think it’s practical to make all those calls async? 
- And especially: are we doing any validation in the background? If so, we can only fix the problem by **avoiding eval** altogether since the sandbox isn’t yet available there. That means: upstream PR or webpack swap.

**Comment by twschiller** [comment]
> The ideal solution might be to send a PR to RJSF but the level of effort, lobbying and time is probably high.

A PR to introduce @cfworker/json-schema support, or a PR to introduce async validation support?

Async validation support might already be supported **enough** for what we need: https://github.com/rjsf-team/react-jsonschema-form/pull/1444

> Do you think it’s practical to make all those calls async?

I think we'd definitely try to use the `extraErrors` feature first. By practical, you're referring to implementation effort of swapping out sync for async, correct? Or are you referring to runtime performance

> are we doing any validation in the background?

To my knowledge we aren't. I also poked around and don't see any places. 

The only place I could see us using it in the future, is for validating configuration vs. the integration definition schema for assist with debugging. For that we could definitely use @cfworker/json-schema

**Comment by fregante** [comment]
I think we're talking about two different things:

- async validation within RJSF (which isn't clear to me how/if it applies here)
- versus: async validation within PB, which is required if we have to move it into the sandbox

If you intend the first one, could you clarify how it's related?

If we're both talking about the second one, then we don't need any changes upstream. The `async` part would just be due to the sandbox. This is what I'm talking about it "being practical". How difficult would it be to modify PB to make async RJSF to the sandbox?

**Comment by fregante** [comment]
As for `extraErrors`, am I understanding correctly that you'd want to use it to plug in `@cfworker/json-schema` and skip the internal AJV? If that's possible, it would probably be the best option.

**Comment by fregante** [comment]
Overall, I'm not familiar with this code. It seems that RJSF is integrated as a JSX component so its validation cannot quite be moved to the sandbox. I'm not sure if `extraError` can actually help here, I don't anything here: https://github.com/rjsf-team/react-jsonschema-form/pull/1444/files#diff-4e73bbe5bfd2fe6c16c12b718b5199a553661a010aa6e6ea7b42e6f41babffb3

**Comment by fregante** [comment]
I opened an issue upstream. Do you think we can wait for v5?

**Comment by twschiller** [comment]
Let's not let this block the Sandbox work for Nunjucks, etc.

I think for Option 2 you meant to say "use @cfworker/json-schema" via webpack. Given the the stability of RJSF v4 (because of the impending v5 release), I suspect dependency updates wouldn't be a problem

The next step is to see how close `@cfworker/json-schema`'s output format is to ajv and what any gaps in validation would be. Since we could use this library with both RJSF v4 and v5.

**Comment by fregante** [comment]
Do we have any tests for this validation? Are they enough to test a possible ajv replacement? 

Given that RJSF authors seem open to the idea of a `@cfworker/json-schema` plugin for v5:

- do you want to wait for v5 before doing any work here?
- do you think we could implement that from the ground up and send a PR? It might require more work than a webpack-based swap, but it would be easier to test in their own suite, it would be permanent and they'd maintain it afterwards.

**Comment by twschiller** [comment]
> do you think we could implement a proper @cfworker/json-schema plugin for v5 from the ground up and send a PR

I think it's work spending an hour seeing what would be involved in that. I suspect it won't be a major lift given that `@cfworker/json-schema` is tested against the https://github.com/json-schema-org/JSON-Schema-Test-Suite JSON Schema spec test suite (so adapter-like things must exist)

From there, we can in parallel: 
- Choose to do the v4 switch out, and/or
- Wait for RJSF v5 to GA

However, let's get Nunjucks into the Sandbox prior to doing RJSF work

**Comment by fregante** [comment]
Is this relevant to us? 

- https://github.com/rjsf-team/react-jsonschema-form/pull/3652

That PR closed this issue:

- https://github.com/rjsf-team/react-jsonschema-form/issues/3543

However I don’t think we can pre-compile the schemas outside the extension… or can we? Maybe pre-compile them in the sandbox and then use them synchronously via ajv8:

Example:

```jsx
<CompileSchema schema={schema}>
	{compiledSchema =>  <JsonSchemaForm schema={compiledSchema}/>}
</CompileSchema>
```

This might be easier than replacing the validator:

- https://github.com/pixiebrix/pixiebrix-extension/pull/7081

**Comment by fregante** [comment]
On further review, that probably won't work. The compilation isn't the issue, it's the _validation_ that can't run in the content script.

1. Compilation generates JS (can be done even with CSP)
2. That generated JS needs to be evaluated by RJSF (blocked by CSP)

If async validation was possible, this would be a useful API, but RJSF [does not support that.](https://rjsf-team.github.io/react-jsonschema-form/docs/usage/validation/#async-validation)
