### ISSUE TITLE
RFC: Can we keep the options page, sidebar, and page editor redux states in sync, in real time?

### ISSUE THREAD

**Issue by BLoe** [pixiebrix/pixiebrix-extension#3069]
This would improve the user experience if things synced up automatically in real time between the three apps, without having to refresh/reload to see changes made in another app. For example, it would be nice if you could see an extension appear in the page editor immediately after activating from the blueprints page without having to reload the page editor. And then also the reverse, when you remove an extension from the page editor, it would be nice if the button on the blueprints page immediately changed back to "Activate" and let you re-activate the extension again, without refreshing the blueprints page first.

I don't know if there is a feasible option here, something like:
* Use the messaging api to keep (parts of?) the redux stores in sync with each other in a bi-directional way
* Move (part of?) the redux store itself to the background script, and use the messaging api to wire up selectors and dispatch to the three apps

**Comment by fregante** [comment]
If the state is stored locally, we can use `browser.storage.onChanged` to detect changes across the extensions. Maybe there's an API around redux-persist that handles this natively too. 

If the state is server-side, we can use raw `browser.runtime.sendMessage('updateStuff')` calls because every context will receive it at once (unlike the Messenger which looks for a specific receiver)

**Comment by BALEHOK** [comment]
If we want to track installed extensions (activation, de-activation), we can reload the relevant part of the Redux state in other apps. There's no need to move the Redux state itself to the background or other storage.

**Comment by twschiller** [comment]
There are some libraries people have put together that work with redux-persist, e.g., https://github.com/rt2zz/redux-persist-crosstab. They're typically based on the local storage events, but probably wouldn't be too hard to adapt to for use with browser.storage

Actually performing the sync introduces a lot of complexity on state merging, so wouldn't prioritize that. 

However, a potentially quick win would be to just alert on a page if part of the slice has changed (for some level of granularity). E.g.:

- Prompt to reload blueprints page
- Prompt to reload whole page editor
- Prompt to reload sidebar
- Prompt to reload extension in Page Editor

At the beginning we could be fairly coarse-grained
