### ISSUE TITLE
Apply partner theme to extension

### ISSUE THREAD

**Issue by twschiller** [pixiebrix/pixiebrix-extension#3120]
Context
- In https://github.com/pixiebrix/pixiebrix-app/issues/1470 we are applying partner theme to the Admin Console
- https://github.com/pixiebrix/pixiebrix-app/issues/1472 adds the API endpoint

Questions
- Can the theme be delivered as a style sheet that we fetch? We could potentially serve the stylesheet from the PixieBrix server so the style-src CSP can just refer to app.pixiebrix.com? (Or we need to inject the style sheet into our own application?)

**Comment by mnholtz** [comment]
Considerations:
- There are bootstrap and pixiebrix components in the extension that don't use colors from the theme folder - they're either hard-coded or they use default bootstrap colors

**Comment by twschiller** [comment]
See comment here: https://github.com/pixiebrix/pixiebrix-app/issues/1469#issuecomment-1101535335

I think we want to use native CSS variables instead of SCSS variables? SCSS variables as you mention are interpolated at compile time from SCSS to CSS? 

I'm not sure how much of a pain this would be to modify our existing theme to support this pattern. It might just work to do some indirection?:  http://github.com/pixiebrix/pixiebrix-extension/blob/62bb7e585640093ab9e0c84326006f36147cdbb3/src/vendors/theme/assets/styles/_variables.scss#L3-L3

```
$theme-colors: (
   $blue: var(--theme-blue);
}
```

> How would multiple css variable files work with our css loader?

The currently flow compiles the SCSS into a single file per entry point (plus some additional for dynamically imported modules)

> and apply the theme classname to a root component

I'm not sure how this would work with components from React Bootstrap?
