### ISSUE TITLE
Fix RTK error type in base query

### ISSUE THREAD

**Issue by twschiller** [pixiebrix/pixiebrix-extension#3126]
Context
- https://github.com/pixiebrix/pixiebrix-extension/pull/3123/files#r846209216
- Data/errors from RTK need to be serializable because RTK places it in the Redux store

Implementation Sketch:
- Change the error clause of RTK base query to return `{error: serializeError(error)}` of the thrown error. NOTE: for Axios errors we have to delete the toJSON property before making the call
- Review all RTK query call sites and ensure they aren't relying on data/status being top-level properties. The callsite is responsible for deserializing and performing actions based on type

Considerations:
- The `unwrap` method on RTK mutations throws the `error` property, which will be a serialized ErrorObject, not an Error instance. Our `errors.ts:selectError` method warns if a non-Error subclass is thrown

Other Options:
- Another option is to have the Redux serializable check ignore the RTK errors, so we can store real Error instances in the Redux store. This would probably OK because: 1) we don't use redux-persist on the state, 2) we don't mutate error objects ever

Related/Discussion
- TIL: RTK actually includes the serialization library we use as part: https://redux-toolkit.js.org/api/other-exports#miniserializeerror
- Some information on muting serialization warnings: https://github.com/reduxjs/redux-toolkit/issues/1273

**Comment by fregante** [comment]
If RTK already handles the serialization then we shouldn't do anything about it, but I don't know enough about RTK to be confident. It just feels that it should be unnecessary.

**Comment by johnnymetz** [comment]
This sounds good. [Docs](https://redux-toolkit.js.org/rtk-query/usage/customizing-queries#basequery-function-return-value) say:

> At its core, a baseQuery function only needs to have the minimum return value to be valid; an object with a data or error property.

Do we also want to rip out `data` and `status` from the app's base query [here](https://github.com/pixiebrix/pixiebrix-app/blob/main/pixiebrix-app/src/services/baseQuery.ts#L24)?

**Comment by twschiller** [comment]
When we implement this, I think we want to turn off the ["A non-Error was thrown" warning](http://github.com/pixiebrix/pixiebrix-extension/blob/fd14c1096222ff7d769b95626bcc44a6f021be5f/src/errors.ts#L493-L493) for arguments that pass the http://github.com/pixiebrix/pixiebrix-extension/blob/fd14c1096222ff7d769b95626bcc44a6f021be5f/src/errors.ts#L497-L497 check

Otherwise, we'd have to explicitly call deserializerError in React components that call `unwrap` on a mutation or throw the error of an RTK query
