### ISSUE TITLE
CSP, images, sidebar, markdown

### ISSUE THREAD

**Issue by orliesaurus** [pixiebrix/pixiebrix-extension#3135]
As a user I want to embed an image using markdown in the sidebar so I can display an image alongside the rest of my text

![image](https://user-images.githubusercontent.com/4209733/162631242-d940579f-223d-4554-9756-e367e046c1e7.png)
![image](https://user-images.githubusercontent.com/4209733/162631264-e5996495-a400-44b5-905f-98bec0d80072.png)

Might be related to the manifest.json sec policies as mentioned here (diff usecase but similar enough?): https://stackoverflow.com/questions/34950009/chrome-extension-refused-to-load-the-script-because-it-violates-the-following-c

**Comment by twschiller** [comment]
Thanks for reporting @orliesaurus. Yes, this is related to the Content Security Policy

Related
- https://github.com/pixiebrix/pixiebrix-extension/pull/3019#issuecomment-1077967069
- https://github.com/pixiebrix/pixiebrix-extension/issues/3059
