### ISSUE TITLE
Active blueprint disappears from side in sidebar if extension is not available

### ISSUE THREAD

**Issue by twschiller** [pixiebrix/pixiebrix-extension#3139]
Steps to reproduce
- Toggle "Show X unavailable"
- Select a blueprint containing only unavailable extensions
- Expand the blueprint
- Select the extension
- Select the blueprint

Expected behavior:
- The blueprint and extension is still shown in the sidebar

Actual behavior
- The blueprint disappears

**Comment by BLoe** [comment]
I'm not able to reproduce the issue:
https://www.loom.com/share/1ba1be075a424e0d91385eccf73d6149

**Comment by BLoe** [comment]
Todd reproduced in person, seems like the element is disappearing from `elements` somehow in the sidebar, I'll investigate more

**Comment by twschiller** [comment]
@BLoe I can't reproduce this anymore (I tried on 363f31f84695ff4dd353d347b79d79b5ec3341cd). Closing and will re-open if it comes back up again
