### ISSUE TITLE
Sort Page Editor sidebar entries alphabetically

### ISSUE THREAD

**Issue by twschiller** [pixiebrix/pixiebrix-extension#3140]
Context
- As a Page Editor user, I need to quickly be able to find an extension/blueprint
- In the future, we might introduce search/filtering to help find the one you're looking for
- Currently, it hard to find it if you have a lot activated because the aren't in a predictable order. (At least not on 1.5.10-beta.1 with the `page-editor-blueprints` feature flag enabled

**Comment by BLoe** [comment]
The current sorting is blueprints first, personal extensions second. Blueprints are sorted alphabetically by name, extensions within blueprints are sorted alphabetically by name, and personal extensions are then sorted alphabetically by name. Are you seeing a case where this behavior isn't working correctly? Or are you wanting to change up how we sort things? Would you rather see blueprints and personal extensions mixed together in overall alphabetical order?

**Comment by twschiller** [comment]
I think I was confused because I had multiple blueprints expanded

I think we should move toward:
- Sort all top-level entries alphabetically. Sort alphabetically by extension within a blueprint
- Only have one blueprint expanded at a time
- Visually show which items are part of the selected blueprint, e.g., a light blue background for the non-selected items associated with the blueprint

**Comment by BLoe** [comment]
Also prepend the blueprint item with a document icon to distinguish
