### ISSUE TITLE
Reset extension after adding to a blueprint

### ISSUE THREAD

**Issue by BALEHOK** [pixiebrix/pixiebrix-extension#3206]
Steps to reproduce:
1. Add extension to a blueprint.
2. Reset extension.

Expected: (probably) see the extension not dirty and included in the Blueprint right after step 1.
Actual: after 1 I see the Blueprint and the Extension marked as dirty; after 2 I get an error.
If I refresh the PageEditor my extension disappears completely (screenshot #3)

After step 1. The `Action button` extension was added to the Blueprint. Both extension and the Blueprint are dirty.
<img width="1287" alt="Screen Shot 2022-04-19 at 8 51 03 PM" src="https://user-images.githubusercontent.com/3116723/164078092-bc58363b-ed06-434d-8fe2-5ef6ea75edcd.png">

Reset the extension (point 2), get the error.
<img width="644" alt="Screen Shot 2022-04-19 at 8 51 27 PM" src="https://user-images.githubusercontent.com/3116723/164078103-8c172d09-429c-413b-864b-97bc3cdc2c60.png">

After refresh extension dissapears.
<img width="1291" alt="Screen Shot 2022-04-19 at 8 51 45 PM" src="https://user-images.githubusercontent.com/3116723/164078104-69d8af29-2ccb-4160-af94-05b3f4a91aab.png">

If after 1 I select the Blueprint and Reset the blueprint I see the following:
<img width="1288" alt="Screen Shot 2022-04-19 at 8 52 48 PM" src="https://user-images.githubusercontent.com/3116723/164079464-80ca9a70-640f-4d14-8930-bffcb97ca11b.png">

**Comment by BLoe** [comment]
@BALEHOK It's expected that a blueprint will be marked dirty if any of its extensions are dirty. Also, after resetting the blueprint here, the extension will be gone, since you've now uninstalled the personal extension when adding to the blueprint, and removed the new copy from the blueprint when you reset it.
