### ISSUE TITLE
JQ fromdate error gets cut off in page editor

### ISSUE THREAD

**Issue by twschiller** [pixiebrix/pixiebrix-extension#3216]
Steps to reproduce
- Add a jq brick with filter `"" | fromdate`
- JQ will throw the error `does not match format "%Y-%m-%dT%H:%M:%SZ"`
- The side panel will show the error as `%SZ"`

It looks like it also gets cut off in the console log of the error

Depending on what the problem is/how hard it is to fix, we can determine prioritization

**Comment by BALEHOK** [comment]
It is JQ library that cuts the error message.
At [this point](https://github.com/pixiebrix/pixiebrix-extension/blob/31d0e91d14fbbac50116e89dac54fce028bface4/src/blocks/transformers/jq.ts#L68) the error is as follows:
``` javascript
{
  message: "%SZ\"",
  stack: "jq: error (at <stdin>:0): date \"\" does not match format \"%Y-%m-%dT%H:%M:%SZ\"\n"
}
```

We probably can:
- match the exact message and return a predefined error text in this case
- try to match weird error messages, like with length <= 10 chars or so, and return (parsed) stack trace

**Comment by twschiller** [comment]
@BALEHOK Thanks for investigating. Can you open an issue with the jq-web project?

For our purposes, I think it'd be good to use a regex to match `jq: error (at <stdin>:0): .*` and grab the raw error message. If that pattern doesn't match, we can fall back to the message

**Comment by BALEHOK** [comment]
While fixing this bumped into another issue. If an error is not serializable and it makes its way to Logs, redux constantly complains about non-serializable value in the store, clogs the console output, and kills CPU.

<img width="1088" alt="image" src="https://user-images.githubusercontent.com/3116723/166524372-b6055dd0-7310-4271-9c8a-ced9b61768ad.png">

**Comment by BALEHOK** [comment]
Opened the issue with `jq-web` https://github.com/fiatjaf/jq-web/issues/24
