### ISSUE TITLE
Can't set alias in create alias screen of "Create new blueprint" modal

### ISSUE THREAD

**Issue by orliesaurus** [pixiebrix/pixiebrix-extension#3226]
I was creating my alias through this modal a after wanting to create a blueprint, however after choosing a username, nothing happens

https://www.loom.com/share/910ae4dcb4f14b6cb8855f7fbd8db835
![image](https://user-images.githubusercontent.com/4209733/164336415-27e3b716-dc52-45b6-b7cc-d8495928b0f0.png)

**Comment by BLoe** [comment]
🎉
