### ISSUE TITLE
Bug: Extensions are not cleared from the page editor when a user logs out of the extension

### ISSUE THREAD

**Issue by BLoe** [pixiebrix/pixiebrix-extension#3229]
Steps to reproduce:
* log into pixiebrix
* create a new extension
* save it without creating a blueprint (creates a personal cloud extension)
* log out from the admin console
* log in to another account
* reload the page editor

Expected:
* See no activated extensions
Actual:
* See extensions from previous user

**Comment by fregante** [comment]
I think the solution to this is too simply to have it stale'd out:

1. listen to auth changes
2. on logout, run `location.reload()`

**Comment by BLoe** [comment]
@fregante I don't think refreshing the page clears activated mods

**Comment by fregante** [comment]
I don't know the inner workings, but way uninstall then instead of clearing the storage?

What should the user expect to see after logging out? I feel that after logging out, the extension should look like just installed, which is a `storage.local.clear()` call away

**Comment by BLoe** [comment]
@twschiller I'll defer to you on prioritization of this

**Comment by twschiller** [comment]
> @twschiller I'll defer to you on prioritization of this

Not a priority - should focus on bugs/UX impacting authenticated users
