### ISSUE TITLE
Handle copying marketplace blueprints

### ISSUE THREAD

**Issue by BLoe** [pixiebrix/pixiebrix-extension#3233]
When a user activates a marketplace blueprint, and then attempts to edit it and save in the page editor, currently the api throws an error. We should handle this case and preset the user with an option to save a personal copy of the blueprint.

I think we should preset a modal that has a message that says "You do not have permissions to edit this blueprint. Save as a new blueprint?" and then have "cancel" and "copy" buttons. On confirm (copy), we then just show the standard create-recipe modal with values copied in from the first blueprint, and the id scope swapped to the user's scope.

If the user saves a copy, we should de-activate the marketplace blueprint in order to prevent confusion to the user caused by two active, duplicate blueprints.

**Comment by twschiller** [comment]
>  to save a personal copy of the blueprint

They can create the blueprint with whatever scope they're allowed to save to
