### ISSUE TITLE
Selector inference for findAncestorsWithIdLikeSelectors including known-bad selector patterns

### ISSUE THREAD

**Issue by twschiller** [pixiebrix/pixiebrix-extension#3258]
Context
- Some frameworks (vue, embers) use auto-generated ids that aren't consistent across page loads
- We exclude those in calls to [getCssSelector](http://github.com/pixiebrix/pixiebrix-extension/blob/57d5440ac8a65dff182a355c7b5456a1fbdd8646/src/contentScript/nativeEditor/infer.ts#L568-L568)
- The new [findAncestorsWithIdLikeSelectors](http://github.com/pixiebrix/pixiebrix-extension/blob/57d5440ac8a65dff182a355c7b5456a1fbdd8646/src/contentScript/nativeEditor/infer.ts#L613-L613) code does not exclude them. Therefore, we're generating known bad selectors

![image](https://user-images.githubusercontent.com/1879821/165353662-d5916211-87ec-4844-bb11-8dc1ed887809.png)

Implementation Sketch
- We need to update findAncestorsWithIdLikeSelectors to exclude the known bad selectors

**Comment by fregante** [comment]
That function specifically selects elements with unique attributes, which has no overlap with the blacklist. I think the issue is the attribute selector generator since it just receives the list of elements that `findAncestorsWithIdLikeSelectors` generates. 

It should be an easy change, but I won't be able to look into this before Sunday/Monday

**Comment by fregante** [comment]
I'm not sure where this is happening. All the new functions I implemented operate on a whitelist and they call [getCssSelector](https://github.com/pixiebrix/pixiebrix-extension/blob/57d5440ac8a65dff182a355c7b5456a1fbdd8646/src/contentScript/nativeEditor/infer.ts#L568-L568), so they cannot produce blacklisted selectors.

- `findAncestorsWithIdLikeSelectors` uses `UNIQUE_ATTRIBUTES_SELECTOR`
- `inferSelectorsIncludingStableAncestors` uses `getUniqueAttributeSelectors` which uses `UNIQUE_ATTRIBUTES`

I need a site where you're seeing this to replicate it.
