### ISSUE TITLE
Automatically upgrade a blueprint's apiVersion if its extensions have been upgraded

### ISSUE THREAD

**Issue by BLoe** [pixiebrix/pixiebrix-extension#3267]
### Problem summary
Our auto-upgrade-extensions code will take v2 extensions and update them to v3, but there is currently nothing that handles modifying the apiVersion of a _blueprint_ in the page editor. This causes an issue where users are unable to save a currently-v2 blueprint in page editor if they even just _open_ one of the extensions, since that causes the v2->v3 upgrade logic to execute, and now the extension apiVersion does not match the blueprint (nor its sibling extensions, for that matter).

### Proposed solution
In the case where all extensions in a blueprint have a matching apiVersion that is higher than the blueprint, we should just bump up the blueprint version to match its extensions.

In the case where at least one extension has been opened it the page editor, and the blueprint has other extensions that have _not_ been opened, and thus haven't been auto-upgraded, we need to decide how to handle saving the blueprint.

I propose that we change the auto-upgrade logic to execute on every extension in the blueprint at once, as soon as any single extension is selected in the page editor. We know that all extensions in a blueprint need to have matching apiVersions to begin with, so this logic should be somewhat straightforward to implement. This will keep all extensions' apiVersions in a blueprint in lock-step together as far as any automatic upgrade goes. This also collapses the previous if-branch into just the easy path, so we then can just apply the aforementioned logic to update the blueprint's apiVersion if all its extensions having a higher, matching apiVersion.

### Two-part implementation sketch, one easy, one medium:
1. _(easy)_ - Near [saveHelpers.ts line 365](https://github.com/pixiebrix/pixiebrix-extension/blob/main/src/pageEditor/panes/save/saveHelpers.ts#L365), add another check inside that if-condition to update the blueprint apiVersion if the extension apiVersion is higher, otherwise throw the error, instead of always throwing
2. _(medium)_ - Near [ElementWizard.tsx line 129](https://github.com/pixiebrix/pixiebrix-extension/blob/main/src/pageEditor/ElementWizard.tsx#L129), expand this logic to check the extension for a `recipe`, and if found, upgrade all extensions in the recipe. We'll probably want to split this logic out into either an async thunk or just a separate helper function in a hook, since we'll need to convert any unchanged, installed extensions into form elements, etc.

**Comment by twschiller** [comment]
Closing, the switchover to v3 was long enough ago that we don't need to upgrade. We can manually upgrade any blueprints that are important enough to switch over
