### ISSUE TITLE
The page editor left-hand side bar is re-rendering constantly

### ISSUE THREAD

**Issue by BLoe** [pixiebrix/pixiebrix-extension#3271]
You can see the extension icons flickering between the generic puzzle piece and the specific extension-point icons as you do various actions around the page editor. A good one is to add a brick to an extension, open the add-brick modal, and scroll up and down the search results, while watching the sidebar icons flicker in the (greyed-out) background as you scroll.

**Comment by twschiller** [comment]
This isn't bad in production builds, but is a real drag on developer ergonomics

**Comment by twschiller** [comment]
> This first PR helped a ton, but I'm still seeing the icon flickering in some situations, like expanding/collapsing a blueprint. I think there's a bit more we could do to try and reduce sidebar re-renders at some point in the future.

Closing this for now. Will create a follow up ticket
