### ISSUE TITLE
Blueprint options don't support dropdown with labels (during activation)

### ISSUE THREAD

**Issue by BLoe** [pixiebrix/pixiebrix-extension#3273]
With the regular `Dropdown` field type, it's showing an active field toggle that has `Select...` and `Text` options, but selecting `Text` does nothing.

With the more complex `Dropdown with labels` field type, something is going horribly wrong and it's showing basically an empty-schema, fully-toggle-able, anything-goes style field input, with no sign of the configured options from page editor.

**Comment by twschiller** [comment]
Our Activation Wizard uses our toggle fields (not RJSF) and does not support `Dropdown with labels` yet
