### ISSUE TITLE
Pressing enter in Activation Wizard during reactivate causes duplicate extensions to be create

### ISSUE THREAD

**Issue by twschiller** [pixiebrix/pixiebrix-extension#3275]
Steps to reproduce
- Reactivate a blueprint with a dropdown option
- Start typing and press enter
- PixieBrix installs new extensions without clearing the old ones

Related:
- https://github.com/pixiebrix/pixiebrix-extension/issues/3273

Discussion:
- https://stackoverflow.com/questions/895171/prevent-users-from-submitting-a-form-by-hitting-enter

**Comment by BLoe** [comment]
@twschiller I'm not able to reproduce this, pressing the enter key doesn't seem to do anything for me while on the blueprint options in the activation wizard. I'm on Chrome/macOS, did you see this on a different system/browser than that?

**Comment by twschiller** [comment]
@BLoe could you try connecting with @MMirandi to reproduce? If you're not able, then I can send over a loom

Reminder that the blueprint needs to start as active

**Comment by BLoe** [comment]
I'm not able to reproduce this on `main`, `release-1.6.1`, or `release-1.6.0`.
