### ISSUE TITLE
Blueprint extensions showing as doubled

### ISSUE THREAD

**Issue by twschiller** [pixiebrix/pixiebrix-extension#3306]
Context
- https://pixiebrix.slack.com/archives/C02CN01JXAA/p1651257584335789
- I've also seen an issue on custom machine where buttons in blueprint are being added multiple times 
- Not sure if these are related. But appear to be triggered when you click on the extension without making changes

**Comment by BLoe** [comment]
I'm not able to reproduce this on `main`, `release-1.6.1`, or `release-1.6.0`.
