### ISSUE TITLE
Can't "Save As" blueprint shared by someone else that uses personal scope

### ISSUE THREAD

**Issue by twschiller** [pixiebrix/pixiebrix-extension#3316]
Steps to Reproduce
- Have someone define a blueprint with a personal scope
- Share it publicly
- Have someone else install it
- They modify the blueprint in the page editor
- There's no way for them to "Save As" and they get a permissions error on save

**Comment by BLoe** [comment]
I'm having trouble reproducing this. I pinged Mike, and I'll try to work with him to figure out how he encountered this issue.

**Comment by BLoe** [comment]
Fixed on the back end with https://github.com/pixiebrix/pixiebrix-app/pull/1613
