### ISSUE TITLE
When you move a sidebar panel into a blueprint, you'll get two panels

### ISSUE THREAD

**Issue by twschiller** [pixiebrix/pixiebrix-extension#3326]
Context
- https://pixiebrix.slack.com/archives/C02CN01JXAA/p1651596855223719

Workaround
- Reload the page

Diagnosis
- When you move into a blueprint, we generate a new extension id for it
- We need to remove the panel that's associated with the old extension id

**Comment by BLoe** [comment]
Also happening if you copy a public blueprint with a sidebar.
