### ISSUE TITLE
Document builder code improvements

### ISSUE THREAD

**Issue by BALEHOK** [pixiebrix/pixiebrix-extension#3331]
Related to #3285 

To make it easier to read and understand the code of Document builder we need to apply certain refactoring:
1. Rename `activeElement` and `setActiveElement` to `activeElementName` and `setActiveElementName` respectively.
2. "element" refers to the FormState elements for extensions and also for the elements of the Document. Such naming can be confusing and one of the entities needs to be renamed.
3. There are two helper functions [`joinName`](https://github.com/pixiebrix/pixiebrix-extension/blob/main/src/utils.ts#L54) used in FormBuilder and [`joinElementName`](https://github.com/pixiebrix/pixiebrix-extension/blob/main/src/components/documentBuilder/utils.ts#L18) used in DocumentBuilder. These functions have a subtle difference in the implementation and it can be confusing to figure out which one should be used in a certain place. As an option, the functions can be merged having an extra argument specifying if it needs to escape the special characters in the Formik path.

**Comment by twschiller** [comment]
Thanks for capturing the issue

> Rename activeElement and setActiveElement to activeElementName and setActiveElementName respectively.

👍  If we wanted to, we could also introduce nominal typing for document builder names/paths (like we do to distinguish UUIDs from registry ids)

> "element" refers to the FormState elements for extensions and also for the elements of the Document. Such naming can be confusing and one of the entities needs to be renamed.

My initial gut reaction is that we should find a better name for the Page Editor entities. "Element" makes sense in the document context, as it's analogous to HTML elements

There some related work:
- Cleaning up our naming of extensions/blueprints: https://github.com/pixiebrix/pixiebrix-extension/issues/2969
- I couldn't find the ticket on refactoring the Redux vs. Formik state in the Page Editor

> These functions have a subtle difference in the implementation and it can be confusing to figure out which one should be used in a certain place

If they should be used in different domain, I would keep them as exported functions with separate names. Under the hood we they could call the same helper method if we wanted, though.

Maybe we could do: `joinFormikName` and `joinDocumentName`?

Or, if we use a single function, we need to make the "mode" argument required to force the user to indicate what context it's being used in

**Comment by BLoe** [comment]
@grahamlangford This might make more sense to fold into the upcoming Document builder UX improvements rather than hang around as a separate DX ticket 🤷‍♂️

**Comment by twschiller** [comment]
The document builder spec work won't cover internal naming conventions/organization. Agree it makes sense to do alongside the Document Builder improvements, but should likely stay as DX
