### ISSUE TITLE
A saved sidebar extension, when removed, still renders its panel when the pixiebrix sidebar is toggled off/on

### ISSUE THREAD

**Issue by BLoe** [pixiebrix/pixiebrix-extension#3337]
### Steps to reproduce:
1. create a sidebar extension
2. save it
3. render the panel
4. remove the extension from page editor
5. close and re-open the pixiebrix sidebar
6. the removed panel renders again

### Initial diagnosis:
In the sidebar content script, when a "dynamic" element is removed, both the extension and extensionPoint are removed. For some reason, with an installed extension, only the element is removed, and not the extensionPoint.
_See: [sidebar.tsx](https://github.com/pixiebrix/pixiebrix-extension/blob/main/src/contentScript/sidebar.tsx)_

**Comment by twschiller** [comment]
This might be fixed by https://github.com/pixiebrix/pixiebrix-extension/pull/4108
