### ISSUE TITLE
Service dependency not removed when you remove a brick using service variable from the document builder

### ISSUE THREAD

**Issue by twschiller** [pixiebrix/pixiebrix-extension#3340]
Steps to reproduce
- Use the document builder
- Add an HTTP Request brick to a button
- Select a service
- Remove the service
- The service dependency will be left in the Formik state

Questions/Considerations
- Does this problem also exist for top-level bricks?
- If you change the service from the dropdown, the old service dependency gets cleaned up

Context
- https://github.com/pixiebrix/pixiebrix-extension/pull/3339#issuecomment-1119175231

**Comment by BALEHOK** [comment]
Can't reproduce. Probably fixed by #3323
