### ISSUE TITLE
Show brick name and marketplace documentation link in Page Editor

### ISSUE THREAD

**Issue by twschiller** [pixiebrix/pixiebrix-extension#3354]
Context
- If you give a step a custom name, you can no longer see what brick it is
- For many bricks we have good "How to Use" content in the marketplace, but users don't know when to look there

Implementation Sketch
- Include brick name in card header (truncated?), with muted font color
- If the brick is in the marketplace and has a non-empty how to use section in the marketplace 
- Call reportEvent for "PageEditorViewDocumentation" with the brick id if the user clicks on the link

Considerations
- We're still experimenting with copy, e.g., "Documentation Available" vs. "View Documentation". We also might use an icon instead of the text if the text takes up too much space
- We should include a utm_source and other utm_ tags

Wireframes:
![image](https://user-images.githubusercontent.com/1879821/167324976-8b505582-52dc-4d08-b47a-d6e4a872ea26.png)

**Comment by twschiller** [comment]
@orliesaurus What utm_ tags do we need to use?

**Comment by orliesaurus** [comment]
utm_source=pixiebrix
utm_medium=page_editor (or pageEditor)
utm_campaign=docs
