### ISSUE TITLE
Clear extension logs when removing extension

### ISSUE THREAD

**Issue by BLoe** [pixiebrix/pixiebrix-extension#3360]
Following up from: https://github.com/pixiebrix/pixiebrix-extension/pull/3338#discussion_r867889261

We should clear logs when removing an extension, but currently the `clearLog` function isn't supposed to be imported directly into page editor react components, so we need a workaround for that.

**Comment by BALEHOK** [comment]
It needs to be registered and called via `messenger`. See the `clearLogs` for example:
https://github.com/pixiebrix/pixiebrix-extension/blob/f3355f3c19e2f73232692fbf02309124b8cd9aae/src/background/messenger/registration.ts#L126

**Comment by twschiller** [comment]
We might need to wait for https://github.com/pixiebrix/pixiebrix-extension/pull/3934 to be merged/or stabilize? @BLoe do you have a perspective?

@jcforest this is a good issue to see how communication between DevTools/Page Editor and the background works

**Comment by jcforest** [comment]
@twschiller okay i will take a look into this

**Comment by jcforest** [comment]
@twschiller what is the result of clearing logs action? How can user check logs are cleared or not?

**Comment by twschiller** [comment]
> @twschiller what is the result of clearing logs action? How can user check logs are cleared or not?

Once you've removed the extension, IIRC the only way to check the logs are to manually look in the IDB database in the Chrome Dev Tools. I will record a Loom of how to do that
