### ISSUE TITLE
Error improvements

### ISSUE THREAD

**Issue by fregante** [pixiebrix/pixiebrix-extension#3372]
- [x] Avoid circular references by moving around some error classes and error helper functions. Maybe as described in [this comment](https://github.com/pixiebrix/pixiebrix-extension/pull/3073/files#r872627908):
	  - utils/errors/businessErrors.ts
	  - utils/errors/clientRequestErrors.ts
	  - utils/errors/generic.ts
	  - utils/errors/errorHelpers.ts
- [ ] Look for errors that are being passed around serialized
- [x] Move `selectErrorFromEvent`/`selectErrorFromRejectionEvent` [out of `selectError`](https://github.com/pixiebrix/pixiebrix-extension/pull/3284#discussion_r862564957)
- [ ] Avoid [`NetworkErrorDetail`](https://github.com/pixiebrix/pixiebrix-extension/blob/a83eb33888ac76c1e84d5af4ca4dbcd7bfc0dca7/src/components/errors/NetworkErrorDetail.tsx#L52)/[`enrichBusinessRequestError`](https://github.com/pixiebrix/pixiebrix-extension/blob/a83eb33888ac76c1e84d5af4ca4dbcd7bfc0dca7/src/utils/enrichAxiosErrors.ts#L74) duplication 
- [ ] Possibly merge [selectServerErrorMessage](https://github.com/pixiebrix/pixiebrix-extension/blob/74b411ecc0c384b5298a80ba700fd1b944a7883c/src/errors.ts#L404)/`selectNetworkErrorMessage` into [enrichBusinessRequestError](https://github.com/pixiebrix/pixiebrix-extension/blob/a83eb33888ac76c1e84d5af4ca4dbcd7bfc0dca7/src/utils/enrichAxiosErrors.ts#L58-L65) so that AxiosError never makes it out out the latter
- [ ] Replace `rejectOnCancelled` with an inline cancellation mechanism

	
Follows

- https://github.com/pixiebrix/pixiebrix-extension/pull/3073

**Comment by twschiller** [comment]
> Look for errors that are being passed around serialized

The 3 places where serialization has to occur is: 1) messenger API, 2) IDB, 3) Redux store

**Comment by fregante** [comment]
Yes, but they should not leave those areas IMHO. If an error is received by those three, they should immediately deserialize it before calling external functions, although I haven't looked into where this could happen exactly in RTK.

The messenger for example does this internally for **thrown** errors; for **passed** errors (like for `RECORD_ERROR`) we already deserialize them on reception: https://github.com/pixiebrix/pixiebrix-extension/blob/954e9893893de518a4ef79248d18afddeb5e1f38/src/background/logging.ts#L262-L274

**Comment by twschiller** [comment]
> Yes, but they should not leave those areas IMHO. If an error is received by those three, they should immediately deserialize it before calling external functions, although I haven't looked into where this could happen exactly in RTK.

RTK is just a nice toolkit for Redux. What's happening is that the error is getting serialized before it's placed in the store

Then, in our components we use hooks, e.g., `const {data, error, isFetching} = useMyCustomQuery(params)` to get that data out of the store. So we're have to do one of the following:

1. Modify the RTK library to deserialize the errors it passes back from its hooks, or
2. In each of our components deserialize the error coming from RTK

Option 2 is a non-starter -- it's too tedious/error-prone. Option 1 could make sense in the future

With respect to IDB, we could deserialize upon retrieval from IDB. However, there's some places where we store the errors in Redux. So we'd need to serialize before putting it into the Redux store there and then deserialize

All in all, our codebase really wants everything to be serializable 😄 . I think we're fighting an uphill battle against wanting to rely on classnames/prototypes/instanceof
