### ISSUE TITLE
Sidebar hidden (and not expandable) under 900px

### ISSUE THREAD

**Issue by abdullah4244** [pixiebrix/pixiebrix-extension#3381]
The hamburger menu is missing and the only way to open the sidebar is to widen the window:

**Comment by twschiller** [comment]
This extension issue corresponds to app issue https://github.com/pixiebrix/pixiebrix-app/issues/1244

**Comment by fregante** [comment]
The sidebar works correctly on the extension:


https://user-images.githubusercontent.com/1402241/168415270-875d72f8-3b5b-4e40-b590-72e418a99f01.mov

the only issue I see is that _it doesn't close_ when clicking the hamburger:


https://user-images.githubusercontent.com/1402241/168415260-494bc74c-7998-4710-8335-1d5ee2be20f9.mov

**Comment by twschiller** [comment]
Closing, fixed in the app repository in https://github.com/pixiebrix/pixiebrix-extension/pull/3383
