### ISSUE TITLE
Warn when editing a blueprint/extension that's open in a different Page Editor tab

### ISSUE THREAD

**Issue by twschiller** [pixiebrix/pixiebrix-extension#3430]
Context
- When working with multi-page blueprints, it's tempting to open up the Page Editor on multiple tabs
- The Page Editor instances aren't kept in sync, so it's easy to overwrite/lose work
- Keeping Page Editor instances in sync would be a big undertaking, with tricky behavior around how to reflect/merge changes across instances
- We want to warn the user before the make changes/put the tabs into a divergent state. (It would be frustrating to warn them only on save)

Implementation Sketch
- Add a Redux slice for mirroring extension/blueprint active+dirty state
- Keep that slice in sync across tabs -- there's likely an existing library? Or can use the extension's localStorage? (Does our existing redux-persistor already support the use case?

**Comment by twschiller** [comment]
>  is looking at whether it is feasible to keep multiple page editor tabs in sync

What does "in sync" mean? Just the unsaved changes? Or also what's active/showing in the Page Editor? Let's make sure we're being clear on what the UX should be

**Comment by BLoe** [comment]
We need to carry over probably about 3 story points for this ticket @corinnemayans
