### ISSUE TITLE
Improve Form Builder UX for default value that's not listed in Options

### ISSUE THREAD

**Issue by orliesaurus** [pixiebrix/pixiebrix-extension#3435]
I was making a modal form.
I have entered a couple of options in the modal form dropdown as different items.

However when I go ahead and submit one of the option I hit an error as shown in the video below.
Could it be something with parsing '-' in the label of the dropdown?

Context: https://www.loom.com/share/80f475780c49461fa0614c8e35b76ccf

**Comment by twschiller** [comment]
@orliesaurus 

Could you try marking the default value as excluded (or copy-paste the option text you want to be default)? I think what’s happening I think is that the value when the form opens is actually “”, but the dropdown is showing the first value since "" doesn't match any of the values

**Comment by orliesaurus** [comment]
That seems to have fixed it @twschiller - good solution! By the way it wouldn't let me rename the field name and was default to example, but I think you already know about that one!

**Comment by twschiller** [comment]
> By the way it wouldn't let me rename the field name and was default to example, but I think you already know about that one!

That's fixed in 1.6.3-alpha.3 release if it's blocking you: https://github.com/pixiebrix/pixiebrix-extension/pull/3369
