### ISSUE TITLE
Deactivating blueprint resets blueprints screen page state

### ISSUE THREAD

**Issue by twschiller** [pixiebrix/pixiebrix-extension#3449]
Context
- When you deactivate a blueprint, it resets the scroll position (and search filters?). So deactivating multiple blueprints is tedious

**Comment by fregante** [comment]
I think this applies to every action that brings you out and back into the blueprints screen, including simply clicking "Activate" (without proceeding) and going back:

![gif](https://user-images.githubusercontent.com/1402241/197359511-7766c02c-8023-4837-88c6-a8c31ae06249.gif)

The whole component state is lost, essentially. I think for this purpose there's the native `history.state` API but I'm sure React Router/history has its own API.

It would be nice to store the filter and perhaps search in the URL itself, via `history.replaceState`, like:

```
/options.html#/blueprints?filter=active&q=pixie
```

Side note: The blueprints page has two addresses and we should probably pick one:

```
/options.html#/
/options.html#/blueprints
```
