### ISSUE TITLE
Try bumping GridLoader to 0.13.0-alpha.5

### ISSUE THREAD

**Issue by twschiller** [pixiebrix/pixiebrix-extension#3451]
Context: 
- https://github.com/davidhu2000/react-spinners/issues/386#issuecomment-1133992742

**Comment by fregante** [comment]
No luck

<img width="895" alt="Screen Shot 19" src="https://user-images.githubusercontent.com/1402241/169798200-6bbe0fdd-27c1-4046-b270-5a4a20f9c672.png">

**Comment by fregante** [comment]
We're now on v0.13

https://github.com/pixiebrix/pixiebrix-extension/blob/cea0b7e6210c401c916e4ca1d6d724baf1bc1dc7/package.json#L125
