### ISSUE TITLE
Refactor runtime type definitions

### ISSUE THREAD

**Issue by twschiller** [pixiebrix/pixiebrix-extension#3477]
There's too many domain-specific types in core, making it impossible to introduce certain types without introducing circular dependency

- [ ] Split out domain agnostic types, e.g., UnknownObjects
- [ ] Split domain-specific from core and types into separate files

**Comment by BLoe** [comment]
@twschiller @grahamlangford Not sure if there's anything more to do here after Todd's semi-recent type refactoring effort

**Comment by twschiller** [comment]
There's still a bit of a hairball in some of the types. But I think we can clarify and circle-back as part of the refactoring work. I'd close this as it doesn't have any detail

- https://github.com/pixiebrix/pixiebrix-extension/blob/627e3c4ea3ae64784152f0456343c52f9c317735/src/types/runtimeTypes.ts#L299-L299
