### ISSUE TITLE
parseDate’s `humanReadable` format is inconsistent (local vs utc)

### ISSUE THREAD

**Issue by fregante** [pixiebrix/pixiebrix-extension#3494]
https://github.com/pixiebrix/pixiebrix-extension/pull/3465 changed the format of `humanReadable` dates. Is this a test/mock issue or our code’s?

https://github.com/pixiebrix/pixiebrix-extension/blob/4ba9771e3d6d8c3d32557abdc6db3a6bec0a15e9/src/blocks/transformers/parseDate.test.ts#L68-L79

But the inconsistency actually isn't a new bug, it was there before as well:

https://github.com/pixiebrix/pixiebrix-extension/blob/4a55943f91050a80ec19d54c35574073dfa62a83/src/blocks/transformers/parseDate.test.ts#L66-L77

**Comment by BLoe** [comment]
`humanReadable` is just a really bad name. This is calling the `localeDate()` function which tries to make a readable date format that takes the user's locale into account. Maybe should call it `localeDate` or something instead. Could also add a standardized "readable" format if people want it I guess.

**Comment by twschiller** [comment]
> Could also add a standardized "readable" format if people want it I guess.

Marked as low-priority. Haven't heard any interest in parsing a human readable date to get a more formal human readable date.
