### ISSUE TITLE
QuickBar can't be closed by clicking outside it (can only be closed via esc)

### ISSUE THREAD

**Issue by fregante** [pixiebrix/pixiebrix-extension#3504]
I had fixed this before in the library and it worked, but no more:

https://user-images.githubusercontent.com/1402241/170852317-b1c23223-4a38-4b43-b285-6b2a7630e38a.mov

## Related

- https://github.com/timc1/kbar/issues/172
- https://github.com/timc1/kbar/pull/173

**Comment by twschiller** [comment]
> I had fixed this before in the library and it worked, but no more:

Yep, I noticed this last week as well. It's especially annoying when working testing a new quickbar in the Page Editor
