### ISSUE TITLE
The content script is injected twice (editor open, click browser action)

### ISSUE THREAD

**Issue by fregante** [pixiebrix/pixiebrix-extension#3510]
This bug caused the behavior described in https://github.com/pixiebrix/pixiebrix-extension/issues/3132#issuecomment-1094554105

Most of the content script already has duplicate avoidance, but that doesn't seem enough for the QuickBar.

## Steps to reproduce

1. Open new website without permissions
2. Open editor
3. Open PB sidebar (enables activeTab and the editor)

## Demo

You can see the `VM_number` prepended to the content script logs, which suggests another contentScript.js was injected.

https://user-images.githubusercontent.com/1402241/170886611-4ccb2ccf-ee08-4eca-9fd1-7e722fdc4eae.mov

## Causes

- The click calls `ensureContentScript` directly
- The click also notifies the pageEditor, which also calls `ensureContentScript`

## Maybe next

- [ ] Figure out why the `ready`/`installed` test isn't working
- [ ] Add option to `ensureContentScript` so that it doesn't attempt to inject via this code path

**Comment by fregante** [comment]
Additionally: While testing I also sporadically saw the same behavior even without the editor open, which is a little concerning.

**Comment by twschiller** [comment]
Moving out of 1.7.0 because it mainly impacts the Page Editor

> Additionally: While testing I also sporadically saw the same behavior even without the editor open, which is a little concerning.

That's more concerning because it can lead to messenger problems, e.g. https://github.com/pixiebrix/pixiebrix-extension/issues/3560

**Comment by fregante** [comment]
> * [ ]  Figure out why the `ready`/`installed` test isn't working

My guess is that `Symbol` is not reliable in this scenario and we need to move to **exclusively** use a Dom-based approach like we do for `ready`:

https://github.com/pixiebrix/pixiebrix-extension/blob/76dac918c8fd3304488d5bf7b36cc98a839a701a/src/contentScript/context.ts#L57

This is how I've been tracking duplicate injections in Refined GitHub: https://github.com/refined-github/refined-github/blob/a7c9dd3a0fe6f6ce22b16c8c4f31c7beefdac4e1/source/features/index.tsx#L124-L141

**Comment by twschiller** [comment]
> My guess is that Symbol is not reliable in this scenario

That's a good theory. If the two scripts run in different VMs, IIRC the symbol would not be the equivalent

**Comment by fregante** [comment]
Reopening this because it wasn't solved and because I'm seeing an additional issue likely caused by this:

1. Open new website without permissions
1. Open editor
2. Click on context menu item that opens the sidebar (`show-sidebar` is enough)

<img width="506" alt="No context menu found for extension" src="https://user-images.githubusercontent.com/1402241/181935142-ce6ae01e-7827-423b-b735-ac170e331468.png">

<img width="1097" alt="Screen Shot" src="https://user-images.githubusercontent.com/1402241/181935160-b8508351-31af-4148-979d-45a9d72eb173.png">

**Comment by fregante** [comment]
I think I'll close this ticked after doing this:

- [ ] Add option to `ensureContentScript` so that it doesn't attempt to inject via this code path

But in the meantime my other PR fixes the issue in my last comment:

- https://github.com/pixiebrix/pixiebrix-extension/pull/3915


https://user-images.githubusercontent.com/1402241/181935401-0550abf9-b5f5-4540-8fec-6ecac1d023a8.mov
