### ISSUE TITLE
Two storybook stories broken (webpack fixture issue)

### ISSUE THREAD

**Issue by twschiller** [pixiebrix/pixiebrix-extension#3542]
Two stories are broken due to webpack fixture loading: https://github.com/pixiebrix/pixiebrix-extension/pull/3538#issuecomment-1142072554

**Comment by fregante** [comment]
Both stories seem to work without error now

<img width="1102" alt="Screen Shot 3" src="https://user-images.githubusercontent.com/1402241/195523450-36dacf75-aa64-45a1-bd99-ced655570e07.png">
