### ISSUE TITLE
New brick modal design improvements

### ISSUE THREAD

**Issue by BLoe** [pixiebrix/pixiebrix-extension#3548]
### Polish
* Horizontal scroll on results grid ✅ 
* Mouse cursor “hand” on hover over the remove-tag X button in the search input ✅
* Save scroll position on results grid when returning from details view ✅
* Bottom padding on tag list ✅
* Move padding from results grid container into the results grid layout, so the top isn’t cut off by padding when scrolling ✅
* Remove icon from “All Categories”? 🚫
* Animate list/detail transition? 🚫
* Should backspace clear the search tag if the search field is empty? ✅
  * Yes - nice to have
* Tag labels - Min-width and reduce line height ✅

### Design fidelity
* Remove brick IDs? ✅
* Larger brick icon? 🚫
* ~Font(s)?~ 🚫 
* Remove the “Add Brick” text from the button in the results grid hover-quick-add button, so it’s just a +? ✅

**Comment by twschiller** [comment]
> Horizontal scroll on results grid

Are you referring to the scroll that's about the width of the vertical scroll? (That the sizing doesn't take into account the vertical scrollbar?). Something else?

Many issues are derived from using the result item from the old modal.

Additional Items
- Add margin around search results
- Lighten border color
- Remove “Official” badges
- Remove registry id
- Add a "Detail" link on hover
- Don't disable search when your on the details page. Just have change handler drop the person back into search mode. Alternatively, hide the search box when you're on the detail

**Comment by BLoe** [comment]
>Don't disable search when your on the details page. Just have change handler drop the person back into search mode. Alternatively, hide the search box when you're on the detail

Move back button up into header on details page, hide Add Brick title and search input.

**Comment by BLoe** [comment]
Telemetry:
* Click add brick (details/main page property)
* Click view details
* Change tag/category
