### ISSUE TITLE
Listener indicated async response by returning true, but channel was closed

### ISSUE THREAD

**Issue by twschiller** [pixiebrix/pixiebrix-extension#3560]
Context
- User reports this starting in 1.6.3, and it's still happening in 1.6.4
- When using the @pixiebrix/wait/element brick
- https://pixiebrixcommunity.slack.com/archives/C02TS1K83EX/p1654198610485169

Discussion
- Potentially related to https://github.com/pixiebrix/pixiebrix-extension/issues/3510

**Comment by fregante** [comment]
Copying this message from Slack:

> Could that be simply a closed tab? The message is basically saying:
> 
> - the onMessage listener didn't resolve before the tab was closed
> 
> It should be replicable with a raw:
> 
> ```
> a: browser.tab.sendMessage(1, 'msg')
> ```
> 
> ```
> b: browser.runtime.onMessage
>   .addListener(() => new Promise())
> ```
> 
> This will never resolve, so if you close the context B, you'll get that error on A

**Comment by fregante** [comment]
This issue is similar to:

- https://github.com/pixiebrix/pixiebrix-extension/issues/2902

Related:

- https://github.com/pixiebrix/webext-messenger/issues/66

I opened:

- https://github.com/mozilla/webextension-polyfill/issues/384
- https://github.com/mozilla/webextension-polyfill/pull/385

**Comment by twschiller** [comment]
Moving to 1.7.1. With the 1.7.0 release, will confirm if https://github.com/pixiebrix/pixiebrix-extension/issues/3510 solved the problem or not

**Comment by twschiller** [comment]
We haven't seen this recently and have been updating related messenger code. Will re-open as necessary

**Comment by fregante** [comment]
Likely it has been fixed/hidden by:

- https://github.com/pixiebrix/pixiebrix-extension/pull/3572

The underlying issue is being tracked in:

- https://github.com/pixiebrix/webext-messenger/issues/67
