### ISSUE TITLE
Brick modal page design issues

### ISSUE THREAD

**Issue by fregante** [pixiebrix/pixiebrix-extension#3574]
## An additional scrollbar is always visible (✅ done)

https://user-images.githubusercontent.com/1402241/172116659-40977f90-117c-427f-8406-90345e45c228.mov

## Scrolling is painful with trackpad

This is likely due to the virtual scrolling area, but scrolling stops after a few pixels when swiping on a trackpad on a Mac. In this demo I'm doing long swipes but they're all cut short.

https://user-images.githubusercontent.com/1402241/172116995-43761794-399c-4bf7-ab58-3925c8d1c221.mov

## Filtering should reset the scroll position

This also happens when picking a label. The current behavior is equivalent to:

1. searching "dogs" on Google
2. opening the third page
3. changing the search to "cats"
4. google opening the "cats" search still on the third page

https://user-images.githubusercontent.com/1402241/172118475-2c70671f-bc2e-42d7-8766-928e6adb7ac4.mov

## Tag labels appear around/below icon

Items with icons should always use the "media object" style, usually with the icon centered vertically. Bootstrap has its own component but we don't necessarily have to use that specifically.

https://getbootstrap.com/docs/4.0/layout/media-object/

This pattern is everywhere in the extension and we could find a common solution. Also seen in:

- https://github.com/pixiebrix/pixiebrix-extension/issues/3513#issuecomment-1140518645

<img width="135" alt="Screen Shot 8" src="https://user-images.githubusercontent.com/1402241/172117070-039dd6e3-428a-4ce4-b5fc-1b096e89e424.png">

## Minor: "Add brick" wraps even when there's plenty of space in the header

It makes sense that it does since it's technically in the sidebar, but it does seem strange since there's plenty of room. A fix might not be practical.

<img width="476" alt="Screen Shot 7" src="https://user-images.githubusercontent.com/1402241/172118298-ac19a250-354e-4f12-ae60-d514a4db09cc.png">

## Related 

- https://github.com/pixiebrix/pixiebrix-extension/pull/3541
- https://github.com/pixiebrix/pixiebrix-extension/issues/3548

cc @BLoe

**Comment by twschiller** [comment]
@fregante, thanks for reporting. Some of these will be addressed by https://github.com/pixiebrix/pixiebrix-extension/issues/3548 (draft PR pending)

We'll triage vs. the other Page Editor work for 1.6.5 and 1.7.0.

**Comment by fregante** [comment]
## "View details" on hover covers too much of the content

Hovering shouldn't completely hide the content, "Activate …" is no longer clear in this case:

<img width="317" alt="Screen Shot" src="https://user-images.githubusercontent.com/1402241/172520579-737b0e00-49c6-4c8c-8165-04c291a92215.png">

I would:

- drop "view details" (it's implied on the regular click)
- maybe make the Add button always visible and less vibrant

Example:

<img width="820" alt="Screen Shot" src="https://user-images.githubusercontent.com/1402241/172521484-a1c00992-1ed9-473b-90a6-bad67f514bd1.png">

**Comment by fregante** [comment]
## The current tag is shown twice

The current tag is already shown in the sidebar so it shouldn't _also_ be in the search bar. 

You can ignore this if you intend to show multiple tags in the future, but then I'd still probably show a dropdown/selector on the search bar instead of a sidebar

<img width="561" alt="Screen Shot 2" src="https://user-images.githubusercontent.com/1402241/172523532-0b26ef7b-7ffd-4c74-83c3-9a3ede51ad4c.png">

**Comment by twschiller** [comment]
> The current tag is already shown in the sidebar so it shouldn't also be in the search bar.

Thanks for the note. This behavior is intentional to make it clear the the user is searching within the Transform Data category when they're typing above

Additionally, in the sidebar in the future we plan on showing counts with the number of matches to help indicate if the user needs to switch categories to find what they're looking for
