### ISSUE TITLE
Incorrect handling of long brick names

### ISSUE THREAD

**Issue by twschiller** [pixiebrix/pixiebrix-extension#3597]
Steps to reproduce:
1. Add a brick
2. Add a long brick name, e.g., supercalifragilisticexpialidocious

Implementation Sketch
* Add text overflow property to the div? 

![image](https://user-images.githubusercontent.com/1879821/172421294-e9c8de57-3eb1-48d2-a68c-f99935163daa.png)

**Comment by fregante** [comment]
I'm stealing this because this problem can be fixed permanently
