### ISSUE TITLE
RTK errors lose `cause` (the page editor HTTP error log is broken)

### ISSUE THREAD

**Issue by fregante** [pixiebrix/pixiebrix-extension#3613]
Something (presumably RTK) is _only partially_ serializing errors, not `serialize-errors`. This is an example I'm seeing in the page editor: 

<img width="269" alt="Screen Shot 13" src="https://user-images.githubusercontent.com/1402241/172560790-e47f2399-2cd4-4e8a-b6f0-ac4a3513c257.png">

The error is thrown  when I try to expand this, which then crashes the app because it expects `cause`:

<img width="864" alt="Screen Shot 14" src="https://user-images.githubusercontent.com/1402241/172560826-93a53c14-5dc9-4b5b-8cf9-5c959a0c3812.png">

 The only place where we generate a RemoteServiceError has a `cause`:

https://github.com/pixiebrix/pixiebrix-extension/blob/e1c4679df66679a1d51e10100b18f69735f6a6e5/src/utils/enrichAxiosErrors.ts#L67

## Possible solution

RTK appears to expose a `serializeError` option but I didn't immediately find a way to implement this in our codebase.

- https://github.com/reduxjs/redux-toolkit/pull/812
- https://redux-toolkit.js.org/api/createAsyncThunk#options

## Related

Recently we've encountered errors that somehow lacked a `cause` property. Maybe around this time, but I'm not sure:

- https://github.com/pixiebrix/pixiebrix-extension/issues/3020

Found while looking into:

- https://github.com/pixiebrix/pixiebrix-extension/issues/3372

This worked three months ago:

- https://github.com/pixiebrix/pixiebrix-extension/pull/2860

RTK docs:

- https://redux-toolkit.js.org/api/createAsyncThunk#handling-thunk-errors

**Comment by fregante** [comment]
I bisected the cause back to this:

- #3073
 
I'm guessing it's because `cause` is ignored by RTK now since it's non-enumerable

**Comment by twschiller** [comment]
> Something (presumably RTK) is only partially serializing errors, not serialize-errors. This is an example I'm seeing in the page editor:

Not sure if I'm understanding, but the network errors are serialized here: https://github.com/pixiebrix/pixiebrix-extension/blob/37d8b1bce6f342c24b2c5e4e3201f029c3dbcac9/src/services/api.ts#L97-L97. It's using the serializeError method from `serialize-error`

**Comment by twschiller** [comment]
> Something (presumably RTK) is only partially serializing errors, not serialize-errors

The HTTP error log show bricks errors, which aren't calls made via RTK Query. They would be made through the background worker's [proxyService](https://github.com/pixiebrix/pixiebrix-extension/blob/25f039c56478ca860d525f239175b1fd5e331483/src/background/requests.ts#L256-L256) method with Axios

The serialization would happen at either: 1) the messenger boundary, and/or 2) storing the error in IDB with [recordLog](https://github.com/pixiebrix/pixiebrix-extension/blob/25f039c56478ca860d525f239175b1fd5e331483/src/background/logging.ts#L319-L319), 3) when the log record is read from IDB and placed in the Redux Slice (which we use RTK to write)

In cases 1/2, I would imagine any non-enumerable/serialized props would get dropped. For 3, Redux puts whatever you throw at it in the Redux Store, but has middleware that will show a warning. 

My hunch is it's probably No 2. not accounting for it right now
