### ISSUE TITLE
PLACEHOLDER: All blocks are passed into the brick modal in sub pipelines, so you can add invalid blocks in certain cases

### ISSUE THREAD

**Issue by BLoe** [pixiebrix/pixiebrix-extension#3629]
We probably need to find a way to calculate "relevant blocks" based on something other than the extensionPoint type so we can use it in sub pipelines.

**Comment by twschiller** [comment]
There's two main cases of invalid bricks:
* Effects in renderer pipelines. Although, Cancel/Error should be valid effects
* Renderers in action pipelines

I'm not sure if we want to hide them completely from the modal (which is confusing), vs. show a warning the user in the Page Editor. (The same holds true for the root pipeline)
