### ISSUE TITLE
Uninstalling the extension leads to 404 page

### ISSUE THREAD

**Issue by orliesaurus** [pixiebrix/pixiebrix-extension#3630]
After uninstalling the extension I am redirect to a page pointing at: `https://web.pixiebrix.com/uninstall?uid=f785091d-5ad6-4308-b490-blablablabla`

**Comment by mnholtz** [comment]
Duplicate issue on the www project: https://github.com/pixiebrix/pixiebrix-www/issues/425

**Comment by mnholtz** [comment]
Closing due to webflow uninstall page: https://www.pixiebrix.com/uninstall
