### ISSUE TITLE
Fix column layout of error details in the data panel

### ISSUE THREAD

**Issue by twschiller** [pixiebrix/pixiebrix-extension#3666]
Steps to reproduce (input validation)
- Add a jq brick and don't configure it
- Pass the output key to the parse URL brick

Steps to reproduce (network error)
- Add HTTP get brick pointing at https://httpstat.us/404 

Discussion
- The columns should wrap below a certain size
- The underlying component is also used in the Log Viewer in the editor and blueprints screen

Related Code
- https://github.com/pixiebrix/pixiebrix-extension/blob/3bb6296858bce35ff91fdcd56e7acd6f8ed571ce/src/components/logViewer/details/InputDetail.tsx#L24-L24

![image](https://user-images.githubusercontent.com/1879821/173246042-55d0f9d4-9b1a-4a88-b7f3-f267bddc42c6.png)

![image](https://user-images.githubusercontent.com/1879821/173247049-27e10acb-2f29-473e-a87d-6d9d0693852d.png)

**Comment by BLoe** [comment]
I think all of these weird formatting bugs are related to Federico's change to have all text elements default to wrapping. I think we'll end up in a better place overall, but we're going to have to just keep fixing these issues as we find them.

**Comment by BLoe** [comment]
@twschiller Isn't that spot with the network error where that bug is right now? How did you get it to display a network error? I'm not seeing that by using a HTTP Get brick hitting that url:

<img width="676" alt="image" src="https://user-images.githubusercontent.com/2801308/173252915-9cb02dc7-e713-4293-a325-9267fcf45d92.png">

**Comment by twschiller** [comment]
@BLoe this PR I merged in fixes the bug: https://github.com/pixiebrix/pixiebrix-extension/pull/3667. Let me know if you're still not able to get a response
