### ISSUE TITLE
Sub pipeline line overlaps with the Document node icon 

### ISSUE THREAD

**Issue by BALEHOK** [pixiebrix/pixiebrix-extension#3692]
1. Create Side panel extension, select Render Document node, add a Button to the document.
2. Collapse the Render Document tree.
3. Select Foundation Node (any other node).

Expected:
the document's node icon is clearly visible

Actual:
the pipeline line is displayed on the top of Document icon

<img width="231" alt="image" src="https://user-images.githubusercontent.com/3116723/173356352-2749a5d3-9335-431c-b945-0786dadd6784.png">

**Comment by twschiller** [comment]
@BLoe is this fixed now?

**Comment by BLoe** [comment]
Yeah this is fixed 👍
