### ISSUE TITLE
Refactor BrickModal - Split up into smaller components/files

### ISSUE THREAD

**Issue by BLoe** [pixiebrix/pixiebrix-extension#3709]
`BrickModal.tsx` is getting pretty large, with several helper functions, many type defs, and everything wiring up the brick results grid view, all in the same file. We should think about how to split this file up to organize the code better and help with readability.

**Comment by twschiller** [comment]
@BLoe please add Jest tests and Storybook entries as part of this too. That will help guide how to split up the code
