### ISSUE TITLE
Undesired result when using Quickbar + Screenshot brick

### ISSUE THREAD

**Issue by orliesaurus** [pixiebrix/pixiebrix-extension#3724]
Hi.

I found a bug in the screenshot brick when you use it with a quickbar, it takes a screenshot of the quickbar on top of the page below it.

I am not gonna lie, this happens once every 2-3 screenshots.

Quick hack/fix - add a sleep timer for 100ms before executing the screenshot brick.

for those who are curious here's an img of what comes out
<img width="1167" alt="image" src="https://user-images.githubusercontent.com/4209733/173857137-b9aa2b08-d47f-4501-8766-1b091c245f96.png">

- Chrome latest
- 1.7.0-alpha-9

**Comment by twschiller** [comment]
@orliesaurus thanks for reporting. Looks like the workaround is sufficient?

I think we'd need to add a check here that the quickbar is no longer on the page: https://github.com/pixiebrix/pixiebrix-extension/blob/c0040c426155e3569c166ddaed8b773d0832f0fa/src/extensionPoints/quickBarExtension.tsx#L234-L234
