### ISSUE TITLE
Renderer lint rules

### ISSUE THREAD

**Issue by twschiller** [pixiebrix/pixiebrix-extension#3815]
Context
- There can only be one renderer in each pipeline. 
- Renderer cannot be embedded in the control flow bricks
- We already warn if there are multiple renderers in the top-level pipeline

Discussion:
- We should see how we can have a single set of rules that can also apply to the Add Brick modal

Implementation Sketch:
- Warn is users have multiple renderers in a pipeline. Probably warn on both of them?
- Warn if the user puts a rendered in a control flow brick (e.g., if-else)

**Comment by twschiller** [comment]
> It shows errors for all the renderers in the pipeline but the last one

👍  LGTM

Technically the error would be more accurate to show on renderers after the first one. (Because I think PixieBrix will show the first renderer). However, the user should fix the error anyway, so what you've implemented works

**Comment by BALEHOK** [comment]
Fixed by #3861
