### ISSUE TITLE
Page editor validation improvements

### ISSUE THREAD

**Issue by BALEHOK** [pixiebrix/pixiebrix-extension#3847]
1. Do not run pipeline validation (Trace errors, renderer validation, etc) on every change of a block.
2. Persist validation results between nodes and elements switches.

**Comment by twschiller** [comment]
> Do not run pipeline validation (Trace errors, renderer validation, etc) on every change of a block.

I think running pipeline validation on input change is OK as long as it doesn't cause input lag. In the future, there will be pipeline validation that depends on the the block configuration/trace (e.g., are any unknown variables being referenced).
