### ISSUE TITLE
Show AA onboarding steps if app start page open

### ISSUE THREAD

**Issue by mnholtz** [pixiebrix/pixiebrix-extension#3848]
Currently, AA onboarding steps are only shown if a user has a partner serialized for the `me` endpoint. This only happens if the user has an organization membership. We want to ensure that these onboarding steps and theme are always shown in the onboarding flow regardless of organization membership.

See:
https://github.com/pixiebrix/pixiebrix-extension/blob/68855c2c99f2ec435e9be45f64ffe268ce34603c/src/background/installer.ts#L37-L42

**Comment by twschiller** [comment]
@mnholtz what's the status of this?

**Comment by mnholtz** [comment]
@twschiller I'm doubting that this is relevant anymore. We added an error view for AA End User links that the end user does not have an organization membership for. Will close if you don't see any other reason to keep this feature open.
