### ISSUE TITLE
Odd behaviour with blueprint search input

### ISSUE THREAD

**Issue by orliesaurus** [pixiebrix/pixiebrix-extension#3879]
When I open (for the first time, meaning hard refresh) the extension's view page where I can search for blueprint - I write some text in the search field "Search All Blueprints" then I mistakenly (muscle memory) hit "Enter/Return" and the whole view refresh

Expected behavior: No page refresh, results of search are shown.

Video of repro steps: https://www.loom.com/share/3c3d05bbccea454ba608215857a600ba

Thanks

**Comment by twschiller** [comment]
@abdullah4244 could you help look into fixing the behavior on "Enter/Return"? Let me know if you need additional clarification on intended behavior

**Comment by abdullah4244** [comment]
that is because default behavior of form is to send /submit data to server on Enter /Return 
so basically has to prevent that , creating pr
