### ISSUE TITLE
min-vw-100 bootstrap class breaks document preview

### ISSUE THREAD

**Issue by twschiller** [pixiebrix/pixiebrix-extension#3894]
Context
- Users have been applying min-vw-100 to address some gotchas with overflow/width in the document builder
- https://pixiebrix.slack.com/archives/C02CN01JXAA/p1658161796940299?thread_ts=1658104793.478029&cid=C02CN01JXAA

Implementation Sketch
- Ignore min-vw-* class in document preview. There's probably some classes we need to ignore as well?

Discussion
- Other ones: d-none

**Comment by fregante** [comment]
What's the expected solution here? Adding _any_ incompatible class would break it. This is the user’s mistake, right? Silently ignoring the user’s wishes is bad UX on top of that.



> * Users have been applying min-vw-100 to address some gotchas with overflow/width in the document builder

It sounds like this is what needs to be solved so users don't have to try adding this class in the first place.

**Comment by twschiller** [comment]
> What's the expected solution here? Adding any incompatible class would break it. This is the user’s mistake, right? Silently ignoring the user’s wishes is bad UX on top of that.

It's not a mistake. The CSS is valid for the rendered document, it's just not valid for the preview. (The preview is an approximation of the rendered document.)

The implementation sketch is to just exclude the problematic CSS classes when rendering the preview

> It sounds like this is what needs to be solved so users don't have to try adding this class in the first place

Correct, we have a related issue here for that particular issue: https://github.com/pixiebrix/pixiebrix-extension/issues/3792.

**Comment by twschiller** [comment]
> you'd just be able to access its contents directly, no messaging necessary

I think we'd still need to do some messaging/extra infrastructure because events in the preview (e.g., clicking an element) dispatches a Redux action to the Page Editor. Or does srcdoc get around that?

I think the easiest way to go will just be to denylist the corner-case utility class patterns. They use case wouldn't be worthintroducing any complexity into the Page Editor architecture

**Comment by fregante** [comment]
I don’t know how those events work, but I’m confident some `<Iframe>` component already exists to take care of this, for example via “react portal”. I know DOM events would definitely not travel across the iframe though.
