### ISSUE TITLE
Compress trace record data

### ISSUE THREAD

**Issue by twschiller** [pixiebrix/pixiebrix-extension#3897]
Context
- Our traces (and debug logging) snapshots the context when the brick is called
- For extensions with a lot of bricks and/or large values (e.g., from API calls) that can clog up the IDB
- There's needless redundancy between traces
- Tracing/program slice tools for real programming languages work by compressing the trace, e.g., storing diffs between program counters

Implementation Sketch
- In a trace "pre-" section, only include the diff from the previous trace record
- Link each trace record to the previous trace record

**Comment by fregante** [comment]
I used this in the past: it takes strings, outputs strings

https://github.com/pieroxy/lz-string

**Comment by twschiller** [comment]
> I used this in the past: it takes strings, outputs strings

Thanks, long-term I suspect we'll need to avoid storing the redundant data. But this is worth a quick look to see if it's a helpful stop gap
