### ISSUE TITLE
Show unavailable bricks in Add Brick modal as greyed out with reason

### ISSUE THREAD

**Issue by twschiller** [pixiebrix/pixiebrix-extension#3901]
Context
---
- Users get confused when they can't find a brick in Search Brick modal
- We can't expect new users to have a mental modal for why renderer/effect bricks aren't available in certain places
- The Page Editor currently hides bricks that aren't available
- Users get confused
- In the future, we will also want to indicate suggested bricks based on what the user has created

Implementation Sketch
---
- Replace the current availability check with a method that returns a message if the brick is unavailable
- Show unavailable bricks as greyed out and provide a message on hover

Considerations
---
- Should we still allow the user to add the brick even if it's unavailable? I think we should. The Page Editor will then show an error so the user will have to remove/move the brick

Design
---
- @icugideon could you coordinate with @BLoe on design for showing unavailable bricks

Related Issues
---
- https://github.com/pixiebrix/pixiebrix-extension/issues/3849

**Comment by twschiller** [comment]
Implementation Sketch for how to re-use existing analyses for the Add Brick modal. This approach is called "speculative analysis", you analyze the potential future states of the application by simulating the change and running an off the shelf analysis

1. Write an adapter function that takes, the:
   - Copy of the current element state
   - Brick 
   - Position
2. The adapter inserts the brick at position
3. The adapter runs the analysis
4. The adapter finds any annotations that were generated for the brick (taking the brick-level annotations, not the field-level annotations)
5. The adapter returns the annotations generated for the brick

**Comment by corinnemayans** [comment]
We'll use this issue to start practicing writing specs. @BLoe will look at 
[ ](https://www.notion.so/pixiebrix/Product-Specification-Checklist-6b9974974ca64302958af4ee277bddf8)
