### ISSUE TITLE
Design: brick and field-level annotations (errors, warnings, recommendations)

### ISSUE THREAD

**Issue by twschiller** [pixiebrix/pixiebrix-extension#3905]
Context
---
- In https://github.com/pixiebrix/pixiebrix-extension/issues/3863 we are improving our Page Editor architecture to allow us to provide better error message
- Validation framework specification: https://www.notion.so/pixiebrix/Blueprint-Page-Editor-Validation-ea42866ffa68463bac822b820455f444
   - See examples of annotations for different scopes here: https://www.notion.so/pixiebrix/Blueprint-Page-Editor-Validation-ea42866ffa68463bac822b820455f444#bfa09e78bcfc410ebe1b711917d57164
- These will display both static analyses (analyses from looking at the code, and dynamic based on the values)

Current UX
---

Brick-level error:
![image](https://user-images.githubusercontent.com/1879821/180573957-e663dfd2-fe04-4d0b-b1eb-6c24ca2ac06c.png)

Field-level error (NOTE: this particular error should be on the field, but is currently shown on the brick)
![image](https://user-images.githubusercontent.com/1879821/180573982-45e73b34-c1d5-4d9e-bfee-dd4b6cb5f2c7.png)

Object Error (NOTE: this particular error ideally should be on the hostname field, but is technically implemented as an object-level error):
![image](https://user-images.githubusercontent.com/1879821/180574071-65bd4fe3-2da0-49bf-a453-bafc484effa6.png)

Considerations
---
- We are planning at least 3 levels: Error, Warning, and Recommendation
- Bricks can have multiple annotation: (at different levels, same level)
- Some annotations may have additional details: detailed information, links to documentation, etc.

Other Information
---
- 7/22 design sync notes: https://www.notion.so/pixiebrix/Todd-Gideon-Design-Sync-356a07fb3ba84fbcad52b8a173702cd5

**Comment by icugideon** [comment]
## Brick-level annotation solution 
Solved using **Alerts**

![Alert](https://user-images.githubusercontent.com/23545614/182908595-889217c5-3792-4923-863b-8a76f98e3bc2.png)

> The Alert has various styles and properties for errors, warnings, recommendations, and more for various use-cases.

----

## Field-level annotations solution 
Solved using **Input Feedbacks**

![Input Feedback](https://user-images.githubusercontent.com/23545614/182908639-bb2859ff-06a2-43ae-b82c-83e50145221a.png)


> The Input Feedback has Success, Error, and Instructional/recommendation styles and properties for most input field annotations use-cases.



----
## Links: 
[Page Editor Design:](https://www.figma.com/file/RGcBtgkFHIBczxhKPKtaE5/Page-Editor?node-id=972%3A30242) 

[Alerts UI Component Documentation](https://www.figma.com/file/d46mjmu6xw3atpe5jvG5hN/%F0%9F%92%8E-Components?node-id=1043%3A23105)

[Input Feedback UI Component Documentation](https://www.figma.com/file/d46mjmu6xw3atpe5jvG5hN/%F0%9F%92%8E-Components?node-id=1043%3A23105)

**Comment by twschiller** [comment]
Discussed live here: https://www.notion.so/pixiebrix/Todd-Gideon-Design-Sync-Annotations-dec10231f031481d9c53d10151e9f528

Designs are ready for initial use. We'll use the "mild" variant
