### ISSUE TITLE
Google Sheets File Picker not showing in Page Editor

### ISSUE THREAD

**Issue by twschiller** [pixiebrix/pixiebrix-extension#3914]
Context
---
- Observed on client call with @twschiller and @mthek10 
- When clicking "Select" sheet in Page Editor, the Google File Picker was not shown. The select button stays disabled
- No errors in Page Editor console
- No errors on gapi startup in Background Page (gapi initialized message was displayed)

Discussion
--- 
- Brittany was experiencing problems with gapi where she had to reload the PixieBrix browser extension for calls to Google Sheets to work (requiring multiple reloads a day): https://pixiebrix.slack.com/archives/C02CN01JXAA/p1659400679658159

Related Code
---
- [FileWidget](https://github.com/pixiebrix/pixiebrix-extension/blob/d80d64d4a4401c584f1d7ffc2d64e5ecf8d7b7b9/src/contrib/google/sheets/FileWidget.tsx#L46-L46)

**Comment by twschiller** [comment]
@BLoe FYI, was getting an error in 1.7.3-beta.1 when using the File Picker in the Extension Console: https://github.com/pixiebrix/pixiebrix-extension/issues/3794#issuecomment-1212520960

**Comment by fregante** [comment]
Given that the `onerror` handler isn't producing [useful output](https://rollbar.com/pixiebrix/pixiebrix/items/5867/), what if we display this error to the user?

For example:

1. `onerror={() => gapiFailed = true}` (or something more elegant, like `await initGoogle()`)
2. When trying to use the gapi, check this loading state and show a notification if it results into an error

This notification would:

- give the user _at least some_ feedback
- prompt Brittany to check the console for further information regarding the load error (if it's in the editor, then she'd have to to open its dedicated console, not the page’s console)

**Comment by fregante** [comment]
> gapi initialized message was displayed

This means that the script was loaded and it was initialized successfully. Since `gapi.*` method calls would throw if the script completely failed, I assume that the user is already probably notified when that happens.

This sounds more like a gapi malfunctioning, for example:
- failed stylesheet injection: e.g. the modal is there, but outside the viewport)
- duplicate injections: gapi conflicts with itself

I still don't know the exact cause though.

**Comment by twschiller** [comment]
Notion spec for putting the GSheets bricks behind a GAPI loaded wall: https://www.notion.so/pixiebrix/Make-Google-Sheets-work-the-way-users-expect-041e91ede0d04a928d21b7bfe7f3482f?pvs=4#55601efc5d44410ba9f7af3b23f4424c

**Comment by twschiller** [comment]
Release 1.7.30 includes some fixes and telemetry for this issue. Closing this for now, and will re-open if we continue to see issues
