### ISSUE TITLE
Improve messaging around missing permissions for HTTP requests

### ISSUE THREAD

**Issue by fregante** [pixiebrix/pixiebrix-extension#3936]
This is a rehash/followup to:

- https://github.com/pixiebrix/pixiebrix-extension/issues/3054

The page editor shows several error messages after an HTTP brick fails due to permissions:

- > No response received. Your browser may have blocked the request. See https://docs.pixiebrix.com/network-errors for troubleshooting information
- > Network error
- > PixieBrix does not have permission to access https://deelay.me/5000/https://pbx.vercel.app/. Specify an Integration to access the API, or add an Extra Permissions rule to the extension.

## Edit tab

<img width="1013" alt="Screen Shot 12" src="https://user-images.githubusercontent.com/1402241/182131439-09a13020-2fa3-4bea-bb1e-1c656a2faa3f.png">

## Logs tab

This is particularly confusing in the logs, where the real error is hidden/collapsed:

<img width="998" alt="Screen Shot 13" src="https://user-images.githubusercontent.com/1402241/182131553-60acdb72-f04e-41be-9694-8399097fec70.png">

## Related

- https://github.com/pixiebrix/pixiebrix-extension/issues/3054

**Comment by twschiller** [comment]
This looks like a bug in enrichBusinessRequestError: https://github.com/pixiebrix/pixiebrix-extension/blob/03401b1564bab9f7ef0b93aafac6941c7b5dbd17/src/utils/enrichAxiosErrors.ts#L47-L47

It should be hitting the `ClientNetworkPermissionError` branch

**Comment by twschiller** [comment]
@BALEHOK this would also be a good area for a analysis engine analysis:

1. If the brick is HTTP get/post and the URL is not a template expression/variable
2. Check if PixieBrix has access to the URL or not
3. Annotate with an error if PixieBrix does permission for that URL
