### ISSUE TITLE
Saving in the editor triggers 3 requests that include all of my bricks ever created

### ISSUE THREAD

**Issue by fregante** [pixiebrix/pixiebrix-extension#3945]
<img width="360" alt="Screen Shot" src="https://user-images.githubusercontent.com/1402241/182431154-c1f15d40-798e-4787-aa4d-1a42bd9ec471.png">

The named endpoints shown here all push 70-200 items each:

<img width="674" alt="Screen Shot 3" src="https://user-images.githubusercontent.com/1402241/182431169-4f31de9c-6b6e-42b5-acdd-7c71d63d1e14.png">

The request total only ~70KB but take 1s-1.4s each, for a total of ~3 seconds to save a QuickBar extension with 2 bricks.

## Questions

1. Can these requests be limited to sending only the current extension? If further syncs are necessary, they can be done asynchronously in the background page.
2. How can I nuke all of my extensions? 😅 I need a batch "select all"

## Related

- https://github.com/pixiebrix/pixiebrix-extension/issues/2720

**Comment by fregante** [comment]
Side note: This other issue is more server-related, but I wonder if it's possible to reduce the time it takes to handle this 1.3KB request (800ms are spent on the server, not on the network):

<img width="405" alt="Screen Shot 4" src="https://user-images.githubusercontent.com/1402241/182433002-db506837-a8d2-40a0-bc6b-2e2873adc322.png">

**Comment by BALEHOK** [comment]
It is worth investigating why the mentioned PUT request is as big as 1.3KB

Another note.
From a Slack conversation:
> It makes 3 GET requests and 1 PUT. The issue is that the editor waits for all 4 requests

What probably happens is:
1. the Editor updates an extension
2. this update invalidates the RTKQ cache
3. RTKQ has to pull the blocks data required to render the Editor page
4. one of the invalidated buckets is the block definitions; we pull all of the available blocks in a single request (`/bricks`) that is getting only bigger.

**Comment by twschiller** [comment]
Yes, this is a known issue. IIRC, it's even less performant for blueprints. Right now, save performance isn't a priority

> This other issue is more server-related, but I wonder if it's possible to reduce the time it takes to handle the 1.3KB

The server actually does analysis of extensions/blueprints on save (it keeps track of the dependency graph, etc.). Getting the time down will involve adding some caching to the analyses

> How can I nuke all of my extensions? 😅 I need a batch "select all"

We can help you with that (will just delete from the server). It's becoming a problem for other devs as well too because dev/test extensions clutter the blueprints screen
