### ISSUE TITLE
Re-ordering brick causes page editor to crash

### ISSUE THREAD

**Issue by orliesaurus** [pixiebrix/pixiebrix-extension#3948]
on `v 1.7.2` when you re-order bricks this happens and causes the page editor to crash

https://www.loom.com/share/c60f412f61f445d88083b57edf1db702

**Comment by orliesaurus** [comment]
workaroud; copy and paste the brick @ the location you want it to be and delete the original brick

**Comment by orliesaurus** [comment]
That's right, exactly as you explained it! No I literally added it normally! Nothing funky about it!

**Comment by BLoe** [comment]
I was just able to reproduce it while chatting with Orlando in our 1:1, I can take a look at this if you want me to

**Comment by twschiller** [comment]
@BLoe @orliesaurus do we know what scope/set of extensions this will impact? Need to decide if this needs to go out in 1.7.3 vs. can wait for 1.7.4

**Comment by BLoe** [comment]
It happens with any random extension I set up with random blocks, so probably needs to go into 1.7.3
