### ISSUE TITLE
Crash on save when using the Translate brick in a new install of PB

### ISSUE THREAD

**Issue by BLoe** [pixiebrix/pixiebrix-extension#3951]
Steps to reproduce:
1. Install PixieBrix
2. Connect an account
3. Open the page editor
4. Add a Context Menu item
5. Add the Google Translate brick
6. Click Save

Expected outcome:

- Extension is saved correctly

Result:

- Extension "saves", but this error message is shown:
![image](https://user-images.githubusercontent.com/2801308/182699442-011963d7-7ad8-4327-adf3-c43645a72ea1.png)
- This happens every time Save is clicked, until the blueprints page is opened

**Comment by twschiller** [comment]
@BLoe I think this should be 1.7.3? Because this impacts the quick start the plan is to delay release as needed to get this in

**Comment by BLoe** [comment]
Ah ok sorry, wasn't sure about that, but makes sense 👍
