### ISSUE TITLE
Add "match pattern" array-fields to the validation system so we can show field-level errors for empty/invalid values

### ISSUE THREAD

**Issue by BLoe** [pixiebrix/pixiebrix-extension#3953]
Match patterns are array-fields on the foundation nodes of extensions, e.g.:
<img width="681" alt="image" src="https://user-images.githubusercontent.com/2801308/182706416-d7413d85-b387-4106-9c8d-de671b8c09be.png">

We should add field-level validation to these fields that will notify the user when they add a blank/invalid value into the match pattern list of any of the match pattern fields.

**Comment by BALEHOK** [comment]
Apart from validation these fields (Sites, Automatic Permissions, Sites/APIs) should have the same UX/UI.
It will be helpful for the users to see an explicit explanation of the differences between the URL Pattern fields.

**Comment by BLoe** [comment]
Yes, agreed. Let's use this ticket to track the full changes:
* Unify the UX of all "url pattern" fields
* Look at all the descriptions together and change them so it's more clear to users how each of them work and what the difference is
* Fully validate all of these fields for valid match patterns in each entry of the array using the `Analysis` engine

**Comment by twschiller** [comment]
@BALEHOK follow up from out meeting yesterday. For this ticket, I just want to focus on the validating the UrlMatchPatternField (which uses UrlMatchPatternWidget). The format is here: https://developer.chrome.com/docs/extensions/mv2/match_patterns/ (see the bottom of the page for examples of invalid match patterns). @fregante I think can point you to exiting methods for helping to validate the match patterns

We will do follow up ticket on improving the UX and in-tool explanations for the differences between: Sites, Extra Permissions, URL Patterns, etc. These are tied to some underlying considerations on the browser extension API and our runtime

**Comment by fregante** [comment]
@twschiller  patternToRegex validates the patterns and throws an error if they're invalid

**Comment by BALEHOK** [comment]
> The regex offered by webext-patterns doesn't allow for specific errors.

I.e. `patternToRegex` doesn't provide a detailed error on what exactly is wrong with an URL. We can't use it.
