### ISSUE TITLE
Sidebar sometimes shows completely blank screen when opened

### ISSUE THREAD

**Issue by twschiller** [pixiebrix/pixiebrix-extension#3957]
Context
---
- https://pixiebrix.zendesk.com/agent/tickets/136
- The issue is intermittent, might be correlated to partial service degredation

Discussion
---
- It looks like the JS is loading but the React app is not showing anything. Is it in a loading state but there's no loading indicator (had we removed the loading indicator to remove the flash?)
- Could be related to the 1.7.2 change to put a RequireAuth gate. What is the error state if RequireAuth gate has an error state or takes a long time to load?
  - Probably not? The RequireAuth gate only covers the panel content: https://github.com/pixiebrix/pixiebrix-extension/blob/3b04a653c0cc0e7a2a04fee4f28794fa4fa34114/src/sidebar/ConnectedSidebar.tsx#L118-L118
- Is an error being thrown here?: https://github.com/pixiebrix/pixiebrix-extension/blob/3b04a653c0cc0e7a2a04fee4f28794fa4fa34114/src/auth/RequireAuth.tsx#L207-L207
- The customer sent us some of the effected users. Examples of errors, which may or may not be relevant:
  - https://rollbar.com/pixiebrix/pixiebrix/items/4887/occurrences/256493275128/: 
![image](https://user-images.githubusercontent.com/1879821/182983973-cb712fe7-edbe-4e4c-8e91-939142b56a76.png)
  - https://rollbar.com/pixiebrix/pixiebrix/items/4847/occurrences/256483957784/
![image](https://user-images.githubusercontent.com/1879821/182984033-f6a64e2d-8292-44d1-a9ff-119ea99157df.png)
   This is the error from from https://github.com/pixiebrix/pixiebrix-extension/issues/3833

Questions
---
- What code path could produce this render state?
- What would an error in the persister/store initialization look like? 

Screenshot
---
![image](https://user-images.githubusercontent.com/1879821/182982861-b056291d-d1df-498b-8d95-68793db66f20.png)

Related Code
---
- Sidebar HTML shows Loading PixieBrix text: https://github.com/pixiebrix/pixiebrix-extension/blob/3b04a653c0cc0e7a2a04fee4f28794fa4fa34114/src/sidebar/sidebar.html#L30-L30

**Comment by twschiller** [comment]
@fregante any ideas here? What in that proxy error would be a proxy reference? The sender tab?

**Comment by fregante** [comment]
I don’t think Rollbar is right for grouping the Proxy error together with this issue. 

Both webextension polyfills use the Proxy to wrap `chrome.*` APIs, so it *could* be them. But also RTK uses it, so I'm guessing that's it: https://stackoverflow.com/questions/64419055/redux-toolkit-cannot-perform-set-on-a-proxy-that-has-been-revoked

In the previous issue I mentioned that the only code paths I could think of triggering the Messenger error were during an extension reload. Having an empty/broken sidebar could also definitely cause the issue if it prevented its `registerMethods()` call.

**Comment by BALEHOK** [comment]
This is how the panel looks when `RequireAuth` throws an error:
```
  // RequireAuth.tsx L205
  const error = meError ?? tokenError ?? new Error("Testing auth error");
  if (error != null) {
    throw error;
  }
```

<img width="1355" alt="Screen Shot 2022-08-05 at 1 02 36 PM" src="https://user-images.githubusercontent.com/3116723/183064568-fdc7f5c1-6436-4ca4-8f60-3511c2bbe6df.png">

**Comment by twschiller** [comment]
> This is how the panel looks when RequireAuth throws an error

Thanks for investigating! So it does look like it could be caused by service degradation from our side (because there would be a meError with a 5XX)

I think the solution for 1.7.3 is to wrap the sidebar in an ErrorBoundary? You'll likely need to create a new one that looks better in the sidebar form
