### ISSUE TITLE
Upgrade content script polyfill

### ISSUE THREAD

**Issue by twschiller** [pixiebrix/pixiebrix-extension#398]
We had made some changes in `src/polyfills/registerPolyfill.ts`. Can those be upstreamed?

https://github.com/pixiebrix/pixiebrix-extension/pull/224

**Comment by fregante** [comment]
Related: https://github.com/fregante/webext-dynamic-content-scripts/issues/16#issuecomment-739259308 https://github.com/fregante/content-scripts-register-polyfill/issues/10

**Comment by twschiller** [comment]
@fregante I linked the other two dependabot PRs to this. Looks like we're good to move forward on this?

**Comment by fregante** [comment]
Yes I opened https://github.com/pixiebrix/pixiebrix-extension/pull/535 just last night.
