### ISSUE TITLE
Upgrade mini-css-extract-plugin

### ISSUE THREAD

**Issue by twschiller** [pixiebrix/pixiebrix-extension#399]
Build currently failing because they changed the options format?: https://github.com/pixiebrix/pixiebrix-extension/pull/370

**Comment by fregante** [comment]
Want me to push to push to these dependabot branches or should I open new PRs?

**Comment by twschiller** [comment]
@fregante No strong preference - whatever is easier for you. I double-checked the Dependabot description to verify it won't ever overwrite any changes we make to a PR
