### ISSUE TITLE
Pre-install Playground blueprint/open Playground on install for individual users

### ISSUE THREAD

**Issue by mnholtz** [pixiebrix/pixiebrix-extension#3996]
Currently, when an individual onboarding user installs the extension, the installer will open the extension options page or the admin console (which will open the typeform survey), depending on the state of their open tabs at the time.

As part of Onboarding Squad goals for this week, we would like to instead open the playground page with the playground blueprint pre-installed.

**Implementation sketch**
- [x] Pre-install Playground blueprint after extension installation
1. Create a separate file for background script called `onboardingBlueprints.ts` or `preinstallOnboardingBlueprints.ts` inside the `background/` directory
2. Create a function in this file called `preinstallPlaygroundBlueprint` that 
a. makes a network request to the `me` endpoint to verify if the user has a preinstalled blueprints flag set
b. If so, makes a network request to get the Playground recipe by (a hard-coded id?)
c. Installs the recipe via the `installRecipe` action on the `extensionsSlice`
d. Call this function in `background.ts`
- [x] Change `openInstallPage` behavior to open Playground url in a separate tab if the user is an individual user (not enterprise or partner)

**Additional back-end changes**
- Create a flag on the back-end separated from `is_onboarded` that tracks whether or not a user has preinstalled blueprints, captured here: https://github.com/pixiebrix/pixiebrix-app/issues/2126
- Nice to have/future work: create an endpoint that will return the blueprints/recipes to preinstall for use in the background script described above

**Comment by twschiller** [comment]
See here for the deployment installer that runs on the background page: https://github.com/pixiebrix/pixiebrix-extension/blob/e9622348796d349934200e27e3129c773bfcc8cc/src/background/deployment.ts#L175-L175

There’s helper methods for working with the settings state in the background page: https://github.com/pixiebrix/pixiebrix-extension/blob/e9622348796d349934200e27e3129c773bfcc8cc/src/background/deployment.ts#L276-L276

The main question to answer is:
* Do you want to install in React world, or
* Do you want to install in background page world

Here’s the deployment installer that runs in React world: https://github.com/pixiebrix/pixiebrix-extension/blob/e9622348796d349934200e27e3129c773bfcc8cc/src/hooks/useDeployments.ts#L101-L101

To automatically install a blueprint, you’ll likely want to use the same methods that we use for installing enterprise deployment (the `.installRecipe` method)

**Comment by BLoe** [comment]
>a. makes a network request to the me endpoint to verify that that the user is not flagged as is_onboarded
>b. If so, makes a network request to get the Playground recipe by (a hard-coded id?)

Could these be combined into one network request that simply returns the recipes that should be pre-installed for the current user? Can we configure which extensions should be installed for which users in a table on the back end?
