### ISSUE TITLE
Add support for infinite scroll in `menuItem` extension point

### ISSUE THREAD

**Issue by twschiller** [pixiebrix/pixiebrix-extension#400]
**Context**
- The menuItem extension point can render a menu multiple times if the container selector appears multiple times on the page
- However, it only renders on the initial navigation / appearance of the menu container. Therefore, it doesn't work for lists/tables that dynamically load rows

**Implementation sketch**
* For performance, expose an option on menuItem extension point foundation to support infinite scroll (default `false`): http://github.com/pixiebrix/pixiebrix-extension/blob/9398618e87a09a54e561b2002ba9acc0d20911d3/src/extensionPoints/menuItemExtension.ts#L113-L113
* After rendering the menu items, keep watching for new instances of the menu. http://github.com/pixiebrix/pixiebrix-extension/blob/9398618e87a09a54e561b2002ba9acc0d20911d3/src/extensionPoints/menuItemExtension.ts#L654-L654
* Add a field in on the foundation configuration page in the dev tools: http://github.com/pixiebrix/pixiebrix-extension/blob/9398618e87a09a54e561b2002ba9acc0d20911d3/src/devTools/editor/tabs/menuItem/FoundationTab.tsx#L106-L106

**Performance considerations**
* Is there a DOM event we can listen to know when the scroll has stopped to look if we need to attach new menu items?

**Comment by fregante** [comment]
> Is there a DOM event we can listen to know when the scroll has stopped to look if we need to attach new menu items?

As of 2023, yes. 

https://developer.chrome.com/blog/scrollend-a-new-javascript-event
