### ISSUE TITLE
Reduce memory footprint of sidebar

### ISSUE THREAD

**Issue by twschiller** [pixiebrix/pixiebrix-extension#4000]
Context
---
- The onboarding playground work is exposing some performance problems when many extensions are active

Things to Explore
---
- On 1.7.3-beta.1 build, the sidebar memory footprint is nearly 20mb of strings
![image](https://user-images.githubusercontent.com/1879821/184059342-4a7b7275-961e-4ffb-bf47-63bbad86508a.png)

Questions
---
- How to profile the content script? I originally wanted to profile the content script, but I profiled the sidebar because I was able to snapshot its heap

Screenshots
---
- Is FontAwesome all being loaded into memory as strings?
![image](https://user-images.githubusercontent.com/1879821/184059308-bab73bb9-edc4-4858-ab72-2005bf6ae553.png)

- Extension is loading all team members from organizations if you're an admin
![image](https://user-images.githubusercontent.com/1879821/184059892-290b9310-efd3-40e8-8624-ba896916d07e.png)

- Why is the getMarketplaceListings endpoint being called from the sidebar? Or is the profile showing the heap from elsewhere? It be coming from BrickIcon?
![image](https://user-images.githubusercontent.com/1879821/184060031-ae6d25ac-2176-4767-8450-6ec3156e5903.png)

- Why are we missing out on string interning? 
Note the duplicate strings:
![image](https://user-images.githubusercontent.com/1879821/184059647-8babf005-6f3b-49f5-a57d-26b3efe4ee5f.png)

**Comment by fregante** [comment]
> How to profile the content script?

Doesn't it show up as part of the same view as a regular page? 

> Is FontAwesome all being loaded into memory as strings?

Font Awesome is not treeshaken, so importing one icon leads to the whole library being loaded into memory. A solution to this (and to other icon issues) was suggested in https://github.com/pixiebrix/pixiebrix-extension/issues/2019

As always the best thing is to limit our usage of icon libraries because so far we have 4 separate libraries, mostly for the users, but we also import some directly. 

> Extension is loading all team members from organizations if you're an admin

> Why is the getMarketplaceListings endpoint being called from the sidebar? Or is the profile showing the heap from elsewhere? It be coming from BrickIcon?

They're not being called but they just exist in memory because of the monolithic structure of the bricks. Every context loads every brick whether they're used or not. 

> Why are we missing out on string interning?
> Note the duplicate strings:

Probably a microoptimization at this point.

**Comment by fregante** [comment]
<img width="109" alt="Screen Shot" src="https://user-images.githubusercontent.com/1402241/184072088-4dbae8cc-fdaf-4b93-9b1e-ff7bfe1e7791.png">

# 😌

**Comment by twschiller** [comment]
> Doesn't it show up as part of the same view as a regular page?

For the memory profiler, I only see the sidebar page. I thought each content script gets its own VM, so would have expected it to be in there

![image](https://user-images.githubusercontent.com/1879821/184267888-91893dc6-b1f6-4f3b-80e5-53a0f25e2795.png)

> As always the best thing is to limit our usage of icon libraries because so far we have 5+ separate libraries

Agree. I don't think it's driving the crashing problem we were seeing on the new playground blueprint. So will punt for a bit longer.

I think eventually we move the icon library out of the extension bundle and host on our server. The original intention was to not leak information about what icons the person is using. But we have that information on our server anyway since we host the blueprint/brick content

> Why is the getMarketplaceListings endpoint being called from the sidebar?

That particular API endpoint I don't think it in a call path from the sidebar. I also don't see network calls for it. So I'm a bit stumped on how content for it is seemingly making its way into the heap snapshot

> Probably a microoptimization at this point.

Agree. Chrome makes it hard to see how much of the string memory content is

**Comment by twschiller** [comment]
For 1.8.2 we made a series of improvements to improve memory utilization:
- Use `mountOnEnter` for Mod Launcher and Activation tabs to prevent unnecessarily fetching mod definitions
- Use `mountOnEnter` for sidebar panel mods
- Lazily load the code for the Mod Launcher and activation tabs

On my setup, the main memory utilization comes from fetch mod details for the mod launcher. That's because I have access to a lot of content, some of with which large images/wordlists in the content:
- [Loading all mod definitions from IDB into memory](https://github.com/pixiebrix/pixiebrix-extension/blob/25d3923415f8cc8d252f89dfc53a6b5553116eb0/src/mods/useModViewItems.tsx#L51-L51)
- [Fetching/Loading all marketplace data into memory](https://github.com/pixiebrix/pixiebrix-extension/blob/25d3923415f8cc8d252f89dfc53a6b5553116eb0/src/mods/useModViewItems.tsx#L50-L50)
