### ISSUE TITLE
Apply validation/error style to Page Editor

### ISSUE THREAD

**Issue by twschiller** [pixiebrix/pixiebrix-extension#4005]
Context
---
- Design sprint ticket: https://github.com/pixiebrix/pixiebrix-extension/issues/3905

Implementation Sketch
---
- Create AnnotationAlert component (naming?)
- Add to Storybook
- Add in annotation locations in Page Editor

**Comment by BALEHOK** [comment]
Using alert styles from this page https://www.figma.com/file/d46mjmu6xw3atpe5jvG5hN/%F0%9F%92%8E-Components?node-id=944%3A8632
