### ISSUE TITLE
Simplify format for dropdowns with labelled values in the Form Builder

### ISSUE THREAD

**Issue by twschiller** [pixiebrix/pixiebrix-extension#4051]
Context
---
- The Form Builder supports dropdowns with labelled values
- For dynamic data (e.g., returned via API), putting the data in the right structure requires convoluted JQ

**Comment by 4626433** [comment]
https://app.pixiebrix.com/activate?id=@pixies/slack/slack-sidebar uses a big jq brick for the channels as an example, could at least be a simpler operation
