### ISSUE TITLE
No handler registered for RUN_BRICK in contentScript in brick running in target tab

### ISSUE THREAD

**Issue by twschiller** [pixiebrix/pixiebrix-extension#4058]
Context
---
- Reported after updating to 1.7.4
- https://pixiebrixcommunity.slack.com/archives/C02TS1K83EX/p1660675907463989

Screenshot
---
![image](https://user-images.githubusercontent.com/1879821/184993094-2dbc8b01-2b5d-49e7-8efc-130239a714d4.png)

Steps to Reproduce
---
- Reproduced with 1.7.5-alpha.1
- Edit https://news.ycombinator.com/
- Create a trigger extension
   - Add a click trigger
   - Open tab https://news.ycombinator.com/
   - Show a modal form (window = target)

Discussion
---
- Potentially related: Enterprise customer is reporting "No handler for FORM_GET_DEFINITION in contentScript" errors when using form modal
  - Item: https://rollbar.com/pixiebrix/pixiebrix/items/5570/?item_page=0&item_count=100&#instances 
    ![image](https://user-images.githubusercontent.com/1879821/185002798-94121d13-de94-483d-a04d-8e804b689c18.png)

  - Example user: https://rollbar.com/pixiebrix/pixiebrix/items/5570/occurrences/258342185973/, https://rollbar.com/pixiebrix/pixiebrix/items/5570/occurrences/258342252124/. These happened at the same time today 4ish hours after we published 1.7.4. Potentially due to an expired contentScript on the tab?
  - Support Ticket: https://pixiebrix.zendesk.com/agent/tickets/144
  ![image](https://user-images.githubusercontent.com/1879821/184992144-701e10bc-9050-42c4-977b-6fb55e4d4f31.png)
- The registerMessenger happens in the async loaded contentScriptCore: https://github.com/pixiebrix/pixiebrix-extension/blob/ea04012a36114be24ab176a2d47137c0ccfaa581/src/contentScript/contentScriptCore.ts#L55-L55
  - The contentScript it receiving/handling message before it's marked as ready? Previously it was included as a top-level synchronous method call in the module: https://github.com/pixiebrix/pixiebrix-extension/pull/3915/files#diff-54bbfc76fd5dc5af42870164053dc17e3e051390709004b5b6b76e490e4832a7L51. @fregante, but it looks like the handlers must be registered to even hit that line of with the error? https://github.com/pixiebrix/webext-messenger/blob/main/source/receiver.ts#L107
 - The messenger receiver is handling the message before it registers its handlers
   ![image](https://user-images.githubusercontent.com/1879821/185012535-8676ad63-c0c6-430e-bfbf-2442885df4a0.png)

Related Issues/PRs
---
- https://github.com/pixiebrix/pixiebrix-extension/pull/3915

Related Code
---
- https://github.com/pixiebrix/webext-messenger/blob/b210e745b6fe382804e79fa1611af36284dcd739/source/receiver.ts#L73

**Comment by fregante** [comment]
Can repro, I can see that the message is received before the handlers are registered 🤔 

<img width="475" alt="Screen Shot" src="https://user-images.githubusercontent.com/1402241/185015020-d06c1990-fe8c-4442-8b6b-243904453c0c.png">


Working on it

**Comment by twschiller** [comment]
The problem is the following:
- The webext-messenger index module calls initPrivateApi, which calls registerMethods, which also adds the Chrome message listener https://github.com/pixiebrix/webext-messenger/blob/bb3b50f98aec62b39bb2a38eb9682c5b0e9303fb/source/index.ts. This is what registers the __getTabData in the screenshot
- The PR for the content script now calls registerMessenger within the async init method

There is a race with the following:
1. contentScriptCore module initialization
2. initPrivateApi -> registerMethods
3. Handle the message
3. registerMessenger

**Comment by fregante** [comment]
> * In webext-messenger, we might consider warning/erroring if no custom handlers have been registered prior to receiving a message (as that indicates a misconfiguration)

That already happens on the sender’s end, which is what the error in title says:

1. Message was received by webext-messenger
2. webext-messenger said no handler registered here

Adding another warning just shows the same error in 2 contexts.

> * Move the registerMessenger(),  registerExternalMessenger() calls to module-level in contentScriptCode

They're already there, I'm looking at why webext-messenger is being loaded outside it.

**Comment by fregante** [comment]
> > * Move the registerMessenger(),  registerExternalMessenger() calls to module-level in contentScriptCode
> 
> They're already there, I'm looking at why webext-messenger is being loaded outside it.

It's due to the error notification API (telemetry/reportError). Let me think if there's a way around this 🤔

**Comment by twschiller** [comment]
> That already happens on the sender’s end, which is what the error in title says:

I was referring to checking  here if _NO_ custom handlers have been registered yet: https://github.com/pixiebrix/webext-messenger/blob/main/source/receiver.ts#L72

> It's due to the error notification API (telemetry/reportError). Let me think if there's a way around this 🤔

Could you hop on Slack to discuss? We're missing each other on GitHub

> They're already there, I'm looking at why webext-messenger is being loaded outside it.

registerMessenger(), registerExternalMessenger() are within a method. Yes, that method is called from the module, but is not run when the module is loaded -- the VM can preempt it with other async calls.

https://github.com/pixiebrix/pixiebrix-extension/blob/ea04012a36114be24ab176a2d47137c0ccfaa581/src/contentScript/contentScriptCore.ts#L55-L55

**Comment by fregante** [comment]
> > That already happens on the sender’s end, which is what the error in title says:
> 
> I was referring to checking here if _NO_ custom handlers have been registered yet (i.e., __getTabData is the only handler registered): [pixiebrix/webext-messenger@`main`/source/receiver.ts#L72](https://github.com/pixiebrix/webext-messenger/blob/main/source/receiver.ts#L72)

Oh yes, instead of responding "no handler registered for RUN_BRICK" it should say "no handlers registered at all yet".

I opened an issue

**Comment by fregante** [comment]
So this issue happens because the messenger becomes a synchronous dependency of the main `contentScript.ts` file via:

1. onContextInvalidated
2. whose file imports `utils/notify`, even if unused
3. which imports `telemetry/reportError`
4. which imports the messenger
5. which calls `registerMethod({__getTabData})`
6. which causes the Messenger to stop retrying and responds with "no RUN_BRICK found" 

Solution:

- handle lack of registered methods as a retryable error, because it's essentially the same as "the content script hasn't loaded yet"
