### ISSUE TITLE
Simplify blueprint activation wizard

### ISSUE THREAD

**Issue by twschiller** [pixiebrix/pixiebrix-extension#4060]
Context
---
- The blueprint activation has at least two steps:
   - Choose extensions
   - View and accept permissions
- Additionally, some blueprints have 1-2 other steps
   - Configure options (if any options are exposed on the blueprint)
   - Configure integrations (if the blueprint uses any integrations)
- This involves a lot of clicking, and the "next" button moves with the height of the cart
- It presents a user with toggles, and in 99% of cases they shouldn't toggle anything off (see Discussion/History below)

Discussion/History
---
- We originally provided the ability to toggle which extensions to include because we were shipping blueprints with 3+ context menus, e.g., https://www.pixiebrix.com/marketplace/08e1c3ab-edca-4c9a-8815-fd22bede4cb3/amazon-search-context-menu/. In practice, blueprints now expect a user to install all the extension b/c they work together

Considerations
---
- We also have a wizard for re-activating a blueprint which shares some code. Recently we modified it's behavior to automatically default to having all extensions toggled (to handle the case where the blueprint author added an extension to the blueprint)
- In the current wizard, the integrations/permissions dynamically change based on which extensions the user has toggled on
- A user should be to be able to see the id of the blueprint because blueprints have similar names
- Permissions
  - PixieBrix may already have been granted the permissions required to run the extension
  - Some extensions (context menus), might not require additional permissions

Coordination
---
- [ ] Low fidelity mockups, @icugideon 
- [ ] High fidelity mockups, @icugideon 

Future Work
---
- In the future, we may allow a user to toggle extensions off from the more "..." menu on the installable on the blueprints screen
- On install, take the user to information about how to use/run the blueprint

**Comment by mnholtz** [comment]
Figma link: https://www.figma.com/file/6J6JbIhjw0YVKaTP2Id4aK/Extension-Console?node-id=240%3A4869

**Comment by mnholtz** [comment]
Closing in favor of follow-up issue: https://github.com/pixiebrix/pixiebrix-extension/issues/4318
