### ISSUE TITLE
Blueprints screen shows "Grant Permissions" button for starter blueprints

### ISSUE THREAD

**Issue by twschiller** [pixiebrix/pixiebrix-extension#4068]
Context
---
- PixieBrix is now set up to install start blueprints for unaffiliated users (new users who aren't in an organization)
- They work fine without additionally permissions because they act on https://web.pixiebrix.com/playground/playground and PixieBrix has permissions for `*.pixiebrix.com` in the manifest
- However, the blueprints screen is showing "Grant Permissions" buttons on the blueprints. This will be confusing to users because it shouldn't be required...

Related Code
---
- https://github.com/pixiebrix/pixiebrix-extension/blob/b035ea1f0b53e12560fd89421847ec3ba46ec45d/src/options/pages/blueprints/useInstallableViewItemActions.ts#L100-L100
- https://github.com/pixiebrix/pixiebrix-extension/blob/b035ea1f0b53e12560fd89421847ec3ba46ec45d/src/options/pages/blueprints/useInstallablePermissions.ts#L47-L47

**Comment by twschiller** [comment]
@fregante I think we just need to swap the call to https://github.com/pixiebrix/pixiebrix-extension/blob/b035ea1f0b53e12560fd89421847ec3ba46ec45d/src/background/messenger/api.ts#L29-L29 with a call to your https://github.com/fregante/webext-additional-permissions library?

**Comment by fregante** [comment]
I'm not sure that's right. `permissions.contain` includes manifest permissions so `contain('https://PixieBrix.com')` already correctly returns true (assuming that it matches the glob in the manifest). My module would return false in this case so it would prompt you to add a permission that already exists.

**Comment by twschiller** [comment]
> I'm not sure that's right

Hmm, that sounds right. We'll need to double-check what's going on a fresh install

**Comment by twschiller** [comment]
@mnholtz it's actually pretty simple. In addition to the pixiebrix URLs, the blueprints say they need access to the webflow.io domains (the staging site)

So they work on the PixieBrix site when deployed as starter blueprint, but PixieBrix does not have access to everyplace the blueprints are asking to run

The extensions team will have to update the blueprints

cc @MMirandi @orliesaurus

**Comment by twschiller** [comment]
Closing because the buttons are working as intended
