### ISSUE TITLE
Verify that recordEvent correctly handles concurrent events

### ISSUE THREAD

**Issue by twschiller** [pixiebrix/pixiebrix-extension#4073]
Context
---
- A recent PR changed recordEvent to store its buffer in local storage, which has an async API
- From reading the code, it looks like there could be possible for the code to drop events reported concurrently

Race Condition
---
- A calls recordEvent with `e_A`
- B calls recordEvent with `e_B`
- A calls readStorage -> reads `[]`
- B calls readStorage -> reads `[]`
- A calls setStorage with `[e_A]`
- B calls setStorage with `[e_B]`
- flush calls readStorage -> reads `[e_B]`

Related Code
---
- https://github.com/pixiebrix/pixiebrix-extension/blob/63cc9de6c551a867d9dac0f502261c94f13ed097/src/background/telemetry.ts#L154-L154

**Comment by mnholtz** [comment]
Quite confident that it does not 🥲 working on a fix, thanks for catching this
