### ISSUE TITLE
"PixieBrix could not run on page" error when opening sidebar

### ISSUE THREAD

**Issue by twschiller** [pixiebrix/pixiebrix-extension#4078]
Steps to reproduce
---
- Tested on 1.7.4-beta.3
- Video: https://www.loom.com/share/53868abef57a47e2a3cca79620602631
- Activate "LinkedIn organization demo bricks" brick from Pixies team
- Visit https://www.linkedin.com/company/tesla-motors/
- Toggle the sidebar

Expected Result
---
- Hacker News search results show in the sidebar panel

Actual Result
---
- Sidebar shows no panels
- After 2-3 seconds, PixieBrix opens up a new tab with "PixieBrix could not run on page" error

Related Conversations
---
- Also impacting playground sidebars for some @MMirandi : https://pixiebrix.slack.com/archives/C03RA8CFW8L/p1661008724190219

**Comment by fregante** [comment]
I was able to reproduce this **once** by reinstalling PB:

1. The sidebar’s own `__getTabData` call is being retried multiple times
2. This means that the content script’s PING_SIDEBAR call is temporarily ignored by the sidebar because it doesn't yet know its own `tabId`

Step 1 is kinda crazy because any `runtime` context should be able to respond to that call immediately and the background page is presumably ready to answer at all times, the message should not fail even if the background page is "processing".

I'll try to find out why this is happening.

**Comment by fregante** [comment]
## Reproducibility

The general issue somewhat reproducible because this is simply a timeout issue due to the lengthy insertion sequence:

1. Page load
2. Content script load
3. Sidebar load

This has to happen within 4s from the user click, as defined by the timeout in the browser action handler.

To reproduce it:

1. Refresh LinkedIn
2. Immediately click the browser action
3. With some luck, it will take long enough to fail

**Comment by fregante** [comment]
I might have found one of the many reasons the sidebar loads slowly: off-site fonts.

<img width="891" alt="Screen Shot 3" src="https://user-images.githubusercontent.com/1402241/185908159-1e05ff06-1b13-4bd0-8360-a738c5f52663.png">


Wow.

Look at the timestamps of the contentscript retries and error and then compare it to the first log by the sidebar. The JS was run 9 whole seconds _after the timeout_.

This is highly variable and depends on a third party, this is why it's hard to reproduce it.

I have a couple of PRs in the pipeline to sidebar address speed.

**Comment by twschiller** [comment]
> This is highly variable and depends on a third party, this is why it's hard to reproduce it.

Yes, and will also depend on 1) if the user is new (are the fonts in cache), and 2) if Chrome decides to go grab it anyway

**Comment by twschiller** [comment]
@fregante I cut a build with the following:

- https://github.com/pixiebrix/pixiebrix-extension/pull/4099
- https://github.com/pixiebrix/pixiebrix-extension/pull/4076
- https://github.com/pixiebrix/pixiebrix-extension/pull/4080
- https://github.com/pixiebrix/pixiebrix-extension/pull/4079

I'm still getting the original issue when I first activate the blueprint. After I reload the extension background page the problem goes away

![image](https://user-images.githubusercontent.com/1879821/186032622-9d335c29-a4cd-431a-bfe5-8b2f01948ef0.png)

**Comment by fregante** [comment]
In case of extreme font loading delays, the sidebar context would not receive any messages nor print any logs. It doesn't look like it's the case in the screenshot. 

Those warnings suggest that the sidebar context is receiving messages while the context is waiting for a __getTabData response (or rather, it failed).

Do you see what happens to that __getTabData? Is it being received by the background page? 

I've been thinking about other ways to get the current tabId but there's nothing, they only suggest a ping to the runtime.

Side note: we should probably add a "context invalidated" notification in the sidebar and options page so we catch any such issues.

**Comment by twschiller** [comment]
Moving to 1.7.X to keep an eye on this, as the main regression/bug has been addressed

**Comment by twschiller** [comment]
Bringing back to 1.7.5. Is still a significant issue. Reloading the background page solves the problem, so appears to be a problem with the background messenger getting into a bad state

**Comment by fregante** [comment]
If it happens, could you post the full logs of the sidebar and background? 

The only state we have I think is the "target name" and only in the requester. The background always knows its name without race conditions. 

I'll try to replicate this again today. I haven't seen it since

**Comment by fregante** [comment]
_Personal notes:_

----

I can replicate it by reinstalling the extension, like:

1. Install
2. Open blueprints
3. Activate "LinkedIn organization demo bricks"
4. Visit https://www.linkedin.com/company/tesla-motors/ in a new tab
5. Toggle sidebar

`__getTabData` is being retried:

<img width="670" alt="Screen Shot 14" src="https://user-images.githubusercontent.com/1402241/186623204-1ebc5287-dbc8-4a0d-9d99-7ae8e096f347.png">

but the background page is successfully responding to every message, so I need to find out why it's not being handled:

<img width="752" alt="Screen Shot 15" src="https://user-images.githubusercontent.com/1402241/186623158-672b2bc1-aaa4-4676-8917-cd67defd50d1.png">

The options page also receives the message but does not handle it at all for some reason,  perhaps it did not register the handler on the very first load? It does on successive loads.
