### ISSUE TITLE
Google Fonts may occasionally cause fatally slow loading

### ISSUE THREAD

**Issue by fregante** [pixiebrix/pixiebrix-extension#4100]
Javascript files are not run until every stylesheet is ready. Since Google Fonts is loaded via a regular `link` tag, it may occasionally (and inexplicably) lead to a broken load.

<img width="891" alt="Screen Shot 3" src="https://user-images.githubusercontent.com/1402241/185908159-1e05ff06-1b13-4bd0-8360-a738c5f52663.png">

## Solutions

- Load the stylesheet asynchronously
- Include the font styles in the bundle
- Drop custom font

The first one is easy, the second or third one  is eventually required due to MV3 restrictions.

## Related

- https://github.com/pixiebrix/pixiebrix-extension/issues/4078#issuecomment-1222207690
- https://github.com/pixiebrix/pixiebrix-extension/issues/287

**Comment by twschiller** [comment]
> The first one is easy, the second or third one is eventually required due to MV3 restrictions.

Are you sure remote CSS/fonts are banned in MV3? I hadn't heard that before

**Comment by fregante** [comment]
https://groups.google.com/a/chromium.org/g/chromium-extensions/c/29A7eSx5Rb0

I remember seeing an error and if you look at my last MV3 test's screenshot it lacks the custom fonts. It's possible that it just needs a CSP adjustment, but it sounds like an unnecessary policy adjustment if it only requires some config to restore it.

**Comment by fregante** [comment]
Indeed it works in Chrome 104. What I might have seen before was a CSP error due to an updated default.

### manifest.json

```json
{
  "manifest_version": 3,
  "author": "@fregante",
  "name": "MV3 test",
  "version": "0.0.0",
  "background": {
    "service_worker": "background.worker.js"
  },
  "options_ui": {
    "page": "options.html",
    "open_in_tab": true
  }
}
```

### options.html

```html
<!DOCTYPE html>
<meta charset="UTF-8">
<title>Document</title>
<style>
	@import url("https://fonts.googleapis.com/css?family=Ubuntu:300,400,500,700&display=swap");
	h1 {
		color: red;
		font-family: Ubuntu;
	}
</style>
<h1>Ubuntu?</h1>
```
```

**Comment by twschiller** [comment]
For reference, our CSP is:
- `style-src 'self' 'unsafe-inline' https://fonts.googleapis.com;`
- `font-src 'self' https://fonts.gstatic.com`

**Comment by fungairino** [comment]
Made another change related to this since the original fix still made a network blocking request causing some additional latency in rendering the html.
https://github.com/pixiebrix/pixiebrix-extension/pull/8270
