### ISSUE TITLE
Add element dropdown gets cuts off inside list element preview in Document Builder

### ISSUE THREAD

**Issue by twschiller** [pixiebrix/pixiebrix-extension#4102]
Context
---
https://pixiebrix.slack.com/archives/C02CN01JXAA/p1661205819787039?thread_ts=1661204482.661599&cid=C02CN01JXAA

Screenshots
---
![image](https://user-images.githubusercontent.com/1879821/186027241-29fb1356-d8af-4415-a9f6-5a2f7dbf62a7.png)

**Comment by BALEHOK** [comment]
Related issue #3894
