### ISSUE TITLE
Add support for preventing multiple clicks on button extensions

### ISSUE THREAD

**Issue by twschiller** [pixiebrix/pixiebrix-extension#4105]
Context
---
- As a creator, I want to create a button that can't be clicked again while the action is in progress. For example, because the button does an API call before showing a user-visible effect
- Users will often click on button multiple times if they don't see it taking effect

Implementation Sketch
---
- Add a `synchronous` configuration to the menuItem extension point option that defaults to false (on the extension point, not the extension): https://github.com/pixiebrix/pixiebrix-extension/blob/9da19ad2af00cdc00eb678025d93aec2ffbfcc08/src/extensionPoints/menuItemExtension.ts#L788-L788
- In the click handler, check if the action is already running: https://github.com/pixiebrix/pixiebrix-extension/blob/9da19ad2af00cdc00eb678025d93aec2ffbfcc08/src/extensionPoints/menuItemExtension.ts#L546-L546
- Add the field to advanced section of the MenuItemConfiguration: https://github.com/pixiebrix/pixiebrix-extension/blob/9da19ad2af00cdc00eb678025d93aec2ffbfcc08/src/pageEditor/tabs/menuItem/MenuItemConfiguration.tsx#L88-L88

Questions
---
- For new buttons created with the Page Editor, do we want the default to be synchronous or asynchronous

Considerations
---
- For backward compatibility, existing buttons should have their existing behavior
- The menu item extension point can create multiple buttons on the page. The logic should only impact the button the user clicked

Future Work (out of scope)
---
- Add support for a disable/in-progress state

**Comment by jcforest** [comment]
@twschiller Could you let me know how to create multiple buttons with menuItem ExtensionPoint? 
I'm referring this text:

```The menu item extension point can create multiple buttons on the page. The logic should only impact the button the user clicked```

**Comment by twschiller** [comment]
Hi @jcforest, see Loom here: https://www.loom.com/share/dd717472cd26463f9510cfeb68103117
