### ISSUE TITLE
Page editor can sometimes enter a state where traces no longer work until the tab is reloaded

### ISSUE THREAD

**Issue by BLoe** [pixiebrix/pixiebrix-extension#4113]
* Ben has seen this happen, albeit very infrequently, only a handful of times total
* Orlando reported the issue in Slack as well (8/24 in #extension-development)

Can we figure out how to reliably reproduce the issue?

**Comment by orliesaurus** [comment]
It happens to me a lot actually. It mostly happens when I am editing an extension part of the blueprint and as I flip between a few extensions (regardless whether they're part of the same blueprint or not) suddenly it stops giving me this state feedback (aka the green tickmarks).

**Comment by BLoe** [comment]
Thanks for the further details! That's helpful.
