### ISSUE TITLE
If the sidebar is closed before it responds as "ready", it will report errors

### ISSUE THREAD

**Issue by fregante** [pixiebrix/pixiebrix-extension#4125]
## Reproduce

1. Double-click browser action

## Current behavior

Messaging continues until it times out, potentially surfacing confusing errors like `No handler registered for PING_SIDEBAR in the receiving end` to the user.

## Expected behavior

All messaging should stop and any current action should be stopped with a "User cancelled action" message/error.

## Related

- https://github.com/pixiebrix/pixiebrix-extension/pull/4079
- https://github.com/pixiebrix/pixiebrix-extension/issues/4021
- https://github.com/pixiebrix/webext-messenger/issues/78
- #4124

**Comment by twschiller** [comment]
@fregante I don't think there's any reason to support double-click scenario. And the user intent is likely that they want to open/toggle the extension. I think I would debounce the browser action with a `leading: true`. Thought?

cc @corinnemayans

**Comment by fregante** [comment]
> I don't think there's any reason to support double-click scenario

That's just the repro for debugging purposes, it's not the common way. Plus plenty of people double click elements that aren't supposed to double-click. 


The common situation is when someone clicks again before the sidebar is ready, which was seen last week as the sidebar was slow or unresponsive: people click again because nothing happened the first time. 

> the user intent is likely that they want to open/toggle the extension

Indeed there's a cutoff in expected behavior between "I expect the sidebar to open" and "I want to close the sidebar". Quick clicks mean that the sidebar should open. 

This issue could happen when the sidebar is toggled programmatically, so a specific "close" command must be followed *and* it will cause the error in object.

**Comment by fregante** [comment]
Downgrading to `low priority` as these two PRs made it rather difficult to have such issues:


- https://github.com/pixiebrix/pixiebrix-extension/pull/4192 
- #4099 

The only scenario where this could still _rarely_ happen:

- bricks and the user toggling the sidebar at the same time

## What's next

- [ ] Use `AbortController` to cancel any in-flight `_toggleSidebar` calls and `rehydrateSidebar` messaging
