### ISSUE TITLE
Nudge user to provide unique name for extension on save

### ISSUE THREAD

**Issue by twschiller** [pixiebrix/pixiebrix-extension#4141]
Context
---
- Some users end up with identically named bricks when learning PixieBrix
- PixieBrix does not enforce name uniqueness
- The page editor generate basic names based on the current page, e.g., "My github.com button"
- User extensions (not associated with a blueprint) have a non-human-readable uuid (it's a uuid v4)

Implementation Sketch
---
- On Save in the Page Editor, if the this is the initial save
- Check to see if the name is already in use by a user extension
- If it is, suggest to the user to provide a different name for the extension because the name is already in use

Discuss
---
- We may always want to nudge the use to give a meaningful name to the extension on initial save, even if the name is not already in use

Related Issues
---
- For blueprints, we're solving the problem by surfacing the registry id: https://github.com/pixiebrix/pixiebrix-extension/issues/3954

**Comment by corinnemayans** [comment]
I'd like to revisit "Save" and "Share" more generally. We will spec that out first, so I'm taking this one for now.
