### ISSUE TITLE
Modify Sidebar empty/onboarding state to include Page Editor instructions

### ISSUE THREAD

**Issue by mnholtz** [pixiebrix/pixiebrix-extension#4178]
As part of our Onboarding Squad sprint 3, we will be modifying the Sidebar empty state to encourage users to open the page editor.

**Figma assets**
https://www.figma.com/file/iK3zlhXpXqjPCX8jgriynh/SideBar?node-id=2%3A21

![image](https://user-images.githubusercontent.com/36575242/187971651-eb95b9db-2f70-48c4-9d8c-311f3b8dfc29.png)

![image](https://user-images.githubusercontent.com/36575242/187971744-1fdf6e4c-a330-4f27-881e-7659ec274cba.png)

**Echoing Specifications outlined below**
- For the Sidebar state where no extensions are installed, add information to the Sidebar about opening the Page Editor
- This will also involve detecting the OS to suggest the keyboard shortcut

**Comment by twschiller** [comment]
Additional consideration: "restricted" and "member" teams users should not be directed to open the Page Editor

**Comment by corinnemayans** [comment]
I aligned with Todd on splitting out #4186 for the case of restricted and member teams. This solution will focus on non-restricted users.

(From Todd) Current behavior is:
- If user is not logged in, we show them a button to connect to PixieBrix
- If they have no extensions installed, we show them the “Activate a pre-made blueprint from the Public Marketplace.” and “Follow the Quick Start Guide to start creating your own bricks in minutes.” actions
- If they have extensions, but no side panels for the page we show “No panels activated for the page”

This issue focuses on the second bullet above where no extensions are installed and the user opens the Sidebar on a valid page (the case where they try to open it on the Chrome Web Store or Options page is Issue #4180 and #4179 .

As a starting point, we'll add information to the Sidebar stating how to open the PixieBrix page editor.

The Lighthouse chrome extension has the same issue that we do with needing to get people into dev tools, and they call it out. We want to do something like this:

<img width="1140" alt="lighthouse" src="https://user-images.githubusercontent.com/111797779/187542774-78954c9a-74b0-47bb-83f7-c8a8623aecb7.png">

@icugideon -- Passing to you to do a quick mock-up.
