### ISSUE TITLE
Lazy load Nunjucks in Page Editor bundle

### ISSUE THREAD

**Issue by twschiller** [pixiebrix/pixiebrix-extension#4198]
Context
---
- This PR reintroduced synchronous dependency on Nunjucks in the Page Editor: https://github.com/pixiebrix/pixiebrix-extension/pull/4118/files/9fff756ac064641e5681c5f393f98bafbaf493d3..3e1a7b0b068359707744d2247ef497f5b941aed5#r959219709
- Not a major deal since Nunjucks is now used for all text fields in the Page Editor. Only benefit would be slightly improving initial Page Editor render

**Comment by fregante** [comment]
Closing in favor of https://github.com/pixiebrix/pixiebrix-extension/issues/4730
