### ISSUE TITLE
Drop `Router` if it's not used

### ISSUE THREAD

**Issue by BALEHOK** [pixiebrix/pixiebrix-extension#4200]

**Comment by twschiller** [comment]
@BALEHOK IIRC, Router is required because RequireAuth now uses it. In RequireAuth I added some logic to always allow the `"/settings/`" page of the extension to be visible

**Comment by fregante** [comment]
Is this about dropping an unnecessary dependency? Or just in this instance?

**Comment by BALEHOK** [comment]
> Is this about dropping an unnecessary dependency? Or just in this instance?

@fregante eventually it is about removing Router from the app **and** dropping the dependency from Page Editor :)
