### ISSUE TITLE
Refactor Page Editor Sidebar

### ISSUE THREAD

**Issue by BALEHOK** [pixiebrix/pixiebrix-extension#4207]
The Sidebar destroys and re-creates its items on every render. This causes an infinite state update loop if Redux state is changed by an item and also is the reason of flickering of the Extension icons.

**Comment by fregante** [comment]
Good to see this ticket! 💯 

> flickering of the Extension icons

As a general issue, this is something I can look into as part of:

-  https://github.com/pixiebrix/pixiebrix-extension/issues/4187

[#deathtoflickering](https://github.com/pixiebrix/pixiebrix-extension/issues?q=+author%3Afregante+flashes+OR+flicker) 😁
