### ISSUE TITLE
Merge webpack configs

### ISSUE THREAD

**Issue by fregante** [pixiebrix/pixiebrix-extension#422]
Follows #113 #421 and specifically https://github.com/pixiebrix/pixiebrix-extension/issues/113#issuecomment-853566849

There are currently 8 partially-overlapping webpack configuration files. I can merged these into 2:

- browser builds (dev/prod + firefox/chrome)
- scripts (which I haven't completely figured out what it's for yet)

This will let me also drop some dependencies #411 and start to look into what can be done to speed up the compilation.

**Comment by twschiller** [comment]
We need to fix https://github.com/pixiebrix/pixiebrix-extension/issues/451 before we can continue with this
