### ISSUE TITLE
Playground bug: "Error rendering panel: Registry item does not exist: notes/simple"

### ISSUE THREAD

**Issue by corinnemayans** [pixiebrix/pixiebrix-extension#4220]
I created a new account to test out the playground. I ran into this error on the Sidebar playground blueprint. I think this was pretty much just the happy path through, though I remember running into an issue where my browser hung while I was making a screen capture and I might have ended up going backwards and visiting the blueprint over again (in case that info helps with diagnosis).

![image](https://user-images.githubusercontent.com/111797779/188227880-3b58fb4d-259d-4c21-878e-365ba503344a.png)

Slack thread about this:
[](https://pixiebrix.slack.com/archives/C02CN01JXAA/p1662144612200389)

**Comment by twschiller** [comment]
Additional conversation: https://pixiebrix.slack.com/archives/C0436P48QHY/p1664488728556519
