### ISSUE TITLE
UI spacing bug in activation wizard 

### ISSUE THREAD

**Issue by corinnemayans** [pixiebrix/pixiebrix-extension#4241]
The app has text-justify set in some places, and suspect that it is causing alignment problems here.

See screenshots and details here:  https://pixiebrix.slack.com/archives/C03CA2M4RCM/p1662130582284679

@orliesaurus

**Comment by fregante** [comment]
It's best to include/copy-paste more context/screenshot in the issue because not all Slack channels are accessible to everyone

**Comment by corinnemayans** [comment]
![image](https://user-images.githubusercontent.com/111797779/188367556-c108accc-e6bc-4cb4-b74e-73771973422e.png)

<img width="297" alt="image" src="https://user-images.githubusercontent.com/111797779/188367646-2db27353-bfca-4dd1-9d4e-4ac36ccbcf88.png">
