### ISSUE TITLE
Take down Typeform survey during onboarding

### ISSUE THREAD

**Issue by corinnemayans** [pixiebrix/pixiebrix-extension#4243]
Currently after fresh PixieBrix extension install, two new tabs open - one with a Typeform survey, and one with the Playground. This is a bit disorienting. The onboarding squad said that the playground questions were intended to replace the Typeform. So, this issue is to revisit to make sure we're capturing what we need to know about new customers in the blueprints, and if so, stop launching the Typeform.

CC @MMirandi

**Comment by corinnemayans** [comment]
Decision: We don't currently use anything from the Typeform except for the question that is being asked in the playground blueprint, so we can stop showing the Typeform for now. Later we might weave in some of those questions in order to direct customers appropriately, but that's something for the future, not today.

Slack thread for reference:
[ ](https://pixiebrix.slack.com/archives/C03RA8CFW8L/p1661954769914729)

**Comment by twschiller** [comment]
@mnholtz isn't this in the app project, not the extension?

**Comment by mnholtz** [comment]
Closing this because it was already implemented in https://github.com/pixiebrix/pixiebrix-app/pull/2249

**Comment by corinnemayans** [comment]
@twschiller - I stuck it under the extension because I was trying to get everything under a common milestone based on timing, but that was a bad idea. :) We'll add milestones on the app project instead.
