### ISSUE TITLE
Selecting `API version: v1` in the page editor, breaks the UI

### ISSUE THREAD

**Issue by fregante** [pixiebrix/pixiebrix-extension#4244]
Not technically a bug, but if I mistakenly select a value, I can no longer go back because the UI disappears:

![text2](https://user-images.githubusercontent.com/1402241/188370368-45b944bb-4f89-42dc-b78e-9a980a1ef331.gif)

**Comment by twschiller** [comment]
> Not technically a bug, but if I mistakenly select a value, I can no longer go back because the UI disappears:

Triaging as low priority. That dropdown is only available to developers with the developer feature flag
