### ISSUE TITLE
Reducing the amount of errors reported to Rollbar

### ISSUE THREAD

**Issue by fregante** [pixiebrix/pixiebrix-extension#4256]
I'm opening this placeholder issue to keep track of possible improvements:

> we’re seeing a large number of errors in the extension since the start of the month (see https://rollbar.com/pixiebrix/all/items/?sort=%5Bobject%20Object%5D&status=all&date_from=&date_to=&environments=production&activated_to=&framework=&levels=40&levels=50&activated_from=&offset=0&timezone=Europe%2FLisbon&assigned_user=&date_filtering=seen&projects=395009&query=&enc_query=). We’re already at 70% of our monthly Rollbar quota. Two concerns:
> - Are there bugs that need to be fixed?
> - This is going to spike our Rollbar bill. Once we hit the limit, we pay https://docs.rollbar.com/docs/billing#on-demand-events--upgrades-for-monthly-plans, which means we pay a fixed price per 1k events over the limit.
> Can someone take a quick look at some of the errors? 

cc @johnnymetz

**Comment by johnnymetz** [comment]
Quick update on this. Our rollbar usage in the extension project is still very high (more than 4 times our old usage). See our usage stats [here](https://rollbar.com/settings/accounts/pixiebrix/usage/). At the end of the month, we'll see how much penalty we need to pay to account for the occurrences past our limit.

We can upgrade to beefier plan but the price difference would be pretty large. We're currently spending $459 / month. Upgrading to our current usage would be about $3-5k.

**Comment by BLoe** [comment]
@grahamlangford @johnnymetz I think this issue can be closed?

**Comment by johnnymetz** [comment]
I think so. We originally created this ticket because our Rollbar usage was well above our allotted monthly threshold. Looking at Rollbar now, looks like we're now below that threshold.
