### ISSUE TITLE
The hash should not be part of the match

### ISSUE THREAD

**Issue by fregante** [pixiebrix/pixiebrix-extension#427]
Not a bug per se, but I think it can cause confusion:

1. Visit https://en.wikipedia.org/wiki/Information#Etymology
2. Add a button in the dev tools
3. Visit "Availability" tab
4. See `https://en.wikipedia.org/*#Etymology` as a pattern
5. Visit "Information theory" section on the page
6. The pattern no longer matches and the button disappears (at some point)

<img width="983" alt="Screen Shot 9" src="https://user-images.githubusercontent.com/1402241/120780769-9f90f700-c552-11eb-9bc6-4f9e7970cc3a.png">

**Comment by twschiller** [comment]
See defaultMatchPattern here: https://github.com/pixiebrix/pixiebrix-extension/blob/ead1833564fff81288a195503b2dea57d3b55d2e/src/devTools/editor/extensionPoints/base.ts#L52
