### ISSUE TITLE
Move `useInstallState()` functionality to redux

### ISSUE THREAD

**Issue by BLoe** [pixiebrix/pixiebrix-extension#4276]
The `useInstallState()` hook can be migrated to use redux instead. This follows on from #4203. After those changes, we can now dispatch thunk actions from the "connect" thunk that will do the availability checking for extensions/elements in separate thunks.

**Comment by corinnemayans** [comment]
Further context where this showed up as a confusing UX:
https://pixiebrix.slack.com/archives/C0436P48QHY/p1665086143956589
