### ISSUE TITLE
Uncaught Error: PixieBrix contentScript already installed

### ISSUE THREAD

**Issue by fregante** [pixiebrix/pixiebrix-extension#428]
Are you seeing this issue? I'm seeing one error in my Webpack 5 branch and 2 errors on `main`, whether it's the prod or dev build.

Possibly related to https://github.com/pixiebrix/pixiebrix-extension/issues/398

```
VM422 contentScript.js:236942 Uncaught Error: PixieBrix contentScript already installed
    at Module.<anonymous> (VM414 contentScript.js:236942)
    at Module../src/contentScript.ts (VM414 contentScript.js:237016)
    at __webpack_require__ (VM414 contentScript.js:1440)
    at VM414 contentScript.js:1618
    at VM414 contentScript.js:1621
```

Screenshot taken with:

1. `main` branch
2. `npm run watch:chrome`
3. Load extension manually from scratch
4. Link account
5. Open static HTML site
6. Grant permission in dev tools
7. Reload page

<img width="716" alt="Screen Shot 11" src="https://user-images.githubusercontent.com/1402241/120854040-c5e08200-c5a6-11eb-9485-c559079ed0c9.png">

**Comment by twschiller** [comment]
Yep, I get the error almost always while using the dev tools. The error itself doesn't hurt anything - it's just a backstop against loading the contentScript multiple times. 

An alternative might be split the content script entry point, and do an async import of the main functionality it hasn't already been loaded. I'm not sure what the performance implication would be

There's a couple places (including dev tools) where we inject the content script if it hasn't already been injected

* https://github.com/pixiebrix/pixiebrix-extension/blob/main/src/devtools.ts#L105
* https://github.com/pixiebrix/pixiebrix-extension/blob/a4fed8f8d17e12874ffded937bed6aafc8086257/src/background/util.ts#L75

I suspect there's a race condition where it thinks the dev tools doesn't see the content script as having already been loaded

Thoughts?

**Comment by fregante** [comment]
I'm also seeing this tangentially-related error occasionally on Google.com with the PB dev tools open. 

<img width="663" alt="Screen Shot 8" src="https://user-images.githubusercontent.com/1402241/122674228-5bfae600-d1fe-11eb-8f79-4db9b1dae92d.png">

**Comment by twschiller** [comment]
> I'm also seeing this tangentially-related error occasionally

That might somehow be related to this? https://github.com/w3c/webextensions/issues/8. I haven't seen that warning before -- probably be a race condition on when various browser navigation events are happening?

I think `testTabPermissions` error/warning would have the opposite effect of preventing the background page from attempting to inject the script on behalf of the dev tools
