### ISSUE TITLE
When a brick with sub-pipelines is copied and then pasted, it's sub-pipeline bricks are not given new instance IDs

### ISSUE THREAD

**Issue by BLoe** [pixiebrix/pixiebrix-extension#4287]
This causes changes to one brick to apply to it's twin brick in the other pipeline, and other weird behavior.

**Comment by corinnemayans** [comment]
Mitigated by recreating instead of copy and paste
or copy and paste individual sub pipeline bricks
Moving to 1.7.9 since there are mitigations
