### ISSUE TITLE
PLACEHOLDER: Spec for variable usage assistance

### ISSUE THREAD

**Issue by corinnemayans** [pixiebrix/pixiebrix-extension#4292]
Give variable usage assistance in the Page Editor to help users avoid syntax issues (common problem for even power users)
This is a placeholder to work on the specification. This can be closed when we are aligned on the specification and have opened issues for each of the slices of work.

Spec to be done by @BLoe or @BALEHOK 
cc @twschiller

**Comment by corinnemayans** [comment]
Consider something like a variable picker to start
Need to create vertical slices and align on priorities, when to hide under feature flag versus when to release, etc.

**Comment by twschiller** [comment]
Spec is in Notion at (and implementation underway): https://www.notion.so/pixiebrix/Autocomplete-Autosuggest-Expressions-270c903d6bf043848fd1a3dcd4cffe45
