### ISSUE TITLE
Add BlueprintsPage tests

### ISSUE THREAD

**Issue by mnholtz** [pixiebrix/pixiebrix-extension#4316]
Follow-up of https://github.com/pixiebrix/pixiebrix-extension/pull/4294

When attempting to add tests for the Blueprints page, we noticed that simply rendering the component is producing an infinite render loop. We haven't been able to reproduce when running the application itself. We learned that it's the `setGlobalFilter` call in the `ListFilters` component that's causing the parent to rerender. 

See the `feature/add_blueprints_page_tests` branch for where we left off.

**Nice to have**
Add tests that test loading flickering states on the blueprints page. One example of this is the loading state for the "Get Started" onboarding tab for new users.

**Comment by BLoe** [comment]
@grahamlangford @mnholtz @twschiller Is this ticket still relevant given that we've added [`BlueprintPageLayout.test`](https://github.com/pixiebrix/pixiebrix-extension/blob/main/src/extensionConsole/pages/blueprints/BlueprintsPageLayout.test.tsx)?

**Comment by twschiller** [comment]
Not applicable. I'd err on the side of dropping old issues that haven't received any engagement (within past 3-6 months)
