### ISSUE TITLE
Chrome Web Store network error during extension download from Argentina

### ISSUE THREAD

**Issue by twschiller** [pixiebrix/pixiebrix-extension#432]
User from Argentina reports a network error during install from Chrome Web Store. It stops after 2-3 seconds and 30% downloaded

Likely a network error, as we've seen extension install OK on slow internet connections in Asia (taking 20+ seconds to download)

**Comment by fregante** [comment]
Is this still happening now that zips are only 7.16mb?

**Comment by twschiller** [comment]
I haven't hear it reported recently. I'll close for now
