### ISSUE TITLE
Removing a blueprint with a button in the Page Editor doesn't remove the button from the page until reload

### ISSUE THREAD

**Issue by twschiller** [pixiebrix/pixiebrix-extension#4321]
Context
---
- Tested on 1.7.8-alpha.2
- https://www.notion.so/pixiebrix/Release-1-7-8-b7f807b77bcc4b7f85d40f0084a1c89c

Steps to Reproduce
---
- Create a button extension
- Save as blueprint
- Open a new page and open the extension in the page editor
- Remove the blueprint

Expected Behavior: button is immediately removed
Actual Behavior: user has to reload the page to remove the button

**Comment by fregante** [comment]
Likely related:

- https://github.com/pixiebrix/pixiebrix-extension/issues/1557

**Comment by fregante** [comment]
This appears to have been fixed:

https://github.com/pixiebrix/pixiebrix-extension/assets/1402241/f44a9dcf-83f3-4add-be43-fae328d957d2
