### ISSUE TITLE
Long brick annotations occlude Add Brick action

### ISSUE THREAD

**Issue by twschiller** [pixiebrix/pixiebrix-extension#4323]
Context
---
- Tested on 1.7.8-alpha.2

Screenshot
---
![image](https://user-images.githubusercontent.com/1879821/191279252-98a4e9a2-646c-40f4-907e-060fe6207c97.png)

**Comment by corinnemayans** [comment]
Design team can provide preferred visual
@icugideon

**Comment by icugideon** [comment]
### Here is a design fix for this - 
A clean-up on the annotation (Tag) item to show "Not supported" and then serve more context using a tooltip, triggered via a text link hover.

![image](https://user-images.githubusercontent.com/23545614/198338366-257df10b-d3b4-444b-a49e-856f31db3854.png)

**Comment by fregante** [comment]
To anyone picking this: can we also place these items at the bottom of the list? They otherwise lengthen the list providing little value. Also we should hide the "Add button" if they really are not supported.

**Comment by twschiller** [comment]
>  can we also place these items at the bottom of the list?

History on the decision to include them. Folks were getting confused why they couldn't find a particular brick (and contacting support). If we move them to the bottom of the results, then we might have that issue again

Other options we talked about were having a toggle/filter to show unavailable bricks that match, etc.

In any case, there are tradeoffs so will want to usertest a bit
