### ISSUE TITLE
Reordering elements does not trigger the ability to save

### ISSUE THREAD

**Issue by twschiller** [pixiebrix/pixiebrix-extension#4325]
Context
---
- @mthek10 is in contact with the customer
- https://pixiebrix.zendesk.com/agent/tickets/172

**Comment by BLoe** [comment]
Related to this ticket I think: https://github.com/pixiebrix/pixiebrix-extension/issues/3948

@mthek10 I think this was fixed, can you validate and re-open the issue if it's still a problem?
