### ISSUE TITLE
Extension Action menu causes scroll 

### ISSUE THREAD

**Issue by twschiller** [pixiebrix/pixiebrix-extension#4331]
Context
---
- Found on 1.7.8-beta.2
- Workarounds: the user can scroll to click the desired action 

Discussion
---
- Likely either a z-index or container issue? Shouldn't it be getting rendered above the sidebar instead of within it?

Screenshots
---
![image](https://user-images.githubusercontent.com/1879821/191392215-1123a5e5-5cd5-4dd2-bc70-804352187252.png)

![image](https://user-images.githubusercontent.com/1879821/191392290-458548a7-2951-4866-9c4b-b13da505591d.png)

**Comment by fregante** [comment]
Scrollbars effectively trigger "overflow hidden", you can't normally have both scrollable content *and* content outside the scroll area.

There are a couple of ways to work around this:

- have the drop-down *outside* the element with overflow:scroll
- don't use position:relative inside the element with overflow:scroll: https://css-tricks.com/popping-hidden-overflow/

The first one require a rework of the drop-down, while the second one is tricky to position and easy to lose (should we accidentally add a position:relative inside again).

If there's an off-the-shelves accessible solution for this, I'd use it, like Adobe's components (I'm not sure they work around the issue, but there's a good chance they do)

**Comment by fregante** [comment]
Ad a quick solution, opening the menu to the left instead of on the right would be good enough though.

**Comment by fregante** [comment]
I can't reproduce it on `main`, it already opens to the left:

<img width="478" alt="Screen Shot 2" src="https://user-images.githubusercontent.com/1402241/191436127-28ddd2f0-5106-4bf3-b1c5-4605afe2f18f.png">

**Comment by twschiller** [comment]
Here's what I'm seeing on 1.7.8-beta.3, which should be equivalent to main for this bug: https://www.loom.com/share/7e2d7c1ffb9a429aaab7e65399370535

**Comment by BLoe** [comment]
>Here's what I'm seeing 

Looks like it's happening just for extensions inside blueprints?

**Comment by BLoe** [comment]
Ugh this seems to be caused by the OS level setting to "Always" show scrollbars. For some reason the bootstrap menu isn't placing correctly when you use that scrollbar setting.

**Comment by fregante** [comment]
I think I know then. The placement is dynamic, so since the width of the menu exceeds the space available to the left, it defaults to open it on the right because on that side it will not risk being inaccessible. 

Solutions:

- widen the sidebar
- shorten the menu/text

**Comment by BLoe** [comment]
Nice, good call! That worked. PR here: https://github.com/pixiebrix/pixiebrix-extension/pull/4335
