### ISSUE TITLE
No UI affordance to save mod if mod listing is open

### ISSUE THREAD

**Issue by fregante** [pixiebrix/pixiebrix-extension#4334]
Following:

- https://github.com/pixiebrix/pixiebrix-extension/issues/3882
- https://github.com/pixiebrix/pixiebrix-extension/pull/3934

Fundamental actions like saving can no longer be performed until the sidebar is opened again, which is a big step back in UX. 

<img width="777" alt="Screen Shot" src="https://user-images.githubusercontent.com/1402241/191486792-d49b9aec-6161-4aa3-abda-3182bc313e82.png">

A similar issue occurs when the sidebar is open, but the scroll position hides the current extension:

<img width="1006" alt="Screen Shot 4" src="https://user-images.githubusercontent.com/1402241/191487163-d002996e-d7fd-4964-bc71-fa51850c91ba.png">

## Solutions

- Revert the change, maybe keeping them as smaller icons if the issue is space
- Find another place outside the sidebar

**Comment by fregante** [comment]
## Note

I think that the initial mockup included "Save" buttons on the closed sidebar, but that doesn't cover my second example. The current position does not feel right to me. It feels like the always-visible "Brick actions" have a greater visual importance than "Save", which shouldn't be the case.

**Comment by corinnemayans** [comment]
https://pixiebrix.productboard.com/entity-detail/features/15920571

**Comment by fregante** [comment]
@corinnemayans I think this is worth picking up again, I never understood why a vital action is in a collapsible area when the top bar has a lot of space.

The [MV3 sidebar](https://github.com/pixiebrix/pixiebrix-extension/pull/7320) takes space from the pageEditor too, so this issue will be even more painful going forward. 

## Today

<img width="1564" alt="Screenshot 6" src="https://github.com/pixiebrix/pixiebrix-extension/assets/1402241/4e3a9e39-7868-4ea5-87a8-dcbde2beb35c">

## Future


At a very comfortable 1500px-wide display, the editor is not usable unless you collapse at least one sidebar:

Notice how the form labels are unreadable.

<img width="1566" alt="Screenshot 14" src="https://github.com/pixiebrix/pixiebrix-extension/assets/1402241/2d51faf2-e324-46be-9736-1034b1fe0f6a">

**Comment by fregante** [comment]
Related:

- https://github.com/pixiebrix/pixiebrix-extension/issues/4867

**Comment by fregante** [comment]
Similarly, the user can't save if the sidebar is open but current mod is not in the viewport:

<img width="611" alt="Screenshot 2" src="https://github.com/pixiebrix/pixiebrix-extension/assets/1402241/214aa046-48f9-45a1-a0e3-a6d653737e12">

**Comment by grahamlangford** [comment]
cc @BrandonPxBx

**Comment by twschiller** [comment]
Closing as "wontfix" - will revisit as part of Page Editor UI review
