### ISSUE TITLE
"Selected" bounding box is off for variable copy buttons nested below the top level in the data panel

### ISSUE THREAD

**Issue by BLoe** [pixiebrix/pixiebrix-extension#4340]
Top level copy button:
![image](https://user-images.githubusercontent.com/2801308/191796442-bef1e77a-3aa4-44f8-92e4-b01da7a1d9fe.png)

Nested:
![image](https://user-images.githubusercontent.com/2801308/191796533-8ecd53b2-85fb-4d35-a421-639fa39f539b.png)

**Comment by fregante** [comment]
👍 

Smells like a flexbox thing fixable via `flex-shrink: 0`
