### ISSUE TITLE
Add Page Editor "Add Brick" special category for Automation Anywhere

### ISSUE THREAD

**Issue by twschiller** [pixiebrix/pixiebrix-extension#4341]
Add Automation Anywhere category in the Page Editor and use the subtype of marketplace tag to populate the list\. Use the Automation Anywhere logo \(ok that this stands out as not purple\)\.This category should only show up for Automation Anywhere partners,

<p></p>

We believe this will be familiar to their users and address their primary need of having a grouping with all AA bricks in the Page Editor\.

[](https://www.notion.so/pixiebrix/Pre-spec-alignment-on-search-slicing-0766361c915c4632b0477159b664506f)

<p></p>

<p></p>

**Comment by twschiller** [comment]
Link to feature: https://pixiebrix.productboard.com/feature-board/planning/features/15437573

**Comment by corinnemayans** [comment]
Note - this issue was auto-generated by ProductBoard, not written by Todd. See Corinne for questions.
