### ISSUE TITLE
DB Support Slice 1: Define a Database Reference Type and show Database Picker

### ISSUE THREAD

**Issue by twschiller** [pixiebrix/pixiebrix-extension#4343]
\(This issue was generated using ProductBoard\. See Corinne for questions\.\)

<p></p>

<https://www.notion.so/pixiebrix/Activation-time-Database-Selection-800b2548093d415d981ce40d656489c7>

<p></p>

Define a Database Reference Type and show Database Picker

- Add a [https:\/\/app\.pixiebrix\.com\/schemas\/database\/](https://app.pixiebrix.com/schemas/services/@pixiebrix/api) schema that is an alias for type `type: string` and `format: uuid`

- Modify the code in the Widget configuration factory, if the type of the field is `$ref: "[<https://app.pixiebrix.com/schemas/database/>](<https://app.pixiebrix.com/schemas/services/@pixiebrix/api>)"` , then show the database picker widget

- Verify in the Page Editor that if the type is database, that the user can select a database, or provide a variable

- Verify the Database Picker is shown on the Blueprints Activation screen\. \(Define a blueprint in the workshop that takes a database as input\)

<p></p>

<https://github.com/pixiebrix/pixiebrix-extension/issues/4343>

[](https://github.com/pixiebrix/pixiebrix-extension/issues/4343)

**Comment by twschiller** [comment]
Link to subfeature: https://pixiebrix.productboard.com/feature-board/planning/features/15485062

**Comment by BALEHOK** [comment]
Demo https://www.loom.com/share/07e5bf3b4caf47708db54a9ac28989e6
