### ISSUE TITLE
Verify background-only network requests don't break on MV3

### ISSUE THREAD

**Issue by twschiller** [pixiebrix/pixiebrix-extension#4391]
Context
---
- Follow up to https://github.com/pixiebrix/pixiebrix-extension/issues/4357#event-7499863613
- We think requests proxied via background page will keep the background page alive due to the open message
- However, we need to verify the background-only requests prior to releasing an MV3 extension
- So opening this issue as low priority just to track the concern

Background Activity
---
> I think this cover most if not all of our concerns. If we do have truly-background activity, moving it to an offscreen document would be the right path.

I think all the pure background requests occur on start up or at a recurring interval (so restarts are OK), but I want to double-check as part of QA/verifying the MV3 build

- Starter Blueprints: on startup
- Deployment checks: startup and recurring intervals

**Comment by fregante** [comment]
According to this document, fetches can be interrupted after 30 seconds. Assuming they don't last nearly as long, we should be fine:

https://developer.chrome.com/docs/extensions/develop/concepts/service-workers/lifecycle#idle-shutdown

Additionally, this line seems to suggest that only long-running tasks (>30) will be cancelled:

> After 30 seconds of inactivity. Receiving an event or calling an extension API resets this timer.

Do we have anything that can take longer than that?

**Comment by fregante** [comment]
> We sometimes see longer fetches for some external APIs, e.g., ChatGPT

For that we can alternatively use a local iframe. The only reason why we can't contact those APIs directly I think is CORB, so any user-requested fetch can just use an iframed `chrome-extension://` page, not necessarily the background page.

> implement long-polling to support alerts

My guess is that someone already described a solution for notifications, so I don’t think that would be a problem in the future.

> these occur when there's a call that has a UI blocking action

What you're describing doesn't sound applicable here. The content script does not get killed; the action happens in the content script and the user can keep the form open for as long as needed. When the form is submitted,  _that_ action will still be immediate and will use/restart the background page as needed.

> There's maybe also some corner cases on running bricks on other tabs

That's indeed a good one. I wonder if the "local iframe" could also work here as an alternative to broadcasting via the background 🤔 

> we'll need to go for a persistent worker

There's no "persistent background worker" in Chrome MV3, I'm not sure what you're referring to

**Comment by twschiller** [comment]
> The content script does not get killed; the action happens in the content script and the user can keep the form open for as long as needed. When the form is submitted, that action will still be immediate and will use/restart the background page as needed.

For my understanding - when the background worker restarts, does that invalidate the extension runtime context (like a reload would). From your comments, it sounds like the extension runtime context still works during/after a worker restart, but just that the worker is unavailable while restarting

> 
We sometimes see longer fetches for some external APIs, e.g., ChatGPT

For that we can alternatively use a local iframe. The only reason why we can't contact those APIs directly I think is CORB, so any user-requested fetch can just use an iframed chrome-extension:// page, not necessarily the background page.

implement long-polling to support alerts

My guess is that someone already described a solution for notifications, so I don’t think that would be a problem in the future.

these occur when there's a call that has a UI blocking action

What you're describing doesn't sound applicable here. The content script does not get killed; the action happens in the content script and the user can keep the form open for as long as needed. When the form is submitted, that action will still be immediate and will use/restart the background page as needed.

There's maybe also some corner cases on running bricks on other tabs

That's indeed a good one. I wonder if the "local iframe" could also work here as an alternative to broadcasting via the background 🤔

we'll need to go for a persistent worker

> There's no "persistent background worker" in Chrome MV3

Correct - I was referring to using the hack to keep it alive indefinitely (subject to them fixing the Chromium bug)

**Comment by twschiller** [comment]
Other tip for keeping the service worker alive: https://github.com/w3c/webextensions/issues/214#issuecomment-1865249950

**Comment by fregante** [comment]
Doesn't that comment confirm that this issue can be closed?

**Comment by tophf** [comment]
Network requests are dropped when the worker is put down to sleep, so you'll still have to actually do something to keep the worker alive like sending a message (or calling any asynchronous `chrome` method) every 29 seconds or less. Since your background bundle is quite big you may want to add an option for your users to customize the keep-alive behavior: Performance (1 hour), Memory (no special handling), Balanced (based on the amount of available RAM obtained in chrome.system.memory.getInfo), Custom (number of minutes).

**Comment by twschiller** [comment]
@fregante have you seen any issues with this? I haven't encountered any problems while dogfooding. We might be good to close?

**Comment by fregante** [comment]
I haven't, but also I don't use bricks with explicit HTTP requests. I think that any API that **doesn't send packets for 30 seconds** should be considered "unsupported" for the time being and we can reconsider once/if that is ever seen. Do you know of anyone using long polling in their mods? I think that's just about the only scenario that Chrome intentionally break.

**Comment by twschiller** [comment]
> Do you know of anyone using long polling in their mods?

That's a good callout. Not currently, but we've been considering it as an option for some notifications mods with our partner. In general, web sockets will be more of a pain to implement than long-polling because there's less standardization

I think we can close this for now
