### ISSUE TITLE
Disable markdown links in the document builder preview

### ISSUE THREAD

**Issue by twschiller** [pixiebrix/pixiebrix-extension#4402]
Context
---
- If you add a link via markdown in the document builder, the preview renders it
- Accidentally Clicking on the link causes the Page Editor to redirect to the page (in the dev tools) and you lose your work

**Comment by fregante** [comment]
I think potentially we just need this:

```js
preview.addEventListener(event => event.preventDefault())
```

This will block all native behavior, including `button` clicks (which are already covered by my other PR)

Note: this also blocks `summary` clicks and any `checkbox` toggles, if they exist possible. Limiting it to `a` elements could be safer:


```js
preview.addEventListener(event => {
	if (event.target.closest('a')) 
		event.preventDefault()
})
```

Related:

- https://github.com/pixiebrix/pixiebrix-extension/pull/4136
