### ISSUE TITLE
Page editor auto-complete bug when uses space

### ISSUE THREAD

**Issue by corinnemayans** [pixiebrix/pixiebrix-extension#4438]
There's a weird auto complete bug in the page editor, when I try to use a variable that has a space in it the following happens

• <https://www.loom.com/share/1cf5e7c05312440090a2fcb991a3fb73>

[Slack Message](https://pixiebrix.slack.com/archives/C0436P48QHY/p1665435582165779)

**Comment by corinnemayans** [comment]
Discovered by Orlando. See slack message and Loom above.

**Comment by twschiller** [comment]
Potentially related to discussion at: https://github.com/pixiebrix/pixiebrix-extension/pull/4371

**Comment by twschiller** [comment]
Closing as dup
