### ISSUE TITLE
Selection Tool is not isolated from page style

### ISSUE THREAD

**Issue by twschiller** [pixiebrix/pixiebrix-extension#4440]
Steps to Reproduce
---
- Visit reddit.com 
- Open selection tool

Problems
---
- Font shows as white, so it's unreadable

Discussion
---
- Is the selector tool missing a shadow root?
- Do some of the font-sizes, etc. need to be explicitly provided on the root to override base HTML styles?

Screenshots
---
![image](https://user-images.githubusercontent.com/1879821/195163675-3000f11d-cf09-479a-be61-793aeb789cff.png)

![image](https://user-images.githubusercontent.com/1879821/195163787-1669bf3b-2f1d-4b4d-8f9c-14d13b89ea0a.png)

**Comment by jcforest** [comment]
@twschiller Could you share the url that you used? I tried on reddit.com but it works fine.

**Comment by fregante** [comment]
I created this playground page: https://pbx.vercel.app/style-conflicts/

<img width="962" alt="Screen Shot" src="https://user-images.githubusercontent.com/1402241/195238174-cada8036-5e34-4864-96bf-6670feda1ac8.png">

**Comment by jcforest** [comment]
thank you @fregante

**Comment by fregante** [comment]
This could be avoided by moving this widget back to the editor, in a proposed overlay/modal:

- https://github.com/pixiebrix/pixiebrix-extension/pull/4451
