### ISSUE TITLE
Selection tool stays open after closing dev tools

### ISSUE THREAD

**Issue by twschiller** [pixiebrix/pixiebrix-extension#4441]
Steps to Reproduce
---
- Open selection tool
- Set to multi selection mode
- Select 1 or more elements
- Close the dev tools

Expected Behavior:
- The page is not in selection mode

Actual Behavior
- The selection mode toolbox still shows. And the page is still in selection mode

**Comment by jcforest** [comment]
@twschiller It seems technically impossible to do since we're not able to detect debug tool opening/closing in chrome after I did many researches. 
Do you have any ideas how to do this?

**Comment by fregante** [comment]
At some point we can also set up an ad-hoc `runtime.connect` channel exclusively to detect closures immediately, like editor crashes and reloads. 

I think the connection can be opened from the editor as soon as the "content script ready" event is received and then the content script can listen to the channel closing.

**Comment by fregante** [comment]
Related, more DOM is affected by this:

- https://github.com/pixiebrix/pixiebrix-extension/issues/4258
