### ISSUE TITLE
Error-style Alerts in show alert brick are reported as errors in error telemetry error

### ISSUE THREAD

**Issue by twschiller** [pixiebrix/pixiebrix-extension#4447]
Context
---
- https://rollbar.com/pixiebrix/pixiebrix/items/6335/occurrences/269188071901/

Steps to Reproduce
---
- Use the "Show Alert" brick and set the level to "Error"

Expected Behavior
---
- User is shown alert in error style, but the error is not reported anywhere. (It's just a notification)

**Comment by fregante** [comment]
Presumably because it uses our own notify API, which defaults to reporting errors
