### ISSUE TITLE
Improve UX of Selection Tool card

### ISSUE THREAD

**Issue by twschiller** [pixiebrix/pixiebrix-extension#4450]
Implementation Sketch
---
- Increase overlay contrast between user-selected and inferred elements
- Add drag handle icon to the section tool card header to signify that the selection tool is draggable
- Hide "Select Similar" toggle in single selection mode

For Discussion
---
- Clarify what the states mean on the toggles. In other places in the tool, we generally vary the text/caption to textually describe what the current state of the toggle means. This might be harder with the inline labels

Related
---
- https://pixiebrix.slack.com/archives/C03CA2M4RCM/p1665494742975729

**Comment by corinnemayans** [comment]
@icugideon -- Will you please take a look at the colors used and also at the drag handle icon to make sure they fit with the design system.
