### ISSUE TITLE
Add support for passing arguments to the embedded AARI widget

### ISSUE THREAD

**Issue by twschiller** [pixiebrix/pixiebrix-extension#4458]
Context
---
- AA 0.26 introduces and embeddable AARI iframe. We have a YAML-based brick that wraps the widget to make it easy to include in a sidebar
- The AARI widget doesn't yet support passing arguments via URL search parameters
- We faced a similar limitation with UiPath Apps. To pass arguments, we implemented a JS brick that returns the iframe and uses the forms/set brick to set the inputs: https://github.com/pixiebrix/pixiebrix-extension/blob/c4cfcba2da729c913266cc22e8f0016769b5c0b1/src/contrib/uipath/embedApp.ts#L48-L48
- YAML based bricks is currently unpublished: `@aa/aari/widget-renderer`
- @mthek10 is the builder of the YAML brick

Implementation Sketch
---
- Copy the `@pixiebrix/uipath/app` brick and adapt for the AARI widget bricks
- Remove the YAML-based brick from the registry

Alternative Approaches
---
- This limitation may come up with all iframeable content. A more general approach would be to introduce the ability to run bricks in sidebar iframes. 

Discussion/Considerations
---
- We should ask the AA team what the URL-based interface is expected to be, so when support is rolled out we can just use the URL-parameter based approach
- The `forms/set` brick might not work for the AARI forms. IIRC, AARI forms don't have the argument name as the name for the field?
- Out of the gate, we only need to support the most common input types, e.g., text fields, date fields, etc.

Reference
---
- AARI bricks Trello: https://trello.com/b/s64gBaza/aari-bricks

**Comment by corinnemayans** [comment]
Assigning to @twschiller for specification spike.

Reference:
https://pixiebrix.slack.com/archives/C042T2TBZ17/p1665752353219009

<img width="482" alt="image" src="https://user-images.githubusercontent.com/111797779/196490014-debb3029-c9b6-41f6-9e9f-7983bcf1b118.png">
