### ISSUE TITLE
DB Support in Public Marketplace and team deployments

### ISSUE THREAD

**Issue by twschiller** [pixiebrix/pixiebrix-extension#4462]
<https://github.com/pixiebrix/pixiebrix-extension/issues/4293>

<p></p>

<https://www.notion.so/pixiebrix/Activation-time-Database-Selection-800b2548093d415d981ce40d656489c7>

<p></p>

Necessary pre-cursor to things like show notes in sidebar.

<p></p>

**Comment by twschiller** [comment]
Link to feature: https://pixiebrix.productboard.com/feature-board/planning/features/15385232

**Comment by corinnemayans** [comment]
This was an accidental click in ProductBoard. Ignore! :)
