### ISSUE TITLE
UX improvements to "Make a Copy"

### ISSUE THREAD

**Issue by twschiller** [pixiebrix/pixiebrix-extension#4463]
\[This was auto\-generated from ProductBoard\.\]

<p></p>

Need to get some design feedback on "Make a Copy" and make updates\.

Ben to expand based on sprint planning discussion\.

<p></p>

**Comment by twschiller** [comment]
Link to subfeature: https://pixiebrix.productboard.com/feature-board/planning/features/15860347

**Comment by corinnemayans** [comment]
First need to make sure that the validation on ID works correctly.

**Comment by corinnemayans** [comment]
Please post Loom to #sprint-demo when complete.
