### ISSUE TITLE
Temporary pop-up Slice 1: Add the “Display Temporary Information” brick

### ISSUE THREAD

**Issue by twschiller** [pixiebrix/pixiebrix-extension#4464]
\[This issue was auto\-generated using ProductBoard\.\]

<https://github.com/pixiebrix/pixiebrix-extension/issues/4464>

<p></p>

You hit an API and then want to show the results of it, and it comes up only after the results come up \(doesn't show up with blank sidebar\)\.

<p></p>

Enables use cases where people want to build on hover over a term, hit an API, then shows additional context\. <span data-preserve-white-space></span>

<p></p>

**Draft specification:** [**https:\/\/www\.notion\.so\/pixiebrix\/Ephemeral\-Temporary\-Document\-Renderer\-acd663a90fb64444ae372404ea6bda8a**](https://www.notion.so/pixiebrix/Ephemeral-Temporary-Document-Renderer-acd663a90fb64444ae372404ea6bda8a)

<p></p>

This issue is for Slice 1 only\.

<p></p>

- **Slice 1: add the “Display Temporary Information” brick**

    - Add a new transformer brick “Display Temporary Information” that takes a: <span data-preserve-white-space></span>

        - Renderer pipeline argument\.  `@pixiebrix/display`

        - A title \(string\)

      <p></p>

    - Add sidebarSlice `temporaryPanels` state to SidebarState

    - In sidebarController add a `showRenderer` method that’s called by the method

    - In the SidebarApp protocol, add a onShowRenderer method and wire up to redux in `getConnectedListener`

    - If a tab in the SidebarApp is for a temporaryPanel, add a close handle to the tab

  <p></p>

- Week 42: 5 points

- Week 43: 2 points remain

**Comment by twschiller** [comment]
Link to subfeature: https://pixiebrix.productboard.com/feature-board/planning/features/15729074

**Comment by corinnemayans** [comment]
Please post Loom to #sprint-demo when complete.
