### ISSUE TITLE
Autocomplete Slice #1: write visitor to determine values that may exist for each input

### ISSUE THREAD

**Issue by twschiller** [pixiebrix/pixiebrix-extension#4465]
\[This issue was automatically opened using ProductBoard\.\]

<https://github.com/pixiebrix/pixiebrix-extension/issues/4465>

<p></p>

Give variable usage assistance in the page editor with autocomplete\.

<p></p>

This issue is for Slice 1\.

<p></p>

Specification:

<https://www.notion.so/pixiebrix/Autocomplete-Autosuggest-Expressions-270c903d6bf043848fd1a3dcd4cffe45>

<p></p>

- **Slice N1: write visitor to determine values that may exist for each input**

    - Write an analysis visitor that compiles the following information\. \(Needs to construct a lattice of types for may\/must analysis\) <span data-preserve-white-space></span>

        - Declared Output keys of previous steps → evidence that output key is available <span data-preserve-white-space></span>

            - Later steps with same output key override previous steps

            - Assumes the output schema of the brick\. If no output schema, assume `any`

          <p></p>

        - The Context from the previous run\. \(Or the Context of the previous brick \+ output key\) if not run yet

        - Bonus: if expression is used as an input to a brick, can infer that the input satisfies the inputSpec in later bricks\. \(Otherwise it would throw a dynamic validation error before getting to that brick\)

        - Need to handle the For\-Each, Try\-Except, etc\. bricks that introduce additional output keys

      <p></p>

    - Week 42: 5 points

    - Week 43: 3 points remain

  <p></p>

- <p></p>

**Comment by twschiller** [comment]
Link to subfeature: https://pixiebrix.productboard.com/feature-board/planning/features/15728980

**Comment by corinnemayans** [comment]
I meant to title this "Autocomplete Slice 1", but it won't let me edit the title since it thinks Todd opened it...
