### ISSUE TITLE
Blueprints/extensions in Page Editor sometimes take a long time (30+ seconds) to load

### ISSUE THREAD

**Issue by twschiller** [pixiebrix/pixiebrix-extension#4485]
Context
---
- Enterprise user has 60+ extension installed, with 4-5 active on the page
- Normal speed is 2-5 seconds to initialize the Page Editor. User has reported it sometimes take a long time (30+ seconds) to load

Discussion
---
- Could be the available/unavailable calculation? Probably makes sense not to block Page Editor load on that
- At some point we have to figure out how to report performance metrics from the extension

**Comment by fregante** [comment]
Related/copy:

- https://github.com/pixiebrix/pixiebrix-extension/issues/2614

**Comment by twschiller** [comment]
Potentially addressed in: https://github.com/pixiebrix/pixiebrix-extension/pull/4531

**Comment by fregante** [comment]
Blueprints still take a while to load, maybe that could be a more specific issue or we can reuse this one for that purpose. I think however it would require changes in the app more than here, I'm not sure.

**Comment by corinnemayans** [comment]
@twschiller - The team would like to know what "definition of done" looks like. Are we fixing the performance issue, or making the UX better to work around the issue? Is the goal for everything to load in 5 seconds or less?

Note -- Johnny has looked into https://github.com/pixiebrix/pixiebrix-app/issues/2184 and hasn't been able to reproduce it, so requires deeper investigation.  
Note -- The team believes there is a need to continue thinking/evolving the architecture for this topic. Mostly related to pulling bulk lists of entities. (e.g. recipes and blocks)

Story pointing based on assumption that using cached info for recipes: 5 (Aleksandr)

**Comment by twschiller** [comment]
For this ticket, I think the definition of done should be:

1.  Making Page Editor startup time not dependent on remote brick fetching. @fregante's PR might have already accomplished this? https://github.com/pixiebrix/pixiebrix-extension/issues/2614
2. Send send slow (5+ second) Page Editor times to rollbar at warning level so we can asses the scale of the problem

The re-architecture of registry fetching is going to require specification and R&D specs. Support for brick version pinning is a big consideration that needs to be thought out

**Comment by corinnemayans** [comment]
3 story points remaining
