### ISSUE TITLE
RTK errors are swallowed (no log, no report)

### ISSUE THREAD

**Issue by fregante** [pixiebrix/pixiebrix-extension#4489]
Repro:

1. Add `throw new Error('TEST')` to after the UUID line

	https://github.com/pixiebrix/pixiebrix-extension/blob/4061afede8e9e1a64a63ed438805ac94dd5df6ed/src/pageEditor/tabState/tabStateSlice.ts#L49-L54

2. Open the console or background console

The error is never reported, it doesn't bubble up to the global handler nor there's any RTK-specific handler to catch it. It's completely hidden from the developer. 

In this case it appears in the UI, but I suppose it might as well not:

<img width="300" alt="Screen Shot" src="https://user-images.githubusercontent.com/1402241/196399853-92c1c1a7-fd93-4106-a020-aee39f1add51.png">

# Related

- https://github.com/pixiebrix/pixiebrix-extension/issues/4032

**Comment by twschiller** [comment]
Raising priority of this in case it's the root cause of missing error indicators in other places

**Comment by corinnemayans** [comment]
Story points: 2

**Comment by BLoe** [comment]
@twschiller What does "missing error indicators in other places" refer to here?

**Comment by fregante** [comment]
Probably: since errors are swallowed, it's possible that they're not being displayed anywhere even in the UI. The screenshots above do show this "error indicator" but other places might not.

**Comment by twschiller** [comment]
> @twschiller What does "missing error indicators in other places" refer to here?

Correct, I was just flagging that it could cause user error toasts/form validation to not appear in some places. I didn't not investigate particular cases.
