### ISSUE TITLE
There should be a faster feedback loop when the wrong element is picked

### ISSUE THREAD

**Issue by fregante** [pixiebrix/pixiebrix-extension#4491]
When picking an element, every time the user clicks on the wrong element, they are kicked out of the selection mode and are shown an error:

https://user-images.githubusercontent.com/1402241/196393712-54da9bbf-6dc1-475b-903f-5613de90375b.mov

## Solutions

- Move the filtering logic into the content script so that the selected element can be rejected before resolving the promise
- https://github.com/pixiebrix/pixiebrix-extension/pull/2508

**Comment by corinnemayans** [comment]
We have some backlog items to improve how we handle buttons, and this fits into that. Added this to our ProductBoard collection of button-related items. https://pixiebrix.productboard.com/entity-detail/features/15891972
