### ISSUE TITLE
Broadcast not returning results when Page Editor is open

### ISSUE THREAD

**Issue by twschiller** [pixiebrix/pixiebrix-extension#4493]
Context
---
- 10/17 customer saw that broadcast (of jquery brick) was not returning when extension was run from the Page Editor. The other steps in the extension did not run
- Problem occurs when Page Editor is not open
- User reports that problem started with 1.7.10
- ~Broadcast appeared to be working for same extension when page editor was not open~ Correction: user reports broadcast also not working when Page Editor is not open

Hypotheses/Discussion
---
- Failed connection to a tab causing broadcast to hang? (Error isn't being handled properly)
- Need to enforce timeout for broadcast to each tab?

**Comment by fregante** [comment]
Waiting for further details via Slack

**Comment by twschiller** [comment]
Closing - working on customers computer now
