### ISSUE TITLE
Blueprint sharing error

### ISSUE THREAD

**Issue by corinnemayans** [pixiebrix/pixiebrix-extension#4497]
<https://www.loom.com/share/d9ad5a4cc00d4d5daca7b2a2c1d1e268|Blueprint Sharing>

[Slack Message](https://pixiebrix.slack.com/archives/C0436P48QHY/p1665684572418839?thread_ts=1665684572.418839&cid=C0436P48QHY)

**Comment by twschiller** [comment]
Closing, the loom link no long works and there isn't enough context in the Slack message
