### ISSUE TITLE
Cannot view diff of current version of brick vs. historic versions in the Workshop

### ISSUE THREAD

**Issue by twschiller** [pixiebrix/pixiebrix-extension#4499]
Context
---
- On 1.7.10
- For bricks the current version of the blueprint/brick is not appearing
- The diff has never shown unsaved code, this issue is referring to the current saved version not appearing
- https://pixiebrix.slack.com/archives/C0436P48QHY/p1666124727038049?thread_ts=1666111908.202029&cid=C0436P48QHY

Discussion
---
- This makes it impossible to see what the latest changes were
- This might be an API/server issue

Screenshot
---
![image](https://user-images.githubusercontent.com/1879821/196560044-98428ffa-1bc5-4f09-8b53-2f2b959cfcbc.png)

**Comment by corinnemayans** [comment]
Story points: 2
