### ISSUE TITLE
Custom Quickbar Item appearing below default "PixieBrix" actions

### ISSUE THREAD

**Issue by twschiller** [pixiebrix/pixiebrix-extension#4501]
Context
---
- Tested on 1.7.10

Steps to Reproduce
--- 
- Add quick bar item
- Item appears at bottom of list

Expected Behavior
---
- User-defined actions appear above the default PixieBrix grouping

Screenshot
---
![image](https://user-images.githubusercontent.com/1879821/196696536-562490be-97bd-407f-85ab-c1105aab3d17.png)

**Comment by fregante** [comment]
Note for the bugfixer: we had the exact issue a few months ago, so it’s a regression.
