### ISSUE TITLE
Sidebar doesn't load on delta.com. Target for SIDEBAR_RENDER_PANELS not found

### ISSUE THREAD

**Issue by corinnemayans** [pixiebrix/pixiebrix-extension#4502]
v1.7.9 Sidebar. (Reproduced in 1.7.10 as well) Only happens on <http://delta.com|delta.com> and happens on my laptop as well. Any ideas? Shane (AA) found this.

[Slack Message](https://pixiebrix.slack.com/archives/C0436P48QHY/p1665764439552929?thread_ts=1665764439.552929&cid=C0436P48QHY)

**Comment by twschiller** [comment]
I haven't been able to reproduce this so far. Someone needs to pair with @mthek10 I think to look through the Chrome Dev Tools Console error reporting

**Comment by mthek10** [comment]
<img width="1628" alt="image" src="https://user-images.githubusercontent.com/33663144/196777881-c3bd77ed-18a8-4291-8e3a-376ee654cc42.png">

**Comment by corinnemayans** [comment]
Reproduced in 1.7.11-beta2 also.

**Comment by twschiller** [comment]
@fregante are you able to reproduce this? This would be a good issue for you to pick up with spare cycles

**Comment by fregante** [comment]
First try, it happened. Will investigate:

<img width="1309" alt="Screen Shot" src="https://user-images.githubusercontent.com/1402241/197155205-8144557d-0793-4e58-9afc-36290d89f0b0.png">
