### ISSUE TITLE
Database selector widget takes a long time to load

### ISSUE THREAD

**Issue by twschiller** [pixiebrix/pixiebrix-extension#4511]
Context
---
- Database widget takes 5-15 seconds to load for some people (especially members of large orgs/many databases)

Discussion
---
- Looking at the network timing, the result is coming back in 100-200ms. Hypotheses: 
   - 1) debouncing of some kind occurring in the widget itself
   - 2) Chrome has a maximum number of requests it will make at a time, before the other requests get queued. So if there's other network activity, it could be getting blocked

Reference
---
- [Slack Discussion/Investigation](https://pixiebrix.slack.com/archives/C0436P48QHY/p1666111268552029)

**Comment by johnnymetz** [comment]
Loom demonstrating the problem: https://www.loom.com/share/c4ac9913628e4735a461b2a3d0f1a5ab

**Comment by BALEHOK** [comment]
I'm not able to reproduce the issue. The cause may be similar to the [one we have with `/recipes`](https://github.com/pixiebrix/pixiebrix-extension/issues/4485).

**Comment by corinnemayans** [comment]
Given the challenge to reliably reproduce this issue, removing the milestone. If someone can provide a reliable means to reproduce, we can schedule it again.

**Comment by twschiller** [comment]
> Given the challenge to reliably reproduce this issue, removing the milestone. If someone can provide a reliable means to reproduce, we can schedule it again.

On 1.7.12 against prod API, I'm able to reliably reproduce this. It takes 10+ seconds to load for me. I will see if I can collect more information to help the investigation

**Comment by corinnemayans** [comment]
@twschiller - Have you seen this again?

**Comment by twschiller** [comment]
@corinnemayans let's close this out and re-open as necessary. It's fast for me in the 1.7.16 build at least
