### ISSUE TITLE
Blueprint Options cleared when updating blueprint description in Page Editor

### ISSUE THREAD

**Issue by twschiller** [pixiebrix/pixiebrix-extension#4512]
Context
---
- Reported by @orliesaurus on version 1.7.10
- https://pixiebrix.slack.com/archives/C0436P48QHY/p1666279537389879

Discussion
---
- Potential blocker to promoting use of templates/marketplace blueprints

**Comment by corinnemayans** [comment]
Need to be able to reproduce this.
