### ISSUE TITLE
Temporary Popup Slice 2: add the ability to view the panel using the snap of the last run

### ISSUE THREAD

**Issue by twschiller** [pixiebrix/pixiebrix-extension#4521]
\[This issue was auto\-generated using ProductBoard\.\]

<p></p>

**Draft specification:** [**https:\/\/www\.notion\.so\/pixiebrix\/Ephemeral\-Temporary\-Document\-Renderer\-acd663a90fb64444ae372404ea6bda8a**](https://www.notion.so/pixiebrix/Ephemeral-Temporary-Document-Renderer-acd663a90fb64444ae372404ea6bda8a)

<p></p>

- **Slice 2: add the ability to view the panel using the snap of the last run**

    - In the Preview pane of the data panel, add a “Preview from Snapshot” button

    - On click, send a message to the content script with the 1\) brick definition, and 2\) latest snapshot of data\. \(See existing preview code\)

  <p></p>

**Comment by twschiller** [comment]
Link to subfeature: https://pixiebrix.productboard.com/feature-board/planning/features/15729085

**Comment by corinnemayans** [comment]
Duplicate. Going to use the one more recently generated by ProductBoard because that one is linked properly. #4621
