### ISSUE TITLE
Bug: When viewing "unavailable" extensions in the page editor, the unavailable count increments incorrectly.

### ISSUE THREAD

**Issue by BLoe** [pixiebrix/pixiebrix-extension#4524]
https://pixiebrix.slack.com/archives/C0436P48QHY/p1666388165242869

![gif](https://user-images.githubusercontent.com/1402241/197324757-22663083-765e-4071-95e5-d0d848f35485.gif)

**Comment by BALEHOK** [comment]
Related issue: the counter doesn't change when an unavailable extension is removed
https://www.loom.com/share/01535a656fee4029a7be363cd22e3765
