### ISSUE TITLE
Setup page flashes the regular options.html content with error 

### ISSUE THREAD

**Issue by fregante** [pixiebrix/pixiebrix-extension#4527]
I think this is a regression. You can see the issue also appearing as a "flash of content" even on the main page, before showing the setup steps

## Repro: flash of broken UI

1. Clean browser
1. Log out from pixiebrix.com
1. Install extension from store
2. Notice flash on the first screen

## Repro: settings page accessible when logged out

1. Visit settings page
3. Clear token
4. Refresh
5. You're logged out but the page, but the settings page is still visible

The video shows the second repro: every page redirects to the setup, but the settings does not

https://user-images.githubusercontent.com/1402241/197326876-874e2a56-7f90-4281-8a13-37c1d2a3708e.mov

**Comment by twschiller** [comment]
> You're logged out but the page, but the settings page is still visible

This is intentional. Some of the Advanced Settings that are behind feature flags control what kind of authentication is used (for demoing certain authentication methods). So I made the Settings page always available. I don't think a regular user would ever hit up against the issue

**Comment by fregante** [comment]
> This is intentional

👍 


> I don't think a regular user would ever hit up against the issue

Are regular users not allowed to clear the token?

**Comment by twschiller** [comment]
> Are regular users not allowed to clear the token?

Regular users can. The solution would be to just redirect the page to the main options page after clearing the token. (Or probably better to reload the extension)

Enterprise restricted users can't clear the token if their organization has turned on interface restrictions
