### ISSUE TITLE
Upstream background page changes to webpack-target-webextension

### ISSUE THREAD

**Issue by twschiller** [pixiebrix/pixiebrix-extension#454]
To get out a fix quickly for https://github.com/pixiebrix/pixiebrix-extension/issues/451, I just added modified version of the file to our repository

We should upstream the changes to webpack-target-webextension as part of: https://github.com/crimx/webpack-target-webextension/issues/15

**Comment by fregante** [comment]
Given that you already opened a PR there, my assignment would be to wait for its release and then revert #453?

**Comment by twschiller** [comment]
I didn't get a chance to create a PR for https://github.com/crimx/webpack-target-webextension/issues/15. So you'd need to create a PR, wait for it to get released, and then switch back to their `background.js` file

**Comment by fregante** [comment]
Oh true, I mistook your detailed issue for a PR while checking it from my phone.

**Comment by fregante** [comment]
It appears that the change in https://github.com/pixiebrix/pixiebrix-extension/pull/453 didn't actually change the behavior:

1. `sender.tab.frameId` exists (as long as it's a tab) and is equivalent to `sender.frameId` (as long as it was sent from a tab) https://developer.chrome.com/docs/extensions/reference/runtime/#type-MessageSender
2. The conditions coming up to that code ensure that it comes from a tab

**Comment by fregante** [comment]
Correction, there's no such thing as a `tab.frameId` in [Tab](https://developer.chrome.com/docs/extensions/reference/tabs/#type-Tab).

<img width="281" alt="Screen Shot 4" src="https://user-images.githubusercontent.com/1402241/121771772-ad222e80-cb9b-11eb-9d8f-18b077dab6f7.png">

I think it never worked in frames, but nobody had noticed because the frameId is not needed unless you actually use frames.

**Comment by fregante** [comment]
It appears that the webpack v4 loader had the raw `import()` call and that may have been why it worked in iframes, as you said. More context in this issue:

https://github.com/crimx/webpack-target-webextension/issues/18#issuecomment-860057582

The v5 doesn’t use include that yet so it fell back to the message-based injection and this bug became visible in Chrome.
