### ISSUE TITLE
Add Design System color variables

### ISSUE THREAD

**Issue by mnholtz** [pixiebrix/pixiebrix-extension#4546]
We'd like to start incrementally integrating Design System work that @icugideon has been doing in Figma: https://www.figma.com/file/LiShRwQlnRG5zNl38oGCKl/%F0%9F%94%91-Foundation?node-id=433%3A7410

A good small first step is to define these colors in a single place and start using them as we make new features in the Extension Console and the Admin Console. TBD if (and how) we will integrate these colors into the Page Editor.

**Comment by BLoe** [comment]
@grahamlangford @mnholtz Closing this, we've already implemented the shared colors file a while ago
