### ISSUE TITLE
Save blueprint status seems to do nothing/shows inconsistent version status message

### ISSUE THREAD

**Issue by twschiller** [pixiebrix/pixiebrix-extension#4547]
Context
---
- Page Editor shows a warning if the user is editing an old version of the blueprint
- https://www.notion.so/pixiebrix/PixieBrix-TaskUs-2022-10-26-5cca06413cde4bceb5af1251f66952f6
- https://pixiebrix.slack.com/archives/C0436P48QHY/p1666801314024519

Discussion
---
- This is maybe 2 separate issues: blue save operation indicator, and incorrect version warning indicator
- During save can we indicate that a save operation is in effect? Do we disable the save button again until it comes back
- @mthek10 did the customer ever get an error? Where they getting success messages? Or was just nothing happening?
- They are assigned the deployment for the blueprint. What could be happening here is that our check in the deployment installer to prevent overwriting developer's activated blueprint could be buggy: https://github.com/pixiebrix/pixiebrix-extension/blob/76e7c7f3ef6b8e9e0da3ca8c26b946bf7784ee86/src/utils/deploymentUtils.ts#L77-L77
- Or it's possible they somehow had 2 copies of the blueprint installed (one deployment, one activated manually) so the warning is non-determinate

Triage
---
- @corinnemayans adding to sprint planning as this can result in lost work

Related Issues
---
- Potentially related: https://github.com/pixiebrix/pixiebrix-extension/issues/3565

**Comment by corinnemayans** [comment]
Issue: Hard to reliably reproduce this issue. Unclear what has happened. 
Ben to take 3 story points to investigate.

**Comment by corinnemayans** [comment]
Ben will comment with the results of the investigation and then close out this issue. There's a separate issue for the follow-up items which are lower priority now that we understand why this is coming up (due to old versions of blueprints).

**Comment by BLoe** [comment]
The way we are loading the blueprint data from the api, there are some places where it’s just grabbing the latest version instead of the specific version that a user has activated. I'll flesh out the details in the follow-up ticket.
