### ISSUE TITLE
Show partner login panel in sidebar if not authenticated/partner token has expired

### ISSUE THREAD

**Issue by twschiller** [pixiebrix/pixiebrix-extension#4548]
Context
---
- The PixieBrix sidebar is wrapped in a RequireAuth which requires authentication
- In the user is authenticated using partner auth and the token expires, the user needs to be prompted to re-authenticate with the partner
- This also would show if the user accesses the sidebar without first authenticating in the Extension Console
- Currently we are showing them a PixieBrix-branded panel with a Connect Account button that opens the Admin Console (to get them to re-link the account)
- We need to instead show a panel with an action to re-trigger the authentication flow with the partner 
- https://github.com/pixiebrix/pixiebrix-extension/blob/f503b3aaf1571a3ddb1efdf20d0783f8a61f369f/src/sidebar/ConnectedSidebar.tsx#L78-L78

Implementation Sketch
---
- If the user has authenticated previously, re-trigger authentication flow to get a new token
- If the user has not authenticated, open extension console which will show the onboarding page

Considerations
---
- In both cases, could just open the extension console. (Though I will file a separate bug ticket on expired tokens). This is a worse UX though for people with expired tokens

Related Work
---
- https://github.com/pixiebrix/pixiebrix-extension/pull/4544

Current Screenshot
---
![image](https://user-images.githubusercontent.com/1879821/198304582-ced4659d-b69c-4a54-9ca4-0c0c93d2533a.png)

**Comment by corinnemayans** [comment]
Story points: 5
