### ISSUE TITLE
Blueprint Activation screen not validating user-provided blueprint options

### ISSUE THREAD

**Issue by twschiller** [pixiebrix/pixiebrix-extension#4550]
Context
---
- https://pixiebrix.slack.com/archives/C0436P48QHY/p1666887299081169

Steps to Reproduce
---
- Activate `@sam-kartenson/misc/support-qa` which has database as a required blueprint option. But you can activate the blueprint without choosing a database

Questions/Considerations
---
- The field is listed under `required:` in the YAML. So it looks like we're not performing a JSON Schema check against the provided blueprint options?

Implementation Sketch
---
- One option: Use schema to yup to convert the schema to a yup validation that can be passed to Formik. Benefit: can provide feedback on individual fields
- Other option: in the onSubmit handler use method to check values vs. JSON Schema and show toast or form status with the first error. (Or concatenate errors with newlines)
- Might be beneficial to do both. The schema-to-yup validation only supports a subset of JSON Schema validation. 

Related Code
---
- Submit callback: https://github.com/pixiebrix/pixiebrix-extension/blob/f503b3aaf1571a3ddb1efdf20d0783f8a61f369f/src/options/pages/activateExtension/ActivateForm.tsx#L83-L83

**Comment by corinnemayans** [comment]
Story points: 1
