### ISSUE TITLE
Page Editor is blank after adding new Trigger extension to page

### ISSUE THREAD

**Issue by twschiller** [pixiebrix/pixiebrix-extension#4551]
## Context
- User is on 1.7.12-alpha.3 build
- User is logged in using partner OAuth - so partner JWT is sent to PixieBrix server
- Issue is intermittent, happens 60-80% of the time on new Page Editor sessions
- There are no errors logged to the console
- Once it's working for a Page Editor session, seems to continue to work
- PixieBrix already had permissions to modify the page
- Observed on Workday (yesterday) and SAP (today)

## Discussion

- Under what circumstances would the `/bricks/:brickId` endpoint return a 400? (Because of authentication issues, there's no payload so shouldn't return otherwise?)

## Observations

- In one observed case, network inspector shows call to endpoint https://app.pixiebrix.com/api/bricks/0b5dd731-6ca3-4a9c-a511-6e1a0dfb3874/ returned 400 error. The user has permissions for this blueprint. Other calls succeeded 

## Related Issues
- Potentially same underlying cause as?: https://github.com/pixiebrix/pixiebrix-extension/issues/4552

**Comment by BLoe** [comment]
@twschiller Just to clarify, "Page editor is blank" means that the `PixieBrix` dev tools tab appears as normal, but when clicked, the entire panel is white with no content, correct?

**Comment by twschiller** [comment]
@BLoe and I have paired on this and added some logging and fixed the problem with the currentURL hook

To answer Ben's question:
- The extension list sidebar is visible and contains expected content
- The main pain is what's blank

The EditorContent component has a couple code paths that return `null` so we're investigating what could cause it to hang in a null state

**Comment by twschiller** [comment]
Update: customer is reporting that the fix we made for permissions button also appears to have fixed this issue. Will close for now and re-open based on alpha testing.
