### ISSUE TITLE
Workshop not showing top-level config error from server on save

### ISSUE THREAD

**Issue by twschiller** [pixiebrix/pixiebrix-extension#4556]
Context
---
- Slack conversation: https://pixiebrix.slack.com/archives/C0436P48QHY/p1666903352111269?thread_ts=1666902638.031139&cid=C0436P48QHY

Steps to Reproduce
---
- Get a 400 error from server on `{config: ["message"]}`
- Message should show on workshop page

Discussion
---
- Need to clarify if this should show as toast or should be shown in errors section at bottom of editor. IIRC, "config"-level errors should be shown on the editor error section

Related Issues
---
- https://github.com/pixiebrix/pixiebrix-app/issues/2516
- https://github.com/pixiebrix/pixiebrix-extension/issues/4697

**Comment by fregante** [comment]
Related? 

- https://github.com/pixiebrix/pixiebrix-extension/issues/4489
