### ISSUE TITLE
Improvements to Var Analysis

### ISSUE THREAD

**Issue by BALEHOK** [pixiebrix/pixiebrix-extension#4591]
This is a split from https://github.com/pixiebrix/pixiebrix-extension/issues/4465
Related PR https://github.com/pixiebrix/pixiebrix-extension/pull/4545

- [x] Improve error message if user types @ - just say "Invalid variable name" #4998 

- [x] #4998

- [x] #5036

- [x] More precise handling of conditional blocks https://github.com/pixiebrix/pixiebrix-extension/pull/4545#discussion_r1009367543 (not applicable atm)

- [x] Support special characters in var name. As of now spaces are supported for exact var names, other cases may produce false negative results. Ex. `@data["hello world"]` works as expected, `@data["hello world"].0` fails.

- [x] Ananlysis Manager. As of now every analysis requires an update when nodes order changes. This can be handled implicitly by the ReduxAnalysisManager

- [x] Make it possible to define the existence for a complex var, i.e. for a var map `{ @foo: { bar: DEFINITELY } }` it should be possible to set existence to @foo and @foo.bar. Need to make sure that if a child var is "DEFINITELY" all its parents also must be "DEFINITELY".

- [x] #5051

**Comment by corinnemayans** [comment]
We discussed this during sprint planning 1/6/23. 
@BALEHOK is going to review this list. Some of the items on this list may already have been fixed. He'll work out what is remaining from this list and anything else that needs to be added, and we'll open those as separate issues to work in order to close out the autocomplete variable popover work.

**Comment by twschiller** [comment]
Additional Issues
---

- The var analysis popup shows `{ } keys` for fields that are string fields
<img width="627" alt="image" src="https://user-images.githubusercontent.com/1879821/211440648-07f75bf5-73ea-4906-9f66-787ca4378bfb.png">

**Comment by twschiller** [comment]
@BALEHOK I think you're creating a separate ticket to add Array/Array Index support?
