### ISSUE TITLE
Reset (re-run) analysis after extension reset

### ISSUE THREAD

**Issue by BALEHOK** [pixiebrix/pixiebrix-extension#4595]
Steps:
1. Make any change to the extension that results in an error (ex. make Document or Form a second to last brick)
2. See the analysis error
3. Reset the extension

Expected result:
The error disappears.

Actual result:
The error is still shown although extension is in a good shape.

**Comment by twschiller** [comment]
@BALEHOK do the errors disappear once you make an edit to the brick after you reset? Or does it get stuck?

**Comment by BALEHOK** [comment]
They disappear after edit. Just need to trigger analysis on reset.
