### ISSUE TITLE
404 errors being enriched/miscategorized as network errors

### ISSUE THREAD

**Issue by twschiller** [pixiebrix/pixiebrix-extension#4653]
## Steps to reproduce
- Add a "Get data from PixieBrix database brick"
- Add an arbitrary key, and key the `Missing Behavior: error`
- When you run the brick, you'll get the error:

> No response received. Your browser may have blocked the request. See https://docs.pixiebrix.com/network-errors for troubleshooting information.

## Discussion
- Likely related to the fetch API switchover

**Comment by fregante** [comment]
### Notes, WIP


___

This function:

https://github.com/pixiebrix/pixiebrix-extension/blob/b4efabb85acd17486ab430836400689f4120a892/src/errors/networkErrorHelpers.ts#L46-L56

Receives this error:

<img width="331" alt="Screen Shot 9" src="https://user-images.githubusercontent.com/1402241/207003073-42a0dd49-772b-417d-9e40-14ae21459a71.png">

And since `response` is undefined, the logic determines it's a network error.

**Comment by twschiller** [comment]
> And since response is undefined, the logic determines it's a network error. I also tried removing the fetch adapter and the issue persists.

I wonder if this is a Chrome or Axios change? I'm pretty sure the old logic worked at some point

**Comment by fregante** [comment]
It's possible that the error is serialized at some point and the response object is lost, so the behavior varies depending on the path. Maybe RTK affected this

**Comment by twschiller** [comment]
> Maybe RTK affected this

I'll take a look at the PR today and throw some unit tests in for the RTK hooks to get a better idea of where serialization might be impacting things (modulo any differences between axios-mock and axios behavior, but at least we'll understanding the quirks)

**Comment by twschiller** [comment]
> Maybe RTK affected this

This particular error doesn't go through RTK. But it does go through the messenger. So there's a chance that Chrome is removing the field across zones?

**Comment by fregante** [comment]
I assume this was fixed by https://github.com/pixiebrix/pixiebrix-extension/pull/4813
