### ISSUE TITLE
Dependabot builds broken

### ISSUE THREAD

**Issue by twschiller** [pixiebrix/pixiebrix-extension#466]
CI builds are failing on both the Firefox and Chrome builds. Example: https://github.com/pixiebrix/pixiebrix-extension/actions/runs/923301031

**Comment by twschiller** [comment]
It looks the environment variables are not flowing through. Here's the error message that seems to correspond with the failed build:

```ERROR in Invalid URL:```

Print out during the build:

```
SOURCE_VERSION:  undefined
SERVICE_URL:  
CHROME_EXTENSION_ID:  kkomancachnjkdalpcokenmjlimmbaog
ROLLBAR_BROWSER_ACCESS_TOKEN:  
ROLLBAR_POST_SERVER_ITEM_TOKEN not configured
```

**Comment by fregante** [comment]
Indeed I had commented on this PR, sorry: https://github.com/pixiebrix/pixiebrix-extension/pull/407#issuecomment-858911676
