### ISSUE TITLE
`unsafe-eval`, required for nunjucks and RJSF, isn't allowed in MV3

### ISSUE THREAD

**Issue by fregante** [pixiebrix/pixiebrix-extension#4693]
This line is causing an error for every brick with text input. I don't think there's any way around this, as it's not a CWS-related restriction as previously suggested, but a hardcoded MV3 limitation that blocks `eval` entirely.

https://github.com/pixiebrix/pixiebrix-extension/blob/fa9ecc1dfaab3818768788c0e243088bb13a9137/src/analysis/analysisVisitors/templateAnalysis.ts#L88

<img width="783" alt="Screen Shot" src="https://user-images.githubusercontent.com/1402241/203346349-2a1622a6-bdba-4d57-9918-6371b52a0ab5.png">

## Previously mentioned

- https://github.com/pixiebrix/pixiebrix-extension/pull/3019#issuecomment-1082950044
- https://github.com/pixiebrix/pixiebrix-extension/issues/3059
- https://github.com/pixiebrix/pixiebrix-extension/issues/4387

## External links (no solution)

- https://github.com/mozilla/nunjucks/issues/298
- https://github.com/mozilla/nunjucks/issues/1383
- [wOxxOm on StackOverflow](https://stackoverflow.com/a/69333808/288906): "The error message means you can't use unsafe-eval in MV3"

## Repro

1. Build MV3

	```sh
	MV=3 npm run watch
	```
2. Open any bricks in the page editor

**Comment by twschiller** [comment]
We have a couple options here I think:
- Sandbox: https://github.com/pixiebrix/pixiebrix-extension/issues/105
- Userscripts which will be supported in MV3: https://github.com/w3c/webextensions/issues/279

I had added this point to the agenda of the w3c kickoff meeting on userscripts, but unfortunately had the drop off the call before it was discussed. I will prioritize clarifying the behavior for MV3

**Comment by fregante** [comment]
Note that neither one is available from the background worker because they either require a full tab or an iframe. Also possible bug that might affect us:

- https://bugs.chromium.org/p/chromium/issues/detail?id=1247690

### Sandbox

The sandbox sounds like the right way to do this, either in the content script or page editor:

- https://developer.chrome.com/docs/extensions/mv3/manifest/sandbox/
- https://developer.chrome.com/docs/extensions/mv3/sandboxingEval/

### Userscripts

Unless Userscripts directly support `unsafe-eval` within them, they could become incredibly involved and slow due to messaging and probably because the "userscript" would be the raw compiled nunjucks/RJSF javascript string. Let's keep this as a last resort (also because they don't exist in Chrome yet).

Related: https://developer.chrome.com/docs/extensions/mv3/known-issues/#userscript-managers-support

**Comment by fregante** [comment]
I can work on the sandbox issue for this then. I will look into implementing a barebones connectable sandbox, possibly one that pre-loads nunjucks in order to evaluate the templates in it:

- https://github.com/pixiebrix/pixiebrix-extension/issues/105

**Comment by twschiller** [comment]
> Note that neither one is available from the background worker because they either require a full tab or an iframe

IIRC, we don't evaluate templates from the background page anyway. 

If we do need to run from background page, there's an offscreen documents proposal: https://github.com/w3c/webextensions/issues/170

**Comment by fregante** [comment]
- Closing in favor of https://github.com/pixiebrix/pixiebrix-extension/issues/105

unsafe-eval is available in the sandbox 🎉
