### ISSUE TITLE
Add eslint rule to prevent banned imports from utils directory

### ISSUE THREAD

**Issue by twschiller** [pixiebrix/pixiebrix-extension#4694]
Context
---
- https://github.com/pixiebrix/pixiebrix-extension/pull/4686/files#r1028003185
- Need to ban imports from contentScript, background, and other folders from modules in the utils directory

**Comment by fregante** [comment]
The rule is in the first few lines of this repo's eslintrc, I just need to drop the "from" line and then move code around to fix the ~100 warnings.

**Comment by twschiller** [comment]
> This shouldn't apply just to the utili folder, but to any folder. That is: files in @/background should not be imported from other folders — and so on.

That sounds correct. I'd propose we do this incrementally if possible (e.g., by context), instead of 1 massive PR for moving things around
