### ISSUE TITLE
Review mocking solutions

### ISSUE THREAD

**Issue by fregante** [pixiebrix/pixiebrix-extension#4700]
I see a few issues with the current mocking situation:

- Transparent mocking via `__mocks__` is picked up by both Jest and Storybook
	- This avoids config, but if a mock uses `jest.fn`, then Storybook fails
	- Such files have to export _everything_ we used, not just whatever we want to override
- Inline mocking via jest.mock + callback
	- This allows partial mocks, but is relatively verbose both in declaration and in usage (import module, call jest.mock, then use `(module.fn as any).mockResolvedValue()` every time)

https://github.com/pixiebrix/pixiebrix-extension/blob/56a43d73a72bd9d446310eb69bc6eae8c2918c8c/src/runtime/pipelineTests/trace.test.ts#L41-L56

### Possible solutions (discuss)

- Avoid or limit Storybook mock sharing
- Use ts-jest-mock to simplify mock typing
- 🤔

**Comment by twschiller** [comment]
There might also be ways to allow jest.fn in Storybook: 
- https://stackoverflow.com/questions/64349461/make-jest-globally-available-in-storybook
- https://github.com/storybookjs/storybook/issues/15391

Given the popularity of Jest/Storybook, I suspect some people have found the "right way" to do this

**Comment by fregante** [comment]
I noticed that you started using `jest.mocked`, which was the intent of this issue
