### ISSUE TITLE
"Disabled" option not working in Document Builder

### ISSUE THREAD

**Issue by twschiller** [pixiebrix/pixiebrix-extension#4704]
Context
---
- Tested on 1.7.14-beta.1

Steps to Reproduce
---
- Add a sidebar panel
- Add a button with an action (e.g., confetti)
- Toggle "disabled" field on the button
- Click "Render Panel"

Expected Behavior
---
- Button is disabled

Actual Behavior
---
- Button is disabled an can be clicked

**Comment by corinnemayans** [comment]
See also: https://www.notion.so/pixiebrix/Add-GUI-Affordances-for-Common-Bootstrap-Classes-to-Document-Builder-ee1952392ae7402e803bfe43a1555193?pvs=4#50a5635f508d42bc96a390a835333a9a
