### ISSUE TITLE
Remove Firefox store references from documentation

### ISSUE THREAD

**Issue by twschiller** [pixiebrix/pixiebrix-extension#4706]
Context
---
- We currently don't officially support Firefox
- In places (e.g., formerly the README.md) we included links to Firefox
- Some users were confused, especially since the Firefox store link was no longer working

**Comment by fregante** [comment]
I think the repo is already clean other than the selenium documents: https://github.com/pixiebrix/pixiebrix-extension/blob/023a27bb2c982c33d3770d6ebe73fe53dc39a189/selenium/readme.md?plain=1#L32

Search: https://github.com/search?q=repo%3Apixiebrix%2Fpixiebrix-extension%20firefox&type=code

Are you referring to the docs on Notion?
