### ISSUE TITLE
Add storybook snapshots to the extension

### ISSUE THREAD

**Issue by BLoe** [pixiebrix/pixiebrix-extension#4735]
Probably also makes sense to remove the storybook item from the PR checklist since it'll be checked automatically

**Comment by twschiller** [comment]
App PR for reference: https://github.com/pixiebrix/pixiebrix-app/pull/2656

**Comment by twschiller** [comment]
There's some stories currently broken. You could mark those as out of scope for this ticket (by disabling the Storyshots for them), and adding them the existing ticket for fixing broken stories
