### ISSUE TITLE
BusinessError subclasses are being reported to Rollbar

### ISSUE THREAD

**Issue by twschiller** [pixiebrix/pixiebrix-extension#4763]
Context
---
- We report ApplicationErrors to Rollbar so our team can triage/fix
- We report all that impact a user-defined extension to our native /errors/ endpoint

Problems
---

The are some additional ones too, but likely fixing these should fix the other cases:

- The tab doesn't exist: https://rollbar.com/pixiebrix/pixiebrix/items/6839/occurrences/302909473645/  
   - Should not be reported to Rollbar
   - Should be reported to PB /errors/ endpoint (because caused the extension to fail)
- ActionCancelled: https://rollbar.com/pixiebrix/pixiebrix/items/6844/occurrences/302910265037/
   - Should not be reported to Rollbar
   - Should **not** be reported to PB /errors/ endpoint
- NoElementsFoundError: https://rollbar.com/pixiebrix/pixiebrix/items/2545/occurrences/302910779561/
   - Should not be reported to Rollbar
   - Should be reported to PB /errors/ endpoint (because caused the extension to fail)

Related Code:
---
- https://github.com/pixiebrix/pixiebrix-extension/blob/8a23ad8e6c0a7a3671262daf8db417807471ae29/src/telemetry/logging.ts#L239-L239

**Comment by twschiller** [comment]
@fregante looks like Webpack is doing some funny business, so name checks fail:

![image](https://user-images.githubusercontent.com/1879821/205790455-3fba6b51-843b-4dee-b3c0-ca92c7338425.png)

**Comment by twschiller** [comment]
Investigation notes:
- https://webpack.js.org/plugins/module-concatenation-plugin/
- Looks like it happens in background but not the other modules because background is a single chunk?

**Comment by fregante** [comment]
I saw what the issue is, webpack is not changing the name property here. The `name` is an instance property, not a static one, so since it's missing, the class name itself is being used by my comparison function.

I'll see if there's any safe way to have the property available both statically and as part of the instance. 

Reopening to track it
