### ISSUE TITLE
Update all usage of the word "recipe"/"blueprint" to "mod" in the codebase

### ISSUE THREAD

**Issue by BLoe** [pixiebrix/pixiebrix-extension#4782]
Here's a rough idea of the scope we're looking at for this:

<img width="651" alt="image" src="https://user-images.githubusercontent.com/2801308/206326839-1a5b7d3a-3829-42aa-8286-64162902cf95.png">

**Comment by twschiller** [comment]
We're doing some naming UX research on "blueprint". So we'll want to hold off on large-scale renaming refactoring until we clarify that

**Comment by BLoe** [comment]
@grahamlangford This can be closed since we're tracking the current renaming work separately, right?
