### ISSUE TITLE
Clean up the implementation/architecture of the document builder live preview

### ISSUE THREAD

**Issue by BLoe** [pixiebrix/pixiebrix-extension#4783]
### Areas of concern
* Code duplication
* Separate of concerns / Coupling

### Running bricks and pipelines from the page editor
* `runRendererBlock()` in `@/contentScript/pageEditor` is only implemented to work with temporary sidebar display bricks

### Generalizing the Document Builder live preview functionality
* We should probably move the `useDocumentPreviewRunBlock()` hook usage outside the `DocumentPreivew` component and lift it up to the `DataPanel`, this will remove some redux coupling from `DocumentPreview`

**Comment by twschiller** [comment]
>  We should probably move the useDocumentPreviewRunBlock() hook usage outside the DocumentPreivew component

Correct, it would also enable live preview of other renderer types
