### ISSUE TITLE
Improve tree shaking ergonomics

### ISSUE THREAD

**Issue by twschiller** [pixiebrix/pixiebrix-extension#480]
**Context**
* Webpack/Typescript should tree shake on production builds since we have the `optimization` section in webpack definied

**Which modules have problems with tree shaking**
* Font awesome?
* react-loaders?

**Discussion Points**
* Certain libraries (e.g., lodash, react-bootstrap) are small enough/we use enough (e.g., multiple imports per module) that the bundle size benefit doesn't make up for the cost to ergonomics

**Relevant eslint plugins/references**
* https://www.npmjs.com/package/eslint-plugin-tree-shaking
* https://stackoverflow.com/questions/63044946/eslint-restrict-imports-from-root-and-enforce-tree-shaking

**Comment by twschiller** [comment]
For the eslint plugin, we may need to submit a request to Codacy to have them add it, if it's not already there: https://github.com/codacy/codacy-eslint/blob/master/package.json

I looked a recent build bundle analysis and it looks like we're still getting the whole import of react-spinners

**Comment by fregante** [comment]
> Let's add lint rules to block the problematic imports. I want to avoid having to manually call out lodash and react-bootrap imports, though. Which imports are the problematic right now? You can see which eslint plugins Codacy support in their package.json: https://github.com/codacy/codacy-eslint. Open a ticket if you need a different one to prevent the problematic imports. Tree shaking ticket is here: https://github.com/pixiebrix/pixiebrix-extension/issues/480

_Originally posted by @twschiller in https://github.com/pixiebrix/pixiebrix-extension/issues/411#issuecomment-864283435_

**Comment by fregante** [comment]
- [ ] `redux-logger` on production builds https://github.com/pixiebrix/pixiebrix-extension/pull/617#issuecomment-869160489

**Comment by fregante** [comment]
I have a feeling that `import 'something'` fundamentally break treeshaking and that this rule is not just a preference/stylistic one: https://github.com/benmosher/eslint-plugin-import/blob/master/docs/rules/no-unassigned-import.md

In short, if you don't specify a specific export, then the bundler is forced to get everything and **potentially** the minifier has a lower ability to trim unused code.

But I may be wrong.

**Comment by twschiller** [comment]
I think the issue is that if packages don't define which modules are side-effect free, Webpack isn't able to do any tree shaking unless they're pure esm packages: https://webpack.js.org/guides/tree-shaking/#mark-the-file-as-side-effect-free

**Comment by fregante** [comment]
https://github.com/pixiebrix/pixiebrix-extension/blob/533af1e00d272c59c669f0c628839f7bc844d7fb/src/blocks/transformers/modal.tsx#L28

Do you think we can replace this style of imports with a "url" import? In short, instead of bundling the whole file in each bundle, we just "import" the URL and we use it as a `<script src="x">`, exactly like we do with the icons. A new `bootstrap.min.css` will appear under `dist/bundles/`

**Comment by twschiller** [comment]
This particular one is interesting, as we need to get it into the Shadow DOM. I'm not sure if we can use script tags within the shadow DOM element. 

It's also a moot point for this component, as we'll need to shift this one over to it's own iframe to get complete style independence (the shadow dom is still affected by the document's root font size, as bootstrap uses rem for sizing)

That being said, for the sidebar, options, etc. we could probably just use the src tag directly? I don't think this will give a big enough win relative to the other improvements impacting code size

**Comment by fregante** [comment]
If you look at the bundles bootstrap comes right after the icons (to which I made some improvements but I haven't verified them yet). Overall they're all small changes but there are several small changes possible. 

The next one is the messaging, that requires a lot of refactoring. 

---

Also my example was incorrect as these are stylesheets so we'd be using `link` not `script` 😅

**Comment by fregante** [comment]
> **Which modules have problems with tree shaking**
> 
> * Font awesome?

This should indeed work but it doesn't: https://github.com/mlwilkerson/react-fontawesome-tree-shaking-demo

I'll have to see why (it could also uncover similar issues for other modules)



> **Relevant eslint plugins/references**
> 
> * [npmjs.com/package/eslint-plugin-tree-shaking](https://www.npmjs.com/package/eslint-plugin-tree-shaking)

Way too many false positives to be useful

```
  ✘  https://google.com/#q=tree-shaking%2Fno-side-effects-in-initialization

     Cannot determine side-effects of calling imported function


     src/utils/renderers.ts:20:19
     18 | import { TemplateEngine } from "@/core";
     19 | import Mustache from "mustache";
   > 20 | import { mapKeys, once } from "lodash";
        |                   ^
     21 | 
     22 | const hyphenRegex = /-/gi;
     23 | 

  ✘  https://google.com/#q=tree-shaking%2Fno-side-effects-in-initialization

     Cannot determine side-effects of calling global function


     src/validators/generic.test.ts:23:1
     21 | import serviceTemplate from "@contrib/templates/service.txt";
     22 | 
   > 23 | test("can validate service", async () => {
        | ^
     24 |   const json = yaml.load(serviceTemplate) as Record<string, unknown>;
     25 |   const result = await validateKind(json, "service");
     26 |   console.log(result.errors);

✘ 557 problems (557 errors, 0 warnings)
```

**Comment by fregante** [comment]
> > **Which modules have problems with tree shaking**
> > 
> > * Font awesome?
> 
> This should indeed work but it doesn't:

Nope, it works! The "stat size" was throwing me off in the report but actually what matters is the parsed size:

<img width="300" alt="Screen Shot 2" src="https://user-images.githubusercontent.com/1402241/131540118-bcac51a6-cc06-4064-b8c5-d4785323795a.png">

I verified

- fort awesome only takes 33K in vendor.js
- unused exports like "book-medical" don't appear in `dist`




```sh
❯ grep -lr "book-medical" dist

❯ grep -lr "book-open" dist
dist/vendors.js

❯ grep -lr "book-reader" dist
dist/vendors.js
```

I'm closing this as resolved. Let me know if anything else is needed. The rest is in:

- #1223 
- #1219
