### ISSUE TITLE
InputValidationError thrown from brick shows success badge

### ISSUE THREAD

**Issue by twschiller** [pixiebrix/pixiebrix-extension#4815]
Steps to Reproduce
---
<img width="1179" alt="image" src="https://user-images.githubusercontent.com/1879821/207151643-b9772c20-5968-4f8d-b504-bf701ef82b23.png">

**Comment by fregante** [comment]
Slightly related:

- https://github.com/pixiebrix/pixiebrix-extension/issues/3573

It's possible that the badge turns green like in that case, but the validation error never reaches the UI to _reset_ it to "failed"

**Comment by twschiller** [comment]
Relevant Code:
- https://github.com/pixiebrix/pixiebrix-extension/blob/05f34322679d425a1d5386311dffa1e2ed3d17c6/src/pageEditor/tabs/editTab/editorNodeLayout/decideStatus.ts#L27-L27
- https://github.com/pixiebrix/pixiebrix-extension/blob/05f34322679d425a1d5386311dffa1e2ed3d17c6/src/analysis/analysisVisitors/traceAnalysis.ts#L73-L73

It looks related to switching over to the analysis framework to instead of using the traces directly for errors.

In my repro, the trace is correct, but there's no error shown because it looks like no error annotation is being added by the `TraceAnalysis`

![image](https://user-images.githubusercontent.com/1879821/210184327-9a98c7f3-cdc8-4902-8c06-4388fb40f819.png)
