### ISSUE TITLE
Tour brick prevents editing field on Salesforce

### ISSUE THREAD

**Issue by twschiller** [pixiebrix/pixiebrix-extension#4833]
Context
---
- https://pixiebrix.slack.com/archives/C0436P48QHY/p1670958248692439
- The Tour Brick has an option of whether or not to prevent interaction. Even when "off" user can't enter values into Salesforce when the field is highlighted by the Tour Brick
- Point of Contact: @mthek10

**Comment by fregante** [comment]
Found out why:

intro.js creates the "spotlight" effect by adding an overlay across the page and then popping out the requested element via `z-index`.

Unfortunately `z-index` isn't global so this only works if the element is _not_ inside a `position`ed element. In this case the form modal has `position: relative` so the element ca never pop above the overlay.

Related issues:

- https://github.com/usablica/intro.js/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+z-index

**Comment by twschiller** [comment]
Closing because the new Tour Step brick is not impacted
