### ISSUE TITLE
Drop Jest snapshots of JSX components in favor of Storybook

### ISSUE THREAD

**Issue by fregante** [pixiebrix/pixiebrix-extension#4852]
From what I understand, thanks to https://github.com/pixiebrix/pixiebrix-extension/pull/4812 we can treat Storybook as "snapshot tests" as well, so basic tests like this one aren't necessary anymore:

https://github.com/pixiebrix/pixiebrix-extension/blob/2e5f652e5a55a852989efd774f4ea1a33563c11b/src/pageEditor/panes/CantModifyPane.test.tsx#L23-L27

However I think Storyshots will only snapshot the default view, so in some cases we'll still need custom tests, like the one that follows the example above.

I haven't checked how common this type of test is, but I just wanted to discuss this.

**Comment by twschiller** [comment]
Closing - it's fine to have both, as smoke tests in tests also serve as basic for adding other more precise assertions
