### ISSUE TITLE
Refactor Modals not to call hooks when they are not visible

### ISSUE THREAD

**Issue by BALEHOK** [pixiebrix/pixiebrix-extension#4854]
We used to render modals conditionally:
```
...
{showModal && <Modal show />}
...
```

This way the code inside `Modal` component is not called unless the Modal is shown. However, the animation on close doesn't work (the component is just removed from the React render tree).

Now we always render the modals and control the visibility via props:
```
...
<Modal show={showModal} />
...
```

This way the animation works as expected, but all the hooks and Redux bindings are always active.

A potential solution would wrapping a modal in component that always render the Bootstrap `Modal` controlling its visibility via `show` prop, and conditionally render the content (name is subject to change).
```
const ModalWrapper = ({show, title, children: body}) => (
  <Modal show={show}>
    <Modal.Header>{title}</Modal.Header>
    {show && body}
  </Modal>
);

...
<ModalWrapper show={showModal}>
  <Modal.Body>{contentFromReduxOrAPI}</Modal.Body>
</ModalWrapper>
...
```

Related issue with always rendered modal: https://github.com/pixiebrix/pixiebrix-extension/pull/4839

**Comment by fregante** [comment]
Yes please!

The suggested solution looks good, the only exception is that once `show` turns false, the body is hidden immediately (while the modal is fading out)

Would [`useDeferredValue`](https://beta.reactjs.org/apis/react/useDeferredValue) avoid that?

Related modal refactorings:

- https://github.com/pixiebrix/pixiebrix-extension/issues/4448
- https://github.com/pixiebrix/pixiebrix-extension/issues/4212

**Comment by fregante** [comment]
Related: 

- https://github.com/pixiebrix/pixiebrix-extension/issues/2754

Maybe that one can be closed
