### ISSUE TITLE
Not found pixiebrix in Chrome Extension Web Store - to install

### ISSUE THREAD

**Issue by TomaxMe** [pixiebrix/pixiebrix-extension#4859]
There is not anymore the pixiebrix extension in Chrome Web Store... so I cannot install it.

**Comment by twschiller** [comment]
Hi @TomaxMe, you can find the extension here: https://chrome.google.com/webstore/detail/pixiebrix/mpjjildhmpddojocokjkgmlkkkfjnepo?hl=en&authuser=0

If you click "Start for Free" at https://www.pixiebrix.com, you also be prompted to install the extension after registering
