### ISSUE TITLE
"This script should only be loaded in a browser extension" in pageScript

### ISSUE THREAD

**Issue by fregante** [pixiebrix/pixiebrix-extension#4869]
This is likely happening via 

1. contentScript/nativeEditor/frameworks
2. contentScript/nativeEditor/selectorInference
3. common.ts
4. contentScript/ready
5. utils/expectContext
6. chrome.ts

<img width="511" alt="Screen Shot 3" src="https://user-images.githubusercontent.com/1402241/209307418-aa86ceb1-10f3-49e6-a225-a5d86a1e7ad4.png">

The fix should be simple but maybe we can also add a webpack fix to ensure `browser-polyfill` either causes the build to break when it appears in pageEditor, or is just omitted there.

**Comment by twschiller** [comment]
@fregante what's the impact of this? The Page Script message handlers won't work?

**Comment by fregante** [comment]
I think that's it since the error is synchronized and I think it stops the execution of all JS
