### ISSUE TITLE
Move page-editor-specific widgets to @/pageEditor

### ISSUE THREAD

**Issue by fregante** [pixiebrix/pixiebrix-extension#4887]
- From https://github.com/pixiebrix/pixiebrix-extension/pull/4728#discussion_r1035957524

> IIRC, SelectorMatchWidget only works in a Page Editor context, because it includes selector fields. Although, it might work in other contexts and just show a plain text field. So it's easiest to assume it should live in the Page Editor subdirectory
> 
> CssClassWidget is also only used in the Page Editor currently. Although, it doesn't depend on any field widgets that are page-editor specific
> 
> Long term, we'd likely have 2 folders:
> - Universal Widgets that work in any context
> - Page Editor-specific widgets that take advantage of the Page Editor context

Related: 

- https://github.com/pixiebrix/pixiebrix-extension/issues/669

**Comment by fregante** [comment]
Also potential improvement in https://github.com/pixiebrix/pixiebrix-extension/pull/4728#discussion_r1035960996

Would it make sense to move `@/contrib/uipath/LocalProcessOptions.tsx` to `@/pageEditor`?

Can we find a (naming?) pattern that helps us maintain safety? i.e. no `eslint-disable` for:

- https://github.com/pixiebrix/pixiebrix-extension/issues/4694

**Comment by BLoe** [comment]
@grahamlangford Not sure how this specific ticket fits into our more general effort around modules and the import lint rules, but should probably be closed in favor of more comprehensive lint-rule/module/folder-structure changes I think?

**Comment by grahamlangford** [comment]
@BLoe considering our Engineering Metrics conversation, this seems like an issue we should pick up as a quick 30% time

**Comment by BLoe** [comment]
Yeah probably worth doing, although this ticket as described might be a huge scope 🤷

**Comment by twschiller** [comment]
I opened two PRs to close out this issue for now:
- https://github.com/pixiebrix/pixiebrix-extension/pull/8629
- https://github.com/pixiebrix/pixiebrix-extension/pull/8628
