### ISSUE TITLE
Refactor `editorSlice` and persisting/syncing the state between apps

### ISSUE THREAD

**Issue by BLoe** [pixiebrix/pixiebrix-extension#4898]
Action items
* What should be persisted? Should opening a new page editor go to the same selected brick/node/data panel tab/etc?
* After fixing the persistence to remove dynamic elements when a recipe in deactivated, check for UiState errors in the page editor related to active element no longer being present
    * We can get to a beta build and figure out if there are things we want to stop persisting for perf/UX reasons
* We need to take a look at how the editorSlice state is being persisted and then accessed/edited in other contexts besides the page editor; the way it's set up right now is messy and error-prone, e.g. the dynamic editing of local storage in `dynamicElementStorage.ts`

Future
* persisting UiState is fine for now to leave it like this
* don't need to touch the install-recipe code in deployments for now

**Comment by twschiller** [comment]
@BLoe 

> The blueprint and all its extensions have been removed.

I think this is a separate issue similar to: https://github.com/pixiebrix/pixiebrix-extension/issues/4830. Basically, the Page Editor doesn't know about what happens on the Blueprint Screen (activation, re-activation, removal)

**Comment by BLoe** [comment]
Oh hmm maybe you're right. I guess I'm not sure what UX problems are caused by this specific issue, "persist only what is needed".

**Comment by corinnemayans** [comment]
We're splitting this issue into:
1. refactor editorSlice (this issue) -- This issue will be just a refactoring issue that can be picked up any time as a 30% time refactoring/bug work item. Therefore, I'm removing the assignee/milestone.
2. UX decision and related implementation on what should/shouldn't be persisted. We will review the persist behavior and get feedback and make a decision about how it needs to change and open a separate issue for that work.
