### ISSUE TITLE
Shared blueprints cannot be exported: `Error exporting blueprint: Already a blueprint. Access in the Workshop`

### ISSUE THREAD

**Issue by fregante** [pixiebrix/pixiebrix-extension#4921]
I know this is intentional, but I'm considering it a bug because:

- a yaml file _could_ be produced just like fr local blueprints
- We're still showing the option and then telling they user they can't do it because it's "already a blueprint", which is unrelated to the requested action

## Repro

1. Install https://www.pixiebrix.com/marketplace/ca72c199-72fb-4871-adce-a19ad251022b/linkedin-comment-templates/
1. Open options page
2. Locate installed blueprint
3. Try to export it
	<img width="294" alt="Screen Shot 2" src="https://user-images.githubusercontent.com/1402241/210163423-26e7623a-a4a8-43a1-8871-aa4954abdcea.png">
3. Receive error
	<img width="388" alt="Screen Shot 1" src="https://user-images.githubusercontent.com/1402241/210163425-ff8fa99d-99e4-4153-a148-8d1f737619a2.png">

## Expectation

4. Click export
5. A .yml file is downloaded

**Comment by fregante** [comment]
I see that it was done in [`35428c1` (#3034)](https://github.com/pixiebrix/pixiebrix-extension/pull/3034/commits/35428c1cfdd24c185bccdac2a399951b8b306a17) due to:

- https://github.com/pixiebrix/pixiebrix-extension/issues/3032

Is this still an issue? Could it be dropped or improved in any way?

https://github.com/pixiebrix/pixiebrix-extension/blob/12526824e041b9c9d2da43f13e97b9113cfc5a54/src/options/pages/blueprints/useInstallableViewItemActions.ts#L245-L247

**Comment by twschiller** [comment]
There's a good chance we'll just remove the "Export Blueprint" action altogether. There's no real use-case for it now that there's a "Make a Copy" option in the Blueprint Editor

As-is, the current behavior is either:
* Frustrating: if you just get a "Access in the Workshop" message, or
* Confusing in what the relationship with Share with Teams and Publish in Marketplace is
