### ISSUE TITLE
Provide "View source" link in Blueprints view (link to "Workshop")

### ISSUE THREAD

**Issue by fregante** [pixiebrix/pixiebrix-extension#4922]
### Intent

1. Open Options page
2. Locate blueprint
3. Try to see its source

### Expectation

There should be a way to see the source in its dropdown

<img width="805" alt="Screen Shot" src="https://user-images.githubusercontent.com/1402241/210163296-4b74f8f2-7f4f-46f4-8cd7-5ac7104befbc.png">

### Actual result

The closest option is to export it, which doesn't even work (but at least it gives a solution)

- https://github.com/pixiebrix/pixiebrix-extension/issues/4921

Finding the source means:

1. Opening the workflow page
2. Search among the sea of unordered blueprints
3. Hopefully end up on `chrome-extension://mpjjildhmpddojocokjkgmlkkkfjnepo/options.html#/workshop/bricks/dee1ffbc-dac4-4b7b-8eb4-4e367b0e1a75`

**Comment by twschiller** [comment]
NOTE: you can only view a blueprint in the workshop if you have edit access for that blueprint (you own the blueprint, or are a developer/admin on the team that owns the blueprint)

**Comment by fregante** [comment]
I wanted to see what brick the blueprint used to display content in the sidebar so that I could build a similar workflow myself. Classic "view source" use case: monkey see, monkey do 🐒
