### ISSUE TITLE
`@pixiebrix/form-modal` doesn't show a close button on the sidebar tab

### ISSUE THREAD

**Issue by fregante** [pixiebrix/pixiebrix-extension#4924]
## Repro

1. Add button to the page
2. Add `@pixiebrix/form-modal` brick
3. Set `location: sidebar`

## Expectation

The tab should show a close button just like `@pixiebrix/display` so that they can be closed at any time.

## Actual result

The form can only be closed via in-page "Cancel" button, so that means you have to select it first and then scroll down to find the button

## Relevant code

https://github.com/pixiebrix/pixiebrix-extension/blob/ba265b428f77f7588ed68393bca539c394e75a62/src/sidebar/Tabs.tsx#L100-L112

## Demo

<img width="405" alt="Screen Shot" src="https://user-images.githubusercontent.com/1402241/210163872-e58a4dc2-27e9-46f4-9823-f764ea8cfd37.png">

**Comment by twschiller** [comment]
Specification note: if we implement this, we should only include the "x" if the form is cancellable
