### ISSUE TITLE
Returning to the blueprints page from another open tab reset the scroll position in the blueprints list

### ISSUE THREAD

**Issue by BLoe** [pixiebrix/pixiebrix-extension#4940]
1. Open blueprints page
2. Scroll down in the blueprints list
3. Open another browser tab alongside
4. Click back to the blueprints page tab

Expected: return to where you were on the blueprints page, since nothing has changed

Result: the blueprints list resets the scroll position to the top after a moment of showing the previous position

**Comment by fregante** [comment]
Possibly due to:

1. The search field receives focus again
2. We have logic to scroll up when a new search is typed

Possible solution:

- only scroll when a new search is typed, not on focus/blur events

**Comment by BLoe** [comment]
This also happens when the page initially loads. If you scroll down fast enough right as the page renders, it will reset to the top after a moment.
