### ISSUE TITLE
Update manifest to allow production Extension to hit the staging app

### ISSUE THREAD

**Issue by johnnymetz** [pixiebrix/pixiebrix-extension#4952]
**Background**

AA needs a staging environment that mimics production to test/demo against: https://www.notion.so/pixiebrix/Stage-Environment-for-AA-1ddb2945fe51473baa9d16bc2d8db785

They will point the production Extension to the staging app (https://app-stg.pixiebrix.com/) via the "PixieBrix URL" advanced setting:

![Screen Shot 2023-01-04 at 11 12 24 AM](https://user-images.githubusercontent.com/20693145/210599226-f12bfd3a-f789-4315-8bec-c5f5a6f47413.png)

In order for this to work, we need to make the staging app externally connectable by updating the Extension manifest file here:

https://github.com/pixiebrix/pixiebrix-extension/blob/f427bbc9bf16274e7863b7330a7c9024d0ee959a/src/manifest.json#L45

**Implementation Notes**

- If we only want to add the staging environment, add `https://app-stg.pixiebrix.com/*` to the array
- If we want to add the staging + development environments, add `https://app-*.pixiebrix.com/*` to the array

**Notes**

- This does NOT require users to accept new permissions, which is ideal because that would be annoying to existing users (see [here](https://pixiebrix.slack.com/archives/C023KL47XV4/p1671154927486989)).
- https://developer.chrome.com/docs/extensions/mv3/manifest/externally_connectable/

**Comment by fregante** [comment]
I think we can make the whole domain externally connectable, I don't see an issue with `*.pixiebrix.com`. This would actually be beneficial once we allow direct communication from the WWW site for example

**Comment by twschiller** [comment]
This needs to go out in the 1.7.16 release

**Comment by johnnymetz** [comment]
@fregante the following patterns threw a `Invalid match pattern` error when I try to [Load unpacked](https://github.com/pixiebrix/pixiebrix-extension/wiki/Loading-the-extension-in-the-browser#manually) locally:

```
*.pixiebrix.com
*.pixiebrix.com/*
https://*.pixiebrix.com
```

So I went with the following pattern:

```
https://*.pixiebrix.com/*
```

However, this doesn't match the website. Let me know if we want that now and I can add that to the array:

```
["https://*.pixiebrix.com/*", "https://pixiebrix.com/*"]
```

**Comment by twschiller** [comment]
> However, this doesn't match the website.

I'm not sure I understand -- why wouldn't `htps://*.pixiebrix.com/*` match the website? Our website has a `www.` subdomain

**Comment by fregante** [comment]
Yeah my suggestion was not to be taken as a literal string to use, I just meant "use * as the subdomain"
