### ISSUE TITLE
Rename "Reset" to "Discard changes" in page editor

### ISSUE THREAD

**Issue by fregante** [pixiebrix/pixiebrix-extension#4956]
Since we moved these actions away from the header, we can now be more descriptive without worrying about their length. From a first look it's not clear whether the "reset" item:

- discards just the changes since the last save
- discards all the changes made to the extension
- discards all the bricks in the extension (full reset?)

<img width="185" alt="Screen Shot" src="https://user-images.githubusercontent.com/1402241/210692818-6e6b638f-92c0-45b1-95bd-3ea645c414eb.png">

Only after clicking it you are given more details about what you just clicked on:

<img width="344" alt="Screen Shot" src="https://user-images.githubusercontent.com/1402241/210692634-ccd5b151-ba56-4e41-8759-16363b2a96b6.png">

**Comment by twschiller** [comment]
Will revisit as part of Page Editor layout overhaul
