### ISSUE TITLE
Consider enforcing await for return values from promises

### ISSUE THREAD

**Issue by twschiller** [pixiebrix/pixiebrix-extension#498]
Context:
* Was removed in previous PR
* Default in IntelliJ is to flag: https://www.jetbrains.com/help/phpstorm/javascript-and-typescript-missing-await-for-an-async-function-call.html. (Rule is enabled by default to allow better V8 stack traces -- see reference at link)
* ESLint needs to be added once we decide/reconfirm which style we want to adopt

**Comment by fregante** [comment]
This is the applicable ESLint rule https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/no-floating-promises.md

**Comment by twschiller** [comment]
Interesting, that documentation doesn't cover the case I'm thinking of. Here's the case I'm referring to:

```js
async random(): Promise<number> {
  return 42;
}

async foo(): Promise<number> {
  // including the await helps V8 show the correct stack frame
  return await random();
}

```

**Comment by twschiller** [comment]
We checked in Chrome via the console and it appears that the await wasn't required to generate a good stack trace. So I'll disable the analysis in IntelliJ
