### ISSUE TITLE
Form UI/UX issues 

### ISSUE THREAD

**Issue by fregante** [pixiebrix/pixiebrix-extension#4994]
There are some small issues we could look into at some point

**Comment by fregante** [comment]
The validation starts too early. In this case it should probably start when the form is submitted or at least after the user empties it.

![no](https://user-images.githubusercontent.com/1402241/211507442-15f7f917-22ba-49f9-8e8d-bca8e266d539.gif)

Testable on https://app.pixiebrix.com/activate?id=@pixies/content-management-demo

**Comment by fregante** [comment]
The PasswordWidget styling is a bit off, the border sometimes appears inside the field, sometimes it doesn't, and the eye icon is always outside it. We need to find a way to position the icon inside the field, where the "info" icon is.

![no](https://user-images.githubusercontent.com/1402241/211509048-c1257672-b3bb-4d3e-bdf6-f1ae0c92df43.gif)


Testable on https://app.pixiebrix.com/activate?id=@pixies/content-management-demo

**Comment by fregante** [comment]
The error banner should not mention `config.` to the user:

<img width="301" alt="Screenshot 5" src="https://user-images.githubusercontent.com/1402241/211543238-00ceb843-3656-470f-9527-9b13a90486c7.png">

**Comment by fregante** [comment]
Related:

- https://github.com/pixiebrix/pixiebrix-extension/issues/5157

**Comment by twschiller** [comment]
> The validation starts too early. In this case it should probably start when the form is submitted or at least after the user empties it.

The current logic is that the error will be show when the user has touched the field. We could potentially only show on dirty and if the form has been submitted. But we should look at this holistically across forms

**Comment by fregante** [comment]
The concept of `user-invalid` should be applied when it becomes higher priority: https://web.dev/articles/user-valid-and-user-invalid-pseudo-classes
