### ISSUE TITLE
Highlight Text Brick: don't highlight text in the head of the document

### ISSUE THREAD

**Issue by twschiller** [pixiebrix/pixiebrix-extension#4996]
Steps to Reproduce
--- 
- Add Highlight Text brick
- Set it to highlight "PixieBrix"
- Visit Admin Console
- Observe that tab title won't show properly because the title has been wrapped in a span

**Comment by fregante** [comment]
A fix for this would be to ensure the roots aren't higher than `body`, for example:

```js
const $root = $(this.querySelector('body') ?? this);
```


While reviewing this brick I also saw this condition which I think is wrong:

https://github.com/pixiebrix/pixiebrix-extension/blob/334cd79e57bec1e2e1fc1634ee02a44788d72048/src/blocks/effects/highlight.ts#L154:L154

By this point, `boolean(condition)` is already confirmed to be always `true` by line 141

**Comment by fregante** [comment]
We do we have two highlight bricks? 🤔 

https://github.com/pixiebrix/pixiebrix-extension/blob/334cd79e57bec1e2e1fc1634ee02a44788d72048/src/blocks/effects/highlightText.ts#L26

https://github.com/pixiebrix/pixiebrix-extension/blob/334cd79e57bec1e2e1fc1634ee02a44788d72048/src/blocks/effects/highlight.ts#L37
