### ISSUE TITLE
Variable autocomplete popover. Merge in traces and show variable values

### ISSUE THREAD

**Issue by BALEHOK** [pixiebrix/pixiebrix-extension#4998]
Spec https://www.notion.so/pixiebrix/Variable-autocomplete-popover-81498f2c34dd40188c558ff7b37caaba#e234911e416041c09e9f2be650bb20ee

Related comment: https://github.com/pixiebrix/pixiebrix-extension/issues/4591#issuecomment-1376592826

**Comment by twschiller** [comment]
These can be done as separate issues/PRs. There are two different but related things here:
- Use the trace to determine available variables
- Show the value from the last run in the popover
