### ISSUE TITLE
Broken snapshots on CI due to unicode character

### ISSUE THREAD

**Issue by twschiller** [pixiebrix/pixiebrix-extension#5010]
It’s a unicode whitespace issue. If you copy-paste into https://www.soscisurvey.de/tools/view-chars.php you’ll see the diff:

![image](https://user-images.githubusercontent.com/1879821/212479401-48b4da69-180e-48ef-9bf4-5bbd1495edc5.png)

That code is for a:

![image](https://user-images.githubusercontent.com/1879821/212479415-548c2487-248a-479f-a651-bec3a54425ab.png)

The differences appear to be in these methods:
- toLocaleTimeString
- toLocaleString

Failure from ParseDate brick:
```
      Object {
        "local": Object {
          "date": "12/9/2021",
    -     "humanReadable": "12/9/2021, 10:00:00 PM",
    +     "humanReadable": "12/9/2021, 10:00:00 PM",
          "iso8601": "2021-12-09T22:00:00.000-05:00",
    -     "time": "10:00:00 PM",
    +     "time": "10:00:00 PM",
        },
        "utc": Object {
          "date": "12/10/2021",
          "epochMillis": 1639105200000,
          "humanReadable": "Fri, 10 Dec 2021 03:00:00 GMT",
          "iso8601": "2021-12-10T03:00:00.000Z",
    -     "time": "3:00:00 AM",
    +     "time": "3:00:00 AM",
        },
      }
```

## Solution

- Pin engine in package.json to `>= 18.13`. Or we could pin to `>= 18, < 18.3`

## Related Tickets
- https://github.com/nodejs/node/issues/45171
- https://github.com/nodejs/node/issues/46123
- https://github.com/nodejs/node/pull/45068

**Comment by fregante** [comment]
Good find! Let's pin to a recent version. It should be as easy as changing the .nvmrc file and ensuring the team is up to date (as well as updating the snapshots)

**Comment by fregante** [comment]
I think GitHub is now consistently pulling 18.13 and every single CI test is consistently failing. For this I updated the snapshots in https://github.com/pixiebrix/pixiebrix-extension/issues/5010 and set the minimum version to 18.13

This can be changed if undesired (ideally not since this is the future anyway) but I made the change to unblock the 10 PRs waiting for this.
