### ISSUE TITLE
useTheme hook imports and initializes Options app store

### ISSUE THREAD

**Issue by BALEHOK** [pixiebrix/pixiebrix-extension#5029]
`useTheme` hook which used in Options and PageEditor imports persistor from Options store, see [useTheme.ts:activateBackgroundTheme](https://github.com/pixiebrix/pixiebrix-extension/blob/main/src/hooks/useTheme.ts#L39) function.
1. This only works as expected in Options app
2. The options store is unnecessary initialized in other apps
3. Makes unit testing harder (Options store has to be mocked in certain tests)

Code ref: https://github.com/pixiebrix/pixiebrix-extension/blob/main/src/hooks/useTheme.ts#L127
The import chain in Page Editor:
`Panel -> PanelContent -> EditorLayout -> Modals -> AddBlockModal -> useGetTheme -> persistor from @/store/optionsStore`

**Comment by twschiller** [comment]
I added a mock to avoid the unit testing issue: https://github.com/pixiebrix/pixiebrix-extension/blob/f97edc1ef96fd9be722a783b8e6aee6e73800d7a/src/testUtils/storePersistorMock.ts#L24-L24

But the other problems described are still problems

This should be using ReduxPersistenceContext to pass receive the passed down persistor function https://github.com/pixiebrix/pixiebrix-extension/blob/f97edc1ef96fd9be722a783b8e6aee6e73800d7a/src/store/ReduxPersistenceContext.ts#L32-L32
