### ISSUE TITLE
Settle on one alert component between `Alert` and `AnalysisAlert`, and then cut over all usages of the base bootstrap `Alert` to use our component that handles the icons automatically based on variant

### ISSUE THREAD

**Issue by BLoe** [pixiebrix/pixiebrix-extension#5040]

**Comment by BALEHOK** [comment]
`[Alert](https://github.com/pixiebrix/pixiebrix-extension/blob/main/src/components/Alert.tsx#L33)` is a generic alert component which is capable of showing an icon and message styled based on variant.
`[AnalysisAlert](https://github.com/pixiebrix/pixiebrix-extension/blob/main/src/components/annotationAlert/AnnotationAlert.tsx#L31)` is a component made specifically to show annotation alerts. It can be modified to use `Alert` under the hood.

If we want to add more functionality related to annotations (annotation action), I think we should keep both components and add the new features to `AnalysisAlert`

**Comment by BLoe** [comment]
Closing this as both are useful, as Aleksandr said above
