### ISSUE TITLE
Review how we deal with a large amount of tabs

### ISSUE THREAD

**Issue by fregante** [pixiebrix/pixiebrix-extension#5041]
With some people hoarding tabs, injection and broadcasting could stall the browser or take several seconds.

Is there anything we can do in this area?

Some thoughts:

- anonymously collect number of tabs
- report back when broadcasts affect more than 20 tabs
- notify user when a run affects a large number of tabs
- stagger broadcasting 
- exclude [discarded tabs](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/tabs/query#discarded)

Some operations that involve opening tabs could also have such limits in place, you wouldn't want to run the blueprint `open every link on a wikipedia page in a new tab`

**Comment by fregante** [comment]
cc @twschiller is there anything actionable here to diagnose the performance issues?

**Comment by fregante** [comment]
I think this compounds with https://github.com/pixiebrix/pixiebrix-extension/issues/6548, especially for users who never restart their computer. Imagine a tab hoarder with 100 tabs open and none of them is connectable. Any broadcasted message will be sent up to 700 times in 10 seconds.

**Comment by twschiller** [comment]
I agree that this is a good issue to keep in mind. The internal users who tend to have performance issues do have a lot of tabs open

However, excess tabs should only impact:
- Memory usage
- Broadcast performance (broadcast isn't common in mods though)

Just having a tab open shouldn't generate background traffic/extra background work utilization if no mods are running on that tab

> I think this compounds with https://github.com/pixiebrix/pixiebrix-extension/issues/6548, especially for users who never restart their computer.

Brainstorming:
- To avoid retries to dead tabs, we could snapshot which tabs were open at the time of install and mark those as do-not message (or only message once) until we see a full navigation event for the tab
- See comment here on pinging for potential liveness: https://github.com/pixiebrix/pixiebrix-extension/issues/6581

**Comment by fregante** [comment]
> ## Brainstorming: by @twschiller 

- Pre-existing tabs access tracked in https://github.com/pixiebrix/pixiebrix-extension/issues/6548
- Discarded tabs were excluded in https://github.com/pixiebrix/webext-messenger/pull/163


> ## Some thoughts: by @fregante 

> anonymously collect number of tabs

I guess not

> report back when broadcasts affect more than 20 tabs

- [ ] I will add `reportEvent('broadcasted to', x, 'tabs')`

> notify user when a run affects a large number of tabs

I don’t think each broadcasted brick should actually add a notification on screen so I'll look into logging maybe?

- [ ] Add warning to Mod "logs", if possible. 

> stagger broadcasting

This might make sense, but I assume it's not necessary. 


I'll try to finalize this issue next week. Let me know if you have reservations.

**Comment by fregante** [comment]
I opened a PR for the first and an issue for the second:

- https://github.com/pixiebrix/pixiebrix-extension/pull/6963
- https://github.com/pixiebrix/pixiebrix-extension/issues/6964
