### ISSUE TITLE
Provide way to reset Page Editor slice state

### ISSUE THREAD

**Issue by twschiller** [pixiebrix/pixiebrix-extension#5055]
Context
---
- We have a Factory Reset button on the Settings Page
- Would also be helpful to have a Reset Page Editor state button
- Workaround is to delete the slice using an extension like Storage Area Explorer

**Comment by fregante** [comment]
Duplicate of https://github.com/pixiebrix/pixiebrix-extension/issues/5280

**Comment by twschiller** [comment]
> Will eventually be caught by strictNullChecks

How would this be caught be strictNullChecks? This DevEx FR is for an FR that clears the persisted Page Editor slice

**Comment by fregante** [comment]
Oh I was looking at a different PR but added the comment here.

- https://github.com/pixiebrix/pixiebrix-extension/issues/5118
