### ISSUE TITLE
`useAutoFocus()` should not default to true

### ISSUE THREAD

**Issue by BLoe** [pixiebrix/pixiebrix-extension#5088]
This causes weird behavior like the `Delay Millis` `NumberWidget` field in a sidebar panel foundation config focusing automatically when you open a sidebar extension in the page editor.

**Comment by fregante** [comment]
> focusing automatically when you open a sidebar extension in the page editor

If it's not meant to be autofocused, why does it call useAutofocus? Having it default to `false` doesn't make sense. It's like saying `focus({yesButReallyFocus: true})` 🤷‍♂️
