### ISSUE TITLE
Error in Rollbar reporting code if Partner JWT user lookup fails

### ISSUE THREAD

**Issue by twschiller** [pixiebrix/pixiebrix-extension#5118]
![image](https://user-images.githubusercontent.com/1879821/215772847-823c13a7-7948-48c7-adf3-1e02e8a0e4c5.png)

**Comment by fregante** [comment]
The code now lives in https://github.com/pixiebrix/pixiebrix-extension/blob/be9cd1788e368dac1e6f68596b7e83e44cc5a865/src/telemetry/telemetryHelpers.ts#L60-L76

Closing as stale anyway for now. Feel free to reopen
