### ISSUE TITLE
Create global mock for RTK query api

### ISSUE THREAD

**Issue by mnholtz** [pixiebrix/pixiebrix-extension#5159]
A lot of dev time writing tests usually involves mocking RTK query hooks: https://github.com/pixiebrix/pixiebrix-extension/pull/5155#issuecomment-1420411575

Ideally, we'd mock RTK query globally or otherwise extract RTK query mocking to allow devs to focus more on writing the tests themselves.

One approach suggested by @BALEHOK:
> I think we can create a global appApi mock and adjust it when needed. also it makes sense to have a shared helper that initializes the auth for a test (a generalized version of mockMeQuery).

**Comment by BLoe** [comment]
@twschiller @mnholtz This is done, correct?

**Comment by twschiller** [comment]
We've switched to mocking at the Axios-level. Closing this out
