### ISSUE TITLE
Problems using Quick Bar on sites that have hot keys

### ISSUE THREAD

**Issue by twschiller** [pixiebrix/pixiebrix-extension#5172]
Context
---
- https://pixiebrix.slack.com/archives/C0436P48QHY/p1676046438601629

Impacted Sites
---
- Zendesk: A and W keys
- GitHub
- Salesforce?

**Comment by brittanyjoiner15** [comment]
- Trello 
- Notion

**Comment by twschiller** [comment]
At least on GitHub, the behavior is that:
- GitHub won't fire hotkeys when the user is typing in a input field or content editable div
- However, we've wrapped our QuickBar in a Shadow DOM to prevent the host page from impacting it's style
- Shadow DOM makes it look like the event.target is the div of the Quick Bar, not the input
