### ISSUE TITLE
Traces in rollbar have origin/host as "undefined"

### ISSUE THREAD

**Issue by twschiller** [pixiebrix/pixiebrix-extension#518]
In production rollbar traces, the origin/host on the filename is `undefined`

![image](https://user-images.githubusercontent.com/1879821/122237262-303dd000-ce8d-11eb-9674-eb0005553607.png)

**Comment by fregante** [comment]
<img width="464" alt="Screen Shot 5" src="https://user-images.githubusercontent.com/1402241/122245114-a3782e00-ceef-11eb-8790-af16ea74cf0f.png">

Weird, the env is not being replaced

**Comment by fregante** [comment]
I know why. Fixing if you don't before
