### ISSUE TITLE
Upgrade to yup 1.0

### ISSUE THREAD

**Issue by twschiller** [pixiebrix/pixiebrix-extension#5192]
Context
---
- Migration guide: https://github.com/jquense/yup/issues/1906
- Need to bump schema-to-yup at the same time

**Comment by fregante** [comment]
`schema-to-yup` will be part of this

Context:
- https://github.com/pixiebrix/pixiebrix-extension/pull/6014#issuecomment-1618748255

**Comment by fregante** [comment]
The stale bot should probably be disabled on `dependency` issues
