### ISSUE TITLE
Cannot complete partner extension install flow

### ISSUE THREAD

**Issue by twschiller** [pixiebrix/pixiebrix-extension#5258]
Context
---
- https://pixiebrix.slack.com/archives/C0436P48QHY/p1677270089559589

**Comment by corinnemayans** [comment]
@twschiller - Is this still an issue?

**Comment by twschiller** [comment]
Let's close for now. Checking with @mthek10 here: https://pixiebrix.slack.com/archives/C042T2TBZ17/p1678757398624139
