### ISSUE TITLE
Google Sheets bug - 403 console errors when switching between sheets in the picker, cannot load tabs/headers

### ISSUE THREAD

**Issue by BLoe** [pixiebrix/pixiebrix-extension#5261]
Exists on `main` + in production, not sure how long this issue has been around.

Steps to reproduce:
* Add a google sheet brick to a pipeline/mod
* Choose a google sheet using the sheet picker input
* Observe that tabs load in
* Select a tab
* Observe that the row header values load in
* Click the sheet picker again and select a _different_ google sheet

Expected results:
* Tab names load in, and row headers load in again for the new sheet

Actual:
* Nothing happens in the UI, old tab names/headers stay in the input form
* Console is spammed with errors:
<img width="1514" alt="image" src="https://user-images.githubusercontent.com/2801308/221652662-8aae0f27-e999-4e84-a82e-a3636afda6d6.png">

**Comment by twschiller** [comment]
@BLoe is this issue relevant anymore?

**Comment by BLoe** [comment]
The app works fine, tab names load correctly when switching sheets. There are still 403 errors in the console though:
<img width="1415" alt="image" src="https://user-images.githubusercontent.com/2801308/229148940-d50fc1ae-a490-49e1-8854-5cee862e12c1.png">

**Comment by corinnemayans** [comment]
@grahamlangford @BLoe -- This might not be relevant anymore?
