### ISSUE TITLE
Add support for Chromatic during CI

### ISSUE THREAD

**Issue by twschiller** [pixiebrix/pixiebrix-extension#5262]
Context
---
- https://www.chromatic.com/ allows for visual regression testing of storybooks

Reference
---
- https://github.com/mswjs/msw-storybook-addon/issues/77

**Comment by BLoe** [comment]
@grahamlangford I'm curious how this relates to Storyshots in Jest? Is this a better option? Something different? We've also started using Rainforest a lot more since this ticket was written.

**Comment by grahamlangford** [comment]
> @grahamlangford I'm curious how this relates to Storyshots in Jest? Is this a better option? Something different? We've also started using Rainforest a lot more since this ticket was written.

@BLoe Chromatic is a full VRT, so it's rather different than Storyshots. It might be worth pursuing later, especially if we start using Storybook more. I would keep this around in the Icebox for now.

**Comment by grahamlangford** [comment]
We're not even fully using Storybook. This would be nice to implement eventually, but not worth keeping around now.

**Comment by twschiller** [comment]
> We're not even fully using Storybook. This would be nice to implement eventually, but not worth keeping around now.

Agree to close for now. Part of the reason we're not fully using Storybook is that the value of maintaining doesn't seem to be there at the moment. Having Chromatic in place would make Storybook more valuable for quality
