### ISSUE TITLE
Allow variables in the TabName input in the google sheets bricks (Append/Lookup)

### ISSUE THREAD

**Issue by BLoe** [pixiebrix/pixiebrix-extension#5265]
Follow up for #5135.

Part of Slice 1 here: https://www.notion.so/Make-Google-Sheets-Work-as-Expected-041e91ede0d04a928d21b7bfe7f3482f

Need to allow field toggle with `Variable` option for the TabName field:
<img width="1044" alt="image" src="https://user-images.githubusercontent.com/2801308/221696266-f713ccc9-0a14-4040-8236-fcc3acc69417.png">

**Comment by twschiller** [comment]
> Need to allow field toggle with Variable option for the TabName field:

If the user provides a variable, the Row Values can just be a generic object field that accepts any property
