### ISSUE TITLE
Configure staging, main, release, and production environments on Rainforest that are test-independent

### ISSUE THREAD

**Issue by mnholtz** [pixiebrix/pixiebrix-extension#5266]
**Context**
Rainforest supports configuring environment variables per environment & easily running tests by selecting an environment before running. 

However, because of the complexity of installing unreleased builds of the extension, it's tricky to write tests that are independent of environment to take advantage of this feature. This makes writing tests difficult, and often results in duplicated tests that are tweaked slightly.

**Implementation sketch**
- Standardize all tests to use a build from S3 (with _perhaps_ the exception of a smoke test for CWS installs)
- Develop a better naming convention for S3 uploads (that perhaps remains consistent for each environment), & store this naming convention in Rainforest env variables per environment
- Create a system for uploading staging, main, release, and production builds of the extension to S3 to keep things up-to-date
- Note: all of these envs (with the exception of staging) can probably point to `app.pixiebrix.com` for now
- Identify any other variables that change for tests (e.g. domain names) & also add this to the configuration

**Comment by alanb43** [comment]
I'm interested in working on anything that helps! How should I prioritize? In my head currently: 

1\. Load testing slice 5 
1\. Cypress for app backend
3\. This?

**Comment by mnholtz** [comment]
Technical spec can be found here:
https://www.notion.so/pixiebrix/Test-Independent-Rainforest-Environments-67a031a2298547e2835dbccf5d35a5a8#0c257df3768b4ac5b0016f98518375ca

I made tickets for this first few slices:
Slice 1: https://github.com/pixiebrix/pixiebrix-app/issues/3158
Slice 2a: https://github.com/pixiebrix/pixiebrix-app/issues/3159
Slice 2b: https://github.com/pixiebrix/pixiebrix-app/issues/3160
Slice 2c: https://github.com/pixiebrix/pixiebrix-app/issues/3161
Slice 3: https://github.com/pixiebrix/pixiebrix-app/issues/3162

cc @alanb43
