### ISSUE TITLE
Create lint rule for RTK Query `useQuery` hook with no parameters

### ISSUE THREAD

**Issue by mnholtz** [pixiebrix/pixiebrix-extension#5273]
See discussion here for context: https://pixiebrix.slack.com/archives/C023KL47XV4/p1677610197731169

We'd like to create a lint rule to enforce passing `undefined` to `useQuery` for endpoints that take options but no parameters.

**Implementation sketch**
- Create a custom eslint plugin: https://eslint.org/docs/latest/extend/plugins
- Create a rule for `useQuery`

**Comment by twschiller** [comment]
> We'd like to create a lint rule to enforce passing undefined to useQuery for endpoints that take options but no parameters.

As opposed to passing "null"

**Comment by BLoe** [comment]
@grahamlangford Might be good to collect all the tickets together about new lint rules. Given the local rule framework I implemented, as well as ChatGPT being good at writing new lint rules, I think someone could probably crank through the list in one DX refactoring sprint.

**Comment by grahamlangford** [comment]
> @grahamlangford Might be good to collect all the tickets together about new lint rules. Given the local rule framework I implemented, as well as ChatGPT being good at writing new lint rules, I think someone could probably crank through the list in one DX refactoring sprint.

I'll create a Lint Rule Updates epic and attach.
