### ISSUE TITLE
Discussion: reconsider `useGetQueryState` vs `useQuery` usage

### ISSUE THREAD

**Issue by mnholtz** [pixiebrix/pixiebrix-extension#5274]
Recently, we learned a little bit about cache behavior with respect to the `useQuery` RTK query hook.

https://pixiebrix.slack.com/archives/C023KL47XV4/p1677610197731169

If caching behavior is understood & used properly, subsequent calls of `useQuery` for the same endpoint should **not** result in subsequent requests, which is an issue we've seen before that was impacting performance. Our solution at the time was to use  `useQueryState` instead of `useQuery`.

However, I see some potential issues with using `useQueryState` instead of `useQuery` for most situations throughout the product:

- It's not clear to me why we should be using `useQueryState` at all if we are correctly using `useQuery` for all endpoints with respect to cache behavior; this adds complexity & confusion.
- [`useQuery` _combines functionality_ of `useQueryState` anyways](https://redux-toolkit.js.org/rtk-query/api/created-api/hooks#:~:text=This%20hook%20combines%20the%20functionality%20of%20both%20useQueryState%20and%20useQuerySubscription%20together%2C%20and%20is%20intended%20to%20be%20used%20in%20the%20majority%20of%20situations.), along with `useQuerySubscription` 
- Unlike `useQuery`, `useQueryState` does **not** add any cache subscriptions, which means that data returned by `useQueryState` could produce unexpected behavior if the original component(s) that call `useQuery` unmount (i.e. if all cache subscriptions are removed)
-  I speculate this could result in missing data/unintended bugs if all subscribers are removed

**Comment by BLoe** [comment]
If we can reliably figure out how to use `useQuery` and get expected cache behavior, I would absolutely support dropping usage of `useQueryState` for all the reasons you said there.

**Comment by mnholtz** [comment]
> If we can reliably figure out how to use useQuery and get expected cache behavior

@BLoe  or @twschiller Do you have other examples in our project where `useQuery` produces unexpected behavior to support my research?

**Comment by BLoe** [comment]
This is the one that comes to mind for me: https://github.com/pixiebrix/pixiebrix-extension/blob/main/src/components/BrickIcon.tsx#L120-L121

**Comment by twschiller** [comment]
> Do you have other examples in our project where useQuery produces unexpected behavior to support my research?

Nothing off the top of my head

**Comment by BLoe** [comment]
We've learned how to use the RTK Query force-fetch options properly now, so I think we have the knowledge at this point to remove all the usages of `useQueryState()` and implement proper options-passing where needed.

_(Caution: https://github.com/pixiebrix/pixiebrix-extension/issues/5273)_

**Comment by mnholtz** [comment]
@BLoe Agreed. We should replace `useGetQueryState` and make sure that nullish parameters passed to `useQuery`s are done consistently/properly.

**Comment by grahamlangford** [comment]
@mnholtz I don't see a reason to create a new issue. We should probably implement the new lint rule before doing this work. Feel free to move both issues into the Backlog.

**Comment by fregante** [comment]
Is this issue resolved/affected by the new lint rule implemented this month? It also mentions caching

- https://github.com/pixiebrix/pixiebrix-extension/pull/7326

**Comment by mnholtz** [comment]
> Is this issue resolved/affected by the new lint rule implemented this month?

It is related but we still have a few places in the codebase where we use `useQueryState` for no good reason.

**Comment by grahamlangford** [comment]
> It is related but we still have a few places in the codebase where we use useQueryState for no good reason.

Right. It handles this goal:

> make sure that nullish parameters passed to useQuerys are done consistently/properly.

**Comment by grahamlangford** [comment]
This has been completed. We also have a lint rule to prevent queryState usage
