### ISSUE TITLE
Open Browser Extension link on markeplace page doesn't open extension console

### ISSUE THREAD

**Issue by twschiller** [pixiebrix/pixiebrix-extension#5301]
Steps to Reproduce
---
- Tested on 1.7.20-beta.2

Discussion
---
- Instead of linking to the app with ?open=1, this should just directly open the extension console
- Currently tries linking to:L `https://app.pixiebrix.com/extension/?open=1`

Screenshot
---
<img width="279" alt="image" src="https://user-images.githubusercontent.com/1879821/223305820-fd46aac3-62a4-469b-8dea-dfdf030c2779.png">

**Comment by fregante** [comment]
Also tracked in:

- https://github.com/pixiebrix/pixiebrix-app/issues/2820
- https://github.com/pixiebrix/pixiebrix-www/issues/937

My suggestion would be to drop the link

**Comment by twschiller** [comment]
> My suggestion would be to drop the link

@mnholtz @grahamlangford I agree we can drop the link. The marketplace isn't as prominent anymore

**Comment by fregante** [comment]
I'd open a Pr but I don't have access to the www repo
