### ISSUE TITLE
Add eslint-plugin-unicorn plugin

### ISSUE THREAD

**Issue by twschiller** [pixiebrix/pixiebrix-extension#536]
I glanced at the ruleset and the rules look pretty good. Codacy also already has support set up for it:

https://github.com/sindresorhus/eslint-plugin-unicorn

Let's give it a try and we can adjust the rules as we go

**Comment by fregante** [comment]
This will take a while to set up and will be done over several PRs (mostly because you might not agree with the opinionated rules so I’d have to send a PR for each)

**Comment by twschiller** [comment]
Does `eslint` have a way to report the number of violation per rule? I think it would make sense to:

1. Enable plugin and recommended rules (and any additional that you like)
2. Run over existing codebase
3. If it looks like the codebase's existing style _intentionally_ disagrees with a rule, disable that rule and post it here for discussion
4. Keep the other rules enabled, and we can discuss as needed if they come up during PR reviews

This will make sure we're moving the codebase in the right direction. 

We can separately decide if for any of the rules we want to fix them across existing code to for consistency/readability

**Comment by fregante** [comment]
> Does `eslint` have a way to report the number of violation per rule?

Not that I could find, but with `jq`, [etc](https://stackoverflow.com/a/4925266/288906):

```
❯ npm run lint --silent -- --format json | jq '.[].messages[].ruleId' | sort| uniq -c |sort -nr
  90 "@typescript-eslint/no-explicit-any"
  54 "security/detect-object-injection"
  41 "@typescript-eslint/ban-types"
  30 "react-hooks/exhaustive-deps"
  20 "@typescript-eslint/explicit-module-boundary-types"
   5 "@typescript-eslint/no-unused-vars"
   4 "security/detect-unsafe-regex"
   1 "security/detect-non-literal-fs-filename"
```

👆 these are the results for my PR #562 at this moment.

**Comment by twschiller** [comment]
Here's my perspective on the controversial ones. Are there any rules you'd want to fix in the code base immediately? Given the breakdown of issues and their criticality, I'm in favor of just cleaning up files we touch as we go

## Go ahead
* `unicorn/explicit-length-check`: agree, it's more readable (and TypeScript will typecheck)

## Introduce in new PRs
* `unicorn/prevent-abbreviations`: agree, but as you'd mention we need to align on a subset of acceptable abbreviations, or where there's strong norms in a library
* `unicorn/prefer-ternary`: I agree with the philosophy of the rule. Let's see how it works in practice. The main place I would disagree is that nested ternary expressions are impossible to read
* `unicorn/catch-error-name`: agree

## Hold Off
* `unicorn/no-null`: let's hold off on this. Figuring out how to enable https://www.typescriptlang.org/tsconfig#strictNullChecks over time would be the most beneficial as with TypeScript most errors we get now nullness error
* `unicorn/filename-case`: would be in favor if we could enforce based on extension. E.g., React components have "tsx" and should have an uppercase name by conventions
* `unicorn/no-array-callback-reference`: the only situation this will prevent is if the methods 2nd parameter is an integer, as TypesScript will block the other situations.

**Comment by fregante** [comment]
> I'm in favor of just cleaning up files we touch as we go

I think the problem with this is organizing the deal would take longer than just ripping off the bandaid.

## If we fix ~~everything~~ _most rules_ now

- we can decide what rule are worth it and which aren't
- it gives me the opportunity to read the codebase and proactively find and fix general issues 

## If we fix as we go

Assuming that that means "enable the rules now, but only see their effects on new PRs," we'll be slowed down later:

- we won't be able to make unrelated changes to affected lines without also being forced to fix the lint errors
- we'll be forced to discuss/disable the rules globally in unrelated PRs

**Comment by fregante** [comment]
There's also this related configuration from Sindre Sorhus, which is quite strict:

- https://github.com/xojs/eslint-config-xo-typescript
- https://github.com/sindresorhus/tsconfig

We could do enable these progressively, like today we work on most of Unicorn, next week we try `config-xo-typescript`, then `tsconfig`

**Comment by fregante** [comment]
> * `unicorn/no-array-callback-reference`: the only situation this will prevent is if the methods 2nd parameter is an integer, as TypesScript will block the other situations.

That's a common misconception that I had until recently: https://jakearchibald.com/2021/function-callback-risks/#typescript-doesnt-solve-this

It seems unnecessary to write `.map(x => foo(a))` instead of `.map(foo)` but it makes sense. It could also be written as `.map(unary(foo))`. We talked about this for `reportError` recently too.
