### ISSUE TITLE
AA end user flow is broken

### ISSUE THREAD

**Issue by johnnymetz** [pixiebrix/pixiebrix-extension#5369]
**Background**

Context: https://pixiebrix.slack.com/archives/C042T2TBZ17/p1679335732880319

Demo: https://www.loom.com/share/c97e864d87c64e1f915c5a18d26a68f3

**Code**

- We're seeing "Required permissions" in the logs - code here: https://github.com/pixiebrix/pixiebrix-extension/blob/cf272f20915c61502d6b225e87a3af9f37b24d1b/src/options/pages/onboarding/partner/ControlRoomOAuthForm.tsx#L131
- Something is breaking shortly after that

**Related PR's**

- https://github.com/pixiebrix/pixiebrix-extension/pull/5115

**Comment by twschiller** [comment]
Appears to a auth config app firewall issue: https://pixiebrix.slack.com/archives/C04UNPP9925/p1679350516078339

**Comment by twschiller** [comment]
Closing, this was fixed via the firewall change
