### ISSUE TITLE
"Update available" warning in Page Editor should take you directly to re-activation flow

### ISSUE THREAD

**Issue by twschiller** [pixiebrix/pixiebrix-extension#5397]
Context
---
- https://pixiebrix.slack.com/archives/C0436P48QHY/p1679664016314509

Correct URL
---
`/marketplace/activate/<modId>?reinstall=1`

**Comment by grahamlangford** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Feature-Board-648b6be80bad0700122cb282/issues/pixiebrix/pixiebrix-extension/5397?planning-poker) with Zenhub @BLoe @johnnymetz @mnholtz @turbochef

**Comment by mnholtz** [comment]
I'm having some trouble finding the component they're discussing in the slack thread. Waiting to see if someone could share a screenshot of the banner so I can find it.

**Comment by twschiller** [comment]
Message is in EditRecipe.tsx: https://github.com/pixiebrix/pixiebrix-extension/blob/66ecd4ad1c131b16479b99c5e922567b27b4c1fa/src/pageEditor/tabs/editRecipeTab/EditRecipe.tsx#L123-L123

**Comment by BLoe** [comment]
I believe this should just be composing the activate link for that href, right? As in, basically a 1LOC change. I would have voted for 1/2-pt if it was an option for story points.

**Comment by twschiller** [comment]
Closing as a dupe of https://github.com/pixiebrix/pixiebrix-extension/issues/8605
