### ISSUE TITLE
#5384 - GSheets Follow up work - clean up service variables, deprecate service integrations

### ISSUE THREAD

**Issue by BLoe** [pixiebrix/pixiebrix-extension#5420]
*This is a follow-up from #5414. We stopped short on that PR in order to cut a beta app build.*

Second half of work for:
- #5384
- #5398

## Remaining work
- Add logic that attempts to clean up GSheets integration from services on the extension when a GSheets brick spreadsheetId field is toggled from @variable to the Sheet Picker, if the service isn't used anywhere else
- Remove GSheets as a service integration option in the Admin Console since it doesn't work
- Add (Deprecated) to the end of the title on the gsheets integration on the Extension Console

**Comment by twschiller** [comment]
> Remove GSheets as a service integration option in the Extension & Admin Consoles

@BLoe see Notion. We're removing it from Admin Console (because it doesn't work there) and adding Deprecated to the name for the Extension Console
