### ISSUE TITLE
RUM not sending performance telemetry from Page Editor

### ISSUE THREAD

**Issue by twschiller** [pixiebrix/pixiebrix-extension#5430]
Context
---
- Tested on 1.7.22-beta.3
- https://www.notion.so/pixiebrix/Release-1-7-22-2ee040a1a7d54d6ab9c18aaf5a35b70a?pvs=4

**Comment by twschiller** [comment]
There are some limitation with running RUM in Browser Extensions: https://github.com/DataDog/browser-sdk/issues/798

From stepping through in the debugger, it appears the test cookie is failing

**Comment by guygrip** [comment]
Hey, this might be helpful - https://eng.grip.security/enabling-chrome-extension-logging-with-datadog-a-journey-of-trial-and-error?utm_source=github

**Comment by twschiller** [comment]
Hi @guygrip - thanks for the link. That's the approach we take with error logging to Rollbar. Did you get that approach to work with Datadog Real User Monitoring?
