### ISSUE TITLE
Modals aren't dismissed when the "Reload page editor" message appears due to changes elsewhere

### ISSUE THREAD

**Issue by BLoe** [pixiebrix/pixiebrix-extension#5441]
Example: https://www.loom.com/share/b8521654bb1e4e749dc8dc12a8feb62c

**Comment by grahamlangford** [comment]
@BLoe can you give more feedback on this? A screenshot or Loom would be helpful.

**Comment by twschiller** [comment]
This could be a quick win. Just need to remove that slice from the persistor

**Comment by grahamlangford** [comment]
Good issue for @fungairino

**Comment by fregante** [comment]
We had a similar issue recently. Here's the small commit that fixed it: [#7465 f7b6abfdd66df635bffc73ea4dc3d045d1836c38](https://github.com/pixiebrix/pixiebrix-extension/pull/7465/commits/f7b6abfdd66df635bffc73ea4dc3d045d1836c38)

The demo is visible in the "Insert menu item ✅⚠️" section in https://github.com/pixiebrix/pixiebrix-extension/pull/7465
