### ISSUE TITLE
Clean up restricted zones warning in code base to enforce separation of concerns

### ISSUE THREAD

**Issue by twschiller** [pixiebrix/pixiebrix-extension#5447]
Context
---
- We have an eslint rule to prevent separation of concerns: https://github.com/pixiebrix/pixiebrix-extension/blob/aa92de40c3e6f19341294aee41b5401301bf831b/.eslintrc.js#L8-L8
- We introduced it to avoid issues importing code in contexts (contentScript, options page, etc.) that is not allowed by the Web Extension API model
- We can also use it to enforce separation of concerns between code modules

Steps to Reproduce
---

```
npm run lint -- --rule '{"import/no-restricted-paths": 2}'
```

Main sources of violations
---
- `@/pageEditor/slices/editorSlice` and related code
- `@/contentScript/elementReference` and related code
- `@/pageScript/framework` and related code
- `@/pageEditor/testHelpers` when used to test components in the context of a Page Editor form state
   - Proposed solution: allow use of  `@/pageEditor/testHelpers` in `.test.tsx` files
- Analysis folder references Page Editor state. Ideally analysis folder is independent. (In future will want to run on server outside of extension context)

**Comment by BLoe** [comment]
Related: #4887
