### ISSUE TITLE
Figure out how to manage both formik errors and analysis annotation on some config fields (GSheets)

### ISSUE THREAD

**Issue by BLoe** [pixiebrix/pixiebrix-extension#5452]
Related to this comment: https://github.com/pixiebrix/pixiebrix-extension/blob/main/src/contrib/google/sheets/LookupSpreadsheetOptions.tsx#L78-L81

**Comment by grahamlangford** [comment]
@BLoe Can you provide more detail? Is this still going to be an issue after the Google Sheets Migration?

**Comment by BLoe** [comment]
I'm going to try and address this issue during my current work, but don't want to get side-tracked if it becomes a rabbit hole. I'll update the ticket here after the gsheets work is done.

**Comment by BLoe** [comment]
@grahamlangford I didn't end up addressing this in the gsheets phase 3 work.

See this comment for a brief explanation of context for this ticket: https://github.com/pixiebrix/pixiebrix-extension/blob/main/src/contrib/google/sheets/ui/AppendSpreadsheetOptions.tsx#L152-L154
