### ISSUE TITLE
Rename `options/pages/marketplace` folder (misleading name)

### ISSUE THREAD

**Issue by twschiller** [pixiebrix/pixiebrix-extension#5474]
Context
---
- "options/pages/marketplace" folder is a holdover to when we didn't have an external marketplace site
- ActivateWizard and related files are are now shared between sidebar and options page
- This ticket is just to rename/split the marketplace folder. But discussion is here about broader approach to splitting things up

Discussion/RFC
---

### Module Organization Approach: organize by vertical slice, organize shared code by concern

- `activation`
   - Common activation wizard hooks and components
- `options` -> rename to `extensionConsole`
   - `pages`
      - `activateExtension` (for starter bricks that aren't part of a mod; in code they are PersistedExtension)
      -  `marketplace` -> `activateRecipe` (will be renamed to `activateMod` in future)
- `sidebar`
   - `activateRecipe`
- `store`: shared cross-cutting data layer code 
   - `extensionsSlice` 
   - `recipesSlice` (move from `@/recipes`)?

### Questions

- Should all/part of `@/recipes` folder be moved under `store`? It's just an abstraction over the local registry in IDB and RTK

Implementation Sketch
---
- Rename "options/pages/marketplace" folder to "options/pages/activateRecipe" (to correspond with activateExtension folder)
- Move files shared between options page and sidebar to "activation/" folder

**Comment by mnholtz** [comment]
As a related note/future work: 

I've been hoping that one day we can combine the "activation wizards" from `activateExtension` and `activateRecipe`, since they use similar logic. The Mod Page is already combining extensions/blueprints actions into an `Installable` concept.

**Comment by twschiller** [comment]
> I've been hoping that one day we can combine the "activation wizards" from activateExtension and activateRecipe

Agree. Would likely look to do that when we revise the Extension Console activation UI
