### ISSUE TITLE
Issue with required permissions calculation for new installs

### ISSUE THREAD

**Issue by corinnemayans** [pixiebrix/pixiebrix-extension#5506]
In the Extension Console activation wizard, it said it couldn’t calculate required permissions because it didn’t know where the @pixies/openai/api brick was. There’s likely a bug in how/where that fetching works on first installs.

Context: https://www.notion.so/pixiebrix/Product-Prioritization-2023-04-10-7d002004b2854403b8518640c704e3d8?pvs=4#bb29cd4f7af043088aa60fcae6207aab

**Comment by twschiller** [comment]
Closing this out - we released a fix for the race in either 1.7.26 or 1.7.27
