### ISSUE TITLE
Fix "Error: This code can only run in the 'extension' context"

### ISSUE THREAD

**Issue by alanb43** [pixiebrix/pixiebrix-extension#5524]
This exception appears in prod (app.pixiebrix.com) as well as when the app project is ran locally. I believe it's originating from the extension, but I could be wrong. This was discovered by the app project's cypress tests auto-failing due to an error being in the console, which is why [this commit](https://github.com/pixiebrix/pixiebrix-app/pull/3296/commits/80d14208117cb805a53236488348e30e8ba20a11) was added to our Cypress support config.

### Prod console output:
![image](https://user-images.githubusercontent.com/22874911/231592273-b2b9e91c-ca7d-426c-9a34-0562a538e16e.png)

### Local console output:
![image](https://user-images.githubusercontent.com/22874911/231591781-7e7b50f1-17b2-4d3a-8a80-d709f09a8eb7.png)

**Comment by twschiller** [comment]
This needs to be fixed in the app project. The syncFlags module needs to be swapped out for another module that can get the flags correctly in the context of the app (see webpack config for other examples of modules that get swapped out)

**Comment by alanb43** [comment]
Closing in favor of new issue in app project
