### ISSUE TITLE
Marketplace activation shows "Finish Activating" when there's nothing to configure

### ISSUE THREAD

**Issue by corinnemayans** [pixiebrix/pixiebrix-extension#5528]
:bug: New Bug Triage Request

Urgency: :large_yellow_circle: Category 2: Priority

Request:
Marketplace activation shows "Finish Activating" when there's nothing to configure

From:
<@U03U71JHFK3>

Impact Details:
Regression

Steps to Reproduce:
<https://www.loom.com/share/14b83fe4da3840709210ef109e20b941|https://www.loom.com/share/14b83fe4da3840709210ef109e20b941>

This mod used to go straight to "success" but now lingers on the screen where mod options are configured but with nothing to configure. After a few seconds, it refreshes to "success" on its own. This impacts other mods as well. 

Additional context: https://pixiebrix.slack.com/archives/C023KL47XV4/p1681393902361689

[Slack Message](https://pixiebrix.slack.com/archives/C0436P48QHY/p1681397222588079?thread_ts=1681397222.588079&cid=C0436P48QHY)

**Comment by twschiller** [comment]
Related Code:
- https://github.com/pixiebrix/pixiebrix-extension/blob/fb902679336a4a84be4e26baef6e2381ec2fa795/src/sidebar/activateRecipe/ActivateRecipePanel.tsx#L79-L79
- https://github.com/pixiebrix/pixiebrix-extension/blob/fb902679336a4a84be4e26baef6e2381ec2fa795/src/utils/includesQuickBarExtensionPoint.ts#L23-L23
