### ISSUE TITLE
Upgrade to Storybook 7

### ISSUE THREAD

**Issue by twschiller** [pixiebrix/pixiebrix-extension#5570]
Context
---
- Blocked: 
  - https://github.com/storybookjs/storybook/issues/22179
  -  Storyshots might not be compatible with Storybook V7: https://github.com/pixiebrix/pixiebrix-extension/blob/105e020084b79b327cf22e1ccfb4d8fa8b0eb929/.storybook/main.js#L36-L36

Implementation Sketch
---
- Upgrade dependencies
- Remove this setting: https://github.com/pixiebrix/pixiebrix-extension/blob/105e020084b79b327cf22e1ccfb4d8fa8b0eb929/.storybook/main.js#L33-L33

Related
---
- https://github.com/pixiebrix/pixiebrix-app/issues/3291

**Comment by grahamlangford** [comment]
Already upgraded to Storybook 7
