### ISSUE TITLE
Exclude/turn off redux logger and devtools in production builds

### ISSUE THREAD

**Issue by twschiller** [pixiebrix/pixiebrix-extension#561]
_Low priority since it only impacts the Options page and Devtools currently_

An opportunity to improve performance and bundle-size slightly in production builds

## Redux Logger

See: https://github.com/LogRocket/redux-logger/issues/6

Locations: 
* http://github.com/pixiebrix/pixiebrix-extension/blob/acc68c02bc706a7e5a7f34c1aa2ff96bf144e185/src/options/store.ts#L67-L67
* http://github.com/pixiebrix/pixiebrix-extension/blob/acc68c02bc706a7e5a7f34c1aa2ff96bf144e185/src/devTools/store.ts#L62-L62

## Redux Devtools

https://redux-toolkit.js.org/api/configureStore#devtools

If we set `devTools: false` will tree-shaking work properly?

**Comment by fregante** [comment]
> If we set `devTools: false` will tree-shaking work properly?

I'd assume that disabling anything dev-related would _improve_ production builds

**Comment by twschiller** [comment]
> I'd assume that disabling anything dev-related would _improve_ production builds

I was just unsure if setting that flag would allow tree shaking to exclude most of the Redux dev tools code. (Not that it's probably that much code). It definitely would at least have runtime performance benefits by not logging
