### ISSUE TITLE
Bug - Quick Bar activation success info shortcut UI is broken on Windows machines

### ISSUE THREAD

**Issue by BLoe** [pixiebrix/pixiebrix-extension#5625]
Context: https://pixiebrix.slack.com/archives/C02CN01JXAA/p1682619653723699

On Windows, the Quick Bar shortcut (string) coming back from the chrome api is `Ctrl+M`, where on MacOS it comes back as just `⌘M`:

<img width="481" alt="image" src="https://user-images.githubusercontent.com/2801308/234963327-6d1f1959-29f2-417e-bfd9-56df80ca9959.png">

**Comment by twschiller** [comment]
Implementation Sketch:
- Add Rainforest Test
- Should ensure correct UI is shown
- Should ensure quick bar can be toggled
