### ISSUE TITLE
Enable Sandbox for template rendering

### ISSUE THREAD

**Issue by twschiller** [pixiebrix/pixiebrix-extension#5676]
Context
---
- https://github.com/pixiebrix/pixiebrix-extension/pull/4972
- Sandbox inject appears to be unreliable/cause issues with contentScript loading (or might be correlated to other problems)

Definition of Done
---
- Nunjucks and Handlebars are evaluated in the sandbox

Related Issues
---
- https://github.com/pixiebrix/pixiebrix-extension/issues/4964

**Comment by fregante** [comment]
I assume this also needs to be covered:

- https://github.com/pixiebrix/pixiebrix-extension/blob/9bddf0d19f15e4fb05f55496007e6190ed582a16/src/bricks/transformers/template.ts#L76

**Comment by twschiller** [comment]
> Is Mustache ok?

I believe so, to my knowledge it doesn't call `eval` or `new Function` under the hood.
