### ISSUE TITLE
Re-enable eslint import plugin

### ISSUE THREAD

**Issue by twschiller** [pixiebrix/pixiebrix-extension#570]
Context: 
* https://github.com/pixiebrix/pixiebrix-extension/pull/562#discussion_r655176511
* https://github.com/benmosher/eslint-plugin-import/issues/1931

```
"plugin:import/errors",   
"plugin:import/warnings",
```

**Comment by fregante** [comment]
I can fix this by the way. Eslint does not need the `fs: false` part in webpack’s config, so I can exclude it from the import:

- quick fix: just delete the property after import
- good fix: further clean/deduplicate config

**Comment by twschiller** [comment]
Would be good to fix, especially as we'll want to use to help with modules with broken tree-shaking. I'd err on the side of the quick fix, but not sure I understand the alternatives

>  exclude it from the import

Which import?

>  further clean/deduplicate config

I'm not sure I follow - what would this involve?

**Comment by fregante** [comment]
> > exclude it from the import
> 
> Which import?

I thought we were `require`ing the webpack file so I thought we could process it first, but instead we just pass a file path to it:

https://github.com/pixiebrix/pixiebrix-extension/blob/b588518a9b109e68346450496ca060bb6bd274ec/.eslintrc#L14

> > further clean/deduplicate config
> 
> I'm not sure I follow - what would this involve?

I haven't looked into the details, but the aliases are defined in 2/3 files (including Jest’s config) so we should merge those while also exporting a eslint-compatible webpack configuration that solves this issue. How exactly I don't know yet.

**Comment by fregante** [comment]
To be clear, this is the problematic object, sorry for being vague: https://github.com/pixiebrix/pixiebrix-extension/blob/b588518a9b109e68346450496ca060bb6bd274ec/browsers/webpack.config.js#L232-L238

ESLint doesn't need this so we can just somehow exclude this specific part from webpack’s config when ESLint imports the file.
