### ISSUE TITLE
Reactivation in the Extension Console hangs and title/caption temporarily changes to "Activate"

### ISSUE THREAD

**Issue by twschiller** [pixiebrix/pixiebrix-extension#5716]
Context
---
- In 1.7.27, the logic changed to determine the title/caption based on if an IExtension from the mod is installed or not
- The reactivation flow uninstalls the IExtensions during reinstall
- The page title and button caption temporarily changes to "Activate" during the reinstall
- Previously we were using the URL to determine if it was a reinstall flow

Discussion
---
- Why is reinstall taking so long?

**Comment by twschiller** [comment]
Additional discussion and demo: https://pixiebrix.slack.com/archives/C0436P48QHY/p1690937204893359

If the user reloads the page, the mod will be uninstalled and they have to activate it

**Comment by twschiller** [comment]
My current theory: some of the messenger calls are hanging due to retries under the hood: https://github.com/pixiebrix/pixiebrix-extension/issues/6206

**Comment by mnholtz** [comment]
It looks like it is likely the messenger calls: https://www.loom.com/share/80ead53c71d3450cad4396bcaf4967a3

**Comment by mnholtz** [comment]
The [`forEachTabAsync`](https://github.com/pixiebrix/pixiebrix-extension/blob/91a9a2ca4fb4022203486995e4f0f15457678f32/src/background/removeExtensionForEveryTab.ts#L12-L12) is taking 6s to run:
<img width="939" alt="Screen Shot 2023-08-07 at 4 53 58 PM" src="https://github.com/pixiebrix/pixiebrix-extension/assets/36575242/d4a01f2c-2bd9-4cce-8517-289b701f16f5">

**Comment by twschiller** [comment]
@mnholtz Try enabling `WEBEXT_MESSENGER_LOGGING=true` so you can see which messages the background tab is sending and if it's having to retry messaging any tab

My current theory is that one of the targets is failing so it's retrying for 6 seconds

**Comment by mnholtz** [comment]
@twschiller Thanks for the tip, trying this now

**Comment by mnholtz** [comment]
You're right todd:
<img width="1499" alt="Screen Shot 2023-08-07 at 5 01 18 PM" src="https://github.com/pixiebrix/pixiebrix-extension/assets/36575242/a6ec30a6-88d6-4f7c-a8c9-a20a2042e279">

**Comment by twschiller** [comment]
@fregante do we have an affordance for turning off or adjusting the number of retries for certain messenger calls? 

@mnholtz `getTabsWithAccess` will be returning a tab that either: 1) PixieBrix isn't actually loaded on, 2) the content script was registered but not loaded (e.g., http urls), 3) the content script was registered, but errored (see discussion thread here: https://github.com/pixiebrix/pixiebrix-extension/issues/6206), etc.

**Comment by fregante** [comment]
> do we have an affordance for turning off or adjusting the number of retries for certain messenger calls?

If delivering a message isn't important, I'd advise using notifications instead, so they are not retried. Retries are only useful if you're actively waiting for a target to become ready, but if you're trying to disable something you probably expect the target to have been ready for a while.

Also `getTabsWithAccess` should be updated to only include tabs that are being altered by PB. PB has access to everything since https://github.com/pixiebrix/pixiebrix-extension/pull/5899 so I'm sure there's some more code that needs to be updated.

**Comment by twschiller** [comment]
> Generally, if a message doesn't have to be delivered (which a lower retry count would suggest), I'd use notifications.

Agree, there might be some rare cases where `await` is used to ensure the order of operations. But I don't think this is one of those cases

**Comment by mnholtz** [comment]
I can confirm that at least the PixieBrix chrome extension tabs are causing issues; the logs I've attached show messages attempting to be sent to the Extension Console activation page:
<img width="1433" alt="Screen Shot 2023-08-08 at 10 56 30 AM" src="https://github.com/pixiebrix/pixiebrix-extension/assets/36575242/92e72387-9e54-4d4b-b6e6-0337f7c06597">

**Comment by mnholtz** [comment]
> I can confirm that at least the PixieBrix chrome extension tabs are causing issues

Interesting, also seeing messenger issues with a regular https tab also:
<img width="1062" alt="Screen Shot 2023-08-08 at 11 10 14 AM" src="https://github.com/pixiebrix/pixiebrix-extension/assets/36575242/c113cd80-1044-440d-a732-8c77afb1c2a6">

**Comment by mnholtz** [comment]
Note (this is a corner case, of course): I'm also seeing this issue for existing tabs with https/http urls after reloading the extension

**Comment by fregante** [comment]
Chrome does not inject the content script into existing tabs after an extension reload. That could be why that tab is not responding

**Comment by mnholtz** [comment]
PR here: https://github.com/pixiebrix/pixiebrix-extension/pull/6239

I'm not 100% sure if converting to a notification will cause issues in, e.g. `uninstallRecipe`, which reactivates the mod for every tab shortly after calling the method
