### ISSUE TITLE
System Notification brick silently fails

### ISSUE THREAD

**Issue by fregante** [pixiebrix/pixiebrix-extension#576]
1. Add button 
2. Add system notification effect with title and message
3. Click the button (in current window or a new dev-tools less window)

![gif](https://user-images.githubusercontent.com/1402241/122880545-4e5f7080-d364-11eb-92c0-9a89a6ea5560.gif)

**Comment by twschiller** [comment]
I think what you're seeing is #586 

There's also an issue to show error notifications as toasts in the dev tools: #533

**Comment by fregante** [comment]
I don’t think either is applicable.

#586 -> the extension has been saved and I'm in a new tab, brick logs still don't appear
#533 -> I don't see errors at all in the tab’s console

<img width="1049" alt="Screen Shot" src="https://user-images.githubusercontent.com/1402241/123018579-04749a00-d3f9-11eb-8e23-8164db164060.png">

Sub-issues:

- I never get asked to add the optional `notifications` permissions
- Since notification failures are silent/invisible (e.g. if the user blocked the notifications at system level, either globally, per browser, or temporarily via Do Not Disturb)

Maybe the brick should have a "Test notification" + "Not seeing any notifications?" buttons.

**Comment by twschiller** [comment]
> I never get asked to add the optional `notifications` permissions

That's a limitation of the Page Editor right now (I just opened https://github.com/pixiebrix/pixiebrix-extension/issues/589). The work around is to save the brick, the grant permissions from the Active Bricks tab in the extension's options page

> Since notification failures are silent/invisible

Agree having at least some documentation here would be helpful. Still thinking through best way to provide: 1) documentation for individual bricks in the page editor, 2) enhancements for built in bricks, like the "Test notification" button
