### ISSUE TITLE
Redirect to Active Mods filter after activating in Extension Console

### ISSUE THREAD

**Issue by twschiller** [pixiebrix/pixiebrix-extension#5785]
Context
---
- >  I think the extension console used to redirect you to the Active Mods filter on the Mods page after you finish activating a Mod, but now you go back to whatever filter you were on before 
- https://pixiebrix.slack.com/archives/C0436P48QHY/p1684274757105929
- Before working on this, confirm expected behavior with @corinnemayans

**Comment by BLoe** [comment]
Here's the behavior I'm talking about: https://www.loom.com/share/d77c09cf72ed45199ce8431dbe3b6dec
