### ISSUE TITLE
Injection improvements

### ISSUE THREAD

**Issue by fregante** [pixiebrix/pixiebrix-extension#579]
A few things we can do to make responses faster:

- [ ] Reduce the content script entry point via `import()` as suggested in https://github.com/pixiebrix/pixiebrix-extension/pull/541#issuecomment-864565818
- [x] Have a single, unified way to "ensure that the content script exists", probably as part of the messaging API. No more explicit injectTemporaryAccess/injectContentScript/isInstalled/waitReady
- [ ] TBD

Related:

- https://github.com/pixiebrix/pixiebrix-extension/issues/428 
- #578

**Comment by fregante** [comment]
One minor issue I found in Firefox:

- [ ] `executeScript` silently fails on meta pages (or maybe others too?)

It's something I noticed [in the sidebar error PR](https://github.com/pixiebrix/pixiebrix-extension/blob/f24c8be18a32de956a38fbf9501827791b28bce1/src/background/browserAction.ts#L44-L54) since I only get a "unable to connect" error instead of "unable to inject"

Related:

- #490 - Firefox compat
- #517 - Sidebar injection error catching

**Comment by fregante** [comment]
https://github.com/pixiebrix/pixiebrix-extension/blob/ef6d152f99fdd3d572b84a3b165649a1498c5b40/src/background/executor.ts#L284

I'm confused about this part of the code. It's marking tabs and frames as "ready" but… what happens when a frame reloads? Don't we lose that _readiness?_ This is never set to _false_ though.

I haven't verified, but this would mean that parts of the extension that depend on this will fail after a reload.

**Comment by twschiller** [comment]
> I haven't verified, but this would mean that parts of the extension that depend on this will fail after a reload.

I think you're correct (I haven't verified either). In practice this executor code is used in a flow where the `@pixiebrix/browser/open-tab` brick is used to open a new tab, and then an action is performed on the URL that is loaded. So it hasn't been a problem

**Comment by twschiller** [comment]
@fregante What do you view as remaining on this ticket? 

We can create a separate issue for: https://github.com/pixiebrix/pixiebrix-extension/issues/579#issuecomment-871558147 that's low priority

**Comment by fregante** [comment]
> We can create a separate issue for: [#579 (comment)](https://github.com/pixiebrix/pixiebrix-extension/issues/579#issuecomment-871558147) that's low priority

Sounds good. What would the action be though? Should that code be dropped?

> @fregante What do you view as remaining on this ticket?

If https://github.com/pixiebrix/pixiebrix-extension/pull/661 eliminated duplicate injection, maybe the first task on this issue isn't necessary anymore.


> [One minor issue I found in Firefox:](https://github.com/pixiebrix/pixiebrix-extension/issues/579#issuecomment-866451242.)

I don't know whether this still applies, I'll extract it if I encounter it again.

---

The next step I wanted to take as part of this was this, but I'll extract this when I hit a problem with it again:

- the lifters/messengers should just attempt to send the message first and then await/inject the content script automatically

---


Closing for now, I'll open more specific issues when found.
