### ISSUE TITLE
Bug: Home panel tab won't retain focus if immediately selected after opening the Sidebar

### ISSUE THREAD

**Issue by mnholtz** [pixiebrix/pixiebrix-extension#5798]
Demo of the bug here: https://www.loom.com/share/154343f6677e446ca2bffcf34a04e40c

Because the Sidebar uses listeners to load Sidebar panels, we are unable to identify when the Sidebar is initially opened whether or not the Home panel should be the default panel. 

To implement a feature where the Home panel is not the default if the user has other Sidebar mods installed, I make the Home panel the initial value by setting it on Sidebar mount: https://github.com/pixiebrix/pixiebrix-extension/blob/053a39f5db00835e0510910c50cbc47d3ce84b1f/src/sidebar/ConnectedSidebar.tsx#L99-L103 and, if the listener receives any `renderPanels` events, I set the active tab to the first default panel available.

However, the `renderPanel` event is triggered three times throughout the first few seconds of the Sidebar being opened, so if a user is to immediately click the Home tab, other tabs will get activated over that.

Demo here showing that the `renderPanel` event is getting triggered 3 times: https://www.loom.com/share/194a98d4b5494899ae3be256d3e9135f

**Comment by twschiller** [comment]
Related: https://github.com/pixiebrix/pixiebrix-extension/issues/5792
