### ISSUE TITLE
File input label doesn't show in custom forms

### ISSUE THREAD

**Issue by twschiller** [pixiebrix/pixiebrix-extension#5871]
Context
---
- https://pixiebrix.slack.com/archives/C0436P48QHY/p1686081686615459
- Likely a bug in the default RJSF Bootstrap template
- Likely something to deal with when upgrading RJSF: https://github.com/pixiebrix/pixiebrix-extension/pull/4913

**Comment by grahamlangford** [comment]
Per @corinnemayans, let's go ahead and fix this if we can ahead of the RJSF5 upgrade. If we cannot make it work, better to remove the label than leave the confusing behavior.

**Comment by fregante** [comment]
It works now, likely thanks to the RJSF5 upgrade.

<img width="628" alt="Screenshot" src="https://github.com/pixiebrix/pixiebrix-extension/assets/1402241/57b483e2-43f3-40ff-9736-79835cbf9428">
