### ISSUE TITLE
Temporary panel doesn't auto-focus if "Show Sidebar" brick used immediately before

### ISSUE THREAD

**Issue by twschiller** [pixiebrix/pixiebrix-extension#5884]
Context
---
- https://pixiebrix.slack.com/archives/C0436P48QHY/p1686058884948299

Steps to Reproduce
---
- Call Show Sidebar brick
- Call Display Temporary Information Brick

Workaround
---
- The "Show Sidebar" brick is redundant, and can be dropped

**Comment by fregante** [comment]
This might eventually be fixed as part of the Sidebar API review/refactor for MV3:

- #7266

**Comment by fregante** [comment]
It looks like the behavior was changed because the Mods tab is now replaced by the temporary information tab

https://github.com/pixiebrix/pixiebrix-extension/assets/1402241/3634a7b8-c93f-4c19-b251-64167e688b0a
