### ISSUE TITLE
Add `ViewError` and `Click` events to Sidebar

### ISSUE THREAD

**Issue by mnholtz** [pixiebrix/pixiebrix-extension#5922]
This feature is a result of https://github.com/pixiebrix/pixiebrix-app/issues/3534

Add the following Mixpanel events to the Sidebar:
- `ViewError` that is reported when an error _view_ is shown to a user (e.g. ErrorBoundry, error toasts, alerts, etc.)
- `Click` events with properties that describe where & what the user clicked on, adding these especially to Activation configuration options & buttons

**Comment by grahamlangford** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Feature-Backlog-648b6be80bad0700122cb282/issues/pixiebrix/pixiebrix-extension/5922?planning-poker) with Zenhub @BLoe @johnnymetz @mnholtz @turbochef
