### ISSUE TITLE
Update Typescript Types

### ISSUE THREAD

**Issue by grahamlangford** [pixiebrix/pixiebrix-extension#5934]
## Background

https://www.notion.so/pixiebrix/Proposal-Domain-Modelling-and-Naming-9f7c8ffc0ed4458599a67536d74bdc3a

## Scope

- Limit scope of work to renaming and deprecating types

**Comment by mnholtz** [comment]
Closing in favor of https://github.com/pixiebrix/pixiebrix-extension/issues/new
