### ISSUE TITLE
node-polyfill-webpack-plugin not working in build?

### ISSUE THREAD

**Issue by twschiller** [pixiebrix/pixiebrix-extension#595]
I think this build is failing because webpack can't find the node polyfill: https://github.com/pixiebrix/pixiebrix-extension/pull/593/checks?check_run_id=2895149088

I rebased the branch, so it should have the latest dependencies. (Also, the build had a npm cache miss, and looks like it did a full package re-install)

What's odd is this is the only PR that seems to have this particular error. Successful builds since: 
- https://github.com/pixiebrix/pixiebrix-extension/pull/594

I've run `npm run watch` successfully on the branch, but have not tried to run the production build

**Comment by fregante** [comment]
It looks like a good old "broken npm install" issue. I deleted node_modules and the lock and reinstalled. It works: https://github.com/pixiebrix/pixiebrix-extension/pull/593

I undid that full lock file rebuild and just run `npm rm node-polyfill-webpack-plugin && npm install -D node-polyfill-webpack-plugin`. Waiting for CI to succeed but it worked locally
