### ISSUE TITLE
Starter Mods not being activated for some users

### ISSUE THREAD

**Issue by twschiller** [pixiebrix/pixiebrix-extension#5962]
Context
---
- https://pixiebrix.slack.com/archives/C0436P48QHY/p1687785556217569
- We're seeing users with PixieBrixRegister, PixieBrixInstall, events but do not get starter mods

Related Code
---
- https://github.com/pixiebrix/pixiebrix-extension/blob/b77f3455ede32d9af2d2b414863a6d73bd4c31af/src/background/messenger/external/api.ts#L77-L77
- https://github.com/pixiebrix/pixiebrix-app/blob/5ebdb8f08fadb457f0bcb3f94d7dd9162ff2e845/pixiebrix-app/src/pages/onboarding/onboardingFlows.tsx#L199-L199

**Comment by mnholtz** [comment]
I think the `starter_blueprints_installed` field on AppUser might be unused now. As part of this ticket, we should double-check that this is the case & remove the field accordingly.

**Comment by twschiller** [comment]
There's also an apparent issue where StarterBrickActivate and ModActivate events are not co-occurring as we'd expect. We either need to update the Mixpanel documentation and/or fix the bug

Hypotheses: if users onboard through the AI Copilot marketplace listing, it won't be installed as starter mod or show the welcome page

**Comment by grahamlangford** [comment]
Notion Doc for [Inject Root Causes](https://www.notion.so/pixiebrix/aa937825d3254377b15294846d90b31e?v=6aadec89cc0e4779be2ba8c615c1a48c)

**Comment by twschiller** [comment]
See chart here: https://pixiebrix.slack.com/archives/C058Z5WF7DZ/p1687971560827599

The user that it failed for, there's no error telemetry in Rollbar. Going to need to double-check why no error is getting reported if starter mods fail to install. (It's possible the messenger calls failed, so it never made it to extension to be reported)
