### ISSUE TITLE
Refactor/move extension factories included in `lifecycle.test.ts`

### ISSUE THREAD

**Issue by mnholtz** [pixiebrix/pixiebrix-extension#5972]
There are two factories included in `lifecycle.test.ts` for generating a trigger extension point, and an extension:
https://github.com/pixiebrix/pixiebrix-extension/blob/feature%2F5937_fix_mod_deployment_updates/src/contentScript/lifecycle.test.ts#L43-L77

The extension point factory id generator seems to be broken (all extension point ids for extension points generated consecutively seem to be `test/extension-point-1` instead of `test/extension-point-1`, `test/extension-point-2` ... `test/extension-point-n`); in addition, passing an `id` override seems to be ineffective.

- [ ] Fix the extension point/extension factories so that iteration/overrides work as expected
- [ ] and move these factories out of the `lifecycle` test into a dedicated factory file

**Comment by grahamlangford** [comment]
Still an issue
