### ISSUE TITLE
Refactor: replace usages of "starterBlueprints" with "starterMods"

### ISSUE THREAD

**Issue by mnholtz** [pixiebrix/pixiebrix-extension#5984]
Follow-up of https://github.com/pixiebrix/pixiebrix-extension/pull/5978

In order to replace all usages of the term `starterBlueprint`, we need to change the background script messenger method [installStarterBlueprints](https://github.com/pixiebrix/pixiebrix-app/blob/5ebdb8f08fadb457f0bcb3f94d7dd9162ff2e845/pixiebrix-app/src/pages/onboarding/onboardingFlows.tsx#L199-L199). This causes a backwards-incompatible change.

We opted to initially not do a partial refactor, i.e. to have a mix of things called `starterBlueprints` and `starterMods`, because we felt that this would make for a better developer experience over all (in terms of e.g. greping for one term or the other).

Options:
- Do the full refactor, which would require two PRs in the extension and app repo, and a check for the right extension version number on the app-side to call the correct method
- Do a partial refactor, preserving the messenger method name `installStarterBlueprints` but renaming everything else

**Comment by mnholtz** [comment]
Considerations:
There has been talk about not using the term `starterMod` anymore at all, and instead using something else that doesn't sound similar to `starterBrick`, e.g. `preInstalledMod`

cc @twschiller

**Comment by twschiller** [comment]
For the sake of moving this work along, let's go with `starterMod` for now

cc @corinnemayans
