### ISSUE TITLE
Google Sheets Integration Slice 2.2: Switch `gapi.client.sheets` calls to use our `proxyService` method for making JSON REST API Calls

### ISSUE THREAD

**Issue by BLoe** [pixiebrix/pixiebrix-extension#5996]
- See calls in [handlers.ts](https://github.com/pixiebrix/pixiebrix-extension/blob/b77f3455ede32d9af2d2b414863a6d73bd4c31af/src/contrib/google/sheets/handlers.ts#L94-L94)
- Update methods to take in a `SanitizedServiceConfiguration` or null
- Swap out `gapi.client.sheets` calls with `proxyService`
- If a `SanitizedServiceConfiguration` is not provided get the token from `ensureSheetsReady` and manually set the header on the request made to pass through the OAuth2 token
~- Drop `SHEETS_DOCS` because we no longer need the API description for the gapi calls (see `onGAPILoadFactory`, etc.)~ (Out of scope, impacts Google File Picker)

**Comment by BLoe** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Feature-Board-648b6be80bad0700122cb282/issues/pixiebrix/pixiebrix-extension/5996?planning-poker) with Zenhub @grahamlangford @johnnymetz @mnholtz @turbochef

**Comment by johnnymetz** [comment]
Looks like this slice is NOT backwards compatible. Deleting the `SHEETS_DOCS` constant breaks the google file picker: https://www.loom.com/share/b06cc7fc6ca44ac69778ba481bf11088

cc @grahamlangford @BLoe
