### ISSUE TITLE
Slice 1.2: Add toggle for “block level” button display in Button’s Layout/Style field

### ISSUE THREAD

**Issue by grahamlangford** [pixiebrix/pixiebrix-extension#6026]
- Bootstrap documentation: https://getbootstrap.com/docs/4.0/components/buttons/#sizes
    - Bootstrap 5 dropped support for btn-block in favor of w-100 or col-12. So we’ll need to migrate if/when we switch to Bootstrap 5 [https://stackoverflow.com/questions/23183343/bootstrap-btn-block-not-working#:~:text=x%2C btn-block is depreciated,12 in the button class.&text=It likely has been removed,be removed in the future](https://stackoverflow.com/questions/23183343/bootstrap-btn-block-not-working#:~:text=x%2C%20btn%2Dblock%20is%20depreciated,12%20in%20the%20button%20class.&text=It%20likely%20has%20been%20removed,be%20removed%20in%20the%20future)
    - Bootstrap also supports widths like w-25 and w-50. w-50 can place buttons side by side, but there’s no way to add spacing between them because adding margin in between makes the total width more than 100%
- For button elements, show a button to toggle `btn-block` mod on the CssWidget
    - Need to determine implementation sketch. Currently no affordance to vary by element type: https://github.com/pixiebrix/pixiebrix-extension/blob/058eb76637a4fe46fa4729938f07bf01a3fdb5e2/src/components/documentBuilder/edit/getElementEditSchemas.ts#L22-L22. Could introduce introduce another format `button-bootstrap-class` (in addition to the current  `bootstrap-class`  format)
- UI considerations
    - TODO: pick an icon but the toggle button
    - TODO: decide if it should be in it’s own button group or added to another group, e.g., add to the border or background color group
    - Discussion: Instead of putting it in Layout/Style, we could add it as a button specific input. However, in general `btn-block` would not be conditionally applied, so there’s no reason in practice to have it as a separate field

**Comment by grahamlangford** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Feature-Board-648b6be80bad0700122cb282/issues/pixiebrix/pixiebrix-extension/6026?planning-poker) with Zenhub @BLoe @johnnymetz @mnholtz @turbochef

**Comment by twschiller** [comment]
@grahamlangford this is already implemented in 1.7.33
