### ISSUE TITLE
Fix FAB overlap on marketplace

### ISSUE THREAD

**Issue by grahamlangford** [pixiebrix/pixiebrix-extension#6030]
- Default FAB placement overlaps `Ask a Question`
- Raise default position of the FAB to be just higher than `Ask a Question`
- Ensure that the z-index is lower than the chat box when it is open

![image.png](https://images.zenhubusercontent.com/648b74d27c8ebbb7d39fe2f5/02084ac2-b9c3-4f6e-a86a-061fca7fb522)

**Comment by grahamlangford** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Feature-Board-648b6be80bad0700122cb282/issues/pixiebrix/pixiebrix-extension/6030?planning-poker) with Zenhub @BLoe @johnnymetz @mnholtz @turbochef

**Comment by turbochef** [comment]
To change this, simply change the styles in `.root` class found [here](https://github.com/pixiebrix/pixiebrix-extension/blob/3447f37fd458730ad626ee89295a03d5d56010fb/src/components/floatingActions/FloatingActions.scss#L19-L25)
