### ISSUE TITLE
Slice 4: Remove button color, text color, border, and hidden settings from the “Layout/Style” options

### ISSUE THREAD

**Issue by grahamlangford** [pixiebrix/pixiebrix-extension#6034]
### Summary of change
- Remove the functionality of editing button color, text color, border, and visibility from the Label Style field.

**Comment by grahamlangford** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Feature-Board-648b6be80bad0700122cb282/issues/pixiebrix/pixiebrix-extension/6034?planning-poker) with Zenhub @BLoe @johnnymetz @mnholtz @turbochef

**Comment by turbochef** [comment]
Where is the label "style" field you're referring to?

**Comment by turbochef** [comment]
Fixed a typo: "Label Style" -> "Layout/Style" 
![image](https://github.com/pixiebrix/pixiebrix-extension/assets/10778363/0aba35c4-a95f-4945-b613-ba407b94c882)
