### ISSUE TITLE
Fix missing web extension mock required by Jest

### ISSUE THREAD

**Issue by twschiller** [pixiebrix/pixiebrix-extension#605]
I'm not sure why this is just becoming an problem now, but this Dependabot PR to update Jest is failing: https://github.com/pixiebrix/pixiebrix-extension/pull/584

I opened in issue in the mock library we use to add the missing method: https://github.com/clarkbw/jest-webextension-mock/issues/141

**Comment by fregante** [comment]
My guess is that something changed in the environment that caused isBackground to be true. Do you want me to send a PR there?

**Comment by twschiller** [comment]
It'd be great if you could look into it. I haven't dug into those tests to know if isBackground should be false for the tests. 

If it should be `false`, let's find the right place to fix the issue. Looking over the build logs again, it looks like there may be 1-2 more other issues, at first glance seem like Jest configuration or mock issues. Jest 27 might have changed some mocking rules

I think the changes to https://github.com/clarkbw/jest-webextension-mock/issues/141 should be pretty straightforward. Would be good to contribute to that project since we've been using it. Even if it ends up not being the root cause of this issue

**Comment by fregante** [comment]
Suspicions were correct. `isBackground` was false before and now it's true, likely because `window` is undefined (false positive due to unexpected environment)

The second part of the issue is an apparent incompatibility in a loader: https://github.com/danwang/yaml-jest/issues/5
