### ISSUE TITLE
Page editor performance issues

### ISSUE THREAD

**Issue by twschiller** [pixiebrix/pixiebrix-extension#606]
There's significant lag on key presses when configuring the action in the page editor. It's likely an issue with unnecessary renders of a component

Reference:
- https://github.com/formium/formik/issues/2268
- https://github.com/welldone-software/why-did-you-render

**Comment by fregante** [comment]
Possible unrelated: One thing I noticed is that the contextMenu is being removed and readded several times as the data changes, if I remember correctly. Or maybe even when page navigates. I suppose it could also affect the performance if not throttled or avoided.

**Comment by twschiller** [comment]
> if not throttled or avoided.

We are debouncing it, but likely need to tweak the debouncing behavior at some point: http://github.com/pixiebrix/pixiebrix-extension/blob/843c86f016cdb052476ada672745e6629043c0a3/src/devTools/editor/panes/EditorPane.tsx#L50-L50

We're also not doing anything smart around which parts of the element we're refreshing/updating. E.g., if you're updating the action and not the caption, we shouldn't need to re-register the context menu with Chrome, we just need to adjust our handler under the hood
