### ISSUE TITLE
Slice 1: Update Account Alias Validation Messaging in Page Editor

### ISSUE THREAD

**Issue by grahamlangford** [pixiebrix/pixiebrix-extension#6081]
## Product Design and Engineering Details
- Updated validation messaging to represent all requirements
  - “Your account alias must start with an @ symbol and consist of lowercase alphanumeric characters and dashes, e.g. @my-account-alias
  ![image.png](https://images.zenhubusercontent.com/648b74d27c8ebbb7d39fe2f5/7f18234f-b0ef-4a06-86a5-7bdd3e227cec)
  
- This update is occurring in the Page Editor → Create New Mod flow 
  ![image.png](https://images.zenhubusercontent.com/648b74d27c8ebbb7d39fe2f5/06a65f81-ae2d-4a58-a60a-c5397054c07f)

- This messaging is similar to the team-scope messaging in the Admin Console, which has the same requirements

- Update second information message
  - “You account” → “Your account”

**Comment by grahamlangford** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Feature-Board-648b6be80bad0700122cb282/issues/pixiebrix/pixiebrix-extension/6081?planning-poker) with Zenhub @BLoe @johnnymetz @mnholtz @turbochef

**Comment by BLoe** [comment]
Can we also fix the padding around the error alert here so it's in line with the info messages above?
