### ISSUE TITLE
[Spike] Create Implementation Slices

### ISSUE THREAD

**Issue by grahamlangford** [pixiebrix/pixiebrix-extension#6094]
[Product Spec](https://www.notion.so/pixiebrix/DocBuild-Brick-Toggle-74069e3308dd4c8f8c028bbc0c965b1a#31e9e1a739894462b57a22c9bec7098c)

- [x] Add Implementation Slices to Notion
- [x] Create Issues for each slice
  - [x] Make sure each issue is added to the [Epic](https://github.com/pixiebrix/pixiebrix-extension#workspaces/feature-board-648b6be80bad0700122cb282/epics/Z2lkOi8vcmFwdG9yL1plbmh1YkVwaWMvMTQzMDE2)
  - [x] Make sure any dependencies/blockers are added to the issues

**Comment by mnholtz** [comment]
First slice GH issue: https://github.com/pixiebrix/pixiebrix-extension/issues/6211

Awaiting feedback on Monday 8/7 to turn the remaining slices into GH issues.

**Comment by mnholtz** [comment]
Tech spec here: https://www.notion.so/pixiebrix/DocBuild-Brick-Toggle-74069e3308dd4c8f8c028bbc0c965b1a

All GH issues have been created.

cc @grahamlangford
