### ISSUE TITLE
"Error initializing contentScript" because the storage is empty

### ISSUE THREAD

**Issue by fregante** [pixiebrix/pixiebrix-extension#610]
I've been seeing this error for a while on https://app.pixiebrix.com/accounts/profile/ , it probably happens on fresh installs because `rawOptions` is `undefined`

```
contentScript.js:203921 Error initializing contentScript SyntaxError: Unexpected token u in JSON at position 0
    at JSON.parse (<anonymous>)
    at loadOptions (contentScript.js:191669)
    at async loadExtensions (contentScript.js:182829)
    at async loadExtensionsOnce (contentScript.js:182861)
    at async handleNavigate (contentScript.js:182899)
    at async init (contentScript.js:203918)
```

On this line:

https://github.com/pixiebrix/pixiebrix-extension/blob/b7151eb9246373977ed80d7ccfc9b628f8eb9a21/src/options/loader.ts#L53

The page seems to load correctly, but I don't see `contentScript ready in 129ms`

**Comment by twschiller** [comment]
This might be the cause of: https://github.com/pixiebrix/pixiebrix-extension/issues/575?

**Comment by twschiller** [comment]
Yep, on fresh installs the Redux persistence layer will have not created that key yet. Submitted a PR to address the issue, will test using web-ext!
