### ISSUE TITLE
Slice 1: Create “Mods” Tab

### ISSUE THREAD

**Issue by grahamlangford** [pixiebrix/pixiebrix-extension#6158]
- Convert the `Home` Tab into the `Mods` Tab as last tab on Sidebar
    - Remains hidden behind `sidebar-home-tab` feature flag
    - Always open to start (will be openable/closable in later slice)
- Update `HomePanel.tsx`, `ActiveModsList.tsx`, and `ActiveModListItem.tsx`
    - Replace home, homePanel, etc. with modLauncher
    - Replace ActiveMods… with AvailableSidebarPanels...
        - update the table to use PanelEntry instead of ModViewItem
        - map over the sidebar panels instead of modViewItems inside the ListGroup
    - Update the `NoActiveModsView` with the updated empty state design in Figma
    - Using the activeMods:
        - Need to find the mods that have sidebar panels on that page
            - For ModDefinitions, can check that the sidebar panels have a panel with a `blueprintId` that is the same as the `modViewItem.mod.id`
            - For ResolvedModComponents, compare sidebar panel `extensionId` to `modViewItem.mod.id`
        - `AvailableSidebarPanelsListItem` needs the PanelEntry and the Mod the PanelEntry is part of
            - The name comes from the PanelEntry heading
            - The logo comes from the Mod
            - Will also need the PanelEntry to derive the eventKey for click events in later slices
    - Remove “Active Mods” heading from list
    - Remove Ellipsis Menu and Grant Permissions buttons from list item
    - Clicking on an ActiveModListItem should focus the relevant tab
        - We will update this functionality to also open closed tabs once we’ve made persistent tabs closable
- Rename `src/sidebar/homePanel` to `src/sidebar/modLauncher`
- Update `ConnectedSidebar.tsx`
    - `showHomePanel` becomes `showModLauncher`
    - remove `permit("marketplace")` check

**Comment by mnholtz** [comment]
> Remove Ellipsis Menu and Grant Permissions buttons from list item

If we're removing "Grant Permissions", does that mean we will **not** show mods in the list that don't have required permissions?
