### ISSUE TITLE
Webpack runtime error loading content script on app.pixiebrix.com during install flow

### ISSUE THREAD

**Issue by twschiller** [pixiebrix/pixiebrix-extension#616]
![image](https://user-images.githubusercontent.com/1879821/123427735-02464300-d593-11eb-9fe4-ac1f93f7601d.png)

**Triage:**
- The "Open Extension Options" button still works, so this error appears to be benign. It also doesn't re-appear on reload

**Reference:**
- https://github.com/crimx/webpack-target-webextension/blob/d3445a43d2065288c302aa7aa1489cb106cb16c1/lib/webpack5/AutoPublicPathRuntimeModule.js#L46
- Our module for setting the extension context: http://github.com/pixiebrix/pixiebrix-extension/blob/8e6b85d1b34d895370f2ebbc87af40214cfbafad/src/extensionContext.ts#L21-L21. This has to appear at the top of the root content script module for Webpack bootstrapping to work properly

**Comment by fregante** [comment]
I haven't checked yet, but the error suggests that this is running outside the extension context. My guess is that's it's being included in script.js. We might have to somehow move `script.js` to its own build (or somehow disable the webext plugin on it)

**Comment by twschiller** [comment]
The thing to double-check would be that there's no code splitting going on with `script.js` (it should be self-contained as-is)

I think this error message is benign, so worth a quick double-check of the above, but otherwise OK to ignore for now

**Comment by fregante** [comment]
On what URL does it happen exactly? I'm not seeing it on:

- "PixieBrix Setup Steps"
- https://app.pixiebrix.com/?install=1

and

- content script dev tools
- background page dev tools

**Comment by fregante** [comment]
> The thing to double-check would be that there's no code splitting going on with `script.js` (it should be self-contained as-is)

Confirmed for `npm run build`:

- no bundles generated when building script.js exclusively 
- no presence of `publicPath` or [`sendMessage`](https://github.com/crimx/webpack-target-webextension/blob/d3445a43d2065288c302aa7aa1489cb106cb16c1/lib/webpack5/LoadScriptRuntimeModule.js#L22) in script.js

**Comment by fregante** [comment]
I saw this too, it's indeed coming from the content script. Repro:

1. Install extension (or "Clear token", sometimes)
2. "Create/link"

<img width="1008" alt="Screen Shot 4" src="https://user-images.githubusercontent.com/1402241/128631222-657b283a-96d1-4096-bab9-c0b0ba6420be.png">

The problem is due to `_reload()` as well, it's a race condition Chrome bug:

1. Page loads
2. Page communicates to background page, requesting reload
3. Content script is injected by manifest.json but its context is already dead, pushing Chrome into a weird state where even `chrome.runtime` is undefined.

---

My guess that it's replicable with:

```js
// content script, via manifest.json
console.log(typeof chrome.runtime)
```
```js
// background
chrome.webNavigation.onDOMContentLoaded.addListener(() => {
	chrome.runtime.reload();
});
```

**Comment by fregante** [comment]
It doesn't seem worth fixing at the moment: It works fine in Firefox and the content script doesn't seem to be used in Chrome. I'd almost argue that we don't need to inject the content script there at all (except for Firefox, and even then it could be extracted into a self-contained externally_connectable polyfill)
