### ISSUE TITLE
Slice 5: Make Form Panels Closable

### ISSUE THREAD

**Issue by grahamlangford** [pixiebrix/pixiebrix-extension#6167]
- Add a `CloseButton` to the forms `TabWithDivider`
    - On click, call `cancelForm` from the messengerApi
- In `src/bricks/transformers/ephemeralForm/EphemeralForm.tsx`, hide the Cancel button if the mode is “sidebar”

**Comment by grahamlangford** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Feature-Board-648b6be80bad0700122cb282/issues/pixiebrix/pixiebrix-extension/6167?planning-poker) with Zenhub @BLoe @johnnymetz @mnholtz @turbochef

**Comment by BLoe** [comment]
Is this ticket impacted at all by this comment? https://www.notion.so/Improvements-to-Mod-Launching-00a77a1177e7434bbda618455fd857b8?d=cd0a818a29544030bb9e67f8ad2192fa&pvs=4#911dfcecaa5b4f119b156a6aa6a636b0

Are there any needed considerations for "forms that can't be closed"? I'm not totally sure what that is referring to.

**Comment by grahamlangford** [comment]
> Is this ticket impacted at all by this comment? https://www.notion.so/Improvements-to-Mod-Launching-00a77a1177e7434bbda618455fd857b8?d=cd0a818a29544030bb9e67f8ad2192fa&pvs=4#911dfcecaa5b4f119b156a6aa6a636b0
> 
> Are there any needed considerations for "forms that can't be closed"? I'm not totally sure what that is referring to.

We're ok there. We currently support marking forms not "closable" in the Page Editor. This was intended for form modals. We may have a follow-on ticket in the future to callout in the Page Editor that all sidebar forms are closable, but we've decided not to worry about that for now.

**Comment by twschiller** [comment]
Additional code references:
- sidebarSlice: need to add closeForm method that calls cancelForm https://github.com/pixiebrix/pixiebrix-extension/blob/f8a866ea4e39594b8342f984adf66a82763f57d2/src/sidebar/sidebarSlice.ts#L139-L139
- See how it's performed with temporary panels: https://github.com/pixiebrix/pixiebrix-extension/blob/f8a866ea4e39594b8342f984adf66a82763f57d2/src/sidebar/Tabs.tsx#L230-L230

**Comment by grahamlangford** [comment]
> Additional code references:
> 
> * sidebarSlice: need to add closeForm method that calls cancelForm https://github.com/pixiebrix/pixiebrix-extension/blob/f8a866ea4e39594b8342f984adf66a82763f57d2/src/sidebar/sidebarSlice.ts#L139-L139
> * See how it's performed with temporary panels: https://github.com/pixiebrix/pixiebrix-extension/blob/f8a866ea4e39594b8342f984adf66a82763f57d2/src/sidebar/Tabs.tsx#L230-L230

Do we need to modify `sidebarSlice`? I thought calling `cancelForm` from `onClosePanel` in `Tabs.tsx` would also remove the form from the redux state?

**Comment by twschiller** [comment]
I don't onClosePanel will -- the two actions it can dispatch (`closeTab` and `removeTemporaryPanel`) wouldn't close a form

**Comment by BLoe** [comment]
I agree with Graham, I think we can just modify the `onClosePanel` function, add a new type checker for `isFormPanelEntry()` in `sidebarTypes.ts`, and then use that checker to add a third branch to the if statement in `onClosePanel` for forms.

I do think, though, that we need to go through and clean up the add/remove/resolve redux actions in sidebar slice. Some, but not all, of them call `*protocol` async functions with `void`, e.g. - [resolveTemporaryPanel()](https://github.com/pixiebrix/pixiebrix-extension/blob/main/src/sidebar/sidebarSlice.ts#L317)

These should probably be extracted to Thunks and could possibly be named more explicitly - for ex. `resolveAndRemoveTemporaryPanel`, `rejectAndRemoveTemporaryPanel`, etc. or something like that.

**Comment by grahamlangford** [comment]
> I agree with Graham, I think we can just modify the `onClosePanel` function, add a new type checker for `isFormPanelEntry()` in `sidebarTypes.ts`, and then use that checker to add a third branch to the if statement in `onClosePanel` for forms.
> 
> I do think, though, that we need to go through and clean up the add/remove/resolve redux actions in sidebar slice. Some, but not all, of them call `*protocol` async functions with `void`, e.g. - [resolveTemporaryPanel()](https://github.com/pixiebrix/pixiebrix-extension/blob/main/src/sidebar/sidebarSlice.ts#L317)
> 
> These should probably be extracted to Thunks and could possibly be named more explicitly - for ex. `resolveAndRemoveTemporaryPanel`, `rejectAndRemoveTemporaryPanel`, etc. or something like that.
> 
> _(Note: A little while ago we did this exact same "cleanup" on the page editor slice, and we probably should also do this cleanup on the extensions slice at some point)_

This is the implementation I was getting at. Dispatching an action that calls `cancelForm` without modifying state doesn't smell right to me. 

Cleaning tup the existing redux actions would be a good DX ticket. Would you mind writing it up @BLoe?

**Comment by BLoe** [comment]
Sure thing, here you go: https://github.com/pixiebrix/pixiebrix-extension/issues/6270
