### ISSUE TITLE
Make sure mods run/open quickly

### ISSUE THREAD

**Issue by grahamlangford** [pixiebrix/pixiebrix-extension#6175]
Context: https://www.notion.so/pixiebrix/Catalog-of-AI-Copilot-Mod-Slowness-Issues-d2a209c895d642b88bd73c4b4db5e6af

- https://pixiebrix.slack.com/archives/C0436P48QHY/p1691424973993799
- https://pixiebrix.slack.com/archives/C0436P48QHY/p1691431865070479

**Comment by twschiller** [comment]
Related Issues
---
- https://github.com/pixiebrix/pixiebrix-extension/issues/2156
- https://github.com/pixiebrix/pixiebrix-extension/issues/4000
