### ISSUE TITLE
Slice 4.3: update requires configuration rule to consider optionality of integration configuration

### ISSUE THREAD

**Issue by grahamlangford** [pixiebrix/pixiebrix-extension#6192]
- https://www.notion.so/pixiebrix/Make-Google-and-Google-Sheets-a-Standard-Integration-efb28821a2b54365a85bcd6981e9c71c?pvs=4#393ccfe81f1d4be28062333ac428db8f

- https://github.com/pixiebrix/pixiebrix-extension/blob/a691d0ac9bcd028c460a57405fd12adb5984eb09/src/sidebar/activateRecipe/RequireMods.tsx#L70-L70

**Comment by mnholtz** [comment]
Just to clarify: we are not requiring user configuration if services are optional?

**Comment by BLoe** [comment]
> Just to clarify: we are not requiring user configuration if services are optional?

Correct
