### ISSUE TITLE
Activate Anywhere NextUrl Race Condition

### ISSUE THREAD

**Issue by grahamlangford** [pixiebrix/pixiebrix-extension#6205]
### Context
- https://app.rainforestqa.com/runs/1468078/tests/395899/browsers/windows10_chrome?job=50954046
- https://app.rainforestqa.com/runs/1466218/tests/395899/browsers/windows10_chrome?job=50933802
- https://pixiebrix.slack.com/archives/C023KL47XV4/p1691064676642039

**Comment by twschiller** [comment]
Context: this occurs when the activation link is pasted into the URL bar and the user has the extension installed already
