### ISSUE TITLE
Show error message if JS fails to load on extensions page

### ISSUE THREAD

**Issue by twschiller** [pixiebrix/pixiebrix-extension#622]
If the JS on the options/sidebar/devtools panel fails to load, it just shows the "Loading..." message that's hard-coded into the HTML page

**Triage:**
* Low priority, in practice should only happen if the build is broken

**Implementation sketch:**
* Add top level error handler to the page (in separate JS file) that shows an error message if the main JS file fails to load. (Or can we use `script.onerror`)

**Considerations:**
* With the above sketch, would have to watch out for top level errors from other places (or does script.onerror solve this?)

**Comment by fregante** [comment]
For the record I had fixed this in https://github.com/pixiebrix/pixiebrix-extension/pull/1219


![gif](https://user-images.githubusercontent.com/1402241/131567994-a99700b0-7699-4272-8fd7-baaf876ff717.gif)
