### ISSUE TITLE
ResizeObserver loop completed with undelivered notifications

### ISSUE THREAD

**Issue by twschiller** [pixiebrix/pixiebrix-extension#6246]
Context
---
- https://app.rollbar.com/a/pixiebrix/fix/item/pixiebrix/3021

Discussion/Triage
---
- The message should be getting filtered already client-side?: https://github.com/pixiebrix/pixiebrix-extension/pull/3284. I thought we had suppressed this error at some point
- Likely not causing business problems
- But is flooding Rollbar with messages
- I think the correct approach here is to 1) see if we're causing it (look through Rollbar), consider suppressing is client-side

Related Code
---
- https://github.com/pixiebrix/pixiebrix-extension/blob/16f0f809091a533357a8e384748c8e225d126527/src/errors/errorHelpers.ts#L53-L53

**Comment by BLoe** [comment]
>The message should be getting filtered already client-side?

We're filtering a different error that sounds related, but it's a different message:
```
const IGNORED_ERROR_PATTERNS = [
  "ResizeObserver loop limit exceeded",
```

Versus "ResizeObserver loop completed with undelivered notifications"
