### ISSUE TITLE
Minor: The save/remove buttons should not wrap

### ISSUE THREAD

**Issue by fregante** [pixiebrix/pixiebrix-extension#626]
<img width="1082" alt="Screen Shot" src="https://user-images.githubusercontent.com/1402241/123534362-e7b4cb00-d746-11eb-928f-87679e7ca530.png">

In smaller windows, the position of the save/reset/remove buttons (below the tab bar) make it seem that they will save/reset the current tab (e.g. the Data tab), but actually they affect the whole brick.

This is more clear when the window actually fits them all:

<img width="1345" alt="Screen Shot 15" src="https://user-images.githubusercontent.com/1402241/123534382-06b35d00-d747-11eb-87bb-61bd962a41bb.png">

They should probably always stay in the corner

**Comment by fregante** [comment]
To expand on my suggested solution: the .nav-item elements should wrap instead. Like:

```
.nav
	.nav-wrapper
		.nav-item
		.nav-item
		.nav-item
	.save
	.reset
	.remove
```

**Comment by twschiller** [comment]
Some other consideration:
- Reset and Remove should potentially be behind a "More..." or ellipses as they are destructive and not the main actions (especially if screen real-estate is tight). Live Support could also go in the "More", especially given that there's not really enough room for the support drawer if page editor has a small width
- In the coming weeks, we're going to be cutting down the number of wizard tabs by simplifying the page editor data model/UX. So there will be probably 2 less tabs in the nav

**Comment by fregante** [comment]
> * So there will be probably 2 less tabs in the nav

- -> https://github.com/pixiebrix/pixiebrix-extension/issues/633

**Comment by twschiller** [comment]
**Related**
- https://github.com/pixiebrix/pixiebrix-extension/issues/919

We still need to think through all the implications - I'll be putting together some balsamiq mockups

**Comment by fregante** [comment]
Fixed?
