### ISSUE TITLE
Google Sheets Slice 3.5.1 - Telemetry Events

### ISSUE THREAD

**Issue by grahamlangford** [pixiebrix/pixiebrix-extension#6267]
### Context
- Add Mixpanel events for the Google Drive integration
[Notion Spec](https://www.notion.so/pixiebrix/Make-Google-and-Google-Sheets-a-Standard-Integration-efb28821a2b54365a85bcd6981e9c71c?pvs=4#a90c9662ee2b477292199decebc2cd39)

Activation Flow
---
- [x] `START` - user started the activation flow for a mod that contains a google drive integration
- [ ] `INTEGRATION_CONFIG_SELECTED` - if there is only one google drive integration option, it was auto-selected, otherwise this means that the user selected an account option from the Integration Config dropdown
    - Event property: user email / account name
- [ ] `LOGIN_START` - user is shown the google login popup
- [ ] `LOGIN_CANCELLED` - user closes the modal before signing in to Google
- [ ] `LOGIN_DENIED_PERMISSIONS` - user clicks Cancel on the permissions request screen
- [ ] `LOGIN_SUCCESS` - user successfully completes google sign in
- [ ] `ALL_SPREADSHEETS_LOADED` - we were able to load all spreadsheets from the user’s drive account and populate the Sheet ID field dropdown with the spreadsheet options
- [ ] `SPREADSHEET_SELECTED` - spreadsheet selected in the `Sheet ID` dropdown field
    - Event properties: `spreadsheetId`, `title`
- [ ] `SPREADSHEET_CLEARED` - user “cleared” the input value for the Sheet ID dropdown field
- [ ] `SUCCESS` - user finishes the activation flow for the mod  
     - Event properties: user email, spreadsheet id, spreadsheet title

Integrations Page
---
- [ ] `SELECTED` - user selects google drive on the add integration modal
- [ ] `ACCOUNT_LOADED` - user signed in successfully on the google sign-in flow, and we were able to load their account in order to label the integration with the email address / account name
    - Event property: user email / account name
- [ ] `DELETED` - user removed/deleted a google drive PKCE integration config from the Integrations page
    - Event property: user email / account name

**Comment by BLoe** [comment]
Blocked temporarily pending PM sync tomorrow
