### ISSUE TITLE
Slice 1: Automatically Trigger Google Auth2 Flow and Create Label Name using Email when clicking “Create New” in configuration picker

### ISSUE THREAD

**Issue by grahamlangford** [pixiebrix/pixiebrix-extension#6269]
### Current behavior:
- When the user clicks “Create New” they are shown a modal with no integration configuration options, but are able to provide a label
- They are prompted to connect authenticate after they click Create in the modal b/c that’s when the configuration is used to fetch the available sheets

### Expected behavior 
- when clicking create new, if the account is an OAuth2 PKCE integration and has no configuration
    - Create a new integration configuration
    - Automatically kick off the OAuth2 PKCE flow
    - Take the `sub` claim from the JWT. If it’s an email address set the label to the email address
        - What’s in the sub claim? Or what claim is the email under for Google JWT?
        - We can hard-code which claim to use for Google for now. In the future, could allow the integration definition say which prop/claim to pull the email from for default label
    - **To decide**: show the modal configuration modal so the user can change the name if they want to?
- **To decide**: what happens if the user authenticates with a different email after clearing the token and being asked to re-authenticate

**Comment by grahamlangford** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Feature-Board-648b6be80bad0700122cb282/issues/pixiebrix/pixiebrix-extension/6269?planning-poker) with Zenhub @BLoe @johnnymetz @mnholtz @turbochef

**Comment by BLoe** [comment]
What should happen if the user aborts/cancels/closes out of the Google OAuth UI flow (i.e. clicks the X in the corner on the Google sign-in modal, or clicks the Cancel button on the permissions prompt after signing in)? Go back to the state where the user has just opened the "Add Integration" modal and sees the list of Integrations? Close the modal? Do we need to show an error alert/message to the user in this case or no?

**Comment by BLoe** [comment]
Interestingly enough, the above error, with the `access_denied` message happens when I click the Cancel button, but if I simply close the sign-in modal, we get a slightly different error message right now:
<img width="1127" alt="image" src="https://github.com/pixiebrix/pixiebrix-extension/assets/2801308/f891d0c9-05f9-487b-bc84-d7c4a5c57817">

**Comment by mnholtz** [comment]
> What should happen if the user aborts/cancels/closes out of the Google OAuth UI flow (i.e. clicks the X in the corner on the Google sign-in modal, or clicks the Cancel button on the permissions prompt after signing in)? 

I second this question

**Comment by BLoe** [comment]
I discussed this with @BrandonPxBx and he's gonna come up with an error message to set as the field level error in these situations

**Comment by BLoe** [comment]
Follow-up: Error handling is moved to separate tickets
