### ISSUE TITLE
Workshop mod error impacting mod activation

### ISSUE THREAD

**Issue by grahamlangford** [pixiebrix/pixiebrix-extension#6276]
### Context
- https://pixiebrix.slack.com/archives/C0436P48QHY/p1692162320908709
- See Slack for steps to reproduce on customer mod

**Comment by twschiller** [comment]
Potentially caused by/related to https://github.com/pixiebrix/pixiebrix-extension/issues/6283?

**Comment by twschiller** [comment]
Potentially related to https://github.com/pixiebrix/pixiebrix-app/issues/4328
