### ISSUE TITLE
Google Sheets Slice 3.5.2 - Handle errors with Google Sign-in flow

### ISSUE THREAD

**Issue by BLoe** [pixiebrix/pixiebrix-extension#6277]
[Notion Spec](https://www.notion.so/pixiebrix/Make-Google-and-Google-Sheets-a-Standard-Integration-efb28821a2b54365a85bcd6981e9c71c?pvs=4#62aa1e0a47b541598238517a71dd8c3a)

**Comment by mnholtz** [comment]
https://www.notion.so/pixiebrix/GSheets-Discussion-283038cee4bc4e06a5dde7c9bc4f8937#db040565c5ce4483ae2bef2b73e56411

**Comment by mnholtz** [comment]
https://www.figma.com/file/RGcBtgkFHIBczxhKPKtaE5/Page-Editor?type=design&node-id=2716-20352&mode=design

**Comment by grahamlangford** [comment]
See: https://github.com/pixiebrix/pixiebrix-extension/issues/6255

**Comment by twschiller** [comment]
Example of what user sees in Page Editor if not signed into Chrome:

<img width="584" alt="image" src="https://github.com/pixiebrix/pixiebrix-extension/assets/1879821/34c2e695-fed0-4703-8fde-ef8c0270ca54">
