### ISSUE TITLE
Automatically Refresh Authentication for MS Azure and other integrations

### ISSUE THREAD

**Issue by grahamlangford** [pixiebrix/pixiebrix-extension#6284]
https://www.notion.so/pixiebrix/Automatically-Refresh-Authentication-for-MS-Azure-and-other-integrations-e20787fe2f794e7aba826e7b794e6bca?pvs=4

**Comment by johnnymetz** [comment]
Helpful Links/Notes:

- https://learn.microsoft.com/en-us/azure/active-directory/develop/v2-oauth2-auth-code-flow
  - https://stackoverflow.com/a/67280275/6611672
- https://learn.microsoft.com/en-us/graph/permissions-reference
- https://learn.microsoft.com/en-us/graph/api/user-list
- https://learn.microsoft.com/en-us/azure/active-directory/develop/access-tokens#token-lifetime

> The default lifetime of an access token is variable. When issued, the Microsoft identity platform assigns a random value ranging between 60-90 minutes (75 minutes on average) as the default lifetime of an access token. The variation improves service resilience by spreading access token demand over a time, which prevents hourly spikes in traffic to Azure AD.



- https://learn.microsoft.com/en-us/azure/active-directory/develop/refresh-tokens

> Refresh tokens have a longer lifetime than access tokens. The default lifetime for the refresh tokens is 24 hours for single page apps and 90 days for all other scenarios. Refresh tokens replace themselves with a fresh token upon every use.

**Comment by johnnymetz** [comment]
Slice 0.1 is done. See the "Azure" postman collection in the "Brick Prototyping" workspace.

Note, there's an additional "Azure AD 2.0 Protocols" collection. This is NOT the one you should use. We pulled that from the Azure docs [here](https://learn.microsoft.com/en-us/azure/active-directory/develop/v2-oauth2-auth-code-flow#protocol-details) and it's not configured correctly for our use case.
