### ISSUE TITLE
Docs typos

### ISSUE THREAD

**Issue by fregante** [pixiebrix/pixiebrix-extension#629]
### https://docs.pixiebrix.com/redfin-google-sheets

- [x] `th\e`
> Hover your mouse over the listing information at the top of the page so **th\e** blue shaded area looks like the image below, and click

- [ ] On the same page page, the screenshot needs to be updated to
<img width="751" alt="Screen Shot" src="https://user-images.githubusercontent.com/1402241/123534216-bab3e880-d745-11eb-8898-6f8f010cb163.png">

- [ ] Step 2 doesn't say what I should do with the data I just found. It should be more clear about this is a "discovery" step just to be ready for the next step. The table makes it look like I should already find that table on the Data tab and fill it in. This piece of information should probably replace/extend the hint just nearby:
<img width="282" alt="Screen Shot 13" src="https://user-images.githubusercontent.com/1402241/123534299-770dae80-d746-11eb-8f2d-4a633fe73496.png">

- [ ] The example paths need to be updated to:
	price: `bannerInfoStore.aboveTheFoldInfo.addressSectionInfo.priceInfo.amount`
	beds: `bannerInfoStore.aboveTheFoldInfo.addressSectionInfo.beds`
	baths: `bannerInfoStore.aboveTheFoldInfo.addressSectionInfo.baths`
	square feet: `bannerInfoStore.aboveTheFoldInfo.addressSectionInfo.sqFt.value`

**Comment by MMirandi** [comment]
@twschiller and @fregante these changes are live: https://docs.pixiebrix.com/redfin-google-sheets
