### ISSUE TITLE
Mod Launcher Rainforest Tests

### ISSUE THREAD

**Issue by grahamlangford** [pixiebrix/pixiebrix-extension#6305]
### Context
- We need to create Rainforest tests for the new Mod Launcher
- Need to differentiate the behavior of the `NoActiveSidebarPanelsView` between regular users and restricted users

### Needed Tests
[ ] Typical ModLauncher Use Cases (should all be in one test):
  - User can close a form, panel, activationPanel, etc. 
  - User can reopen a closed panel using the `Mods` tab
  - Closed panels are persisted when the sidebar is toggled close/open
  - Opening the sidebar when all panels are closed shows the Mod Launcher
  - Opening a sidebar panel when all panels are closed (via QuickBar for example) only opens that panel
  
[ ] Regular users see a link to the Marketplace when they have no active sidebar mods

[ ] Restricted users see the restricted view when they have no active sidebar mods

**Comment by turbochef** [comment]
Going to hold off on this until the mod launcher is activated for all users so rainforest users can see it.
