### ISSUE TITLE
`@pixiebrix/chrome-profile` does not work

### ISSUE THREAD

**Issue by fregante** [pixiebrix/pixiebrix-extension#632]
It's running in the content script, where `chrome.identity` is undefined.

<img width="401" alt="Screen Shot 22" src="https://user-images.githubusercontent.com/1402241/123536454-9b708780-d754-11eb-8e2d-7dd77f858e09.png">

**Comment by fregante** [comment]
Related: the `chromeP.identity.getProfileUserInfo` API returns `{email: "", id: ""}` for me. The Google Sheets integration works correctly.

**Comment by twschiller** [comment]
Triaging as low priority -- in practice people use the `pixiebrix/session` reader which returns the current PixieBrix user
