### ISSUE TITLE
Merge tabs: Name, Foundation, Availability

### ISSUE THREAD

**Issue by fregante** [pixiebrix/pixiebrix-extension#633]
I think that Name and Availability should be merged into a single "Extension point" tab since they're pretty short and describe a single extension:

<img width="681" alt="Screen Shot 26" src="https://user-images.githubusercontent.com/1402241/123537036-b42e6c80-d757-11eb-84e0-b134baa81ba4.png">
<img width="725" alt="Screen Shot 28" src="https://user-images.githubusercontent.com/1402241/123537038-b5f83000-d757-11eb-9c15-edaf0b65d07c.png">

Likewise maybe Foundation could be fit in there since, if I understand correctly, it's:

- constant (every extension has one)
- without sub-categories
- always only one per extension point
- short (only 2 fields)

<img width="694" alt="Screen Shot 27" src="https://user-images.githubusercontent.com/1402241/123537176-50f10a00-d758-11eb-94e7-612b0fe64808.png">

**Comment by twschiller** [comment]
Closing - will be handled by Page Editor overhaul
