### ISSUE TITLE
Scroll for Long Document Builder panel content scrolls entire sidebar

### ISSUE THREAD

**Issue by twschiller** [pixiebrix/pixiebrix-extension#6342]
Steps to Reproduce
---
- Observed in .37-beta.4
- Bug is also present in 1.7.36
- Create a long document in the document builder
- The whole sidebar content scrolls instead of just the panel content

### Context
- https://pixiebrix.slack.com/archives/C05P62XGFUZ/p1693009979561599

**Comment by fregante** [comment]
If I remember correctly the sidebar was also set up with the "full-height" CSS class, which needs its companion "scrollable area" class to enable scrolling within

**Comment by grahamlangford** [comment]
Duplicate of https://github.com/pixiebrix/pixiebrix-extension/issues/7294
