### ISSUE TITLE
Sidebar closing when clicking "Render Panel" in the Page Editor 

### ISSUE THREAD

**Issue by grahamlangford** [pixiebrix/pixiebrix-extension#6363]
### Context
- https://pixiebrix.slack.com/archives/C0436P48QHY/p1693177644512639

### Discussion
- Likely occurring because the panel is the last panel, and clicking "Render Panel" removes/re-adds it

**Comment by mnholtz** [comment]
Would also like to point out that the render panel button is also not opening the Sidebar on the first click in Mark's demo described in the slack thread.
