### ISSUE TITLE
Select selects only show "Loading..."

### ISSUE THREAD

**Issue by johnnymetz** [pixiebrix/pixiebrix-extension#6379]
## Steps to Reproduce

- Create a brick with the "Put data in PixieBrix database" brick
- Notice the following fields only show "Loading...": Key, Database, Value

![Screenshot 2023-09-01 at 12 45 45 PM](https://github.com/pixiebrix/pixiebrix-extension/assets/20693145/d6fb4b10-edb2-4c3e-b7f7-304400e52aa5)

## Expected

The fields should show dropdowns:

![Screenshot 2023-09-01 at 12 42 55 PM](https://github.com/pixiebrix/pixiebrix-extension/assets/20693145/7297632a-02e9-4610-ac2d-b181c014e43f)

## Notes

- The bug may have been introduced in https://github.com/pixiebrix/pixiebrix-extension/pull/6288. I reverted that PR locally and everything looks fine (BUT the bug is flaky so I'm not sure).
- We're only seeing this bug in the following 2 bricks and it only occurs sometimes (looks like the bug may be a race condition):
  - Get data from PixieBrix database
  - Put data in PixieBrix database
- Temporary workaround is to relaunch the Page Editor

**Comment by grahamlangford** [comment]
Discussion Thread: https://pixiebrix.slack.com/archives/C0436P48QHY/p1693587313850619

**Comment by grahamlangford** [comment]
Appears to be related to: https://github.com/pixiebrix/pixiebrix-extension/pull/2270
