### ISSUE TITLE
Authentication with AA not working from IFrame

### ISSUE THREAD

**Issue by twschiller** [pixiebrix/pixiebrix-extension#6414]
Context
---
- Might be related to upcoming 0.30 release, or this week's Chrome release
- We've been unable to reproduce on 0.29 EE (cloud) and CE and Mac or Windows
- https://www.notion.so/pixiebrix/AARI-Team-Sync-f050674a1f444a34827e1772d8e53d8c?pvs=4

**Comment by grahamlangford** [comment]
@twschiller, is this issue safe to close?

**Comment by twschiller** [comment]
We've found the root cause of the issue - it's the experimental Chrome Policy for storage isolation. So it's no longer an inject/blocker

The next steps from our side are to look into that Chrome Policy to see:
- Why it breaks in that scenario: e.g., what origin is our sidebar
- Evaluate if that policy might impact our problems in other ways we should be aware of

**Comment by grahamlangford** [comment]
Will be addressed in #6444
