### ISSUE TITLE
Regression: active mods with deleted definitions don't appear on mod screen so can't be de-activated

### ISSUE THREAD

**Issue by twschiller** [pixiebrix/pixiebrix-extension#6439]
Steps to Reproduce
---
- Tested on 1.7.40-beta.2
- Create a mod
- Delete the mod in the workshop
- Refresh the page

Expected Behavior
---
- Shown on mod screen as a mod definition you no longer have access to so you can remove it

Actual Behavior
---
- Does not show on mods screen

Discussion
---
- Likely a regression on fixed bugs on mod screen
- On the Page Editor, is shows in a perpetual "Loading..." state. However, IIRC that has always been the behavior so it's not a regression

**Comment by grahamlangford** [comment]
@twschiller I'm unable to replicate. I may not be following the steps to reproduce correctly?

<img width="746" alt="image" src="https://github.com/pixiebrix/pixiebrix-extension/assets/30706330/6e25711d-108c-43f7-a189-3f5995a0355c">

<img width="175" alt="image" src="https://github.com/pixiebrix/pixiebrix-extension/assets/30706330/0255e331-f43a-47f0-abf6-9639c75a4db1">

**Comment by twschiller** [comment]
Confirmed I'm not able to replicate it. Created a mod under the team scope and deleted it
