### ISSUE TITLE
Evaluate impact of storage partitioning on sidebar iframes

### ISSUE THREAD

**Issue by twschiller** [pixiebrix/pixiebrix-extension#6444]
Context
---
- https://developer.chrome.com/docs/privacy-sandbox/storage-partitioning/
- https://pixiebrix.slack.com/archives/C042T2TBZ17/p1694648697216719
- In particular, this seems to impact iframes that open windows for authentication. The popup window cannot communicate with the frame in the sidebar

Discussion
---
- There's no timeline on when the feature flag would be enabled default in Chrome
- To test this out:
  - Define a mod that exercises the behavior   
  - We need to add Rainforest QA tests with Chrome flag off/on

**Comment by grahamlangford** [comment]
https://developer.chrome.com/en/blog/storage-partitioning-dev-trial/#how-to-test-storage-partitioning

**Comment by twschiller** [comment]
> https://github.com/wanderview/quota-storage-partitioning/blob/main/explainer.md#interaction-with-extension-pages

@grahamlangford my understanding is that the paragraph applies to the background page. See the comment on it not mattering in MV3 (in MV3 the background page is replaced with a background service worker which can't directly embed an iframe)

**Comment by grahamlangford** [comment]
> > https://github.com/wanderview/quota-storage-partitioning/blob/main/explainer.md#interaction-with-extension-pages
> 
> @grahamlangford my understanding is that the paragraph applies to the background page. See the comment on it not mattering in MV3 (in MV3 the background page is replaced with a background service worker which can't directly embed an iframe)

Wouldn't this still be something we need to consider while we're still on MV2?

**Comment by twschiller** [comment]
> Wouldn't this still be something we need to consider while we're still on MV2?

We add the iframes from the sidebar.js entry point, not from our background worker (background.js)

**Comment by grahamlangford** [comment]
> We add the iframes from the sidebar.js entry point, not from our background worker (background.js)

That makes sense. Thanks for the explanation.

**Comment by fregante** [comment]
> The changes mainly affect APIs that allow the discovery of other contexts via broadcasting or same-origin rendezvous

I don’t think this affects PixieBrix? It's describing this setup:

- example.com -> has Facebook.com iframe
- pixiebrix.com -> has Facebook.com iframe

Both example.com and pixiebrix.com can communicate to the iframes, but Facebook cannot know of other iframes in other tabs.

Given that extensions have their own communication channel via `chrome.runtime`, I don’t think PB is affected.

- iframes with `chrome-extension:` origins are definitely not affected
- iframes with `https:` origins added by PB
	- still have access to `chrome.runtime` in the content script
	- can still use `PostMessageEffect` to the parent and vice versa 

> wanderview/quota-storage-partitioning@`main`/explainer.md#interaction-with-extension-pages

Explanation: background pages in MV2 are actual documents that can create and load their own iframes. PV only uses this feature for the sandbox, as far as I know, so it's not affected.

**Comment by grahamlangford** [comment]
Related to: https://github.com/pixiebrix/pixiebrix-extension/issues/6414

**Comment by grahamlangford** [comment]
This has shown up as a possible issue for a customer (#6414). We need to determine:
* Why it breaks in that scenario: e.g., what origin for frames in our sidebar vs. the popup
* Evaluate if that policy might impact our problems in other ways we should be aware of

**Comment by fregante** [comment]
Can you clarify what "it works"/"it doesn't work" mean in that issue? The iframe document doesn't load? You're unable to login? It doesn't show as logged in?

**Comment by twschiller** [comment]
@fregante our partner's iframe creates a login popup. The two communicate (I believe) via storage. I.e., the frame is waiting for the popup to set a field on the shared storage. Since the storage is now segregated, the iframe doesn't see that field that's set

**Comment by twschiller** [comment]
AA documentation is currently guiding people to disable storage partitioning: https://docs.automationanywhere.com/bundle/enterprise-v2019/page/chrome-storage-partition.html

**Comment by fregante** [comment]
Yess, this is what I meant by:

> it's possible that this change could affect PB users, but they'd be affected regardless of PB 

I suppose they themselves have to fix it eventually.

**Comment by twschiller** [comment]
Closing - our partner is addressing the issue. Currently they instruct users to turn off the feature
