### ISSUE TITLE
JQ brick errors after 2048 calls on a frame

### ISSUE THREAD

**Issue by twschiller** [pixiebrix/pixiebrix-extension#6447]
Context
---
- As of 1.7.40, the error message will be: "Error opening stream, reload the page"
 - https://github.com/fiatjaf/jq-web/issues/18

Discussion
---
- We'll likely need to fork the jq-web project to get the fixed pushed out in a timely manner
- We're working with the impacted customer to reduce the number of jq calls so they have to reload the page less frequently

**Comment by mnholtz** [comment]
Implementation sketch (taken from [this slack thread](https://pixiebrix.slack.com/archives/C05SHRG544C/p1695160333238749)):
- [ ] Fork the jq-web library
- [ ] Remove the 2 suspect lines (see the [jq-web issue write up](https://github.com/fiatjaf/jq-web/issues/18))
- [ ] Publish fork
- [ ] Stress test change in Jest
- [ ] Stress test change in PixieBrix
- [ ] Cut a beta for impacted teams to test
