### ISSUE TITLE
Broken spacing in Page Editor modal forms and object configuration

### ISSUE THREAD

**Issue by twschiller** [pixiebrix/pixiebrix-extension#6453]
Context
---
- Likely a regression caused by https://github.com/pixiebrix/pixiebrix-extension/pull/6442
- Areas impacted in Page Editor
  - Create new mod modal
  - Object configuration
  - Edit Tab for Mod Definitions
- Should also test Integration Configuration modals in Sidebar and Extension Console

**Comment by grahamlangford** [comment]
Fixed in https://github.com/pixiebrix/pixiebrix-extension/issues/6588
