### ISSUE TITLE
Data loss: ModComponents lost when saving in Page Editor

### ISSUE THREAD

**Issue by twschiller** [pixiebrix/pixiebrix-extension#6456]
Context
---
- I am not sure if I'll be able to reproduce the issue, but while working on a client project when I saved it in the Page Editor, it looks like I lost the non-dirty elements in the Mod Definition I was working on
- We need to investigate under what conditions the save operation might drop Mod Components that exist within the mod
- I did seemingly have the original mod I had copied from active, so there might be an issue with extension ids during Make a Copy? (I thought I had deactivated that mod)
- Might also be related to having had used the "Reset" operation. Perhaps the non-dirty mod components were switched back to being in their original mod instead of the new mod

Hypotheses
---
- "Reset" operation has bug when used with a copy from Make a Copy causing them to be detached from mod copy

Discussion
---
- The Mod saving code is messy because we re-assemble ModComponents into a Mod based on their `recipeId` fields

Related Code
--- 
- https://github.com/pixiebrix/pixiebrix-extension/blob/80b362f6a3f869a81b63eb64b0a79919a642e1fc/src/pageEditor/panes/save/saveHelpers.ts#L388-L388

**Comment by twschiller** [comment]
@mthek10 also encountered the bug (or similar bug today): https://pixiebrix.slack.com/archives/C05DW7JE16Y/p1695217372530789?thread_ts=1695217258.083819&cid=C05DW7JE16Y

**Comment by BLoe** [comment]
RE: moving this ticket back to `Next`

@twschiller is going to spend some time trying to reproduce this, we'll move forward on this again depending on results from that investigation.

**Comment by grahamlangford** [comment]
Appears to be happening again: https://pixiebrix.slack.com/archives/C0671QASFMZ/p1707330730450969

**Comment by fregante** [comment]
Could this be related or is it just a UI bug? 

- https://github.com/pixiebrix/pixiebrix-extension/issues/7019

If the `key` is missing, maybe it's because the `id`/`name` of the fields are lost/overwritten as well?

**Comment by twschiller** [comment]
> Appears to be happening again: https://pixiebrix.slack.com/archives/C0671QASFMZ/p1707330730450969

@mthek10 I don't think the case from today involved copying mods? You had just made a change to to a field?

**Comment by twschiller** [comment]
> Could this be related or is it just a UI bug?

I don't think it's related. The saving bug is most likely related to how we track dirty state and try to rebuild the recipe at save time

**Comment by twschiller** [comment]
Discussed with @grahamlangford a good step could be to add invariants to the save code to detect corruption

- The number of entries in the extensionPoints array in the mod definition should match what's being displayed in the Page Editor
- All extensionPoints entry should either reference an inner definition or a registry id for their starter brick
- All inner definitions should be referenced by an extensionPoints entry. (This will be true because innerDefinitions are only used for starter bricks currently). To do this,  I would also consider dropping the excess extensionPoints: https://github.com/pixiebrix/pixiebrix-extension/issues/6529 automatically

**Comment by twschiller** [comment]
Closing for now because we've implemented the invariants. Will re-open on reports of data loss
