### ISSUE TITLE
Extension or starter mod breaks ipynb rendering on GitHub

### ISSUE THREAD

**Issue by twschiller** [pixiebrix/pixiebrix-extension#6487]
Context
---
- Report from user: 
  > I installed your extension to check it out, and then I started having a bug where github would no longer display .ipynb files. Disabling the extension immediately fixed it
- Not clear if this is an issue with a starter mods or the extension itself

**Comment by grahamlangford** [comment]
I've verified that this occurs even when I have no mods or starter bricks activated.

**Comment by twschiller** [comment]
This seems to be working now in 1.8.2-beta.7. Could be memory related? https://github.com/michelucci/Sandbox/blob/master/Logistic%20Regression%20Part%201.ipynb

**Comment by grahamlangford** [comment]
> This seems to be working now in 1.8.2-beta.7. Could be memory related? https://github.com/michelucci/Sandbox/blob/master/Logistic%20Regression%20Part%201.ipynb

Can confirm. I'm closing the issue.
