### ISSUE TITLE
Incremental strictNullChecks adoption - Slice X (add contentScript/messenger/api.ts)

### ISSUE THREAD

**Issue by mnholtz** [pixiebrix/pixiebrix-extension#6526]
Follow-up of https://github.com/pixiebrix/pixiebrix-extension/issues/6498
`contentScript/messenger/api.ts` is being split off because of the 700 ts errors that need to be resolved from adding it

**Comment by grahamlangford** [comment]
We'll keep this one on the back-burner for now. Once other low-hanging fruit have been fixed, we'll try again.

**Comment by grahamlangford** [comment]
As of https://github.com/pixiebrix/pixiebrix-extension/pull/6590, there are still 605 errors that would need to be resolved.

**Comment by grahamlangford** [comment]
Need to remove temporary typing in `src/sidebar/messenger/registration.ts`. See https://github.com/pixiebrix/pixiebrix-extension/pull/6650/files#r1355092186

**Comment by fregante** [comment]
> Need to remove temporary typing in `src/sidebar/messenger/registration.ts`. See [#6650 (files)](https://github.com/pixiebrix/pixiebrix-extension/pull/6650/files#r1355092186)

Yes, once the background messenger files are added.

**Comment by fregante** [comment]
We can unblock many of these files by creating additional entry points for common methods like `recordEvent`, which is imported directly by 60 files:

```diff
- import { recordEvent } from "@/background/messenger/api";
+ import { recordEvent } from "@/background/messenger/api-strict";
or
+ import { recordEvent } from "@/background/strict/messenger/api";
```

This, together with a "strict" registration.ts file, can help migrate more and more common methods to being strict, instead of having to tackle all of the 700 errors in a single PR (or never tackling this at all)

**Comment by grahamlangford** [comment]
> We can unblock many of these files by creating additional entry points for common methods like `recordEvent`, which is imported directly by 60 files:
> 
> ```diff
> - import { recordEvent } from "@/background/messenger/api";
> + import { recordEvent } from "@/background/messenger/api-strict";
> or
> + import { recordEvent } from "@/background/strict/messenger/api";
> ```
> 
> This, together with a "strict" registration.ts file, can help migrate more and more common methods to being strict, instead of having to tackle all of the 700 errors in a single PR (or never tackling this at all)

This sounds like a good approach. 

It is also worth noting that adding the two files now generates 570 errors, so working on other files first is slowly decreasing the overall load here.

**Comment by fregante** [comment]
I started the migration in #7519.

Here's how:

1. Move a method from `registration.ts` to `strict/registration.ts`
2. Fix the type errors that arise, if possible
3. Move the method from `api.ts` to `strict/api.ts` as well.
4. Update the imports and mocks across the extension

In that PR, I just moved the methods that caused 1 or 0 type issues.

**Comment by grahamlangford** [comment]
completed
