### ISSUE TITLE
The options page shows a broken "Revoke additional permission" button

### ISSUE THREAD

**Issue by fregante** [pixiebrix/pixiebrix-extension#6547]
Since host permissions are [no longer optional](https://github.com/pixiebrix/pixiebrix-extension/pull/5899), we should probably not show them in this section.  I considered dropping the section but some current and future bricks can request additional permissions, like `clipboardWrite`.

<img width="588" alt="Screenshot" src="https://github.com/pixiebrix/pixiebrix-extension/assets/1402241/d45e69d4-7324-46d5-aa70-f5fd11dcf7b4">

**Comment by twschiller** [comment]
Thanks for reporting - I believe we should drop the section entirely, as the value in being able to drop `clipboardWrite` is very limited. (The clipboard functionality generally works without having that permission)
