### ISSUE TITLE
The + button in the sidebar does nothing if the Mods tab is the only tab

### ISSUE THREAD

**Issue by fregante** [pixiebrix/pixiebrix-extension#6549]
I don't have any mods installed, could that be why?

https://github.com/pixiebrix/pixiebrix-extension/assets/1402241/8c43487c-3d3e-4bb0-b170-5f06e400c4d9

**Comment by twschiller** [comment]
This is expected behavior. The "+" button 1) opens the Mod Launcher tab if it's not already open, or 2) switches to the Mod Launcher Tab if the tab already exists

@BrandonPxBx we might want to show the plus button as disabled state if the Mod Launcher tab is the only tab visible?

**Comment by fregante** [comment]
> show the plus button as disabled state

The button is already gray, I don’t think it can be made substantially more "disabled"
