### ISSUE TITLE
Future: Move sandbox execution to `ShadowRealms`

### ISSUE THREAD

**Issue by fregante** [pixiebrix/pixiebrix-extension#6580]
The API is in Stage 3: 

- https://github.com/tc39/proposal-shadowrealm/
- https://tc39.es/proposal-shadowrealm/
- https://chromestatus.com/feature/5638053476433920
	- > Implementation status: No active development

Here's an in-depth review of the API:

- https://2ality.com/2022/04/shadow-realms.html

Interestingly, there's a polyfill for the API (but I assume it's node-only):

- https://github.com/leobalter/shadowrealms-polyfill

Most recent updates:

- https://github.com/tc39/proposal-shadowrealm/issues/386#issuecomment-1723927319
- https://github.com/tc39/proposal-shadowrealm/issues/4#issuecomment-1557529314

Related issues for us:

- https://github.com/pixiebrix/pixiebrix-extension/pull/5677
- https://github.com/pixiebrix/pixiebrix-extension/issues/105
- https://github.com/pixiebrix/pixiebrix-extension/issues/5676

**Comment by twschiller** [comment]
Closing for now because it's not available
