### ISSUE TITLE
Mod variable usage false positives in Page Editor

### ISSUE THREAD

**Issue by twschiller** [pixiebrix/pixiebrix-extension#6583]
Context
---
- Mod variables can be referenced as `@mod.foo` directly in text templates/variable expressions
- The Page Editor will warn the mod variable doesn't exist if it hasn't been assigned yet, even though it's known the variable might exist due to usage in bricks
- JS bricks can define a getModVariableSchema method that specifies the mod schema

Steps to Reproduce
---
- Add the "Run with Async Mod Variable" brick with configuration:
  - Mod Variable Name: "foo"
- Add a Window Alert Brick with configuration
  - Alert Message: `{{ @mod.foo }}!`, or `{{ @mod.foo.data }}!`

Expected Behavior:
- The Page Editor does not warn, because it knows that `@mod.foo` it knows the `WithAsyncModVariable` is PageStateAware and has a dynamic PageStateSchema declared via `getModVariableSchema`
- NOTE: the warning should also not show if the `Window Alert Brick` is before the `Run with Async Mod Variable` Brick, because the mod variable analysis considers name anywhere in the mod. (This behavior I believe, is already implemented correctly)

Screenshot
---

![image](https://github.com/pixiebrix/pixiebrix-extension/assets/1879821/19776801-d09a-4db0-8ccd-3ac530b8b386)

Discussion/Implementation Sketch
---
- Override/Implement getModVariableSchema for the WithAsyncModVariable brick. See the implementation for the shape: `data` (anything), `currentData` (anything), isLoading, etc.
- `visitBrick` might need to be update in the mod analysis to use getModVariableSchema?
- Might be a bug in https://github.com/pixiebrix/pixiebrix-extension/blob/b4d2d22a860f59e0f90e89521efe683beb0c786b/src/analysis/analysisVisitors/varAnalysis/varAnalysis.ts#L332-L332

Related Code
---
- https://github.com/pixiebrix/pixiebrix-extension/blob/b4d2d22a860f59e0f90e89521efe683beb0c786b/src/types/brickTypes.ts#L171-L171
- https://github.com/pixiebrix/pixiebrix-extension/blob/b4d2d22a860f59e0f90e89521efe683beb0c786b/src/bricks/transformers/controlFlow/WithAsyncModVariable.ts#L46-L46
- https://github.com/pixiebrix/pixiebrix-extension/blob/b4d2d22a860f59e0f90e89521efe683beb0c786b/src/analysis/analysisVisitors/pageStateAnalysis/modVariableNamesVisitor.ts#L54-L54
- https://github.com/pixiebrix/pixiebrix-extension/blob/b4d2d22a860f59e0f90e89521efe683beb0c786b/src/analysis/analysisVisitors/varAnalysis/varAnalysis.ts#L476-L476

**Comment by grahamlangford** [comment]
@twschiller Do you have steps to reproduce for this? This would be a good bug to fix in 1.8.1.

**Comment by twschiller** [comment]
> Do you have steps to reproduce for this? This would be a good bug to fix in 1.8.1.

@grahamlangford I added the reproduction steps - should be a relatively quick hit
