### ISSUE TITLE
Improve error message in Workshop when updating a brick with invalid permissions

### ISSUE THREAD

**Issue by grahamlangford** [pixiebrix/pixiebrix-extension#6597]
Context 
---
https://pixiebrix.slack.com/archives/C0436P48QHY/p1696372763377169

Acceptance Criteria
---
Given I am editing a brick in the Workshop
When the brick is shared with an organization I do not have sharing access for
And I attempt to save the brick
And the save fails
Then I should see a descriptive error message explaining why it failed

**Comment by twschiller** [comment]
I suspect the fix will end up being in the view or serializer on the backend to improve the error message. The front-end likely passes the organization UUID which then the backend fails to find because the user doesn't have permissions to view it
