### ISSUE TITLE
Cannot use new Google Drive integration in Page Editor in MS Edge

### ISSUE THREAD

**Issue by twschiller** [pixiebrix/pixiebrix-extension#6622]
Context
---
- Tested used 1.8.0-beta.1 on MS Edge on Mac
- The AppendSpreadsheetOptions and LookupSpreadsheet options are wrapped in `requireGoogleHOC`, which prevents the options from being loaded in MS Edge
- The new Google Drive integration should work in MS Edge because it doesn't use gapi/the browser's Google OAuth2 identity

Screenshot
---

![image](https://github.com/pixiebrix/pixiebrix-extension/assets/1879821/b4c77589-de44-4101-96f5-9c9388b8c6a1)

Related Code
---
- https://github.com/pixiebrix/pixiebrix-extension/blob/23b5fbb13ddcdd6cdecbd964d14d883c624b3ea6/src/contrib/google/sheets/ui/AppendSpreadsheetOptions.tsx#L181-L181

**Comment by grahamlangford** [comment]
We will update this logic when we remove GAPI support in version 1.8.2

**Comment by twschiller** [comment]
Closing because we've removed the gapi gate code
