### ISSUE TITLE
Improve RegEx typings

### ISSUE THREAD

**Issue by grahamlangford** [pixiebrix/pixiebrix-extension#6628]
_Originally posted by @fregante in https://github.com/pixiebrix/pixiebrix-extension/pull/6607#discussion_r1349465899_
            

---

> I thought of an alternative way to define/use groups: with a helper function that forces us to define the regex and its expected groups next to its definition:
> 
> ```ts
> // before
> const elementsCollectionRegexp =
>      /((?<collectionName>.*)\.)?(?<elementIndex>\d+)/;
> 
> // after
> const elementsCollectionRegexp = regexGroups<[
>    'collectionName',
>    'elementIndex'
> ]>(/((?<collectionName>.*)\.)?(?<elementIndex>\d+)/)
> ```
> 
> Still not fail-safe, but:
> 
> - it's easier to tell if they become mismatched
> - there's no need for `!`/`assert`
> - it enforces the property names at the usage site.
> 
> 
> There's a less verbose way, but it requires using `new RegExp` instead of regex literals, so we'd lose syntax highlighting, etc
> 
> https://blog.ndpsoftware.com/2022/10/strong-typing-regexp
>

**Comment by grahamlangford** [comment]
Nice to have but low priority. Keeping alive for now.

**Comment by fregante** [comment]
TS 5.5 will start parsing/validating regexes so this might _eventually_ become part of TS itself.

https://devblogs.microsoft.com/typescript/announcing-typescript-5-5/#regular-expression-syntax-checking

This is not yet available though:

https://www.typescriptlang.org/play/?target=10#code/MYewdgzgLgBATgUwOYIB4wLwwPQApcD8APKADakLBQCW4AcgIYC2CAfAHQBUAlADrvcChIggoswUAJJgAJmla8ZAam7YA3ACgNoSLCbUIEamCSZ4yNOzSVcpEMAY1w7ABaIAZoPZI4IAK4ADhAE7HQA8gAKAKIaMHHY2DAAegQaQA
