### ISSUE TITLE
Iframes are not updated until reload

### ISSUE THREAD

**Issue by fregante** [pixiebrix/pixiebrix-extension#6648]
Probably a minor issue, somewhat related to:

- https://github.com/pixiebrix/pixiebrix-extension/issues/1557

### Repro

1. Open https://ephiframe.vercel.app/Outer?iframe=https://extra-ephiframe.vercel.app/Cross-domain-iframe%3Fiframe%3D./nested
2. Add button next to "Docs" in the Outer document
3. Set `https://*.vercel.app/*` as the site
4. Save

⚠️  At this point the button should appear in every iframed document, but doesn't.

5. Reload the page

✅ The button now appears 

6. Make changes to the button
7. Save

⚠️  Changes are still not reflected until a reload.

### Demo for steps 6-7

https://github.com/pixiebrix/pixiebrix-extension/assets/1402241/babf1e6a-8506-41bd-91cc-ca4cdc351deb

### Questions

What is the current support state for iframes? The dev tools cannot select elements inside iframes, but any pre-existing buttons are loaded.

**Comment by twschiller** [comment]
This is a known limitation. We have some docs on tips for working with IFrames: https://www.notion.so/pixiebrix/Editing-Pages-with-IFrames-630066b5d18d43d0bd50f0935d50e0b2?pvs=4

**Comment by twschiller** [comment]
That addresses the issue on save. Reminder that dirty state is still not synced to the frames, though with that approach

**Comment by fregante** [comment]
> dirty state

I assume that refers to unsaved changes in the page editor. That limitation applies to other tabs as well, so it's unrelated to this frame-specific bug.

**Comment by fregante** [comment]
This was partially reverted in:

- https://github.com/pixiebrix/pixiebrix-extension/pull/7785

Due to:

- https://github.com/pixiebrix/webext-messenger/issues/219

**Comment by fregante** [comment]
I think this was fixed by https://github.com/pixiebrix/pixiebrix-extension/pull/8001
