### ISSUE TITLE
Watch for navigation via the new Navigation API

### ISSUE THREAD

**Issue by fregante** [pixiebrix/pixiebrix-extension#6649]
Browsers now have access to all navigation events thanks to the navigation API. 

https://developer.mozilla.org/en-US/docs/Web/API/Navigation_API

We should drop the `browser.webNavigation`-based events from the background and just use the new API directly in the content script

https://github.com/pixiebrix/pixiebrix-extension/blob/4a103edc6975282a7cca07ec376cf7831caaf7eb/src/background/navigation.ts#L72-L75

https://github.com/pixiebrix/pixiebrix-extension/blob/4a103edc6975282a7cca07ec376cf7831caaf7eb/src/contentScript/lifecycle.ts#L570

This does not affect the pageEditor’s listeners, because you can't listen to the navigation of other frames. 

Related issue:

- https://github.com/pixiebrix/pixiebrix-extension/issues/4257

**Comment by fregante** [comment]
This would reduce the reliance on the background page and the amount of messaging required during navigation. 

I'll mark this as `mv3` only because it would be particularly beneficial there.

**Comment by twschiller** [comment]
NOTE: Chromium-only (not Firefox/Safari) is OK. 

Related discussion about SPA event detection: https://github.com/w3c/webextensions/issues/446

**Comment by fregante** [comment]
> listening for navigation could be a good way to avoid the background worker being recycled

If that actually helps we can keep the listeners enabled without having to also using the messaging channel. This has the added benefit that when the worker is eventually and necessarily restarted, the navigation doesn't have to wait for it to complete loading.
