### ISSUE TITLE
Internal error opening backing store for indexedDB.open

### ISSUE THREAD

**Issue by grahamlangford** [pixiebrix/pixiebrix-extension#6655]
Context
---
* https://pixiebrix.slack.com/archives/C0436P48QHY/p1697064881956369
* https://pixiebrix.slack.com/archives/C0436P48QHY/p1696275349600979
* https://app.rollbar.com/a/pixiebrix/fix/item/pixiebrix-extension/10106

Acceptance Criteria
---
* Determine if there are any mitigations we can put in place to reduce the number of errors we see
* Help the user recover from the error
    * Usual recovery is to restart Chrome, we should at least be recommending that to the user

**Comment by twschiller** [comment]
@grahamlangford we do have some prior art here, see IDBErrorDisplay: https://github.com/pixiebrix/pixiebrix-extension/blob/5e908ad7f2d2e37ec0f7cfb15eb980bcd08ca73b/src/extensionConsole/components/IDBErrorDisplay.tsx#L166-L166

I'm not sure why that component is not being displayed for some of these users

**Comment by grahamlangford** [comment]
Another report: https://pixiebrix.slack.com/archives/C0436P48QHY/p1705603945743259
