### ISSUE TITLE
Slice 1.1: Add a Javascript Brick

### ISSUE THREAD

**Issue by grahamlangford** [pixiebrix/pixiebrix-extension#6657]
https://www.notion.so/pixiebrix/Add-Javascript-brick-for-data-transformation-to-avoid-JQ-754618ab6bc64a868b149f2a8c389454?pvs=4#c86ada73eefd46db8060df6c33c67673

**Comment by fregante** [comment]
I had added a method to the sandbox, but I never opened a PR for it. It might be useful: ab48d71862a6b31720658ea5fa828c4c8d638103
