### ISSUE TITLE
PKCE web auth flow shows multiple times simultaneously

### ISSUE THREAD

**Issue by twschiller** [pixiebrix/pixiebrix-extension#6684]
Context
---
- The PixieBrix background worker will automatically run the web auth flow if the user doesn't have a valid token
- As a result, the end-user can get multiple Web Auth Flow windows simultaneously for the same service
- Users impacted: @MMirandi, and customers on KB assist and other Google mods
- This causes problems as requests only one of the web auth flows will succeed

Discussion
---
- Simultaneous calls to [launchOAuth2Flow](https://github.com/pixiebrix/pixiebrix-extension/blob/2ab6d92c39543409309927d4624532a9b14996ac/src/background/auth/launchOAuth2Flow.ts#L30-L30) likely needs to be coalesced while the promise is pending
- Can likely use the [memoizeUntilSettled](https://github.com/pixiebrix/pixiebrix-extension/blob/2ab6d92c39543409309927d4624532a9b14996ac/src/utils/promiseUtils.ts#L80-L80) helper method

**Comment by BLoe** [comment]
Note:
* This is reproducible with a deployment mod
