### ISSUE TITLE
Refactor/simplify `CreatableAutoSuggest` (too many `strictNullChecks` issues)

### ISSUE THREAD

**Issue by fregante** [pixiebrix/pixiebrix-extension#6686]
_Originally posted by @BLoe in https://github.com/pixiebrix/pixiebrix-extension/pull/6683#discussion_r1368895783_
            

> Furthermore, this `CreatableAutoSuggest` component appears to only be used in one place, in `SelectorSelectorWidget`. I'm not sure if this was used in more places previously, but if we only need to support the one widget, then this whole thing can/should be simplified a TON. Probably can remove a bunch of the props and make the rest required, based on the one widget call-site.

This is related to the strictNullChecks upgrade.

We have two options:

- figure out how to handle the optional `onCreateNew` and `renderCreateNew` callbacks
- simplify the whole component to avoid unnecessary complexity

**Comment by grahamlangford** [comment]
completed
