### ISSUE TITLE
Sheets from Shared Drives should show up in the sheet dropdown

### ISSUE THREAD

**Issue by grahamlangford** [pixiebrix/pixiebrix-extension#6701]
## Describe the bug

When configuring a mod that uses the Google Drive integration, when the sheet I want to use is in a shared drive (owned by someone else), then I do not see that sheet in the dropdown even if I have edit access.

## To Reproduce

1. Create a Google Sheet in a drive that is shared with your account
2. Activate a mod that uses the Google Drive integration
3. Select your drive integration
4. Search for the sheet from the shared drive in the dropdown

## Actual behavior

The Shared Drive Google sheet is not in the options

## Expected behavior

The Shared Drive Google sheet is available in the options

## Desktop (please complete the following information):

- OS: OSX
- Browser: Chrome
- Extension Version: 1.8.1

## Additional context

https://pixiebrix.slack.com/archives/C0436P48QHY/p1698244221871169

**Comment by BLoe** [comment]
Just to make sure and note here so it doesn't fall through the cracks:

After adding the query parameters to the /drive/files list api call, we need to verify that all intended sheets functionality still works properly when selecting one of these "shared" sheets. Including but not limited to:
* Mod execution
* All related page editor functionality
* Mod activation
* _Writing_ to a shared sheet
  * Nuances in expectations/behavior for a sheet that is shared with only View access vs. Edit access

**Comment by grahamlangford** [comment]
> Just to make sure and note here so it doesn't fall through the cracks:
> 
> After adding the query parameters to the /drive/files list api call, we need to verify that all intended sheets functionality still works properly when selecting one of these "shared" sheets. Including but not limited to:
> 
> * Mod execution
> * All related page editor functionality
> * Mod activation
> * _Writing_ to a shared sheet
>   
>   * Nuances in expectations/behavior for a sheet that is shared with only View access vs. Edit access

@BLoe, can you recommend some feature tests here: https://www.notion.so/pixiebrix/Release-1-8-2-676f3ca1795541019e25d79c306b04c9?
