### ISSUE TITLE
Can't use page editor on page that doesn't have permissions

### ISSUE THREAD

**Issue by twschiller** [pixiebrix/pixiebrix-extension#671]
## Scenario 1: Granting Permanent Permissions

**Steps to reproduce:**
* Visit a page that the extension doesn't have access to
* Open the devtools to the PixieBrix panel
* Click "Grant Permanent Access"
* In the lower left of the devtools, the loading indicator shows the devtools is trying to connect to the page
* The devtools panel shows an error "Cannot access the page in 4s"

Some investigation:
* This console.debug looks wrong. It will log as "ready" even if an error is thrown in the try block http://github.com/pixiebrix/pixiebrix-extension/blob/17739d6b6ceb9bc547ca5ca8220c780e2045ab9c/src/background/util.ts#L145-L145

Root cause:
* When the user click "Grant permanent access", they accept permissions for the site. Then, during the ensureContentScript check, it thinks that the content script should already be available because it's in the list of permissions: http://github.com/pixiebrix/pixiebrix-extension/blob/17739d6b6ceb9bc547ca5ca8220c780e2045ab9c/src/background/util.ts#L128-L128
* Potential solution: expose "force" flag for ensureContentScript that ignores the isContentScriptRegistered check

Relevant code:
* Action for requesting permissions: http://github.com/pixiebrix/pixiebrix-extension/blob/17739d6b6ceb9bc547ca5ca8220c780e2045ab9c/src/devTools/editor/panes/PermissionsPane.tsx#L33-L33
* Connect method that gets called after the permissions request: http://github.com/pixiebrix/pixiebrix-extension/blob/17739d6b6ceb9bc547ca5ca8220c780e2045ab9c/src/devTools/context.ts#L173-L173

## Scenario 2: Granting Temporary Permissions

**Steps to reproduce**
* Visit a page that the extension doesn't have access to
* Open the devtools to the PixieBrix panel
* Click the PIxieBrix icon in the toolbar to open the sidepanel (which also give PixieBrix access to the page)
* The devtools panel still doesn't have access to the page

Relevant background page debug log:

```
ensureContentScript: requested {tabId: 182, frameId: 0}
util.ts:134 ensureContentScript: injecting {tabId: 182, frameId: 0}
util.ts:145 ensureContentScript: ready {tabId: 182, frameId: 0}
backgroundProtocol.ts:205 Sending content script action @@pixiebrix/contentScript/TOGGLE_ACTION_PANEL to tab 182, frame 0
executor.ts:265 Marked tab 182 (frame: 0) as ready {sender: {…}}
internal.ts:314 emitDevtools: ContentScriptReady {tabId: 182, frameId: 0}
```

Root cause:
* An event is emitted to the React front-end for "ContentScriptReady" for http://github.com/pixiebrix/pixiebrix-extension/blob/17739d6b6ceb9bc547ca5ca8220c780e2045ab9c/src/background/devtools/external.ts#L55-L55, but not for "DOMContentLoaded"/"HistoryStateUpdate", so the devtools never tries to connect
* Implementation sketch: fire one of the above events on the first content script navigation event. Or, also also connect on content script ready here: http://github.com/pixiebrix/pixiebrix-extension/blob/17739d6b6ceb9bc547ca5ca8220c780e2045ab9c/src/devTools/context.ts#L209-L209

## Additional Info

FYI: `main` now has support for removing additional permissions on the Settings page of the extension. So you can use that during testing

**Comment by fregante** [comment]
> ## Scenario 1: Granting Permanent Permissions

Found the issue: https://github.com/fregante/content-scripts-register-polyfill/issues/26

`webext-dynamic-content-scripts` automatically registers the scripts on new permissions, but `content-scripts-register-polyfill` does not automatically inject it in existing frames like the native `.register()` Firefox does.

I fixed this locally, need cleanup and release.

> ## Scenario 2: Granting Temporary Permissions

hmmmm it seems to work for me. This screencast is taken on `main` and it matches v1.1.12. The step missing is the page refresh, which is also outlined in the devtools instructions.

![chrome](https://user-images.githubusercontent.com/1402241/124264676-fcd29500-db5e-11eb-9d6e-b22e9578f72f.gif)


> * Potential solution: expose "force" flag for ensureContentScript that ignores the isContentScriptRegistered check

The point of #661 was to never need to handle injection as an action but rather as a static definition, similar to we define files in manifest.json and they're just taken care of by "the system." I expect to move `ensureContentScript` to a lower and lower level to achieve this once this change is stable.

**Comment by twschiller** [comment]
> hmmmm it seems to work for me

Apologies for the confusion - you're correct. I think it is actually no possible to get rid of the extra step though now just by connecting the devtools on the content script ready event. I'll create a separate ticket
