### ISSUE TITLE
Update npm version in package.json to be consistent with lockfile v3

### ISSUE THREAD

**Issue by twschiller** [pixiebrix/pixiebrix-extension#6789]
Context
---
- The project now uses npm lockfile version 3
- Lockfile version 3 is used by npm 7 and 8: https://docs.npmjs.com/cli/v9/configuring-npm/package-lock-json#file-format
- Our npm engine in the package json file is currently "8.x": https://github.com/pixiebrix/pixiebrix-extension/blob/547d4ff73aee3ca189bbe3331a50df69a37b8921/package.json#L27-L27

Discussion
---
- From the release schedule it looks like we should be on npm 9: https://nodejs.org/en/about/previous-releases given that our `.nvmrc` version is 18.13

Related
---
- https://github.com/pixiebrix/pixiebrix-extension/pull/6663

**Comment by fregante** [comment]
What's the inconsistency? Npm 7+ supports v3 and the project uses npm 8

**Comment by fregante** [comment]
By the way I had tried to bump both node and npm a few days ago but was blocked by Vercel: https://github.com/pixiebrix/pixiebrix-extension/pull/6741

The current LTS is Node 20 and the latest is 21

**Comment by twschiller** [comment]
Apologies, realized I had npm 7 locally. Looks like npm version 8 can both consume and use Lockfile Version 3
