### ISSUE TITLE
Firefox lacks `port.onMessage.hasListeners()` API

### ISSUE THREAD

**Issue by fregante** [pixiebrix/pixiebrix-extension#679]
Firefox is missing `onMessage.hasListeners()`, it only has `hasListener(fn)`

Used here: 
https://github.com/pixiebrix/pixiebrix-extension/blob/c34b29d67f09523d80c7ba1b68a5ebaa06c9293c/src/background/devtools/external.ts#L92
 
> What is this impacting?

The devtools panel won't load at all when this fails. I don't know exactly why it's used yet (I was just listing the Firefox limitations)

**Comment by twschiller** [comment]
> I don't know exactly why it's used yet

I think it's just a sanity check. Should be safe to omit on Firefox. Would probably leave in for Chrome as it helps isolate what causes a message to not be received/handled
