### ISSUE TITLE
Target for RUN_BRICK not found when targeting the `window: top` tab

### ISSUE THREAD

**Issue by twschiller** [pixiebrix/pixiebrix-extension#6807]
## Describe the bug

- https://app.pixiebrix.com/teams/b8049b91-8b77-4ae5-852f-dfe9925507f4/deployments/c9671812-5f85-4297-ae0a-aa6a6d3a347b
- `The target {"tabId":828417699,"frameId":0} for RUN_BRICK was not found`
- Error comes from webext-messenger here: https://github.com/pixiebrix/webext-messenger/blob/b3aed0cd3096b26f5a242bcd7de0b0a2a5d831a1/source/sender.ts#L94. Error scenarios:
  > Any target exists and has onMessage handler, but never handled the message
  > Extension page exists and has Messenger, but never handled the message (Messenger in Runtime ignores messages when the target isn't found)
- Request from sender comes from here: https://github.com/pixiebrix/pixiebrix-extension/blob/8270456ebd581a1cd3871818b953778f3bf19f19/src/background/executor.ts#L141-L141
- Receiver is registered in content script here: https://github.com/pixiebrix/pixiebrix-extension/blob/8270456ebd581a1cd3871818b953778f3bf19f19/src/contentScript/messenger/registration.ts#L190-L190

## To Reproduce

- TBD: have not been able to reproduce in the sandbox yet

## Additional context

- What mod(s) were you running? See deployment link
- What website(s) were you using? See deployment link
- Do you need any special permissions to reproduce? We have credentials for customer's client sandbox

## Discussion

- The web app doesn't support deep-linking, so by the time the user opens a relevant sub-frame, the top-level frame should already be ready to receive messages
- I think the messenger already would have retried for 4 seconds: https://github.com/pixiebrix/webext-messenger/blob/b3aed0cd3096b26f5a242bcd7de0b0a2a5d831a1/source/sender.ts#L77

**Comment by fregante** [comment]
The error comes from this line:

https://github.com/pixiebrix/webext-messenger/blob/b3aed0cd3096b26f5a242bcd7de0b0a2a5d831a1/source/sender.ts#L155-L159

Line 94 is for `{page}` targets, while the log is a direct `{tabId, frameId}` target.

It might be this, which is something I'm working on:

- https://github.com/pixiebrix/pixiebrix-extension/issues/6548

If urgent, I think the existing version of my package should cover it: https://github.com/fregante/webext-inject-on-install/blob/master/index.js

**Comment by twschiller** [comment]
> It might be this, which is something I'm working on

If that's the root cause (e.g., restarts/context invalidation), it won't be too urgent. I'll take a look at telemetry to see if the error timing seems to correspond with an extension upgrade/restart

**Comment by fregante** [comment]
Since #6548 was resolved, this might be too.

**Comment by fregante** [comment]
Can't repro, probably fixed with #6548 

### Test

1. Visit https://ephiframe.vercel.app/Pixie?iframe=https://extra-ephiframe.vercel.app/Brix%3Fiframe%3Dhttps%3A%2F%2Fephiframe.vercel.app%2FPixie
1. Add "Window alert" brick
2. Set to "execute in top level frame"
3. Save and refresh page (due to https://github.com/pixiebrix/pixiebrix-extension/issues/6648)
4. Click the button in either the frame or the top frame

### Demo


https://github.com/pixiebrix/pixiebrix-extension/assets/1402241/d6f71311-1fe1-4cc1-ad39-3f9521154653
