### ISSUE TITLE
"A worker process has failed to exit gracefully..." warning after running tests

### ISSUE THREAD

**Issue by mnholtz** [pixiebrix/pixiebrix-extension#6815]
## Describe the bug

The following warning has appeared on main after running `npm run test`: 
```txt
A worker process has failed to exit gracefully and has been force exited. This is likely caused by tests leaking due to improper teardown. 
Try running with --detectOpenHandles to find leaks. Active timers can also cause this, ensure that .unref() was called on them.
```

For example, you can see the warning present on this run of main: https://github.com/pixiebrix/pixiebrix-extension/actions/runs/6750216991/job/18352177291

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK09oQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--04b9c526285b8dc13bf96bf74b9de9009c69a980/Screen%20Shot%202023-11-03%20at%202.16.39%20PM.png)

## To Reproduce

1. Pull `main` branch locally
2. Run `npm run test`

## Actual behavior

All tests are passing, and this warning is present at the end of the output.

## Expected behavior

All tests passing, with no warnings present.

## Additional context

- @twschiller believes this warning has appeared some time before the writing this ticket
- Running `npm run test --detectObjectHandles` as recommended doesn't seem to change the output in any way
    - Could be related to https://github.com/jestjs/jest/issues/9473 
    - Running `TZ=UTC jest --detectOpenHandles` produces some failed tests that might be helpful to debugging
- More information present on this slack conversation: https://pixiebrix.slack.com/archives/C023KL47XV4/p1699041836269559

**Comment by fregante** [comment]
> * Running `npm run test --detectObjectHandles` as recommended doesn't seem to change the output in any way

`npm run` does not pass flags down to the commands, you'll have to use 

```js
npm run test -- --detectObjectHandles
```

**Comment by fregante** [comment]
CI is 💀 

Each one of this failure has up to 5 hours of CI usage

<img width="568" alt="Screenshot 1" src="https://github.com/pixiebrix/pixiebrix-extension/assets/1402241/b76b6fc2-9a98-4bb3-843b-b1929c593e79">

**Comment by grahamlangford** [comment]
Thank you @fregante. We'll make fixing this a priority this week.
