### ISSUE TITLE
app.pixiebrix.com sends messages before Firefox is ready to receive

### ISSUE THREAD

**Issue by fregante** [pixiebrix/pixiebrix-extension#682]
_Originally posted by @fregante in https://github.com/pixiebrix/pixiebrix-extension/issues/490#issuecomment-868398929_

---

In Chrome, `runtime.sendMessage` is available immediately because it communicates directly to the background, but Firefox can't communicate until both the content script and script.js are injected.

Here you can see pb.com sending 5 requests before the content script is even executed. 

<img width="610" alt="Screen Shot 6" src="https://user-images.githubusercontent.com/1402241/123408780-9afeb200-d5d7-11eb-92e7-b80e75e03f51.png">

Unfortunately `document_start` only fixes the issue some of the time, this needs to be fixed in pb.com so that it waits before sending those messages.

I'm not entirely sure of how it's implemented because pb.com didn't receive the improvements in https://github.com/pixiebrix/pixiebrix-extension/pull/420 and the source code is basically obfuscated by the [regenerator](https://github.com/facebook/regenerator).

I suppose we have 2 options:

- message queue that is read by script.js (e.g. a global array)
- have a global callback function that is called by script.js

Alternatives?

**Comment by fregante** [comment]
> > it sends messages when the content script isn't yet ready.
> 
> What is this referring to?

In Firefox instead every "external" message has to go through the content script. The problem arises when the external messages are sent before the content script is injected and starts listening to them.

In Chrome this is not a problem because external messages go directly to the background page.

**Comment by twschiller** [comment]
I'll look into making the changes for this one. There's basically two options:
1. External page loops it's checks, or 
2. The extension messages first

References:
* http://github.com/pixiebrix/pixiebrix-app/blob/403b5c34bef67c30dbedb1fd49155d8dc9f96209/pixiebrix-app/src/auth/hooks.ts#L103-L103

**Comment by fregante** [comment]
2 definitely sounds best, we already have a couple of "ready" events.

I'd love to turn this code into a polyfill and if I get to it first I'll try to unify this communication so Chrome and Firefox listeners will be identical. This would cover this issue: https://github.com/pixiebrix/pixiebrix-extension/issues/490#issuecomment-868427229

**Comment by twschiller** [comment]
Sure, would be good for you to take a swing at a separate polyfill

You'd then want to adapt the code in PixieBrix to use it under the hood: http://github.com/pixiebrix/pixiebrix-extension/blob/263412d518756cb382bde0569d1e79ffd41b963c/src/contentScript/externalProtocol.ts#L34-L34

Additional consideration:
* We won't be able to get rid of coupling until: https://github.com/pixiebrix/pixiebrix-extension/issues/578
* We may need to roll out the change in a series of steps (that are each backward compatible) so that we don't break the Chrome functionality while different versions of the extension are live

**Comment by fregante** [comment]
Feel free to address this in the App if it's just a matter of waiting for an event, it will be faster for you, and then I can work on the general polyfill.

**Comment by fregante** [comment]
> Sure, would be good for you to take a swing at a standalone polyfill.

If you'd like to extract this into its own module at some point you can open an issue with more details:

- you mean to publish this as its own module, right?
- should it try to match the sendMessage/onExternalMessage as much as possible like a polyfill or just a simplified module that wraps the API if it exists?
- are you ok with forgoing the current lifter architecture in this module to be a simple messaging module?
- would this make sense as a more generic messaging module across all contexts basically extracting the whole lifter architecture?
