### ISSUE TITLE
Can toggle submit on enter in the Custom Form Brick

### ISSUE THREAD

**Issue by grahamlangford** [pixiebrix/pixiebrix-extension#6854]
## User Story

As a PixieBrix developer, I want the custom form brick to submit on enter, so that I can create a chat app experience with ChatGPT.

## Motivation

For KB and other Copilots, we want to make it as easy as possible for users to quickly send queries to ChatGPT.

## Acceptance Criteria

Scenario: Creating a mod in the Page Editor using the Custom Form

- Given I am creating a mod in the Page Editor
- When I add a sidebar panel
- And I add the Custom form brick to the Render Document
- Then I should be able to configure the form to submit on enter

Scenario: Hiding the Submit button in the Sidebar
- Given I am using a mod with a Custom Form
- And the "submit on enter" toggle has been set to true
- When I use the form in the sidebar
- Then the submit button should be hidden

Scenario: Pressing Enter in the Custom Form in the Sidebar

- Given I am using a mod with a Custom Form
- And the "submit on enter" toggle has been set to true
- When I use the form in the sidebar
- And I enter text
- And I press "Enter"
- Then the form should submit 

Scenario: Creating a new line in the Custom Form in the Sidebar

- Given I am using a mod with a Custom Form
- And the "submit on enter" toggle has been set to true
- When I use the form in the sidebar
- And I enter text in a textarea
- And I press "Shift + Enter"
- Then the a newline should be added
- And the form should *not* submit

**Comment by mthek10** [comment]
The only specification missing in this document is:

given  the form has been set to “submit on enter”
-   we don’t want to see the submit button in our chat demo.
 
This could be an option for the user potentially but for chat interfaces we won’t want the default submit button.
