### ISSUE TITLE
Drop externally_connectable?

### ISSUE THREAD

**Issue by fregante** [pixiebrix/pixiebrix-extension#690]
Just a thought.

Since we need to implement a working "polyfill" for Firefox, why not just use it in Chrome as well? This way we avoid having to wrangle to completely different implementations through a polyfill and we can just focus on one.

When/if externall_connectable becomes available in Firefox, we can just update it at once.

**Comment by twschiller** [comment]
> When/if externall_connectable becomes available in Firefox

I'm not aware of any plans from the Firefox team to add it

In general, I like `externally_connectable` as the security model is better. With postMessage on the window/defaultView there's a lot to get right

My preference is to keep externally_connectable for now unless it's too much of a burden to support both:
* Better reliability/startup performance by not having to wait for the content script
* No opportunities for other extensions/etc. to interfere

Related:
* https://developer.mozilla.org/en-US/docs/Web/API/Window/postMessage#security_concerns
