### ISSUE TITLE
QuickBar - focus lock not working on Notion

### ISSUE THREAD

**Issue by grahamlangford** [pixiebrix/pixiebrix-extension#6904]
## Describe the bug

See original report here: https://pixiebrix.slack.com/archives/C0436P48QHY/p1700067247652419
- Backspace, Enter, Shift+Enter and possibly other keyboard events

## To Reproduce

1. Go to any notion page
2. Add some text to the page
3. Launch the QuickBar
4. Type some text in the Search
5. Press Backspace

## Actual behavior

The text on the Notion page is deleted

## Expected behavior

The focus lock prevents Notion from being impacted by the keyboard events in the QuickBar Search

## Screenshots/Loom

https://www.loom.com/share/14492c77a3db44a68240324a990d650b?sid=cbdcb3bb-5746-4cad-8ecf-c1eb48a1fadd

## Desktop (please complete the following information):

- OS: OSX
- Browser: Chrome
- Extension Version: 1.8.2, 1.8.3

**Comment by grahamlangford** [comment]
Issue opened with KBar here: https://github.com/timc1/kbar/issues/343

**Comment by twschiller** [comment]
Raised again today: https://pixiebrix.slack.com/archives/C0436P48QHY/p1708456968711829?thread_ts=1708456714.445559&cid=C0436P48QHY

**Comment by fregante** [comment]
I don’t think "focus lock" does this, it just handles the TAB key, it doesn't prevent events from bubbling. If that's the reason why it was added, I think it can be removed.


My guess is that Notion has `capture` events so it receives them before kbar can see and "prevent" them.
