### ISSUE TITLE
Drop use of deprecated endpoints from extension

### ISSUE THREAD

**Issue by twschiller** [pixiebrix/pixiebrix-extension#6937]
Context
---
- https://github.com/pixiebrix/pixiebrix-app/pull/4356

Violations
---
- `/api/services/` -> `/api/registry/bricks/?kind=`
- `/api/recipes/<registryId>/` -> `/api/registry/bricks/<registryId>/`

**Comment by grahamlangford** [comment]
@BLoe and @johnnymetz Something to consider as part of the Service Layer/Serializer work.
