### ISSUE TITLE
Show popover on restricted URLs

### ISSUE THREAD

**Issue by twschiller** [pixiebrix/pixiebrix-extension#6947]
## User Story

As a PixieBrix end-user, I want to see a popover when I try to access PixieBrix on a restricted URL so I can figure out how to access the PixieBrix sidebar

## Context

https://www.notion.so/pixiebrix/Improve-Browser-Toolbar-UX-on-Extension-Console-and-non-scriptable-URLs-1f3a0f2452d74653823201103d1c4d22?pvs=4

**Comment by fregante** [comment]
We went back and forth on this a lot 😅 

- https://github.com/pixiebrix/pixiebrix-extension/pull/517
- https://github.com/pixiebrix/pixiebrix-extension/pull/1508
- https://github.com/pixiebrix/pixiebrix-extension/pull/4079
