### ISSUE TITLE
Upgrade to Node 16 LTS

### ISSUE THREAD

**Issue by twschiller** [pixiebrix/pixiebrix-extension#700]
Node 16 LTS should is the latest LTS and should hopefully give performance benefits and the benefits of the new lock file format

Considerations:
- node-sass compatibility (it should work, I hit problems updating the package lock on my machine): https://github.com/sass/node-sass/pull/3090
- node-sass is actually deprecated in favor of https://sass-lang.com/dart-sass. I'm not sure what's involved in that upgrade though since we use sass-loader

Implementation sketch:
- Install Node 16 locally an run `npm install` to upgrade the package log
- Update node version in the CI configuration. For example: http://github.com/pixiebrix/pixiebrix-extension/blob/49bac214f957b1cdd64d2b4dcdaced80ca213084/.github/workflows/build.yaml#L16-L16

**Comment by fregante** [comment]
I haven’t tried but I think the issue you found is that it needs a full reinstall when changing node version, so updating should be just a matter of updating the docs and accepting the new lockfile.

**Comment by twschiller** [comment]
Sorry, should have been more specific -- I was getting a C/C++ compilation error on my machine when it was rebuilding node-sass for using with Node 16. We're on version 6.0.X of node-sass, which should theoretically work with it though
