### ISSUE TITLE
Duplicate form field labels in 1.8.5-alpha.1

### ISSUE THREAD

**Issue by twschiller** [pixiebrix/pixiebrix-extension#7055]
## Describe the bug

- https://pixiebrix.slack.com/archives/C068HQX9K53/p1701734798104469

## To Reproduce

1. Add a form
2. Add a text area field
3. Add a dropdown field

## Actual behavior

The field label should be shown once

## Expected behavior

The field label is shown 2x in the real form. In the preview, it depends on the selected field type

## Screenshots/Loom

Screenshots: https://pixiebrix.slack.com/archives/C068HQX9K53/p1701734798104469

## Desktop (please complete the following information):

- 1.8.5-alpha.1

**Comment by fregante** [comment]
I don't have access to that screenshot, can you upload it to GitHub for easier reference?

**Comment by fregante** [comment]
I can reproduce it. Will attempt to fix it

**Comment by grahamlangford** [comment]
@fregante, in RJSF4, we had to add the label to our custom widgets, because they weren't getting the labels from the FieldTemplate. It's likely we just need to remove the labels from those widgets.
