### ISSUE TITLE
Developer authenticated via partner JWT cannot edit mod under team scope

### ISSUE THREAD

**Issue by twschiller** [pixiebrix/pixiebrix-extension#7062]
## Describe the bug

- https://pixiebrix.slack.com/archives/C042T2TBZ17/p1701462755297679
- NOTE: upon investigation this is likely a pixiebrix-app bug. If it is, close this issue and re-open in pixiebrix-app

## To Reproduce

See Slack: https://pixiebrix.slack.com/archives/C042T2TBZ17/p1701462755297679

1. Authenticate as developer role using partner JWT
2. Open the Page Editor
3. Edit a mod under the team scope
4. Try to save the mod

## Actual behavior

Use gets message: "You do not have permissions to edit X mod. Save as a new mod"

## Expected behavior

The mod is saved, because the user is a developer on the team

# Discussion

- This is likely the server being too restricted: https://pixiebrix.slack.com/archives/C042T2TBZ17/p1701827393480169?thread_ts=1701462755.297679&cid=C042T2TBZ17
- If this is a server bug, close this ticket and re-open on the app project

**Comment by johnnymetz** [comment]
Moved to App project: https://github.com/pixiebrix/pixiebrix-app/issues/4461
