### ISSUE TITLE
[Spike] Create technical spec for Brick Comments Phase 1

### ISSUE THREAD

**Issue by grahamlangford** [pixiebrix/pixiebrix-extension#7077]
See product spec: https://www.notion.so/pixiebrix/Brick-Comments-in-Mods-e4382d34bcd84a23b3467374144ebbff

**Comment by mnholtz** [comment]
Reopening spec until the spec is fully approved & all questions are resolved

**Comment by mnholtz** [comment]
Now closing this out due to an approval on the spec
