### ISSUE TITLE
Add link checker to CI

### ISSUE THREAD

**Issue by twschiller** [pixiebrix/pixiebrix-extension#7080]
Context
---
- We had some broken links from the doc portal migration
- We've also had problems with webflow URLs changing

Discussion
---
- May also want to run as recurring Cron job, because links may break due to docs/webflow changes not code changes
- Likely need to exclude:
  - `https://app.pixiebrix.com/schemas/*` (some of these links, e.g., service schemas, are placeholders)
  - Links behind authorization to https://app.pixiebrix.com
- Not really possible to do in eslint because eslint node walker is synchronous (I tried for 5-10 min and failed)

Options
---
- GitHub Actions: (need to verify content of docker image)
  - https://github.com/filiph/linkcheck/
  - https://github.com/urlstechie/urlchecker-action  
- Pre-commit
  - Maybe only Markdown?: https://github.com/tcort/markdown-link-check/

**Comment by fregante** [comment]
This would be relatively easy to add to Jest if move all URLs to a standalone file, without further tools.

```js
// src/urls.ts
export const documentationHome = 'https://etc'
export const …
```

This can probably be enforced via `no-restricted-syntax` that detects `'https?://'` anywhere except `src/urls.ts`

Then in Jest something like:

```js
// Prior art 
// https://github.com/refined-github/refined-github/blob/cd4c2468/source/github-helpers/selectors.test.ts
// https://github.com/refined-github/refined-github/blob/cd4c2468/source/github-helpers/selectors.ts
describe.concurrent('urls', () => {
	test.each(urls)('%s', async (url) => {
		expect(fetch(url)).resolves.matches({ok: true})
	}, {timeout: 9999});
});
```

This also solves the issue where some URLs are updated and others are forgotten, even if still valid.

**Comment by twschiller** [comment]
> Prior art

The irony is that those give a 404 for me

Agree it could be good to centralize the URLs. We'll want to consider if we want separate entries by UTM parameter or not

If we do split out into a URLs file, we should introduce an eslint rule that URLs should be extracted to that file
