### ISSUE TITLE
[Spike] Create technical spec for Brick Comments Phase 2

### ISSUE THREAD

**Issue by grahamlangford** [pixiebrix/pixiebrix-extension#7112]
Product Spec: https://www.notion.so/pixiebrix/Brick-Comments-in-Mods-e4382d34bcd84a23b3467374144ebbff

Acceptance Criteria
---

- [x] Sub page created for technical spec
- [ ] All outstanding comments on the tech spec have been resolved
- [ ] Approval Matrix has been signed off on by all required roles (Product, Design, Engineering, Tech Lead)

**Comment by mnholtz** [comment]
Technical spec has been created here: https://www.notion.so/pixiebrix/Phase-2-add-signifier-in-brick-configuration-pane-with-affordance-for-viewing-comments-0ed5dd5a986b4f8ab34a7e3c41ec4a5b

**Comment by twschiller** [comment]
@mnholtz thanks - we're good to start implementation here
