### ISSUE TITLE
Devtools Elements inspect shows message-less error when the site has no permission

### ISSUE THREAD

**Issue by fregante** [pixiebrix/pixiebrix-extension#713]
Tested on the store version, I suppose 1.1.12.

The content script can't be injected if we don't have activeTab or permanent permissions, but we should probably show a better message.

What fixes it: triggering activeTab by clicking the action button.

<img width="1122" alt="Screen Shot 18" src="https://user-images.githubusercontent.com/1402241/124655098-95537700-dec9-11eb-81ae-78fad5e6eee1.png">

**Comment by twschiller** [comment]
Triaging as low priority. The sidebar isn't an advertised feature of PixieBrix

**Comment by fregante** [comment]
- Was fixed by https://github.com/pixiebrix/pixiebrix-extension/pull/911

Still applicable:

- https://github.com/pixiebrix/pixiebrix-extension/issues/910
