### ISSUE TITLE
Warning not appearing on custom event field for trigger starter brick

### ISSUE THREAD

**Issue by twschiller** [pixiebrix/pixiebrix-extension#7144]
## Describe the bug

Warning not appearing on custom event field for trigger starter brick

## To Reproduce

1. Add trigger starter brick
2. Set type to custom event
3. Add a custom event

## Actual behavior

Warning shows in the brick outline. Should also show on the Custom Event field:

![image](https://github.com/pixiebrix/pixiebrix-extension/assets/1879821/602dcb31-5b37-4332-a065-ada7482a0ee3)

## Expected behavior

Warning shows on the field

## Desktop (please complete the following information):

- Extension Version: 1.8.5 (and before)

**Comment by grahamlangford** [comment]
Fixed in https://github.com/pixiebrix/pixiebrix-extension/pull/7194
