### ISSUE TITLE
Mod Current Inputs fields lose focus while typing

### ISSUE THREAD

**Issue by twschiller** [pixiebrix/pixiebrix-extension#7148]
## Describe the bug

- While typing into fields on the Mod Current Inputs form, the fields lose focus
- Seems to be new in 1.8.5
- Seems to only occur with fields that have not been saved

## To Reproduce

1. Add a text mod option
2. On the Mod Current Input form
3. Start typing in the text field

## Actual behavior

Field loses focus while typing

## Expected behavior

Field does not lose focus while typing

## Screenshots/Loom

If applicable, add screenshots/looms to help explain your problem.

## Desktop (please complete the following information):

- 1.8.5
- Bug does not seem to exist in 1.8.4

## Discussion

- The field is most likely being remounted while typing

**Comment by fregante** [comment]
> * The field is most likely being remounted while typing


The entire page editor is re-rendered with most interactions anywhere:

![after](https://github.com/pixiebrix/pixiebrix-extension/assets/1402241/0008c24c-2749-45f9-b30d-4f2d4e63e625)

In this case, the component is being removed and re-added, which seems to be confirmed by the "focus" position after the focus loss:

<img width="1145" alt="Screenshot 3" src="https://github.com/pixiebrix/pixiebrix-extension/assets/1402241/9ae48a19-cf24-4af2-8d47-437211374dd8">

I don't see any bad `key`s that suggest a bad remount, `spreadsheet` is set correct there for example.

My React Devtools skill end here 😅

**Comment by twschiller** [comment]
Performance issue that likely has a similar root cause: https://github.com/pixiebrix/pixiebrix-extension/issues/8245

**Comment by twschiller** [comment]
Potential fix/related: https://github.com/pixiebrix/pixiebrix-extension/pull/9351
