### ISSUE TITLE
Rainforest test for Comments tab

### ISSUE THREAD

**Issue by grahamlangford** [pixiebrix/pixiebrix-extension#7151]
https://www.notion.so/pixiebrix/Phase-1-make-a-brick-comment-editor-available-in-the-data-panel-for-non-starter-bricks-2f29353a290547ccbfbe0eadf01d0626?pvs=4#299e3049337a458b8e64a70792bbd422

**Comment by mnholtz** [comment]
Rainforest test is here: https://app.rainforestqa.com/tests/413867

1 thing I noticed about this test is that the textarea does not expand with the content as it does on Mac OS.

**Comment by mnholtz** [comment]
Graham is out this week; alternatively maybe @BLoe or @twschiller could review the test

**Comment by BLoe** [comment]
Ideally I think you should switch data panel tabs, and/or switch bricks, and/or switch mods, in order to show that comments are properly preserved on the brick.

**Comment by mnholtz** [comment]
> Ideally I think you should switch data panel tabs, and/or switch bricks, and/or switch mods, in order to show that comments are properly preserved on the brick.

Updated 👍 thanks for the input

**Comment by mnholtz** [comment]
I'm closing this issue due to people being ooo this week and this issue being relatively simple, happy to reopen as others see fit
