### ISSUE TITLE
Warnings not showing on fields in Brick Configuration

### ISSUE THREAD

**Issue by twschiller** [pixiebrix/pixiebrix-extension#7167]
## Describe the bug

- Warnings not showing on the K-V fields in Brick Configuration
- I had previously reported this for https://github.com/pixiebrix/pixiebrix-extension/issues/7144. But I think it's impacting multiple field types

## To Reproduce

1. Add HTTP brick
2. Set method to GET
3. Set a K-V value for the data field

## Actual behavior

![image](https://github.com/pixiebrix/pixiebrix-extension/assets/1879821/494dff05-0b62-439c-b398-5af9c479f1f8)

![image](https://github.com/pixiebrix/pixiebrix-extension/assets/1879821/778a32d4-35de-492e-be48-d331c49bdea0)

![image](https://github.com/pixiebrix/pixiebrix-extension/assets/1879821/82f80f57-b6d7-4d79-bf1b-641756191cb7)

## Expected behavior

A warning is shown above the field

## Desktop (please complete the following information):

- 1.8.6-alpha.1 and I think 1.8.5

## Discussion

- Did changes/fixes for variable popover break it?

**Comment by mnholtz** [comment]
Looks like these additions were the culprit:
https://github.com/pixiebrix/pixiebrix-extension/blob/2ec84a9fc4384b8190c06cc5c4e37f49106893e6/src/components/form/useFieldAnnotations.ts#L89-L100
