### ISSUE TITLE
Mark MV3 builds as MV3 builds in telemetry

### ISSUE THREAD

**Issue by twschiller** [pixiebrix/pixiebrix-extension#7174]
Context
---
- https://github.com/pixiebrix/pixiebrix-extension/issues/7171
- https://github.com/pixiebrix/pixiebrix-extension/issues/7172

Discussion
---
- Do we just need to include mv3 in the version name in the extension manifest? E.g., 1.8.X-mv3-beta.1

Definition of Done
---
- ~Identified as MV3 in Rollbar~
- Identified as MV3 in Datadog
- Identified as MV3 in Mixpanel

**Comment by fregante** [comment]
> * Identified as MV3 in Rollbar

We will soon have two identifiers:

- [#7219](https://github.com/pixiebrix/pixiebrix-extension/pull/7219) will include `mv2` or `mv3` in the sourcemap URL
- [#7172](https://github.com/pixiebrix/pixiebrix-extension/issues/7172) will include the mv3 EXTENSION_ID in the source of the error, like `chrome://the-new-mv3-id/dist/contentScript.js`

I'm not sure if either one of those will be helpful for grouping errors on Rollbar

**Comment by grahamlangford** [comment]
@grahamlangford -- need to check DataDog to see if this is still necessary.
