### ISSUE TITLE
Reduce reliance on background script 

### ISSUE THREAD

**Issue by fregante** [pixiebrix/pixiebrix-extension#7182]
The upcoming MV3 background worker limitations make it clear that the Chrome team do not see this context as a stateful "app" like it's easy to imagine it. I think it would be a good idea to reduce the scope of the background page as much as we can.

Especially for long-running operations such as broadcasting or background HTTP requests (#4391) I think it might make sense to use a **local proxy iframe** instead of the background. This would eliminate most lifecycle issues. The approach here would be nearly identical to what we do with the sandbox, with the exception that we can use the regular messenger for this local proxy.

To do this, we should probably look at the list of background methods exposed via the messenger: https://github.com/pixiebrix/pixiebrix-extension/blob/fbffa960d857ad8f44c3453488f0d917286af2c5/src/background/messenger/registration.ts

From here we can:

- drop any methods that don't actually require background calls
	- for example if the underlying logic/API is available in the context that needs it
- move any long-running methods to a local proxy
	- most likely any "request run" methods
- look at any logic that is unnecessarily split between two contexts
	- such as https://github.com/pixiebrix/pixiebrix-extension/pull/7030

Related:

- https://github.com/pixiebrix/pixiebrix-extension/issues/7181
- https://github.com/pixiebrix/pixiebrix-extension/issues/2156

**Comment by twschiller** [comment]
> I think it would be a good idea to reduce the scope of the background page as much as we can.

We can revisit once we see what shape we're in for MV3. The alternative is to employ the background worker keep-alive techniques

There's going to be memory vs. latency tradeoffs for injecting extra iframes. (E.g., we'd need to decide whether there's a proxy iframe per frame or per tab)

**Comment by fregante** [comment]
> There are going to be memory vs. latency tradeoffs for injecting extra iframes.

If we don't load the entire extension in each frame we create I don't expect each frame to be heavy for this purpose. Being "chrome API" proxy frames they should only just load the messenger and deal with a handful of local API calls. 

> (E.g., we'd need to decide whether there's a proxy iframe per frame or per tab / top-level window)

We can't use frames in other tabs because they can be closed at any time, reducing reliability rather than increasing it, so there has to be one per tab. 

> There may also be frame CSP issues we need to account for

Is there an open issue with repro for that? I saw the message on slack but I'd like to look into what's happening

**Comment by twschiller** [comment]
Closing - we haven't seen any problems during MV3 dogfooding so far. Will reopen if we see problems during beta of problems related to background worker usage
