### ISSUE TITLE
Expire `SessionItem`/`SessionMap` to avoid accumulation in long browser sessions 

### ISSUE THREAD

**Issue by fregante** [pixiebrix/pixiebrix-extension#7190]
> do we need a way of expiring them, so they don't just accumulate over time?

Mentioned in https://github.com/pixiebrix/pixiebrix-extension/pull/7180#discussion_r1435126918

Potential solution: https://github.com/fregante/webext-storage-cache

Alternative simple solution: keep `storage.session`-based ledger with "keys to delete", then set `chrome.alarm` to clean it up regularly.

**Comment by twschiller** [comment]
🤦  Actually, the chrome.session.storage is not persisted across browser profile restarts: https://developer.chrome.com/docs/extensions/reference/api/storage#property-session

So I don't think we actually want to expire the keys in any case. The behavior of that storage is indeed the same behavior we have currently in a persistent background page

**Comment by fregante** [comment]
> The behavior of that storage is indeed the same behavior we have currently in a persistent background page

Indeed 🙌 

However in the case of tab:opener pairs that is still an issue, more so in the session storage because it's not _unlimited_ like it is for regular `Map`s

**Comment by twschiller** [comment]
The quota is 10mb, which would be pretty hard to fill up with tab metadata: https://developer.chrome.com/docs/extensions/reference/api/storage#property-session

**Comment by fregante** [comment]
So I think this should be implemented by the caller each time, rather than globally by SessionItem/Map. 

To fix this issue:

1. Review session storage usage
2. Add custom logic where deemed necessary
  - e.g. in the example above, `chrome.tabs.onRemoved` to remove specific tabs from the SessionMap
