### ISSUE TITLE
Webpack error loading page script

### ISSUE THREAD

**Issue by twschiller** [pixiebrix/pixiebrix-extension#722]
Not sure what the impact is yet

![image](https://user-images.githubusercontent.com/1879821/124781446-67922080-df11-11eb-9c86-c45a8ab88642.png)

**Comment by fregante** [comment]
Need help here? Is this a new issue?

**Comment by twschiller** [comment]
> Need help here? Is this a new issue?

IIRC, I saw it in the release build when QAing 1.1.12. I'll keep an eye out for in when QAing the next release

I don't see the error in the dev build
