### ISSUE TITLE
Test eslint no-magic-numbers rule

### ISSUE THREAD

**Issue by twschiller** [pixiebrix/pixiebrix-extension#723]
Try turning on https://eslint.org/docs/rules/no-magic-numbers rule as a warning, and see how many violations are currently in the codebase.

Options to consider:
- https://eslint.org/docs/rules/no-magic-numbers#ignoredefaultvalues

**Comment by fregante** [comment]
For the record, there are 504 instances with the default and 479 with  `"ignoreDefaultValues": true`

If you want to enable it I think it's just a matter of setting it as a warning and treating it like we treat the `security` rule.

**Comment by twschiller** [comment]
> If you want to enable it I think it's just a matter

Let's not enable it since it adds noise. The `security` rule I eventually want to clean up, as it's one that developers should at least be cognizant of
