### ISSUE TITLE
Support dropdown for Google Sheet tab name as input type

### ISSUE THREAD

**Issue by brittanyjoiner15** [pixiebrix/pixiebrix-extension#7263]
## User Story

As a mod activator, I don't want to have to remember or check the name of my Google Sheet tab when activating a mod, so that I can quickly use the mod without checking for typos or opening multiple tabs.

## Motivation

After selecting a Google Sheet in any of the Google Sheet bricks, the Tab Name appears as a dropdown, which contains a list of all the tabs in the selected sheet. 

![image](https://github.com/pixiebrix/pixiebrix-extension/assets/16166290/934f5102-5ba3-4bfa-b1aa-f2847b0c190e)

_Note: it also defaults to the first tab, but you can select the dropdown to choose another tab._

This is currently not available as a mod configuration input type, so when specifying a tab name on mod configuration, it must be a text field, and it cannot dynamically pull from the selected Google Sheet.
![image](https://github.com/pixiebrix/pixiebrix-extension/assets/16166290/c618f1a9-ad98-45f7-a076-10511dd46cba)

This could be a blocker that prohibits people from activating a mod because they don't understand what the tab name is or where to find it, or they may make a typo which causes the mod to fail.

## Acceptance Criteria

- Given a user is activating a mod
- When they add a google sheet to a google sheet input type 
- Then they should be able to dynamically select one of the tabs from the specified google sheet in the previous configuration input field

**Comment by twschiller** [comment]
Closing as not prioritized
