### ISSUE TITLE
Google Sheet options don't load without page refresh

### ISSUE THREAD

**Issue by brittanyjoiner15** [pixiebrix/pixiebrix-extension#7264]
## Describe the bug
When activating a mod with a google sheet, if you don't already have the Google integration, you'll need to configure it and then refresh the page and start to activate the mod again in order for the Google Sheet dropdown to populate with the sheets from your configured Google Account. 

## To Reproduce

1. Remove all Google Drive integrations you have access to
2. Activate the Decision Tree template: https://app.pixiebrix.com/activate?id=@pixies/template/decision-tree&nextUrl=https://www.pixiebrix.com/templates/decision-tree/#activationInstructions
3. Configure a Google Drive integration
4. Click the dropdown in the Google Sheet field. No options are available, despite seeing your Google account above. 
5. Refresh the page, start to activate again: https://app.pixiebrix.com/activate?id=@pixies/template/decision-tree&nextUrl=https://www.pixiebrix.com/templates/decision-tree/#activationInstructions
6. Click the Google Sheet dropdown and you'll see your available sheets.

## Actual behavior

After configuring a google drive account, you are unable to view your available sheets

## Expected behavior

When you configure a google drive account, it should be extremely clear, easy, and unobtrusive to re-fetch the available google sheets (like clicking a button) or it should happen automatically so that when you open the dropdown, you can view your available google sheets. 

## Screenshots/Loom

https://www.loom.com/share/20cc73aa365e488184af658f36c5e113

## Desktop (please complete the following information):

- OS: [e.g. OSX, Windows 10, Windows 11] OSX
- Browser [e.g. chrome, edge] Chrome
- Extension Version [e.g. 22] 1.8.6

## Additional context

- What mod(s) were you running? Decision Tree
- What website(s) were you using? https://www.pixiebrix.com/templates/decision-tree
- Do you need any special permissions to reproduce? no
  - Access to a Control Room?
  - Membership on a specific team?

**Comment by BLoe** [comment]
Talked with @brittanyjoiner15, I'm not able to reproduce this issue, and Britt is not seeing it anymore either
