### ISSUE TITLE
CSP error from Page Editor analysis rule in MV3

### ISSUE THREAD

**Issue by twschiller** [pixiebrix/pixiebrix-extension#7265]
## Describe the bug

The TemplateAnalysis Page Editor analysis rule uses `new Template` which calls eval under the hood

## To Reproduce

1. Load the MV3 extension
2. Add a trigger
3. Add the Show Sidebar brick and click into the template field

<img width="847" alt="image" src="https://github.com/pixiebrix/pixiebrix-extension/assets/1879821/4b934ca7-69f4-49b6-90c0-0d4dff143bea">

## Actual behavior

Error shown due to the invalid template

## Discussion

We may need to add a sandbox to the devtools to be able to compile the template (preferred?). Or will need to message the content script which then messages its sandbox

## Expected behavior

No error

## Additional context

- 1.8.6-beta.1

**Comment by fregante** [comment]
@grahamlangford I think https://github.com/pixiebrix/pixiebrix-extension/pull/7081 was supposed to fix this? Or is it something else?

**Comment by twschiller** [comment]
> @grahamlangford I think this PR was supposed to fix this issue? Or is it something else?

This is something else. It's a use on Nunjucks in the analysis: https://github.com/pixiebrix/pixiebrix-extension/blob/132c7ccf2da7ce838077ad241d665fb30dcf119d/src/analysis/analysisVisitors/templateAnalysis.ts#L95-L95

**Comment by twschiller** [comment]
@grahamlangford I'd recommend bumping this up as it's a blockers to me using the MV3 build as my daily driver

**Comment by grahamlangford** [comment]
@fregante feel free to pick this up when you're looking for next work, otherwise @BLoe or I will pick it up when one of us finishes up our current issues.

**Comment by fregante** [comment]
Source of the error:

https://github.com/pixiebrix/pixiebrix-extension/blob/25dd3d0389b8c90820ec2a2881ff56b40f3918b5/src/analysis/analysisVisitors/templateAnalysis.ts#L95

**Comment by fregante** [comment]
I opened a PR but this requires larger changes that need to be discussed first (`visitExpression` must be async)

**Comment by twschiller** [comment]
> I opened a PR but this requires larger changes that need to be discussed first (visitExpression must be async)

I would think we'd want to avoid changing the color of the visitExpression method because that will result in every visitor method needing to be async. 

This is what we've done for others: https://github.com/pixiebrix/pixiebrix-extension/blob/76ee8fa649ed741ab941ccab39a796ea0479d273/src/analysis/analysisVisitors/requestPermissionAnalysis.ts#L146-L146

**Comment by twschiller** [comment]
> The "add annotation" method is called in the async .catch callback but I only see my own logging, not the annotation

You're missing the `await allSettled` in the async run method for the analysis. The analysis results go into redux. Changes to the analysis annotation after the fact won't flow through because the Redux state is an independent copy of the results

**Comment by fregante** [comment]
Oh yes I remember seeing this being implemented a while ago actually. I'll give it a try
