### ISSUE TITLE
`ensureContentScript` does not inject `styles.css`

### ISSUE THREAD

**Issue by fregante** [pixiebrix/pixiebrix-extension#727]
- As noted in https://github.com/pixiebrix/pixiebrix-extension/pull/661

---

2 files appear in the manifest:

https://github.com/pixiebrix/pixiebrix-extension/blob/45f58aa5accef9656966b924fe177b1759df355f/browsers/manifest.json#L18-L19

But only the JS file is injected by `ensureContentScript`

https://github.com/pixiebrix/pixiebrix-extension/blob/17739d6b6ceb9bc547ca5ca8220c780e2045ab9c/src/background/util.ts#L135-L140

- Quick fix: Add `insertCSS('styles.css')`
- Permanent fix: read from manifest and inject every content script [like `webext-dynamic-content-scripts` does](https://github.com/fregante/webext-dynamic-content-scripts/blob/1d1e718991c87cc7adddd8b56539d298d3cc1681/index.ts#L21-L37)

I wonder why this isn't a more visible problem. Is contentScript.js **also** independently injecting the style or are the styles so minimal that we haven't noticed?

**Comment by twschiller** [comment]
> the styles so minimal that we haven't noticed?

The styles are minimal:

1. The z-index of notify JS
2. PixieBrix collapsable native panels
3. Style when using the "drag" feature for buttons on the page editor

http://github.com/pixiebrix/pixiebrix-extension/blob/843c86f016cdb052476ada672745e6629043c0a3/browsers/src/styles.css#L13-L13

1 and 2 are important. 3 is less relevant in most cases
