### ISSUE TITLE
Making a copy of a mod with changes clears changes in the original

### ISSUE THREAD

**Issue by twschiller** [pixiebrix/pixiebrix-extension#7276]
## Describe the bug

- Reported by enterprise customer during office hours. Have not attempted to reproduce locally yet
- Making a copy of a mod with changes clears changes in the original. 

## To Reproduce

1. Activate a team mod
2. Make some changes in Page Editor
3. Click "make a copy" and make a copy

## Actual behavior

- Changes in the original mod are deleted
- You have 2 mods as expected

## Expected behavior

- Copy of mod has the changes applied. (Or at least you don't lose your work from the other mod)

**Comment by BLoe** [comment]
@twschiller I tested this myself and it looks like my changes _were_ applied to the copy, but the original mod did reset to the clean state. Should we try and make it so that both copies retain the changes? Or are you still totally losing changes in both the original and copy when you try this? Should just be a matter of duplicating the mod form state properly, but I haven't dug into the code yet.

**Comment by twschiller** [comment]
> @twschiller I tested this myself and it looks like my changes were applied to the copy, but the original mod did reset to the clean state.

I'm seeing the behavior you see: 1) the changes are included in the saved copy, 2) the original mod loses the changes

> Should we try and make it so that both copies retain the changes?

Yes, I think that would be least surprising:
1. The original retains its unsaved changes
2. The copy includes the changes as saved changes

> Should just be a matter of duplicating the mod form state properly

You might also need to regenerate brick instance ids? (It might not matter in practice?)

Let's time-box an investigation (1 hour) of how hard it would be to fix. Alternatively, we could warn when clicking "make a copy" when there are unsaved changes.  The downside of that in certain cases, you don't want to save the changes, so you'll end up losing your work

**Comment by grahamlangford** [comment]
> Alternatively, we could warn when clicking "make a copy" when there are unsaved changes. The downside of that in certain cases, you don't want to save the changes, so you'll end up losing your work

I was going to suggest not allowing developers to make a copy if the form is dirty, but that would result in the same problem.
