### ISSUE TITLE
Move editor toasts to less bothering position

### ISSUE THREAD

**Issue by fregante** [pixiebrix/pixiebrix-extension#729]
The toasts appear in the top-right corner of the editor, covering the editor’s tabs. Can they be moved to a place where they are less annoying? Maybe even pushed 30px lower to uncover the tab bar.

Example from #730

![gif](https://user-images.githubusercontent.com/1402241/124890827-a05df280-e002-11eb-83be-6edf69cb5977.gif)

**Comment by fregante** [comment]
This library seems modern, compact and it appears centered by default

https://react-hot-toast.com

**Comment by twschiller** [comment]
We can re-position the current library as well. The main thing will be taking some assumptions about what screen width most users (not devs) will be using. Or, if we want, allowing the devs to override the location if they find themselves often using abnormal widths

**Comment by fregante** [comment]
I don’t think it's a dev-specific issue, but the page editor _reduced_ the annoyance so I'll close this.

https://user-images.githubusercontent.com/1402241/134060043-50b9c67c-38f5-46ad-b91e-f70ff80cc4f3.mov

Notes:

- I still think `react-hot-toast` would be a visual improvement and be smaller for short messages (design preference)
- The toast still appears right under the cursor when saving, which means it won't close until the user moves the cursor (minor UX issue)
