### ISSUE TITLE
Sidebar scroll should only scroll panel body

### ISSUE THREAD

**Issue by grahamlangford** [pixiebrix/pixiebrix-extension#7294]
## Describe the bug

In the sidebar, when the vertical content is greater than the viewport height, the entire sidebar scrolls instead of just the content in the Panel Body. 

## To Reproduce

1. Create or install a mod with a sidebar mod component with enough content to force a scroll
2. Scroll the content

## Actual behavior

The entire sidebar scrolls (including the tabs)

## Expected behavior

Only the content of the tab scrolls

## Screenshots/Loom

<img width="719" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOXFuQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c2da1e3ccf07d5159265d6c491e12f491c715808/image.png" alt="image.png" />

## Additional context

- Example of a mod with a long sidebar: `@pixiebrix-dev/test/long-sidebar-form`
- Because this issue has recurred multiple times, let's create a Rainforest test to catch it in the future.

**Comment by fregante** [comment]
I can look into this this week. It's probably a single class
