### ISSUE TITLE
Unable to link local Extension to local App

### ISSUE THREAD

**Issue by johnnymetz** [pixiebrix/pixiebrix-extension#7297]
## Describe the bug

I'm unable to link a locally running Extension to a locally running App.

May be caused by https://github.com/pixiebrix/pixiebrix-extension/pull/7211/

Slack thread: https://pixiebrix.slack.com/archives/C0436P48QHY/p1704750893502259

Workaround: Manually add the localhost urls to `externally_connectable` (see loom)

## To Reproduce

1. Configure your local environment to use a local Extension and a local App, see https://www.notion.so/pixiebrix/Dev-Environment-Setup-bc53fdc29e7148c89c251103ef119f44?pvs=4#1ce7c90c42a34026a0b6c0d6f0cd6298
2. Hit the App url: http://127.0.0.1:8000/

## Actual behavior

Unsuccessful linking. The verbose logs include the following message:

> Extension is not installed/available RuntimeNotFoundError: Browser runtime is unavailable; is the extension externally connectable?

## Expected behavior

Successful linking. The following alert should appear:

> Successfully linked the Browser Extension to your PixieBrix account

## Screenshots/Loom

https://www.loom.com/share/51939824c74f4e08a862a574b17a6ae1

## Desktop (please complete the following information):

- OS: OSX
- Browser: Chrome
- Extension Version: 1.8.6-alpha.1

**Comment by johnnymetz** [comment]
Looks like the localhost urls aren't being applied? https://github.com/pixiebrix/pixiebrix-extension/blob/main/scripts/manifest.mjs#L109-L112

**Comment by twschiller** [comment]
When I run `npm run test` locally, I get the following snapshot diffs:
<img width="501" alt="image" src="https://github.com/pixiebrix/pixiebrix-extension/assets/1879821/6f1f96d3-0514-4983-ae67-5b8c65292c44">

So I suspect there is some environment oddness going on

**Comment by fregante** [comment]
There's a chance that localhost is being filtered out from the permissions "because it's include in <all_urls>", but it's very likely given a special treatment by Chrome. 

I'll restore it

**Comment by fregante** [comment]
Is the EXTERNALLY_CONNECTABLE env set on your computer? I don't see further conditions on that field. The extension is only connectable when built via `npm run watch` I think

**Comment by twschiller** [comment]
> Is the EXTERNALLY_CONNECTABLE env set on your computer? 

It's not set globally, and doesn't appear in my .env files with those values

**Comment by fregante** [comment]
So that condition was probably dead code but I assumed it was good. See https://github.com/pixiebrix/pixiebrix-extension/pull/7211/files#r1437096182

**Comment by fregante** [comment]
Oh here it is:

https://github.com/pixiebrix/pixiebrix-extension/blob/d39b94c3dc52f8f29b6340e22b30101d10be1c7b/.github/workflows/ci.yml#L75
