### ISSUE TITLE
Stay on current editor tab after saving

### ISSUE THREAD

**Issue by fregante** [pixiebrix/pixiebrix-extension#730]
1. Make changes in the editor
2. Click save
3. The current tab is lost
4. Go find wherever you were
5. Repeat

![gif](https://user-images.githubusercontent.com/1402241/124890827-a05df280-e002-11eb-83be-6edf69cb5977.gif)

It doesn't help that the toasts cover the tab bar, so they need to be closed to return to the tab:

- #729

**Comment by twschiller** [comment]
I agree with this. I originally wanted to have this behavior, but it happens to be non straight-forward based on how the Redux state is stored (it causes a clean render of the React tree on save)

Will bump up priority as we get more requests about this

**Comment by fregante** [comment]
I think this has been resolved by the page editor :🎉 

Reopen if I'm mistaken

**Comment by fregante** [comment]
Still happens:


https://user-images.githubusercontent.com/1402241/135693438-d7c4b91d-9226-462d-a60f-b6b28632181f.mov

**Comment by fregante** [comment]
The "current brick" is now preserved 🎊 even though scrolling isn't preserved… but that's less annoying

https://user-images.githubusercontent.com/1402241/145687437-18ba6456-1ce7-4d9b-8076-e6b790cc1843.mov
