### ISSUE TITLE
Enable context menu in sandboxed iframe with srcdoc

### ISSUE THREAD

**Issue by twschiller** [pixiebrix/pixiebrix-extension#7300]
## Describe the bug

- Customer CRM has an iframe using `srcdoc` and sandbox policy without `allow-scripts`
- The initial content script bootstrapper loads, but dynamic imports to load the rest fails due to lack of allow-scripts
- If `allow-scripts` is provided on the iframe, the whole content script loads properly
- However, you can't specify a contextMenu that matches srcdoc iframe (`*://*` does not match)

## To Reproduce

Run a server with: `python3 -m http.server` and `index.html` file.

Without allow-scripts (content script fails to fully load):
```html
<html>
<body>
  <iframe srcdoc="<p>Hello world!</p>" sandbox="allow-forms">
</body>
</html>
```

With allow-scripts:
```html
<html>
<body>
  <iframe srcdoc="<p>Hello world!</p>" sandbox="allow-forms allow-scripts">
</body>
</html>
```

## Actual behavior

<img width="903" alt="image" src="https://github.com/pixiebrix/pixiebrix-extension/assets/1879821/7f23fa2c-e162-43f8-8e20-7f4984aa1270">

## Discussion

- We're checking if the customer can relax the sandbox policy to include `allow-frames`
- If they're not able to, what are our options?
  - Provide a build where entire content script is loaded in frame (probably not possible due to large jq bundle size)
  - Watch for the iframe and alter the sandbox policy from the parent page. Is it possible to do that in time for the initial content script load? We might also be able to toggle a frame reload?
- It's possible to show the context menu without the content script in the frame because the context menu is managed by the background script. But the handler would fail because the menu action targets the frame: https://github.com/pixiebrix/pixiebrix-extension/blob/29b42d68ee0713f4efd0c82cdf3f7e650da9a963/src/background/contextMenus.ts#L88-L88
- What match pattern for the context menu would match `srcdoc` iframes? Do we need `<all_urls>`? See https://developer.chrome.com/docs/extensions/reference/api/contextMenus#method-create

**Comment by twschiller** [comment]
@fregante any ideas on the: srcdoc match pattern for context menu (does it need to be `<all_urls>`) and tricks for handling the sandboxed srcdoc iframe?

**Comment by fregante** [comment]
The curious part is that contentScripts is loading, but webpack deferred bundles are being blocked. My guess is that it's a bug

As for the pattern, yes `*://*/*` exclusively matched http and https.

**Comment by twschiller** [comment]
Investigation so far:
- `<all_urls>` causes Chrome to show context menu on `srcdoc:`
- `dispatchMenu` calls `ensureContentScript` which fails for `srcdoc:`
- The context menu fails to run because the availability check fails (I opened issue here: https://github.com/fregante/webext-patterns/issues/13)

**Comment by fregante** [comment]
I think there's more, the extension already has `all_urls` as a global permission but I still see this when clicking on a context menu item on a srcdoc frame

<img width="551" alt="Screenshot 11" src="https://github.com/pixiebrix/pixiebrix-extension/assets/1402241/1cb2b2e4-de48-41fb-8001-dcfd9c7590bf">

Also useful badge 😃 

https://github.com/pixiebrix/pixiebrix-extension/assets/1402241/d98e5052-455a-4ed3-8e82-345bc08a6d1a

**Comment by fregante** [comment]
> in the frame because the context menu is managed by the background script

When I saw that the context menus were managed by the content script it was rather surprising to me. The logic around it appears to be complex and I remember seeing a few tickets for it.

Would it make sense to have the background page deal with this for every type of frame?

**Comment by fregante** [comment]
I think I got it, I'll self-assign

**Comment by fregante** [comment]
I'm also looking into the webpack issue.

Repro URL: https://ephiframe.vercel.app/?srcdoc=%3Ch1%3Ehello-srcdoc

(But to set the `sandbox` you have to edit the DOM)

**Comment by twschiller** [comment]
I'm meeting with our client tomorrow on prioritization. It turns out that the sandboxed editor is only in one place in their in-house CRM, so PixieBrix is working in the other places as expected (with content editables and TinyMCE)

**Comment by twschiller** [comment]
Kicking this back to "Next" status. Doesn't seem to be required for the client project anymore

**Comment by twschiller** [comment]
Clarified with the customer that the problem is a blocker to some use cases. Route to example editor in their sandbox detailed here: https://pixiebrix.slack.com/archives/C0671QASFMZ/p1706132384629469

We'll need to pick our option for overriding the allow-scripts sandbox attribute. Some options are:
1. Always override to allow PixieBrix to run in all frames normally sandboxed. (On page load and iframe element initialization with a sandbox, apply the sandbox policy adjustment)
2. Add as an option to to starter bricks to allow them to run in sandboxed iframes. If applies to the top-level frame on the tab, watch on all frames on the tab
3. Add a brick to adjusts the sandbox policy. Then users can wire up an load/initialize trigger that watches to adjust the sandbox policy
