### ISSUE TITLE
Slice 2: Add Rainforest test for “Set Toolbar Badge” Brick

### ISSUE THREAD

**Issue by grahamlangford** [pixiebrix/pixiebrix-extension#7311]
https://www.notion.so/pixiebrix/Phase-2-Add-Brick-for-Setting-Badge-in-Toolbar-04b12e551113443b9218317744dd864f?pvs=4#bd2f0969df43405b97bf2e95e02e05bc

**Comment by mnholtz** [comment]
Test is here: https://app.rainforestqa.com/tests/414926

It asserts:
- That the Toolbar Badge brick properly sets a badge on the current tab
- Sets a toolbar badge on a separate tab and confirms that the badges are independent of tab
- Page navigation removes the badge
