### ISSUE TITLE
Textareas sometimes missing labels

### ISSUE THREAD

**Issue by grahamlangford** [pixiebrix/pixiebrix-extension#7323]
## Describe the bug

We previously had an issue where Textareas that should not have a label were instead showing the field name (https://github.com/pixiebrix/pixiebrix-extension/issues/7106). This was due to a default in [RJSF](https://github.com/rjsf-team/react-jsonschema-form/blob/e8aa9e8f2078d86a6048ff3d018bd3030d8d2aba/packages/core/src/components/fields/SchemaField.tsx#L196). As a workaround, we switched the [FieldTemplate](https://github.com/pixiebrix/pixiebrix-extension/blob/dc328e8e565634b9d03deffa51e6cbda9960bdab/src/components/formBuilder/FieldTemplate.tsx#L79) to only use the `title` prop. Unfortunately there are some use cases where we still need to use the label prop.

## To Reproduce

1. Install the [AI Copilot ](https://www.pixiebrix.com/marketplace/8bbefac2-876c-4196-97e5-3fd44ce919e7/ai-copilot/)
2. Pick a prompt from the dropdown

## Actual behavior

The textareas appear without labels

## Expected behavior

The textareas appear with the labels defined in the mod (or Google Sheet if a sheet is linked)

## Screenshots/Loom

![image](https://github.com/pixiebrix/pixiebrix-extension/assets/30706330/a6f99916-b026-471b-8b31-b7f15366de7f)

## Desktop (please complete the following information):

- Extension Version 1.8.6

## Implementation Sketch
Default to using the `label` prop if the label is not the same as the name, otherwise fallback to the `title` prop.
https://github.com/pixiebrix/pixiebrix-extension/blob/dc328e8e565634b9d03deffa51e6cbda9960bdab/src/components/formBuilder/FieldTemplate.tsx#L79

**Comment by twschiller** [comment]
@grahamlangford making this change will then cause a regression in other mods as the field name will now show? Or is this unrelated to the property name for the field in the RJSF schema?

If the AI Copilot mod is the only mod impacted, we might just want to change the AI Copilot mod to pass in a title field in the dynamic JSON Schema

**Comment by fungairino** [comment]
We don't have a direct reference to the field name, but we could use `id` in `formBuilder/FieldTemplate` as a proxy.

However I'm not sure the suggested implementation in the issue will work, as in testing with the AI Copilot mod, the text field label is still not displayed (the name is still the same as the label).

 I think we need to enforce setting the field's configured displayLabel to false if there is no label in the formBuilder, or fix the specific cases like the AI Copilot to have the title specifically set for those dynamic fields.

I was able to fix the described issue for the mod by just fixing the `jq` processor statement to include the `title` value in the rjsf props, so maybe we can just fix it there until we get around to improving how we handle these forms.
