### ISSUE TITLE
Copy to Clipboard focus issue in MV3 Side Panel

### ISSUE THREAD

**Issue by grahamlangford** [pixiebrix/pixiebrix-extension#7324]
## Describe the bug

When using `Copy to Clipboard` in the MV3 Side Panel, the brick runs when the main window doesn't have focus (because the sidebar has focus). This causes the "Click anywhere to copy text to clipboard" alert to be displayed so that the main window gets the focus needed to copy to the clipboard
 
## To Reproduce

1. In KB Assist, click the `Restarting PixieBrix` button
2. Click `Copy to Clipboard` in the temporary panel that opens

## Actual behavior

Observe that the Click anywhere to copy text to clipboard alert is displayed

## Expected behavior

The content should be copied without need for further user interaction

## Screenshots/Loom

![image](https://github.com/pixiebrix/pixiebrix-extension/assets/30706330/2f9d1d30-0775-4a60-bc04-11c488749c94)

## Desktop (please complete the following information):

- MV3

## Additional context

- https://pixiebrix.slack.com/archives/C06CD8TRM6E/p1704987239264749
- First noted in the https://github.com/pixiebrix/pixiebrix-extension/pull/7320

**Comment by fregante** [comment]
I noticed that in the last couple of issues you opened the image can't be parsed. How are you generating those PNGs?

<img width="287" alt="Screenshot 4" src="https://github.com/pixiebrix/pixiebrix-extension/assets/1402241/45a49ac3-ac87-4577-bc5d-82c87e734407">

If I request that page, I get "Non-Image content-type returned"

**Comment by twschiller** [comment]
> I noticed that in the last couple of issues you opened the image can't be parsed. How are you generating those PNGs?

Image is working for me. @fregante might be a problem on your end? I'm assuming @grahamlangford is pasting into the GitHub markdown editor from clipboard

**Comment by fregante** [comment]
The image is being copy-pasted from Zenhub, which I'm not logged into, it's not uploaded to GitHub

<img width="894" alt="Screenshot 7" src="https://github.com/pixiebrix/pixiebrix-extension/assets/1402241/5658fb82-9443-4b99-afd2-9eea07a1e36b">

**Comment by grahamlangford** [comment]
That's what it is. I'm creating the issues through ZenHub, so when I copy them in, they get added as ZenHub images. I'll add images outside ZenHub going forward.

**Comment by grahamlangford** [comment]
We use ZenHub to prioritize issues and track Cycle Time and other metrics.

**Comment by grahamlangford** [comment]
@fregante You should be able to see the image now. If there are any others you can't see that you need, please flag them for me and I'll fix them.

**Comment by fregante** [comment]
While this is a new limitation, what can really be done here? The core issue is the same as:

- https://github.com/pixiebrix/pixiebrix-extension/pull/5362

So the solution is the same: show a "click to copy" dialog.

The only other solution I can think would be to always run the `copy to clipboard` brick locally instead of in the puppeteering content script. This could also work in the case above too.

Alternatively, if we're lucky, we can try calling `window.focus()` before `copyToClipboard()`. Worth a shot.

**Comment by grahamlangford** [comment]
> Alternatively, if we're lucky, we can try calling window.focus() before copyToClipboard(). Worth a shot.

I'd be very surprised if it worked, but it definitely is worth trying. Would be way better UX.

**Comment by twschiller** [comment]
> The only other solution I can think of would be to always run the copy to clipboard brick where then last click happened instead of in the puppeteering content script

I think we'll end up exploring that route because the `"click to copy" dialog` is confusing to users/mod creators.

Moving clipboard permission as a required permission might also solve the problem?

**Comment by fregante** [comment]
> can try calling `window.focus()` before `copyToClipboard()`.

Nope. Chrome didn't like that

**Comment by grahamlangford** [comment]
> Moving clipboard permission as a required permission might also solve the problem?

@fregante have we tried this yet? If it worked, we would also need to consider if requiring that permission is going to disable the Extension for existing users. We have a method to test that documented here: https://www.notion.so/pixiebrix/Testing-Manifest-json-changes-c60283073fba40d98ee28cdeab19b04a

**Comment by fregante** [comment]
My extension has had that permission for the whole week but you can see I still get prompted in #7471's screenshots. 

I'll look into this issue later this week if you don't do it first. #7471 is related but does not address it in any way.

**Comment by grahamlangford** [comment]
> My extension has had that permission for the whole week but you can see I still get prompted in #7471's screenshots.
> 
> I'll look into this issue later this week if you don't do it first. #7471 is related but does not address it in any way.

Good to know. Please do look into it. I doubt I'll have time until sometime next week at the earliest.

**Comment by fregante** [comment]
This is just a limitation of the API itself. The document must be focused even when we have the permission to write into the clipboard: https://stackoverflow.com/a/61977696

The only solution I see is this, but I don’t think I can help with it because it's part of the bricks runner:

> always run the `copy to clipboard` brick where then last click happened

**Comment by twschiller** [comment]
> What's the work involved in moving the execution to the sidebar? It would solve this issue at the root and work towards your "PixieBrix anywhere" future. Is this possible? I think your PR basically does that?

It's theoretically possible, but the issue is that we want the button click action to run in the context of the page (e.g., for extracting information, confetti, etc.). If we want those actions to run in the sidebar, we'd need to introduce a new notion of target
