### ISSUE TITLE
AA Brick Configuration: fix caching and stale value handling when changing/updating integration

### ISSUE THREAD

**Issue by grahamlangford** [pixiebrix/pixiebrix-extension#7325]
### Update 4/17
The issues in the initial description here were fixed by #8207, but there's still an issue with refreshing the bot list when the integration changes, if there's already a selected value in the bot field.

Steps:
1. Open Run Bot brick in page editor
2. Select an integration
3. Select a bot from the list
4. Change integrations to one that does not have access to the selected bot
5. Click the `x` to clear the bot input, and open the dropdown of options

Expected:
6. See list of valid bot options to choose from

Actual:
6. No options listed until user enters a search query

---

## Legacy ticket

Definition of Done
---
- [x] When the integration configuration changes (the id, or any value in the configuration), reset the options caches
- [x] Ensure widget error states are cleared when cached values are cleared
  - Context from @BLoe: "When you switch back to an integration that does _not_ have an error, and it CAN successfully fetch the list of options again, it still doesn't clear the error placeholder thing from the previous bullet point ☝️ If you combine the previous 2 bullets, it makes it very unclear that the dropdown list is working properly, because you see the error placeholder, and no options until you type a filter query"
- [x] Handle stale values
  - Context from @BLoe: Similarly, it's also unclear in cases where the drop is _not_ working. You can make a valid selection and then switch to another integration, and the list will show the error placeholder when you click, but the selection won't change and it'll keep the previous bot/task name selected in the field

Steps to Reproduce
- Graham: *Not totally sure how to reproduce this yet, but will try setting up an integration config with a folderId to see if the folderId is related to this issue (_see the folderId warning message in the screenshot above_)
  - Todd: I think the issue is that we invalidate the cache on changed configuration id, but not if the options for that configuration changed

Open Questions
---
- What should the UX be if a field references an option that's no longer valid. @BrandonPxBx thoughts? For example, we could automatically clear the field. Or we could keep the value and show an error annotation

Screenshots
---
<img width="536" alt="image" src="https://github.com/pixiebrix/pixiebrix-extension/assets/2801308/637e8072-7dc6-44a5-9f28-7f82277e65c0">

![image](https://github.com/pixiebrix/pixiebrix-extension/assets/2801308/9cb5dbee-8c30-4e42-aa80-81c0e86c7d3b)

**Comment by twschiller** [comment]
Related issue: 
- https://github.com/pixiebrix/pixiebrix-extension/issues/8198

**Comment by twschiller** [comment]
@BLoe I updated this to in progress because it seems like it's being worked on? https://www.notion.so/pixiebrix/Product-Engineering-Standup-2024-04-17-4f4baa2cedf24905a6596d4167c4a1f0?pvs=4#de4969eea3854bc7941d0184929ebafb. 

Or were you and @grahamlangford thinking that it won't actually be worked on?

**Comment by BLoe** [comment]
Thanks, sorry, should have moved this to in progress, my bad
