### ISSUE TITLE
[Spike] Support Icons in Document Builder Buttons

### ISSUE THREAD

**Issue by grahamlangford** [pixiebrix/pixiebrix-extension#7341]
Notion
---
https://www.notion.so/pixiebrix/Phase-1-Support-Icons-in-Document-Builder-Buttons-6da3d7f7742b4838ad7ad85b8afed8ac

AC
---
- [ ] Phase Spec signed off by all members of Approval Matrix
- [x] Issues created and added to the 1.8.7 Release
- [x] Issues added to the Sidebar UI Improvements Epic

**Comment by mnholtz** [comment]
Spec is ready for a first pass here: https://www.notion.so/pixiebrix/Phase-1-Support-Icons-in-Document-Builder-Buttons-6da3d7f7742b4838ad7ad85b8afed8ac#c3ecfeb7b4b04303b3c0fa950373bcdc

**Comment by mnholtz** [comment]
Issue is here: https://github.com/pixiebrix/pixiebrix-extension/issues/7345

Tentatively closing this & moving on to development in the consideration of time, despite needing a sign-off from Todd & Mike
