### ISSUE TITLE
Datadog sourcemaps not working in RainforestQA release builds

### ISSUE THREAD

**Issue by twschiller** [pixiebrix/pixiebrix-extension#7362]
Context
---
- Observed on 1.8.7-alpha.4

Discussion
---
- @johnnymetz you'll need to confirm which sourcemaps got uploaded for the actual release build
- The issues is there's a mismatch in domain between what gets called here: https://github.com/pixiebrix/pixiebrix-extension/blob/13f0d366dc040a5b7ddac0e2e1562981c00501c8/src/telemetry/initErrorReporter.ts#L103-L103 and the upload triggered from here: https://github.com/pixiebrix/pixiebrix-extension/blob/13f0d366dc040a5b7ddac0e2e1562981c00501c8/.github/workflows/release.yaml#L46-L46
- Upload uses the S3 URL,  the code reporter rewrites stack traces to use `extension://dynamichost/`

Screenshots
---

<img width="1058" alt="image" src="https://github.com/pixiebrix/pixiebrix-extension/assets/1879821/c8aca70d-9999-4a4f-a975-e9e23fff9c93">

<img width="794" alt="image" src="https://github.com/pixiebrix/pixiebrix-extension/assets/1879821/a0e4da91-a635-4d63-8c52-4efe4bde2da2">

**Comment by johnnymetz** [comment]
Both the mv2 and mv3 build logs show `sourceMapPublicUrl` is set:
- mv2: https://github.com/pixiebrix/pixiebrix-extension/actions/runs/7563418803/job/20595791849#step:5:28
- mv3: https://github.com/pixiebrix/pixiebrix-extension/actions/runs/7563418803/job/20595792088#step:5:28

So not sure how it's nullish here: https://github.com/pixiebrix/pixiebrix-extension/blob/13f0d366dc040a5b7ddac0e2e1562981c00501c8/webpack.config.mjs#L218-L219

**Comment by twschiller** [comment]
cc @fregante

**Comment by fregante** [comment]
There is no `dynamichost` string in the zip file produced by that run (build-production.zip). Did you upload that bundle? 

https://github.com/pixiebrix/pixiebrix-extension/actions/runs/7563418803

**Comment by fregante** [comment]
`build-production.zip` includes sourcemaps URLs like this one, which is valid and it exists:

```
//# sourceMappingURL=https://pixiebrix-extension-source-maps.s3.amazonaws.com/sourcemaps/build/c0e5cacc39b865790973c99cac04ebc523db8ecf/mv2/browserActionInstantHandler.js.map
```

**Comment by twschiller** [comment]
Hmm, not sure how these could get out of sync:

- Value that's submitted in errors comes from here: https://github.com/pixiebrix/pixiebrix-extension/blob/13f0d366dc040a5b7ddac0e2e1562981c00501c8/webpack.config.mjs#L219-L219
- Value that's in the build comes from here: https://github.com/pixiebrix/pixiebrix-extension/blob/13f0d366dc040a5b7ddac0e2e1562981c00501c8/webpack.config.mjs#L171-L171

> There is no dynamichost string in the zip file produced by that run (build-production.zip). Did you upload that bundle?

Hmm, that's odd - that's a good place to dig into first. We'd expect to see that string somewhere in there

**Comment by johnnymetz** [comment]
Re-opening because this is still broken

**Comment by johnnymetz** [comment]
Running the rainforest qa job manually didn't work. The `{{ github.sha }}` value is `b120c2a2470da2f478201204e8f878137a7361e9` which is not present in datadog (see [here](https://app.datadoghq.com/source-code/setup/rum?search=b120c2a2470da2f478201204e8f878137a7361e9%20&config_rum_sourcemap_mgmt=true&filters=%7B%22service%22%3A%5B%22pixiebrix-browser-extension%22%5D%7D&mapkind=js&page=1)).

**Comment by fregante** [comment]
> which is not present in datadog

Isn't that a matter of uploading the sourcemaps in the `rainforest.yml` workflow?

**Comment by twschiller** [comment]
> Isn't that a matter of uploading the sourcemaps in the rainforest.yml workflow?

We could if we wanted too. I'm not aware there's any problems with uploading extra source maps to Datadog (e.g., if there's a max size across all maps/if we were to get billed for them)

**Comment by johnnymetz** [comment]
Still not working

**Comment by fregante** [comment]
Is their support helping? They can probably see what information they're missing and what we're doing wrong

**Comment by grahamlangford** [comment]
> Is their support helping? They can probably see what information they're missing and what we're doing wrong

We've got an email chain with them that's been going on for a few weeks now. Most of the changes have been at their suggestion.

**Comment by twschiller** [comment]
Unassigning because it's in the icebox
