### ISSUE TITLE
Page Editor: Cannot destructure property "blockId"

### ISSUE THREAD

**Issue by grahamlangford** [pixiebrix/pixiebrix-extension#7365]
## Describe the bug

NPE thrown in the Page Editor when viewing/editing `@pixies/demo/alert-if-over-limit`

## Screenshots/Loom

![image](https://github.com/pixiebrix/pixiebrix-extension/assets/30706330/99f09896-54d8-4eff-bd5d-079a66a03404)

## Desktop (please complete the following information):

- Extension Version `1.8.7-alpha.3`

## Additional context

https://pixiebrix.slack.com/archives/C0436P48QHY/p1705499231482439

**Comment by twschiller** [comment]
Triaging:
- Only happened to Mike once
- Other team members unable to reproduce

**Comment by mnholtz** [comment]
I cannot replicate either. However, I identified that this line in the `DataPanel` component is throwing the error: 

https://github.com/pixiebrix/pixiebrix-extension/blob/fa5165bf5b5cd5ff2036378e05d58c136f02b46c/src/pageEditor/tabs/editTab/dataPanel/DataPanel.tsx#L87-L93

Implying that `selectActiveNodeInfo` is returning `undefined` for some reason

**Comment by grahamlangford** [comment]
@mnholtz We can close for now and re-open if we see this again.
