### ISSUE TITLE
Show loading overlay and “no longer available” overlay on persistent panels

### ISSUE THREAD

**Issue by fregante** [pixiebrix/pixiebrix-extension#7369]
The content of the sidebar will get stale and "non-interactive" after navigation: it will stay that way until the new page reached `document_idle` and the content script ran. This means it stays stale for several seconds.

## Possible solutions

- make the sidebar app less dependent on the content script so that some panels can operate without contacting the content script
- detect the "unload" event and empty the sidebar

## Related

- Slice 2 defined in: https://www.notion.so/pixiebrix/Phase-1-PixieBrix-sidebar-in-Chromium-Side-Panel-d95485473005421db945142bfa792568
- Follows https://github.com/pixiebrix/pixiebrix-extension/issues/7228
- Follows https://github.com/pixiebrix/pixiebrix-extension/pull/7354

**Comment by twschiller** [comment]
Created phase spec here to allow for team discussion: https://www.notion.so/pixiebrix/Phase-2-gracefully-handle-non-SPA-navigation-in-the-Chromium-Side-Panel-0efdedb6c1e44b088e65106202e08c28?pvs=4

I suspect this will be done in a couple slices, to handle temporary panels/forms and behavior for persistent sidebars

**Comment by grahamlangford** [comment]
Superseded by https://github.com/pixiebrix/pixiebrix-extension/issues/8209
