### ISSUE TITLE
Some bricks causing RJSF to infinite loop on shouldRender locally

### ISSUE THREAD

**Issue by grahamlangford** [pixiebrix/pixiebrix-extension#7417]
## Describe the bug

When running AI Copilot locally, running a prompt appears to trigger an infinite loop in an RJSF call to shouldRender. This does not appear to happen in production builds. 

## To Reproduce

1. Run the Extension locally
2. Install the [AI Copilot](https://app.pixiebrix.com/activate?id=@pixies/ai/chatgpt-sidebar)
3. Run a prompt

## Actual behavior

The Extension freezes (see loom)

## Expected behavior

The prompt runs successfully. The Extension continues running normally

## Screenshots/Loom

https://www.loom.com/share/a8341e68fc914b54a09f46714f1fb651

## Additional context

- https://pixiebrix.slack.com/archives/C06CD8TRM6E/p1704990238648849

**Comment by twschiller** [comment]
Due to React running useEffect twice on development builds? https://github.com/facebook/react/issues/24502 Or is that only React 18?

**Comment by fregante** [comment]
This is exactly what's happening. It's comparing two FiberNode objects:

- https://github.com/rjsf-team/react-jsonschema-form/issues/1693

The last comment in that thread shows a possible fix, it might be due to `React.memo`?

**Comment by grahamlangford** [comment]
Since this only appears to impact development builds, I'm not prioritizing immediately. But I'll try to get it into the backlog sooner rather than later.

**Comment by fregante** [comment]
Yeah I can't repro in production. I've also seen this in the KB Assist brick while debugging #7324, it's making it slow to work on the sidebar 

<img width="344" alt="Screenshot 8" src="https://github.com/pixiebrix/pixiebrix-extension/assets/1402241/4d2442f1-a6d1-44ef-8c09-491223c6bdf2">

**Comment by grahamlangford** [comment]
> Yeah I can't repro in production. I've also seen this in the KB Assist brick while debugging https://github.com/pixiebrix/pixiebrix-extension/issues/7324, it's making it impossible to work on the sidebar. Sometimes I open the sidebar and it freezes

Noted. In that case I'm bumping it up.
