### ISSUE TITLE
MV2 sidebar regressions

### ISSUE THREAD

**Issue by fregante** [pixiebrix/pixiebrix-extension#7420]
- [x] `UPDATE_SIDEBAR` and the successive `SIDEBAR_PING` events are dispatched when the sidebar is closed via browser action

<img width="548" alt="Screenshot" src="https://github.com/pixiebrix/pixiebrix-extension/assets/1402241/27c38d43-c4c6-4673-8ea2-64fad46739aa">

**Comment by twschiller** [comment]
@fregante what's the impact here? Presumably, this needs to be addressed prior to the next release?

**Comment by grahamlangford** [comment]
> @fregante what's the impact here? Presumably, this needs to be addressed prior to the next release?

We detected no user-facing impact of the MV3 Side Panel merge. But we didn't do any long running tests. Are there performance implications?

**Comment by fregante** [comment]
No direct user impact for that specific item, but presumably it's automatically reported to rollbar right?

**Comment by johnnymetz** [comment]
I don't see this error in datadog error tracking: https://app.datadoghq.com/logs/error-tracking

**Comment by fregante** [comment]
Closing for now, no glaring issues 🙌
