### ISSUE TITLE
[Spike] Phase 0 Spec for Business Onboarding

### ISSUE THREAD

**Issue by grahamlangford** [pixiebrix/pixiebrix-extension#7422]
Phase Spec
---
https://www.notion.so/pixiebrix/Phase-0-deliver-target-mods-to-business-users-during-onboarding-b3607b032f68499fa4372cbf337ba135

Acceptance Criteria
---
- [x] Slices specified
- [ ] Approval Matrix signed off
- [x] Slices converted to issues
- [x] Issues added to `Business Onboarding` Epic
- [ ] Tech Lead notified for prioritization

**Comment by mnholtz** [comment]
New issues here:
- https://github.com/pixiebrix/pixiebrix-app/issues/4631
- https://github.com/pixiebrix/pixiebrix-app/issues/4632
