### ISSUE TITLE
Error showing form in sidebar in MV3

### ISSUE THREAD

**Issue by twschiller** [pixiebrix/pixiebrix-extension#7467]
## Describe the bug

Error when showing form in sidebar

> Error getting information for form: This target is not in a frame

## To Reproduce

1. Add Quick Bar Item Starter Brick
2. Add Show Sidebar Brick
3. Add Show a Modal or Sidebar Item brick
   - Target: sidebar

## Actual behavior

An error is shown:

![image](https://github.com/pixiebrix/pixiebrix-extension/assets/1879821/1b7444d1-ef7f-4f1f-94f4-f9f2ef47c473)

## Expected behavior

Form shows

## Desktop (please complete the following information):

Main: f0607dfc0062781e7fbd2035f65cc2197500b9e9

**Comment by fregante** [comment]
There are similar situations where this might happen. Do you see anything else that might open in the sidebar? https://github.com/search?q=repo:pixiebrix/pixiebrix-extension%2520set(%22opener%22&type=code
