### ISSUE TITLE
[Spike] Allow teams to restrict access to certain URLs unless PixieBrix is authenticated

### ISSUE THREAD

**Issue by grahamlangford** [pixiebrix/pixiebrix-extension#7474]
Notion 
---
https://www.notion.so/pixiebrix/Allow-teams-to-restrict-access-to-certain-URLs-unless-PixieBrix-is-authenticated-e3b29cdfa553424bb5abc8aee79c4d1c

AC
---
- [x] Slices specified
- [x] Approval Matrix signed off
- [x] Slices converted to issues
- [x] Issues added to `Anti-Fraud Use Cases` Epic and `1.8.8` release
- [x] Tech Lead notified for prioritization

**Comment by mnholtz** [comment]
GH Issues Created here:
- Slice 1: https://github.com/pixiebrix/pixiebrix-app/issues/4669
- Slice 2: https://github.com/pixiebrix/pixiebrix-extension/issues/7483
- Slice 3: https://github.com/pixiebrix/pixiebrix-app/issues/4670

Still awaiting @twschiller's explicit approval to close out the issue
