### ISSUE TITLE
Mods are not automatically activated

### ISSUE THREAD

**Issue by johnnymetz** [pixiebrix/pixiebrix-extension#7484]
## Describe the bug

Shane from AA is reporting that mods are NOT automatically activated. He needs to manually activate them.

See email from Shane called "Mod Activation" (Todd, Johnny, Graham, Mark are cc'd on it)

## To Reproduce

_This is reported by Shane. Still need to reproduce._

- Use a team connected to an AA Control Room
- Create new deployment
- Notice the deployment is pushed to the Control Room as an "Extension"
- Assign the deployment to a Control Room Team that your user is a part of

## Actual behavior

After several min, the mod from the deployment is NOT activated in the user's Extension Console

## Expected behavior

After several min, the mod from the deployment is activated in the user's Extension Console

## Screenshots/Loom

If applicable, add screenshots/looms to help explain your problem.

## Desktop (please complete the following information):

- OS: [e.g. OSX, Windows 10, Windows 11]
- Browser [e.g. chrome, edge]
- Extension Version [e.g. 22]

## Additional context

- What mod(s) were you running?
- What website(s) were you using?
- Do you need any special permissions to reproduce?
  - Access to a Control Room?
  - Membership on a specific team?

**Comment by johnnymetz** [comment]
Investigation Notes / Summary: https://www.loom.com/share/511f2017688346479378b8a5514b0112

**Comment by johnnymetz** [comment]
All 4 mods from Shane's email installed automatically.

Note, hijacking the user didn't fetch any deployments. I imagine it's because I didn't have a valid JWT for the user. What did work was copying the mods, creating them under my team "Team Metz" that has a linked Control Room, adding them to a deployment and adding those deployment to the Control Room team. My Extension fetched the deployments and installed them automatically after a few min.

**Comment by twschiller** [comment]
Capturing that the behavior seen is likely fixed by: https://github.com/pixiebrix/pixiebrix-extension/pull/7482

**Comment by johnnymetz** [comment]
Shane reported this is no longer an issue. And I wasn't able to reproduce.
