### ISSUE TITLE
Improve page editor responsive UI further

### ISSUE THREAD

**Issue by fregante** [pixiebrix/pixiebrix-extension#7558]
## Describe the bug

- Follows https://github.com/pixiebrix/pixiebrix-extension/pull/7464

As seen in that PR, some parts of the form don't wrap well in tight viewports and they might need to be reviewed.

This might be classified as `low priority` or `papercut`. However after the MV3 sidePanel migration, more people will see it since the page editor will be smaller when the sidePanel is open.

## To Reproduce

1. Create Sidebar panel
2. Leave both page editor sidebars open
3. Make window tight enough that components feel cramped

## Actual behavior

<img width="322" alt="Screenshot 11" src="https://github.com/pixiebrix/pixiebrix-extension/assets/1402241/3aa48b25-d8e1-421e-9db2-51d0a1794b1e">

<img width="267" alt="Screenshot 10" src="https://github.com/pixiebrix/pixiebrix-extension/assets/1402241/a793a78d-77a4-4160-ba41-a622b74de0ee">

## Expected behavior

They should wrap earlier.

## Related

- https://github.com/pixiebrix/pixiebrix-extension/issues/4914

**Comment by fregante** [comment]
These two fields were also affected until #7464 was merged:

<img width="335" alt="Screenshot 19" src="https://github.com/pixiebrix/pixiebrix-extension/assets/1402241/33be2e1e-f8f5-483c-b3e2-093d692aa7b4">


<img width="394" alt="Screenshot 18" src="https://github.com/pixiebrix/pixiebrix-extension/assets/1402241/3dff9413-a8c2-4dc0-98bc-29683ea9ae80">


Now they don't suffer the same exact issue, but in one specific resolution they might end up in this layout instead (between 1516px and 1528px)


<img width="622" alt="Screenshot 21" src="https://github.com/pixiebrix/pixiebrix-extension/assets/1402241/f553def6-4c93-4528-965b-123b4fa6db9d">

**Comment by BrandonPxBx** [comment]
The gap between the label and the input is too great once wrapped. However, this change is sorely needed, IMO. There's a bigger discussion going on about it, so copying Todd for visibility. CC @twschiller

**Comment by fregante** [comment]
> The gap between the label and the input is too great once wrapped

True, there's a PR open to fix that. You can see the before/after in it:

- https://github.com/pixiebrix/pixiebrix-extension/pull/7597
