### ISSUE TITLE
Google login window pops up without explicit user action

### ISSUE THREAD

**Issue by fregante** [pixiebrix/pixiebrix-extension#7564]
## Describe the bug

Users of this brick are expected to eventually log into their Google account, but if they can't or don't want to, they'll be presented with a popup every time that component is loaded.

## To Reproduce

1. Add "Add Google Sheet row" brick
2. Select it (maybe select account first?)

## Actual behavior

A new login window is opened every time the brick is selected

## Expected behavior

The login window should only appear when the user explicitly clicks "Connect Google Account" (which also works)

## Screenshots/Loom

https://github.com/pixiebrix/pixiebrix-extension/assets/1402241/94c9ecbd-f912-4bbe-8e4f-45f9b3d42c77

## Desktop (please complete the following information):

- OS: macOS Sonoma
- Browser: Chrome
- Extension Version: 1.8.8 (I've been seeing this for a while though)

**Comment by twschiller** [comment]
Thanks for reporting. We will also be looking at this in the context of mod users, so show an on-screen notice that the user has to engage with prior to showing the popup.

**Comment by BrandonPxBx** [comment]
I'm good with explicitly requiring user action to launch the login window. 👍

**Comment by fregante** [comment]
> show an on-screen notice

In my demo the popup seems to be triggered by the sheets picker. I'd say that rather than a notice/banner/modal, the sheets picker should just show a "connect to google" button or something like that.

**Comment by fregante** [comment]
I wasn't immediately able to decouple the UI from the `browser.identity.launchWebAuthFlow()` call in `codeGrantFlow.ts`.

If the user cancels the login, they're shown this message:

<img width="400" alt="Screenshot 3" src="https://github.com/pixiebrix/pixiebrix-extension/assets/1402241/c28c9f50-1595-423e-9fc4-c0cbe1bc6f87">

We can slightly alter it and show it without triggering the login popup, using the bootstrap "info" alert instead of the "error" alert seen above:

<img width="400" alt="Screenshot 4" src="https://github.com/pixiebrix/pixiebrix-extension/assets/1402241/dd4e1804-0a25-4b88-a92f-540267bfc766">

But actually I think we already have something like this for other integrations, right?

<img width="400" alt="Screenshot 5" src="https://github.com/pixiebrix/pixiebrix-extension/assets/1402241/930bfcd9-62d6-4726-928d-16186d6c10be">

**Comment by twschiller** [comment]
We're working on the specification here, focusing first on end-user experience: https://www.notion.so/pixiebrix/Phase-require-user-gesture-before-displaying-Google-and-other-OAuth2-PKCE-popups-69650e3985ab4d4785b9e1cf3578c9cd?pvs=4

**Comment by fregante** [comment]
Yes, it's kind of why I posted this here.

> show an on-screen affordance for the user to click to launch the flow

The on-screen affordance can be a button, like we do everywhere else in the extension. 👍

**Comment by BrandonPxBx** [comment]
My main concern with just a button is there is already a ton of blue on the screen. I am not sure it's going to stand out enough for something that is functionally breaking the mod

**Comment by twschiller** [comment]
Fixed for the content script in 1.8.11
