### ISSUE TITLE
MV3 `sidePanel` breaks support for content script in iframes

### ISSUE THREAD

**Issue by fregante** [pixiebrix/pixiebrix-extension#7565]
Note: This might not be officially supported, but it still sends errors our way.

## Context (MV2)

You can create iframes in the sidebar:

<img width="231" alt="Screenshot 8" src="https://github.com/pixiebrix/pixiebrix-extension/assets/1402241/f6881104-ed0a-41c2-899c-098ce3e8766c">

The iframes actually receive the content script too:

<img width="410" alt="Screenshot 9" src="https://github.com/pixiebrix/pixiebrix-extension/assets/1402241/12c3cd4c-e9b0-409a-a08d-842c4e44a35f">

## Problem (MV3)

Iframes loaded in the `sidePanel` do not have a `tabId`/`frameId`, which breaks a lot of our expectations. So the content script fails to load in there:

<img width="805" alt="Screenshot 10" src="https://github.com/pixiebrix/pixiebrix-extension/assets/1402241/798967c9-784e-426f-bf4e-6a07a73e9825">

## Solutions

- Detect and prevent execution of content scripts in tab-less frames
	- This also solves the `TypeError: This target is not in a frame` errors we're seeing in DataDog
	- This slightly delays the execution of the entire content script because we have to ping the background page to have this information
	- The alternative is to have it fail and just silence the errors, potentially leading to a broken UI
- Instead of breaking the entire content script, catch and handle `getThisFrame` errors gracefully (e.g. "You can't open the sidebar from this frame")

We appear to have zero information regarding this frame so we have no way to link it to its tab:

<img width="853" alt="Screenshot 11" src="https://github.com/pixiebrix/pixiebrix-extension/assets/1402241/7af746fb-40fb-41cd-98d0-ad40221fd069">

At some point I saw `tabId: -1, frameId: 360` in the logs, but I don't know where that came from. This might be a browser bug.

## Additional context

`getThisFrame` is generally required for cross-frame communication, for example when creating a modal iframe or when opening the sidebar from an iframe:

- https://github.com/pixiebrix/pixiebrix-extension/pull/7490

**Comment by fregante** [comment]
This API might help in the future (if it can get its own frame), but it's not yet available in Chrome:

- https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/runtime/getFrameId

Other APIs:

- `webNavigation.getAllFrames()`: no, it requires a `tabId`
- `runtime.getContexts()`: no, it only returns `chrome-extension://` contexts

**Comment by twschiller** [comment]
We don't need to support running content scripts in tab-less frames.

> This slightly delays the execution of the entire content script because

What's the expected delay? (I think it's less than 5ms generally?). If the delay is small, I'd be in favor of adding the delay until `runtime.getFrameId()` or similar is available

For the sidebar case in particular, is there something we can set on the iframe itself? (Query parameter might not be a good idea, because it could interfere with 3rd party site behavior in the frame)
