### ISSUE TITLE
`TypeError: This target is not in a frame` reported thousands of times in DataDog

### ISSUE THREAD

**Issue by fregante** [pixiebrix/pixiebrix-extension#7566]
I'm opening this issue to organize the discussion around it.

I'm certain it's coming from an iframe either on the background page or in the page editor. However it's hard to determine where exactly the iframe is being created because tab-less iframes provide zero information about their parent:

> <img width="853" alt="Screenshot 11" src="https://github.com/pixiebrix/pixiebrix-extension/assets/1402241/43ed364d-b512-479c-9fd6-7ae35b15d861">

The updated "This target is not in a frame" error might just tell us what URL is being loaded, and maybe we recognize it (e.g. googleapis.com) like we've seen in:

- https://github.com/pixiebrix/pixiebrix-extension/pull/6598

## Demo error

<img width="805" alt="Screenshot 10" src="https://github.com/pixiebrix/pixiebrix-extension/assets/1402241/ff74db96-3ddc-4077-a4e8-793f4bb419da">

## PRs opened to debug this issue

- https://github.com/pixiebrix/pixiebrix-extension/pull/7559
- https://github.com/pixiebrix/pixiebrix-extension/pull/7557

## Related issues (its solutions include silencing the error, which also applies here)

- https://github.com/pixiebrix/pixiebrix-extension/issues/7565

**Comment by fregante** [comment]
New finding: It looks like it was seen on January 18th:

- https://github.com/pixiebrix/pixiebrix-extension/issues/7362

Which is before the `sidePanel` PR was merged on January 24th:

- https://github.com/pixiebrix/pixiebrix-extension/pull/7354

Which means it's not a new issue caused by the large refactoring made in that PR (which touched `getThisFrame`)

However I don't know if that PR exacerbated it in 1.8.8

**Comment by grahamlangford** [comment]
Note, we were seeing this in 1.8.7-beta.2 as well. (Earliest I can search in DataDog). 

@johnnymetz are we able to check our Rollbar dump to see if we can find this error and how far back it goes?

**Comment by johnnymetz** [comment]
> are we able to check our Rollbar dump to see if we can find this error and how far back it goes

Yes, it goes as far back as the data dump goes, which is Dec 26, 2023

**Comment by grahamlangford** [comment]
Can't tell from the dump what the version was, but 1.8.6 and 1.8.7 were released during that time frame (1.8.7 was January 24). Based on raw numbers, I think it's safe to assume it went back at least to 1.8.6, possibly earlier.

**Comment by grahamlangford** [comment]
As of 1.8.9, we now have additional logging:

```
TypeError: This target is not in a frame (context: contentScript, url: https://ogs.google.com/u/0/widget/app?awwd=1&gm3=1&origin=https%3A%2F%2Flens.google.com&cn=app&pid=269&spid=594&hl=en)
	./node_modules/webext-messenger/distribution/thisTarget.js at line 125:15
	./src/contentScript/lifecycle.ts at line 575:9
	./src/contentScript/lifecycle.ts at line 664:23
````

**Comment by fregante** [comment]
I have fresh info thanks to #7598:

<img width="842" alt="Screenshot 2" src="https://github.com/pixiebrix/pixiebrix-extension/assets/1402241/74a19024-6255-463f-89f3-5e3898a48599">

This is the popup opened by the "Add to Google Spreadsheets" brick, also seen in:

- #7564 

These are the two `getThisFrame` calls:

<img width="486" alt="Screenshot 3" src="https://github.com/pixiebrix/pixiebrix-extension/assets/1402241/770bd158-dece-43b9-8de0-28d10cf75ab3">

That popup actually has an iframe or two so each popup triggers a handful of errors, which might explain why we have so many. 

However the URL doesn't match the one you've seen, so there might be multiple scenarios in which this happens. Google's login system is very complex so it's likely it loads different pages for different people, especially as it sets the "logged in" cookie for multiple Google domains: https://webapps.stackexchange.com/q/30254/40770

I think the solution remains the same:

- abort the loading of `contentScriptCore` if `getThisFrame` fails

This can't go through the Messenger but it's actually a quick PING away. I'll work on it.

**Comment by fregante** [comment]
Other URLs include:

- https://accounts.google.com/_/bscframe
- https://accounts.youtube.com/accounts/CheckConnection?pmpo=https%3A%2F%2Faccounts.google.com&v=-139121&timestamp=17088835 (as seen in the stack exchange question)
- https://accounts.google.com/v3/signin/identifier?opparams=%253F&dsh=S503614747%3A17 etc
