### ISSUE TITLE
[Spike] Phase: create business user Lead Scoring and product activity notifications

### ISSUE THREAD

**Issue by grahamlangford** [pixiebrix/pixiebrix-extension#7591]
## Phase Spec

- https://www.notion.so/pixiebrix/Phase-create-business-user-Lead-Scoring-and-product-activity-notifications-cd361a7b80ed475e80c6ba3813900439

## Acceptance Criteria

- [x] Slices specified
- [x] Approval Matrix signed off
- [x] Slices converted to issues
- [x] Issues added to `Phase: create business user Lead Scoring and product activity notifications` epic
- [x] Tech Lead notified for prioritization

**Comment by mnholtz** [comment]
Slices created here:
- Slice 0: https://github.com/pixiebrix/pixiebrix-app/issues/4730
-  Slice 1: Rename #inbound-leads → #demo-requests (Zenhub issue)
- https://github.com/pixiebrix/pixiebrix-app/issues/4770
- https://github.com/pixiebrix/pixiebrix-app/issues/4771
- https://github.com/pixiebrix/pixiebrix-app/issues/4775
- https://github.com/pixiebrix/pixiebrix-app/issues/4776
- https://github.com/pixiebrix/pixiebrix-app/issues/4777

cc @grahamlangford
