### ISSUE TITLE
Send Slack Notification when Rainforest fails post merge

### ISSUE THREAD

**Issue by grahamlangford** [pixiebrix/pixiebrix-extension#7611]
Context
---
* We added post-merge runs of Rainforest here: https://github.com/pixiebrix/pixiebrix-extension/pull/7562
* Right now, without checking the Actions, there's no indication that Rainforest failed
* It would be nice to ping a channel (an possibly a specific user) in Slack when a Rainforest run fails post merge

Questions
---
* Should we use #engineering or a new channel? #rainforest-notifications?

**Comment by fungairino** [comment]
Maybe #engineering-notifications channel might be more appropriate? I do notice we have a lot of other separate notification channels (ex. #error-tracking-app). We might want to consider consolidating them into the same #engineering-notifications channel as well.
