### ISSUE TITLE
Form not registered error in form modal when working with iframes

### ISSUE THREAD

**Issue by twschiller** [pixiebrix/pixiebrix-extension#7631]
## Describe the bug

- Reported by 2 users
- https://pixiebrixcommunity.slack.com/archives/C02TS1K83EX/p1707805952753639

## To Reproduce

1. Activate `@pixies/7631-bug-repro`
2. Visit https://pbx.vercel.app/frames-builder.html
3. Click "Open Frame"

## Actual behavior

Modal shows in the iframe with `Form not registered: 4f2175d9-f272-40f1-b050-bcc8c9746b9b` message and the "Close" button doesn't work

## Expected behavior

For shows in the iframe

## Screenshots/Loom

Screenshot from `@pixies/7631-bug-repro` on https://pbx.vercel.app/frames-builder.html
![image](https://github.com/pixiebrix/pixiebrix-extension/assets/1879821/12506dbd-10c9-4df3-8eb8-7e27b7265afd)

Customer Screenshot
![image](https://github.com/pixiebrix/pixiebrix-extension/assets/1879821/c0281224-e7a4-46fc-90aa-e9a56e3d007a)

## Desktop (please complete the following information):

- Extension Version: 1.8.8, use reports it was working in 1.8.7

## Workaround

- A workaround it to change the form target to "Top-Level Frame"

**Comment by twschiller** [comment]
@fregante does anything jump to mind? I'm going to look through 1.8.8 PRs related to messaging

**Comment by fregante** [comment]
Yes this happened in the sidePanel migration, because I moved all those calls to also work from a non-tab frame (the sidePanel). I think all the calls were already getTopLevelFrame but if this is a regression then I must have changed some other too.
