### ISSUE TITLE
Scope dropdown is illegible in mod creation modal

### ISSUE THREAD

**Issue by twschiller** [pixiebrix/pixiebrix-extension#7640]
## Describe the bug

Mod conversion modal scope dropdown unusable

## To Reproduce

1. In mods screen, share a standalone mod component

Or, in the Page Editor

1. Add a standalone mod component to a new mod

## Actual behavior

See screenshot

## Expected behavior

Scope selection is legible

## Discussion

Probably makes sense to put the scope as a different field/row

## Screenshots/Loom

![image](https://github.com/pixiebrix/pixiebrix-extension/assets/1879821/4caf7811-5eca-4738-aa78-3eeb72d1cb36)

**Comment by fregante** [comment]
I think I gave the label too much width in general, it looks too wide in the page editor too. This can be fixed by reducing its minimum width globally, not just for this form
