### ISSUE TITLE
Allow opening multiple Mod Launcher tabs in sidebar

### ISSUE THREAD

**Issue by fregante** [pixiebrix/pixiebrix-extension#7646]
> Ideally, multiple "mod launcher" states will eventually be able to be opened. When a mod is selected from the mod launcher, it should take over that tab (in our case, I believe we're opening the mod and then closing the mod launcher tab). Think of it like Chrome - it doesn't limit you to a single new tab.

_Originally posted by @BrandonPxBx in https://github.com/pixiebrix/pixiebrix-extension/issues/6549#issuecomment-1742961879_

**Comment by twschiller** [comment]
There are no plans at this time to support multiple Mod Launcher tabs. Given limited horizontal space, not having excess tabs is important
