### ISSUE TITLE
Add text command popover behind skunkworks flag

### ISSUE THREAD

**Issue by twschiller** [pixiebrix/pixiebrix-extension#7671]
Context
---
- As a user, I want to insert text as I type quickly
- Once the auto-fill brick is added https://github.com/pixiebrix/pixiebrix-extension/pull/7669, I will be able to do that via the quick bar/side panel
- However, quick bar requires filtering through other commands, and the side panel involves clicking back and forth between the main page and sidebar (and mouse and keyboard)

Discussion
---
- If we wanted to continue using the quick bar, we could potentially have it sort/order based on whether the context where it was triggered is an "editable"
- However, the ergonomics of the quick bar aren't great for text editing because it's a dialog that occludes the screen

Related Issues
---
- This PR added experimental support for text selection actions: https://github.com/pixiebrix/pixiebrix-extension/issues/7665

**Comment by grahamlangford** [comment]
> ## Context
> * As a user, I want to insert text as I type quickly
> * Once the auto-fill brick is added [#7668: add experimental insert text at cursor brick #7669](https://github.com/pixiebrix/pixiebrix-extension/pull/7669), I will be able to do that via the quick bar/side panel
> * However, that

However, that ??

**Comment by twschiller** [comment]
> However, that ??

👍  Updated
