### ISSUE TITLE
Image Reader: Failed to execute 'toDataURL' on 'HTMLCanvasElement': Tainted canvases may not be exported.

### ISSUE THREAD

**Issue by fregante** [pixiebrix/pixiebrix-extension#7673]
## Describe the bug

I want to right click to copy an image to the clipboard. When it reaches the first brick (Image reader) is shows an error notification.

## To Reproduce

1. Add Context Menu for images
2. Add Image reader brick
3. Set Element as the `Target Root Mode`
4. Set `@input.element.ref` as the target element
3. Use the context menu on the "Your extension factory" image in https://www.pixiebrix.com/

## Actual behavior

<img width="395" alt="Screenshot" src="https://github.com/pixiebrix/pixiebrix-extension/assets/1402241/9f5c43d6-5932-4162-ae9e-dd400b641126">

## Expected behavior

The Data URL is passed to the next brick

## Screenshots/Loom

https://github.com/pixiebrix/pixiebrix-extension/assets/1402241/2e972bd5-2679-4fe8-93d9-52a6fc0bcb72

## Desktop (please complete the following information):

- OS: macOS
- Extension Version:
1.8.10-alpha.1-local+2024-02-20T07:23:25.116Z

## Related

I was testing:

- https://github.com/pixiebrix/pixiebrix-extension/issues/6812
- https://github.com/pixiebrix/pixiebrix-extension/pull/7635

**Comment by twschiller** [comment]
Very old context: https://github.com/pixiebrix/pixiebrix-extension/issues/452

**Comment by fregante** [comment]
I think the current situation is:

- same-origin images already work
- cross-origin images only work if CORS is enabled

It doesn't look like there's a way to determine whether an existing cross-origin `<img>` is safe to paint (https://stackoverflow.com/a/69231591/288906). We continue to _attempt_ to use canvas and then fall back to a simple `fetch -> blob -> data URL` conversion, which we also already have code for.

It's worth keeping the existing code (canvas) to avoid an additional download on same-origin images and the occasional CORS-enabled cross-origin image.
