### ISSUE TITLE
Fix flaky Jest tests

### ISSUE THREAD

**Issue by twschiller** [pixiebrix/pixiebrix-extension#7682]
- themeStore.test.ts
- `src/contentScript/selectionTooltip/tooltipController.test.ts`: "Unable to find an element by: [data-testid="pixiebrix-selection-tooltip"
- `src/contentScript/commandPopover/commandController.test.tsx`: "Unable to find role="menu"·
    Ignored nodes: comments"
- `src/components/documentBuilder/edit/DocumentOptions.test.tsx` (timeout)
- `TriggerConfiguration.test.tsx` (timeout): https://pixiebrix.slack.com/archives/C023KL47XV4/p1708528350765149?thread_ts=1708527811.076519&cid=C023KL47XV4
- `pixiebrix-extension/src/telemetry/logging.test.ts` (timeout):  https://pixiebrix.slack.com/archives/C023KL47XV4/p1708531094371059?thread_ts=1708527811.076519&cid=C023KL47XV4

**Comment by grahamlangford** [comment]
No longer seeing this issue
