### ISSUE TITLE
Switching back and forth from automation-anywhere does not change the favicon.

### ISSUE THREAD

**Issue by fungairino** [pixiebrix/pixiebrix-extension#7685]
## Describe the bug

If you remove "automation-anywhere" as your partner id in extension console settings, it should remove all automation
anywhere theming, but it does not remove the favicon in the tab.

## To Reproduce

1. Go to extension console settings
2. Set the Partner ID to "automation-anywhere" and click outside
3. Clear the Partner ID and click outside

## Actual behavior

Observe that the favicon is still the automation-anywhere favicon.

## Expected behavior

The displayed favicon should instead be the default Pixiebrix favicon.

## More details
Here is the relevant code:
https://github.com/pixiebrix/pixiebrix-extension/blob/4d5d5ef003654582426bbc4c2611c4cf9babb092/src/themes/themeUtils.ts#L98

**Comment by grahamlangford** [comment]
Good catch. I highly doubt this will occur frequently, so it's not a high priority. But we should still fix it.
