### ISSUE TITLE
Create Playwright utility for logging in to App

### ISSUE THREAD

**Issue by grahamlangford** [pixiebrix/pixiebrix-extension#7689]
* Account can be hard-coded
* `extension-e2e-test.unaffiliated@pixiebrix.com`
* Credentials should be made available via an environment variable so they can be overridden locally
* Add credentials to 1Password

Notes
--- 
- We already do this in App with a custom Cypress utility command
- Depending on implementation, we could potentially leverage [Page object models](https://playwright.dev/docs/pom)

Out of Scope
---
* GitHub Actions integration

**Comment by mnholtz** [comment]
Test account provisioned & added to 1password under "PixieBrix E2E Test Account Credentials"

**Comment by mnholtz** [comment]
Closed per https://github.com/pixiebrix/pixiebrix-extension/pull/7761
