### ISSUE TITLE
Handle iframes in text selection popver

### ISSUE THREAD

**Issue by twschiller** [pixiebrix/pixiebrix-extension#7707]
Open Questions
---
- Always show the popover on the top-level frame? 
  - If so, do actions come from the top-level frame, or the source frame? (The source frame is generally an editor frame, so if those actions are contributed, would likely only be 
- Approaches
  - Easiest change is to implement flip/shift middleware so popover still shows reasonably for the top line of the editor iframe
- Once we get the popover API working, I believe the top-layer still only applies to the iframe vs. the whole window?
 
Screenshots
---
The top placement is clipped due to the frame
![image](https://github.com/pixiebrix/pixiebrix-extension/assets/1879821/5179241f-e7e0-4f29-89c9-4145fcb2dbfd)

References
---
- Placement relative to iframe: https://github.com/floating-ui/floating-ui/issues/1711
- Grammarly appears to only put the popover on the top level frame

**Comment by fregante** [comment]
> Always show the popover on the top-level frame?

That's what TinyMCE seems to be doing by the way:

![no scrollbar](https://github.com/pixiebrix/pixiebrix-extension/assets/1402241/d5f614d3-f4a9-445b-bbee-b99df75a3402)


> * I believe the top-layer still only applies to the iframe vs. the whole window?

Correct. Imagine if iframes were able to paint over other parts of the page. 🤯

> The top placement is clipped due to the frame 
> ![image](https://private-user-images.githubusercontent.com/1879821/307537464-5179241f-e7e0-4f29-89c9-4145fcb2dbfd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg3OTYwOTcsIm5iZiI6MTcwODc5NTc5NywicGF0aCI6Ii8xODc5ODIxLzMwNzUzNzQ2NC01MTc5MjQxZi1lN2UwLTRmMjktODljOS00MTQ1ZmNiMmRiZmQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIyNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMjRUMTcyOTU3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ODg4YmNhMzBjZWM5ZmNlMjJkNDc2ODIxZTMzMTU2MzI0NTcwNzE5MmZkY2JiNTg1NDk5MGQzYjJhMGU1OWE1YiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.pquXvyvf6j4J6OsO-UOg8yIk5bYFlJPAm54jtelglKM)

Is it placed via the floating-ui component? Why isn't it being placed at the bottom as their demo suggest?

**Comment by twschiller** [comment]
Closing for now given that we're handling the flip. Will re-open or create new issue as we get feedback from the writing assist mod
