### ISSUE TITLE
Review Required/Optional keys of `Me` and `UserData` type

### ISSUE THREAD

**Issue by fregante** [pixiebrix/pixiebrix-extension#7725]
The types of `Me` seem to be incomplete. In the swagger file, no key is required, I don’t think this is the case in real life as actual users must be identified somehow, even if by a temporary UUID… right?

https://github.com/pixiebrix/pixiebrix-extension/blob/fe4f6abd4f36122129d5e4dce7cb74a2b8489b12/src/types/swagger.ts#L1187-L1194

The local Me type is specified at:

https://github.com/pixiebrix/pixiebrix-extension/blob/fe4f6abd4f36122129d5e4dce7cb74a2b8489b12/src/types/contract.ts#L62

`UserData` is likewise fully optional:

https://github.com/pixiebrix/pixiebrix-extension/blob/fe4f6abd4f36122129d5e4dce7cb74a2b8489b12/src/auth/authTypes.ts#L37

The biggest conflict I found is that in `selectUserDataUpdate`, the value of the return `email` is required, but the input is optional.

**Comment by fregante** [comment]
Also see the notes in https://github.com/pixiebrix/pixiebrix-extension/pull/7667/files#r1495965976

In short, `Required` isn't enough and is still leaving `null` values behind.

**Comment by grahamlangford** [comment]
cc @BLoe

**Comment by BLoe** [comment]
I'm working on cleaning this stuff up right now, I'll link my PR when I get a draft up soon

**Comment by BLoe** [comment]
Related ticket: https://github.com/pixiebrix/pixiebrix-extension/issues/7757
