### ISSUE TITLE
Text Selection popover doesn't run action in Gmail email composer

### ISSUE THREAD

**Issue by twschiller** [pixiebrix/pixiebrix-extension#7729]
## Describe the bug

Text selection popover over buttons don't work in Gmail email composer

## To Reproduce

- Enable the text selection popover
- Add a context menu for selection (e.g., one that shows the selected text as an alert)
- Open the email composer in Gmail
- Write "hello", select the text, and click your action

## Actual behavior

- Popover disappears but doesn't run

## Expected behavior

- Action runs and popover disappears

## Investigation

- What appears to happening is that upon clicking the the popover, the `selectionchange` event fires with an empty selection, so tooltipController calls hideTooltip. It likely calls the Abort before the click has a chance to run
- If you remove the `hideTooltip()` in the selectionchange handler, the action runs, but doesn't see any selected text

## Desktop (please complete the following information):

- https://github.com/pixiebrix/pixiebrix-extension/pull/7728

**Comment by fregante** [comment]
I can repro from the sidebar too. The strange part is that a plain `document.execCommand('insertText', false, 'hello')` works from the console, so focus/selection doesn't have to be a problem

**Comment by fregante** [comment]
A couple more demos showing the regular behavior:


![](https://github.com/pixiebrix/pixiebrix-extension/assets/1402241/6494e4d3-9e51-4028-9a67-f62de6c450e8)

and the broken behavior on Gmail:

![2](https://github.com/pixiebrix/pixiebrix-extension/assets/1402241/2fed0c9c-39a9-4846-bfed-4a70f1919bee)

**Comment by twschiller** [comment]
Reopening because it's still not generally working on 1.8.10-beta.2-mv3 on Chrome: https://www.loom.com/share/1934bedba08f43dd88066fd2fea11f25?sid=5cb7826f-d245-4264-8dc7-a91e43f93602

@fregante should I give MV2 a try?

**Comment by twschiller** [comment]
> Side note: The logic in these two should be combined.

Which two are you referring to? The React Component and controller? Or the listeners in showTooltip and initSelectionTooltip?

There's likely a gotcha around [useDocumentSelection](https://github.com/pixiebrix/pixiebrix-extension/blob/F%2Fbug%2Fgmail/src/hooks/useDocumentSelection.ts#L39-L39). We should probably be using the selection at the time the popover was shown vs. at the time the button was clicked

> I'm unsure on how to proceed because it's hard to determine whether the `selectionchange` was intentional by the user or if caused by Gmail.

A couple of options are:
- Look at  https://developer.mozilla.org/en-US/docs/Web/API/Event/isTrusted to determine if the user initiated the change
- Keep track of whether there was a `selectionstart` within a certain amount of time before the `selectionchange`

Going to push some potential changes in your PR

**Comment by fregante** [comment]
> > Side note: The logic in these two should be combined.
>
> Which two are you referring to?

I was referring to the two pieces of code I linked before the note, and then also merge the logic into the React component. I think it's easier to reason about it when the logic is in a single place. Also delays might be easier to add in the React component without risking that they get out of sync (e.g. a `hide` command is scheduled via setTimeout, but another `show` event happens before it fires)
