### ISSUE TITLE
Page Editor NPE (destructure property blockId)

### ISSUE THREAD

**Issue by grahamlangford** [pixiebrix/pixiebrix-extension#7735]
## Describe the bug

An NPE was thrown in the Page Editor caused by an attempt to destructure `blockId`. See https://pixiebrix.slack.com/archives/C04373D2R18/p1708967778693429

## Desktop (please complete the following information):

- Extension Version: 1.8.9

**Comment by twschiller** [comment]
Also seeing it here:

<img width="903" alt="image" src="https://github.com/pixiebrix/pixiebrix-extension/assets/1879821/ff34a551-4adb-4a48-8527-a20de22f3aef">

**Comment by grahamlangford** [comment]
Thanks @twschiller. What build was that?

**Comment by twschiller** [comment]
I saw it on alpha 4 with this mod: `@pixies/aa/notifications-demo`. I'll try to reproduce today

**Comment by grahamlangford** [comment]
> I saw it on 1.8.10-alpha.4 with this mod: @pixies/aa/notifications-demo. I'll try to reproduce today

Thanks. Mostly needed the build version so I can check the minified code to confirm whether it's the same error.
