### ISSUE TITLE
Incrementally enable TypeScript strictNullChecks

### ISSUE THREAD

**Issue by twschiller** [pixiebrix/pixiebrix-extension#775]
Long-term code quality initiative, incremental plan to turn on TypeScript's `strictNullChecks` option

Reference on incremental migration:
- Incremental migration: https://kevinwil.de/incremental-migration/
- https://github.com/mjbvz/vscode-strict-null-check-migration-tools

**Comment by fregante** [comment]
New option, currently under development (it fails on our source), is this project:


- https://github.com/airbnb/ts-migrate

It'd enable `strictNullChecks` everywhere and temporarily ignore all existing errors. However this means we'll have 1.9k lines of `// @ts-expect-error` temporarily cluttering our code. We have just about 130k lines now (95k of pure code) so it wouldn't be overwhelming.

Pros:

- new code will hopefully be stricter

Cons:

- `@ts-expect-error` silences _all_ errors on those lines

---

Given the current amount of non-strict code (1900 LoC), enabling `strictNullChecks` feels impossible at this point. My previous attempt is probably still the solution with the best DX to enable it on new files while _not_ completely silencing the existing files:

- https://github.com/pixiebrix/pixiebrix-extension/pull/2791
