### ISSUE TITLE
AA notifications mod crashing browser on activation/after use

### ISSUE THREAD

**Issue by twschiller** [pixiebrix/pixiebrix-extension#7753]
## Describe the bug

- https://pixiebrix.slack.com/archives/C0436P48QHY/p1709071728241349
- Mod: `@pixies/aa/notifications-demo`
- Activating the mod caused the browser to crash
- Our hypothesis was that it was because the user had a lot of tabs open
- The mod had "Run in Background" turned off for the load/interval triggers

**Comment by twschiller** [comment]
I've confirmed that "Run in Background" behavior is working as expected

**Comment by twschiller** [comment]
Will need @johnnymetz and @mthek10 to assist in helping to fix our test environment

**Comment by johnnymetz** [comment]
> Will need @johnnymetz and @mthek10 to assist in helping to fix our test environment

I'll fix it. What test environment are you referring to? And what's broken about it?

**Comment by twschiller** [comment]
> I'll fix it. What test environment are you referring to? And what's broken about it?

The Control Room test environment with AuthConfig App

**Comment by johnnymetz** [comment]
You mean https://pixiebrix-controlroom-dev-3.eastus.cloudapp.azure.com/? I was just able to login and authenticate with the service account. Anything else you want me to check to make it's working for a specific workflow?

**Comment by twschiller** [comment]
> I was just able to login and authenticate with the service account. Anything else you want me to check to make it's working for a specific workflow?

Is the OAuth2 PKCE working?

**Comment by johnnymetz** [comment]
@twschiller Nevermind I was using the wrong user. The `todd+creator@pixiebrix.com` user works.

**Comment by twschiller** [comment]
I haven't been able to reproduce yet - going to try figuring out how to get a lot of notifications into the Control Room to see if data volume is an issue

**Comment by twschiller** [comment]
Note from customer call:
- Only appears to happen when actively switching between tabs
- Appears to be a CPU utilization is (e.g., memory leak)
- Extension storage utilization OK
- General heap utilization OK

**Comment by twschiller** [comment]
I was able to reproduce on 1.8.11-beta.2 without the mod but just having the Co-Pilot open - seems like it might be an issue with the embedded widget

**Comment by twschiller** [comment]
I opened #7983, which I believe the infinite forwarding is the root cause. But will keep this ticket open separately for tracking this specific mod

**Comment by twschiller** [comment]
Tested in 1.8.11-beta.5. Appears to be working
