### ISSUE TITLE
"Copy to mod" didn't copy over mod components

### ISSUE THREAD

**Issue by twschiller** [pixiebrix/pixiebrix-extension#7766]
## Describe the bug

- https://pixiebrix.slack.com/archives/C0436P48QHY/p1709166919833469
- @mthek10 made a copy of a mod and no mod components where included in the saved mod
- When pairing with Mark we noticed the Page Editor slice was out of sync with the extensions slice. Page Editor was showing as having 4 mods that he didn't have active in the Extension Console
- ~Potentially related to: https://github.com/pixiebrix/pixiebrix-extension/issues/6456?~
    - Can't be related, copying is a different save path entirely
- Also potentially related to: https://github.com/pixiebrix/pixiebrix-extension/pull/7299?
- Has happened to Mark 2x in past 2 days

## Screenshots/Loom

- Loom shows the aftermath, but not it happening: https://www.loom.com/share/da68fac9dc1245648545adbdc76cdb56?sid=387b00b1-2f91-462f-80a9-9d99e8b59b79

## Discussion

- From a DevEx perspective, we probably want to rewrite the clone logic using an async thunk. Right now, the clone action just sets the redux state to show a modal

## Acceptance Criteria

- [ ] Fix copy behavior
- [ ] Add relevant jest tests
- [ ] Update Manual Regression checklist (we test the copy mod behavior but didn't catch this)

## Desktop (please complete the following information):

- Extension Version: 1.8.9

## Additional context

- Mod copied: `@pixies/ai/writer-assist`

**Comment by grahamlangford** [comment]
Notes
---

- The mod in the demo does not have extensions (from the copy error) which is why it's not showing up
- Copying clean versions of the mod from the demo seems to work as expected

**Comment by twschiller** [comment]
> The discrepancy between the Page Editor and the Active mods in the Extension Console was likely due to the lack of mod components.

IIRC, from what I saw screensharing, Mark's Page Editor was showing 4 active mods, but the Extension Console was showing no active mods

**Comment by grahamlangford** [comment]
> IIRC, from what I saw screensharing, Mark's Page Editor was showing 4 active mods, but the Extension Console was showing no active mods

My current (untested) hypothesis is the mods he's seeing in the Page Editor don't have mod components and something in the logic in the Extension Console is preventing those from showing up as active. Likely due to the duplicate state between active mods and the editor version. 

It would be a great (eventual) DevEx improvement to remove that duplicate state and have the Page Editor derive that state instead of copying and reshaping it. Probably a very large lift though.

**Comment by twschiller** [comment]
> My current (untested) hypothesis is the mods he's seeing in the Page Editor don't have mod components and something in the logic in the Extension Console is preventing those from showing up as active.

I had paired with Mark using the the Storage Explorer extension. IIRC, they were still showing in the Extension Console even when there was nothing in the storage key for `options` slice. So I suspect the editor slice got out of sync with the options slice at some point

**Comment by grahamlangford** [comment]
> IIRC, they were still showing in the Extension Console even when there was nothing in the storage key for options slice.

Are you saying there was a case where the Extension Console _was_ showing the mods? Or did you mean the Page Editor?

**Comment by twschiller** [comment]
> Are you saying there was a case where the Extension Console _was_ showing the mods? Or did you mean the Page Editor?

Sorry, I mispoke/typed. They were showing in the Page Editor even though there was nothing in the options slice
