### ISSUE TITLE
Add Automation Anywhere API Task JS brick and brick configuration pane

### ISSUE THREAD

**Issue by twschiller** [pixiebrix/pixiebrix-extension#7767]
## User Story

- As an Automation Anywhere mod developer, I want to take advantage of AA's new AA API Task functionality

## Discussion

- @johnnymetz @mthek10 Can get the developer set up on our dev/test control rooms
- It looks like API Tasks use the same `deploy` API endpoint, but a different API version (`v4` vs `v2`). We can potentially re-use some of our code (e.g., for polling results). NOTE: you can't change our existing Bot calls to `v4` because AA on-premise customers might not have updated yet
- @mthek10 do you know if API Tasks are available on AA Community Edition? For V1 I think we can assume we're only dealing with enterprise
- You might want to prototype the requests in Postman before building the brick

## Acceptance Criteria

For the skateboard, let's just expose the basic configuration options:

- Add method for `https://{{ControlRoomURL}}/v4/automations/deploy` in the `aaApi` file 
- Add a "Run Automation Anywhere API Task" `@pixiebrix/automation-anywhere/run-task` brick
  - Inputs: [see API docs for reference](https://docs.automationanywhere.com/bundle/enterprise-v2019/page/api-task-on-demand-endpoint.html#d923050e160)
    - botId (required)
    - automationName (optional)
    - botInput (optional, in Brick Configuration Pane, base on the schema retrieved from the endpoint)
    - awaitResult: see our existing Run Bot brick
    - sharedRunAsUserId: required (will add an affordance to default it in the Page Editor in a follow-up ticket: https://github.com/pixiebrix/pixiebrix-extension/issues/7782
  - Automatically passes:
    - `headlessRequest.numberOfExecutions`: 1
    - `headlessRequest.queueOnSlotsExhaustion`: true
- Add brick tests that mock the response from the AA control room
- Should accept either kind of AA integration:
  - `automation-anywhere/control-room`
  - `automation-anywhere/oauth`
- Add an options pane for the Page Editor that: 
  - Fetches the input schema for the task

## Reference:
- API documentation: https://docs.automationanywhere.com/bundle/enterprise-v2019/page/api-task-on-demand-endpoint.html
- https://docs.automationanywhere.com/bundle/enterprise-v2019/page/enterprise-cloud/topics/control-room/bots/api-task/introduction-api-task.html

**Comment by BLoe** [comment]
BLOCKED: waiting for CR license renewal from Shane

**Comment by BLoe** [comment]
Noting here for reference, the filter value to list the API Tasks is:
```
"filter": {
    "operator": "and",
    "operands": [
      {
            "operator": "eq",
            "field": "type",
            "value": "application/vnd.aa.headlessbot"
      }
    ]
  }
```
