### ISSUE TITLE
Insert at Cursor brick not working from MV2 sidebar on some sites

### ISSUE THREAD

**Issue by twschiller** [pixiebrix/pixiebrix-extension#7774]
## Describe the bug

- https://pixiebrix.slack.com/archives/C0436P48QHY/p1709246784781219
- Insert at Cursor brick not working on:
  - Zendesk (in a ticket) — inserts only the first line. Zendesk uses CKEditor
  - GMail (in a composer) - doesn’t insert
    - It's working for Todd on MV3 using the `@pixies/ai/writer-assist-3` (v1.5.0) mod
- Mod: `@pixies/ai/writer-assist-3` (v1.5.0)
- Might be sidebar related

## Discussion

- See Slack discussion. The issue's @mthek10 is seeing are potentially MV2 sidebar focus related as it's working for Todd in MV3 sidebar and Mark when using trigger

### CKEditor inserting text on single line in MV3

1. Create a Trigger
2. Add the "Insert Text at Cursor" brick
3. Set target to "All Frames" (because CKEditor 6 editor runs in a frame)
4. Set text to be multiline, e.g., 
```
ABC

123
```
5. Click into the field and run the trigger

<img width="781" alt="image" src="https://github.com/pixiebrix/pixiebrix-extension/assets/1879821/d1389b37-158a-4387-8b23-8b7c6b388046">

## Demo Video

- https://www.loom.com/share/c31f266f0e284fbbac4cb634578529df?sid=076f5ecf-a65a-44c7-8a7a-794b75cd21fd

## Desktop (please complete the following information):

- Extension Version: 1.8.10-beta1

**Comment by fregante** [comment]
It looks like it doesn't work in most custom fields:

- ❌  https://draftjs.org/
- ✅  https://www.tiny.cloud/docs/tinymce/6/
- ✅  https://ckeditor.com/ckeditor-4/demo/
- ❌  https://ckeditor.com/ckeditor-5/demo/editor-types/

**Comment by fregante** [comment]
> 3\. because CKEditor 6 editor runs in a frame

I think you're talking about TinyMCE 6 right?

> * Set target to "All Frames" (because CKEditor 6 editor runs in a frame)

We should detect and deal with the field as a _dependent_ of the current page rather than targeting the iframe in the brick runner. This is how the editor itself deals with it.

It looks like `iframe.contentDocument.execCommand('insertText', false, 'hello')` works in TinyMCE 6 for example. For CKE5 it kind of works but it actually it injects it off the document.

**Comment by fregante** [comment]
By the way, in today's version, the brick doesn't work at all in any JS editor. I assume this has to do with focus switching back and forth. We should try to avoid altering focus/selection unless necessary. This means `text-field-edit` might not be beneficial when the user is already interacting with a field.

**Comment by twschiller** [comment]
> By the way, in today's version, the brick doesn't work at all in any JS editor. 

@grahamlangford flagging for awareness on 1.8.10

**Comment by twschiller** [comment]
> I want to specify: it doesn't work from the sidebar due to this focus loss. It does work on contenteditable though

Having to fix for 1.8.10 because it's broken on CKEditor, which is used by Zendesk, etc.

**Comment by fregante** [comment]
Which version do they use?

**Comment by twschiller** [comment]
> Which version do they use?

Will take a look. It was working, but now there's a focus issue with the MV2 sidebar. At this point, the element is our iframe, not the editor: https://github.com/pixiebrix/pixiebrix-extension/blob/dec63ce8f20394d5ec77553b982584cf43b87516/src/contentScript/textEditorDom.ts#L56-L56

**Comment by fregante** [comment]
> Can you elaborate on this note?

Long story, but:

- in the outer frame, the focus is on the `iframe` element
- in the inner frame, the focus is on the right element

the issue is that you can't exactly restore the focus to the right element unless you do both in the right order.
