### ISSUE TITLE
Insert text at cursor injects into the wrong field

### ISSUE THREAD

**Issue by fregante** [pixiebrix/pixiebrix-extension#7779]
## Describe the bug

The content script messages the page script with an action to take _on a selector_. The selector generated is probably wrong and the action ends up selecting the wrong element.

This might be resolved by firing events directly on the affected elements instead of going through "generateSelector" and having to select the element again.

## To Reproduce

1. Go to https://pbx.vercel.app/advanced-fields/
2. Focus the CKEditor 5 or Draft JS field
3. In the sidebar, use the `Insert Text at Cursor` brick

## Actual behavior

The text is injected in the _**CKEditor 4**_ field

## Expected behavior

The text should be injected in the focused field

## Screenshots/Loom

https://github.com/pixiebrix/pixiebrix-extension/assets/1402241/c1b7e0e0-3a15-48c7-926e-fa2a8c30bd16

## Desktop (please complete the following information):

- Extension Version: 1.8.11-alpha.1

## Related

- https://github.com/pixiebrix/pixiebrix-extension/issues/7774#event-11972317454

**Comment by twschiller** [comment]
> This might be resolved by firing events directly on the affected elements instead of going through "generateSelector" and having to select the element again.

Would the idea be to have the pageScript register a capture listener on `document` for a CustomEvent events and look at the target of that event?

The challenge of contentScript + pageScript communication is quickly/reliably communicating elements without JS. I believe what we currently do is traverse up the tree to generate a structural selector. But we also might consider adding a data attribute temporarily to an element to uniquely identify it

**Comment by fregante** [comment]
> look at the target of that event?

Yes. I think the whole communication looks like this:

```js
// content script
elementWeAlreadyHaveAReferenceTo.dispatchEvent(new CustomEvent('pb-input', {
	bubble: true,
	detail: data,
}))
```

```js
// page script
document.body.addEventListener('pb-input', (event) => {
  textFieldEdit.set(event.target, event.detail.text)
});
```

**Comment by twschiller** [comment]
Seeing this on Zendesk even with the change in this PR: https://github.com/pixiebrix/pixiebrix-extension/issues/7779

![image](https://github.com/pixiebrix/pixiebrix-extension/assets/1879821/7767e09f-3a84-4b58-8e5e-4cad98b9e695)

**Comment by fregante** [comment]
I think I figured out why this is happening, and the problem is that they all have different conflicting ways to deal with the insertion.

- `input` must be focused, so we must call `selectionController.restoreWithoutClearing()` before inserting from the sidebar
- `contentEditable` works effortlessly, because the document's selection is preserved even when you click into another frame
- other editors need their own focus/selection logic

In this case specifically, clicking into a CK4 field changes the focused element, but not the selection, so how do we know which one to use? The selection or the focused element?

It's possible that we might need a unified controller that keeps track of the last field touched at all times. This is further complicated by our own `.restore` calls, MV2 sidebar `iframe` and QuickBar `input`

The most recent work is af08449ab, still exploring how each field deals with insertion.

**Comment by fregante** [comment]
Closing as invalid. It's not really a bug, this happened because the suggested way to insert into CK4 was to run "insert text" **into all frames**… so the text was inserted _into all frames_.

I'll open a new issue describing alternative ways to support framed editors.

**Comment by twschiller** [comment]
Calling out that Zendesk is not on CK4, it's on CK5 so we'll still need to keep an eye on: https://github.com/pixiebrix/pixiebrix-extension/issues/7779#issuecomment-1983675198
