### ISSUE TITLE
PLACEHOLDER: can't re-use subscribe methods across useAsyncExternalStore snapshot generators

### ISSUE THREAD

**Issue by twschiller** [pixiebrix/pixiebrix-extension#7789]

**Comment by fregante** [comment]
I'd like to look into this hook this week. Tentatively self-assigning

**Comment by twschiller** [comment]
> I'd like to look into this hook this week. Tentatively self-assigning

Could you please prioritize the text selection and text editor work first? This issue is devex work and is non-blocking. Also, we already have some insights on how to handle from @fungairino's interview project.

**Comment by fregante** [comment]
Yes, I was only assigned that on my Friday and I started working on it. That's why I said "this week" and not already working on it. 

I'm a left some comments on those two issues
