### ISSUE TITLE
MS Edge MV3 crashes when clicking sidebar gear icon

### ISSUE THREAD

**Issue by twschiller** [pixiebrix/pixiebrix-extension#7809]
## Describe the bug

MS Edge MV3 crashes when clicking sidebar gear icon

## To Reproduce

1. Open the sidebar on an unrestricted page
2. Click the gear icon (button of death)

![image](https://github.com/pixiebrix/pixiebrix-extension/assets/1879821/51dc5aa7-fa0d-4a15-8f8b-f6221d43aa1a)

## Discussion

- Might need to use runtime.getURL? Is it the relative URL? https://github.com/pixiebrix/pixiebrix-extension/blob/583c480c6484faa0a4b9c3d5e7b1e25b2ba09f37/src/sidebar/Header.tsx#L101-L101
- The restricted URL content uses `browser.tabs.update`
- Clicking "Open Options" from the MS Edge Extension details page also works
- Other non-extension links work OK from the sidebar

## Actual behavior

Browser crashes/exits

## Expected behavior

Options page options

## Desktop (please complete the following information):

- OS: Mac 14.3.1 (23D60)
- Browser: Version 122.0.2365.63 (Official build) (arm64)
- Extension Version: 1.8.10-beta.2

**Comment by twschiller** [comment]
@fregante clicking the gear icon is still crashing on 1.8.11-alpha.3 (cut from main). Reopening

**Comment by fregante** [comment]
If window.open() still crashes, I can replace it with tabs.create()

**Comment by twschiller** [comment]
> If window.open() still crashes, I can replace it with tabs.create()

I can help test to see if it's just the Extension Console (maybe we need a runtime.openOptionsPage()) vs. other links. It's surprising the link works the first time to open the Extension Console
