### ISSUE TITLE
Insert at Cursor brick losing visible focus after insertion

### ISSUE THREAD

**Issue by fregante** [pixiebrix/pixiebrix-extension#7813]
## To Reproduce

This is immediately visible if you create an interval trigger with the "Insert brick", so you can see that it's not a conflict with other focus/selection changing actions

1. Go to https://pbx.vercel.app/advanced-fields/
2. Create Interval trigger
3. Add "insert text" brick
4. Save
5. close the editor
	- Due to #7812
6. Click on a textarea to focus it

## Actual behavior

The field loses visual focus. This might be because of the `window.focus()` call.

This affects _**all**_ fields on the page, except

- TinyMCE because it's untargetable due to #7779 
- Draft JS which disappears on insertion, much like #7630

## Expected behavior

No changes in focus

## Screenshots/Loom

![2](https://github.com/pixiebrix/pixiebrix-extension/assets/1402241/fba3ea30-e95e-4b28-9211-e6b2dc8b081b)

## Desktop (please complete the following information):

- Extension Version: 1.8.11-alpha.1

## Related

Found while debugging:

- https://github.com/pixiebrix/pixiebrix-extension/issues/7774

**Comment by fregante** [comment]
https://github.com/pixiebrix/pixiebrix-extension/blob/e9a0bfcb065c33511cdf1409323f3aeb2edf5bee/src/bricks/effects/InsertAtCursorEffect.ts#L60-L61

@twschiller what does this mean? Can the brick receive an element reference and insert into it? When do you expect this to happen in practice?

The brick name seems to imply that it will use the existing cursor/selection and _insert_ there, it seems strange to pass a random element and _append/prepend_ there without knowing where the cursor/selection is.

I ask here because if we drop it we can stop using the focus for **most fields**, just call `insertText` and let the browser deal with it.

**Comment by twschiller** [comment]
> @twschiller what does this mean? Can the brick receive an element reference and insert into it? When do you expect this to happen in practice?

Good point, `isRootAware` does mean that a target element can be passed in

![image](https://github.com/pixiebrix/pixiebrix-extension/assets/1879821/9ea0f0ec-2a8a-4002-a245-bd1d8e4d499f)

I agree it doesn't make sense to support it for this brick is that individual editors don't preserve their cursor position. If that's the case, you can set that to `false` with an explanation

>  just call insertText and let the browser deal with it.

I believe we'd still need to detect the element to handle CKEditor and other editors that don't seem to play nicely with insertText?

**Comment by fregante** [comment]
Correct. That's what I meant by only running code for the fields that need it. So we'd still want to check the selection/focus, but if it doesn't lead to any "special case", just continue with the regular insertText. 

I noticed that the API does return `false` in many cases, for example if the selection/focus is on the iframe, so we can still throw an error in that case and detect future issues.
