### ISSUE TITLE
Refactor fetch deployment mod definitions axios call to use RTK Query

### ISSUE THREAD

**Issue by johnnymetz** [pixiebrix/pixiebrix-extension#7841]
## User Story

As a frontend developer, I an API call to fetch deployment mod definitions to use RTK, so we get the RTK query benefits (caching) and consistency with the rest of the codebase

## Motivation

RTK query is better than using axios directly

## Acceptance Criteria

- Update this axios call to use RTK query: 
- Note, we need to keep the `fetchDeploymentModDefinitions` function because it's used in the background script, see `deploymentUpdater.ts` (unless we somehow figure out how to use RTK query in the bg script)

**Comment by twschiller** [comment]
> , so we get the RTK query benefits (caching

As a reminder, we still get browser-level caching in the current world
