### ISSUE TITLE
Text Selection Popover UI Polish

### ISSUE THREAD

**Issue by twschiller** [pixiebrix/pixiebrix-extension#7853]
Context
---
- Figma: https://www.figma.com/file/BHZrQVl4Xm43VCuGBdIyjY/Text-Popover-Analysis?type=whiteboard&node-id=0-1&t=IgpCtKdAm8FnZHcw-0

Definition of Done
---
- [ ] 32x32 pixel containers for centered icons
- [x] Icons size is 16px (corresponds with 1rem), vertical positioning consistent between emoji and icon
- [ ] Use greys vs. purples for hover state: @BrandonPxBx what reference colors are these?
- [ ] Remove spacing between containers: @BrandonPxBx which spacing is this referring to? Is this referring to the extra padding on the left/right items?

Discussion
---
- @BrandonPxBx I left off the drop shadow comments because the Figma seems to be referencing the border/drop shadow prior to a drop shadow already being implemented for the popover

**Comment by BrandonPxBx** [comment]
All of the greys should be referenced here: https://github.com/pixiebrix/pixiebrix-extension/blob/f6c7465da311562278e85251f9e862bc426739ce/src/themes/colors.scss#L1-L1

For the hover state, the design token is
`$S2: #efeef1;`

Border color is:
`$S3: #dedbe3;`

For spacing: I'm saying that each 32x32 container should have margin between it and the other containers. That includes the edges of the parent container (the gap Mike was referencing in the first version UI
