### ISSUE TITLE
Text Command Popover: add empty/no result states to command popover

### ISSUE THREAD

**Issue by twschiller** [pixiebrix/pixiebrix-extension#7855]
Design Reference
---
- https://www.figma.com/file/BHZrQVl4Xm43VCuGBdIyjY/Text-Popover-Analysis?type=whiteboard&node-id=9-986&t=i1ok1h6GbWx4kdFr-0

Discussion
---
- @BrandonPxBx can you add the designs for the error states? By error states, are you just referring to no matching snippets for your search?

Definition of Done
---
- [ ] Add true error states
- [ ] Error state design v1 - just describe the error I.E.: we can’t find any matching snippets

**Comment by BrandonPxBx** [comment]
V1: https://www.figma.com/file/0FSyxGoz2Pk1gtvrzWNe7G/Business-User-Onboarding-Mods?type=design&node-id=241-2275&mode=design&t=qvQc9OYM6QWuD6hD-4

Yes, for v1, the suggestion is to just say "We can’t find any matching snippets." so the user knows what's wrong.

**Comment by twschiller** [comment]
@BrandonPxBx the danger text seems a bit harsh for no matching snippets. Should we use a grey instead?
