### ISSUE TITLE
Fix e2e-tests CI job for dependabot

### ISSUE THREAD

**Issue by twschiller** [pixiebrix/pixiebrix-extension#7880]
Context
---
- e2e-test jobs failing, likely due to the `E2E_TEST_` settings not being available to dependabot runs
- The e2e-tests job isn't a requirement for merging, so the patch dependabot PRs got auto-merged even though the job failed

Examples
---
https://github.com/pixiebrix/pixiebrix-extension/pull/7876

```
    Call log:
      -   checking visibility of getByText('')


      42 |   await waitForAdminConsoleToLoad(page);
      43 |
    > 44 |   if (await page.getByText(E2E_TEST_USER_EMAIL_UNAFFILIATED).isVisible()) {
         |                                                              ^
      45 |     // If the user is already authenticated, reuse the existing session
      46 |     await page.context().storageState({ path: authFile });
      47 |     return;
```

**Comment by grahamlangford** [comment]
Fixed the missing env variables. 

Will make a requirement once @fungairino and @mnholtz are confident the tests are in a good state.

**Comment by twschiller** [comment]
@grahamlangford @fungairino I think this is good now? We can re-open if dependabot fails Monday?

**Comment by twschiller** [comment]
@grahamlangford closed because this week's dependabot runs ran successfully

**Comment by grahamlangford** [comment]
I was keeping it open as a reminder to make the e2e tests required in the branch protection rules. But I can create a separate ticket. Need to confirm with @fungairino and @mnholtz that everything is ready and stable before we enforce the tests.
