### ISSUE TITLE
Integration banner is hidden on sites with sticky nav

### ISSUE THREAD

**Issue by twschiller** [pixiebrix/pixiebrix-extension#7979]
## Describe the bug

Integration banner is hidden on sites with sticky nav

## To Reproduce

0. Ensure the integration-login-banner feature flag is turned on
1. Use Storage Area Explorer to clear the extensions OAuth2 Cache
2. Run a mod that uses Google Drive or another PKCE integration
3. Visit reddit.com or Google Drive

## Actual behavior

The integration banner is hidden

## Expected behavior

The integration banner is visible

## Discussion

- ~Need to decide behavior, so as to not obstruct the nav. Or make the banner dismissable~
- Decision made here: https://www.notion.so/pixiebrix/Integration-Banner-Design-Sync-0250dc75a400400d88ca5f9161630e57
- @BrandonPxBx will add mockups for the dismiss button

## Additional context

Version: main

**Comment by BrandonPxBx** [comment]
I added the bootstrap dismissable close to the mock-up [here](https://www.figma.com/file/RGcBtgkFHIBczxhKPKtaE5/Page-Editor?type=design&node-id=3628-37287&mode=design&t=NU8XKZvsK0F0eU2x-4). 

Here's the bootstrap doc on it: https://react-bootstrap-v4.netlify.app/components/alerts/#dismissing
