### ISSUE TITLE
Move Text Selection Popover and Command Popover from Skunkworks to General Settings

### ISSUE THREAD

**Issue by twschiller** [pixiebrix/pixiebrix-extension#7980]
Definition of Done
---
- Text Selection Popover and Command Popover configuration is included in Extension Console > Settings > General Settings
- They default to toggled on "ON" (write a settings migration)
- They are removed from the Skunkworks settings

Discussion
---
- Need to finalize feature naming
  - Snippet Shortcut Menu
  - Text Selection Menu 
- OK to show the settings to all users

**Comment by grahamlangford** [comment]
@twschiller I'm assuming it's safe to remove the `text-selection-popover-force` flag since we're enabling by default.
