### ISSUE TITLE
Setup proxy to convert SVG to PNG

### ISSUE THREAD

**Issue by johnnymetz** [pixiebrix/pixiebrix-extension#7982]
## User Story

As an end user, I want to convert an SVG to a PNG, so that it can be used as a theme icon.

## Motivation

In https://github.com/pixiebrix/pixiebrix-extension/pull/7925, we need to convert an SVG to a PNG (see [here](https://github.com/pixiebrix/pixiebrix-extension/pull/7925#issuecomment-1999006721)).

Note this is a temporary workaround until browsers support dynamic SVG icons: https://github.com/w3c/webextensions/issues/462

## Acceptance Criteria

- A user can convert an SVG to a PNG in the Extension

## Implementation Notes

- Potential Solutions
  - https://github.com/GewoonJaap/svg-to-png-cf-worker: Let's look into this first
  - Setup an App endpoint to do this
- This endpoint will be called a lot so need to ensure the solution isn't expensive. If it is, we probably want to enable caching.

**Comment by twschiller** [comment]
Can we just have the user upload in the Admin Console, convert it, and then store the PNG on S3?

**Comment by johnnymetz** [comment]
> Can we just have the user upload in the Admin Console, convert it, and then store the PNG on S3?

That should work. @grahamlangford mentioned we need the icon to load for unauthenticated users but we can design the backend so that works (e.g. construct the icon URL in Chrome instead of returning the icon from an authenticated PixieBrix endpoint).

How often will this feature be used? I'm wondering if it's better to just require teams to contact PixieBrix support to do this (convert to PNG + upload to S3) manually? Considering we don't need this feature once https://github.com/w3c/webextensions/issues/462 is done.

**Comment by fregante** [comment]
Considering that https://github.com/GewoonJaap/svg-to-png-cf-worker is already tested and it works, I'd probably say it's the quickest solution, at least until someone finds it and starts spamming it. A rate limiter (via CF page rules) can certainly help.

**Comment by twschiller** [comment]
>  @grahamlangford mentioned we need the icon to load for unauthenticated users but we can design the backend so that works (e.g. construct the icon URL in Chrome instead of returning the icon from an authenticated PixieBrix endpoint).

Don't we return the icon URL via the theme currently?

> How often will this feature be used? I'm wondering if it's better to just require teams to contact PixieBrix support to do this (convert to PNG + upload to S3) manually?

It would be whenever we onboard an enterprise customer, or want to demo custom branding to an enterprise customer. @BrandonPxBx this would be good to triage vs. the other self-serve administration efforts

**Comment by grahamlangford** [comment]
> Don't we return the icon URL via the theme currently?

This is correct, when I was speaking with Johnny earlier, I mistakenly thought we were managing the theme with managedStorage, but we're just checking for a partnerId and organizationId:

https://github.com/pixiebrix/pixiebrix-extension/blob/6ca9daa7f57f2f525eb2fd25f8a27662b5911ef1/src/themes/themeStore.ts#L55-L68

**Comment by twschiller** [comment]
Closing - we'll instead do icon upload/hosting
