### ISSUE TITLE
Infinite messenger forwarding loop when working with iframe in the Page Editor

### ISSUE THREAD

**Issue by twschiller** [pixiebrix/pixiebrix-extension#7983]
## Describe the bug

- Potentially the cause of: https://github.com/pixiebrix/pixiebrix-extension/issues/7753. I discovered this issue while trying to diagnose that issue

## To Reproduce

1. Activate `@pixies/aa/notifications-demo`
2. Go to https://news.ycombinator.com/
3. Open the Page Editor and click around

TODO: try to create a simpler reproduction

## Actual behavior

- CPU utilization increases until the browser tab or browser crashes
- If you pause the debugger, you'll it's constantly in `removePersistedExtension` which is the handler for https://github.com/pixiebrix/pixiebrix-extension/blob/0c94f1d994c81bc75bd5a31e6267c550d1a8fad7/src/contentScript/messenger/api.ts#L26-L26
- The likely initiating call is here: https://github.com/pixiebrix/pixiebrix-extension/blob/0c94f1d994c81bc75bd5a31e6267c550d1a8fad7/src/pageEditor/PanelContent.tsx#L64-L64
- Notice the message to allFramesInInspectedTab, which would include our iframe tiny page: https://github.com/pixiebrix/pixiebrix-extension/blob/0c94f1d994c81bc75bd5a31e6267c550d1a8fad7/src/tinyPages/frame.ts#L26-L26

## Expected Behavior

- No crash
- @fregante if the messenger sees a trace that hasn't made progress, we should likely have it throw instead of infinitely forwarding? We could look at the last 2 trace frames and see if they're the same?

## Screenshots/Loom

<img width="248" alt="image" src="https://github.com/pixiebrix/pixiebrix-extension/assets/1879821/992be634-acb1-4143-9ded-519b81c14f61">

<img width="837" alt="image" src="https://github.com/pixiebrix/pixiebrix-extension/assets/1879821/eda313e5-22b1-404d-994f-ec033c0a9b3a">

## Desktop (please complete the following information):

- OS: Mac
- Browser: Chrome
- Extension Version: `main`

## Additional context

- What mod(s) were you running?: @pixies/aa/notifications-demo
- https://news.ycombinator.com/
- Do you need any special permissions to reproduce?
  - Access to a Control Room? I will try to reproduce

## Related Issues

- https://github.com/pixiebrix/pixiebrix-extension/issues/7753
- https://github.com/pixiebrix/pixiebrix-extension/issues/7847

## Discussion

- Could a infinite messenger loop also happen on mod activation if there are any sidebars with iframes? That might explain a crash for https://github.com/pixiebrix/pixiebrix-extension/issues/7753 I saw a customer have on mod activation in the extension console when I don't think the Page Extension was involved

**Comment by fregante** [comment]
Tracked in:

- https://github.com/pixiebrix/webext-messenger/issues/219

**Comment by fregante** [comment]
As an immediate fix I think you can just temporarily set `allFramesInInspectedTab = inspectedTab` and drop "all frames" support. I can then implement one of the two solutions mentioned in the issue above

**Comment by twschiller** [comment]
> As an immediate fix I think you can just temporarily set allFramesInInspectedTab = inspectedTab and drop "all frames" support.

Let's add the check to prevent infinite forwarding. In addition to the fail-safe, we should also try to understand why it was getting forward in the first place?

**Comment by twschiller** [comment]
Related webext-messenger project issue: https://github.com/pixiebrix/webext-messenger/issues/219

**Comment by fregante** [comment]
> let's also try to understand why it was getting forward in the first place?

The reason is that extension pages (i.e. "not content script") don't expect to receive messages that don't have the `page` in the target, so they forward it to "all frames" on the specified tab, which includes themselves. 

The solution is likely to `ignore` any messages received in framed extension pages. Actually only the background page should do the forwarding I think
