### ISSUE TITLE
Use EM sizing for Snippet Shortcut Menu to isolate size from host page

### ISSUE THREAD

**Issue by twschiller** [pixiebrix/pixiebrix-extension#7990]
## Describe the bug

- Use EM sizing for Snippet Shortcut Menu to ensure the documents root font size doesn't impact

## To Reproduce

1. Go to linkedin.com
2. Toggle the menu

## Screenshots/Loom

What is this, a footer for ants? 🐜 

![image](https://github.com/pixiebrix/pixiebrix-extension/assets/1879821/2f72fcf9-35d8-42c6-ab87-6102c9951ef5)

## Desktop (please complete the following information):

- Extension Version: 1.8.11-beta.2

**Comment by fregante** [comment]
Related, part of its “future work”: 

- https://github.com/pixiebrix/pixiebrix-extension/pull/7940
