### ISSUE TITLE
Text Selection Menu obscuring input in Google Sheets sharing modal

### ISSUE THREAD

**Issue by grahamlangford** [pixiebrix/pixiebrix-extension#7993]
## Describe the bug

See https://pixiebrix.slack.com/archives/C0436P48QHY/p1710880142825579

## Actual behavior

Menu covers part of the input

## Expected behavior

Menu appears below the input

## Notes
- Verify also works correctly with the Snippet Shortcut Menu

**Comment by grahamlangford** [comment]
Potentially fixed by https://github.com/pixiebrix/pixiebrix-extension/pull/7998

@fungairino can you replicate? This is what I'm seeing now:

<img width="114" alt="image" src="https://github.com/pixiebrix/pixiebrix-extension/assets/30706330/30ae897f-6131-43bf-b3de-90f66b0b225c">

**Comment by fungairino** [comment]
Yea, I can still repro
![Screenshot 2024-03-21 at 12 01 46 PM](https://github.com/pixiebrix/pixiebrix-extension/assets/3498063/673e7601-1164-4b8a-aa9c-53e8c5a00b5b)

On a related note, the selection menu in the linkedin sign in input also looks a little too close.
![Screenshot 2024-03-21 at 12 02 49 PM](https://github.com/pixiebrix/pixiebrix-extension/assets/3498063/6deba1ef-73a0-4430-aa97-a19665b70def)
