### ISSUE TITLE
OAuth Grant Flow displays login banner

### ISSUE THREAD

**Issue by grahamlangford** [pixiebrix/pixiebrix-extension#8004]
## Describe the bug

When the Login Banner is enabled and has been displayed requesting OAuth permissions, the Login Banner also displays on the sign in window.

## To Reproduce

1. Install a mod that requires Google Drive access
2. Using Storage Explorer, delete the oauth key
3. On any page, wait for the Login Banner to appear
4. Click login
5. Choose an account (banner doesn't display here)
6. User is automatically redirected to the sign in page

## Actual behavior

The Login banner shows on the sign in page (see the screenshot)

## Expected behavior

Login banner should not be displayed at any point in the oauth flow

## Screenshots/Loom

<img width="1441" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMno4QXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--80a3a9e19272056a242ddf108c2b16f3c7084576/image.png" alt="image.png" />

**Comment by twschiller** [comment]
- This is happening for our notifications mod which runs on all pages
- Could be potentially solved by memoizingUntilSettled launchOAuth2Flow: https://github.com/pixiebrix/pixiebrix-extension/blob/3d4d03b365327be5f47a962b23c4b2153301021e/src/background/auth/launchOAuth2Flow.ts#L36-L36 based on the configuration id passed in

**Comment by grahamlangford** [comment]
> Could be potentially solved by memoizingUntilSettled launchOAuth2Flow:

Easy to test. I'll try that real quick.

**Comment by grahamlangford** [comment]
That appears to have worked. Great call!
