### ISSUE TITLE
Login banner not visible on some pages

### ISSUE THREAD

**Issue by twschiller** [pixiebrix/pixiebrix-extension#8009]
## Describe the bug

Login banner not visible on https://www.nespresso.com/us/en/

## To Reproduce

1. Clear your integration storage
1. Visit https://www.nespresso.com/us/en/ (notice they have a nav + a sale banner)

## Actual behavior

See screenshot. Screen is shifted but banner is not visible

## Screenshots/Loom

![image](https://github.com/pixiebrix/pixiebrix-extension/assets/1879821/51284e95-714c-45d9-9beb-d218f082fce6)

If I adjust the z-index to 9999 it shows, but nespresso's CSS is also leaking:
![image](https://github.com/pixiebrix/pixiebrix-extension/assets/1879821/0d280622-b26f-446c-ac63-60f6bee206b4)

## Desktop (please complete the following information):

- Browser: Chrome
- Extension Version: 1.8.11-beta.5

**Comment by grahamlangford** [comment]
@twschiller I set the z-index to 1030 in the previous PR to prevent the banner from being higher than our modals (one of the goals we discussed). 

Looks like their header is z-index 2002. I can raise the z-index considerably higher, but then we run into it being above the modal overlay. I can update that as well, just need to confirm whether that's something we want to do. 

We vendor the bootstrap css now, so I should be able to find all z-indexes and raise them from ~1000 to ~10000. That should handle nearly any site.

**Comment by grahamlangford** [comment]
> If I adjust the z-index to 9999 it shows, but nespresso's CSS is also leaking:

What host styling are you seeing?

**Comment by twschiller** [comment]
> What host styling are you seeing?

Isn't the font and the padding off?

**Comment by grahamlangford** [comment]
> Isn't the font family and the padding off? (Or it seems off compared to what I'm used to)

Possibly the font-face. Not sure on the padding. Hard to tell from a screenshot.

**Comment by fregante** [comment]
> will still have the correct overlay

That's correct. It's a great new concept: the latest call gets the top-most layer. We'll want to eventually use it for our notifications and other overlays.
