### ISSUE TITLE
Login Banner button is occluded by sidebar or is under overlay preventing interaction

### ISSUE THREAD

**Issue by twschiller** [pixiebrix/pixiebrix-extension#8010]
## Describe the bug

https://pixiebrix.slack.com/archives/C0436P48QHY/p1711043410190069

## Related Issues

- https://github.com/pixiebrix/pixiebrix-extension/issues/8009

**Comment by fregante** [comment]
We have some dynamic CSS variables that include the sidebar width if open, we use it to add margin to the body, so it should easily be reusable to add a margin to the banner
