### ISSUE TITLE
Strict null checks migration

### ISSUE THREAD

**Issue by fregante** [pixiebrix/pixiebrix-extension#8018]
I think there should be a main tracking issue for ease of reference. I'll be using this.

**Comment by twschiller** [comment]
We have an Epic in Zenhub we're using to track. @grahamlangford can set you up with an invite
<img width="664" alt="image" src="https://github.com/pixiebrix/pixiebrix-extension/assets/1879821/276c1603-3e8f-4bcc-9c9d-ace95559f7ed">

**Comment by fregante** [comment]
Not to track the existing issues, but to place all the context in one issue and link it specifically on GitHub. To identify issues and PRs as a group I had also added a label yesterday. 🙌

**Comment by grahamlangford** [comment]
Zenhub is an additional layer over GitHub that makes it easier to track projects/epics/etc. I'll send an invite. Having access to the epics alone will probably be useful to you.

**Comment by grahamlangford** [comment]
> Not to track the existing issues, but to place all the context in one issue and link it specifically on GitHub. Also to remind myself of this assignment when I look at my issues.

The epics support that as well. And if you have the zenhub chrome extension, all of that is accessible without leaving github.
