### ISSUE TITLE
Replace axios-mock-adapter with Nock

### ISSUE THREAD

**Issue by mnholtz** [pixiebrix/pixiebrix-extension#8024]
Part of @fregante's implementation sketch here: https://github.com/pixiebrix/pixiebrix-extension/issues/4810#issuecomment-1999009685

**Comment by fregante** [comment]
We might use `msw` instead of `nock` when mocking our own API, we already use it in Storybook I think

- https://kentcdodds.com/blog/stop-mocking-fetch
- https://nate-d-gage.medium.com/mocking-axios-with-mock-service-worker-427b0f87aa08
