### ISSUE TITLE
Replace direct axios usage with ky

### ISSUE THREAD

**Issue by mnholtz** [pixiebrix/pixiebrix-extension#8025]
Part of @fregante's implementation sketch here: https://github.com/pixiebrix/pixiebrix-extension/issues/4810#issuecomment-1999009685

**Context**
- See [F/deps/axios-partial](https://github.com/pixiebrix/pixiebrix-extension/tree/F/deps/axios-partial?rgh-link-date=2024-03-13T14%3A06%3A09Z)

**Comment by fregante** [comment]
Extracting some sub-tasks:

- [ ] Revert 1383ce021 and continue working on Google API support
