### ISSUE TITLE
Playwright Test mod that uses Google Sheets

### ISSUE THREAD

**Issue by grahamlangford** [pixiebrix/pixiebrix-extension#8058]
Acceptance Criteria
---

- [ ] Test that leverages the Google Sheets APIs
    - [ ] Can be Page Editor, Sidebar mod, or Extension Console, whatever is easiest
    - [ ] Mock the response from the API (https://playwright.dev/docs/mock)
    - [ ] Should successfully call the API and test that the UI is correctly updated with the response
   
Notes
---
* Let's timebox initially to 1 day, then revisit. Depending on LoE, we may want to prioritize other Playwright issues first.
* @BLoe has context on the GSheets APIs

**Comment by BLoe** [comment]
> @BLoe is there a Postman collection with the relevant APIs?

It's in the "Brick Prototyping" workspace, in the `Google Drive` and `Google Sheets` collections. YMMW on cleanliness/completeness of the collections there, but I think most of it is in place. For authentication, the `CLIENT_ID`, and `CLIENT_SECRET` should be configured as collection variables, but let me know if there are any issues with that and I can share those values directly.

**Comment by fungairino** [comment]
Reopening due to flakiness in CI due to Captcha checking.

We should look into seeing if we can make something like https://www.npmjs.com/package/puppeteer-extra-plugin-stealth work for us.

In the meantime I am marking the existing test as local only, and skip in CI.

**Comment by twschiller** [comment]
Closing, will re-open new issue for getting the test to run on CI
