### ISSUE TITLE
Playwright test for the Snippet Shortcut Menu

### ISSUE THREAD

**Issue by grahamlangford** [pixiebrix/pixiebrix-extension#8059]
Acceptance Criteria
---
- [ ] Simple test leveraging the Snippet Shortcut Menu

Notes
---
- Let's timebox initially to 1 day, then revisit
  - depending on LoE, we may want to prioritize other Playwright issues first.

**Comment by twschiller** [comment]
@grahamlangford @fungairino I think it would make sense to split this into 2 separate issues. I created `@pixies/test/text-snippets` and spent a little time trying to get keyboard controls to work on https://pbx.vercel.app/advanced-fields/. Even for the basic input, it's non-trivial. E.g., know which delays, etc. are require to toggle the menu. And using `.press("Tab")` to complete, it was having issues where the `\s` snippet query wouldn't be cleard

**Comment by fungairino** [comment]
I ran into some of the issues Todd described here, but I was able to write a very simple test without the keyboard controls (using just clicks to select the snippet).

I'd say we create a follow-up for further e2e testing using arrow controls and searching if needed after this PR closes out the issue.

**Comment by fungairino** [comment]
I also suspect the difficulty in using the keyboard controls in e2e tests might be indicative of some buggy behavior that we might need to dig deeper into.
