### ISSUE TITLE
Blank numeric text integration configuration field not validated on save

### ISSUE THREAD

**Issue by twschiller** [pixiebrix/pixiebrix-extension#8067]
## Describe the bug

- Integration configuration text field with numeric string format not validated on save
- This has come up multiple times where users have left the field blank and then it errors at runtime

## To Reproduce

1. Add the `automation-anywhere/control-room` integration
2. Provide an invalid configuration (invalid because Folder ID regex is `\d+`)

<img width="712" alt="image" src="https://github.com/pixiebrix/pixiebrix-extension/assets/1879821/e903f182-57fd-4ea0-b102-8bb882cf49dd">

## Expected behavior

<img width="691" alt="image" src="https://github.com/pixiebrix/pixiebrix-extension/assets/1879821/d40a967e-f174-4350-8487-1f6cfff83172">

## Discussion

- Is Formik not validating the field? Or does the schema-to-yup field consider it as being valid because it's an optional field? The documentation for Yup required seems to indicate required corresponds with null/undefined: https://github.com/jquense/yup?tab=readme-ov-file#schemarequiredmessage-string--function-schema
- Best fix might be to run the JSON Schema validator check on save as a backstop for inconsistency between Yup Schema generation and JSON Schema?

## Related Code

- https://github.com/pixiebrix/pixiebrix-extension/blob/837ea111eead6afd0adec5c76cf8b628e220a5fb/contrib/integrations/automation-anywhere.yaml#L31-L31

**Comment by twschiller** [comment]
> https://github.com/cf-worker's validator also seems to deliver the same result.

Noting from our call that it seems like a code reload issue, and that cf-worker was catching it

**Comment by grahamlangford** [comment]
> Noting from our call that it seems like a code reload issue, and that cf-worker was catching it

Yes, looks like I had an issue with hot reloading not triggering for some reason. I'll look into converting the validation result so that the appropriate error is displayed.

**Comment by grahamlangford** [comment]
Reopened due to bug when saving some configurations:
![image](https://github.com/pixiebrix/pixiebrix-extension/assets/30706330/2561484c-7583-40d4-8b55-165bb4818c8f)

**Comment by twschiller** [comment]
@grahamlangford see this file for examples of validating JSON Schemas: https://github.com/pixiebrix/pixiebrix-extension/blob/4668ee9455d97634a9512663bf0c80c04c7a91ef/src/validators/schemaValidator.ts#L244-L244
