### ISSUE TITLE
Text Selection Menu never closes on Notion modals

### ISSUE THREAD

**Issue by grahamlangford** [pixiebrix/pixiebrix-extension#8075]
## Describe the bug

In Notion, when a page modal is open and text is selected, clicking away does not close the menu. The same behavior does not happen when the page is opened as a full page.

## To Reproduce

1. Go to Notion
2. Open the preview of a page (in a modal)
3. Select text
4. the Text Selection Menu is shown
5. Click elsewhere in the modal

## Actual behavior

The menu remains open in the same location. Highlighting other text moves the menu, but it does not appear possible to close it

## Expected behavior

The menu should be dismissed

## Screenshots/Loom

https://www.loom.com/share/47ae5403286e4d0fb793e8e5b6e83ad2

## Desktop (please complete the following information):

- Extension Version: 1.8.11

**Comment by fregante** [comment]
I'm gonna guess that they use stopPropagation so it never reaches our listener. Is our event already `capture: true`?
