### ISSUE TITLE
Enforce `@/` usage or drop it

### ISSUE THREAD

**Issue by fregante** [pixiebrix/pixiebrix-extension#808]
Root-based imports are nice but in reality they're often just handled by the editor, when adding, moving or just looking for usage.

My editor sometimes uses `@/` sometimes it doesn't. The codebase has many `./` imports as well. I think one or the other should be enforced via ESLint, if a rule exists.

**Comment by twschiller** [comment]
> I think one or the other should be enforced via ESLint, if a rule exists.

Agree whatever we choose should be enforced. When importing, I think IntelliJ's heuristic is to choose the alias that produces the shortest import name. IIRC, there's some code in the codebase from before I added aliases
