### ISSUE TITLE
Widgets are inserted into the user's content when `body.isContentEditable`

### ISSUE THREAD

**Issue by fregante** [pixiebrix/pixiebrix-extension#8094]
## Describe the bug

Our widgets will be injected into this page and, if the content editable field/frame is read by a controller (as one would expect), it will include our widgets

```html
<!doctype html>
<body contenteditable>
   Hello user, type something here
</body>
```

## To Reproduce

1. Visit https://contenteditable-body.tiiny.site

## Actual behavior

- See our widgets end up inside the `contenteditable` field, in the DOM, and are potentially **saved as part of the user input**
- Our widgets (including the notifications) are selectable/editable

## Expected behavior

I'm not sure of how to deal with this. At at very least we can add a `contenteditable=false` attribute to all of our widgets (part of #7670)

## Demo

<img width="661" alt="Screenshot 23" src="https://github.com/pixiebrix/pixiebrix-extension/assets/1402241/45405ae9-bfeb-46a1-93e5-d515c7c3386b">

https://github.com/pixiebrix/pixiebrix-extension/assets/1402241/3311dcf2-eb18-497c-bde6-ea7e937ab2ff

## Context

Seen in https://github.com/pixiebrix/pixiebrix-extension/issues/8071

**Comment by fregante** [comment]
### Thoughts

- We cannot hide the elements from the reader, they can use `.innerHTML` at any time to "save" all of the elements
- Our shadow DOM already prevents the actual content, providing that we **stop using `mode=open`** on the shadow DOM


### Provisional resolutions

- [ ] Use `contenteditable=false` on every shadow root
- [ ] Use `mode=closed` on every shadow root
- [ ] Introduce lint rule to avoid `mode=open
- [ ] Proactively remove elements from the DOM when not in use, rather than leaving them behind
- [ ] Keep in mind that some of our elements may already exist on the page, and our code will reuse them: https://github.com/pixiebrix/pixiebrix-extension/blob/58ae23e997d43011220c74f23792b1b129e7f22b/src/contentScript/tooltipDom.ts#L31-L33

Also

- [ ] Add these to the list of things to include in https://github.com/pixiebrix/pixiebrix-extension/issues/7670

**Comment by grahamlangford** [comment]
I toast is not in a shadow dom. I also don't. We don't have this problem with the Snippet Shortcut Menu, and it's in a `mode=open` shadow dom. I would be against requiring `mode=closed`. I'm not convinced it does anything for us, and closed shadow doms are harder to write tests for.

**Comment by twschiller** [comment]
> I'm not sure of how to deal with this. At at very least we can add a contenteditable=false attribute to all of our widgets

Given that this case arises with certain editors, I think the correct long-term fix is to render the elements on the on the parent frame (which is what I believe what Grammarly does)

To prevent data corruption in editors, my vote for immediate approach would be to have our UI affordances error instead of show if the body is `contenteditable`

- Toast
- Snippet shortcut menu
- Text selection menu
- Modal/popover
- Quickbar/Sidebar (only show on top-level frame, it's generally unlikely that top-level body is contenteditable, but would be safer to assert its not)

**Comment by BLoe** [comment]
The alert popups are no longer rendered inside the `<body/>` element in the page, so they seem to no longer suffer from this issue? I can't produce the behavior from the initial video anymore. Is this issue still a real problem that user's suffer from?

<img width="505" alt="image" src="https://github.com/pixiebrix/pixiebrix-extension/assets/2801308/f5e0a709-3258-44fe-a4b1-d7d17669574b">

**Comment by twschiller** [comment]
Moving to "Next" - I'm also having trouble reproducing on the Salesforce edit field right now: https://pixiebrix3-dev-ed.lightning.force.com/lightning/r/Case/5008X00002YDcUtQAL/view. But I'm not aware of what would have changed

**Comment by BLoe** [comment]
The "widget" used to be appended to `body` here: https://github.com/pixiebrix/pixiebrix-extension/blob/abfecafc36b7ea914e3f91a0305bb5a47bf38a1f/src/contentScript/modalDom.tsx#L64

Federico fixed the issue in [this PR](https://github.com/pixiebrix/pixiebrix-extension/pull/8150)

Now, the widget is added directly to `document` instead, [see here](https://github.com/pixiebrix/pixiebrix-extension/blob/4e94c28483307ca7381b83e54efacdf37efad888/src/utils/reactUtils.tsx#L73)

**Comment by BLoe** [comment]
@twschiller I think we should close this issue unless you see a reason otherwise, given the above change

**Comment by twschiller** [comment]
Thanks for clarifying - will close for now
