### ISSUE TITLE
Add Playwright to Codecov

### ISSUE THREAD

**Issue by mnholtz** [pixiebrix/pixiebrix-extension#8099]
We'd like a way to systematically calculate code coverage from e2e tests to facilitate discussion around minimum test expectations.

Playwright doesn't seem to provide code coverage support out of the box: https://github.com/microsoft/playwright/issues/9208

Potentially useful resources: 
- https://github.com/microsoft/playwright/issues/13452
- https://playwright.dev/docs/api/class-coverage
- https://github.com/mxschmitt/playwright-test-coverage

**Comment by twschiller** [comment]
This will be nice, but given that we're working through the list of manual regression tests, the coverage of test cases/stores will be a better metric of coverage than code coverage. So I'd prioritize any blockers to testing over collecting code coverage

**Comment by fungairino** [comment]
Here's a quick demo branch of generating initial code coverage. We would still need to figure out a way to generate coverage for pop-up pages like the sidebar and for the service worker.
https://github.com/pixiebrix/pixiebrix-extension/commit/b0200ca0533b7c34644fa77c49c1070e1422fe74
