### ISSUE TITLE
Test permissions upgrade requirement from MV2 to MV3

### ISSUE THREAD

**Issue by twschiller** [pixiebrix/pixiebrix-extension#8103]
Context
---
- https://www.notion.so/pixiebrix/Testing-Manifest-json-changes-and-permissions-changes-c60283073fba40d98ee28cdeab19b04a?pvs=4
- The MV3 manifest includes some new MV3-only permissions, but they might not require a permissions re-prompt
- Test if upgrade from MV2 to MV3 browser extension will require end-user to reactivate the extension

**Comment by grahamlangford** [comment]
Duplicate
