### ISSUE TITLE
Show “Panel is no longer available” overlay on temporary sidebar panels/forms on MV3 navigation

### ISSUE THREAD

**Issue by twschiller** [pixiebrix/pixiebrix-extension#8105]
- https://www.notion.so/pixiebrix/Phase-2-gracefully-handle-non-SPA-navigation-in-the-Chromium-Side-Panel-0efdedb6c1e44b088e65106202e08c28?pvs=4#63b9bbed5b4247249e3975922040e7bc

**Comment by fregante** [comment]
Duplicate of https://github.com/pixiebrix/pixiebrix-extension/issues/7369? Either one can be closed

**Comment by twschiller** [comment]
Leaving both open for now. This issue is about temporary sidebar panels/forms. The other is about persistent panels and forms. They're both off of here: https://www.notion.so/pixiebrix/Phase-gracefully-handle-non-SPA-navigation-in-the-Chromium-Side-Panel-0efdedb6c1e44b088e65106202e08c28?pvs=4

**Comment by grahamlangford** [comment]
Superseded by https://github.com/pixiebrix/pixiebrix-extension/issues/8209

**Comment by grahamlangford** [comment]
Superseded by https://github.com/pixiebrix/pixiebrix-extension/issues/8209
