### ISSUE TITLE
Lazyload templating dependencies

### ISSUE THREAD

**Issue by fregante** [pixiebrix/pixiebrix-extension#811]
Templating engines are a large part of almost every bundle and often they're not immediately needed (I suppose)

- nunjucks
- mustache
- handlebars

I think it would make sense to split/lazyload them like we used to do with the icons. A smaller initial bundle will help the initial parsing and display of each page.

Related:

- https://github.com/pixiebrix/pixiebrix-extension/issues/105
	
	Fixing this would probably help towards fixing that issue as well since the codebase will be ready for lazyloaded templating dependencies.

- #411

**Comment by twschiller** [comment]
> Fixing this would probably help towards fixing that issue as well since the codebase

Firefox doesn't support the sandbox, so we'll still want to split even if we're not including the sandbox

I would include Mustache in the bundle by default for performance times, and then async load nunjucks and handlebars

There's only one module where they're imported. The "problem" is that mapValues is synchronous, so if we make it async, we'll need to change a lot of call sites. I still think this is worth doing though, as it's necessary to move evaluation to the sandbox on Chrome
