### ISSUE TITLE
Test user impact of upgrading from MV2 to MV3

### ISSUE THREAD

**Issue by grahamlangford** [pixiebrix/pixiebrix-extension#8129]
Motivation
---

- We'll soon be switching the Chrome Manifest Version of the Extension from 2 to 3 in the store
- Some changes to the manifest.json can lead to the Extension being disabled for users until they re-enable
- We want to confirm if that behavior or any other unusual behaviors occur when upgrading

Notes
--- 
- The MV3 manifest includes some new MV3-only permissions, but they might not require a permissions re-prompt
- Test if upgrade from MV2 to MV3 browser extension will require end-user to reactivate the extension
- We've used a tool to test manifest changes previously
    - See: https://www.notion.so/pixiebrix/Testing-Manifest-json-changes-and-permissions-changes-c60283073fba40d98ee28cdeab19b04a
    - Might not work this time because there's more to the change than just the manifest version
    - Document is out of date, should no longer need to update the App `.env`. It may even be possible to test against the production version of App

Implementation Sketch
--- 
- Use tool mentioned above to swap out MV2 with MV3
    - Ensure that the Extension works normally

**Comment by twschiller** [comment]
@grahamlangford there was an issue here: https://github.com/pixiebrix/pixiebrix-extension/issues/8103. We can drop one of the issues

**Comment by mnholtz** [comment]
I was able to get the testing tool running with production to test MV2 -> MV3. See loom below for that demo:
https://www.loom.com/share/ab7a05432624463b9b13d5a9dc087c1e
