### ISSUE TITLE
AA Brick Configuration: improve bot/task search input UX

### ISSUE THREAD

**Issue by BLoe** [pixiebrix/pixiebrix-extension#8138]
[See this Loom that demonstrates most of the following issues](https://www.loom.com/share/71eed58fa7384a349be8c8521928e2d4)

Definition of Done
---
- [ ] Make the Bot dropdown clearable (the underlying widget theoretically already supports `isClearable`)
- [ ] Update searchBots/searchApiTasks and their corresponding inputs [to provide a page of results if there is no query](https://github.com/pixiebrix/pixiebrix-extension/blob/b2b87d2331155b25c58b155891d12a3f2ad54f76/src/contrib/automationanywhere/aaApi.ts#L196-L196). Does react-select just not run the request if there's no query? 

Related Issues:
---
- Caching/stale value issues have been moved to: https://github.com/pixiebrix/pixiebrix-extension/issues/7325

**Comment by twschiller** [comment]
@BLoe @grahamlangford how does this issue relate to the other tickets?
