### ISSUE TITLE
The editor should not show the intermediary "Welcome" page every time

### ISSUE THREAD

**Issue by fregante** [pixiebrix/pixiebrix-extension#814]
Every time I open the editor I'm fooled into thinking I have to fill in the form on the **Welcome screen**, but it's actually just loading the next screen.

![slow](https://user-images.githubusercontent.com/1402241/125989862-83a23848-828d-4490-b91c-4eceeb367a7f.gif)

Improvements possible:

- [ ] don't show this screen while checking (I think it should ever only be shown on the first install)
- [ ] performance! It takes a few second from the click until the final page loads, sometimes even more than a few. What's holding the welcome page for so long?

**Comment by twschiller** [comment]
> holding the welcome page for so long?

It's making a server call to determine whether or not you have an account scope defined: http://github.com/pixiebrix/pixiebrix-extension/blob/da448c93bdb85cdc0a9915e7d9a97d945e554224/src/devTools/Panel.tsx#L78-L78

The background page should already know that, though, so we should be able to make that check must faster

> don't show this screen while checking 

Agree that we should be continuing to show the loading indicator or a stencil while that check is resolving. We can also just optimistically show the main interface while the check is pending
