### ISSUE TITLE
Verify AA OAuth2 integration is working in the Page Editor

### ISSUE THREAD

**Issue by BLoe** [pixiebrix/pixiebrix-extension#8145]
Definition of Done
---
- [x] Verify that AA OAuth2 integration is working in the Page Editor
- [x] Can be used with the Run Bot/Run API Task bricks

**Comment by twschiller** [comment]
@BLoe is this issue status up to date? From Slack is seemed like this is in progress or complete?

**Comment by BLoe** [comment]
We should be good to go here, I validated with Mark that things are all working.
