### ISSUE TITLE
Insert at Cursor not working on Zendesk

### ISSUE THREAD

**Issue by grahamlangford** [pixiebrix/pixiebrix-extension#8154]
## Describe the bug

When running the `Insert at Cursor` brick on Zendesk, the text is not being inserted even though the brick reports running successfully 

## To Reproduce

https://www.loom.com/share/c7a405c5b8564d498e3108f2b33d0fbb

## Desktop (please complete the following information):

- Extension Version: 1.8.12-alpha.2
- Manifest Version: 2 & 3

## Additional context

> It looks like potentially it’s the first time that it fails, but works on subsequent ones. So potentially an issue with focus tracking/restore

- https://pixiebrix.slack.com/archives/C06G212E3U1/p1712246489165759

**Comment by twschiller** [comment]
We've seen this issue before, but I thought we had fixed it. There was a problem with focus tracking when mousing into the sidebar. Might have been a regression due to text selection menu behavior

**Comment by twschiller** [comment]
Potentially related: https://github.com/pixiebrix/pixiebrix-extension/issues/7922. If you see console error messages about the target element not being found here: https://github.com/pixiebrix/pixiebrix-extension/blob/feature%2F8157-draft-js/src/pageScript/pageScript.ts#L283-L283

**Comment by twschiller** [comment]
@fungairino potentially we also need to look at use of https://github.com/pixiebrix/pixiebrix-extension/blob/1b84b17b3e8cb5553970a110b1e1a29cd6109200/src/utils/focusController.ts#L35-L35

**Comment by twschiller** [comment]
@grahamlangford I think this can slip to 1.8.13 if required. We'd just want to cut an alpha asap for @MMirandi
