### ISSUE TITLE
Extension Console mods and Page Editor mods activated keep getting out of sync

### ISSUE THREAD

**Issue by grahamlangford** [pixiebrix/pixiebrix-extension#8159]
## Describe the bug

https://pixiebrix.slack.com/archives/C0436P48QHY/p1712256983102099

## To Reproduce

1. Install the MV3 version of the Extension
2. Activate a mod in the Extension Console
3. Attempt to edit the mod in the Page Editor

## Actual behavior

The mod is not visible in the Page Editor

## Expected behavior

The mod is visible in the Page Editor

## Desktop (please complete the following information):

- Extension Version: 1.8.12-alpha.2
- Manifest Version: MV2 and MV3

## Discussion

- Where exactly is the session change triggered? https://github.com/pixiebrix/pixiebrix-extension/blob/6e2f02e1d6f2c6fa8bf8f96be25278bc4586bbe5/src/store/optionsStore.ts#L116-L116
- It would be from one of the actions here: https://github.com/pixiebrix/pixiebrix-extension/blob/6e2f02e1d6f2c6fa8bf8f96be25278bc4586bbe5/src/store/sessionChanges/sessionChangesListenerMiddleware.ts#L40-L40
- Another context could potentially be overwriting the changes made by the Extension Console tab?

## Related Issues
- https://github.com/pixiebrix/pixiebrix-extension/issues/8218

**Comment by twschiller** [comment]
> The mod is visible in the Page Editor

When the mod is activated, the Page Editor should show a message that the mods were edited somewhere else and prompt the user to click to reload the Page Editor

@mthek10 to confirm, it sounds like you're not seeing that screen in the Page Editor?

**Comment by grahamlangford** [comment]
The issue was the mod definition had several hundred unused extensionPoints. We'll eventually have to fix Page Editor saving to prevent us from getting into this state. Temporarily resolved by deleting the excess extensionPoints

**Comment by twschiller** [comment]
For reference, here's the https://github.com/pixiebrix/pixiebrix-extension/issues/6529. The invariant check appears to not be working
