### ISSUE TITLE
Reduce Lodash usage

### ISSUE THREAD

**Issue by fregante** [pixiebrix/pixiebrix-extension#816]
Related:

- #411 
- https://youmightnotneed.com/lodash/

Dropping Lodash entirely might not be ideal since it has some useful methods like `cloneDeep` but the vast majority are now either native (`every`, `fromPairs`, `sortBy`) or trivial (`noop`, `identity`, `head`). Since it's a substantial module, dropping its imports wherever possible will potentially also speed up the bundling (a lil bit)

**Comment by twschiller** [comment]
I agree we're using a relatively small subset of lodash. 

I could be in favor of:
- Enabling a linting rule that points for certain lodash methods points to their native implementation 
- Enabling a linting rule that enforces import of the specific lodash method as opposed to a destructured import

This should get the use the best of both worlds

The things I want to avoid are:
- re-implementing any utility methods (e.g., partition) that are implemented in lodash
- Using native patterns that are more difficult to read

**Comment by fregante** [comment]
It looks like plug-ins exist!

- Enforce import style: https://www.npmjs.com/package/eslint-plugin-lodash
- Avoid lodash altogether when possible: https://www.npmjs.com/package/eslint-plugin-you-dont-need-lodash-underscore

**Comment by fregante** [comment]
> The things I want to avoid are:

Agreed! In some cases they can still be rewritten with a different logic though, for example:

```js
const [, removed] = partition(this.extensions, (currentExtension) =>
  updatedIds.has(currentExtension.id)
);
```

👇 
```js
const removed = this.extensions.filter((currentExtension) =>
  updatedIds.has(currentExtension.id)
);
```

**Comment by twschiller** [comment]
Don't hate the player, hate the game: http://github.com/pixiebrix/pixiebrix-app/blob/b202fb204ce471f42c5d7635951108cc6cd90eb1/pixiebrix-app/src/pages/deployments/EngagementTable.tsx#L2-L2

![image](https://user-images.githubusercontent.com/1879821/128103873-659ec90e-4db8-4f3e-95d6-0ef8fbbe967e.png)

**Comment by fregante** [comment]
Heartbreaking. 

<img src="https://user-images.githubusercontent.com/1402241/128116216-c44a7779-7486-4b4c-b423-355de2464718.jpeg" width="200">

But yeah this *by functions are useful
