### ISSUE TITLE
Make the UI/UX of API-based options widgets consistent

### ISSUE THREAD

**Issue by twschiller** [pixiebrix/pixiebrix-extension#8198]
Context
---
- RemoteSelectWidget: loads options from remote source
- AsyncRemoteSelectWidget: loads options based on user query

Affordances required:
---
- Loading state: react-select supports a loading indicator. It's automatically or manually controlled: https://react-select.com/props#async-props:~:text=any-,loadOptions,-Function%20that%20returns
- Error state
- Placeholder: the AsyncRemoteSelectWidget needs messaging instructing to search
- Empty/no-results state
- Refresh button: refetch the results from the remote source. Likely want to match what we do for the integration configuration/database drop-downs for consistency

Discussion
---
- Ideally these changes would correspond to the widget, not the entire field
- `react-select` doesn't have native support for error states, we'll have to write our own: https://github.com/pixiebrix/pixiebrix-extension/blob/b2b87d2331155b25c58b155891d12a3f2ad54f76/src/components/form/widgets/AsyncRemoteSelectWidget.tsx#L110-L110

Screenshot
---
AsyncRemoteSelectWidget currently uses muted/disable text. RemoteSelectWidget doesn't render the select and instead shows an error message:

![image](https://github.com/pixiebrix/pixiebrix-extension/assets/1879821/4a3ffe35-858b-4f8b-920e-aae03a07a8b5)

**Comment by twschiller** [comment]
@BrandonPxBx could you propose some standard UI?

**Comment by twschiller** [comment]
@BLoe I think you're completing this as part of https://github.com/pixiebrix/pixiebrix-extension/issues/8070?

**Comment by BLoe** [comment]
Ah yeah, I forgot there was a separate issue here. Yes we are addressing this.

**Comment by BLoe** [comment]
Closed by #8399
