### ISSUE TITLE
[Spike] gracefully handle page reload/navigation in the Chromium Side Panel

### ISSUE THREAD

**Issue by grahamlangford** [pixiebrix/pixiebrix-extension#8209]
## Phase Spec

- https://www.notion.so/pixiebrix/Phase-gracefully-handle-page-reload-navigation-in-the-Chromium-Side-Panel-0efdedb6c1e44b088e65106202e08c28

## Acceptance Criteria

- [x] Slices specified
- [x] Approval Matrix signed off
- [x] Slices converted to issues
- [x] Issues added to _insert epic name_
- [x] Tech Lead notified for prioritization

**Comment by twschiller** [comment]
Some existing placeholder issues we can use (or would need to be closed as duplicates):
* https://github.com/pixiebrix/pixiebrix-extension/issues/7369
* https://github.com/pixiebrix/pixiebrix-extension/issues/8105
