### ISSUE TITLE
Delayed launching of the LoginBanner after deployment

### ISSUE THREAD

**Issue by grahamlangford** [pixiebrix/pixiebrix-extension#8217]
## Describe the bug

When deploying a mod with a team OAuth2 integration (Google Drive), after receiving the deployment the `LoginBanner` does not launch immediately

## To Reproduce

1. Create a Google Drive team integration
2. Create a deployment for a mod that uses that team integration
3. Wait for the mod to be installed by the background script

## Actual behavior

The LoginBanner either never shows or takes a very long time to show. Running the mod leads to errors due to authentication errors.

## Expected behavior

As soon as the mod is deployed/activated, the user should see the LoginBanner appear

## Additional context

- https://pixiebrix.slack.com/archives/C0436P48QHY/p1712690509038379

**Comment by twschiller** [comment]
> after receiving the deployment the LoginBanner does not launch immediately

The banner will only appear once an API request is made from that page. So the root cause might be a difference in expectations on when the mod runs after deployment?

**Comment by grahamlangford** [comment]
> The banner will only appear once an API request is made from that page. So the root cause might be a difference in expectations on when the mod runs after deployment?

From the loom in the slack thread, it appeared that the mod ran and errored without launching the LoginBanner, but it's hard to tell exactly what's going on in the loom. 

cc @brittanyjoiner15
