### ISSUE TITLE
Mod not active after activation via Extension Console

### ISSUE THREAD

**Issue by twschiller** [pixiebrix/pixiebrix-extension#8218]
## Describe the bug

- https://pixiebrix.slack.com/archives/C0436P48QHY/p1712777593678799

## To Reproduce

- See Slack report (does not happen all the time)

## Actual behavior

- Shows activation success message
- But mod is not active and when refreshing extension console, it doesn't appear as active

## Expected behavior

- Mod is activated

## Screenshots/Loom

- See Loom: https://pixiebrix.slack.com/archives/C0436P48QHY/p1712777593678799

## Desktop (please complete the following information):

- OS: Mac
- Browser: Chrome
- Extension Version: 1.8.12-mv3

## Additional context

- Will need access to staging team (see Slack)

## Related Issues

- Potentially related to https://github.com/pixiebrix/pixiebrix-extension/issues/8159

## Discussion

- Could potentially be cause by another context overwriting the Redux state with a stale version of the state
- The redirect to the mods page appears to only occur on success: https://github.com/pixiebrix/pixiebrix-extension/blob/6e2f02e1d6f2c6fa8bf8f96be25278bc4586bbe5/src/extensionConsole/pages/activateMod/ActivateModCard.tsx#L169-L169

**Comment by grahamlangford** [comment]
The issue was the mod definition had several hundred unused extensionPoints. We'll eventually have to fix Page Editor saving to prevent us from getting into this state. Temporarily resolved by deleting the excess extensionPoints

**Comment by twschiller** [comment]
For reference, here's the https://github.com/pixiebrix/pixiebrix-extension/issues/6529. The invariant check appears to not be working
