### ISSUE TITLE
RENDER_NUNJUCKS not available within 3 seconds

### ISSUE THREAD

**Issue by twschiller** [pixiebrix/pixiebrix-extension#8220]
## Describe the bug

- RENDER_NUNJUCKS not available within 3 seconds

## To Reproduce

The error is intermittent. What @brittanyjoiner15 is seeing is most likely that either: 1) a selection watch trigger is failing, or 2) a page load trigger (e.g., to fetch announcements) is failing on some pages

Likely steps to reproduce:
- Add a page load trigger with no debounce
- Configure the trigger to show an error on failure
- Add a brick that uses a nunjucks template. E.g., the identity brick with `{{ @input.url }}`
- Browse the web and wait for the error to pop up

## Actual behavior

- A mod fails with error "RENDER_NUNJUCKS not available within 3 seconds"
- Behavior depends on what the triggers error handler is set to (i.e., whether or not an error toast will be shown)

## Discussion

- RENDER_NUNJUCKS is handled by the sandbox injected into the page: https://github.com/pixiebrix/pixiebrix-extension/blob/6e2f02e1d6f2c6fa8bf8f96be25278bc4586bbe5/src/sandbox/messenger/api.ts#L62-L62
- In MV3, all nunjucks evaluation is run via the Sandbox. (In MV2, you have to toggle it on. Javascript brick is always run in the sandbox though)
- To diagnose the error, you need to figure out whether that error would be thrown if:
  - Is the sandbox not getting added to the page properly? Or,
  - Is the sandbox added, but then getting removed?
  - Is the sandbox on the page, but it's not responding in time (e.g., b/c it's processing another message)?

## Potential Solution

- Add automatic retries when renderNunjucks fails
- Advice users to refresh the page if renderNunjucks fails 4 times
- Similar to: https://github.com/pixiebrix/pixiebrix-extension/pull/8474

**Comment by brittanyjoiner15** [comment]
![image](https://github.com/pixiebrix/pixiebrix-extension/assets/16166290/32cafaec-76bd-4279-81bd-b328fed3dfc6)

This just happened again, i think it's relating to the announcements mod.

**Comment by brittanyjoiner15** [comment]
FInally got into the logs in time - confirmed its the announcements mod
![image](https://github.com/pixiebrix/pixiebrix-extension/assets/16166290/683fe2d3-7e88-44ec-8bf9-c867150172a3)

**Comment by brittanyjoiner15** [comment]
I believe its this brick? 

![image](https://github.com/pixiebrix/pixiebrix-extension/assets/16166290/8090c63c-246c-4ec7-8ddd-9b6bddfd6378)

**Comment by twschiller** [comment]
Have been able to replicate sporadically. Will add more logging to my repro mod to collect information

![image](https://github.com/pixiebrix/pixiebrix-extension/assets/1879821/213b29a7-daaa-40a0-bc84-737631806ef3)

**Comment by twschiller** [comment]
I managed to get the error from the KB Assist selection trigger during the normal course of writing up a Github issue. That happened even though I had been on the page for awhile:

![image](https://github.com/pixiebrix/pixiebrix-extension/assets/1879821/71a5de6e-3867-4fd8-bab2-4d25aa3a14c4)

**Comment by brittanyjoiner15** [comment]
@twschiller been using your mod, and i think pixiebrix is trying to tell me not to check my amazon orders during work hours 😂  (seems like that triggers the mod)

![image](https://github.com/pixiebrix/pixiebrix-extension/assets/16166290/0e959949-ad4d-43c5-ad2d-07470e4e927d)

**Comment by brittanyjoiner15** [comment]
Happened again, this time in slack, but i don't think the mod ran because i don't see the window alert with the URL 

![image](https://github.com/pixiebrix/pixiebrix-extension/assets/16166290/c54298e6-03b3-4707-bf4d-4d498072ccdf)

**Comment by brittanyjoiner15** [comment]
Happened again, this time in slack. Don't think the mod ran though, because i didn't see the window alert with the url. Just saw the render_nunjucks error.

**Comment by brittanyjoiner15** [comment]
I'm still assuming this is related to the mod that @twschiller made that i added that will report the business errors and show these URLs. I just got an error on https://app.pixiebrix.com/admin/marketplace/listing/?q=%40pixiebrix%2Fcommand%2Ftext-command

It showed the URL but then also showed an error with the URL. Of course i can't reproduce now that i didn't get a screenshot

**Comment by twschiller** [comment]
Potentially related to https://github.com/pixiebrix/pixiebrix-extension/issues/8168 if the sidebar is just loading slowly

**Comment by brittanyjoiner15** [comment]
Happening on LinkedIn in frames: 
![image](https://github.com/pixiebrix/pixiebrix-extension/assets/16166290/0a324d5e-7e9c-4991-9d57-bc7762444315)

**Comment by grahamlangford** [comment]
https://pixiebrix.slack.com/archives/C023KL47XV4/p1720029626794029

**Comment by twschiller** [comment]
@grahamlangford I agree - let's prioritize. As you mention, first step should be prioritizing attempting to re-inject the sandbox. 

To clarify definition of done: we need to add the retry to all methods that call into the Sandbox (Nunjucks, run JS), etc. The `loadSandbox` method itself should potentially contain the check/retry: https://github.com/pixiebrix/pixiebrix-extension/blob/72334200b17050bde676dbf234650f147f53ac8a/src/sandbox/messenger/api.ts#L26-L26

**Comment by twschiller** [comment]
@grahamlangford we implemented the workaround for the customer. They'll be soft-launching Monday this week, so we'll have more information on urgency

I agree we should still prioritize though
