### ISSUE TITLE
Beta logo proportions are wrong in the Extension Console

### ISSUE THREAD

**Issue by twschiller** [pixiebrix/pixiebrix-extension#8229]
## Describe the bug

- https://pixiebrix.slack.com/archives/C0436P48QHY/p1712864681216039
- @BrandonPxBx please add any additional context/guidance

## Screenshots/Loom

Beta Channel:

![image](https://github.com/pixiebrix/pixiebrix-extension/assets/1879821/51c96c8e-6579-4678-bf3c-737d2a466caa)

Normal:

![image](https://github.com/pixiebrix/pixiebrix-extension/assets/1879821/d1c0dff6-4c01-456c-a6e3-2483e089e868)

## Desktop (please complete the following information):

- OS: Mac
- Browser: Chrome
- Extension Version: 1.8.12 CWS Channel Build

**Comment by BrandonPxBx** [comment]
This is a duplicate issue https://github.com/pixiebrix/pixiebrix-extension/pull/8230#pullrequestreview-1995166153
