### ISSUE TITLE
Lint the dependency lists for useAsyncEffect and useAsyncState

### ISSUE THREAD

**Issue by BLoe** [pixiebrix/pixiebrix-extension#8235]
See this section on the use-async-effect docs: https://github.com/rauldeheer/use-async-effect?tab=readme-ov-file#linting-dependencies-list-using-eslint

We should try to get lint to check the dependencies for both `useAsyncEffect` and `useAsyncState`.

**Comment by grahamlangford** [comment]
Duplicate of https://github.com/pixiebrix/eslint-config-pixiebrix/issues/70
