### ISSUE TITLE
Visual Regressions from the IsolatedComponent work

### ISSUE THREAD

**Issue by grahamlangford** [pixiebrix/pixiebrix-extension#8237]
> Oh the issue is that my `renderWidget` PR removed the shadow DOM because it's supposed to only be part of the `IsolatedComponent`. This week I'll send a PR combining these two new pieces.

_Originally posted by @fregante in https://github.com/pixiebrix/pixiebrix-extension/pull/8234#discussion_r1562089789_

Notes
---
- `all: initial` was previously set on `modalDom` as a workaround to fix opacity issues
    - https://github.com/pixiebrix/pixiebrix-extension/pull/8234
- Font color on `IsolatedComponents` has been reset to solid black

**Comment by fregante** [comment]
> Font color on IsolatedComponents has been reset to solid black

Where is the color not supposed to be black?

**Comment by twschiller** [comment]
You can see that the color previously was off black (I'd need to look at CWS for exact hex code and what stylesheet it came from). Also there might be a padding/or root font-size change?:

<img width="874" alt="image" src="https://github.com/pixiebrix/pixiebrix-extension/assets/1879821/6c57899a-77d8-4732-b903-99cf34032d87">

**Comment by fregante** [comment]
I think the solution would be to enable the shadow DOM on renderWidget again. It's fine if there are two shadow DOM wrappers

**Comment by twschiller** [comment]
Comment thread on impact on customer mod: https://pixiebrix.slack.com/archives/C0671QASFMZ/p1713186904097249

**Comment by fregante** [comment]
Where was the off-black color coming from? My guess is that `all: initial` is doing its job, and it wasn't there before. 

I assume that DocumentView is in the shadow DOM to allow the customer to change its style and avoid style leaks. 

So should this be optional? It can't both be isolated and inherit styles. The existing `noStyle` option should probably toggle two states:

- inherit style, load our style in the Shadow DOM
- `all:initial` + don't load our style
