### ISSUE TITLE
Sidebar mod panel flashing/re-render

### ISSUE THREAD

**Issue by twschiller** [pixiebrix/pixiebrix-extension#8245]
## Describe the bug

- https://pixiebrix.slack.com/archives/C0436P48QHY/p1712946233756539
- Panel content flashes
- Hypotheses: might be due to either: 1) CSS stylesheets resolving, 2) unnecessary React re-mounts. From the video, looks like an unnecessary React re-mount of the whole panel
- Appears on panels that listen for state updates. 

## To Reproduce

1. Open the `@pixies/templates/kb`
2. Run a search an open the result

## Actual Behavior

- Panel appears to flash/do a full re-render

## Screenshots/Loom

- See Loom: https://pixiebrix.slack.com/archives/C0436P48QHY/p1712946233756539

## Desktop (please complete the following information):

- Browser: Chrome
- Extension Version: MV3

## Additional context

- What mod(s) were you running?: @pixies/templates/kb

## Related Issues

- https://pixiebrix.slack.com/archives/C0436P48QHY/p1712850969345089: panel re-mounts could be a root cause

**Comment by brittanyjoiner15** [comment]
Just wanted to share that im experiencing this again - you can see it a bit in my demo here: https://www.loom.com/share/3904c790174244aa815002c536f80c2d

**Comment by brittanyjoiner15** [comment]
@grahamlangford could we add the bug label to this? I was searching for it in my mod and realized it didn't come up because it doesn't have the bug label, but seems to be a bug report

**Comment by twschiller** [comment]
Visually, it looks like a React re-mount. Potential root causes:
* @fregante had made some changes with React keys (adding keys in places)
* @fregante had made some changes with shadow dom location in the tree

**Comment by twschiller** [comment]
Additionally causing problems with text entry field losing focus (potentially only on MV3?): https://pixiebrix.slack.com/archives/C0436P48QHY/p1713815247793639
