### ISSUE TITLE
Sidepanel user gesture error opening sidebar from trigger

### ISSUE THREAD

**Issue by twschiller** [pixiebrix/pixiebrix-extension#8281]
## Describe the bug

- https://pixiebrix.slack.com/archives/C0436P48QHY/p1713321165258629

## Steps to Reproduce

- Create mod that runs when a page is loaded
- Go to the page
- Click the "Click "OK" to open the sidebar" button

## Actual behavior

- PixieBrix showed the sidebar dialog. But after clicking, PixieBrix shows an error toast 

![image](https://github.com/pixiebrix/pixiebrix-extension/assets/1879821/3a4235e3-7ee7-42f8-a877-28751cbbf5b4)

## Expected behavior

- PixieBrix shows a dialog for the user to click to open the sidebar

## Desktop (please complete the following information):

- Browser: Chrome
- Extension Version: 1.8.13-alpha.3-mv3

**Comment by brittanyjoiner15** [comment]
Just saw this happen again on restream.io
