### ISSUE TITLE
FORM_GET_DEFINITION not found

### ISSUE THREAD

**Issue by twschiller** [pixiebrix/pixiebrix-extension#8283]
## Describe the bug

- https://pixiebrix.slack.com/archives/C0436P48QHY/p1713284471705029

## To Reproduce

**Flaky**

1. Open browser using 1.8.12 with your pixiebrix account (so you'll be triggered to see a notice)
2. Go to any webpage
3. The modal appears with the purple loading indicator, and then shows a message saying the target for form_get_definition was not found.

## Actual behavior

![image](https://github.com/pixiebrix/pixiebrix-extension/assets/1879821/c1a7942e-71c7-422c-a28b-12164cbbff86)

## Expected behavior

Announcement shows as expected

## Desktop (please complete the following information):

- Browser: Chrome
- Extension Version: 1.8.12 (MV2)

**Comment by twschiller** [comment]
We're having a customer reporting this problem for a user on the team announcements mod. 

Given the error message, my hypothesis is that the mod is first running while the content is being pre-rendered (and therefore has a non-0 frame id). By the time the form messages the main page, it's now frame 0 so the message fails

I was hoping @fungairino's PR for page lifecycle would have addressed the root cause. But it's still an issue

**Comment by fungairino** [comment]
I was able to replicate this error by using a simple trigger mod that shows a modal on page load, and then loading a prerendered page (type in google in url, wait a second, and hit enter)

![Screenshot 2024-06-13 at 3 25 38 PM](https://github.com/pixiebrix/pixiebrix-extension/assets/3498063/cb909807-ce06-4cab-bf06-81b6d52f3e14)

The problem we need to solve is to make sure that these ephemeralForms maintain the correct reference to their target after being prerendered:
https://github.com/pixiebrix/pixiebrix-extension/blob/d6a1f25ecea107f404b6d2ec4e6f8066af7505aa/src/contentScript/ephemeralPanel.ts#L52-L57

**Comment by fungairino** [comment]
One hypothesis is that the webext-messenger is caching the old value of the target before the prerendered page is swapped as the active page.

https://github.com/pixiebrix/webext-messenger/blob/main/source/thisTarget.ts#L63

**Comment by fungairino** [comment]
I confirmed that the above hypothesis is correct. Modifying the webext-messenger as shown below fixes the issue. The change would require us checking the tabData every single call, so we should find a way to detect when we need to refetch the tab data in the webext-messenger.

```
// removed `once` call wrapping 
const storeTabData = async () => {
    // if (tabDataStatus !== "needed") {
    //     return;
    // }
    try {
        tabDataStatus = "pending";
        Object.assign(thisTarget, await messenger("__getTabData", {}, { page: "any" }));
        tabDataStatus = "received";
    }
    catch (error) {
        tabDataStatus = "error";
        throw new MessengerError("Tab registration failed. This page won’t be able to receive messages that require tab information", { cause: error });
    }
};
```

**Comment by twschiller** [comment]
@fungairino in this scenario, is it the sender (iframe) or the top-level frame that's the issue? My understanding is the stale target is coming before the call to getFormDefinition: https://github.com/pixiebrix/pixiebrix-extension/blob/d095691e1f9ebe9b73be90f1260256a4e8d19f78/src/bricks/transformers/ephemeralForm/EphemeralForm.tsx#L103-L103

I'm not sure I understand the sequence using __getTabData

Is it the following sequence?
1. Top-level frame is pre-rendered 
2. Top-level frame adds the modal with `?target={tab: 123, frame: 12952}`
3. Top-level frame is switched to have frame 0
4. Top-level frame initializes messenger `__getTabData` with frame 0
5. Modal frame initializes `__getTabData`
6. Modal frame messages target `{tab: 123, frame: 12952}`
    - Nothing responds
    - Modal frame messenger throws

Or is it a different sequence?

**Comment by fungairino** [comment]
The sequence you described is not exactly what's going on, as far as I can tell.

> 2. Top-level frame adds the modal with ?target={tab: 123, frame: 12952}

Happens for sure after the top-level frame is switched to be frame 0.

I think what is happening is that `storeTabData` is called during prerendering and caches the tab / frame value even after the prerendering is done and the target is switched to frame 0.

So we either have to ensure we don't call this until the document is done prerendering, or make a change in webext-messenger to not cache the `thisTarget` value while the document is in prerendering state.

**Comment by twschiller** [comment]
@fungairino could you write out exactly the bad sequence you think is happening and what is happening in the sender/receiver? My understanding is that the receiver is what uses `storeTabData` so it knows which messages to respond to?

> Happens for sure after the top-level frame is switched to be frame 0.

I'm not sure I understand. Isn't the frameId in the frame URL the non-zero frame? And that's why the frame is trying to message frame 12952 and not frame 0?

**Comment by fungairino** [comment]
The sequence is the following:
1. While initializing the content script, the import dependency chain imports `webext-messenger`
The example import sequence I logged was the following, but there are probably other import sequences.
```
    at thisTarget.js:48:1
    at shared.js:25:1
    at initPrivateApi (thisTarget.js:108:1)
    at ./node_modules/webext-messenger/distribution/index.js (index.js:11:15)
    at __webpack_require__ (contentScript.js:9993:42)
    at ./src/telemetry/reportError.ts (logging.ts:568:2)
    at __webpack_require__ (contentScript.js:9993:42)
    at ./src/telemetry/reportUncaughtErrors.ts (reportEvent.ts:41:2)
    at __webpack_require__ (contentScript.js:9993:42)
    at ./src/extensionContext.ts (rejectOnCancelled.ts:44:2)
```

2. webext-messenger index import runs `initPrivateApi()`
https://github.com/pixiebrix/webext-messenger/blob/main/source/index.ts#L14

3. initPrivateApi calls `storeTabData` which is wrapped in `once`. In the prerendering case this stores the {tabId, frameId} values during the prerendering state. This makes every subsequent call use these values, even after prerendering is done and the "real" values are swapped in for the frame.

4. Later on, when the modal is created, the url of the modal is set with the content script target (which is no longer correct) https://github.com/pixiebrix/pixiebrix-extension/blob/a8d3c3b7dbca92123931033004339799b2404a2c/src/contentScript/ephemeralForm.ts#L47

5. This value is used within the EphemeralForm in the `useAsyncState(async () => getFormDefinition(target, nonce), [nonce]);` [call](https://github.com/pixiebrix/pixiebrix-extension/blob/a25c54954c660ce78943cf8dc5749eeb5ed66dc9/src/bricks/transformers/ephemeralForm/EphemeralForm.tsx#L103). This attempts to message the old frame of the content script (that existed during prerendering), but fails since it no longer exists.

**Comment by fungairino** [comment]
A simple fix might be to check in `storeTabData` whether the document is currently in prerendering state, and if it is, then don't call with `once`.

**Comment by fungairino** [comment]
Not closed yet - we still need to use the new version of the messenger in the extension.
