### ISSUE TITLE
Sidebar form doesn't submit

### ISSUE THREAD

**Issue by twschiller** [pixiebrix/pixiebrix-extension#8284]
## Describe the bug

- https://pixiebrix.slack.com/archives/C0436P48QHY/p1713284277907749

## To Reproduce

> Not sure how to reproduce but im clicking submit in a mod and nothing is happening. I am sure if i refresh the page and load the mod again it will work.

1. install `@pixies/test/temp-form-in-sidebar`
2. open the form in the side panel
3. refresh the page
4. attempt to submit the form

## Actual behavior

- Clicking submit doesn't do anything

## Expected behavior

- Form shows an error if there's an invalid field, or
- Form submits when clicking submit

## Screenshots/Loom

- See Slack: https://pixiebrix.slack.com/archives/C0436P48QHY/p1713284277907749

## Desktop (please complete the following information):

- Browser: Chrome
- Extension Version: 1.8.13-alpha.3-mv3

## Additional context

- What mod(s) were you running?: `@pixies/internal/bug-tracker`
- What website(s) were you using?: Slack

**Comment by fungairino** [comment]
This happened to me as well as shown here:
https://pixiebrix.slack.com/archives/C0436P48QHY/p1713810182928819

**Comment by grahamlangford** [comment]
This may have been fixed by https://github.com/pixiebrix/pixiebrix-extension/pull/8330 and https://github.com/pixiebrix/pixiebrix-extension/pull/8325. It may also have had to do with the datadog logger fix. 

@brittanyjoiner15 can you attempt to replicate in 1.8.13-beta.5?

**Comment by grahamlangford** [comment]
Per @brittanyjoiner15 this issue is reproducible when the page is refreshed and a temporary form is open in the side panel. This issue should be resolved by #8293 

cc @fungairino
