### ISSUE TITLE
Make the sidebar open timeout experience better

### ISSUE THREAD

**Issue by fungairino** [pixiebrix/pixiebrix-extension#8287]
## User Story

As a mod consumer, I want to have a clear message around the sidebar taking longer to open, so that I'm not confused as to what to do or what's going on.

## Motivation

The error message we show to users when the sidebar is taking longer to load is very confusing and has no call to action.

![image](https://github.com/pixiebrix/pixiebrix-extension/assets/3498063/6acda4b7-1795-41f9-8885-4394d79a7f1f)

## Acceptance Criteria

This acceptance criteria is meant to be a stop gap for the phase in: https://www.notion.so/pixiebrix/Enable-recovery-from-intermittent-errors-flakiness-8e742782bd4444e891fc0327ec24c0f4?pvs=4

- After 3 seconds, show an info toast with copy: "The Sidebar is taking longer than expected to load. Retrying..."
- The info toast should be automatically dismissed when we hit the hard error timeout, or when the sidebar opens
  - Ideally, we'd hide the info toast once the sidebar is open (but before loading), because the sidebar shows its own loading indicator. But let's implement what's easiest
- Increase the hard error message to be thrown at the 12s mark (rather than 4s)
- Change the error message for timeout to read: "The Sidebar took too long to load. Retry your last action or reopen the Sidebar". 
- The error toast should not show the raw error detail from the messenger

**Comment by twschiller** [comment]
Clarified the acceptance criteria for this issue. We'll take a closer look in https://www.notion.so/pixiebrix/Enable-recovery-from-intermittent-errors-flakiness-8e742782bd4444e891fc0327ec24c0f4?pvs=4
