### ISSUE TITLE
Improve copy on the MV3 user gesture dialog

### ISSUE THREAD

**Issue by grahamlangford** [pixiebrix/pixiebrix-extension#8315]
Context
---
- In MV3, opening the sidebar requires a user gesture
- If too much time has passed (e.g., due to an API call), PixieBrix shows a dialog modal over the page to get the user to click to be used as the gesture Chrome requires to open the sidebar
- Current copy: "Please click "OK" to allow PixieBrix to open the sidebar."

Discussion
--- 
- @BrandonPxBx this is a good issue to quickly collect input on what copy would make the most sense to end users
- IIRC, the copy is in 2x+ different places. We might want to extract the copy as a constant

Definition of Done
---
- Change copy to 'Please click "Open Sidebar" to open the mod sidebar'
- Change button text to "Open Sidebar"
- "PixieBrix" branding removed from the dialog
- Update Playwright test utilities

Future Work
---
- Improve UI/theme: https://github.com/pixiebrix/pixiebrix-extension/issues/8301

**Comment by BrandonPxBx** [comment]
Is this a duplicate issue? https://github.com/pixiebrix/pixiebrix-extension/issues/8301

**Comment by grahamlangford** [comment]
No, this is just the "quick-win" copy changes. The other is for any UI styling changes we want to make

**Comment by BrandonPxBx** [comment]
On the previous issue: The definition of done copy and the current copy do not show a statistically significant difference in user preference. [Link to study](https://app.lyssna.com/tests/2a9caccc9faa/results/e83eb01eb57e).
