### ISSUE TITLE
Playwright: Create a mod using the Page Editor

### ISSUE THREAD

**Issue by grahamlangford** [pixiebrix/pixiebrix-extension#8316]
## User Story

As a PixieBrix engineer, I want an example of a Playwright test that creates a new mod, so that I can begin creating more complex test scenarios leveraging the Page Editor

## Motivation

Currently we have no way to cleanup after creating a mod using the Page Editor in Playwright

## Acceptance Criteria

Scenario: Create a mod in the Page Editor

- Given I am running Playwright tests
- When the "Create a mod in the Page Editor" test runs
- Then all of the steps to open the Page Editor, create a simple mod, and save it succeed

Scenario: Cleanup after creating a mod in the Page Editor

- Given all of the Playwright tests have finished running
- Then a cleanup function deletes the created mod(s)

**Comment by grahamlangford** [comment]
Note: I'm assuming we'll need to have a discussion on exactly what this looks like in practice

**Comment by mnholtz** [comment]
Some considerations off the top of my head:
- I imagine that this is a point where we'll want to consider introducing a cleanup endpoint that either the test runner or CI can hit before/after a test suite runs
- We'll have to also consider how this impacts tests running in parallel, e.g. running tests locally using the same credentials as CI could be problematic if we are sticking with the static user acct

**Comment by grahamlangford** [comment]
> I imagine that this is a point where we'll want to consider introducing a cleanup endpoint that either the test runner or CI can hit before/after a test suite runs

Potentially we could have a single `cleanup` endpoint that we call in the `globalTeardown`. We would need to be sure that we don't have mod name collisions in the tests, but that seems like a simple problem to solve.

**Comment by mnholtz** [comment]
**Implementation sketch for cleanup affordance**
- When creating mods, generate a unique id to interpolate into the mod name, e.g. "Test Mod <uuid>"
- In app project, introduce new cleanup endpoint for playwright tests
    - Upon cleanup, remove all UserExtension/Package instances with the unique id in the name (of course, filtered by our static test user id)
    - Upon cleanup, remove all UserExtensions/Packages created by test user that are older than 3hrs? or 24hrs? This is to ensure mods get cleaned up even if the teardown fails to initiate

**Comment by mnholtz** [comment]
After a synchronous conversation with @fungairino, I've decided to take the pure-frontend approach of executing mod cleanup in Playwright via the UI. We had some performance concerns with "what happens when test cleanup fails"? But it will be easy to setup a cron job to cleanup remaining old assets in that case. I vote to start with this approach and address those concerns as they come up.

**Comment by grahamlangford** [comment]
> * When creating mods, generate a unique id to interpolate into the mod name, e.g. "Test Mod `<uuid>`"

I'm assuming this is to prevent simultaneous runs from conflicting?

> * In app project, introduce new cleanup endpoint for playwright tests
>   * Upon cleanup, remove all UserExtension/Package instances with the unique id in the name (of course, filtered by our static test user id)

Same reasoning, prevent collisions?

>   * Upon cleanup, remove all UserExtensions/Packages created by test user that are older than 3hrs? or 24hrs? This is to ensure mods get cleaned up even if the teardown fails to initiate

We could just have a scheduled job  that runs 1/day to clear them from the db instead of exposing an endpoint?

**Comment by mnholtz** [comment]
> Same reasoning, prevent collisions?

Yep, preventing collisions. Otherwise, we wouldn't be able to run e2e tests on CI/locally in parallel, and those runs would likely interfere with each other, especially during cleanup
