### ISSUE TITLE
Speed up E2E error telemetry logging test

### ISSUE THREAD

**Issue by mnholtz** [pixiebrix/pixiebrix-extension#8348]
[See this test step](https://github.com/pixiebrix/pixiebrix-extension/blob/2521c02186fe317c9bbbeeb4fea8c7f9f23365cf/end-to-end-tests/tests/telemetry/errors.spec.ts#L58-L59) in our E2E error telemetry test. Due to Datadog browser SDK implementation, this test currently takes >30s to execute while waiting for the network request to be sent by the browser logging library.

Find out a way to get the network request to be sent sooner in order to speed up the test.

**Comment by twschiller** [comment]
@mnholtz thread on manual flush: https://github.com/DataDog/browser-sdk/issues/2327. Seems like not explicitly supported

**Comment by mnholtz** [comment]
@fungairino If I recall, you opened a datadog ticket about this particular issue? Do you have a reference to that thread?

**Comment by fungairino** [comment]
This looks promising as a work-around:

https://github.com/DataDog/browser-sdk/issues/2327#issuecomment-1677845075

**Comment by fungairino** [comment]
This was the issue they opened:
https://help.datadoghq.com/hc/en-us/requests/1754158

Their final message was:

>Thanks for waiting while I was checking with the team.
>
>To give you more context about my investigation, after your clarification I reached out to our team responsible for the browser-intake endpoint and they confirmed that unfortunately this is something that we don't currently support.
> 
>Given this I have modified the Feature request that I opened before to include a method on the client api that allows immediately flushing the buffered metrics.
