### ISSUE TITLE
Show Sidebar Brick not refreshing panel

### ISSUE THREAD

**Issue by grahamlangford** [pixiebrix/pixiebrix-extension#8376]
## Describe the bug

When the `Show Sidebar` brick runs, it should be refreshing the panel. Looks like this behavior was removed by mistake when adding the MV3 Side Panel. See the changes to the sidebarController: https://github.com/pixiebrix/pixiebrix-extension/pull/7354

## To Reproduce

1. Install `@pixies/misc/shared-notes-sidebar-v2`
2. Open the notes panel
3. Add a note

## Actual behavior

The note is added, but it is not shown until you refresh the sidebar

## Expected behavior

The note is added and is visible immediately

## Notes

- Update test added by https://github.com/pixiebrix/pixiebrix-extension/pull/8395

**Comment by twschiller** [comment]
Because this is a regression, let's include a Jest test or e2e test covering the regression

**Comment by grahamlangford** [comment]
> Because this is a regression, let's include a Jest test or e2e test covering the regression

That should be standard for all regressions
