### ISSUE TITLE
App crashes on version 1.8.13 because chrome.runtime is undefined

### ISSUE THREAD

**Issue by johnnymetz** [pixiebrix/pixiebrix-extension#8397]
## Describe the bug

The App is crashing when upgrading the Extension version from 1.8.11 to 1.8.13

See slack conversation: https://pixiebrix.slack.com/archives/C023KL47XV4/p1714672493730429

Similar issue: https://github.com/pixiebrix/pixiebrix-extension/issues/8273

## To Reproduce

1. Upgrade the Extension version in the App to 1.8.13 (or pull down the branch from https://github.com/pixiebrix/pixiebrix-app/pull/5180)
1. Re-install the npm dependencies
1. Run the App

## Actual behavior

The App crashes (see loom). Notice the following console error:

> Uncaught TypeError: Cannot read properties of undefined (reading 'onMessage')

This line is causing this problem: https://github.com/pixiebrix/pixiebrix-extension/blob/a35084f5addf3b63dfbe623178e599556860653c/src/tinyPages/offscreen.ts#L27

## Expected behavior

The App should run successfully.

## Screenshots/Loom

https://www.loom.com/share/65bb995fca304c038ce6e1e81c7cf33a

## Desktop (please complete the following information):

- OS: OSX
- Browser: Chrome
- Extension Version: 1.8.13

## Potential Solutions

1. ✅ [Confirmed it works] Use optional chaining which is what we did to fix the previous bug: https://github.com/pixiebrix/pixiebrix-extension/pull/8275
2. Move the `chrome.runtime` into a function so it's not run on module import
3. Figure out what in the App is causing this code to run and try not running it

Notes:
- `isExtensionContext()` doesn't work in the offscreen page, see [here](https://pixiebrix.slack.com/archives/C023KL47XV4/p1714673947124799?thread_ts=1714672493.730429&cid=C023KL47XV4)

**Comment by fregante** [comment]
> * `isExtensionContext()` doesn't work in the offscreen page, see [here](https://pixiebrix.slack.com/archives/C023KL47XV4/p1714673947124799?thread_ts=1714672493.730429&cid=C023KL47XV4)

This has been recently fixed in https://github.com/fregante/webext-detect/pull/32.

If you find issues in `webext-*` libraries you can always ping me as I maintain them for PixieBrix as well.
