### ISSUE TITLE
[Spike] Make it easy to find and configure the mod you want to deploy

### ISSUE THREAD

**Issue by grahamlangford** [pixiebrix/pixiebrix-extension#8398]
## Phase Spec

- https://www.notion.so/pixiebrix/Make-it-easy-to-find-and-configure-the-mod-you-want-to-deploy-fddb70aeb41142ed9bda27010f83c92e

## Acceptance Criteria

- [x] Slices specified
- [ ] Approval Matrix signed off
- [x] Slices converted to issues
- [x] Issues added to `Make it easy to find and configure the mod you want to deploy`
- [x] Tech Lead notified for prioritization

**Comment by mnholtz** [comment]
I went ahead and created the slices here: https://github.com/pixiebrix/pixiebrix-app/issues/new#workspaces/feature-board-648b6be80bad0700122cb282/epics/Z2lkOi8vcmFwdG9yL1plbmh1YkVwaWMvMTkyMTQ3?state=OPEN&state=TODO&state=IN_PROGRESS 

(I also adding blockers to each of the slices where needed)

Still waiting on @twschiller to approve the slicing though.
