### ISSUE TITLE
Snippet Shortcut Styling Regression

### ISSUE THREAD

**Issue by grahamlangford** [pixiebrix/pixiebrix-extension#8433]
## Describe the bug

- Snippet Shortcut Menu styling is unset
- First noted in Gmail, unknown if it occurs elsewhere
- Possibly related to the IsolatedComponent change

## To Reproduce

See https://pixiebrix.slack.com/archives/C0436P48QHY/p1715290748216759

**Comment by fungairino** [comment]
not reproducible, doesn't seem like it is happening any more to the original reporter.

Let's keep an eye out for this happening again - maybe prioritizing a visual regression test for the snippet shortcut menu
