### ISSUE TITLE
Mod deployment not updating in background

### ISSUE THREAD

**Issue by twschiller** [pixiebrix/pixiebrix-extension#8485]
## Describe the bug

- Reported by a couple customers recently
- Customer 1: 1.8.13: https://pixiebrix.slack.com/archives/C0436P48QHY/p1716229239496419
  - User is an manager, did not click snooze (verified using Mixpanel), does not appear to have manually activated it (verified using Mixpanel)
  - User had a recent device heartbeat (which reported the old mod version)
  - No relevant datadog logs for user/errors for user
  - I've been unable to reproduce the issue on my machine
- Customer 2: Extension Version Unknown: https://pixiebrix.slack.com/archives/C0436P48QHY/p1715884426657399

## To Reproduce

1. See Slack for mod ids

**Comment by twschiller** [comment]
This might be related to team role (e.g., under what conditions updater runs in background for admin/manager/developer). See https://app.pixiebrix.com/teams/bbb49a1f-ec7b-4099-a4a3-eade03cdfe86/deployments/7622749e-ea89-45da-a491-ba9e880ea471?tabKey=users for example

**Comment by grahamlangford** [comment]
> This might be related to team role (e.g., under what conditions updater runs in background for admin/manager/developer). See https://app.pixiebrix.com/teams/bbb49a1f-ec7b-4099-a4a3-eade03cdfe86/deployments/7622749e-ea89-45da-a491-ba9e880ea471?tabKey=users for example

Digging into four users that should have received the deployment -- 2 were restricted, 2 were managers

**Comment by grahamlangford** [comment]
Not seeing any errors for them in Datadog either. Analysis here: https://www.notion.so/pixiebrix/Mod-Deployment-not-happening-in-background-8485-853af3b9ae6f4cef991abde4fd2dc77b
