### ISSUE TITLE
No active sidepanel for tabId error on SFDC

### ISSUE THREAD

**Issue by twschiller** [pixiebrix/pixiebrix-extension#8486]
## Describe the bug

- No active sidepanel for tabId message
- https://pixiebrix.slack.com/archives/C0436P48QHY/p1716250103035139

## To Reproduce

- @mthek10 can you provide information in the Slack thread

**Comment by grahamlangford** [comment]
Possibly fixed by https://github.com/pixiebrix/pixiebrix-extension/pull/8452

**Comment by twschiller** [comment]
Closing because we haven't seen this reported again
