### ISSUE TITLE
Add a close sidebar button to the PixieBrix sidebar/drawer

### ISSUE THREAD

**Issue by twschiller** [pixiebrix/pixiebrix-extension#849]
**Context**
- To open the sidebar, a user can click the PixieBrix browser action icon from any page. Additionally, bricks can automatically open the sidebar
- However, to close the sidebar, a user must either: 1) refresh the page, or 2) click the browser action icon again. The latter is hidden if PixieBrix is not pinned to the toolbar

**Relevant Code**
- Panel toolbar: http://github.com/pixiebrix/pixiebrix-extension/blob/7e896452035f181a5065b4acbeb99a928c3a9fef/src/actionPanel/ActionPanelApp.tsx#L100-L100
- Send a HIDE_ACTION_FRAME message onclick: http://github.com/pixiebrix/pixiebrix-extension/blob/7e896452035f181a5065b4acbeb99a928c3a9fef/src/blocks/effects/sidebar.ts#L65-L65

**Comment by fregante** [comment]
I think a tiny right-aligned × button would be good and unobtrusive.

**Comment by twschiller** [comment]
I've seen a double chevron used in some other tools which I like as the sidebar is a sidebar not a modal. For example, in Notion

![image](https://user-images.githubusercontent.com/1879821/126193269-e33addc1-572f-4e00-b1c6-a42e7437cdcd.png)

**Comment by mnholtz** [comment]
FYI, the free version of font awesome [doesn't include a double chevron](https://fontawesome.com/v5.15/icons?d=gallery&p=2&q=chevron). Using a single chevron two times looks ok. But it's redundant.
<img width="168" alt="Screen Shot 2021-07-21 at 3 52 39 PM" src="https://user-images.githubusercontent.com/36575242/126569892-ecf8746d-3375-4798-928d-9cbdcb4665b1.png">

**Comment by twschiller** [comment]
Good to know - we can alternatively us the bootstrap library, as it's already included: https://icons.getbootstrap.com/icons/chevron-double-right/

We might want to include it directly though (e.g., copy the SVG code), as the bootstrap icons library is excluded in "slim" build we're trying to support to speed up development builds (see https://github.com/pixiebrix/pixiebrix-extension/pull/885)

**Comment by fregante** [comment]
> We might want to include it directly though (e.g., copy the SVG code

We can import the single icon instead of relying on `svgIcons.ts`, something like this:

```ts
import chevronDoubleRight from "bootstrap-icons/icons/chevron-double-right.svg"
```
