### ISSUE TITLE
Enable filename eslint plugin rules

### ISSUE THREAD

**Issue by twschiller** [pixiebrix/pixiebrix-extension#850]
https://github.com/selaux/eslint-plugin-filenames

- Support either camel or pascal case (we use for React components). Disallow kebab case

**Other Considerations**
- The Codacy eslint checker should already have this plugin available
- The plugin might no longer be maintained? Is it compatible?

**Comment by fregante** [comment]
We already have a rule locally, but it’s not enabled https://github.com/sindresorhus/eslint-plugin-unicorn/issues/262

**Comment by twschiller** [comment]
`eslint-plugin-filenames` has some additional helpful rules, e.g., ensuring that the name of the variable being exported is the same as the name of the filename

I'm open to either, especially as selaux/eslint-plugin-filenames is likely stable but not well maintained

**Comment by fregante** [comment]
Let’s use
- `unicorn/filename-case` rule since it will be included in the unicorn preset anyway
- `filenames/match-exported` until it’s implemented in our other existing plugin https://togithub.com/benmosher/eslint-plugin-import/pull/1476
