### ISSUE TITLE
Add support for target="_blank" in markdown renderer

### ISSUE THREAD

**Issue by twschiller** [pixiebrix/pixiebrix-extension#851]
**Context**
- Links rendered with `@pixiebrix/markdown` in the sidepanel will open in the sidepanel. This doesn't work for pages that don't allow iframing (e.g., Google Maps)
- DOMPurify removes the target attribute. We can add it as long as we also automatically add the safety `rel` attributes (noopener, noreferrer)

**References**
- https://github.com/cure53/DOMPurify/issues/317

**Comment by fregante** [comment]
Since the brick itself doesn't know where its output will be rendered, I think this is the renderer’s responsibility, or even the context’s. For example, I'd add something like this to `action.tsx`:

```js
// https://www.npmjs.com/package/filter-altered-clicks
$('a').click(filterAlteredClicks(event => {
    event.preventDefault();
	window.open(event.currentTarget.href)
}));
