### ISSUE TITLE
[Spike] Research Playwright gaps in the Page Editor

### ISSUE THREAD

**Issue by grahamlangford** [pixiebrix/pixiebrix-extension#8551]
## Motivation

We're going to be focusing on the Page Editor in the near future -- refactoring and updating the UX. We want to have a robust series of Playwright tests to help provide confidence during that work

## Acceptance Criteria

- [ ] Identify gaps in Playwright coverage
- [ ] Determine which gaps we should prioritize
- [ ] Create issues to write tests for those gaps
- [ ] Add issues to the `Page Editor Playwright Tests` epic

## Notes

- The Form Builder is unlikely to change anytime soon, so test for it can be deprioritized in favor or creating/editing mods

**Comment by grahamlangford** [comment]
We need to be sure to test that the invariant checks are working correctly. That includes deleting excess starterBrick definitions. (See this PR for additional context: https://github.com/pixiebrix/pixiebrix-extension/pull/8557). 

We'll likely want to create a testing mod that has multiple excess starter brick definitions by editing a mod in the workshop. Then copy that mod in the Page Editor during the test, modify it in different ways, and then save it.

* Add a new mod component
* Delete a mod component
* Move a mod component out of the mod (this is actually functionally different from deleting)
* Edit the Mod metadata
* Edit 1 or more mod components

**Comment by fungairino** [comment]
Spike doc:
https://www.notion.so/pixiebrix/Page-Editor-e2e-Coverage-1796202b57a04aa9b16d14fd19c3ebcc?pvs=4

Created tasks in the epic:
https://github.com/pixiebrix/pixiebrix-extension/issues/8599#workspaces/648b6be80bad0700122cb282/epics/Z2lkOi8vcmFwdG9yL1plbmh1YkVwaWMvMTk1MzU3?state=OPEN&state=TODO&state=IN_PROGRESS
