### ISSUE TITLE
Data error saving mod

### ISSUE THREAD

**Issue by twschiller** [pixiebrix/pixiebrix-extension#8553]
## Describe the bug

- https://pixiebrix.slack.com/archives/C0436P48QHY/p1717553792057509

## To Reproduce

See Slack thread for diagnostics export

1. Activate: `@pixies/ai/chatgpt-sidebar`
2. Make a change
3. Try to click to save

## Actual behavior

Page Editor shows data error

## Expected behavior

Mod is saved

## Desktop (please complete the following information):

- Extension Version: v2.0.2-beta.1

**Comment by grahamlangford** [comment]
Likely related to https://github.com/pixiebrix/pixiebrix-extension/pull/8533

**Comment by twschiller** [comment]
> Caused by https://github.com/pixiebrix/pixiebrix-extension/pull/8533. Confirmed that reverting resolves the issue

I'd prefer to spend some time looking into the root cause vs. reverting

**Comment by grahamlangford** [comment]
> I recommend we spend some time looking into the root cause vs. reverting

Agreed, I just validated the assumption that it was that PR that caused it and not something else

**Comment by grahamlangford** [comment]
Removing `deleteUnusedStarterBrickDefinitions` from buildNewMod is allowing me to copy the mod successfully

**Comment by grahamlangford** [comment]
The problem appears to be that we're deleting the unused mod components to create the unsaved mod definition (in buildNewMod), but we never delete them from the source mod. We then check the two against each other, which leads to the discrepancy.
