### ISSUE TITLE
[Spike] Page Editor: always package standalone mods on save

### ISSUE THREAD

**Issue by grahamlangford** [pixiebrix/pixiebrix-extension#8565]
## Context

- Tech Spec: https://notion.so/pixiebrix/Page-Editor-always-package-standalone-mods-on-save-e9d8189618944e4e9ee1edc292fd1796
- https://www.notion.so/pixiebrix/Rearchitecting-Local-Representation-of-Activated-Mods-79012dd573ab47adaea959618e7b27e7?pvs=4#9a0b6206502047789ff2d71efbfd8bc6

## Acceptance Criteria

- [x] Slices specified
- [x] Approval Matrix signed off
- [x] Slices converted to issues
- [x] Issues added to `Page Editor: always package standalone mods on save` epic
- [x] Tech Lead notified for prioritization

## Related Code

- https://github.com/pixiebrix/pixiebrix-extension/blob/c4cff146c23d3076f25d1d1567f8814f60fe5bc1/src/extensionConsole/pages/mods/modals/convertToRecipeModal/ConvertToRecipeModalBody.tsx#L157-L157

**Comment by twschiller** [comment]
@BLoe let's keep an eye on the scope of this issue and split into multiple spikes as necessary

**Comment by twschiller** [comment]
@BLoe this work will be part of the following work: https://www.notion.so/pixiebrix/Eliminate-standalone-mods-from-Page-Editor-to-simplify-editor-state-91d4afb2af714faaafa78e20aa6298ff?pvs=4

**Comment by BLoe** [comment]
Epic here with sliced issues: https://github.com/pixiebrix/pixiebrix-extension#workspaces/feature-board-648b6be80bad0700122cb282/epics/Z2lkOi8vcmFwdG9yL1plbmh1YkVwaWMvMTg5MTI5
