### ISSUE TITLE
Fixture for creating test mods via their definition yaml

### ISSUE THREAD

**Issue by fungairino** [pixiebrix/pixiebrix-extension#8580]
- Fixture that returns a method for creating a mod using the workshop page from a yaml definition, based on file name pattern.

**Comment by twschiller** [comment]
@fungairino is the point of this ticket to provide a way to get the Page Editor into a certain initial state? Do you have an example test that would exercise this as part of definition of done?

**Comment by fungairino** [comment]
Correct. This way we can for example create a mod with multiple extension points for the invariance assertions tests. 

We could also create the mod in the e2e team group and clone it, but this way we have a method for creating mods on the fly   and modify them right away if we don't necessarily need to save them in that team scope.

**Comment by fungairino** [comment]
This way we also start adding coverage for the workshop new mod create flow as well.
