### ISSUE TITLE
Invariant check - Eliminate excess starter bricks

### ISSUE THREAD

**Issue by fungairino** [pixiebrix/pixiebrix-extension#8592]
- Start with a testing mod that has multiple excess starter brick definitions.
- Copy the mod, modify it and save it.
- Verify yaml structure does not have duplicates.

We need to be sure to test that the invariant checks are working correctly. That includes deleting excess starterBrick definitions. (See this PR for additional context: https://github.com/pixiebrix/pixiebrix-extension/pull/8557).

**Comment by twschiller** [comment]
I recommend we don't spend time implementing a Playwright test on this. Time better spent fixing the root cause

**Comment by fungairino** [comment]
@grahamlangford can you provide a mod with duplicate extension points for this test?

**Comment by grahamlangford** [comment]
> I recommend we don't spend time implementing a Playwright test on this. Time better spent fixing the root cause

I agree on fixing the root cause, but the implementation for this is straightforward and can be used to confirm that the fix for the root cause is also working as expected (we remove the deletions from the invariant check and the test should still pass without any changes)
