### ISSUE TITLE
Document/Form Builder UX tests

### ISSUE THREAD

**Issue by fungairino** [pixiebrix/pixiebrix-extension#8599]
- **Element Navigation in Preview Panel**
    - Clicking on different elements in the Preview panel navigates to different bricks in the panel.
- **Outline Tab Verification**
    - “Outline” data panel tab shows expected structure.
- **Sidebar Starter Brick Configuration**
    - Custom forms within sidebar starter brick can be configured.
        - Data binding defaults to “Mod” namespace.

**Comment by mnholtz** [comment]
This will be lower priority from what I understand; we won't be making many changes to the document/form builder during our refactoring project
