### ISSUE TITLE
Move/reorganize root-level `src/pageEditor` components

### ISSUE THREAD

**Issue by mnholtz** [pixiebrix/pixiebrix-extension#8606]
Part of our spec for rename refactoring the Page Editor, see here https://www.notion.so/pixiebrix/Project-Page-Editor-Renaming-90fa2f5deca448a4927bc9d019b018b0?pvs=4#2ed303d45ffa44c190b9beb7c72d635f

The `src/pageEditor` directory has a handful of root-level components that need a home. Let's move them into an appropriate subdirectory, with the goal of making it easier to navigate the directory structure.

**Comment by twschiller** [comment]
@mnholtz I think this it the correct notion reference: https://www.notion.so/pixiebrix/Project-Page-Editor-Renaming-90fa2f5deca448a4927bc9d019b018b0?pvs=4#2ed303d45ffa44c190b9beb7c72d635f
