### ISSUE TITLE
Rename element -> documentPreviewComponent

### ISSUE THREAD

**Issue by mnholtz** [pixiebrix/pixiebrix-extension#8609]
**Context/motivation**
Part of our efforts to rename usages of the term `element` in the Page Editor. 

In this particular case, we'd like to rename usages of the term `element` in the context of referring to a document preview element. See https://www.notion.so/pixiebrix/Project-Page-Editor-Renaming-90fa2f5deca448a4927bc9d019b018b0?pvs=4#226686e344ba45a68a7f016d03384b13 for a list of other contexts where we use the term `element`.

**Definition of done**
- Rename all types, variables, and comments that use `element` -> `documentPreviewComponent`
- Add any new terms to the glossary https://www.notion.so/pixiebrix/Glossary-82ccc0b8932c466380a20c382d498656

**Comment by grahamlangford** [comment]
@mnholtz I think we won't need this issue after https://github.com/pixiebrix/pixiebrix-extension/pull/8702 is merged

**Comment by mnholtz** [comment]
@grahamlangford I might want to take inventory of the singleton `elements` that are floating around to refer to documentPreviewElements, but would probably agree with you

**Comment by mnholtz** [comment]
@grahamlangford going to use this ticket to address issues with the term "DocumentOrFormPreviewElement" that I introduced, see https://github.com/pixiebrix/pixiebrix-extension/pull/8706#discussion_r1655677777

It sounds like `PreviewElement` or `BuilderElement` is preferred
