### ISSUE TITLE
Generate AST for variable path parsing/generation to handle property access edge cases in variable popover

### ISSUE THREAD

**Issue by twschiller** [pixiebrix/pixiebrix-extension#8638]
Context
---
- https://github.com/pixiebrix/pixiebrix-extension/pull/8637
- The current implementation has a corner case for bracketed expressions that end in ?, e.g., `["hello world?"]`
- The check `/[ .]/` for which accessors need brackets also needs to be fixed. Characters such as `-`, etc., would also necessitate brackets
- Ideally would use a JS parser, but `@` is not a valid first character in identifiers

**Comment by fungairino** [comment]
For reference:
https://github.com/pixiebrix/pixiebrix-extension/pull/8637/files#diff-e02574e2697ce0dc8b2fb077f7eb38285c3a7181250ea290e41e42cd23437e71R328-R329

**Comment by twschiller** [comment]
Closing as not planned
