### ISSUE TITLE
[Spike] Page Editor: affordance to add component directly to existing mod

### ISSUE THREAD

**Issue by grahamlangford** [pixiebrix/pixiebrix-extension#8684]
## Phase Spec

- https://www.notion.so/pixiebrix/Page-Editor-affordance-to-add-component-directly-to-existing-mod-5c0b6acfd1774683a40ce89d331aea17

## Acceptance Criteria

- [ ] Slices specified
- [ ] Approval Matrix signed off
- [ ] Slices converted to issues
- [ ] Issues added to `Page Editor: affordance to add component directly to existing mod` epic
- [ ] Tech Lead notified for prioritization

**Comment by twschiller** [comment]
@grahamlangford @BLoe this was closed 2 days ago? I don't think this is sliced yet: https://www.notion.so/pixiebrix/Page-Editor-affordance-to-add-component-directly-to-existing-mod-5c0b6acfd1774683a40ce89d331aea17?pvs=4

**Comment by grahamlangford** [comment]
> @grahamlangford @BLoe this was closed 2 days ago? I don't think this is sliced yet: https://www.notion.so/pixiebrix/Page-Editor-affordance-to-add-component-directly-to-existing-mod-5c0b6acfd1774683a40ce89d331aea17?pvs=4
> 
> I'm moving back to backlog

Looks like I closed the wrong ticket. Good catch
