### ISSUE TITLE
Font family not showing in custom theme

### ISSUE THREAD

**Issue by twschiller** [pixiebrix/pixiebrix-extension#871]
Related: 
- https://github.com/pixiebrix/pixiebrix-extension/pull/861
- https://github.com/pixiebrix/pixiebrix-extension/pull/857

**Comment by twschiller** [comment]
Caused by the bump from 2.0.0 to 2.1.0

**Comment by fregante** [comment]
Can you attach a screenshot? I don't exactly know what this refers to
