### ISSUE TITLE
Rename remaining instances of "recipe" in the Page Editor

### ISSUE THREAD

**Issue by mnholtz** [pixiebrix/pixiebrix-extension#8710]
We have several places where we still use the legacy term "recipe" in the Page Editor in place of "mod". As part of low-hanging fruit for the Page Editor refactoring project, replace straggling instances of "recipe".

See https://www.notion.so/pixiebrix/Project-Page-Editor-Renaming-90fa2f5deca448a4927bc9d019b018b0

**Comment by grahamlangford** [comment]
@mnholtz This is a duplicate of https://github.com/pixiebrix/pixiebrix-extension/issues/8614? Did you mean something else?

**Comment by mnholtz** [comment]
@grahamlangford hmmm, I opened this yesterday because I couldn't find that other ticket.
