### ISSUE TITLE
Deactivated Sidepanel deployments not removed from Mod Launcher

### ISSUE THREAD

**Issue by grahamlangford** [pixiebrix/pixiebrix-extension#8744]
## Describe the bug

When a side panel mod that has been deployed to a user is removed, the mod still shows up in the Mod Launcher even after refreshing the page so long as the sidebar is not closed

## To Reproduce

1. Create a deployment that uses a side panel mod (the mod cannot not already be activated for the user)
2. Refresh the Extension Console (do *not* toggle the Extension in the Manage Extensions screen)
3. In a separate tab, open the sidebar to the Mod Launcher and confirm the mod has been deployed
4. In the Admin Console, disable the deployment and remove the group
5. Trigger the deployments to run (same as step 2)
6. Return to the tab with the sidebar open

## Actual behavior

* The mod is still seen in the Mod Launcher
* Refreshing the page does not remove the mod from the Mod Launcher

## Expected behavior

* The sidebar mod is no longer seen in the Mod Launcher

## Screenshots/Loom

https://www.loom.com/share/65f42284694d442f9f255b10e170ea40

## Desktop (please complete the following information):

- OS: OSX
- Browser: Chrome
- Extension Version: 2.0.4-beta.2

## Additional context

- What mod(s) were you running?
    - `Regression Test: Team API PaLM` deployment under "The Pixies"

**Comment by fungairino** [comment]
I'm also observing that when initially activating the deployment, if I'm on the tab with the sidepanel open already, the sidebar is not updated with the new panel to show

**Comment by fungairino** [comment]
I fixed the issue by reloading the mods after activation, but now I'm consistently running into the bug described here:
https://github.com/pixiebrix/pixiebrix-extension/issues/8158

I suspect that this extra added delay just tipped it over to make this behavior consistent. I'll look into fixing the above mentioned bug as well as part of this.
