### ISSUE TITLE
RFC: speed up incremental build during development

### ISSUE THREAD

**Issue by twschiller** [pixiebrix/pixiebrix-extension#881]
Even with incremental builds, depending on what part of the code you're touching updates can take 3-30s to build (also depending on other system load)

I wanted to capture ideas for speeding up the development build:
- Fix the module coupling issue cause by the "lift" methods. (See #578)
- Add build(s) flag which excludes certain dependencies that may not be needed depending on what you're developing (e.g., icon packages, nunjucks, uipath sdk, etc.). This might be implemented by resolving them to false, or swapping in a mock depending on the environment variables

**Comment by fregante** [comment]
Agreed. Definitely avoiding unnecessary dependencies in every bundle should speed up compilation and make it faster and lighter for the users too. 

Sometimes I just exclude entry points when I just want to try something, but I don’t think it's safe to do that (it might lead to further head-scratching during development)

It's really strange that webpack is taking so long to do incremental compilation after a single file update. I can definitely look for what's causing this. It's possible that some configuration is breaking the internal caching/memoization and causing webpack to do a full compilation occasionally. 

Possible ways to go about it:

- start webpack config from scratch and see at what point it starts to slow down
- exclude type checking (and run tsc separately) or use fork-ts-plugin
- look for more configuration that might speed it up
- use some performance debugging tool to see what's taking so long exactly (this might not always be accurate as far as I know)

**Comment by fregante** [comment]
We could also potentially consider other bundlers but I'm afraid none of them support code-splitting the same way. I think Parcel does but it's honestly a pain to upgrade every time because they change the behavior so often (not that webpack here is perfect, as we've seen with some loaders)

**Comment by twschiller** [comment]
> It's really strange that webpack is taking so long to do incremental compilation after a single file update

I think it depends on which entry points the file ends up touching. E.g., working on dev tools front-end code seems to reload quickly. Also, how much RAM my computer happens to have free also makes a big difference

> We could also consider other bundlers

Let's stick with Webpack, as we've got bigger fish to fry, e.g., the messaging infrastructure. Those will have benefits for end-user experience as well

Definitely also worth a peek at Webpacks performance/debugging output to see where it's spending the most time
