### ISSUE TITLE
Incorrect partner auth flow from sidebar

### ISSUE THREAD

**Issue by twschiller** [pixiebrix/pixiebrix-extension#8815]
## Describe the bug

"Connect" action in sidebar in partner mode sends user to the admin console instead of the extension console partner login page

## To Reproduce

1. Set Extension Console > Advanced Settings > Partner to `automation-anywhere` (to reproduce, you might also need to set the authentication mode to `partner-oauth2`)
2. Open the sidebar in a new tab
3. Click "Connect"

## Actual behavior

User is taken to the Admin Console

## Expected behavior

Open an Extension Console page so the user is shown the partner login screen

## Discussion

- Could be pretty straightforward to add a Playwright test for this bug/regression?

**Comment by mnholtz** [comment]
I'm unable to replicate. Any tips @twschiller ? 

See my PR here for a test that demonstrates the expected behavior: https://github.com/pixiebrix/pixiebrix-extension/pull/8862

**Comment by twschiller** [comment]
> I'm unable to replicate. Any tips @twschiller ?

I'll send an intro email to our counterpart to so you can coordinate on if the bad behavior is still happening

**Comment by mnholtz** [comment]
@twschiller FYI I actually suspect it may be an MS Edge/MV3 sidebar thing. I noticed that the e2e test I wrote is failing in edge (which I didn't notice initially due to the way I was running tests locally). Will continue tomorrow

**Comment by mnholtz** [comment]
@twschiller I ruled-out the hypothesis that it was an issue with MS Edge. See this comment here about the sidebar behavior in edge: https://github.com/pixiebrix/pixiebrix-extension/pull/8862/files

Still can't replicate this in chrome or edge
