### ISSUE TITLE
Page Editor error editing button in document builder

### ISSUE THREAD

**Issue by twschiller** [pixiebrix/pixiebrix-extension#8848]
Context
---
- https://pixiebrix.slack.com/archives/C0436P48QHY/p1721069462336779
- Mod: `@pixies/starter/chatgpt-sidebar` (ChatGPT sidebar mod)

Related Code
---
- https://github.com/pixiebrix/pixiebrix-extension/blob/1a1cf7c3e55ddfbc45112d36c4941eb3588766a6/src/pageEditor/fields/ConfigErrorBoundary.tsx#L32-L32

**Comment by mnholtz** [comment]
Closing due to being unable to replicate, see updated slack thread
