### ISSUE TITLE
Slice 1: Add a new parameter to useAddNewModComponent - modMetadata

### ISSUE THREAD

**Issue by grahamlangford** [pixiebrix/pixiebrix-extension#8865]
https://www.notion.so/pixiebrix/Page-Editor-affordance-to-add-component-directly-to-existing-mod-5c0b6acfd1774683a40ce89d331aea17?pvs=4#aa4340f6bf1349bb816e5dc4563139c6

**Comment by mnholtz** [comment]
Closing in favor of combining with https://github.com/pixiebrix/pixiebrix-extension/issues/8869
