### ISSUE TITLE
Slice 2: Add redux editor slice property to track which mod is currently having a starter brick added

### ISSUE THREAD

**Issue by grahamlangford** [pixiebrix/pixiebrix-extension#8866]
https://www.notion.so/pixiebrix/Page-Editor-affordance-to-add-component-directly-to-existing-mod-5c0b6acfd1774683a40ce89d331aea17?pvs=4#6595dd4c12b54996b810fc5587de2319

**Comment by mnholtz** [comment]
This slice is now irrelevant after https://github.com/pixiebrix/pixiebrix-extension/pull/8886, see updated notion document
