### ISSUE TITLE
Slice 3: Modify useAutoInsert to read the new redux property and assign the mod metadata to new mod components created there

### ISSUE THREAD

**Issue by grahamlangford** [pixiebrix/pixiebrix-extension#8867]
https://www.notion.so/pixiebrix/Page-Editor-affordance-to-add-component-directly-to-existing-mod-5c0b6acfd1774683a40ce89d331aea17?pvs=4#6ea3a762d4c7456891a66530ae172133

**Comment by mnholtz** [comment]
This slice is now irrelevant after https://github.com/pixiebrix/pixiebrix-extension/pull/8886, see updates to notion document
