### ISSUE TITLE
Handle retired `v1/authentication/token` endpoint in `checkConfigAuth`

### ISSUE THREAD

**Issue by twschiller** [pixiebrix/pixiebrix-extension#8871]
## Describe the bug

- Handle retired `v1/authentication/token` endpoint in `checkConfigAuth`
- AA v.33 retired the `v1/authentication` endpoints
- There are still customers on v.32 and before
- There's now way to detect what version the Control Room is on

## Discussion

- Probably need to try the new v2 endpoint and fallback to v1

**Comment by twschiller** [comment]
Upon further investigation of the Swagger, it looks like `v1/authentication/token` is still valid in v.33. @johnnymetz is confirming with AA PM

**Comment by johnnymetz** [comment]
No Extension changes necessary.

There only change is that the `token` query param is now deprecated but the Extension doesn't use this param, see [slack](https://pixiebrix.slack.com/archives/C07CWT4Q2V9/p1721254117440619)
