### ISSUE TITLE
Bugfix: workaround to inject content script on iframes with `srcdoc` and `sandbox` attributes

### ISSUE THREAD

**Issue by mnholtz** [pixiebrix/pixiebrix-extension#8921]
A bug was introduced in chromium and included in the latest version of Chrome 127 that prevents the content script from loading in iframes with both the `srcdoc` and `sandbox` attributes set, e.g. `<iframe srcdoc="..." sandbox/>`. See slack channel [#bugfix-sandbox-iframes-chrome-update](https://pixiebrix.slack.com/archives/C07DQ2J7C78) for more details.

The proposed workaround is programmatically removing the sandbox attribute and reloading the iframe to trigger content script injection. This [strategy was discussed in the past](https://github.com/pixiebrix/pixiebrix-extension/issues/7300#issuecomment-1882418119) regarding issues with sandboxed iframes, but a different approach was taken at the time.

**Implementation sketch**
- Add some logic to content script initialization that will iterate over all iframes on the page
- Remove the sandbox attr, if present, and reload the frame

**Comment by fungairino** [comment]
Referencing the proposed fix here:
https://issues.chromium.org/issues/355256366#comment4

I tried it out but it doesn't seem to work for us. Although it does seem to work in the minimum reproducible example shared in that same ticket.

**Comment by mnholtz** [comment]
Closing in favor of https://github.com/pixiebrix/pixiebrix-extension/issues/8927
