### ISSUE TITLE
Page Editor shows "unable to edit configuration" message

### ISSUE THREAD

**Issue by twschiller** [pixiebrix/pixiebrix-extension#8928]
Context
---
- https://pixiebrix.slack.com/archives/C0436P48QHY/p1721851646639019
- > maybe something with mod variable popover since it seems to only happen when writing mod variables

**Comment by mthek10** [comment]
Turn off mod variable popover seemed to fix things for me

**Comment by twschiller** [comment]
@mthek10 if you can share in the Slack mods that it happens for you on, that will help to fix quickly. This happens when there's an uncaught error in the Page Editor UI state

**Comment by grahamlangford** [comment]
Labeling `blocked` due to being unable to reproduce.
