### ISSUE TITLE
PLACEHOLDER: focus dialog always required in Chrome 127 and click doesn't open sidebar

### ISSUE THREAD

**Issue by twschiller** [pixiebrix/pixiebrix-extension#8933]
Context
--- 
- Slack channel: https://pixiebrix.slack.com/archives/C07DGPVQJKH
- Chrome issue: https://issues.chromium.org/issues/355266358
- Google Group discussion: https://groups.google.com/a/chromium.org/g/chromium-extensions/c/WRGFOAHxoaY

**Comment by grahamlangford** [comment]
Update: Chrome Canary has a fix. I've installed and tested and confirmed it solves our user gesture issues. 

The Chromium team says they will attempt to backport the fix to Chrome 128, but it is unlikely to be applied to Chrome 127

**Comment by twschiller** [comment]
@grahamlangford can we close out given that 128 is coming out this week?

**Comment by grahamlangford** [comment]
Chromium team has resolved this issue in Chrome 128
