### ISSUE TITLE
Sidebar panel stuck in loading state when undefined error is thrown

### ISSUE THREAD

**Issue by grahamlangford** [pixiebrix/pixiebrix-extension#8954]
## Describe the bug

- See full context here: https://pixiebrix.slack.com/archives/C0436P48QHY/p1722351717659199. 

- It appears that the `heading` passed to `mustache.render` is `undefined`. See https://github.com/pixiebrix/pixiebrix-extension/blob/main/src/starterBricks/sidebar/sidebarStarterBrick.ts#L185-L186. 

- Manually passing `undefined` replicates the issue

**Comment by fungairino** [comment]
Datadog query for this user:

https://app.datadoghq.com/logs?query=%40usr.id%3Acf6e5871-c8f3-4d27-bfb2-73f08eb95b89%20&agg_m=count&agg_m_source=base&agg_t=count&cols=host%2Cservice&fromUser=true&messageDisplay=inline&refresh_mode=sliding&storage=hot&stream_sort=desc&viz=stream&from_ts=1722179858308&to_ts=1722352658308&live=true

```
TypeError: Invalid template! Template should be a "string" but "undefined" was given as the first argument for mustache#render(template, view, partials)
  at w.render @ https://pixiebrix-extension-source-maps.s3.amazonaws.com/sourcemaps/build/1aa8ce4e1107b349c4b7fc6610644f6ee490aee2/mv3/bundles/63619.bundle.js:2:633671
  at R.runModComponent @ https://pixiebrix-extension-source-maps.s3.amazonaws.com/sourcemaps/build/1aa8ce4e1107b349c4b7fc6610644f6ee490aee2/mv3/bundles/contentScriptCore.bundle.js:2:334967
  at async R.refreshComponentPanel @ https://pixiebrix-extension-source-maps.s3.amazonaws.com/sourcemaps/build/1aa8ce4e1107b349c4b7fc6610644f6ee490aee2/mv3/bundles/contentScriptCore.bundle.js:2:335665
  at async R.debouncedRefreshPanels @ https://pixiebrix-extension-source-maps.s3.amazonaws.com/sourcemaps/build/1aa8ce4e1107b349c4b7fc6610644f6ee490aee2/mv3/bundles/contentScriptCore.bundle.js:2:335846

```

**Comment by fungairino** [comment]
Seems like there is no validation for enforcing that tab title should be defined, which causes this issue.

**Comment by fungairino** [comment]
As part of this task I'm also looking to add a validation analysis visitor to warn the user if a required field is empty.
