### ISSUE TITLE
[Spike] extension behavior for Drop support for standalone mod components

### ISSUE THREAD

**Issue by twschiller** [pixiebrix/pixiebrix-extension#8974]
## Phase Spec

- https://www.notion.so/pixiebrix/Drop-support-for-standalone-mod-components-f7f3b59fc3474e45955a7b7d46baf333?pvs=4
- As discussed with @BLoe and @grahamlangford - code can just be dropped directly in a PR vs. sketching it all out first. Slicing/spec mainly to double-check migration considerations vs. the server changes

## Acceptance Criteria

- [x] Slices specified
- [ ] Approval Matrix signed off
- [ ] Slices converted to issues
- [ ] Issues added to _insert epic name_
- [ ] Tech Lead notified for prioritization

**Comment by BLoe** [comment]
Issues here:
Slice 1: #8979 
Slice 2: #8980
