### ISSUE TITLE
Show Sidebar Brick not showing active tab

### ISSUE THREAD

**Issue by grahamlangford** [pixiebrix/pixiebrix-extension#8976]
## Describe the bug

The correct sidebar panel is not always being displayed when calling the `Show Sidebar` brick in a mod.
The sidepanel is supposed to open:
  1) the panel that is specifically provided, or
  2) _any_ panel from the mod

## To Reproduce

1. Activate `@pixies/gptzero/detect-ai-writing-with-gptzero`
2. In the context menu mod component, in the show sidebar brick, disable `Force Panel`
3. On a page, highlight some text
4. Click the :robot_face: emoji in the text selection menu

## Actual behavior

The sidepanel opens (possibly requires a user gesture) to the Mod Launcher

## Expected behavior

The sidepanel opens to the `AI Detector Side Panel`

## Additional context

- https://pixiebrix.slack.com/archives/C0436P48QHY/p1722971574358689

**Comment by twschiller** [comment]
@grahamlangford see specification table here of the combinations: https://www.notion.so/pixiebrix/8976-show-sidebar-specification-54cb74ac3170407da2bdaa861fc62ea0?pvs=4

I think we want to change the default in the JSON Schema to true:  https://github.com/pixiebrix/pixiebrix-app/blob/b0ce456835c185bc86458273ed6170592c630d67/node_modules/@pixiebrix/extension/src/bricks/effects/sidebarEffects.ts#L53-L53

And also in the example brick configs: https://github.com/pixiebrix/pixiebrix-extension/blob/682a53e2c300def303ac2c4a4edaab7cc9e74ed4/src/bricks/exampleBrickConfigs.ts#L46-L46. For backward compatibility, we'd keep the default in the runtime as false
