### ISSUE TITLE
Drop support for standalone mod components - Slice 4 - Refactor `_recipe` mod component property

### ISSUE THREAD

**Issue by BLoe** [pixiebrix/pixiebrix-extension#9003]
See here: https://www.notion.so/pixiebrix/Drop-support-for-standalone-mod-components-f7f3b59fc3474e45955a7b7d46baf333#1e86868c7fad4c45b66620fc30150354

* Change the signature of the `ModComponentBase._recipe: ModMetadata | undefined` field to be `modMetadata: ModMetadata`
* Migrate the types in redux-persist (It's now decoupled from the api, so this is ok)
* Clean up all the call sites and collapse all code that is currently handling `_recipe == null` cases

Follows on from #8979 & #8980 & #9007

**Comment by twschiller** [comment]
Closing in favor of refactoring in next phase: https://pixiebrix.slack.com/archives/C02RAMRDF0R/p1724350221764719
