### ISSUE TITLE
Bug: addStarterBrick e2e tests flaky on sidebar ping

### ISSUE THREAD

**Issue by mnholtz** [pixiebrix/pixiebrix-extension#9011]
End to end tests for addStarterBrick are intermittently failing on the Pre-release browser workflow, for both `msedge-beta` and `msedge`: https://github.com/pixiebrix/pixiebrix-extension/actions/runs/10381677885/job/28771479311

Tests seem to be failing consistently with the error `The Sidebar is taking longer than expected to load. Retrying...` when waiting for the sidebar to open.

<img width="1345" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeWxiQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d4dd1515e70f4e417cd8e49eb9ffe87ce8dfb8eb/Screenshot%202024-08-14%20at%2012.09.49%E2%80%AFPM.png" alt="Screenshot 2024-08-14 at 12.09.49 PM.png" />

**Comment by grahamlangford** [comment]
I spent a day digging into this bug. This only appears to happen when running the e2e tests. When adding a sidepanel starterbrick using the Page Editor, the sidepanel should open automatically, but it doesn't. Nor does the gesture popover appear.

Findings:
* Cannot be replicated in MS Edge outside Playwright
    * Tested with the Page Editor open in another tab to as closely simulate the test as possible and still could not replicate
* Can be replicated in MS Edge launched by Playwright
* When running the e2e test, if I pause test execution as soon as the test had finished starting up, I can replicate in the Playwright-launched Edge browser (same Edge version as when not using Playwright)
* Tested with old versions of the Extension from before the flakiness appeared, but was still able to reproduce in Playwright
* Confirmed that the `chrome.sidePanel.open` method is being called

**Comment by fungairino** [comment]
This should be resolved now with https://github.com/pixiebrix/pixiebrix-extension/issues/9087 closed
