### ISSUE TITLE
Slice 2.1: Support displaying and activating user deployments in extension

### ISSUE THREAD

**Issue by johnnymetz** [pixiebrix/pixiebrix-extension#9031]
Part of Slice 2:
Extension Changes for sync mod activation across browser profiles without local integrations

## Context

https://www.notion.so/pixiebrix/Sync-mod-activation-across-browser-profiles-without-local-integrations-a4d7ee78491d4d7e8d5f1d996b113e11?pvs=4#dd02be54a0f744b9be55021c358b7a5d

## AC

Ensure a user deployment can be properly activated on a fresh install
Indicate on the mod table/grid component if a mod came from a user deployment
Update type definitions so mods can tell if they came from a user or team deployment

**Comment by fungairino** [comment]
I'm splitting this issue into three slices:
1. Supporting fetching, activating and displaying user deployments for a mod in extension console
2. Supporting creating a user deployment in extension console
3. Supporting deleting a user deployment in extension console
