### ISSUE TITLE
Deployment key doesn't take effect if team has an associated AA Control Room

### ISSUE THREAD

**Issue by twschiller** [pixiebrix/pixiebrix-extension#9089]
## Describe the bug

- Deployment key doesn't take effect if team has an associated AA Control Room
- https://pixiebrix.slack.com/archives/C0436P48QHY/p1725478881903879

## To Reproduce

1. Create a team with an associated AA control room
2. Create a deployment key for that team and assign the key to a deployment
1. Install the extension in a fresh browser profile
2. Provide a deployment key associated with a team with a configured AA control room: https://docs.pixiebrix.com/deploying-mods/deployment-keys#testing-the-deployment-key-in-the-browser-extension
3. Click to apply changes and then click the "Mods" screen

(Same behavior happens when setting the deploymentKey via managed storage)

## Actual behavior

- Extension Console shows the AA login form for username/password. Deployments are not activated

## Expected behavior

- The extension is authenticated as the deployment key. Extension receives the assigned deployments
- NOTE: should also be true if deployment key is provided via managed storage (i.e., extension policy): https://docs.pixiebrix.com/deploying-mods/deployment-keys#configuring-deployment-key-in-the-extension-configuration-policy
- Mod deployments work as expected

## Workaround

- Force the authentication method to be `pixiebrix-token` on the Extension Console settings screen

## Related Issues

- https://github.com/pixiebrix/pixiebrix-extension/issues/9069

**Comment by grahamlangford** [comment]
I don't think this is actually an issue anymore. I think it was fixed in https://github.com/pixiebrix/pixiebrix-extension/pull/9077

See loom: https://www.loom.com/share/3d169e647b6b4b068f4279227b924db7?sid=5caaec36-6c58-4362-b60b-07b9c2e5e897

**Comment by twschiller** [comment]
> See loom: https://www.loom.com/share/3d169e647b6b4b068f4279227b924db7?sid=5caaec36-6c58-4362-b60b-07b9c2e5e897

Thanks for the loom -- in the loom you're missing the part about the team being associated with an AA control room
