### ISSUE TITLE
Session Replay not available for welcome page

### ISSUE THREAD

**Issue by twschiller** [pixiebrix/pixiebrix-extension#9093]
Context
---
- https://www.notion.so/pixiebrix/Welcome-Page-Mod-Use-2024-09-05-4a1f011b9aaf4b0a897e623b97eeae9c?pvs=4
- We had introduced a flag https://app.pixiebrix.com/admin/waffle/flag/215/change/ to force recording of sidebar on welcome page so we can diagnose why users aren't making it to a mod panel
- It looks like we're capturing all the sessions, but replay videos aren't available

Discussion
---
- Is it a flag issue, e.g., the flag is not being detected by the extension?
- Or, is it a Datadog configuration issue? Did we misunderstand how the options work?
  - Do we need to pass `force` here: https://github.com/pixiebrix/pixiebrix-extension/blob/ad8d224ef08fd469bbe1254adb1fc983a9bec280/src/telemetry/performance.ts#L110-L110?

**Comment by fungairino** [comment]
How do we know that the sidebar sessions on the welcome page are not being recorded? I took a quick look at some sessions on Datadog and couldn't find any attribute that tells us what the connected tab url is. (We do record this for errors, but not for RUM it seems)

**Comment by twschiller** [comment]
@fungairino see links here: https://www.notion.so/pixiebrix/Welcome-Page-Mod-Use-2024-09-05-4a1f011b9aaf4b0a897e623b97eeae9c?pvs=4

You can find the sessions for each user, but there's no replay available for them. I can pair if you're still having trouble identifying what I mean

![image](https://github.com/user-attachments/assets/fd81b1b7-c764-4940-8945-7f4797dd45af)

**Comment by fungairino** [comment]
Yes, I saw those sessions you referenced but I wasn't sure how we were certain that these specific ones were on the welcome page - I think we don't know for sure they are. This might be something we should look into adding as well.

**Comment by twschiller** [comment]
> I think we don't know for sure they are.

You could cross-reference the timestamp with Mixpanel. Based on what I've seen in Mixpanel, I think they are most likely from the welcome page

**Comment by fungairino** [comment]
Initial testing shows to me that the session replay recording seemingly works fine.

I installed the prod extension on a fresh chrome profile and created a new account, navigated to the welcome page and recorded this session:
https://app.datadoghq.com/rum/sessions?query=%40usr.email%3Aeduardoaft%2Btest3%40gmail.com%20%40type%3Aview&agg_m=count&agg_m_source=base&agg_t=count&cols=&event=AgAAAZHD9xYAq6qH-gAAAAAAAAAYAAAAAEFaSEQ5eFlBQUFBQk00TC16ZDNqY2NWUgAAACQAAAAAMDE5MWMzZjctYjhhYi00YTNjLTg0YjctYWJjZmIyMDBmODA0&fromUser=false&track=rum&viz=stream&from_ts=1725568931204&to_ts=1725569831204&live=true

I'll try double checking those sessions you posted in mixpanel, but I'm not sure what issue there might be. One possibility could be that they might be using extensions that block tracking.

**Comment by fungairino** [comment]
Ah, I figured it out.

Datadog does not document this well, but when a rum session was already started for the user (say from the extension console page), initializing datadogRum again will not reuse the same session replay setting. Thus, if the initial session did not start a replay recording, any subsequent datadogRum.init calls will not start the session replay, even if the sessionReplaySampleRate is 100.

Thus as a work-around, we call startSessionReplayRecording with force: true to ensure that the session replay is started (as you had originally suggested in the issue, @twschiller ;) )

See: https://github.com/DataDog/browser-sdk/issues/1967
