### ISSUE TITLE
Slice 1 - Update the saving logic and reset option for unsaved mods and components

### ISSUE THREAD

**Issue by BLoe** [pixiebrix/pixiebrix-extension#9097]
[Spec slice here](https://www.notion.so/pixiebrix/Page-Editor-eliminate-standalone-mods-from-UI-4f118aebd2b8491cb4fdaa3db380970a?pvs=4#eaeed592fee54a398d1345a50bc2ac70)

- Engineering Considerations/Implementation Sketch
    - Re-wire the save-mod logic to check for the temporary `@inner/mod/*` mod id format, and show the “create mod from mod component” UX flow instead of saving automatically
        - see `getStandaloneModComponentRuntimeModId`
    - Remove save button from mod component list items
    - Rename the 3-dot-menu item from Reset to Clear Changes
        - Currently, when there are no unsaved changes in a component, this menu option is *hidden*, but we should change this to *disable* the option instead
- Test Plan: *any special considerations?*
    - For unit tests, we can mock an “unsaved” mod by assigning it an `@inner/mod/*` format id
    - Should be able to hack something together in the code to test this out locally in the page editor… 🤔

**Comment by grahamlangford** [comment]
Re-implementing following https://www.notion.so/pixiebrix/Re-Slicing-Eliminate-Standalone-mods-from-UI-694e4c85e61441809e14aec18f6b6109
