### ISSUE TITLE
Slice 2 - Update the Add button label and change behavior to create new mod with inner id

### ISSUE THREAD

**Issue by BLoe** [pixiebrix/pixiebrix-extension#9098]
[Slice spec here](https://www.notion.so/pixiebrix/Page-Editor-eliminate-standalone-mods-from-UI-4f118aebd2b8491cb4fdaa3db380970a?pvs=4#7168fa9bf1564809848855019bf233ce)

- Engineering Considerations/Implementation Sketch
    - Label —> `New Mod`
    - Rename component `AddStarterBrickButton` to `NewModButton`
    - `useAddNewModComponent` hook already takes a modMetadata as an optional input param
        - In the logic where it checks this input, when there is no metadata provided, instead of doing nothing (creating a stand alone component form state), create mod metadata using the above indicated values and assign it to the new component
            - Id: create this using the existing helper function `getStandaloneModComponentRuntimeModId`
            - Name: *same as mod component name*
            - Description: `Created with the PixieBrix Page Editor`
            - Version: `1.0.0`
            - Sharing:
                
                ```tsx
                {
                	public: false,
                	organizations: [] as UUID[],
                }
                ```
                
            - updated_at: use the `nowTimestamp()` helper function

**Comment by grahamlangford** [comment]
Re-implementing following https://www.notion.so/pixiebrix/Re-Slicing-Eliminate-Standalone-mods-from-UI-694e4c85e61441809e14aec18f6b6109
