### ISSUE TITLE
Slice 4 - Add the Duplicate action to the mod component dot-menu

### ISSUE THREAD

**Issue by BLoe** [pixiebrix/pixiebrix-extension#9100]
[Slice spec here](https://www.notion.so/pixiebrix/Page-Editor-eliminate-standalone-mods-from-UI-4f118aebd2b8491cb4fdaa3db380970a?pvs=4#e10802af5f70430aa47183d180bf154a)

- Engineering Considerations/Implementation Sketch
    - Add `onDuplicate` to `ActionMenu` props
        - Always enabled, never hidden
    - Use current `onClone` action in `DraftModComponentListItem`
    - Change `cloneActiveModComponent` thunk so it doesn’t remove the mod metadata from the clone
        - Double-check that fresh brick instance ids are generated

**Comment by grahamlangford** [comment]
Re-implementing following https://www.notion.so/pixiebrix/Re-Slicing-Eliminate-Standalone-mods-from-UI-694e4c85e61441809e14aec18f6b6109
