### ISSUE TITLE
Slice 5 - Convert “Move from mod” action to “Move to Mod” and adjust Copy action

### ISSUE THREAD

**Issue by BLoe** [pixiebrix/pixiebrix-extension#9101]
[Slice spec here](https://www.notion.so/pixiebrix/Page-Editor-eliminate-standalone-mods-from-UI-4f118aebd2b8491cb4fdaa3db380970a?pvs=4#186fe91a987340cc82e20efa817fa284)

- Engineering Considerations/Implementation Sketch
    - Delete the current move from mod modal
        - `onRemoveFromMod` prop in `ActionMenu`
        - `MoveFromModModal`
        - update `selectEditorModalVisibilities`
        - `removeModComponentFormStateFromMod` redux action/reducer
    - We can keep using the `keepLocalCopyOnCreateMod` field in redux
    - Recreate `MoveFromModModal`
        - Rename remaining pieces
            - `showRemoveFromModModal` → `showMoveFromModModal` redux action/reducer
            - `REMOVE_FROM_MOD` → `MOVE_FROM_MOD` modal key
        - Copy the `"modId"` field from `AddtoModModal`, and all the pieces required for it
        - select the `keepLocalCopyOnCreateMod` from redux
            - Change modal title and submit button copy based on the flag, see wireframe above
        - Add an input param to the `cloneActiveModComponent` thunk
            - `modMetadata?: ModMetadata`
            - cloned component has the mod (re-)assigned if passed in
                - cloned component should have `optionsArgs` overwritten by the destination mod’s options (options pulled from activated components of that mod)
        - Submit handler has similar logic as `AddToModalModal`
            - If new mod is selected, show the create mod modal
                - Change `showCreateModModal` action creator to make the `keepLocalCopy` payload optional, don’t update the flag if it’s not passed in (was already set here, but we still need to support the payload for other call sites)
                - CreateModModal should still basically work the same
            - if mod is selected, call the `cloneActiveModComponent` with new mod metadata param
    - Add new redux action `showMoveFromModModal`
        - `keepLocalCopy` payload param, set the redux flag `keepLocalCopyOnCreateMod`
    - Change `ActionMenu` props
        - `onClone` → `onCopy`
            - `dipatch(showMoveFromModModal({ keepLocalCopy: true })`
        - `onAddToMod` → `onMove`
            - `dipatch(showMoveFromModModal({ keepLocalCopy: false })`

**Comment by grahamlangford** [comment]
Re-implementing following https://www.notion.so/pixiebrix/Re-Slicing-Eliminate-Standalone-mods-from-UI-694e4c85e61441809e14aec18f6b6109
