### ISSUE TITLE
Slice 6 - Cleanup dead code related to some mod modals

### ISSUE THREAD

**Issue by BLoe** [pixiebrix/pixiebrix-extension#9102]
[Slice spec here](https://www.notion.so/pixiebrix/Page-Editor-eliminate-standalone-mods-from-UI-4f118aebd2b8491cb4fdaa3db380970a?pvs=4#4cd469f71c0149eca5100027c3cfdbd2)

- Engineering Considerations/Implementation Sketch
    - Delete
        - `AddToModModal`
        - `SaveAsNewModModal`
        - `ModalKey.*ADD_TO_MOD*`
        - `ModalKey.*SAVE_AS_NEW_MOD*`
        - `showAddToModModal`

**Comment by grahamlangford** [comment]
Re-implementing following https://www.notion.so/pixiebrix/Re-Slicing-Eliminate-Standalone-mods-from-UI-694e4c85e61441809e14aec18f6b6109
