### ISSUE TITLE
Mods screen shows "update" button for team deployments

### ISSUE THREAD

**Issue by twschiller** [pixiebrix/pixiebrix-extension#9103]
## Describe the bug

- Mods screen shows "update" button for deployments
- The intent of deployments is that users will use the pinned version
- The button is confusing because users naturally think they're supposed to click the button

## To Reproduce

1. Create a deployment of a mod and pin to an older version
2. Deploy the mod via deployment key (or normally to a restricted user)

## Actual behavior

The mods screen shows an "Update" button for the mod

## Expected behavior

- The mods screen shows an "Active" status with the pinned mod version for the mod

## Discussion

- For organizations that apply UI restrictions, the [RestrictedFeatures.DEACTIVATE_DEPLOYMENT](https://github.com/pixiebrix/pixiebrix-extension/blob/a0e8129cf370b17a2b2505ba772cd65e4e1242b0/src/auth/featureFlags.ts#L156-L156) would be the policy for whether or not the use is able to deactivate/re-activate a deployment
- However, to avoid confusion in the UI, for deployments, the mods screen SHOULD NOT show the Update button as the main status to any user. But users with permission to reactivate should still be able to re-activate/upgrade using the 3-dot menu to get the latest version
- Note that the Update button should show for personal deployments: https://github.com/pixiebrix/pixiebrix-extension/issues/9091

## Future Work

- Indicate to developers/managers/admins when a mod deployment isn't the latest version (and see which version is activated vs. the latest)

## Related Code

- https://github.com/pixiebrix/pixiebrix-extension/blob/a0e8129cf370b17a2b2505ba772cd65e4e1242b0/src/extensionConsole/pages/mods/Status.tsx#L91-L91
- https://github.com/pixiebrix/pixiebrix-extension/blob/a0e8129cf370b17a2b2505ba772cd65e4e1242b0/src/extensionConsole/pages/mods/ModsPageActions.tsx#L167-L167

**Comment by mnholtz** [comment]
Interpreting defintion of done from discussion here:
**Acceptance Criteria**
1. Mods activated via deployment should have "Active" status for pinned mod version
- Given a user views the mods screen after creating a deployment and pinning it to an older version,
- When the user sees the mod,
- Then the screen should not show an "Update" button for the pinned mod version.

2. Mods activated via deployment key should have "Active" status for pinned mod version
- Given a user has deployed a mod using a deployment key,
- When the user views the mods screen,
- Then the screen should display "Active" as the status with the pinned mod version.

3. Accessibility of Upgrading
- Given a user has permission to reactivate a deployment,
- When they view the mod in the mods screen,
- Then they should be able to upgrade to the latest version using the 3-dot menu

4. Update Button for Personal Deployments

- Given a user has created a personal deployment,
- When they view the deployed mod in the mods screen,
- Then the screen should show the "Update" button if there is a newer version available.

5. Correct "Update" Restrictions for Organizations

- Given an organization has applied UI restrictions via https://github.com/pixiebrix/pixiebrix-extension/blob/a0e8129cf370b17a2b2505ba772cd65e4e1242b0/src/auth/featureFlags.ts#L156-L156,
- When a user views the mods screen,
- Then the option to "Update" or "Reactivate" should not be displayed to the user in any situation

**Comment by mnholtz** [comment]
@twschiller is this bullet correct?

> Update Button for Personal Deployments
Given a user has created a personal deployment,
When they view the deployed mod in the mods screen,
Then the screen should show the "Update" button (instead of the "Active" status) if there is a newer version available.

**Comment by mnholtz** [comment]
> Update Button for Personal Deployments
Given a user has created a personal deployment,
When they view the deployed mod in the mods screen,
Then the screen should show the "Update" button (instead of the "Active" status) if there is a newer version available.

Per slack conversation, acceptance criteria #4 will omit subsequent clicking behavior to "...[click update] and then the new version would be what’s sync’d across their devices" as it is out of scope. We'll be creating a follow-up ticket to implement this behavior.
