### ISSUE TITLE
Change sidebar header style

### ISSUE THREAD

**Issue by fregante** [pixiebrix/pixiebrix-extension#912]
The new chevrons look great! But they make the blue button look even more out of place. I think it'd make sense to drop it, especially because "Extension" is ambiguous in PixieBrix.

## Before

<img width="403" alt="Screen Shot 8" src="https://user-images.githubusercontent.com/1402241/126879470-a4c94e77-733f-4731-9d03-eaa93e4a495e.png">

## After

Mockup

<img width="404" alt="Screen Shot 9" src="https://user-images.githubusercontent.com/1402241/126879471-a1fb1df5-3a4e-4999-b87f-28e058d9da79.png">

**Comment by twschiller** [comment]
I agree that "Extension" is ambiguous. I think the principles here are:

- That button will potentially be how a new user opens the options page for the 1-2 time, so there needs to be enough labelling/semantic information to make it obvious what it does
- Needs to be obvious that it's clickable

My proposal is a "Settings" button with a label + [cog](https://fontawesome.com/v5.15/icons/cog?style=solid) icon

The external link icon in the Mockup conveys that it opens a new window/tab, but it doesn't convey "why"/what will be opened when clicked

**Comment by fregante** [comment]
Agreed on all counts. I think:

- use "Options" because that's how it's called across the extension
- keep the button backgroundless

Example:

<img width="403" alt="Screen Shot" src="https://user-images.githubusercontent.com/1402241/127267549-7a62fcaa-7137-4ce2-90fe-adb880311a46.png">

**Comment by twschiller** [comment]
> keep the button backgroundless

If we keep it backgroundless, we should add a hover effect (and change the cursor to point) like we have for the collapse button on the left
