### ISSUE TITLE
Switch ErrorBanner to dismissible modal

### ISSUE THREAD

**Issue by twschiller** [pixiebrix/pixiebrix-extension#915]
**Context**
- The PixieBrix side panel can't be shown on special/protected pages because Chrome/FF doesn't allow content scripts to run on certain pages, e.g., the Chrome Web Store, internal browser pages, etc.
- If the user clicks the PixieBrix toolbar button, we open the options page to a special URL that cases an Error Banner to be displayed: http://github.com/pixiebrix/pixiebrix-extension/blob/abb45b475fa5c240d1d4ec6591df5920d1625389/src/layout/ErrorBanner.tsx#L25-L25
- The user has no way to dismiss the banner, and refreshing the options page doesn't remove it because the error code is in the URL

**Implementation Sketch**
- Modify `ErrorBanner` to show a `Modal` instead of a banner (see react-bootstrap documentation for Modal, or search for uses of Modal in our codebase)
- When the user dismisses the modal, remove the error from the search param from the URL so it doesn't appear on refresh/navigation to other extension pages

**Comment by fregante** [comment]
Should this be implemented as a regular alert/popup instead since now we have the local code for that?

**Comment by twschiller** [comment]
I was thinking we'd have it still open up a full-sized tab with the options page. When I've seen this error live, it's because people are trying to get to the options page from the CWS or another extension page

**Comment by fregante** [comment]
> people are trying to get to the options page from the CWS or another extension page

That's actually how I use the button. 😁 I click it to open the options page and ignore the error

**Comment by mnholtz** [comment]
Closed by #940
