### ISSUE TITLE
High incidence of IndexedDB errors

### ISSUE THREAD

**Issue by twschiller** [pixiebrix/pixiebrix-extension#9169]
Context
---
- https://www.notion.so/pixiebrix/IDB-Error-Investigation-2024-09-17-10443b21a25380e78cf6d7ad1273ad24?pvs=4
- https://pixiebrix.zendesk.com/agent/tickets/697
- https://pixiebrix.zendesk.com/agent/tickets/698
- Client is using a Citrix environment

Information Gathering
---
- Errors in Datadog
  - [Failed to execute 'transaction' on 'IDBDatabase': One of the specified object stores was not found.](https://app.datadoghq.com/logs/error-tracking?fromUser=true&issueId=ea6e5fbc-42b1-11ef-81a4-da7ad0900002)
  - [Failed to read large IndexedDB value](https://app.datadoghq.com/logs/error-tracking?fromUser=true&issueId=34cc3404-d81c-11ee-8a4e-da7ad0900002)
    - [Upcoming Chromium Feature: Improved error reporting in IndexedDB for large value read failures](https://chromestatus.com/feature/5140210640486400)
  - [Internal error opening backing store for indexedDB.open.](https://app.datadoghq.com/logs/error-tracking?fromUser=true&issueId=dcfaa910-badc-11ee-a93b-da7ad0900002)
  - [IDB Unresponsive](https://app.datadoghq.com/logs/error-tracking?fromUser=true&issueId=c622a160-e00d-11ee-bd85-da7ad0900002)
- Confirm if they're deploying extension via the image, or via a force install policy: https://docs.keeper.io/en/v/enterprise-guide/deploying-keeper-to-end-users/keeper-fill/virtual-machine-persistence#chrome-locations

Resources
---
- Chromium Issue Tracker: https://issues.chromium.org/issues?q=indexeddb
- Chrome IndexedDB debugging resources:
  - chrome://indexeddb-internals

Proposed Mitigations
---

- [x] Change logging for triggerStarterBrick success from `info` to `debug`
- [x] Feature flag to stop appending log entries
- [x] Set [IDBTransaction durability](https://developer.mozilla.org/en-US/docs/Web/API/IDBTransaction/durability) to `"relaxed"`
- [x] Add timeout to stop `sweepLogs` early if it's long-running
- [x] Add timeout to stop `openLoggingDB` in case it's hanging
- [ ] Determine when [DataError: Failed to read large IndexedDB](https://app.datadoghq.com/logs/error-tracking?fromUser=true&issueId=34cc3404-d81c-11ee-8a4e-da7ad0900002&source=all) is thrown and properly handle
- [ ] Add application telemetry to various edge cases:
    - [ ] Add catch blocks to all `try, finally` blocks, report to app telemetry, and rethrow the error
    - [ ] When `upgrade`, `blocking`, `blocked`, and `terminated` are called by `openDB`, report the event along with the args they were called with

**Comment by fungairino** [comment]
More details on behavior captured in this slack channel:
https://pixiebrix.slack.com/archives/C07MJ3LJ66B/p1726672632378699

**Comment by fungairino** [comment]
In investigating this issue I found a loop I was suspecting:

reportUncaughtErrors.ts -> reportError -> recordError -> appendEntry

so if appendEntry throws an uncaught error for whatever reason it will enter a loop of attempting to write to idb, and reporting and rewriting to idb

**Comment by fungairino** [comment]
Closing as we have done what we can to spike on this issue for now. We will open follow ups based on new logs that come in. Ex: 
https://app.datadoghq.com/logs/error-tracking/issue/b70f12d6-79b8-11ef-95e3-da7ad0900002?query=service%3Apixiebrix-browser-extension%20version%3A2.1.2&fromUser=false&refresh_mode=sliding&from_ts=1727017447690&to_ts=1727103830468&live=true
