### ISSUE TITLE
[Spike] Extension Runtime Paywall

### ISSUE THREAD

**Issue by grahamlangford** [pixiebrix/pixiebrix-extension#9175]
## Phase Spec

- https://www.notion.so/pixiebrix/Phase-3-Extension-Runtime-Paywall-e46ad4f7e84f482b9b1e2c195a4eac68

## Acceptance Criteria

- [x] Slices specified
- [x] Approval Matrix signed off
- [x] Slices converted to issues
- [x] Issues added to `Phase 3: Extenion Paywall`
- [x] Tech Lead + Pasha notified for prioritization

**Comment by mnholtz** [comment]
It looks like there is only one trivial slice for this phase, ticket here: https://github.com/pixiebrix/pixiebrix-extension/issues/9196

@grahamlangford spec is ready for review
