### ISSUE TITLE
[Spike] how to best open Sidepanel on Welcome Page

### ISSUE THREAD

**Issue by Pashaminkovsky** [pixiebrix/pixiebrix-extension#9178]
Context:
We want to improve the "Visit Welcome Page" -> "Open Side Panel" rate.

In an ideal world, the Sidepanel would open automatically as soon as the user landed on the Welcome Page. Given this isn't feasible, what is next best thing?

Potential ideas:
1. host the welcome page on app.pixiebrix.com and structure a "Launch PixieBrix" button as a link (e.g. app.pixiebrix.com/welcome?show_sidebar=true)

We are currently showing instructions and a gif which instruct users to click the extensions puzzle piece in the browser: https://www.pixiebrix.com/welcome

**Comment by twschiller** [comment]
@Pashaminkovsky assigning to you — I'm assuming this isn't a priority anymore?

**Comment by Pashaminkovsky** [comment]
Yeah we can punt on this until we see prioritize the onboarding flow again.
