### ISSUE TITLE
Remove logo in Sidebar for a subset of users

### ISSUE THREAD

**Issue by Pashaminkovsky** [pixiebrix/pixiebrix-extension#9206]
A customer has a request to remove branding in the sidebar for a subset of customers. They are looking to have a path forward before EoW (9/27).

Details here: https://www.notion.so/pixiebrix/Remove-Sidebar-logo-for-some-users-10c43b21a253804eb207c3800a6654fd

cc @twschiller @mnholtz

**Comment by twschiller** [comment]
Issue for engineering: https://github.com/pixiebrix/pixiebrix-extension/issues/9222
