### ISSUE TITLE
Deployed mod can't find integration configuration when configuration switched

### ISSUE THREAD

**Issue by twschiller** [pixiebrix/pixiebrix-extension#9212]
## Describe the bug

- Triage note: issue at customer seems to have resolved itself
- https://pixiebrix.slack.com/archives/C0671QASFMZ/p1727450510849549
- I'm 95% sure the app issue is the problem, but there's some extension improvements we can make to help address: https://github.com/pixiebrix/pixiebrix-app/issues/5809

## To Reproduce

NOTE: I've been unable to reproduce locally. But haven't tried with an OAuth2 PKCE integration. See Slack for email addresses of impacted users. (Customer dev things the issue might have resolved itself. It also hasn't shown up in error telemetry for 1 day+: https://app.pixiebrix.com/teams/ec096a08-58f3-4efd-b2ab-b153bd903533/deployments/434b2ffb-c379-423a-966d-32832c53199e?tabKey=errors)

1. Assign a deployment to restricted users with a pushdown OAuth2 PKCE integration
2. Create a new configuration for the integration
3. Switch the deployment to use the new configuration

## Actual behavior

When running sidebar, user sees error that integration configuration id corresponding to the new configuration can't be found

## Expected behavior

User is able to use the mod after the deployment updates

## Discussion

- I'm 95% sure the app issue is the problem, but there's some extension improvements we can make to help address: https://github.com/pixiebrix/pixiebrix-app/issues/5809
- The background deployment update refreshes the configuration locator before updating deployments: https://github.com/pixiebrix/pixiebrix-extension/blob/625c84f071b0f089c7f1f3f5adc08002d4d259e6/src/background/deploymentUpdater.ts#L519-L519
- If the network request to retrieve configurations was failing, would we be able to see it in Datadog? https://github.com/pixiebrix/pixiebrix-extension/pull/9201 would only impact IDB

## Mitigations

Potential mitigations

- Verify the user is in a group with permissions to access the configuration
- Pause/Unpause the deployment in the Admin Console to force extension deployment updater to try fetching configurations and re-activating the mod
- Refresh the Extension Console to force extension to refetch local integration configurations
- Restart the browser profile. On restart, the extension will refetch local integration configurations

## Screenshots/Loom

- See linked Slack for screenshots of what occurs
- Deployment: https://app.pixiebrix.com/teams/ec096a08-58f3-4efd-b2ab-b153bd903533/deployments/434b2ffb-c379-423a-966d-32832c53199e

## Desktop (please complete the following information):

- OS: Windows
- Browser: Chrome
- Extension Version: 2.1.2

## Next Steps

- In background deployment update code, report an error to Datadog if the deployment references an unknown integration configuration (i.e., the user doesn't have access to it)
  - What do we want the behavior to be? Stop deployment activation? Or report but activate the deployment knowing the mod will error at runtime?
  - @Pashaminkovsky I think we should automatically open the Extension Console
- In the Extension Console deployment update code:
  - Show an error if a deployment can't be activated because it references an unknown integration configuration

**Comment by mnholtz** [comment]
Fixed by https://github.com/pixiebrix/pixiebrix-app/pull/5842
