### ISSUE TITLE
Add Chrome Extension managed storage policy for hiding sidebar logo

### ISSUE THREAD

**Issue by mnholtz** [pixiebrix/pixiebrix-extension#9222]
## User Story

See context on discussion document here: https://www.notion.so/pixiebrix/Remove-Sidebar-logo-for-some-users-10c43b21a253804eb207c3800a6654fd

## Motivation

We have an enterprise user who has legal requirements to hide the sidebar logo for certain users within a PixieBrix team, but retain the sidebar logo for others.

## Acceptance Criteria

Scenario: Hidden sidebar logo per extension policy

- Given the e.g. `hideSidebarLogo` policy is set on a machine in managed storage,
- When the user opens the PixieBrix sidebar
- Then the sidebar logo should be hidden

## Implementation Sketch

- Add new entry to the [managed storage schema](https://github.com/pixiebrix/pixiebrix-extension/blob/0e09e6ceeebb72624849ed8e7cb0f4211e7ddc1a/static/managedStorageSchema.json#L21-L21)
- Leverage utility in [managedStorage.ts](https://github.com/pixiebrix/pixiebrix-extension/blob/0e09e6ceeebb72624849ed8e7cb0f4211e7ddc1a/src/store/enterprise/managedStorage.ts#L277-L277) to modify the `showSidebarLogo` value returned by [useTheme](https://github.com/pixiebrix/pixiebrix-extension/blob/0e09e6ceeebb72624849ed8e7cb0f4211e7ddc1a/src/hooks/useTheme.ts#L73-L73) (make sure to accommodate hiding the sidebar logo by default while managed storage is loading)

**Comment by mnholtz** [comment]
Yes, a user story would be much appreciated

**Comment by Pashaminkovsky** [comment]
That specific requirement we're clarifying w/ TP right now, so we'll have an answer when they respond. There could be a scenario where they say it's fine for all developers to have the logo hidden, in which case we don't have to introduce more complexity w/ a toggle.
