### ISSUE TITLE
CreateModModal causes multiple DOM elements with same id

### ISSUE THREAD

**Issue by twschiller** [pixiebrix/pixiebrix-extension#9238]
Context
---
- Certain modals, e.g., the `CreateModModal` can cause multiple elements with the same id to be on the Page. That's because there are scenarios the form in the modal has fields with the same name as the being displayed in the main content
- That results in technically invalid HTML, and breaks `getByLabel` and label-based logic in Playwright

Discussion
---
- An option explored was to add a random UUID to control ids: https://github.com/pixiebrix/pixiebrix-extension/blob/cc4caf3b12d9d25b3d9ffa95e33d32dd53a2777a/src/components/form/FieldTemplate.tsx#L211-L211. However, that, by itself, causes Jest snapshot tests to break

Related Code
---
- https://github.com/pixiebrix/pixiebrix-extension/blob/cc4caf3b12d9d25b3d9ffa95e33d32dd53a2777a/src/pageEditor/modListingPanel/modals/CreateModModal.tsx#L299-L299

**Comment by grahamlangford** [comment]
See https://github.com/pixiebrix/pixiebrix-extension/pull/9350 for an example of resolving this issue by giving more specific ids to fields

**Comment by grahamlangford** [comment]
Since it's just the create mod modal, I think we're safe to close this now @twschiller
