### ISSUE TITLE
"Illegal invocation" error volume is blowing up Datadog cost

### ISSUE THREAD

**Issue by johnnymetz** [pixiebrix/pixiebrix-extension#9269]
## Describe the bug

Datadog Error Tracking item: https://app.datadoghq.com/logs/error-tracking/issue/b79d14fc-776d-11ef-8147-da7ad0900002

See the error occurrence chart:

![Screenshot 2024-10-10 at 1 35 05 PM](https://github.com/user-attachments/assets/124a6216-fc92-4b04-86f2-bf882e6f0d38)

This is blowing up our Datadog bill. Here are our spend over the last few months for comparison:
- July: $4.9k
- August: $4.8k
- September: $8.5k
- October (through only 10 days): $6.1k

## Additional context

- The error tracking item doesn't provide any helpful context about what is causing this error or where in the code it's happening
- Most of the volume is coming from Extension version 2.1.2 (see Datadog link above)

![Screenshot 2024-10-10 at 1 47 06 PM](https://github.com/user-attachments/assets/8486085b-98a4-461b-afb4-0248abfa413e)

- According to the occurrence chart above, volume has come way down over the last few days. Perhaps the bug was fixed in a newer release?
- We need to set up Datadog cost monitors to alert us when our monthly cost is spiking. I found this by checking the cost on a limb

**Comment by twschiller** [comment]
@johnnymetz original issue here: https://github.com/pixiebrix/pixiebrix-extension/issues/9210
