### ISSUE TITLE
[Needs Eng Slicing] Support Image Upload and Text Formatting in Mods

### ISSUE THREAD

**Issue by Pashaminkovsky** [pixiebrix/pixiebrix-extension#9273]
We want to enable users to natively upload images into mods (as opposed to host them elsewhere and upload a url) and to use a rich text editor to format text/images.

Relevant docs and discussions:
1. [Image Upload and Rich Text Editor 1 Pager](https://www.notion.so/pixiebrix/Image-Upload-and-Rich-Text-Editor-11a43b21a253802198f1c90696f5ec53?showMoveTo=true&saveParent=true)
2. [Enable Image Content Storage](https://www.notion.so/pixiebrix/Enable-Image-Content-Storage-in-Mods-be0bbd0f8b4c470aa629144fc8b3ae6b#939b96fff99b47529a94446f553b89d5)
3. [Support Rich Text Formatting](https://www.notion.so/pixiebrix/Support-Formatted-Text-Editing-Component-in-Form-Builder-Forms-0c2733eb789044f096f0bf992ce9eeb2)

**Comment by grahamlangford** [comment]
Blocked until we've finalized the product requirements

**Comment by grahamlangford** [comment]
Closing due to superseding issues
