### ISSUE TITLE
Fix Pre-release Browser workflow

### ISSUE THREAD

**Issue by mnholtz** [pixiebrix/pixiebrix-extension#9283]
## Describe the bug

Follow-up of https://github.com/pixiebrix/pixiebrix-extension/issues/9193

Our Pre-release Browser workflow is failing consistently despite improvements to test flakiness in CI. https://github.com/pixiebrix/pixiebrix-extension/actions/workflows/e2e-test-pre-release-browsers.yml

**Comment by grahamlangford** [comment]
Suggestion: if this is really caused by running so many tests simultaneously, can we eliminate the sharding so we only run 5 at a time? We don't need to worry about total runtime since this is a separate nightly run

**Comment by fungairino** [comment]
Related flakiness fixes: https://github.com/pixiebrix/pixiebrix-extension/pull/9288
