### ISSUE TITLE
Simplify Marketplace Activation Wizard UX

### ISSUE THREAD

**Issue by twschiller** [pixiebrix/pixiebrix-extension#931]
**Context**
- The Marketplace Activation Wizard is used to configure blueprints activated from the marketplace. The user can configure which bricks, to include, which services to configure, grant necessary permissions, etc.
- In the future, we'll be creating a single-page activation screen for certain situations

**Implementation Sketch**
- Remove the  "Activate" from the final card body. It confuses uses to have multiple places to click. Make the final activate width larger. (Nice to have: can we have a glow/shine effect that makes it obvious it's the last step?)
- Show "+ Add Configuration" button if there are not configurations. If there are at least 1 configuration, show "+ Add Configuration" in the dropdown, not as a separate button
- If there's only one auth available, default to it even if it's not local
- Show single list of requested permissions in order: 1) non-origin permissions, 2) origin permissions sorted
- Remove permissions code for grouping permissions by origin
- Remove `distinctPermissions` method: http://github.com/pixiebrix/pixiebrix-extension/blob/f52a35bf39f57e215fd5e8cf961268f4f16ce268/src/utils/permissions.ts#L50-L50. (You can use `mergePermissions` instead)

**Out of Scope/Not Doing**
- For bricks that use the PixieBrix API, which is automatically supported, show a PixieBrix integration entry with credential "Automatic" instead of hiding it entirely

**References**
- Example of a custom select option: http://github.com/pixiebrix/pixiebrix-extension/blob/f52a35bf39f57e215fd5e8cf961268f4f16ce268/src/devTools/editor/fields/SelectorSelectorField.tsx#L45-L45
- Place where permissions are listed: http://github.com/pixiebrix/pixiebrix-extension/blob/f52a35bf39f57e215fd5e8cf961268f4f16ce268/src/options/pages/marketplace/ActivateBody.tsx#L198-L198

**Example of Permissions Display**

```js
[
    {origins: ["https://www.google.com/*"], permissions: ["clipboardWrite", "notifications"]},
    {origins: ["https://www.cnn.com/*"], permissions: []},
]
```

Permissions list:
- clipboardWrite
- notifications
- https://www.cnn.com/*
- https://www.google.com/*

**Comment by mnholtz** [comment]
@twschiller I noticed that the UI (options list) does not update when new configurations are added (the entire page has to be refreshed). It looks like that logic [might already be implemented here](https://github.com/pixiebrix/pixiebrix-extension/blob/6205e9f55169879f976bd4c76f3a1abcc6673573/src/options/pages/marketplace/ServicesBody.tsx#L78-L78)? If so, this might be a bug. Is this out of scope to handle here?
