### ISSUE TITLE
Deleting a mod component from a mod does not mark the mod as dirty

### ISSUE THREAD

**Issue by Pashaminkovsky** [pixiebrix/pixiebrix-extension#9315]
Extension Extension Version: 2.1.5

Steps to Reproduce:
GIVEN I am viewing the Page Editor
AND I expand a mod with multiple mod components
WHEN I delete one of the mod components
AND make no other changes
Actual
THEN the save mod button is disabled
AND I am unable to save the mod
Expected
THEN the save mod button is enabled
AND I am able to save the mod

[Slack Thread](https://pixiebrix.slack.com/archives/C0436P48QHY/p1729185382535679)

**Comment by twschiller** [comment]
Related: https://github.com/pixiebrix/pixiebrix-extension/issues/9313
