### ISSUE TITLE
[Spike] Phase 1: Implement Rich Text Editor

### ISSUE THREAD

**Issue by grahamlangford** [pixiebrix/pixiebrix-extension#9317]
## Phase Spec

- [Phase 1: Implement Rich Text Editor](https://www.notion.so/pixiebrix/Phase-1-Implement-Rich-Text-Editor-f74aea6b845847c0ad25f81d8236da3c)

## Acceptance Criteria

- [x] Slices specified
- [x] Approval Matrix signed off
- [x] Slices converted to issues
- [x] Issues added to `Phase 1: Implement Rich Text Editor`
- [x] Tech Lead and PM notified for prioritization

**Comment by grahamlangford** [comment]
Supersedes https://github.com/pixiebrix/pixiebrix-extension/issues/9273

**Comment by mnholtz** [comment]
See epic here for final slicing: https://github.com/pixiebrix/pixiebrix-extension/issues#workspaces/feature-board-648b6be80bad0700122cb282/epics/Z2lkOi8vcmFwdG9yL1plbmh1YkVwaWMvMjE3MzM0
