### ISSUE TITLE
RFC: useUserAction hook to simplify error handling of click handlers

### ISSUE THREAD

**Issue by twschiller** [pixiebrix/pixiebrix-extension#932]
**Context**
- We use `useCallback` to produce handlers for buttons (e.g., delete, etc.)
- Each `useCallback` use has to implement its own error handlers for all operations.  Otherwise, if there's an exception it will be logged to Rollbar, but the user won't get any visual feedback that the operation failed
- The introduction of `useNotifications` helped standardize success/error notifications and telemetry, but didn't solve the problem of top-level error handlers in callbacks

**Considerations**
- Alternative: add a root level error handler on the page that adds the toast to extension pages (Benefits: doesn't require any code changes. Drawbacks: could be noisy/confusing, if operation was not user initiated)
- This will be less configurable though as we could add an options argument to useActionCallback
- The caller can still do it's own error handling to offer improved error messages
- Allow the callback to throw a `CancelError` so that the error message doesn't show?
- Allow the caller to pass in a `cleanup` method that's called part of a finally clause?

```js
function useUserAction(callback, options, deps) {
	const {notify} = useNotifications();
    const {event, successMessage, errorMessage="An error occurred"} = options;
	
	return useCallback(async (...args) => {
		try {
			const rv = await callback(...args);
            if (successMessage) {
              notify.success(successMessage, {event});
            } else if (event) {
              reportEvent(event)
            } 
 		} catch(error) {
            if (error instanceof CancelError) {
              return;
            }

			const detail = getErrorMessage(error);
			notify.error(`${errorMessage}: ${detail}`, {
				error,
			}) 		
		}
	}, [deps, notify, options]);
} 

```

**Comment by fregante** [comment]
Would error boundaries also work? https://reactjs.org/docs/error-boundaries.html

**Comment by twschiller** [comment]
> Would error boundaries also work?

ErrorBoundaries only catch errors that occur during renders. This proposal is for callbacks/events, which aren't caught by error boundaries

**Comment by twschiller** [comment]
This is implemented in the app now: http://github.com/pixiebrix/pixiebrix-app/blob/2213f3606dd2c5670d8d123eee121ca17a30d1b8/pixiebrix-app/src/hooks/useUserAction.ts#L15-L15

I will be moving over to the extension so both can use
