### ISSUE TITLE
Page Editor: Missing sidepanel tab title

### ISSUE THREAD

**Issue by grahamlangford** [pixiebrix/pixiebrix-extension#9381]
## Describe the bug

When I have a sidepanel mod component, the sidebar is open, and I select the mod containing that sidepanel mod component or another mod component in that mod, then I do not see the tab title in the sidebar

## To Reproduce

1. Create or install a mod with a side panel mod component
2. Open the sidebar
3. Open the Page Editor
4. Select the mod with the side panel mod component (but do not select the sidepanel mod component)

## Actual behavior

The tab title is not visible

## Expected behavior

The tab title is visible

## Screenshots/Loom

https://pixiebrix.slack.com/archives/C023KL47XV4/p1730223727362799

## Desktop (please complete the following information):

- Extension Version: 1.2.7-alpha.0 (main)

**Comment by twschiller** [comment]
Related code: 
- https://github.com/pixiebrix/pixiebrix-extension/blob/90b898dfdf4ce3bb438d6b2b626c5042207b5aa1/src/starterBricks/sidebar/sidebarStarterBrick.ts#L366-L366
- https://github.com/pixiebrix/pixiebrix-extension/blob/90b898dfdf4ce3bb438d6b2b626c5042207b5aa1/src/contentScript/pageEditor/draft/updateDraftModComponent.ts#L84-L84
