### ISSUE TITLE
[Spike] Image Upload in Rich Text Editor

### ISSUE THREAD

**Issue by Pashaminkovsky** [pixiebrix/pixiebrix-extension#9422]
## Specs

Image Upload epic: https://app.zenhub.com/workspaces/feature-board-648b6be80bad0700122cb282/epics/Z2lkOi8vcmFwdG9yL1plbmh1YkVwaWMvMjE3MzM1

Rich Text Editor Phase 2 epic: https://app.zenhub.com/workspaces/feature-board-648b6be80bad0700122cb282/epics/Z2lkOi8vcmFwdG9yL1plbmh1YkVwaWMvMjE4Nzc5

Notion doc: https://www.notion.so/pixiebrix/Phase-2-Implement-Image-Upload-in-Rich-Text-Editor-12643b21a25380eb9508e2f8419317ba

## Motivation
Introduce image upload functionality in the rich text editor.

## Acceptance Criteria

- [x] Specification doc in Notion
- [ ] Spike approved by Tech Lead and PM

**Comment by twschiller** [comment]
@Pashaminkovsky @mnholtz is this the spike to create the sketch? Or to implement? My assumption is we're getting upload in for 2.1.8

**Comment by grahamlangford** [comment]
> @Pashaminkovsky @mnholtz is this the spike to create the sketch? Or to implement? My assumption is we're getting upload in for 2.1.8

See Acceptance Criteria -- this is for the implementation sketch. We're going to move quickly on the sketch, but we need to be certain the requirements are clear so that the implementation is what we actually want

**Comment by mnholtz** [comment]
@grahamlangford @Pashaminkovsky Moving quickly on this so not awaiting 100% formal approval; @twschiller gave the spec a look and I created related GH issues. Regardless, take a look at the spec when you get the chance
