### ISSUE TITLE
Mod Commit Messages

### ISSUE THREAD

**Issue by Pashaminkovsky** [pixiebrix/pixiebrix-extension#9433]
## User Story
As a mod developer, I want an optional field in which to write a commit message when I save a mod in the Page Editor. If I write a commit message, the version number of the mod will be incremented.

As a mod developer, I want to see the commit message for a mod in the following places:
1. Extention Console: Workshop > Edit Package > History
2. Admin Console: Deployments
3. Page Editor (last 3 commit messages and associated timestamps)

## Motivation
"It's impossible to collaborate with someone when building mods and updating versions without commit messages (even going back to old mods yourself hard to keep track of updates)"

This would accelerate starter mod development and help maintain sanity. This is both an app change and an extension change.

## Acceptance Criteria
Scenarios:
1. Saving a mod in the page editor.
- Given a mod is in a dirty state in the page editor
- When I click save
- Then I should have an optional text box to input a commit message and increment the version number.

2. Viewing commit messages in Workshop
- Given I saved a mod with a commit message
- When I visit the Workshop History to diff versions of a mod
- Then the associated commit message (if any) should appear above each panel.

3. Viewing commit messages in Deployments
- Given I saved a mod with a commit message
- When I visit the Deployments table
- Then the associated commit message (if any) should be visible in a column next to "Version"

4. Viewing commit messages in Deployment Details
- Given I saved a mod with a commit message
- When I visit the Deployments Detail View
- Then the associated commit message (if any) should be visible in field under "Version"

5. Viewing commit messages in the Page Editor
- Given I saved a mod with a commit message
- When I select the mod in the Page Editor
- Then the previous 3 commit messages (if any) and their Versions should be visible in the Mod Metadata

Designs: we can go with whatever is the lowest eng lift; no need to overthink it. As long as the data exists in a relatively usable way that's sufficient. 
![image (8)](https://github.com/user-attachments/assets/7b8632e8-750b-475b-91fd-de489951e747)

Slack discussion: https://pixiebrix.slack.com/archives/C042CA15AKS/p1730934129875419

**Comment by grahamlangford** [comment]
@Pashaminkovsky we should convert this to a product spec. I know I said this wouldn't be a huge effort, but @twschiller brought up a good point I didn't think about. We might not need to worry about that, but we should follow the normal PRD/ERD process to de-risk

**Comment by Pashaminkovsky** [comment]
@grahamlangford sounds good I'll have that by eod

**Comment by twschiller** [comment]
FWIW, my vote is to just add the committer/message to the deprecated serializer. The volume on the endpoint is/will continue to be very low

**Comment by grahamlangford** [comment]
> FWIW, my vote is to just add the committer/message to the deprecated serializer. The volume on the versions endpoint is/will continue to be very low

Either that or a separate version history endpoint would be my vote. Do we call the versions endpoint in the Page Editor?

**Comment by twschiller** [comment]
> Either that or a separate version history endpoint would be my vote.

See the discussion in https://github.com/pixiebrix/pixiebrix-extension/issues/7692 and it's corresponding app issue

>  Do we call the versions endpoint in the Page Editor?

Not currently, but I dropped it in here to get the ball rolling on Version History pane (will be trivial to swap out): https://github.com/pixiebrix/pixiebrix-extension/pull/9439

**Comment by Pashaminkovsky** [comment]
@grahamlangford I defer to you on the best way to phase / slice the scope based on the acceptance criteria https://www.notion.so/pixiebrix/Commit-Messages-for-Mods-13843b21a25380fc879ecb625810c5c1
