### ISSUE TITLE
Run knip script from the root project package.json

### ISSUE THREAD

**Issue by fungairino** [pixiebrix/pixiebrix-extension#9457]
With the recent monorepo npm workspace refactor, the dead code script using knip was broken. To fix it, we need to move knip so that it runs from the root context rather than the workspace package.json. This may also require some refactoring for the tsconfig

See:
https://knip.dev/guides/handling-issues#missing-binaries
https://github.com/pixiebrix/pixiebrix-extension/blob/7eb722f2a62c567b8c94843fe58e30e71aa2fa14/applications/browser-extension/package.json#L26

**Comment by twschiller** [comment]
Docs page: https://knip.dev/features/monorepos-and-workspaces
