### ISSUE TITLE
Refactor `process.env` usage to enable single JS bundle for pixiebrix-app

### ISSUE THREAD

**Issue by twschiller** [pixiebrix/pixiebrix-extension#946]
**Context**

- For the extension, we have a single JS build across all browsers
- For the web app, a corollary is that we want to use the same JS bundle across all environments (staging, production). This will enable continuous deployment (CD) with staging as a quality gate. 
- The web app depends on pixiebrix-extension. There are some modules/components we're like to re-use in the app

**Implementation Sketch**
- Locate modules referenced by PixieBrix app: http://github.com/pixiebrix/pixiebrix-extension/blob/a9d371f086aae69c5e2aac6d45bcee1abff60cc8/src/layout/Banner.tsx#L29-L29
- Eliminate the use of `process.env` in those modules. For example, we might introduce a globals.ts file in pixiebrix-extension that provides a getGlobals method. Then in pixiebrix-app we can use webpack to alias to it's own globals.ts file
- Perform a build of the front-end and make sure none the hard-coded environment values are being included

**Problematic Values**
- SERVICE_URL
- CHROME_EXTENSION_ID
- ENVIRONMENT
- VERSION_NAME (because it depends on ENVIRONMENT)

**OK to Use `process.env`**
Environment variables that are pinned to the code (not the environment) are OK to use directly:
- `NODE_ENV` can be kept as is, b/c there's still differences between development/production builds
- `NPM_PACKAGE_VERSION`
- `SOURCE_VERSION`

**Reference**
- Corresponding app issue: https://github.com/pixiebrix/pixiebrix-app/issues/259
- How the front-end bundle gets the environment variables from the backend: http://github.com/pixiebrix/pixiebrix-app/blob/2b423999fccddf3d48bf58a0bd47b3381ce92549/pixiebrix-app/src/globals.ts#L3-L3

**Comment by fregante** [comment]
To make sure I understand correctly: the extension bundle will still have those values hardcoded, but the app will have dynamic values that depend on the hostname, I suppose. Is that correct?

**Comment by fregante** [comment]
This is a webpack problem and not a code problem. Our webpack configuration is set to hardcode these values but our intention is to have them dynamic. 

https://github.com/pixiebrix/pixiebrix-app/blob/c72784e2e764f77f91fa966fff9837c7dc8b695f/pixiebrix-app/webpack/webpack.prod.js#L80-L83

The solution is to _not_ hardcode the values in the webpack configuration and instead _redirect_ them to use the DOM. `process.env -> document.body`

PR coming in the app repo

**Comment by twschiller** [comment]
> To make sure I understand correctly: the extension bundle will still have those values hardcoded, but the app will have dynamic values that depend on the hostname, I suppose. Is that correct?

That's correct. The gotcha is that there's some shared code where the app needs to have it dynamic based on the hostname, but that it will be static in the extension
