### ISSUE TITLE
Page editor freezes on slow API requests when rendering side panel

### ISSUE THREAD

**Issue by twschiller** [pixiebrix/pixiebrix-extension#954]
**Steps to Reproduce**
- Add a side panel via the page editor
- Add a slow API call
- Click "render". While the API is being called, you can't perform any work in the page editor

**Comment by fregante** [comment]
It looks like this was resolved by the new editor 

https://user-images.githubusercontent.com/1402241/152369978-a861ec2e-da6e-4084-a866-ef29a68a26a8.mov
