### ISSUE TITLE
External/app communication broken in Firefox due to `SET_EXTENSION_AUTH`

### ISSUE THREAD

**Issue by fregante** [pixiebrix/pixiebrix-extension#958]
1. Install extension in Firefox
2. Follow login process
3. End up on https://app.pixiebrix.com/ or https://app.pixiebrix.com/?install=1
4. See "Successfully linked extension to your PixieBrix account" notification
5. Click "Open Browser Extension" button

The messages are ignored due to a `_reload` call happening in `SET_EXTENSION_AUTH`. If I drop that call, the buttons work. Is this call necessary?

I thought this would be fixed by https://github.com/pixiebrix/pixiebrix-app/issues/377, but that would still depend on a working contentScript-background connection.

**Comment by twschiller** [comment]
I'm not sure if it's required or now. IIRC we're reloading the background script so it gets the updated information after we store them in local storage:

- http://github.com/pixiebrix/pixiebrix-extension/blob/2b24f85e6e03bcf438c69622fb60a9a1e7b41394/src/auth/token.ts#L97-L97

However, if I look for all uses of `getExtensionToken()` it's always being retrieved at the time of the request and not being stored anywhere

I can carve out some time today to dig more into whether or not removing the refresh might cause problems

An alternative might be to  have the background page listen for changes to `STORAGE_EXTENSION_KEY` in local storage. However, I'm 1) not sure that's necessary, 2) not sure what we've update based on that unless I can track down if it's necessary in the first place

**Comment by twschiller** [comment]
The `_reload` is there for the extension to do a proper initialization once it gets the token from the server. 

That includes, for example:
- http://github.com/pixiebrix/pixiebrix-extension/blob/93a302ea17c72dc410fa0284357b8c0556b1d4f2/src/background/installer.ts#L83-L83
- http://github.com/pixiebrix/pixiebrix-extension/blob/93a302ea17c72dc410fa0284357b8c0556b1d4f2/src/background/locator.ts#L67-L67

To avoid the reload, we'd need need to refactor background.ts to be able to "re-initialize" itself on a signal (e.g., another message from the host page, or listening for the auth token in the storage to change)

**Comment by fregante** [comment]
Those 2 examples seem straightforward: have `SET_EXTENSION_AUTH` call `initTelemetry()` and `locator.refresh()` instead of `_reload()`. I'll probably leave this issue to you as you're more familiar with what's supposed to happen at reload.


> another message from the host page

We already have `SET_EXTENSION_AUTH` for this

> listening for the auth token in the storage to change

I like these reactive behaviors: _The environment changed; Update self,_ no need for further signals/messages. This is also the first suggested solution in https://github.com/pixiebrix/pixiebrix-extension/issues/812

**Comment by fregante** [comment]
Woot, https://github.com/pixiebrix/pixiebrix-extension/pull/1003 also fixed this! Feels like this has happened a few times: Fix something that bugs me and end up fixing some other "difficult bug" in the process.

In short, the reload kills the previous content script and that bug was preventing the new content script from being injected.
