### ISSUE TITLE
"Use existing..." button in page editor is confusing

### ISSUE THREAD

**Issue by twschiller** [pixiebrix/pixiebrix-extension#989]
**Context**
- When you add a menu item/panel/etc. the interface includes a button that say "Use existing (button)"
- The button refers to existing foundations, but it's easy to confuse that it means use an existing button on the page as a reference point

**Additional Considerations**
- Can we make it more visually obvious in the devtools page when the page is in insertion mode?

**Comment by BLoe** [comment]
Fixed via #1539
